(function () {
  "use strict";
  window.WEATHER_WATCH_LOCALES = {
    en: {
      loading: "Reading the sky log…", title: "Weather Watch", kicker: "A calm forecast puzzle", world: "Willow weather station", intro: "Read three sky signs, predict the next one, and open a safe shelter window for each animal.", start: "Read the first forecast", choose: "Choose a forecast", chapter: "Forecast notebook", round: "Forecast", prompt: "Which sign comes next?", rule1: "The two signs alternate.", rule2: "The first sign returns after two signs.", rule3: "The three signs cycle in order.", check: "Check forecast", reset: "Reset forecast", selected: "Next sign: {name}", selectPrompt: "Choose the next weather sign.", wrong: "Not quite — read the rhythm again and try another sign.", correct: "Correct! The shelter window is calm.", finished: "Forecast settled", resultTitle: "The shelter window is clear!", resultLevel: "One forecast is clear.", resultText: "{count} of 3 forecasts settled. Checks this visit: {checks}. Best: {best}.", next: "Next forecast", settings: "Settings", sound: "Sound", language: "Language", on: "On", off: "Off", close: "Close", back: "Back", best: "Best checks: {best}", shelter1: "Fern awning", shelter2: "Pond cave", shelter3: "Lantern grove", plan1: "Dawn meadow", plan2: "Rainy hollow", plan3: "Evening grove", hint1: "Sun · cloud · sun · ?", hint2: "Rain · cloud · cloud · ?", hint3: "Sun · rain · cloud · ?", signSun: "Sun", signCloud: "Cloud", signRain: "Rain", shelterOpen: "Shelter: {name}"
    },
    "zh-Hant": {
      loading: "正在讀取天空紀錄……", title: "天氣觀察站", kicker: "平靜的預報規律益智", world: "柳影氣象站", intro: "讀懂三個天空訊號，預測下一個變化，為每隻動物打開安全的避風時段。", start: "讀取第一份預報", choose: "選擇預報", chapter: "預報筆記", round: "預報", prompt: "下一個訊號是什麼？", rule1: "兩個訊號會交替出現。", rule2: "第一個訊號會隔兩個再回來。", rule3: "三個訊號依序循環。", check: "確認預報", reset: "重設預報", selected: "下一個訊號：{name}", selectPrompt: "選擇下一個天氣訊號。", wrong: "還差一點——再讀一次規律，換一個訊號試試。", correct: "答對了！避風時段很平靜。", finished: "預報穩定", resultTitle: "避風時段已確認！", resultLevel: "一份預報已確認。", resultText: "已確認 {count} / 3 份預報。本次嘗試：{checks} 次。最佳：{best}。", next: "下一份預報", settings: "設定", sound: "音效", language: "語言", on: "開", off: "關", close: "關閉", back: "返回", best: "最佳嘗試：{best}", shelter1: "蕨葉遮棚", shelter2: "池畔洞穴", shelter3: "燈籠林地", plan1: "黎明草地", plan2: "雨天窪地", plan3: "暮色林地", hint1: "晴 · 雲 · 晴 · ？", hint2: "雨 · 雲 · 雲 · ？", hint3: "晴 · 雨 · 雲 · ？", signSun: "晴", signCloud: "雲", signRain: "雨", shelterOpen: "避風處：{name}"
    }
  };
}());
