// Authored controls shared by the live Battle and static localized guide.
const rows = {
  en: ['Equipment', 'Battle paused — equip or upgrade at your own pace.', 'Back to battle', 'Dodge', 'Move', 'Chain', 'OVERDRIVE', 'Drag the left joystick to move; release to stop. WASD or arrow keys also work. Attacks fire automatically. Tap Dodge or press Shift to dash safely through danger (3-second cooldown). Tap Relic Pulse or press Space to knock enemies back. Open Equipment or press E to pause, equip and upgrade. Defeat five enemies within a chain to trigger 5 seconds of faster fire; each defeat extends the chain window to 6 seconds.'],
  'zh-Hant': ['裝備', '戰鬥已暫停，安心換裝與升級。', '返回戰鬥', '閃避', '移動', '連殺', '火力爆發', '拖曳左下搖桿移動，放開立即停止；電腦可用 WASD 或方向鍵。武器自動攻擊。點「閃避」或按 Shift 可短暫無敵衝刺，冷卻 3 秒；點「遺物脈衝」或按空白鍵可擊退敵人。點「裝備」或按 E 暫停戰鬥並換裝、升級。連續擊倒五個敵人可獲得 5 秒火力爆發；每次擊倒會把連殺時限延長至 6 秒。'],
  'zh-Hans': ['装备', '战斗已暂停，安心换装与升级。', '返回战斗', '闪避', '移动', '连杀', '火力爆发', '拖动左下摇杆移动，松开立即停止；电脑可用 WASD 或方向键。武器自动攻击。点“闪避”或按 Shift 可短暂无敌冲刺，冷却 3 秒；点“遗物脉冲”或按空格键可击退敌人。点“装备”或按 E 暂停战斗并换装、升级。连续击倒五个敌人可获得 5 秒火力爆发；每次击倒会把连杀时限延长至 6 秒。'],
  ja: ['装備', '戦闘停止中。ゆっくり装備変更や強化ができます。', '戦闘に戻る', '回避', '移動', '連続撃破', '集中砲火', '左下のスティックをドラッグして移動し、離すと停止します。WASDや矢印キーでも移動できます。攻撃は自動です。回避ボタンかShiftで短い無敵ダッシュ（再使用3秒）、遺物パルスかスペースで敵を押し戻せます。装備ボタンかEで戦闘を止めて装備変更・強化。5連続撃破で5秒間射撃が加速し、撃破ごとに連続撃破の制限時間が6秒になります。'],
  ko: ['장비', '전투 일시 정지. 여유롭게 장비를 바꾸고 강화하세요.', '전투로 복귀', '회피', '이동', '연속 처치', '집중 사격', '왼쪽 아래 조이스틱을 끌어 이동하고 놓으면 멈춥니다. WASD와 방향키도 지원합니다. 공격은 자동입니다. 회피나 Shift로 잠시 무적 돌진(재사용 3초), 유물 파동이나 Space로 적을 밀칩니다. 장비나 E로 전투를 멈추고 장착·강화하세요. 5연속 처치하면 5초간 사격이 빨라지며 처치할 때마다 연속 처치 제한이 6초로 갱신됩니다.'],
  es: ['Equipo', 'Combate en pausa: equipa y mejora sin prisa.', 'Volver al combate', 'Esquivar', 'Mover', 'Racha', 'SOBRECARGA', 'Arrastra el joystick izquierdo para moverte y suelta para parar; también sirven WASD y las flechas. Disparas automáticamente. Esquivar o Shift da un impulso invulnerable breve (recarga: 3 s). Pulso reliquia o Espacio empuja enemigos. Equipo o E pausa para equipar y mejorar. Cinco bajas encadenadas aceleran los disparos durante 5 s; cada baja renueva a 6 s el tiempo de la racha.'],
  'pt-BR': ['Equipamento', 'Combate pausado: equipe e melhore com calma.', 'Voltar ao combate', 'Esquivar', 'Mover', 'Sequência', 'SOBRECARGA', 'Arraste o joystick esquerdo para mover e solte para parar; WASD e setas também funcionam. Ataques são automáticos. Esquivar ou Shift dá um avanço com invulnerabilidade breve (recarga de 3 s). Pulso Relíquia ou Espaço afasta inimigos. Equipamento ou E pausa para equipar e melhorar. Cinco eliminações seguidas aceleram os disparos por 5 s; cada eliminação renova a janela da sequência para 6 s.'],
  fr: ['Équipement', 'Combat en pause : équipez et améliorez tranquillement.', 'Reprendre le combat', 'Esquive', 'Bouger', 'Série', 'SURCHARGE', 'Glissez le joystick gauche pour bouger, relâchez pour arrêter ; WASD et les flèches fonctionnent aussi. Les attaques sont automatiques. Esquive ou Maj permet une ruée brièvement invulnérable (recharge : 3 s). Impulsion relique ou Espace repousse les ennemis. Équipement ou E met en pause pour équiper et améliorer. Cinq éliminations en série accélèrent les tirs pendant 5 s ; chaque élimination renouvelle la fenêtre de série à 6 s.'],
  de: ['Ausrüstung', 'Kampf pausiert: in Ruhe ausrüsten und verbessern.', 'Weiterkämpfen', 'Ausweichen', 'Bewegen', 'Serie', 'FEUERSCHUB', 'Ziehe den linken Joystick zum Bewegen und lasse zum Stoppen los; WASD und Pfeiltasten gehen auch. Angriffe erfolgen automatisch. Ausweichen oder Umschalt startet einen kurz unverwundbaren Sprint (3 s Aufladung). Reliktimpuls oder Leertaste stößt Gegner zurück. Ausrüstung oder E pausiert zum Ausrüsten und Verbessern. Fünf schnelle Siege beschleunigen Schüsse für 5 s; jeder Sieg erneuert das Serienfenster auf 6 s.'],
  it: ['Equipaggiamento', 'Combattimento in pausa: equipaggia e migliora con calma.', 'Torna in battaglia', 'Schivata', 'Muovi', 'Serie', 'SOVRACCARICO', 'Trascina il joystick sinistro per muoverti e rilascialo per fermarti; funzionano anche WASD e le frecce. Attacchi automatici. Schivata o Maiusc dà uno scatto brevemente invulnerabile (ricarica: 3 s). Impulso reliquia o Spazio respinge i nemici. Equipaggiamento o E mette in pausa per equipaggiare e migliorare. Cinque eliminazioni in serie accelerano i colpi per 5 s; ogni eliminazione rinnova a 6 s il tempo della serie.'],
  ru: ['Снаряжение', 'Бой приостановлен: меняйте и улучшайте снаряжение.', 'Продолжить бой', 'Рывок', 'Движение', 'Серия', 'ФОРСАЖ', 'Тяните левый джойстик для движения, отпустите для остановки; также работают WASD и стрелки. Атаки автоматические. Рывок или Shift даёт краткую неуязвимость (перезарядка 3 с). Импульс реликвии или пробел отбрасывает врагов. Снаряжение или E ставит бой на паузу для смены и улучшения вещей. Пять убийств подряд ускоряют стрельбу на 5 с; каждое убийство обновляет окно серии до 6 с.'],
  hi: ['उपकरण', 'लड़ाई रुकी है। आराम से उपकरण बदलें और सुधारें।', 'लड़ाई पर लौटें', 'बचाव', 'चलें', 'श्रृंखला', 'तेज़ प्रहार', 'बाएं जॉयस्टिक को खींचकर चलें और छोड़कर रुकें; WASD या तीर कुंजियां भी काम करती हैं। हमले अपने आप होते हैं। बचाव या Shift से थोड़ी देर अजेय दौड़ लगाएं (3 सेकंड रीचार्ज)। अवशेष तरंग या Space से दुश्मनों को धकेलें। उपकरण या E से लड़ाई रोककर उपकरण बदलें और सुधारें। लगातार पांच दुश्मन हराने पर 5 सेकंड तेज़ फायर मिलता है; हर हार के बाद श्रृंखला की समय सीमा 6 सेकंड हो जाती है।'],
  ar: ['المعدات', 'المعركة متوقفة. جهّز معداتك وطوّرها بهدوء.', 'متابعة القتال', 'تفادٍ', 'تحرّك', 'سلسلة', 'اندفاع ناري', 'اسحب عصا التحكم اليسرى للتحرك واتركها للتوقف؛ تعمل WASD والأسهم أيضًا. الهجمات تلقائية. تفادٍ أو Shift يمنح اندفاعًا بحصانة قصيرة (شحن 3 ثوانٍ). نبضة الأثر أو Space تصد الأعداء. المعدات أو E توقف القتال للتجهيز والتطوير. هزيمة خمسة أعداء متتاليين تسرّع إطلاق النار لمدة 5 ثوانٍ؛ كل هزيمة تجدّد مهلة السلسلة إلى 6 ثوانٍ.'],
};
export const battleCopy = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale,
  Object.fromEntries(['equipmentLabel', 'equipmentPaused', 'equipmentClose', 'dodgeLabel', 'moveLabel', 'chainLabel', 'surgeLabel', 'controlsGuide'].map((key, i) => [key, values[i]]))
]));
