// Game-owned instructions; presentation belongs to the shared guide/frame CSS.
// Keep campaign totals out of prose: the live Stage screen owns that number.
export const guideCopy = {
 en: ['Explore ruins, dodge enemies and build a relic loadout.', 'Move and survive', 'Tap a destination or drag to steer; on desktop use WASD or the arrow keys. Your weapon attacks automatically. Move out of enemy attacks rather than standing still to trade damage.', 'Explore and equip', 'Follow the room objective, collect keys and open chests. Compare dropped equipment before choosing to equip it or keep your current gear. Relic choices strengthen the current expedition; training and equipment prepare you for the next one.', 'Progress and saves', 'Choose an expedition on Stage. After a defeat, retry or return to preparation; after a victory, follow the unlocked route. Health and temporary relic choices start fresh on a new expedition.', 'Is progress saved?', 'Unlocks, gold, training and equipment are stored in this browser. Clearing site data can remove them; do not expect progress to transfer to another device.'],
 'zh-Hant': ['探索遺跡、閃避敵人，搭配裝備與遺物闖過房間。', '移動與生存', '點擊目的地或拖曳移動；電腦可用 WASD 或方向鍵。武器會自動攻擊，不必追著點敵人。看準敵人的攻擊範圍，邊走位邊輸出。', '探索與裝備', '依房間目標前進、收集鑰匙並開啟寶箱。取得裝備後先比較，再選擇裝上或保留現有裝備。遺物選擇強化本次遠征；訓練與裝備則用來準備下一趟。', '進度與存檔', '在關卡畫面選擇遠征。失敗後可重試或返回整備，勝利後沿解鎖路線前進。新遠征會重新開始生命值與暫時遺物效果。', '進度會保存嗎？', '解鎖進度、金幣、訓練與裝備保存在目前瀏覽器。清除網站資料可能使存檔消失，不保證跨裝置同步。'],
 'zh-Hans': ['探索遗迹、闪避敌人，搭配装备与遗物闯过房间。', '移动与生存', '点击目的地或拖动移动；电脑可用 WASD 或方向键。武器会自动攻击，不必追着点敌人。看准敌人的攻击范围，边走位边输出。', '探索与装备', '按房间目标前进、收集钥匙并开启宝箱。获得装备后先比较，再选择装上或保留现有装备。遗物选择强化本次远征；训练与装备则用来准备下一趟。', '进度与存档', '在关卡画面选择远征。失败后可重试或返回整备，胜利后沿解锁路线前进。新远征会重新开始生命值与临时遗物效果。', '进度会保存吗？', '解锁进度、金币、训练与装备保存在当前浏览器。清除网站数据可能使存档消失，不保证跨设备同步。'],
 ja: ['遺跡を探索し、敵をかわしながら装備と遺物を組み合わせよう。', '移動と生存', '目的地をタップするかドラッグして移動。PCではWASDまたは矢印キーを使えます。武器は自動攻撃します。敵を連打せず、攻撃範囲から逃れながら戦いましょう。', '探索と装備', '部屋の目標に従い、鍵を集めて宝箱を開けます。拾った装備を比較し、装備するか現在の装備を残すか選びます。遺物は今回の遠征を強化し、訓練と装備は次の遠征にも役立ちます。', '進行と保存', 'ステージ画面から遠征を選択。敗北後は再挑戦か準備画面へ戻り、勝利後は解放された道を進みます。新しい遠征では体力と一時的な遺物効果がリセットされます。', '進行は保存されますか？', '解放状況、金貨、訓練、装備はこのブラウザーに保存されます。サイトデータを削除すると失われる場合があります。別の端末との同期は保証されません。'],
 ko: ['유적을 탐험하고 적을 피하며 장비와 유물을 조합하세요.', '이동과 생존', '목적지를 누르거나 드래그해 이동하세요. PC에서는 WASD 또는 방향키를 사용합니다. 무기는 자동 공격하므로 적을 연타할 필요가 없습니다. 공격 범위를 피하며 싸우세요.', '탐험과 장비', '방의 목표를 따라 열쇠를 모으고 상자를 여세요. 새 장비를 비교한 뒤 장착하거나 기존 장비를 유지하세요. 유물 선택은 이번 원정을 강화하고 훈련과 장비는 다음 원정을 준비합니다.', '진행과 저장', '스테이지에서 원정을 선택하세요. 패배하면 재도전하거나 준비 화면으로 돌아가고, 승리하면 열린 경로를 진행하세요. 새 원정에서는 체력과 임시 유물 효과가 초기화됩니다.', '진행 상황이 저장되나요?', '해금 진행, 금화, 훈련, 장비는 현재 브라우저에 저장됩니다. 사이트 데이터를 지우면 사라질 수 있으며 다른 기기와의 동기화는 보장되지 않습니다.'],
 es: ['Explora ruinas, esquiva enemigos y combina equipo y reliquias.', 'Movimiento y supervivencia', 'Toca un destino o arrastra para moverte; en ordenador usa WASD o las flechas. El arma ataca automáticamente. Evita las zonas de ataque en lugar de quedarte quieto intercambiando golpes.', 'Exploración y equipo', 'Sigue el objetivo de la sala, recoge llaves y abre cofres. Compara el equipo encontrado antes de equiparlo o conservar el actual. Las reliquias potencian esta expedición; el entrenamiento y el equipo preparan la siguiente.', 'Progreso y guardado', 'Elige una expedición en la pantalla de etapas. Tras perder, reintenta o vuelve a prepararte; tras ganar, sigue la ruta desbloqueada. La salud y los efectos temporales de reliquias se reinician en una nueva expedición.', '¿Se guarda el progreso?', 'Los desbloqueos, el oro, el entrenamiento y el equipo se guardan en este navegador. Borrar los datos del sitio puede eliminarlos; no se garantiza la sincronización entre dispositivos.'],
 'pt-BR': ['Explore ruínas, desvie dos inimigos e combine equipamentos e relíquias.', 'Movimento e sobrevivência', 'Toque no destino ou arraste para se mover; no computador, use WASD ou as setas. A arma ataca automaticamente. Saia das áreas de ataque em vez de ficar parado trocando golpes.', 'Exploração e equipamentos', 'Siga o objetivo da sala, colete chaves e abra baús. Compare o equipamento encontrado antes de equipá-lo ou manter o atual. As relíquias fortalecem esta expedição; treinamento e equipamentos preparam a próxima.', 'Progresso e salvamento', 'Escolha uma expedição na tela de fases. Após perder, tente novamente ou volte à preparação; após vencer, siga a rota desbloqueada. A vida e os efeitos temporários de relíquias recomeçam em uma nova expedição.', 'O progresso é salvo?', 'Desbloqueios, ouro, treinamento e equipamentos ficam neste navegador. Limpar os dados do site pode apagá-los; não há garantia de sincronização entre dispositivos.'],
 fr: ['Explorez les ruines, esquivez les ennemis et combinez équipement et reliques.', 'Déplacement et survie', 'Touchez une destination ou faites glisser pour vous déplacer ; sur ordinateur, utilisez WASD ou les flèches. Votre arme attaque automatiquement. Évitez les zones d’attaque plutôt que de rester immobile à échanger des coups.', 'Exploration et équipement', 'Suivez l’objectif de la salle, ramassez les clés et ouvrez les coffres. Comparez le butin avant de l’équiper ou de garder votre équipement actuel. Les reliques renforcent cette expédition ; l’entraînement et l’équipement préparent la suivante.', 'Progression et sauvegarde', 'Choisissez une expédition dans l’écran des étapes. Après une défaite, réessayez ou préparez-vous ; après une victoire, suivez la route débloquée. La santé et les effets temporaires des reliques repartent à zéro lors d’une nouvelle expédition.', 'La progression est-elle sauvegardée ?', 'Les déblocages, l’or, l’entraînement et l’équipement sont conservés dans ce navigateur. Effacer les données du site peut les supprimer ; la synchronisation entre appareils n’est pas garantie.'],
 de: ['Erkunde Ruinen, weiche Gegnern aus und kombiniere Ausrüstung und Relikte.', 'Bewegung und Überleben', 'Tippe ein Ziel an oder ziehe zum Bewegen; am Computer nutzt du WASD oder die Pfeiltasten. Deine Waffe greift automatisch an. Verlasse gegnerische Angriffsbereiche, statt im Stehen Treffer auszutauschen.', 'Erkundung und Ausrüstung', 'Folge dem Raumziel, sammle Schlüssel und öffne Truhen. Vergleiche Beute, bevor du sie ausrüstest oder deine bisherige Ausrüstung behältst. Relikte stärken diese Expedition; Training und Ausrüstung bereiten die nächste vor.', 'Fortschritt und Speicherung', 'Wähle im Levelbildschirm eine Expedition. Nach einer Niederlage kannst du erneut starten oder zur Vorbereitung zurückkehren; nach einem Sieg folgst du dem freigeschalteten Weg. Gesundheit und vorübergehende Relikteffekte beginnen bei einer neuen Expedition von vorn.', 'Wird der Fortschritt gespeichert?', 'Freischaltungen, Gold, Training und Ausrüstung bleiben in diesem Browser. Das Löschen der Websitedaten kann sie entfernen; eine geräteübergreifende Synchronisierung ist nicht garantiert.'],
 it: ['Esplora rovine, schiva i nemici e combina equipaggiamento e reliquie.', 'Movimento e sopravvivenza', 'Tocca una destinazione o trascina per muoverti; sul computer usa WASD o le frecce. L’arma attacca automaticamente. Evita le aree di attacco invece di restare fermo a scambiare colpi.', 'Esplorazione ed equipaggiamento', 'Segui l’obiettivo della stanza, raccogli chiavi e apri forzieri. Confronta il bottino prima di equipaggiarlo o tenere quello attuale. Le reliquie potenziano questa spedizione; allenamento ed equipaggiamento preparano la prossima.', 'Progressi e salvataggio', 'Scegli una spedizione nella schermata dei livelli. Dopo una sconfitta, riprova o torna ai preparativi; dopo una vittoria, segui il percorso sbloccato. Salute ed effetti temporanei delle reliquie ripartono con ogni nuova spedizione.', 'I progressi vengono salvati?', 'Sblocchi, oro, allenamento ed equipaggiamento restano in questo browser. Cancellare i dati del sito può eliminarli; la sincronizzazione tra dispositivi non è garantita.'],
 ru: ['Исследуйте руины, уклоняйтесь от врагов и сочетайте снаряжение с реликвиями.', 'Движение и выживание', 'Нажмите на цель или ведите пальцем для движения; на компьютере используйте WASD или стрелки. Оружие атакует автоматически. Выходите из зон атаки, а не обменивайтесь ударами стоя на месте.', 'Исследование и снаряжение', 'Выполняйте цель комнаты, собирайте ключи и открывайте сундуки. Сравнивайте добычу, прежде чем надеть её или оставить прежнее снаряжение. Реликвии усиливают текущую экспедицию, а тренировки и снаряжение готовят к следующей.', 'Прогресс и сохранение', 'Выберите экспедицию на экране этапов. После поражения повторите попытку или вернитесь к подготовке; после победы идите по открытому пути. В новой экспедиции здоровье и временные эффекты реликвий начинаются заново.', 'Сохраняется ли прогресс?', 'Открытые этапы, золото, тренировки и снаряжение сохраняются в этом браузере. Очистка данных сайта может удалить их; синхронизация между устройствами не гарантируется.'],
 hi: ['खंडहर खोजें, दुश्मनों से बचें और उपकरणों व अवशेषों का संयोजन बनाएं।', 'चलना और बचना', 'चलने के लिए गंतव्य पर टैप करें या खींचें; कंप्यूटर पर WASD या तीर कुंजियां इस्तेमाल करें। हथियार अपने आप हमला करता है। एक जगह खड़े होकर वार सहने के बजाय दुश्मन के हमले के क्षेत्र से बाहर निकलें।', 'खोज और उपकरण', 'कमरे का लक्ष्य पूरा करें, चाबियां जुटाएं और संदूक खोलें। मिले उपकरण की तुलना करके उसे पहनें या मौजूदा उपकरण रखें। अवशेष इस अभियान को मजबूत करते हैं; प्रशिक्षण और उपकरण अगले अभियान की तैयारी हैं।', 'प्रगति और सेव', 'चरण स्क्रीन पर अभियान चुनें। हारने पर फिर कोशिश करें या तैयारी पर लौटें; जीतने पर खुले रास्ते पर आगे बढ़ें। नए अभियान में स्वास्थ्य और अस्थायी अवशेष प्रभाव फिर से शुरू होते हैं।', 'क्या प्रगति सेव होती है?', 'खुले चरण, सोना, प्रशिक्षण और उपकरण इसी ब्राउज़र में सेव होते हैं। साइट डेटा हटाने से ये मिट सकते हैं; दूसरे उपकरण पर सिंक होने की गारंटी नहीं है।'],
 ar: ['استكشف الأطلال وتفادَ الأعداء واجمع بين المعدات والآثار.', 'الحركة والبقاء', 'المس وجهة أو اسحب للتحرك؛ على الكمبيوتر استخدم WASD أو مفاتيح الأسهم. يهاجم السلاح تلقائيًا. اخرج من مناطق هجوم الأعداء بدل الوقوف وتبادل الضربات.', 'الاستكشاف والمعدات', 'اتبع هدف الغرفة واجمع المفاتيح وافتح الصناديق. قارن الغنيمة قبل تجهيزها أو الاحتفاظ بمعداتك الحالية. تقوّي الآثار هذه الرحلة، بينما يجهزك التدريب والمعدات للرحلة التالية.', 'التقدم والحفظ', 'اختر رحلة من شاشة المراحل. بعد الهزيمة أعد المحاولة أو عد للاستعداد؛ بعد الفوز اتبع الطريق المفتوح. تبدأ الصحة وتأثيرات الآثار المؤقتة من جديد في كل رحلة جديدة.', 'هل يُحفظ التقدم؟', 'تُحفظ المراحل المفتوحة والذهب والتدريب والمعدات في هذا المتصفح. قد يمحوها حذف بيانات الموقع؛ لا نضمن المزامنة بين الأجهزة.'],
};
const faqCopy = {
 en: ['Frequently Asked Questions', 'What happens after a defeat?', 'Retry the expedition or return to preparation; a new expedition starts with fresh health and temporary relic effects.'],
 'zh-Hant': ['常見問題', '失敗後會怎樣？', '你可以重試遠征或返回整備；新的遠征會以全新的生命值與暫時遺物效果開始。'],
 'zh-Hans': ['常见问题', '失败后会怎样？', '你可以重试远征或返回整备；新的远征会以全新的生命值和临时遗物效果开始。'],
 ja: ['よくある質問', '敗北するとどうなりますか？', '遠征を再挑戦するか準備画面へ戻れます。新しい遠征では体力と一時的な遺物効果が新しく始まります。'],
 ko: ['자주 묻는 질문', '패배하면 어떻게 되나요?', '원정을 다시 시도하거나 준비 화면으로 돌아갈 수 있습니다. 새 원정은 체력과 임시 유물 효과가 새로 시작됩니다.'],
 es: ['Preguntas frecuentes', '¿Qué ocurre tras una derrota?', 'Puedes reintentar la expedición o volver a prepararte; una nueva expedición comienza con salud y efectos temporales de reliquia renovados.'],
 'pt-BR': ['Perguntas frequentes', 'O que acontece após uma derrota?', 'Você pode tentar a expedição novamente ou voltar à preparação; uma nova expedição começa com vida e efeitos temporários de relíquias renovados.'],
 fr: ['Questions fréquentes', 'Que se passe-t-il après une défaite ?', 'Vous pouvez réessayer l’expédition ou revenir à la préparation ; une nouvelle expédition commence avec une santé et des effets temporaires de reliques réinitialisés.'],
 de: ['Häufige Fragen', 'Was passiert nach einer Niederlage?', 'Du kannst die Expedition erneut starten oder zur Vorbereitung zurückkehren; eine neue Expedition beginnt mit frischer Gesundheit und neuen temporären Relikteffekten.'],
 it: ['Domande frequenti', 'Cosa succede dopo una sconfitta?', 'Puoi riprovare la spedizione o tornare alla preparazione; una nuova spedizione inizia con salute ed effetti temporanei delle reliquie rinnovati.'],
 ru: ['Частые вопросы', 'Что происходит после поражения?', 'Можно повторить экспедицию или вернуться к подготовке; новая экспедиция начинается с полным здоровьем и заново действующими временными эффектами реликвий.'],
 hi: ['अक्सर पूछे गए प्रश्न', 'हार के बाद क्या होता है?', 'आप अभियान को फिर से आज़मा सकते हैं या तैयारी पर लौट सकते हैं; नया अभियान नए स्वास्थ्य और अस्थायी अवशेष प्रभावों के साथ शुरू होता है।'],
 ar: ['الأسئلة الشائعة', 'ماذا يحدث بعد الهزيمة؟', 'يمكنك إعادة المحاولة في الرحلة أو العودة إلى الاستعداد؛ وتبدأ الرحلة الجديدة بصحة وتأثيرات آثار مؤقتة جديدة.'],
};
const reworkSummary = {
 en: 'Explore ruins, dodge attacks and unleash a relic pulse against nearby threats.',
 'zh-Hant': '探索遺跡、閃避攻擊，釋放遺物脈衝重擊周圍威脅。',
 'zh-Hans': '探索遗迹、闪避攻击，释放遗物脉冲重击周围威胁。',
 ja: '遺跡を探索し、攻撃をかわして遺物パルスで周囲の敵を吹き飛ばそう。',
 ko: '유적을 탐험하고 공격을 피하며 유물 파동으로 주변 적을 날려 보내세요.',
 es: 'Explora ruinas, esquiva ataques y desata un pulso de reliquia contra enemigos cercanos.',
 'pt-BR': 'Explore ruínas, desvie de ataques e libere um pulso de relíquia contra inimigos próximos.',
 fr: 'Explorez les ruines, esquivez les attaques et libérez une impulsion de relique contre les ennemis proches.',
 de: 'Erkunde Ruinen, weiche Angriffen aus und entfessle einen Reliktimpuls gegen Gegner in der Nähe.',
 it: 'Esplora le rovine, schiva gli attacchi e scatena un impulso reliquia contro i nemici vicini.',
 ru: 'Исследуйте руины, уклоняйтесь от атак и поражайте близких врагов импульсом реликвии.',
 hi: 'खंडहर खोजें, हमलों से बचें और अवशेष तरंग से पास के दुश्मनों को पीछे हटाएँ।',
 ar: 'استكشف الأطلال وتفادَ الهجمات وأطلق نبضة أثر لصد الأعداء القريبين.',
};
const pulseGuideCopy = {
 en: 'Press Space or tap the canvas Relic Pulse control to damage nearby enemies, push them back, and clear enemy shots. Relic Damage increases its hit; Relic Speed shortens its 12-second cooldown by one second per stack, down to 7 seconds.',
 'zh-Hant': '按空白鍵或點擊畫面右下角的遺物脈衝，對附近敵人造成傷害、擊退敵人並清除敵方彈幕。每層「傷害遺物」提高脈衝傷害；每層「速度遺物」縮短 1 秒冷卻，最短 7 秒。',
 'zh-Hans': '按空格键或点击画面右下角的遗物脉冲，对附近敌人造成伤害、击退敌人并清除敌方弹幕。每层“伤害遗物”提高脉冲伤害；每层“速度遗物”缩短 1 秒冷却，最短 7 秒。',
 ja: 'スペースキーまたは画面右下の遺物パルスをタップすると、近くの敵にダメージを与えて押し戻し、敵弾を消せます。「水晶の牙」は威力を高め、「ランタンの閃光」は重ねるごとに再充填を1秒短縮します（最短7秒）。',
 ko: '스페이스바를 누르거나 화면 오른쪽 아래의 유물 파동을 탭하면 주변 적에게 피해를 주고 밀쳐내며 적 탄환을 지웁니다. 수정 송곳니는 파동 피해를 높이고, 등불 폭발은 중첩마다 재충전 시간을 1초 줄입니다(최소 7초).',
 es: 'Pulsa Espacio o toca el control Pulso reliquia abajo a la derecha: daña y empuja a los enemigos cercanos y elimina sus disparos. Colmillo de Cristal aumenta el daño; Estallido de Linterna reduce la recarga 1 s por acumulación, hasta 7 s.',
 'pt-BR': 'Pressione Espaço ou toque no controle Pulso Relíquia no canto inferior direito: ele causa dano, empurra inimigos próximos e limpa disparos inimigos. Presa de Cristal aumenta o dano; Explosão de Lanterna reduz a recarga em 1 s por acúmulo, até 7 s.',
 fr: 'Appuyez sur Espace ou touchez Impulsion relique en bas à droite : elle blesse et repousse les ennemis proches et dissipe leurs tirs. Croc de cristal augmente ses dégâts ; Éclat de lanterne réduit la recharge d’1 s par cumul, jusqu’à 7 s.',
 de: 'Drücke die Leertaste oder tippe unten rechts auf Reliktimpuls: Er schädigt und stößt nahe Gegner zurück und beseitigt feindliche Schüsse. Kristallzahn erhöht den Schaden; Laternenstoß verkürzt die Aufladung pro Stapel um 1 s, bis auf 7 s.',
 it: 'Premi Spazio o tocca Impulso reliquia in basso a destra: danneggia e respinge i nemici vicini e disperde i loro colpi. Zanna di cristallo aumenta i danni; Scatto di lanterna riduce la ricarica di 1 s per accumulo, fino a 7 s.',
 ru: 'Нажмите пробел или коснитесь импульса реликвии внизу справа: он ранит и отбрасывает близких врагов, а также рассеивает вражеские снаряды. Кристальный клык усиливает урон; Вспышка фонаря сокращает зарядку на 1 с за уровень, минимум до 7 с.',
 hi: 'पास के दुश्मनों को नुकसान पहुँचाने व पीछे धकेलने और उनके गोले हटाने के लिए Space दबाएँ या नीचे दाईं ओर अवशेष तरंग टैप करें। क्रिस्टल फेंग इसका नुकसान बढ़ाता है; लालटेन बर्स्ट हर स्टैक पर रीचार्ज 1 सेकंड घटाता है, न्यूनतम 7 सेकंड तक।',
 ar: 'اضغط Space أو المس زر نبضة الأثر أسفل اليمين لإصابة الأعداء القريبين ودفعهم وإزالة طلقاتهم. يزيد ناب الكريستال ضررها، وتقلّل ومضة الفانوس إعادة الشحن ثانية واحدة لكل تكديس، حتى 7 ثوانٍ.',
};
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
export function replaceRelicGuide(html, locale = 'en') {
 const copy = guideCopy[locale];
 if (!copy) throw new Error(`Missing Relic guide locale: ${locale}`);
 const summaryCopy = reworkSummary[locale];
 const separator = ['zh-Hant', 'zh-Hans', 'ja'].includes(locale) ? '' : ' ';
 const moveCopy = `${copy[2]}${separator}${pulseGuideCopy[locale]}`;
 const summary = /<p\b[^>]*data-ui="menuHint"[^>]*>[\s\S]*?<\/p>/;
 if (!summary.test(html)) throw new Error('Relic Main summary missing');
 html = html.replace(summary, () => `<p class="menu-hint main-summary" data-ui="menuHint" data-relic-authored-summary="true" data-runtime-localize="off">${escape(summaryCopy)}</p>`);
 const pattern = /<section\b[^>]*class="game-page-info game-page-info-static"[^>]*>[\s\S]*?<\/section>/;
 const title = html.match(pattern)?.[0].match(/<h2\b[^>]*>([\s\S]*?)<\/h2>/)?.[1];
 if (!title) throw new Error('Relic guide title missing');
 html = html.replace(/<body\b(?![^>]*data-wp-game-owned-guide)/, '<body data-wp-game-owned-guide="true"');
 const faq = faqCopy[locale] || faqCopy.en;
 return html.replace(pattern, () => `<section id="gameGuide" class="game-page-info game-page-info-static" data-wp-guide-complete="true" data-runtime-localize="off"><div class="game-info-hero"><div class="game-info-title"><h2>${title}</h2><p>${escape(summaryCopy)}</p></div></div><div class="game-info-sections">${[1,3,5].map(i => `<div class="game-info-section"><h3>${escape(copy[i])}</h3><p>${escape(i === 1 ? moveCopy : copy[i+1])}</p></div>`).join('')}<div class="game-info-section"><h3>${escape(copy[7])}</h3><p>${escape(copy[8])}</p></div><div class="game-info-section"><h3>${escape(faq[0])}</h3><dl><div><dt>${escape(faq[1])}</dt><dd>${escape(faq[2])}</dd></div></dl></div></div></section>`);
}
