(() => {
  const $ = (id) => document.getElementById(id);
  const saveKey = 'animal_skyport_dispatch_save';
  const text = {en:{title:'Animal Skyport Dispatch',language:'Language',headline:'Keep Cloudline Skyport moving.',intro:'Draw safe routes, match airships to docks, and protect the shift from congestion.',start:'Start Game',chooseShift:'Choose a shift',best:'Best shift: {n}',shift:'Shift {n}/5',objective:'Serve {done}/{goal} flights',service:'Use repair service',dragHint:'Drag the airship to its matching dock.',menu:'Main Menu',next:'Next Shift',retry:'Retry Shift',win:'Shift complete!',lose:'Skyport congested!',winCopy:'Clear routing earns a new skyport record.',loseCopy:'Three unsafe arrivals closed the shift. Retry is free.',repair:'Repair parts {n}'},'zh-Hant':{title:'動物天空港調度隊',language:'語言',headline:'讓雲線天空港持續運轉。',intro:'畫出安全航線，配對飛船與碼頭，別讓壅塞中斷班次。',start:'開始遊戲',chooseShift:'選擇班次',best:'最佳班次：{n}',shift:'第 {n}/5 班',objective:'已服務 {done}/{goal} 艘飛船',service:'使用修理服務',dragHint:'把飛船拖到相符的碼頭。',menu:'主選單',next:'下一班',retry:'重試班次',win:'班次完成！',lose:'天空港壅塞！',winCopy:'清楚的調度創下新的天空港紀錄。',loseCopy:'三次不安全的抵達使班次關閉，重試免費。',repair:'修理零件 {n}'}};
  let locale=localStorage.getItem('weightPlayLocale')||'en', save=JSON.parse(localStorage.getItem(saveKey)||'{"best":0,"unlocked":1}'), state={};
  const t=(key,data={})=>Object.entries(data).reduce((s,[k,v])=>s.replace(`{${k}}`,v),text[locale][key]);
  const screens=['mainScreen','stageScreen','battleShell','result'];
  const show=(name)=>{screens.forEach(id=>$(id).classList.toggle('hidden',id!==name));$('mainHeader').classList.toggle('hidden',name!=='mainScreen');document.body.classList.toggle('skyport-playing',name==='battleShell')};
  function persist(){localStorage.setItem(saveKey,JSON.stringify(save))} function localize(){document.documentElement.lang=locale;document.title=t('title')+' - Internal Trial';document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));$('localeSelect').value=locale;renderStages()}
  const flights=[['cargo','cargo'],['passenger','passenger'],['repair','repair'],['festival','passenger'],['heavy','cargo']];
  function renderStages(){if($('stageScreen').classList.contains('hidden'))return;$('bestText').textContent=t('best',{n:save.best||0});$('stageRail').innerHTML='';for(let i=1;i<6;i++){const b=document.createElement('button');b.className='stage-card'+(i===state.shift?' selected':'');b.disabled=i>save.unlocked;b.innerHTML=`<strong>${t('shift',{n:i})}</strong><span>${t('objective',{done:0,goal:i+2})}</span><small>${i>save.unlocked?'Locked':i===save.unlocked?'Ready':'Replay'}</small>`;b.onclick=()=>{state.shift=i;startBattle()};$('stageRail').append(b)}}
  function startBattle(){state={shift:state.shift||1,done:0,errors:0,parts:2,goal:(state.shift||1)+2,flightIndex:0};show('battleShell');nextFlight();renderHud()}
  function renderHud(){ $('shiftText').textContent=t('shift',{n:state.shift});$('scoreText').textContent=`${state.done}/${state.goal}`;$('objectiveText').textContent=t('objective',{done:state.done,goal:state.goal});$('resourceText').textContent=t('repair',{n:state.parts}); }
  function nextFlight(){const [kind,dock]=flights[state.flightIndex++%flights.length];state.kind=kind;state.dock=dock;$('flight').style.backgroundImage=`url('../../assets/animal-skyport-dispatch-airship-${kind}.webp')`;$('feedback').textContent=t('dragHint');$('routeLine').style.opacity='0'}
  function finish(ok){if(ok){state.done++;$('feedback').textContent='✓';if(state.done>=state.goal){save.best=Math.max(save.best||0,state.shift);save.unlocked=Math.max(save.unlocked||1,Math.min(5,state.shift+1));persist();return result(true)}nextFlight()}else{state.errors++;$('feedback').textContent='!';if(state.errors>=3)return result(false)}renderHud()}
  function result(win){show('result');$('resultTitle').textContent=win?t('win'):t('lose');$('resultCopy').textContent=win?t('winCopy'):t('loseCopy');$('nextBtn').textContent=win&&state.shift<5?t('next'):t('retry');$('nextBtn').onclick=()=>{state.shift=win?Math.min(5,state.shift+1):state.shift;startBattle()}}
  let dragging=false;function pointer(e){const f=$('flight'),field=$('routeField').getBoundingClientRect();const x=e.clientX-field.left,y=e.clientY-field.top;if(e.type==='pointerdown'){dragging=true;f.setPointerCapture(e.pointerId)}if(!dragging)return;const fx=f.offsetLeft+36,fy=f.offsetTop+36,dx=x-fx,dy=y-fy,len=Math.hypot(dx,dy);Object.assign($('routeLine').style,{left:fx+'px',top:fy+'px',width:len+'px',transform:`rotate(${Math.atan2(dy,dx)}rad)`,opacity:'1'});if(e.type==='pointerup'){dragging=false;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.dock');finish(target?.dataset.dock===state.dock)}}
  $('startBtn').onclick=()=>{state.shift=save.unlocked;show('stageScreen');renderStages()};$('stageBack').onclick=()=>show('mainScreen');$('battleBack').onclick=()=>{show('stageScreen');renderStages()};$('menuBtn').onclick=()=>show('mainScreen');$('serviceBtn').onclick=()=>{if(state.kind==='repair'&&state.parts){state.parts--;state.dock='repair';$('feedback').textContent='Repair ready';renderHud()}};$('flight').addEventListener('pointerdown',pointer);window.addEventListener('pointermove',pointer);window.addEventListener('pointerup',pointer);$('localeSelect').onchange=e=>{locale=e.target.value;localStorage.setItem('weightPlayLocale',locale);localize()};localize();
})();
