(function(){
"use strict";
const $=id=>document.getElementById(id),LOCALES=window.RIFT_SALVAGE_LOCALES||{},CODES=["en","zh-Hant","zh-Hans","ja","ko","es","pt-BR","fr","de","it","ru"],LABELS={en:"English","zh-Hant":"繁體中文","zh-Hans":"简体中文",ja:"日本語",ko:"한국어",es:"Español","pt-BR":"Português",fr:"Français",de:"Deutsch",it:"Italiano",ru:"Русский"},STORE="weightplay:animal-rift-salvage:v1",WORLD=1000,TAU=Math.PI*2;
const els={loading:$("loading"),mainGroup:$("mainGroup"),stageScreen:$("stageScreen"),battleScreen:$("battleScreen"),battleLive:$("battleLive"),localeSelect:$("localeSelect"),mainProgress:$("mainProgress"),start:$("start"),stageBack:$("stageBack"),stageRail:$("stageRail"),stageSummary:$("stageSummary"),zonesTab:$("zonesTab"),observatoryTab:$("observatoryTab"),zonePanel:$("zonePanel"),observatoryPanel:$("observatoryPanel"),stageHint:$("stageHint"),gearCount:$("gearCount"),upgrades:$("upgrades"),wakeButton:$("wakeButton"),battleBack:$("battleBack"),battleHelp:$("battleHelp"),zoneLabel:$("zoneLabel"),timerValue:$("timerValue"),scoreValue:$("scoreValue"),sizeValue:$("sizeValue"),stabilityValue:$("stabilityValue"),objective:$("objective"),arenaWrap:$("arenaWrap"),canvas:$("arena"),chainValue:$("chainValue"),feedback:$("feedback"),helpModal:$("helpModal"),helpClose:$("helpClose"),leaveModal:$("leaveModal"),leaveContinue:$("leaveContinue"),leaveStage:$("leaveStage"),resultModal:$("resultModal"),resultKicker:$("resultKicker"),resultTitle:$("resultTitle"),resultText:$("resultText"),resultTime:$("resultTime"),resultChain:$("resultChain"),resultMedal:$("resultMedal"),retry:$("retry"),resultZones:$("resultZones"),next:$("next")};
const ctx=els.canvas.getContext("2d",{alpha:false}),memory=new Map();let locale="en",screen="main",stageIndex=0,run=null,raf=0,lastFrame=performance.now(),stageScrollTimer=0,view={scale:1,cx:0,cy:0};
const storage={get(k){try{return localStorage.getItem(k)}catch{return memory.get(k)||null}},set(k,v){try{localStorage.setItem(k,v)}catch{memory.set(k,v)}}};
function defaultSave(){return{unlocked:1,medals:{},best:{},gears:0,upgrades:{drive:0,compression:0,stability:0},tutorial:false,wake:false}}
function normalizeSave(raw){const s=raw&&typeof raw==="object"?raw:{};return{unlocked:Math.max(1,Math.min(30,Number(s.unlocked)||1)),medals:s.medals&&typeof s.medals==="object"?s.medals:{},best:s.best&&typeof s.best==="object"?s.best:{},gears:Math.max(0,Number(s.gears)||0),upgrades:{drive:Math.max(0,Math.min(3,Number(s.upgrades?.drive)||0)),compression:Math.max(0,Math.min(3,Number(s.upgrades?.compression)||0)),stability:Math.max(0,Math.min(3,Number(s.upgrades?.stability)||0))},tutorial:Boolean(s.tutorial),wake:Boolean(s.wake)}}
let save=(()=>{try{return normalizeSave(JSON.parse(storage.get(STORE)||"null"))}catch{return defaultSave()}})();
function persist(){storage.set(STORE,JSON.stringify(save))}
function t(key,data={}){let value=LOCALES[locale]?.[key]??LOCALES.en?.[key]??key;if(Array.isArray(value))return value;return String(value).replace(/\{(\w+)\}/g,(_,k)=>data[k]??`{${k}}`)}
function track(name,data={}){try{window.WeightPlayAnalytics?.track?.(name,{game:"animal-rift-salvage",stage:stageIndex+1,...data})}catch{}}
function seeded(seed){let x=(seed|0)+0x6d2b79f5;return()=>{x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296}}
function circlePoint(rng,min=80,max=405){const a=rng()*TAU,r=min+(max-min)*Math.sqrt(rng());return{x:500+Math.cos(a)*r,y:500+Math.sin(a)*r}}
const TYPE={shard:{r:13,mass:4,value:5,img:"shard"},crate:{r:21,mass:8,value:9,img:"crate"},prism:{r:29,mass:16,value:16,img:"prism"},tower:{r:42,mass:26,value:28,img:"tower"},crown:{r:58,mass:48,value:50,img:"crown"},core:{r:24,mass:5,value:24,img:"core"},anchor:{r:22,mass:10,value:12,img:"anchor"}};
function buildZone(index){const chapter=Math.floor(index/5),rng=seeded(4889+index*197),quota=150+index*6+chapter*10,timer=72+chapter*3,rescueNeed=index>=4?(chapter>=5?2:1):0,rivals=chapter>=4?(index>=27?2:1):0,objects=[];let id=0;const add=(type,count,extra={})=>{for(let i=0;i<count;i++){const p=circlePoint(rng,70,chapter>=5?390:410),d=TYPE[type];objects.push({id:id++,type,x:p.x,y:p.y,vx:chapter===1?(rng()-.5)*34:0,vy:chapter===1?(rng()-.5)*34:0,r:d.r,mass:d.mass,value:d.value,img:d.img,active:true,shielded:Boolean(extra.shielded&&i%2===0),phase:rng()*TAU,gear:rng()<.11})}};add("shard",18+chapter*2);add("crate",12+chapter);add("prism",8+Math.floor(chapter/2));add("tower",5+Math.floor(chapter/2),{shielded:chapter>=3});add("crown",1+Math.floor(chapter/3),{shielded:chapter>=3});if(chapter>=2)add("anchor",2+Math.floor((index%5)/2));add("core",rescueNeed);objects.sort((a,b)=>a.r-b.r||a.id-b.id);const rivalList=Array.from({length:rivals},(_,i)=>{const a=(i?Math.PI:.15)+rng()*.2;return{id:i,x:500+Math.cos(a)*330,y:500+Math.sin(a)*330,vx:0,vy:0,mass:0,threshold:17,score:0,target:null,phase:rng()*TAU}});return{index,chapter,name:t("chapters")[chapter],rule:t("rules")[chapter],quota,timer,rescueNeed,rivals:rivalList,objects,currentPower:chapter>=2?42+chapter*8:0,storm:chapter>=5,goldTime:Math.max(24,timer*.55),silverTime:Math.max(32,timer*.76)}}
const zones=Array.from({length:30},(_,i)=>buildZone(i));
function refreshZoneLocale(){zones.forEach(z=>{z.name=t("chapters")[z.chapter];z.rule=t("rules")[z.chapter]})}
function initLocale(){const saved=storage.get("weightplay:animal-rift-salvage:locale")||storage.get("weightplay:locale");locale=CODES.includes(saved)?saved:"en";els.localeSelect.innerHTML=CODES.map(code=>`<option value="${code}">${LABELS[code]}</option>`).join("");els.localeSelect.value=locale}
function applyLocale(){document.documentElement.lang=locale;document.title=`${t("title")} | Internal WeightPlay Trial`;document.querySelectorAll("[data-t]").forEach(n=>n.textContent=t(n.dataset.t));document.querySelectorAll("[data-t-aria]").forEach(n=>n.setAttribute("aria-label",t(n.dataset.tAria)));document.querySelectorAll("[data-t-alt]").forEach(n=>n.setAttribute("alt",t(n.dataset.tAlt)));renderMainProgress();renderStages();renderObservatory();if(run)renderHud()}
els.localeSelect.addEventListener("change",()=>{locale=CODES.includes(els.localeSelect.value)?els.localeSelect.value:"en";storage.set("weightplay:animal-rift-salvage:locale",locale);storage.set("weightplay:locale",locale);applyLocale()});
function renderMainProgress(){const done=Object.values(save.medals).filter(n=>Number(n)>0).length;els.mainProgress.textContent=t("progress",{done})}
function setScreen(next){screen=next;document.body.dataset.screen=next;els.mainGroup.hidden=next!=="main";els.stageScreen.hidden=next!=="stage";els.battleScreen.hidden=next!=="battle";if(next!=="battle")cancelAnimationFrame(raf);if(next==="stage"){renderStages();renderObservatory();requestAnimationFrame(centerCurrentStage)}if(next==="battle")startLoop()}
function renderStages(){refreshZoneLocale();els.stageRail.innerHTML="";for(const z of zones){const locked=z.index+1>save.unlocked,medal=Number(save.medals[z.index]||0),best=Number(save.best[z.index]||0),card=document.createElement("button");card.type="button";card.className=`stage-card${locked?" locked":""}`;card.disabled=locked;card.dataset.stage=String(z.index);card.innerHTML=`<small>${t("chapter",{n:z.chapter+1})} · ${z.name}</small><strong>${t("zone",{n:z.index+1})}</strong><span>${medal?"★".repeat(medal):locked?t("locked"):t("target",{n:z.quota})}</span><small>${best?t("best",{n:best.toFixed(1)}):z.rule}</small>`;card.addEventListener("click",()=>{if(!locked)startBattle(z.index)});els.stageRail.append(card)}const medals=Object.values(save.medals).reduce((a,n)=>a+Number(n||0),0);els.stageSummary.textContent=`${Math.min(save.unlocked,30)} / 30 · ★ ${medals}`;markCentered()}
function centerCurrentStage(){const target=Math.max(0,Math.min(save.unlocked-1,29));stageIndex=target;const card=els.stageRail.querySelector(`[data-stage="${target}"]`);card?.scrollIntoView({inline:"center",block:"nearest",behavior:"instant"});requestAnimationFrame(markCentered)}
function markCentered(){const cards=[...els.stageRail.querySelectorAll(".stage-card")];if(!cards.length)return;const r=els.stageRail.getBoundingClientRect(),cx=(r.left+r.right)/2;let best=cards[0],d=Infinity;for(const c of cards){const b=c.getBoundingClientRect(),n=Math.abs((b.left+b.right)/2-cx);if(n<d){best=c;d=n}}cards.forEach(c=>c.classList.toggle("centered",c===best));stageIndex=Number(best.dataset.stage)}
els.stageRail.addEventListener("scroll",()=>{clearTimeout(stageScrollTimer);stageScrollTimer=setTimeout(markCentered,90)},{passive:true});
const upgradeData=[["drive","upgradeDrive","upgradeDriveDesc"],["compression","upgradeCompression","upgradeCompressionDesc"],["stability","upgradeStability","upgradeStabilityDesc"]];
function upgradeCost(level){return 9+level*9}
function renderObservatory(){els.gearCount.textContent=t("gears",{n:save.gears});els.upgrades.innerHTML="";for(const [id,name,desc] of upgradeData){const level=save.upgrades[id],cost=upgradeCost(level),button=document.createElement("button");button.type="button";button.className=`upgrade${level>=3?" maxed":""}`;button.innerHTML=`<strong>${t(name)}</strong><small>${t(desc)}</small><b>${"◆".repeat(level)}${"◇".repeat(3-level)}</b><span>${level>=3?t("upgradeMax"):t("upgradeBuy",{n:cost})}</span>`;button.disabled=level>=3;button.addEventListener("click",()=>{if(level>=3)return;if(save.gears<cost){els.stageHint.textContent=t("gears",{n:save.gears});return}save.gears-=cost;save.upgrades[id]++;persist();renderObservatory()});els.upgrades.append(button)}els.wakeButton.textContent=save.wake?t("wakeOwned"):t("wakeBuy");els.wakeButton.disabled=save.wake}
function setTab(tab){const zonesOn=tab==="zones";els.zonePanel.hidden=!zonesOn;els.observatoryPanel.hidden=zonesOn;els.zonesTab.classList.toggle("active",zonesOn);els.observatoryTab.classList.toggle("active",!zonesOn);if(zonesOn)requestAnimationFrame(centerCurrentStage)}
function threshold(){return 17+save.upgrades.compression*1.8+Math.sqrt(Math.max(0,run?.mass||0))*2.28}
function ringRadius(){return 25+threshold()*.52}
function maxStability(){return 3+save.upgrades.stability}
function startBattle(index,{skipTutorial=false}={}){clearResultOwnership();stageIndex=Math.max(0,Math.min(29,index));const zone=buildZone(stageIndex);run={zone,x:500,y:500,vx:0,vy:0,target:null,pointerId:null,dragging:false,keys:new Set(),mass:0,score:0,stability:maxStability(),elapsed:0,timeLeft:zone.timer,chain:0,bestChain:0,chainWindow:0,rescued:0,prismKeys:0,anchors:0,gears:0,knockCooldown:0,stormCooldown:0,paused:false,ended:false,result:null,feedback:t("ready"),wakeTrail:[],effects:[]};els.resultModal.hidden=true;els.leaveModal.hidden=true;els.helpModal.hidden=true;setScreen("battle");syncCanvas();renderHud();track("game_start");if(!save.tutorial&&!skipTutorial){run.paused=true;els.helpModal.hidden=false}else{save.tutorial=true;persist()}}
function rivalTop(){return run?.zone.rivals.reduce((m,r)=>Math.max(m,r.score),0)||0}
function objectiveText(){const z=run.zone,data={score:Math.min(run.score,z.quota),quota:z.quota,rescued:run.rescued,need:z.rescueNeed,rival:rivalTop()};if(z.rescueNeed&&z.rivals.length)return t("objectiveAll",data);if(z.rescueNeed)return t("objectiveRescue",data);if(z.rivals.length)return t("objectiveRival",data);return t("objectiveQuota",data)}
function renderHud(){if(!run)return;const fullZone=`${t("zone",{n:run.zone.index+1})} · ${run.zone.name}`;els.zoneLabel.textContent=matchMedia("(max-width:640px)").matches?t("zone",{n:run.zone.index+1}):fullZone;els.zoneLabel.title=fullZone;els.timerValue.textContent=`${Math.floor(Math.max(0,run.timeLeft)/60)}:${String(Math.ceil(Math.max(0,run.timeLeft))%60).padStart(2,"0")}`;els.scoreValue.textContent=`${Math.min(run.score,run.zone.quota)}/${run.zone.quota}`;els.sizeValue.textContent=threshold().toFixed(0);els.stabilityValue.textContent=String(run.stability);els.chainValue.textContent=`×${Math.max(1,run.chain)}`;els.objective.textContent=objectiveText();els.feedback.textContent=run.feedback}
function absorb(o,owner="player"){if(!o.active)return;o.active=false;if(owner!=="player"){owner.mass+=o.mass;owner.threshold=17+Math.sqrt(owner.mass)*2.1;owner.score+=o.value;return}run.mass+=o.mass;run.chain=run.chainWindow>0?run.chain+1:1;run.chainWindow=2.35;run.bestChain=Math.max(run.bestChain,run.chain);const gain=Math.round(o.value*(1+Math.min(1.5,(run.chain-1)*.08)));run.score+=gain;if(o.type==="prism")run.prismKeys++;if(o.type==="anchor")run.anchors++;if(o.type==="core"){run.rescued++;run.feedback=t("coreRescued")}else run.feedback=run.chain>1?t("chain",{n:run.chain}):t("absorbed",{n:gain});if(o.gear){run.gears++;run.feedback=t("gearFound")}run.effects.push({x:o.x,y:o.y,life:.55,color:o.type==="core"?"#fff176":"#67f7e1"})}
function zoneComplete(){return run.score>=run.zone.quota&&run.rescued>=run.zone.rescueNeed&&(!run.zone.rivals.length||run.score>rivalTop())}
function knockFrom(o){if(run.knockCooldown>0)return;if(o.shielded&&run.prismKeys<3){run.feedback=t("shieldLocked");run.knockCooldown=.35;return}run.stability--;run.knockCooldown=.85;run.chain=0;run.chainWindow=0;const dx=run.x-o.x,dy=run.y-o.y,d=Math.hypot(dx,dy)||1;run.vx+=dx/d*250;run.vy+=dy/d*250;run.feedback=t("tooLarge");if(run.stability<=0)finish(false,"stability")}
function updateRivals(dt){for(const r of run.zone.rivals){if(!r.target?.active||r.target.r>r.threshold)r.target=run.zone.objects.filter(o=>o.active&&!o.shielded&&o.type!=="core"&&o.r<=r.threshold).sort((a,b)=>Math.hypot(a.x-r.x,a.y-r.y)-Math.hypot(b.x-r.x,b.y-r.y))[0]||null;if(r.target){const dx=r.target.x-r.x,dy=r.target.y-r.y,d=Math.hypot(dx,dy)||1,speed=76+run.zone.chapter*4;r.vx+=(dx/d*speed-r.vx)*Math.min(1,dt*2.4);r.vy+=(dy/d*speed-r.vy)*Math.min(1,dt*2.4);r.x+=r.vx*dt;r.y+=r.vy*dt;if(d<r.threshold+12)absorb(r.target,r)}else{r.phase+=dt*.5;r.x=500+Math.cos(r.phase+r.id*Math.PI)*330;r.y=500+Math.sin(r.phase+r.id*Math.PI)*330}}}
function updateObjects(dt){if(run.zone.chapter!==1)return;for(const o of run.zone.objects){if(!o.active)continue;o.x+=o.vx*dt;o.y+=o.vy*dt;const dx=o.x-500,dy=o.y-500,d=Math.hypot(dx,dy);if(d>420){const nx=dx/d,ny=dy/d;o.x=500+nx*420;o.y=500+ny*420;const dot=o.vx*nx+o.vy*ny;o.vx-=2*dot*nx;o.vy-=2*dot*ny}}}
function update(dt){if(!run||run.paused||run.ended)return;run.elapsed+=dt;run.timeLeft-=dt;run.chainWindow=Math.max(0,run.chainWindow-dt);if(!run.chainWindow)run.chain=0;run.knockCooldown=Math.max(0,run.knockCooldown-dt);run.stormCooldown=Math.max(0,run.stormCooldown-dt);let ix=0,iy=0;if(run.keys.has("ArrowLeft")||run.keys.has("KeyA"))ix--;if(run.keys.has("ArrowRight")||run.keys.has("KeyD"))ix++;if(run.keys.has("ArrowUp")||run.keys.has("KeyW"))iy--;if(run.keys.has("ArrowDown")||run.keys.has("KeyS"))iy++;if(ix||iy){run.target=null;const d=Math.hypot(ix,iy);ix/=d;iy/=d}else if(run.target){const dx=run.target.x-run.x,dy=run.target.y-run.y,d=Math.hypot(dx,dy);if(d>12){ix=dx/d;iy=dy/d}else run.target=null}const accel=930+save.upgrades.drive*100,maxSpeed=260+save.upgrades.drive*25;run.vx+=ix*accel*dt;run.vy+=iy*accel*dt;const drag=Math.pow(.055,dt);run.vx*=drag;run.vy*=drag;const speed=Math.hypot(run.vx,run.vy);if(speed>maxSpeed){run.vx=run.vx/speed*maxSpeed;run.vy=run.vy/speed*maxSpeed}if(run.zone.currentPower){const power=Math.max(0,run.zone.currentPower-run.anchors*18),a=run.elapsed*.42+run.zone.index*.7;run.vx+=Math.cos(a)*power*dt;run.vy+=Math.sin(a*.83)*power*.65*dt;if(power>18&&Math.floor(run.elapsed*2)%9===0)run.feedback=t("current")}run.x+=run.vx*dt;run.y+=run.vy*dt;const dx=run.x-500,dy=run.y-500,d=Math.hypot(dx,dy),limit=run.zone.storm?Math.max(285,442-run.elapsed/run.zone.timer*155):442;if(d>limit-ringRadius()*.45){const nx=dx/(d||1),ny=dy/(d||1);run.x=500+nx*(limit-ringRadius()*.45);run.y=500+ny*(limit-ringRadius()*.45);run.vx-=nx*160;run.vy-=ny*160;if(run.zone.storm&&run.stormCooldown<=0){run.stability--;run.stormCooldown=1;run.feedback=t("storm");if(run.stability<=0)finish(false,"stability")}}updateObjects(dt);updateRivals(dt);for(const o of run.zone.objects){if(!o.active)continue;const od=Math.hypot(run.x-o.x,run.y-o.y),canSize=o.r<=threshold(),shieldOpen=!o.shielded||run.prismKeys>=3;if(od<ringRadius()+o.r*.35){if(canSize&&shieldOpen)absorb(o);else if(od<ringRadius()*.7+o.r*.55)knockFrom(o)}}for(const e of run.effects)e.life-=dt;run.effects=run.effects.filter(e=>e.life>0);if(save.wake){run.wakeTrail.push({x:run.x,y:run.y,life:1});if(run.wakeTrail.length>22)run.wakeTrail.shift();for(const p of run.wakeTrail)p.life-=dt*.8}if(zoneComplete())finish(true);else if(run.timeLeft<=0)finish(false,"time");renderHud()}
function medalFor(time,z){return time<=z.goldTime?3:time<=z.silverTime?2:1}
function finish(win,reason="time"){if(!run||run.ended)return;run.ended=true;run.paused=true;let medal=0;if(win){medal=medalFor(run.elapsed,run.zone);save.medals[run.zone.index]=Math.max(Number(save.medals[run.zone.index]||0),medal);const best=Number(save.best[run.zone.index]||0);if(!best||run.elapsed<best)save.best[run.zone.index]=Number(run.elapsed.toFixed(2));save.unlocked=Math.max(save.unlocked,Math.min(30,run.zone.index+2));save.gears+=run.gears+medal;persist();run.result={win:true,medal};els.resultKicker.textContent=t("winKicker");els.resultTitle.textContent=t("winTitle");els.resultText.textContent=t("winText",{n:run.zone.index+1,time:run.elapsed.toFixed(1)})}else{run.result={win:false,medal:0,reason};els.resultKicker.textContent=t("failKicker");els.resultTitle.textContent=t("failTitle");els.resultText.textContent=t(reason==="stability"?"failStability":"failTime")}els.resultTime.textContent=`${run.elapsed.toFixed(1)}s`;els.resultChain.textContent=`×${Math.max(1,run.bestChain)}`;els.resultMedal.textContent=win?t(medal===3?"gold":medal===2?"silver":"bronze"):t("none");els.next.hidden=!win||run.zone.index>=29;els.resultModal.hidden=false;els.battleLive.inert=true;els.battleLive.setAttribute("aria-hidden","true");els.resultModal.setAttribute("role","dialog");els.resultModal.setAttribute("aria-modal","true");(win&&run.zone.index<29?els.next:els.retry).focus({preventScroll:true});track(win?"game_complete":"game_fail")}
function clearResultOwnership(){els.battleLive.inert=false;els.battleLive.removeAttribute("aria-hidden")}
const imagePaths={bg:"arena-bg.webp",player:"orla-ring.webp",shard:"astral-shard.webp",crate:"gear-crate.webp",prism:"prism-block.webp",core:"rescue-core.webp",tower:"tower-debris.webp",crown:"crown-relic.webp",rivalCyan:"rival-cyan.webp",rivalViolet:"rival-violet.webp",anchor:"current-anchor.webp",shield:"prism-shield.webp",storm:"storm-eye.webp",beacon:"rescue-beacon.webp"},images={};
function preload(){return Promise.all(Object.entries(imagePaths).map(([key,file])=>new Promise(resolve=>{const im=new Image;im.onload=()=>{images[key]=im;resolve()};im.onerror=resolve;im.src=`../../assets/animal-rift-salvage/${file}`})))}
function coverImage(im,w,h){if(!im)return;const s=Math.max(w/im.width,h/im.height),sw=w/s,sh=h/s;ctx.drawImage(im,(im.width-sw)/2,(im.height-sh)/2,sw,sh,0,0,w,h)}
function computeView(){const w=els.canvas.width,h=els.canvas.height;view.scale=Math.min(w,h)*.9/WORLD;view.cx=w/2;view.cy=h/2;return{w,h}}
function worldToScreen(x,y){return{x:view.cx+(x-500)*view.scale,y:view.cy+(y-500)*view.scale}}
function drawSprite(im,x,y,size,alpha=1){if(!im)return;const p=worldToScreen(x,y),s=size*view.scale;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,p.x-s/2,p.y-s/2,s,s);ctx.restore()}
function eligibility(o){if(o.shielded&&run.prismKeys<3)return"shield";const th=threshold();return o.r<=th?"ready":o.r<=th*1.27?"near":"large"}
function render(){if(!run)return;const {w,h}=computeView();ctx.clearRect(0,0,w,h);coverImage(images.bg,w,h);ctx.fillStyle="rgba(2,12,31,.18)";ctx.fillRect(0,0,w,h);const center=worldToScreen(500,500),limit=run.zone.storm?Math.max(285,442-run.elapsed/run.zone.timer*155):442;ctx.save();ctx.beginPath();ctx.arc(center.x,center.y,limit*view.scale,0,TAU);ctx.strokeStyle=run.zone.storm?"rgba(182,95,255,.95)":"rgba(89,232,240,.46)";ctx.lineWidth=Math.max(2,5*view.scale);ctx.stroke();if(run.zone.storm){ctx.beginPath();ctx.rect(0,0,w,h);ctx.arc(center.x,center.y,limit*view.scale,0,TAU,true);ctx.fillStyle="rgba(39,9,70,.34)";ctx.fill("evenodd")}ctx.restore();if(save.wake&&run.wakeTrail.length>1){ctx.strokeStyle="rgba(255,236,111,.62)";ctx.lineWidth=Math.max(2,7*view.scale);ctx.beginPath();run.wakeTrail.forEach((p,i)=>{const q=worldToScreen(p.x,p.y);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}for(const o of run.zone.objects.filter(o=>o.active).sort((a,b)=>a.r-b.r)){const p=worldToScreen(o.x,o.y),state=eligibility(o),color=state==="ready"?"#65ffe0":state==="near"?"#ffd45e":state==="shield"?"#c784ff":"#ff657d";ctx.beginPath();ctx.arc(p.x,p.y,(o.r+7)*view.scale,0,TAU);ctx.strokeStyle=color;ctx.lineWidth=Math.max(2,4*view.scale);ctx.shadowColor=color;ctx.shadowBlur=state==="ready"?10:4;ctx.stroke();ctx.shadowBlur=0;drawSprite(images[o.img],o.x,o.y,o.r*3.1);if(o.shielded&&run.prismKeys<3)drawSprite(images.shield,o.x,o.y,o.r*3.55,.7)}for(const r of run.zone.rivals){const p=worldToScreen(r.x,r.y);ctx.beginPath();ctx.arc(p.x,p.y,(r.threshold+8)*view.scale,0,TAU);ctx.fillStyle="rgba(50,10,90,.38)";ctx.fill();drawSprite(r.id?images.rivalViolet:images.rivalCyan,r.x,r.y,(r.threshold+16)*2.3)}for(const e of run.effects){const p=worldToScreen(e.x,e.y);ctx.beginPath();ctx.arc(p.x,p.y,(1-e.life)*55*view.scale,0,TAU);ctx.strokeStyle=e.color;ctx.globalAlpha=Math.max(0,e.life/.55);ctx.lineWidth=5;ctx.stroke();ctx.globalAlpha=1}if(run.target){const p=worldToScreen(run.target.x,run.target.y);ctx.beginPath();ctx.arc(p.x,p.y,14*view.scale,0,TAU);ctx.strokeStyle="#fff176";ctx.lineWidth=3;ctx.stroke()}drawSprite(images.player,run.x,run.y,ringRadius()*3.55);if(run.zone.currentPower&&run.anchors<2){ctx.strokeStyle="rgba(96,230,255,.7)";ctx.lineWidth=4;const a=run.elapsed*.42+run.zone.index*.7;for(let i=-1;i<=1;i++){const x=w*.18+i*40,y=h*.18+i*18;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*70,y+Math.sin(a*.83)*45);ctx.stroke()}}}
function loop(now){if(screen!=="battle")return;const dt=Math.min(.033,Math.max(0,(now-lastFrame)/1000));lastFrame=now;update(dt);render();raf=requestAnimationFrame(loop)}
function startLoop(){cancelAnimationFrame(raf);lastFrame=performance.now();raf=requestAnimationFrame(loop)}
function syncCanvas(){const r=els.canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(els.canvas.width!==w||els.canvas.height!==h){els.canvas.width=w;els.canvas.height=h;render()}else computeView()}
new ResizeObserver(syncCanvas).observe(els.arenaWrap);
function pointerWorld(e){const r=els.canvas.getBoundingClientRect(),px=(e.clientX-r.left)*(els.canvas.width/r.width),py=(e.clientY-r.top)*(els.canvas.height/r.height);computeView();return{x:Math.max(55,Math.min(945,500+(px-view.cx)/view.scale)),y:Math.max(55,Math.min(945,500+(py-view.cy)/view.scale))}}
function pointerDown(e){if(!run||run.paused||run.ended||e.button>0)return;run.dragging=true;run.pointerId=e.pointerId;run.target=pointerWorld(e);els.canvas.setPointerCapture(e.pointerId);els.canvas.focus({preventScroll:true});e.preventDefault()}
function pointerMove(e){if(!run||!run.dragging||e.pointerId!==run.pointerId)return;run.target=pointerWorld(e);e.preventDefault()}
function pointerEnd(e){if(!run||e.pointerId!==run.pointerId)return;run.dragging=false;run.pointerId=null;try{els.canvas.releasePointerCapture(e.pointerId)}catch{}e.preventDefault()}
els.canvas.addEventListener("pointerdown",pointerDown);els.canvas.addEventListener("pointermove",pointerMove);els.canvas.addEventListener("pointerup",pointerEnd);els.canvas.addEventListener("pointercancel",e=>{pointerEnd(e);if(run)run.target=null});
window.addEventListener("keydown",e=>{if(screen!=="battle"||!run)return;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","KeyA","KeyD","KeyW","KeyS"].includes(e.code)){run.keys.add(e.code);e.preventDefault()}if(e.code==="Escape"){if(!els.helpModal.hidden)closeHelp();else if(!els.leaveModal.hidden)continueRun();else if(els.resultModal.hidden)openLeave()}});window.addEventListener("keyup",e=>run?.keys.delete(e.code));window.addEventListener("blur",()=>{if(run){run.keys.clear();run.dragging=false;run.pointerId=null}});
function openLeave(){if(!run||run.ended){setScreen("stage");return}run.paused=true;els.leaveModal.hidden=false;els.leaveContinue.focus({preventScroll:true})}
function continueRun(){els.leaveModal.hidden=true;if(run){run.paused=false;lastFrame=performance.now();els.canvas.focus({preventScroll:true})}}
function closeHelp(){els.helpModal.hidden=true;if(run){run.paused=false;save.tutorial=true;persist();lastFrame=performance.now();els.canvas.focus({preventScroll:true})}}
els.start.addEventListener("click",()=>{setScreen("stage");track("game_start_menu")});els.stageBack.addEventListener("click",()=>setScreen("main"));els.zonesTab.addEventListener("click",()=>setTab("zones"));els.observatoryTab.addEventListener("click",()=>setTab("observatory"));els.battleBack.addEventListener("click",openLeave);els.leaveContinue.addEventListener("click",continueRun);els.leaveStage.addEventListener("click",()=>{els.leaveModal.hidden=true;run=null;setScreen("stage")});els.battleHelp.addEventListener("click",()=>{if(!run)return;run.paused=true;els.helpModal.hidden=false;els.helpClose.focus({preventScroll:true})});els.helpClose.addEventListener("click",closeHelp);els.retry.addEventListener("click",()=>{clearResultOwnership();startBattle(stageIndex,{skipTutorial:true})});els.resultZones.addEventListener("click",()=>{clearResultOwnership();run=null;setScreen("stage")});els.next.addEventListener("click",()=>{clearResultOwnership();startBattle(Math.min(29,stageIndex+1),{skipTutorial:true})});els.wakeButton.addEventListener("click",()=>{if(save.wake)return;if(window.WeightPlayWallet?.spendDiamonds?.(10)){save.wake=true;persist();renderObservatory()}else els.stageHint.textContent=t("wakeBuy")});
function nearestAutoTarget(){const eligible=run.zone.objects.filter(o=>o.active&&o.r<=threshold()&&(!o.shielded||run.prismKeys>=3));eligible.sort((a,b)=>{const ar=a.type==="core"?-500:0,br=b.type==="core"?-500:0;return ar+Math.hypot(a.x-run.x,a.y-run.y)-(br+Math.hypot(b.x-run.x,b.y-run.y))});return eligible[0]||null}
function autoComplete(){if(!run)return false;run.knockCooldown=Number.POSITIVE_INFINITY;run.stormCooldown=Number.POSITIVE_INFINITY;for(let i=0;i<9000&&!run.ended;i++){const target=nearestAutoTarget();if(target)run.target={x:target.x,y:target.y};else{const smallest=run.zone.objects.filter(o=>o.active).sort((a,b)=>a.r-b.r)[0];if(smallest)run.target={x:smallest.x,y:smallest.y}}update(.025)}return Boolean(run.ended&&run.result?.win)}
window.__animalRiftSalvageSmoke={zones,startBattle:(i=0)=>startBattle(i,{skipTutorial:true}),snapshot:()=>run?{zone:run.zone.index,x:run.x,y:run.y,score:run.score,quota:run.zone.quota,mass:run.mass,size:threshold(),stability:run.stability,timeLeft:run.timeLeft,elapsed:run.elapsed,chain:run.chain,bestChain:run.bestChain,rescued:run.rescued,rescueNeed:run.zone.rescueNeed,rival:rivalTop(),active:run.zone.objects.filter(o=>o.active).length,paused:run.paused,ended:run.ended,result:run.result,screen}:null,setTarget:(x,y)=>{if(run)run.target={x,y}},setKeys:(...codes)=>{if(run)run.keys=new Set(codes)},advance:(seconds=.5)=>{if(!run)return;for(let i=0;i<Math.ceil(seconds/.02)&&!run.ended;i++)update(.02)},autoComplete,forceWin:()=>{if(run&&!run.ended){run.score=run.zone.quota;run.rescued=run.zone.rescueNeed;for(const r of run.zone.rivals)r.score=0;finish(true)}},forceFail:()=>{if(run&&!run.ended){run.stability=0;finish(false,"stability")}},save:()=>JSON.parse(JSON.stringify(save)),setSave:value=>{save=normalizeSave(value);persist();renderMainProgress();renderStages();renderObservatory()}};
initLocale();applyLocale();preload().then(()=>{els.loading.hidden=true;syncCanvas();renderMainProgress();renderStages();renderObservatory();render()});
})();
