(function () {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const locales = window.ANIMAL_TIDE_TALLY_LOCALES || {};
  const storage = { get(key) { try { return window.localStorage?.getItem(key) || null; } catch (_) { return null; } }, set(key, value) { try { window.localStorage?.setItem(key, value); } catch (_) { /* restricted storage is non-blocking */ } } };
  const notes = [
    { id: 1, name: "Dawn cove", story: "story1", target: 2, answers: [1, 2, 3] },
    { id: 2, name: "Noon cove", story: "story2", target: 3, answers: [2, 3, 4] },
    { id: 3, name: "Sunset cove", story: "story3", target: 3, answers: [2, 3, 5] }
  ];
  let locale = storage.get("weightplay-animal-tide-tally-locale") || "en";
  if (!locales[locale]) locale = "en";
  let sound = storage.get("weightplay-animal-tide-tally-sound") !== "off";
  let noteIndex = 0; let checks = 0; let sessionChecks = 0; let solved = new Set(); let feedback = ""; let currentScreen = "main";
  const copy = (key, vars = {}) => Object.entries(vars).reduce((out, [name, value]) => out.replaceAll(`{${name}}`, String(value)), (locales[locale] || locales.en)[key] || locales.en[key] || key);
  const announce = (name, data = {}) => { window.dataLayer = window.dataLayer || []; window.dataLayer.push({ event: `animal_tide_tally_${name}`, note: noteIndex + 1, checks, ...data }); };
  const bestValue = () => Number(storage.get("weightplay-animal-tide-tally-best-v1") || 0) || "—";
  function show(screen) { currentScreen = screen; document.querySelectorAll("[data-screen]").forEach((node) => { node.hidden = node.dataset.screen !== screen; }); $("settingsPanel").hidden = true; $("backBtn").hidden = screen === "main"; }
  function renderStatic() { document.documentElement.lang = locale; document.documentElement.dir = "ltr"; document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = copy(node.dataset.i18n); }); $("backBtn").setAttribute("aria-label", copy("back")); $("settingsBtn").setAttribute("aria-label", copy("settings")); $("closeSettings").setAttribute("aria-label", copy("close")); $("localeSelect").setAttribute("aria-label", copy("language")); $("soundBtn").textContent = sound ? copy("on") : copy("off"); $("soundBtn").setAttribute("aria-pressed", String(sound)); $("best").textContent = copy("best", { best: bestValue() }); renderStages(); renderBattle(); renderResult(); }
  function renderStages() { const root = $("stageList"); if (!root) return; root.replaceChildren(); notes.forEach((note, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "stage-card"; button.innerHTML = `<span><strong>${copy(note.name === "Dawn cove" ? "world" : "round")} ${index + 1}</strong><small>${copy(note.story)}</small></span><span class="arrow">${solved.has(index) ? "✓" : "→"}</span>`; button.addEventListener("click", () => startNote(index, true)); root.appendChild(button); }); }
  function startNote(index, fromStage = false) { noteIndex = index; checks = 0; feedback = ""; if (index === 0 || fromStage) sessionChecks = 0; show("battle"); renderBattle(); announce("start"); }
  function renderBattle() { if (!$("answerGrid") || currentScreen !== "battle") return; const note = notes[noteIndex]; $("noteTitle").textContent = `${copy("round")} ${noteIndex + 1}`; $("progressPill").textContent = `${noteIndex + 1} / ${notes.length}`; $("prompt").textContent = copy("prompt"); $("story").textContent = copy(note.story); $("equation").textContent = locale === "zh-Hant" ? "帶來的 − 帶走的 = 留下的" : "arrivals − departures = resting"; const root = $("answerGrid"); root.replaceChildren(); note.answers.forEach((value) => { const button = document.createElement("button"); button.type = "button"; button.className = `answer ${feedback === "correct" && value === note.target ? "chosen" : ""}`; button.setAttribute("aria-label", copy("answerLabel", { value })); button.textContent = String(value); button.addEventListener("click", () => choose(value)); root.appendChild(button); }); $("status").textContent = feedback ? copy(feedback) : ""; $("status").className = feedback === "correct" ? "status good" : feedback === "wrong" ? "status try" : "status"; }
  function choose(value) { if (feedback === "correct") return; checks += 1; sessionChecks += 1; const correct = value === notes[noteIndex].target; feedback = correct ? "correct" : "wrong"; announce("answer", { value, correct }); renderBattle(); if (correct) { solved.add(noteIndex); setTimeout(() => { show("result"); renderResult(); }, 280); } }
  function renderResult() { if (!( $("resultText"))) return; const complete = solved.size === notes.length; $("resultTitle").textContent = complete ? copy("resultTitle") : copy("resultLevel"); $("resultText").textContent = copy("resultText", { count: solved.size, checks: sessionChecks, best: bestValue() }); $("nextBtn").hidden = complete; $("resultMapBtn").hidden = !complete; if (complete) { const old = Number(storage.get("weightplay-animal-tide-tally-best-v1") || 0); if (!old || sessionChecks < old) storage.set("weightplay-animal-tide-tally-best-v1", String(sessionChecks)); $("resultText").textContent = copy("resultText", { count: solved.size, checks: sessionChecks, best: Math.min(old || sessionChecks, sessionChecks) }); } }
  function nextNote() { const nextIndex = noteIndex + 1; if (nextIndex < notes.length) startNote(nextIndex); else { show("stage"); renderStages(); } }
  function goBack() { if (currentScreen === "battle") { show("stage"); renderStages(); } else if (currentScreen === "stage" || currentScreen === "result") show("main"); }
  function bind() { $("startBtn").addEventListener("click", () => startNote(0)); $("mapBtn").addEventListener("click", () => { show("stage"); renderStages(); }); $("resultMapBtn").addEventListener("click", () => { show("stage"); renderStages(); }); $("nextBtn").addEventListener("click", nextNote); $("resetBtn").addEventListener("click", () => { checks = 0; feedback = ""; renderBattle(); announce("reset"); }); $("backBtn").addEventListener("click", goBack); $("settingsBtn").addEventListener("click", () => { $("settingsPanel").hidden = false; }); $("closeSettings").addEventListener("click", () => { $("settingsPanel").hidden = true; }); $("soundBtn").addEventListener("click", () => { sound = !sound; storage.set("weightplay-animal-tide-tally-sound", sound ? "on" : "off"); renderStatic(); }); $("localeSelect").addEventListener("change", (event) => { locale = event.target.value; storage.set("weightplay-animal-tide-tally-locale", locale); renderStatic(); }); }
  function boot() { bind(); $("localeSelect").value = locale; $("loading").hidden = true; $("app").hidden = false; show("main"); renderStatic(); announce("loaded"); }
  window.__ANIMAL_TIDE_TALLY_TEST__ = { notes, startNote, getState: () => ({ noteIndex, solved: [...solved], checks, screen: currentScreen, feedback }) };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot, { once: true }); else boot();
}());
