(() => {
  "use strict";
  const localeKeys = ["en", "zh-Hant", "zh-Hans", "ja", "ko", "es", "pt-BR", "fr", "de", "it", "ru", "hi", "ar"];
  const localeNames = { en:"English", "zh-Hant":"繁體中文", "zh-Hans":"简体中文", ja:"日本語", ko:"한국어", es:"Español", "pt-BR":"Português (Brasil)", fr:"Français", de:"Deutsch", it:"Italiano", ru:"Русский", hi:"हिन्दी", ar:"العربية" };
  const en = { language:"Language", prototype:"Internal prototype", world:"WeightPlay Animal World", title:"Orchard Steward", intro:"Choose one gentle care action each day to balance light, water, and soil.", tagPlan:"Planning", tagBalance:"Balance", tagFamily:"Family", start:"Start the orchard", coverBadge:"3 calm orchard days", guideKicker:"Quick guide", guideTitle:"Read the need, choose the care", guideText:"Each care card shows its exact trade-off. Keep sunlight, water, and soil in their healthy bands for three days.", battleKicker:"Orchard Steward", forecastKicker:"Today's orchard note", resources:"Orchard resources", chooseCare:"Choose one care", exactDeltas:"Exact trade-offs", leaves:"Leaves {value}", day:"Day {current} / {total}", restart:"Restart day", leaveTitle:"Leave the orchard?", leaveText:"This day will reset, but your best leaf count stays on this browser.", continue:"Keep playing", leave:"Leave", resultKicker:"Orchard notes", resultTitle:"A cared-for grove", resultSummary:"You kept the orchard healthy for {value} of 3 days.", leavesLabel:"Healthy days", bestLabel:"Best", replay:"Replay", mainMenu:"Main menu", soundOn:"Sound on", soundOff:"Sound off", good:"The grove is in a healthy band.", needs:"The grove needs another gentle day.", sun:"Sunlight", water:"Water", soil:"Soil", healthy:"Healthy", rain:"Rain barrel", shade:"Shade cloth", sunBasket:"Sun basket", rainDelta:"+2 water · −1 sunlight · +1 soil", shadeDelta:"+2 soil · −1 sunlight · +1 water", sunDelta:"+2 sunlight · −1 water · +1 soil", day1Title:"Clouds gather over the west trees", day1Text:"Water is the urgent need; keep the leaves from drying before the rain arrives.", day2Title:"A bright morning opens the blossoms", day2Text:"The grove can take more sunlight today, but do not let the soil fall behind.", day3Title:"Warm wind crosses the last row", day3Text:"The roots need steady moisture and rich soil before the final harvest.", band:"Goal: {sun} sunlight · {water} water · {soil} soil" };
  const overrides = {
    "zh-Hant": { title:"果園守望", intro:"每天選一個照料動作，平衡陽光、水分與土壤。", start:"開始照料果園", coverBadge:"3 天平靜果園", guideTitle:"讀懂需要，選擇照料", chooseCare:"選一項照料", restart:"重新開始今天", good:"果園維持在健康範圍。", needs:"果園還需要溫柔的一天。", sun:"陽光", water:"水分", soil:"土壤", rain:"雨水桶", shade:"遮陽布", sunBasket:"日光籃", day1Title:"西側樹梢聚起雲朵", day1Text:"水分最重要；在雨來以前，別讓葉子乾渴。", day2Title:"明亮早晨打開花朵", day2Text:"今天果園能承受更多陽光，但別讓土壤落後。", day3Title:"暖風穿過最後一排", day3Text:"最後採收前，根部需要穩定水分與肥沃土壤。" },
    "zh-Hans": { title:"果园守望", intro:"每天选一个照料动作，平衡阳光、水分与土壤。", start:"开始照料果园", coverBadge:"3 天平静果园", guideTitle:"读懂需要，选择照料", chooseCare:"选一项照料", restart:"重新开始今天", good:"果园保持在健康范围。", needs:"果园还需要温柔的一天。", sun:"阳光", water:"水分", soil:"土壤", rain:"雨水桶", shade:"遮阳布", sunBasket:"日光篮", day1Title:"西侧树梢聚起云朵", day1Text:"水分最重要；在雨来以前，别让叶子干渴。", day2Title:"明亮早晨打开花朵", day2Text:"今天果园能承受更多阳光，但别让土壤落后。", day3Title:"暖风穿过最后一排", day3Text:"最后收获前，根部需要稳定水分与肥沃土壤。" },
    ja: { title:"オーチャード・スチュワード", intro:"毎日ひとつの世話を選び、光・水・土を整えます。", start:"果樹園を始める", guideTitle:"必要を読み、世話を選ぼう", chooseCare:"世話をひとつ選ぶ", restart:"今日をやり直す", good:"果樹園は元気な範囲です。", needs:"もう一日、やさしい世話が必要です。", sun:"日光", water:"水", soil:"土", rain:"雨だる", shade:"日よけ布", sunBasket:"ひかりかご" },
    ko: { title:"과수원 지킴이", intro:"매일 돌봄 하나를 골라 햇빛·물·흙을 맞춰요.", start:"과수원 시작하기", guideTitle:"필요를 읽고 돌봄을 골라요", chooseCare:"돌봄 하나 선택", restart:"오늘 다시 시작", good:"과수원이 건강한 범위예요.", needs:"과수원에 하루의 돌봄이 더 필요해요.", sun:"햇빛", water:"물", soil:"흙", rain:"빗물통", shade:"그늘막", sunBasket:"햇빛 바구니" },
    es: { title:"Guardián del Huerto", intro:"Elige un cuidado diario para equilibrar luz, agua y tierra.", start:"Empezar el huerto", guideTitle:"Lee la necesidad y elige", chooseCare:"Elige un cuidado", restart:"Repetir el día", good:"El huerto está en una zona sana.", needs:"El huerto necesita otro día tranquilo.", sun:"Sol", water:"Agua", soil:"Tierra", rain:"Barril de lluvia", shade:"Tela de sombra", sunBasket:"Cesta de sol" },
    "pt-BR": { title:"Guardião do Pomar", intro:"Escolha um cuidado por dia para equilibrar luz, água e terra.", start:"Começar o pomar", guideTitle:"Leia a necessidade e escolha", chooseCare:"Escolha um cuidado", restart:"Recomeçar o dia", good:"O pomar está numa faixa saudável.", needs:"O pomar precisa de mais um dia calmo.", sun:"Sol", water:"Água", soil:"Terra", rain:"Barril de chuva", shade:"Tela de sombra", sunBasket:"Cesta de sol" },
    fr: { title:"Gardien du Verger", intro:"Choisissez un soin par jour pour équilibrer lumière, eau et terre.", start:"Commencer le verger", guideTitle:"Lisez le besoin et choisissez", chooseCare:"Choisissez un soin", restart:"Recommencer le jour", good:"Le verger est dans une zone saine.", needs:"Le verger a besoin d'un autre jour doux.", sun:"Soleil", water:"Eau", soil:"Terre", rain:"Baril de pluie", shade:"Toile d'ombre", sunBasket:"Panier de soleil" },
    de: { title:"Obsthüter", intro:"Wähle täglich eine Pflege, um Licht, Wasser und Erde auszubalancieren.", start:"Obstgarten starten", guideTitle:"Bedarf lesen, Pflege wählen", chooseCare:"Eine Pflege wählen", restart:"Tag neu starten", good:"Der Obstgarten ist im gesunden Bereich.", needs:"Der Obstgarten braucht einen weiteren ruhigen Tag.", sun:"Sonne", water:"Wasser", soil:"Erde", rain:"Regentonne", shade:"Schattensegel", sunBasket:"Sonnenkorb" },
    it: { title:"Custode del Frutteto", intro:"Scegli una cura al giorno per bilanciare luce, acqua e terra.", start:"Inizia il frutteto", guideTitle:"Leggi il bisogno e scegli", chooseCare:"Scegli una cura", restart:"Ripeti il giorno", good:"Il frutteto è nella fascia sana.", needs:"Il frutteto ha bisogno di un altro giorno calmo.", sun:"Sole", water:"Acqua", soil:"Terra", rain:"Barile della pioggia", shade:"Tela ombreggiante", sunBasket:"Cesto del sole" },
    ru: { title:"Смотритель сада", intro:"Каждый день выбирайте заботу, чтобы уравновесить свет, воду и почву.", start:"Открыть сад", guideTitle:"Прочитайте нужду и выберите заботу", chooseCare:"Выберите заботу", restart:"Начать день заново", good:"Сад в здоровом диапазоне.", needs:"Саду нужен ещё один спокойный день.", sun:"Свет", water:"Вода", soil:"Почва", rain:"Бочка дождя", shade:"Тент от солнца", sunBasket:"Корзина света" },
    hi: { title:"बाग़ का रखवाला", intro:"हर दिन एक देखभाल चुनकर धूप, पानी और मिट्टी संतुलित करें।", start:"बाग़ शुरू करें", guideTitle:"ज़रूरत पढ़ें, देखभाल चुनें", chooseCare:"एक देखभाल चुनें", restart:"दिन फिर शुरू करें", good:"बाग़ स्वस्थ सीमा में है।", needs:"बाग़ को एक शांत दिन और चाहिए।", sun:"धूप", water:"पानी", soil:"मिट्टी", rain:"बारिश का पीपा", shade:"छाँव का कपड़ा", sunBasket:"धूप की टोकरी" },
    ar: { title:"حارس البستان", intro:"اختر عناية واحدة كل يوم لموازنة الضوء والماء والتربة.", start:"ابدأ البستان", guideTitle:"اقرأ الحاجة واختر العناية", chooseCare:"اختر عناية واحدة", restart:"أعد اليوم", good:"البستان ضمن النطاق الصحي.", needs:"يحتاج البستان إلى يوم هادئ آخر.", sun:"الشمس", water:"الماء", soil:"التربة", rain:"برميل المطر", shade:"قماش الظل", sunBasket:"سلة الشمس" }
  };
  const copy = Object.fromEntries(localeKeys.map((key) => [key, { ...en, ...(overrides[key] || {}) }]));
  const days = [
    { start:{sun:3,water:3,soil:2}, min:{sun:2,water:4,soil:3}, title:"day1Title", text:"day1Text" },
    { start:{sun:4,water:3,soil:3}, min:{sun:5,water:2,soil:4}, title:"day2Title", text:"day2Text" },
    { start:{sun:3,water:4,soil:4}, min:{sun:3,water:3,soil:5}, title:"day3Title", text:"day3Text" }
  ];
  const actions = [
    { id:"rain", icon:"💧", name:"rain", delta:{sun:-1,water:2,soil:1}, deltaKey:"rainDelta" },
    { id:"shade", icon:"🌿", name:"shade", delta:{sun:-1,water:1,soil:2}, deltaKey:"shadeDelta" },
    { id:"sunBasket", icon:"☀️", name:"sunBasket", delta:{sun:2,water:-1,soil:1}, deltaKey:"sunDelta" }
  ];
  const $ = (id) => document.getElementById(id);
  const state = { locale:"en", sound:true, day:0, leaves:0, meters:{...days[0].start}, selected:false, best:0 };
  const storage = { get(key){try{return localStorage.getItem(key)}catch(_){return null}}, set(key,value){try{localStorage.setItem(key,value)}catch(_){}} };
  const routeMap = {en:"en", "zh-tw":"zh-Hant", "zh-hant":"zh-Hant", "zh-cn":"zh-Hans", "zh-hans":"zh-Hans", ja:"ja", ko:"ko", es:"es", "pt-br":"pt-BR", fr:"fr", de:"de", it:"it", ru:"ru", hi:"hi", ar:"ar"};
  function t(key, vars={}){const value=(copy[state.locale]||copy.en)[key]||copy.en[key]||key;return value.replace(/\{(\w+)\}/g,(_,name)=>String(vars[name]??""));}
  function queryLocale(){const query=new URLSearchParams(location.search).get("lang");const route=location.pathname.split("/").filter(Boolean)[0]?.toLowerCase();return query&&copy[query]?query:routeMap[route]||"en";}
  function applyLocale(){document.documentElement.lang=state.locale==="zh-Hant"?"zh-TW":state.locale;document.documentElement.dir=state.locale==="ar"?"rtl":"ltr";document.querySelectorAll("[data-copy]").forEach((node)=>{node.textContent=t(node.dataset.copy)});$("settingsButton").setAttribute("aria-label",t("language"));$("soundButton").textContent=state.sound?t("soundOn"):t("soundOff");$("soundButton").setAttribute("aria-pressed",String(state.sound));$("battleSoundButton").setAttribute("aria-label",state.sound?t("soundOn"):t("soundOff"));$("battleSoundButton").setAttribute("aria-pressed",String(state.sound));renderBattle();}
  function populateLocales(){const select=$("localeSelect");localeKeys.forEach((key)=>{const option=document.createElement("option");option.value=key;option.textContent=localeNames[key];select.append(option)});select.value=state.locale;select.addEventListener("change",()=>{state.locale=select.value;storage.set("weightplay-orchard-steward-locale",state.locale);applyLocale()});}
  function tone(kind){if(!state.sound||!(window.AudioContext||window.webkitAudioContext))return;try{const Audio=window.AudioContext||window.webkitAudioContext;const audio=new Audio();const oscillator=audio.createOscillator();const gain=audio.createGain();oscillator.frequency.value=kind==="good"?620:180;gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.02,audio.currentTime+.01);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.12);oscillator.connect(gain).connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.13);oscillator.addEventListener("ended",()=>audio.close(),{once:true})}catch(_){} }
  function showView(view){$("mainView").hidden=view!=="main";$("battleView").hidden=view!=="battle";$("resultView").hidden=view!=="result";window.scrollTo(0,0)}
  function renderMeters(){const labels=["sun","water","soil"];$("meters").innerHTML=labels.map((key)=>`<div class="meter-row"><div class="meter-label"><span>${t(key)}</span><span class="meter-value">${state.meters[key]} / 6</span></div><div class="meter-track"><div class="meter-fill" style="width:${Math.round(state.meters[key]/6*100)}%"></div></div></div>`).join("");}
  function renderBattle(){if(!$('dayLabel'))return;const day=days[state.day];$("dayLabel").textContent=t("day",{current:state.day+1,total:days.length});$("forecastTitle").textContent=t(day.title);$("forecastText").textContent=`${t(day.text)} ${t("band",{sun:day.min.sun,water:day.min.water,soil:day.min.soil})}`;$("leafCount").textContent=t("leaves",{value:state.leaves});renderMeters();$("actions").innerHTML=actions.map((action)=>`<button class="action-button" type="button" data-action="${action.id}" ${state.selected?"disabled":""}><span class="action-icon" aria-hidden="true">${action.icon}</span><span class="action-name">${t(action.name)}</span><span class="action-delta">${t(action.deltaKey)}</span></button>`).join("");$("feedback").textContent=state.feedback||"";$("feedback").className=`feedback ${state.feedbackClass||""}`;$("leafCount").setAttribute("aria-label",t("leaves",{value:state.leaves}));}
  function start(){state.day=0;state.leaves=0;state.best=0;startDay();showView("battle");}
  function startDay(){state.meters={...days[state.day].start};state.selected=false;state.feedback="";state.feedbackClass="";renderBattle();}
  function choose(id){if(state.selected)return;const action=actions.find((item)=>item.id===id);if(!action)return;state.selected=true;Object.keys(state.meters).forEach((key)=>{state.meters[key]=Math.max(0,Math.min(6,state.meters[key]+action.delta[key]))});const day=days[state.day];const good=Object.keys(day.min).every((key)=>state.meters[key]>=day.min[key]);if(good){state.leaves+=1;state.feedback=t("good");state.feedbackClass="good";tone("good")}else{state.feedback=t("needs");state.feedbackClass="bad";tone("bad")}renderBattle();window.setTimeout(()=>{if(state.day<days.length-1){state.day+=1;startDay()}else finish()},850)}
  function finish(){const old=Number(storage.get("weightplay-orchard-steward-best")||0);state.best=Math.max(old,state.leaves);storage.set("weightplay-orchard-steward-best",String(state.best));$("resultTitle").textContent=state.leaves===3?t("resultTitle"):t("needs");$("resultSummary").textContent=t("resultSummary",{value:state.leaves});$("resultLeaves").textContent=String(state.leaves);$("resultBest").textContent=String(state.best);showView("result");}
  function toggleSettings(){const panel=$("settingsPanel");const open=panel.hidden;panel.hidden=!open;$("settingsButton").setAttribute("aria-expanded",String(open));}
  function toggleSound(){state.sound=!state.sound;applyLocale();}
  function openLeave(){$("leaveDialog").hidden=false;$("continueButton").focus()}
  function closeLeave(){$("leaveDialog").hidden=true;$("homeFromBattle").focus()}
  function goHome(){showView("main");$("leaveDialog").hidden=true;applyLocale()}
  state.locale=queryLocale();
  document.addEventListener("DOMContentLoaded",()=>{populateLocales();applyLocale();$("startButton").addEventListener("click",start);$("replayButton").addEventListener("click",start);$("restartDay").addEventListener("click",startDay);$("actions").addEventListener("click",(event)=>{const button=event.target.closest("button[data-action]");if(button)choose(button.dataset.action)});$("settingsButton").addEventListener("click",toggleSettings);$("soundButton").addEventListener("click",toggleSound);$("battleSoundButton").addEventListener("click",toggleSound);$("homeFromBattle").addEventListener("click",openLeave);$("continueButton").addEventListener("click",closeLeave);$("confirmLeaveButton").addEventListener("click",goHome);$("homeFromResult").addEventListener("click",goHome);});
  window.ORCHARD_STEWARD_TEST={state,days,actions,start,startDay,choose,applyLocale};
})();
