/* Complete, authored runtime and first-response copy. No cross-language fallback. */
(function (root) {
  'use strict';
  const keys = ['start','stages','stage','reading','stars','progress','locked','done','waterline','dial','minus','plus','seal','reset','hint','remember','target','tolerance','wrong','correct','next','replay','leaveTitle','leaveBody','continue','leave','saveError','loadError','solution','reference','results','attempts','how','rules','tips','save','faqTitle','about'];
  const data = {
    en: {
      title:'Tide Level Calibration',
      ui:['Start Game','Stages','Stage {value}','Reading {current}/{total}','Stars','{count}/{total} stages completed','Locked','Completed','Water level','Dial','Lower by 1','Raise by 1','Seal','Reset','Hint {count}/2','Ready','Target {value}%','Tolerance: ±{value} percentage points','Not yet. Adjust and try again.','Calibrated!','Next Stage','Replay','Leave this stage?','This stage restarts. Completed stages and best results stay saved.','Continue','Stages','Storage is unavailable. This session still works, but progress may not survive closing the page.','The game could not load. Reload the page to retry.','Correct water level: {value}%','Reference','Stage complete','{count} attempts · {stars}/3 stars','How to play','Rules and progression','Calibration tips','Progress and storage','Questions','About the game'],
      modes:['Read the tide','Remember the mark','Correct the gauge','Balance the pair','Read a fraction','Reef examination'],
      clues:['Match the water surface to the gold marker.','Study the mark, then select Ready to hide it. There is no countdown.','Recreate the water level you remembered.','Water level = dial {bias}. Match the actual water to {value}%.','The reference is {value}%. Fill your glass so the two levels total 100%.','Set the water to {n}/{d} of the scale height.'],
      guide:['Calibrate animated tide glasses through visual reading, memory, gauge offsets, complementary levels and fractions.','Help Nori check the reef’s tide gauges. This is a number-and-observation puzzle, not a realistic tide forecast or a liquid-sorting game. Each chapter introduces a different reason to think before sealing a reading.','Select an unlocked stage. Drag the slider or focus it and use the arrow keys; the minus and plus buttons adjust one point. Read the instruction, check the water surface, then select Seal. A miss lets you adjust the same reading without a timer or life limit.','There are 30 stages in six chapters, with five readings per stage. All five must be sealed to advance campaign progress by one stage. Later chapters hide a remembered mark, add a signed gauge offset, ask for two levels totaling 100%, or express the target as a fraction. Every fifth stage is a checkpoint with tighter tolerance.','Three stars require no mistakes and no hints. Up to three mistakes and one hint earn two stars; other successful runs earn one. Two hints are available per stage. Watch the gold mark rather than the bottle’s decorative rim. For an offset, subtract the signed offset from the desired water level to find the dial setting.','Completed stages, best stars and fewest attempts are stored in this browser when local storage is available. Replay cannot erase a better record. Unfinished readings restart when you leave. Old prototype records are kept, but do not unlock new campaign stages.'],
      faq:[['Does five readings mean five stages?','No. Completing all five readings advances the campaign by exactly one stage.'],['Can I take my time in memory rounds?','Yes. Study the mark for as long as needed, then select Ready. The mark disappears until you use a hint or finish the reading.'],['Why does the dial differ from the water level?','Gauge-offset rounds add the signed offset to the dial. For a target of 60% with an offset of +8, set the dial to 52.']],
      tags:['Visual estimation','Memory puzzle','Fraction practice']
    },
    'zh-Hant': {
      title:'潮汐水位校準',
      ui:['開始遊戲','關卡','第 {value} 關','校準 {current}/{total}','星星','已完成 {count}/{total} 關','尚未解鎖','已完成','水位','旋鈕讀數','降低 1 格','提高 1 格','封存','重設','提示 {count}/2','記好了','目標 {value}%','容許誤差：±{value} 個百分點','還沒對準，調整後再試一次。','校準成功！','下一關','重玩','離開這一關？','本關會重新開始，已通關進度與最佳成績會保留。','繼續','返回關卡','目前無法儲存；仍可遊玩，但關閉網頁後可能失去這次進度。','遊戲載入失敗，請重新整理後再試。','正確水位：{value}%','參考瓶','關卡完成','嘗試 {count} 次 · {stars}/3 星','操作方式','規則與關卡變化','校準技巧','進度與存檔','常見問題','遊戲介紹'],
      modes:['刻度讀取','潮位記憶','儀表校正','雙瓶互補','分數水位','礁岩總測驗'],
      clues:['把水面對準金色刻度線。','先觀察刻度，按「記好了」後隱藏；沒有倒數時間。','重現剛才記住的水位。','實際水位＝旋鈕讀數 {bias}。把水位調到 {value}%。','參考瓶為 {value}%。讓兩瓶水位相加等於 100%。','把水位調到刻度全高的 {n}/{d}。'],
      guide:['透過刻度、記憶、儀表偏差、互補水位與分數題，校準會流動的潮汐玻璃瓶。','協助 Nori 檢查礁岩上的潮汐儀表。這是結合觀察與數字推理的謎題，不是實際潮汐預報，也不是液體分類遊戲。每個章節都有不同的判斷方式，而非只重複拖到相同數字。','選擇已解鎖關卡，拖曳滑桿調整讀數；也可將焦點移到滑桿後使用方向鍵，或用加減按鈕逐格微調。讀清題目，確認水面，再按封存。答錯後可繼續調整同一題，沒有生命或時間限制。','共有 30 關，分為六個章節，每關包含五次校準。五題全部封存才算通過一關，總進度只增加一格。後續題型會隱藏記住的刻度、加入正負儀表偏差、要求雙瓶水位相加為 100%，或用分數表示目標。每五關設有誤差更小的檢查關。','完全不失誤且不用提示可得三星；失誤不超過三次、提示不超過一次可得二星，其餘完成紀錄為一星。每關有兩次提示。對準的是金色刻度與水面，不是瓶身裝飾邊框。偏差題先用目標水位減去帶正負號的偏差，便能得到旋鈕讀數。','瀏覽器允許本機儲存時，會保留已通過關卡、最佳星數與最少嘗試次數。重玩不會覆蓋較佳紀錄；離開時尚未完成的關卡會重來。舊原型的紀錄不會被刪除，但不能用來推算新關卡的解鎖進度。'],
      faq:[['五次校準會增加五關進度嗎？','不會。完成一關中的五次校準，總進度只增加一關。'],['記憶題一定要很快作答嗎？','不用。觀察時間由你決定，按下「記好了」才隱藏刻度；使用提示或完成該題後才能再看到答案。'],['為什麼旋鈕讀數不等於水位？','儀表偏差題會把正負偏差加到旋鈕讀數。例如目標是 60%、偏差是 +8，旋鈕應設定為 52。']],
      tags:['視覺估讀','記憶謎題','分數練習']
    },
    'zh-Hans': {
      title:'潮汐水位校准',
      ui:['开始游戏','关卡','第 {value} 关','校准 {current}/{total}','星星','已完成 {count}/{total} 关','尚未解锁','已完成','水位','旋钮读数','降低 1 格','提高 1 格','封存','重设','提示 {count}/2','记好了','目标 {value}%','允许误差：±{value} 个百分点','还没对准，调整后再试一次。','校准成功！','下一关','重玩','离开这一关？','本关会重新开始，已通关进度与最佳成绩会保留。','继续','返回关卡','目前无法保存；仍可游玩，但关闭网页后可能失去这次进度。','游戏加载失败，请刷新后再试。','正确水位：{value}%','参考瓶','关卡完成','尝试 {count} 次 · {stars}/3 星','操作方式','规则与关卡变化','校准技巧','进度与存档','常见问题','游戏介绍'],
      modes:['刻度读取','潮位记忆','仪表校正','双瓶互补','分数水位','礁岩总测验'],
      clues:['把水面对准金色刻度线。','先观察刻度，按“记好了”后隐藏；没有倒计时。','重现刚才记住的水位。','实际水位＝旋钮读数 {bias}。把水位调到 {value}%。','参考瓶为 {value}%。让两瓶水位相加等于 100%。','把水位调到刻度全高的 {n}/{d}。'],
      guide:['通过刻度、记忆、仪表偏差、互补水位与分数题，校准会流动的潮汐玻璃瓶。','协助 Nori 检查礁岩上的潮汐仪表。这是结合观察与数字推理的谜题，不是实际潮汐预报，也不是液体分类游戏。每个章节都有不同的判断方式，而非只重复拖到相同数字。','选择已解锁关卡，拖动滑块调整读数；也可将焦点移到滑块后使用方向键，或用加减按钮逐格微调。读清题目，确认水面，再按封存。答错后可继续调整同一题，没有生命或时间限制。','共有 30 关，分为六个章节，每关包含五次校准。五题全部封存才算通过一关，总进度只增加一格。后续题型会隐藏记住的刻度、加入正负仪表偏差、要求双瓶水位相加为 100%，或用分数表示目标。每五关设有误差更小的检查关。','完全不失误且不用提示可得三星；失误不超过三次、提示不超过一次可得二星，其余完成记录为一星。每关有两次提示。对准的是金色刻度与水面，不是瓶身装饰边框。偏差题先用目标水位减去带正负号的偏差，便能得到旋钮读数。','浏览器允许本地存储时，会保留已通过关卡、最佳星数与最少尝试次数。重玩不会覆盖较佳记录；离开时尚未完成的关卡会重来。旧原型的记录不会被删除，但不能用来推算新关卡的解锁进度。'],
      faq:[['五次校准会增加五关进度吗？','不会。完成一关中的五次校准，总进度只增加一关。'],['记忆题一定要很快作答吗？','不用。观察时间由你决定，按下“记好了”才隐藏刻度；使用提示或完成该题后才能再看到答案。'],['为什么旋钮读数不等于水位？','仪表偏差题会把正负偏差加到旋钮读数。例如目标是 60%、偏差是 +8，旋钮应设置为 52。']],
      tags:['视觉估读','记忆谜题','分数练习']
    },
    ja: {
      title:'潮位合わせ',
      ui:['ゲーム開始','ステージ','ステージ {value}','測定 {current}/{total}','星','{count}/{total} ステージ達成','未解放','達成','水位','ダイヤル','1 下げる','1 上げる','確定','リセット','ヒント {count}/2','覚えた','目標 {value}%','許容誤差：±{value} ポイント','もう少し。調整して再挑戦。','調整成功！','次へ','再挑戦','このステージを離れますか？','このステージは最初からになります。達成状況と最高記録は残ります。','続ける','ステージへ','保存できません。この画面では遊べますが、閉じると進行状況が失われる場合があります。','読み込めませんでした。ページを再読み込みしてください。','正しい水位：{value}%','基準の瓶','ステージ達成','{count} 回の試行 · 星 {stars}/3','遊び方','ルールと進行','調整のコツ','進行状況の保存','よくある質問','ゲームについて'],
      modes:['目盛りを読む','潮位を覚える','計器を補正','二つの瓶','分数の水位','サンゴ礁の試験'],
      clues:['水面を金色の目盛りに合わせます。','目盛りを見て「覚えた」を選ぶと隠れます。時間制限はありません。','覚えた水位を再現します。','水位＝ダイヤル {bias}。実際の水位を {value}% にします。','基準の瓶は {value}%。二つの水位の合計を 100% にします。','目盛り全体の高さの {n}/{d} に水位を合わせます。'],
      guide:['目盛り、記憶、計器のずれ、二つの水位の和、分数を使って、動く潮位の瓶を調整しましょう。','Nori と一緒にサンゴ礁の計器を点検する観察と数のパズルです。実際の潮位予測や液体の色分けゲームではありません。章ごとに異なる考え方が必要です。','解放されたステージを選び、スライダーを動かします。スライダーにフォーカスを置いて矢印キーを使うか、加減ボタンで一つずつ調整できます。指示と水面を確認して確定します。失敗しても同じ問題を続けられ、制限時間や残機はありません。','全 30 ステージ、六つの章があり、各ステージは五つの測定で構成されます。五つ全部を確定すると進行状況が一ステージ進みます。記憶、正負の計器補正、合計 100% の組み合わせ、分数が順に登場します。五ステージごとの確認問題は許容誤差が小さくなります。','失敗もヒントもゼロなら星三つ。失敗三回以下かつヒント一回以下なら星二つ、それ以外の達成は星一つです。ヒントは一ステージに二回まで。瓶の飾りではなく金色の目盛りを見ましょう。計器補正では、目標から符号付きのずれを引くとダイヤル値が求められます。','保存が利用できるブラウザーでは達成ステージ、最高の星数、最少試行回数が残ります。再挑戦で良い記録が消えることはありません。途中で離れたステージはやり直しです。旧試作版の記録は残しますが、新しいステージの解放には使いません。'],
      faq:[['五つの測定で五ステージ進みますか？','いいえ。五つ全部を終えると一ステージだけ進みます。'],['記憶の問題を急ぐ必要はありますか？','ありません。「覚えた」を選ぶまで自由に観察できます。その後はヒントを使うか測定を終えるまで目標が隠れます。'],['ダイヤルと水位が違うのはなぜですか？','計器補正の問題では符号付きのずれが加算されます。目標 60%、ずれ +8 ならダイヤルは 52 です。']],
      tags:['視覚で推定','記憶パズル','分数の練習']
    },
    ko: {
      title:'조수 수위 맞추기',
      ui:['게임 시작','스테이지','스테이지 {value}','측정 {current}/{total}','별','{count}/{total} 스테이지 완료','잠김','완료','수위','다이얼','1 낮추기','1 높이기','확정','초기화','힌트 {count}/2','기억했어요','목표 {value}%','허용 오차: ±{value}%p','아직 안 맞아요. 조정해서 다시 해 보세요.','보정 성공!','다음','다시 하기','이 스테이지를 나갈까요?','현재 스테이지는 다시 시작합니다. 완료한 스테이지와 최고 기록은 유지됩니다.','계속','스테이지로','저장할 수 없습니다. 계속 플레이할 수 있지만 페이지를 닫으면 진행 상황이 사라질 수 있습니다.','게임을 불러오지 못했습니다. 페이지를 새로고침해 주세요.','정확한 수위: {value}%','기준 병','스테이지 완료','{count}회 시도 · 별 {stars}/3','플레이 방법','규칙과 진행','보정 요령','진행 상황 저장','자주 묻는 질문','게임 소개'],
      modes:['눈금 읽기','수위 기억','계기 보정','두 병의 합','분수 수위','산호초 시험'],
      clues:['수면을 금색 눈금에 맞추세요.','눈금을 본 뒤 기억했어요를 누르면 가려집니다. 제한 시간은 없습니다.','기억한 수위를 재현하세요.','수위 = 다이얼 {bias}. 실제 수위를 {value}%에 맞추세요.','기준 병은 {value}%입니다. 두 수위의 합을 100%로 만드세요.','눈금 전체 높이의 {n}/{d}에 수위를 맞추세요.'],
      guide:['눈금, 기억, 계기 오차, 상보적인 수위와 분수 문제로 움직이는 조수 유리병을 보정하세요.','Nori와 함께 산호초의 수위계를 점검하는 관찰·수 추리 퍼즐입니다. 실제 조수 예보나 액체 색깔 분류 게임은 아닙니다. 장마다 다른 판단 방식이 필요합니다.','열린 스테이지를 선택하고 슬라이더를 움직이세요. 슬라이더에 초점을 맞춘 뒤 방향키를 쓰거나 더하기·빼기 버튼으로 한 칸씩 조정할 수도 있습니다. 지시와 수면을 확인하고 확정을 누르세요. 틀려도 같은 문제를 계속 풀 수 있으며 시간이나 목숨 제한이 없습니다.','여섯 장에 걸쳐 30개 스테이지가 있으며 스테이지마다 측정 다섯 번을 완료해야 합니다. 다섯 번을 모두 마쳐야 전체 진행이 한 단계 늘어납니다. 기억, 부호가 있는 계기 오차, 합이 100%인 두 수위와 분수 문제가 차례로 등장합니다. 다섯 번째 스테이지마다 허용 오차가 좁아집니다.','실수와 힌트가 없으면 별 세 개입니다. 실수 세 번 이하, 힌트 한 번 이하이면 별 두 개, 그 밖에 완료한 경우는 별 한 개입니다. 힌트는 스테이지당 두 번입니다. 병의 장식 대신 금색 눈금을 보세요. 오차 문제에서는 목표에서 부호가 있는 오차를 빼면 다이얼 값이 됩니다.','브라우저 저장이 가능하면 완료한 스테이지, 최고 별 수, 최소 시도 횟수가 저장됩니다. 다시 해도 더 좋은 기록은 지워지지 않습니다. 도중에 나가면 그 스테이지는 처음부터 시작합니다. 이전 시제품 기록은 남지만 새 스테이지를 열어 주지는 않습니다.'],
      faq:[['측정 다섯 번이면 다섯 스테이지가 완료되나요?','아니요. 다섯 번 모두 완료해야 한 스테이지만 완료됩니다.'],['기억 문제는 빨리 풀어야 하나요?','아니요. 기억했어요를 누르기 전까지 원하는 만큼 관찰하세요. 이후 힌트를 쓰거나 측정을 마칠 때까지 목표가 가려집니다.'],['다이얼과 수위는 왜 다른가요?','계기 오차 문제는 다이얼에 부호가 있는 오차를 더합니다. 목표가 60%, 오차가 +8이면 다이얼은 52입니다.']],
      tags:['시각적 추정','기억 퍼즐','분수 연습']
    },
    es: {
      title:'Ajuste de Mareas',
      ui:['Jugar','Niveles','Nivel {value}','Lectura {current}/{total}','Estrellas','{count}/{total} niveles completados','Bloqueado','Completado','Nivel de agua','Dial','Bajar 1','Subir 1','Sellar','Reiniciar','Pista {count}/2','Listo','Objetivo {value}%','Tolerancia: ±{value} puntos porcentuales','Todavía no. Ajusta y vuelve a probar.','¡Calibrado!','Siguiente','Repetir','¿Salir de este nivel?','Este nivel se reiniciará. Se conservan los niveles completados y tus mejores marcas.','Continuar','Niveles','No se puede guardar. Puedes jugar, pero al cerrar la página podrías perder este progreso.','No se pudo cargar el juego. Recarga la página.','Nivel correcto: {value}%','Referencia','Nivel completado','{count} intentos · {stars}/3 estrellas','Cómo jugar','Reglas y avance','Consejos','Progreso y guardado','Preguntas','Acerca del juego'],
      modes:['Leer la marca','Recordar la marea','Corregir el medidor','Equilibrar dos vasos','Leer una fracción','Prueba del arrecife'],
      clues:['Alinea la superficie con la marca dorada.','Observa la marca y pulsa Listo para ocultarla. No hay cuenta atrás.','Recrea el nivel que recuerdas.','Agua = dial {bias}. Ajusta el agua a {value}%.','La referencia es {value}%. Los dos niveles deben sumar 100%.','Ajusta el agua a {n}/{d} de la altura de la escala.'],
      guide:['Calibra vasos de marea animados con lectura visual, memoria, errores del medidor, niveles complementarios y fracciones.','Ayuda a Nori a revisar los medidores del arrecife. Es un rompecabezas de observación y números, no una previsión real de mareas ni un juego de clasificar líquidos. Cada capítulo propone una forma distinta de razonar.','Elige un nivel desbloqueado y mueve el deslizador. También puedes enfocarlo y usar las flechas, o los botones de suma y resta para ajustar un punto. Lee la indicación, mira el agua y pulsa Sellar. Si fallas, ajusta la misma lectura: no hay vidas ni límite de tiempo.','Hay 30 niveles en seis capítulos y cinco lecturas por nivel. Solo al completar las cinco avanzas un nivel. Después aparecen marcas ocultas, errores positivos o negativos del medidor, parejas que suman 100% y fracciones. Cada quinto nivel reduce la tolerancia.','Sin errores ni pistas consigues tres estrellas. Con hasta tres errores y una pista obtienes dos; las demás partidas completadas dan una. Hay dos pistas por nivel. Usa la marca dorada, no el borde decorativo. Para corregir el medidor, resta el error con su signo al nivel deseado.','Si el navegador permite almacenamiento local, guarda niveles completados, mejores estrellas y menos intentos. Repetir no borra una marca mejor. Al salir, el nivel sin terminar empieza de nuevo. Se conservan los registros del prototipo, pero no desbloquean la campaña nueva.'],
      faq:[['¿Cinco lecturas cuentan como cinco niveles?','No. Las cinco lecturas juntas completan un solo nivel.'],['¿Debo apresurarme en las pruebas de memoria?','No. Observa hasta pulsar Listo. La marca queda oculta hasta usar una pista o terminar la lectura.'],['¿Por qué el dial no coincide con el agua?','En esas pruebas se suma el error con signo al dial. Para un objetivo de 60% y un error de +8, pon el dial en 52.']],
      tags:['Estimación visual','Memoria','Práctica de fracciones']
    },
    'pt-BR': {
      title:'Ajuste das Marés',
      ui:['Jogar','Fases','Fase {value}','Leitura {current}/{total}','Estrelas','{count}/{total} fases concluídas','Bloqueada','Concluída','Nível da água','Seletor','Diminuir 1','Aumentar 1','Selar','Reiniciar','Dica {count}/2','Pronto','Alvo {value}%','Tolerância: ±{value} pontos percentuais','Ainda não. Ajuste e tente de novo.','Calibrado!','Próxima','Repetir','Sair desta fase?','Esta fase recomeçará. Fases concluídas e melhores resultados serão mantidos.','Continuar','Fases','Não foi possível salvar. Você pode jogar, mas pode perder este progresso ao fechar a página.','O jogo não carregou. Recarregue a página.','Nível correto: {value}%','Referência','Fase concluída','{count} tentativas · {stars}/3 estrelas','Como jogar','Regras e progresso','Dicas','Progresso salvo','Perguntas','Sobre o jogo'],
      modes:['Ler a marca','Lembrar a maré','Corrigir o medidor','Equilibrar os copos','Ler uma fração','Teste do recife'],
      clues:['Alinhe a superfície com a marca dourada.','Observe a marca e selecione Pronto para ocultá-la. Não há contagem regressiva.','Reproduza o nível que você memorizou.','Água = seletor {bias}. Ajuste a água para {value}%.','A referência é {value}%. Os dois níveis devem somar 100%.','Ajuste a água a {n}/{d} da altura da escala.'],
      guide:['Calibre copos de maré animados usando observação, memória, desvios do medidor, níveis complementares e frações.','Ajude Nori a verificar os medidores do recife. Este é um quebra-cabeça de observação e números, não uma previsão real das marés nem um jogo de separar líquidos. Cada capítulo exige um raciocínio diferente.','Escolha uma fase aberta e arraste o controle deslizante. Você também pode focá-lo e usar as setas, ou os botões de mais e menos para ajustar um ponto. Leia a instrução, observe a água e selecione Selar. Erros permitem tentar a mesma leitura novamente, sem limite de vidas ou de tempo.','São 30 fases em seis capítulos, com cinco leituras por fase. Só completar as cinco faz o progresso avançar uma fase. Depois surgem marcas escondidas, desvios positivos e negativos do medidor, pares que somam 100% e frações. A cada cinco fases há um teste com tolerância menor.','Sem erros nem dicas, você ganha três estrelas. Até três erros e uma dica rendem duas; outras conclusões rendem uma. Há duas dicas por fase. Observe a marca dourada, não a borda decorativa. Para corrigir o medidor, subtraia o desvio com sinal do nível desejado.','Quando o armazenamento local está disponível, o navegador salva fases concluídas, melhores estrelas e menor número de tentativas. Repetir não apaga um resultado melhor. Sair reinicia a fase incompleta. Os registros do protótipo são preservados, mas não abrem fases da nova campanha.'],
      faq:[['Cinco leituras contam como cinco fases?','Não. As cinco leituras juntas concluem somente uma fase.'],['Preciso correr nas rodadas de memória?','Não. Observe até selecionar Pronto. A marca fica oculta até usar uma dica ou terminar a leitura.'],['Por que o seletor e a água são diferentes?','Nas rodadas de desvio, o valor com sinal é somado ao seletor. Para um alvo de 60% e desvio de +8, ajuste o seletor para 52.']],
      tags:['Estimativa visual','Memória','Prática de frações']
    },
    fr: {
      title:'Réglage des marées',
      ui:['Jouer','Niveaux','Niveau {value}','Mesure {current}/{total}','Étoiles','{count}/{total} niveaux terminés','Verrouillé','Terminé','Niveau d’eau','Cadran','Baisser de 1','Monter de 1','Valider','Réinitialiser','Indice {count}/2','Prêt','Cible {value}%','Tolérance : ±{value} points de pourcentage','Pas encore. Ajustez et réessayez.','Étalonnage réussi !','Suivant','Rejouer','Quitter ce niveau ?','Ce niveau recommencera. Les niveaux terminés et vos meilleurs résultats restent enregistrés.','Continuer','Niveaux','Sauvegarde indisponible. Vous pouvez jouer, mais fermer la page peut effacer cette progression.','Chargement impossible. Rechargez la page.','Niveau correct : {value}%','Référence','Niveau terminé','{count} essais · {stars}/3 étoiles','Comment jouer','Règles et progression','Conseils','Sauvegarde','Questions','À propos du jeu'],
      modes:['Lire le repère','Mémoriser la marée','Corriger la jauge','Équilibrer la paire','Lire une fraction','Épreuve du récif'],
      clues:['Alignez la surface sur le repère doré.','Observez le repère, puis choisissez Prêt pour le masquer. Aucun compte à rebours.','Reproduisez le niveau mémorisé.','Eau = cadran {bias}. Réglez l’eau à {value}%.','La référence vaut {value}%. Les deux niveaux doivent totaliser 100%.','Réglez l’eau à {n}/{d} de la hauteur graduée.'],
      guide:['Étalonnez des verres animés par observation, mémoire, correction de jauge, niveaux complémentaires et fractions.','Aidez Nori à vérifier les jauges du récif. Ce puzzle associe observation et nombres : ce n’est ni une prévision réelle des marées ni un tri de liquides. Chaque chapitre demande un raisonnement différent.','Choisissez un niveau déverrouillé et déplacez le curseur. Vous pouvez aussi lui donner le focus et utiliser les flèches, ou ajuster d’un point avec les boutons moins et plus. Lisez la consigne, observez l’eau, puis validez. Une erreur permet de corriger la même mesure, sans limite de temps ni de vies.','Les six chapitres contiennent 30 niveaux de cinq mesures. Il faut réussir les cinq pour avancer d’un niveau. Les chapitres suivants cachent un repère, ajoutent un décalage signé, demandent une somme de 100% ou utilisent des fractions. Tous les cinq niveaux, une épreuve réduit la tolérance.','Aucune erreur ni aucun indice donne trois étoiles. Jusqu’à trois erreurs et un indice donnent deux étoiles ; toute autre réussite donne une étoile. Deux indices sont disponibles par niveau. Visez le repère doré, pas le bord décoratif. Soustrayez le décalage signé du niveau souhaité pour trouver le réglage du cadran.','Si le stockage local est disponible, le navigateur conserve les niveaux terminés, les meilleures étoiles et le minimum d’essais. Rejouer n’efface pas un meilleur résultat. Quitter recommence le niveau inachevé. Les anciens records du prototype restent conservés, sans déverrouiller la nouvelle campagne.'],
      faq:[['Cinq mesures font-elles avancer de cinq niveaux ?','Non. Les cinq mesures terminées valident un seul niveau.'],['Faut-il se dépêcher dans les épreuves de mémoire ?','Non. Observez aussi longtemps que nécessaire avant de choisir Prêt. Le repère reste ensuite caché jusqu’à un indice ou la réussite de la mesure.'],['Pourquoi le cadran diffère-t-il du niveau d’eau ?','Les épreuves de correction ajoutent le décalage signé au cadran. Pour une cible de 60% et un décalage de +8, réglez le cadran sur 52.']],
      tags:['Estimation visuelle','Mémoire','Fractions']
    },
    de: {
      title:'Gezeitenpegel einstellen',
      ui:['Spiel starten','Level','Level {value}','Messung {current}/{total}','Sterne','{count}/{total} Level geschafft','Gesperrt','Geschafft','Wasserstand','Regler','Um 1 senken','Um 1 erhöhen','Bestätigen','Zurücksetzen','Tipp {count}/2','Gemerkt','Ziel {value}%','Toleranz: ±{value} Prozentpunkte','Noch nicht. Passe den Wert an und versuche es erneut.','Kalibriert!','Weiter','Wiederholen','Dieses Level verlassen?','Dieses Level beginnt neu. Geschaffte Level und Bestwerte bleiben gespeichert.','Fortsetzen','Levelauswahl','Speichern ist nicht möglich. Du kannst spielen, beim Schließen kann dieser Fortschritt aber verloren gehen.','Das Spiel konnte nicht laden. Lade die Seite neu.','Richtiger Wasserstand: {value}%','Referenz','Level geschafft','{count} Versuche · {stars}/3 Sterne','Spielanleitung','Regeln und Fortschritt','Tipps','Speicherstand','Fragen','Über das Spiel'],
      modes:['Markierung lesen','Pegel merken','Messgerät korrigieren','Zwei Gläser ergänzen','Bruch ablesen','Riffprüfung'],
      clues:['Bringe die Wasseroberfläche zur goldenen Markierung.','Sieh dir die Markierung an. Mit Gemerkt blendest du sie aus. Es gibt keinen Countdown.','Stelle den gemerkten Wasserstand wieder her.','Wasserstand = Regler {bias}. Stelle das Wasser auf {value}%.','Die Referenz beträgt {value}%. Beide Wasserstände sollen zusammen 100% ergeben.','Stelle das Wasser auf {n}/{d} der Skalenhöhe.'],
      guide:['Kalibriere animierte Gezeitengläser mit Beobachtung, Gedächtnis, Messabweichungen, ergänzenden Pegeln und Brüchen.','Hilf Nori, die Messgeräte am Riff zu prüfen. Dies ist ein Beobachtungs- und Zahlenrätsel, keine echte Gezeitenvorhersage und kein Flüssigkeitssortierspiel. Jedes Kapitel verlangt eine andere Überlegung.','Wähle ein freigeschaltetes Level und bewege den Schieberegler. Du kannst ihn auch fokussieren und die Pfeiltasten benutzen oder mit Plus und Minus einen Punkt einstellen. Lies den Hinweis, prüfe die Wasseroberfläche und bestätige. Nach einem Fehler kannst du dieselbe Messung korrigieren, ohne Zeit- oder Lebenslimit.','Es gibt 30 Level in sechs Kapiteln, jeweils mit fünf Messungen. Erst alle fünf zusammen erhöhen den Fortschritt um ein Level. Später werden Markierungen verdeckt, vorzeichenbehaftete Abweichungen addiert, Pegel zu 100% ergänzt oder Brüche vorgegeben. Jedes fünfte Level hat eine engere Toleranz.','Ohne Fehler und Tipps gibt es drei Sterne. Bis zu drei Fehler und ein Tipp ergeben zwei Sterne; jeder andere erfolgreiche Durchlauf ergibt einen. Pro Level gibt es zwei Tipps. Orientiere dich an der goldenen Markierung, nicht am Zierrand. Ziehe die Abweichung mit ihrem Vorzeichen vom Ziel ab, um den Reglerwert zu finden.','Wenn lokales Speichern verfügbar ist, bleiben geschaffte Level, beste Sterne und wenigste Versuche im Browser erhalten. Wiederholen überschreibt keinen besseren Wert. Beim Verlassen beginnt das unfertige Level neu. Alte Prototypwerte bleiben erhalten, schalten aber keine neuen Kampagnenlevel frei.'],
      faq:[['Zählen fünf Messungen als fünf Level?','Nein. Erst fünf abgeschlossene Messungen ergeben genau ein Level.'],['Muss ich bei Gedächtnisaufgaben schnell sein?','Nein. Schau so lange hin wie nötig und wähle dann Gemerkt. Danach bleibt die Markierung bis zu einem Tipp oder der richtigen Messung verborgen.'],['Warum weichen Regler und Wasserstand voneinander ab?','Bei Korrekturaufgaben wird die Abweichung mit Vorzeichen zum Regler addiert. Bei Ziel 60% und Abweichung +8 stellst du 52 ein.']],
      tags:['Visuelles Schätzen','Gedächtnisrätsel','Brüche üben']
    },
    it: {
      title:'Regola la Marea',
      ui:['Gioca','Livelli','Livello {value}','Lettura {current}/{total}','Stelle','{count}/{total} livelli completati','Bloccato','Completato','Livello dell’acqua','Quadrante','Abbassa di 1','Alza di 1','Conferma','Azzera','Indizio {count}/2','Pronto','Obiettivo {value}%','Tolleranza: ±{value} punti percentuali','Non ancora. Regola e riprova.','Calibrato!','Avanti','Rigioca','Lasciare questo livello?','Questo livello ricomincerà. I livelli completati e i risultati migliori restano salvati.','Continua','Livelli','Impossibile salvare. Puoi giocare, ma chiudendo la pagina potresti perdere questi progressi.','Il gioco non è stato caricato. Ricarica la pagina.','Livello corretto: {value}%','Riferimento','Livello completato','{count} tentativi · {stars}/3 stelle','Come giocare','Regole e progressi','Consigli','Salvataggio','Domande','Il gioco'],
      modes:['Leggi il segno','Ricorda la marea','Correggi il misuratore','Equilibra la coppia','Leggi una frazione','Prova della barriera'],
      clues:['Allinea la superficie al segno dorato.','Osserva il segno, poi scegli Pronto per nasconderlo. Non c’è conto alla rovescia.','Riproduci il livello memorizzato.','Acqua = quadrante {bias}. Porta l’acqua al {value}%.','Il riferimento è {value}%. I due livelli devono sommare 100%.','Porta l’acqua a {n}/{d} dell’altezza della scala.'],
      guide:['Calibra bicchieri animati usando osservazione, memoria, errori del misuratore, livelli complementari e frazioni.','Aiuta Nori a controllare i misuratori della barriera. È un rompicapo di osservazione e numeri, non una previsione reale delle maree né un gioco di separazione dei liquidi. Ogni capitolo propone un ragionamento diverso.','Scegli un livello sbloccato e muovi il cursore. Puoi anche selezionarlo e usare le frecce, oppure i pulsanti più e meno per regolare un punto. Leggi la consegna, osserva l’acqua e conferma. Gli errori permettono di correggere la stessa lettura, senza limiti di tempo o vite.','Ci sono 30 livelli in sei capitoli, con cinque letture ciascuno. Devi completarle tutte per avanzare di un livello. In seguito compaiono segni nascosti, scarti positivi o negativi, coppie che sommano 100% e frazioni. Ogni quinto livello riduce la tolleranza.','Senza errori né indizi ottieni tre stelle. Fino a tre errori e un indizio danno due stelle; gli altri completamenti ne danno una. Hai due indizi per livello. Guarda il segno dorato, non il bordo decorativo. Sottrai lo scarto con il suo segno dal livello desiderato per trovare il quadrante corretto.','Se la memoria locale è disponibile, il browser conserva livelli completati, migliori stelle e minor numero di tentativi. Rigiocare non cancella un risultato migliore. Uscire fa ricominciare il livello incompleto. I dati del prototipo restano, ma non sbloccano la nuova campagna.'],
      faq:[['Cinque letture valgono cinque livelli?','No. Tutte e cinque le letture completano un solo livello.'],['Devo essere veloce nelle prove di memoria?','No. Osserva quanto vuoi prima di scegliere Pronto. Il segno rimane poi nascosto fino a un indizio o al completamento della lettura.'],['Perché quadrante e acqua sono diversi?','Le prove di correzione sommano lo scarto con segno al quadrante. Per un obiettivo del 60% e uno scarto di +8, imposta 52.']],
      tags:['Stima visiva','Memoria','Esercizi con frazioni']
    },
    ru: {
      title:'Настройка уровня прилива',
      ui:['Начать игру','Уровни','Уровень {value}','Замер {current}/{total}','Звёзды','Пройдено {count}/{total} уровней','Закрыто','Пройдено','Уровень воды','Регулятор','Уменьшить на 1','Увеличить на 1','Проверить','Сбросить','Подсказка {count}/2','Запомнил','Цель {value}%','Допуск: ±{value} процентных пункта','Пока не совпало. Исправьте и попробуйте снова.','Откалибровано!','Далее','Повторить','Покинуть этот уровень?','Этот уровень начнётся заново. Пройденные уровни и лучшие результаты сохранятся.','Продолжить','К уровням','Сохранение недоступно. Играть можно, но после закрытия страницы этот прогресс может исчезнуть.','Игра не загрузилась. Обновите страницу.','Верный уровень воды: {value}%','Образец','Уровень пройден','Попыток: {count} · Звёзды: {stars}/3','Как играть','Правила и этапы','Советы','Сохранение','Вопросы','Об игре'],
      modes:['Чтение отметки','Память прилива','Поправка прибора','Пара стаканов','Доли объёма','Испытание рифа'],
      clues:['Совместите поверхность воды с золотой отметкой.','Рассмотрите отметку и нажмите «Запомнил», чтобы скрыть её. Отсчёта времени нет.','Восстановите запомненный уровень воды.','Вода = регулятор {bias}. Установите воду на {value}%.','В образце {value}%. Сумма двух уровней должна быть 100%.','Установите воду на {n}/{d} высоты шкалы.'],
      guide:['Настраивайте анимированные стаканы с помощью наблюдения, памяти, поправок прибора, дополняющих уровней и дробей.','Помогите Nori проверить приборы на рифе. Это головоломка на наблюдение и числа, а не реальный прогноз прилива и не сортировка жидкостей. В каждой главе нужен новый способ рассуждения.','Выберите открытый уровень и передвигайте ползунок. Можно также установить на него фокус и использовать стрелки или менять значение на единицу кнопками плюс и минус. Прочитайте условие, посмотрите на воду и нажмите проверку. После ошибки можно исправить тот же замер; ограничения времени и жизней нет.','В шести главах 30 уровней, по пять замеров в каждом. Только все пять вместе продвигают кампанию на один уровень. Дальше появятся скрытые отметки, поправки со знаком, суммы двух уровней до 100% и дроби. Каждый пятый уровень уменьшает допустимую ошибку.','Без ошибок и подсказок вы получаете три звезды. Не более трёх ошибок и одной подсказки дают две; остальные успешные прохождения дают одну. На уровень доступны две подсказки. Смотрите на золотую отметку, а не на украшение стакана. Вычтите поправку со знаком из цели, чтобы найти значение регулятора.','При доступном локальном хранилище браузер сохраняет пройденные уровни, лучшие звёзды и минимум попыток. Повтор не стирает более удачный результат. При выходе незаконченный уровень начинается заново. Старые рекорды прототипа остаются, но не открывают новую кампанию.'],
      faq:[['Пять замеров считаются пятью уровнями?','Нет. Все пять замеров вместе завершают ровно один уровень.'],['Нужно ли спешить в заданиях на память?','Нет. Наблюдайте сколько нужно и нажмите «Запомнил». После этого отметка скрыта до подсказки или завершения замера.'],['Почему регулятор и вода показывают разное?','В заданиях с поправкой её значение со знаком прибавляется к регулятору. Для цели 60% и поправки +8 поставьте 52.']],
      tags:['Оценка на глаз','Память','Практика дробей']
    },
    hi: {
      title:'ज्वार का स्तर मिलाएँ',
      ui:['खेल शुरू करें','चरण','चरण {value}','माप {current}/{total}','सितारे','{count}/{total} चरण पूरे','बंद','पूरा','पानी का स्तर','डायल','1 घटाएँ','1 बढ़ाएँ','जाँचें','रीसेट','संकेत {count}/2','याद है','लक्ष्य {value}%','छूट: ±{value} प्रतिशत अंक','अभी नहीं मिला। बदलकर फिर जाँचें।','माप सही है!','अगला','फिर खेलें','यह चरण छोड़ें?','यह चरण फिर शुरू होगा। पूरे चरण और सर्वश्रेष्ठ नतीजे सुरक्षित रहेंगे।','जारी रखें','चरणों पर','सहेजना उपलब्ध नहीं है। खेल जारी रहेगा, लेकिन पेज बंद करने पर यह प्रगति खो सकती है।','खेल लोड नहीं हुआ। पेज फिर लोड करें।','सही जलस्तर: {value}%','संदर्भ','चरण पूरा','{count} प्रयास · {stars}/3 सितारे','कैसे खेलें','नियम और प्रगति','मापने के सुझाव','प्रगति सहेजना','सवाल','खेल का परिचय'],
      modes:['निशान पढ़ें','स्तर याद रखें','मीटर सुधारें','दो गिलास मिलाएँ','भिन्न पढ़ें','रीफ की परीक्षा'],
      clues:['पानी की सतह को सुनहरे निशान तक लाएँ।','निशान देखें, फिर याद है दबाकर छिपाएँ। कोई उलटी गिनती नहीं है।','याद किया हुआ जलस्तर फिर बनाएँ।','जलस्तर = डायल {bias}। असली पानी को {value}% पर लाएँ।','संदर्भ {value}% है। दोनों स्तरों का जोड़ 100% बनाएँ।','पानी को पैमाने की ऊँचाई के {n}/{d} पर रखें।'],
      guide:['नज़र, याददाश्त, मीटर की त्रुटि, पूरक स्तरों और भिन्नों से चलती हुई ज्वार-बोतलों का स्तर ठीक करें।','Nori की रीफ के मीटर जाँचने में मदद करें। यह देखने और संख्याओं की पहेली है, असली ज्वार का पूर्वानुमान या तरल छाँटने का खेल नहीं। हर अध्याय में सोचने का नया तरीका मिलता है।','खुला चरण चुनें और स्लाइडर खिसकाएँ। स्लाइडर पर फ़ोकस करके तीर कुंजियाँ इस्तेमाल कर सकते हैं, या जोड़-घटाव के बटनों से एक अंक बदल सकते हैं। निर्देश और पानी देखकर जाँचें दबाएँ। गलत होने पर उसी माप को फिर बदलें; समय या जीवन की सीमा नहीं है।','छह अध्यायों में 30 चरण हैं और हर चरण में पाँच माप हैं। पाँचों सही होने पर ही कुल प्रगति एक चरण बढ़ती है। आगे निशान छिपते हैं, धन या ऋण चिह्न वाली मीटर त्रुटि जुड़ती है, दो स्तरों का जोड़ 100% बनाना होता है, या भिन्न दिए जाते हैं। हर पाँचवें चरण में गलती की छूट कम होती है।','बिना गलती और संकेत के तीन सितारे मिलते हैं। अधिकतम तीन गलतियों और एक संकेत पर दो; बाकी सफल चरणों पर एक सितारा मिलता है। हर चरण में दो संकेत हैं। सजावटी किनारे के बजाय सुनहरा निशान देखें। सही डायल पाने के लिए लक्ष्य से चिह्न सहित मीटर की त्रुटि घटाएँ।','स्थानीय संग्रह उपलब्ध होने पर ब्राउज़र पूरे चरण, सर्वश्रेष्ठ सितारे और सबसे कम प्रयास सहेजता है। दोबारा खेलना बेहतर नतीजे को नहीं मिटाता। अधूरा चरण छोड़ने पर फिर शुरू होता है। पुराने नमूने के रिकॉर्ड रहते हैं, पर नई यात्रा के चरण नहीं खोलते।'],
      faq:[['क्या पाँच माप पूरे करने से पाँच चरण बढ़ते हैं?','नहीं। पाँचों माप मिलकर केवल एक चरण पूरा करते हैं।'],['क्या याददाश्त वाले माप में जल्दी करनी है?','नहीं। जितना चाहें देखें, फिर याद है दबाएँ। उसके बाद संकेत लेने या माप पूरा करने तक निशान छिपा रहता है।'],['डायल और पानी अलग क्यों हैं?','मीटर त्रुटि वाले सवालों में चिह्न सहित त्रुटि डायल में जुड़ती है। लक्ष्य 60% और त्रुटि +8 हो तो डायल 52 रखें।']],
      tags:['दृश्य अनुमान','याददाश्त की पहेली','भिन्न का अभ्यास']
    },
    ar: {
      title:'ضبط مستوى المدّ',
      ui:['ابدأ اللعب','المراحل','المرحلة {value}','القياس {current}/{total}','النجوم','اكتملت {count}/{total} مرحلة','مقفلة','مكتملة','مستوى الماء','القرص','خفض بمقدار 1','رفع بمقدار 1','تثبيت','إعادة','تلميح {count}/2','حفظت العلامة','الهدف {value}%','السماح: ±{value} نقاط مئوية','لم يتطابق بعد. عدّل وحاول مجددًا.','تم الضبط!','التالية','إعادة اللعب','مغادرة هذه المرحلة؟','ستبدأ هذه المرحلة من جديد. تبقى المراحل المكتملة وأفضل النتائج محفوظة.','متابعة','المراحل','الحفظ غير متاح. يمكنك اللعب، لكن قد تضيع هذه البيانات بعد إغلاق الصفحة.','تعذر تحميل اللعبة. أعد تحميل الصفحة.','المستوى الصحيح: {value}%','المرجع','اكتملت المرحلة','{count} محاولات · {stars}/3 نجوم','طريقة اللعب','القواعد والتقدم','نصائح الضبط','حفظ التقدم','أسئلة','عن اللعبة'],
      modes:['قراءة العلامة','تذكّر المستوى','تصحيح المقياس','موازنة الكأسين','قراءة الكسر','اختبار الشعاب'],
      clues:['طابق سطح الماء مع العلامة الذهبية.','راقب العلامة ثم اختر حفظت العلامة لإخفائها. لا يوجد عدّ تنازلي.','أعد مستوى الماء الذي تذكّرته.','الماء = القرص {bias}. اضبط الماء الفعلي على {value}%.','المرجع {value}%. اجعل مجموع المستويين 100%.','اضبط الماء على {n}/{d} من ارتفاع التدريج.'],
      guide:['اضبط كؤوس المدّ المتحركة بالملاحظة والذاكرة وتصحيح المقياس والمستويات المتكاملة والكسور.','ساعد Nori على فحص مقاييس الشعاب. هذا لغز ملاحظة وأرقام، وليس توقعًا حقيقيًا للمدّ أو لعبة فرز سوائل. يقدم كل فصل طريقة مختلفة للتفكير قبل تثبيت القياس.','اختر مرحلة مفتوحة وحرك شريط الضبط. يمكنك أيضًا التركيز عليه واستخدام مفاتيح الأسهم، أو زري الزيادة والنقصان لتغيير نقطة واحدة. اقرأ التعليمات وانظر إلى سطح الماء ثم ثبّت القياس. يتيح الخطأ تعديل القياس نفسه دون حدّ للوقت أو المحاولات.','توجد 30 مرحلة في ستة فصول، وفي كل مرحلة خمسة قياسات. يجب إكمال الخمسة ليتقدم المسار مرحلة واحدة. تظهر لاحقًا علامات مخفية، وانحرافات موجبة أو سالبة للمقياس، ومستويان مجموعهما 100%، وأهداف بالكسور. كل مرحلة خامسة تقلل هامش الخطأ.','تحصل على ثلاث نجوم دون أخطاء أو تلميحات. ثلاثة أخطاء كحد أقصى وتلميح واحد تمنح نجمتين، وبقية المحاولات الناجحة تمنح نجمة واحدة. لكل مرحلة تلميحان. انظر إلى العلامة الذهبية لا الحافة المزخرفة. اطرح الانحراف بإشارته من المستوى المطلوب لإيجاد قيمة القرص.','عندما يتاح التخزين المحلي، يحفظ المتصفح المراحل المكتملة وأفضل النجوم وأقل عدد محاولات. إعادة اللعب لا تمحو نتيجة أفضل. عند المغادرة تبدأ المرحلة غير المكتملة من جديد. تبقى سجلات النموذج القديم، لكنها لا تفتح مراحل الحملة الجديدة.'],
      faq:[['هل خمسة قياسات تعني خمس مراحل؟','لا. إكمال القياسات الخمسة معًا ينجز مرحلة واحدة فقط.'],['هل يجب الإسراع في مراحل الذاكرة؟','لا. راقب كما تشاء ثم اختر حفظت العلامة. بعدها تختفي العلامة حتى تستخدم تلميحًا أو تكمل القياس.'],['لماذا يختلف القرص عن مستوى الماء؟','تضيف مراحل التصحيح الانحراف بإشارته إلى القرص. لهدف 60% وانحراف +8، اضبط القرص على 52.']],
      tags:['تقدير بصري','لغز ذاكرة','تدريب الكسور']
    }
  };
  const localeKeys = ['en','zh-Hant','zh-Hans','ja','ko','es','pt-BR','fr','de','it','ru','hi','ar'];
  const segments = ['en','zh-tw','zh-cn','ja','ko','es','pt-br','fr','de','it','ru','hi','ar'];
  const names = ['English','繁體中文','简体中文','日本語','한국어','Español','Português','Français','Deutsch','Italiano','Русский','हिन्दी','العربية'];
  const copy = Object.fromEntries(localeKeys.map((locale,i) => {
    const d = data[locale];
    if (d.ui.length !== keys.length || d.modes.length !== 6 || d.clues.length !== 6 || d.guide.length !== 6 || d.faq.length !== 3) throw Error('Incomplete Tideglass locale: '+locale);
    return [locale,Object.freeze({...d,...Object.fromEntries(keys.map((key,n)=>[key,d.ui[n]])),direction:locale==='ar'?'rtl':'ltr',segment:segments[i],languageName:names[i]})];
  }));
  Object.defineProperty(copy,'__localeKeys',{value:Object.freeze(localeKeys)});
  if (root) root.TIDEGLASS_LOCALES = Object.freeze(copy);
  if (typeof module !== 'undefined' && module.exports) module.exports = Object.freeze(copy);
})(typeof window === 'undefined' ? null : window);
