window.ANIMAL_DEWLINE_LOCALES = {
  en: {
    loading: "Waking the meadow…", back: "Return to WeightPlay", settings: "Settings", soundOn: "Sound: On", soundOff: "Sound: Off", language: "Language", kicker: "A calm linked-flow puzzle", title: "Meadow Dewline", intro: "Tune three linked dew valves to match the meadow note and wake the dawn flowers.", start: "Start a meadow", plots: "Choose a meadow", best: "Best tries", noBest: "Not yet", guideTitle: "How to play", guideOneTitle: "1. Read the note", guideOne: "Each meadow shows the three flow levels the flowers need.", guideTwoTitle: "2. Tune the valves", guideTwo: "Use − and + to set every linked valve; the live total stays visible.", guideThreeTitle: "3. Check gently", guideThree: "A mismatch names the first valve to revisit. There is no timer or lives.", round: "Meadow {n} of {total}", tries: "Tries", noteLabel: "Meadow note", target: "Target", current: "Current", valve: "Valve {n}", decrease: "Decrease valve {n}", increase: "Increase valve {n}", battleHint: "Match each valve to the note, then check the flow.", total: "Current total", check: "Check flow", reset: "Reset valves", ready: "Flow is ready to check.", wrong: "Valve {n} is off target. Adjust it and try again.", correct: "The flowers are drinking happily.", finishTitle: "Dewline complete!", finishText: "Three meadows opened in {n} tries. Your best is {best}.", next: "Next meadow", map: "Meadow map", home: "Back to menu", allDone: "All three dawn meadows are awake."
  },
  "zh-Hant": {
    loading: "晨光正在喚醒草地……", back: "回到 WeightPlay", settings: "設定", soundOn: "音效：開", soundOff: "音效：關", language: "語言", kicker: "平靜的連動水流益智", title: "晨露水線", intro: "調整三個連動的晨露閥門，依照草地筆記喚醒晨光花朵。", start: "開始草地", plots: "選擇草地", best: "最佳嘗試", noBest: "尚無紀錄", guideTitle: "玩法", guideOneTitle: "1. 閱讀筆記", guideOne: "每片草地會顯示花朵需要的三個水流等級。", guideTwoTitle: "2. 調整閥門", guideTwo: "用 − 和 + 設定每個連動閥門，總量會即時顯示。", guideThreeTitle: "3. 平靜檢查", guideThree: "不吻合時會指出第一個要回看的閥門，沒有計時或生命。", round: "第 {n} 片草地／共 {total} 片", tries: "嘗試", noteLabel: "草地筆記", target: "目標", current: "目前", valve: "閥門 {n}", decrease: "降低閥門 {n}", increase: "提高閥門 {n}", battleHint: "依照筆記調整每個閥門，再檢查水流。", total: "目前總量", check: "檢查水流", reset: "重設閥門", ready: "水流已準備好檢查。", wrong: "閥門 {n} 尚未對準目標，調整後再試一次。", correct: "花朵正開心地喝著水。", finishTitle: "晨露水線完成！", finishText: "三片草地共用了 {n} 次嘗試，最佳紀錄是 {best} 次。", next: "下一片草地", map: "草地地圖", home: "回到選單", allDone: "三片晨光草地都醒來了。"
  },
  "zh-Hans": {
    loading: "正在唤醒草地……", back: "返回 WeightPlay", settings: "设置", soundOn: "音效：开", soundOff: "音效：关", language: "语言", kicker: "平静的连动水流益智游戏", title: "晨露水线", intro: "调整三个连动的晨露阀门，对准草地笔记，唤醒晨光花朵。", start: "开始草地", plots: "选择草地", best: "最佳尝试", noBest: "尚无记录", guideTitle: "玩法", guideOneTitle: "1. 阅读笔记", guideOne: "每片草地会显示花朵需要的三个水流等级。", guideTwoTitle: "2. 调整阀门", guideTwo: "用 − 和 + 设定每个连动阀门，实时总量会保持可见。", guideThreeTitle: "3. 平静检查", guideThree: "不匹配时会指出第一个需要回看的阀门，没有计时或生命。", round: "第 {n} 片草地／共 {total} 片", tries: "尝试", noteLabel: "草地笔记", target: "目标", current: "当前", valve: "阀门 {n}", decrease: "降低阀门 {n}", increase: "提高阀门 {n}", battleHint: "让每个阀门对准笔记，再检查水流。", total: "当前总量", check: "检查水流", reset: "重置阀门", ready: "水流已准备好检查。", wrong: "阀门 {n} 尚未对准目标，调整后再试一次。", correct: "花朵正开心地喝水。", finishTitle: "晨露水线完成！", finishText: "三片草地用了 {n} 次尝试，最佳记录是 {best} 次。", next: "下一片草地", map: "草地地图", home: "返回菜单", allDone: "三片晨光草地都醒来了。"
  },
  ja: {
    loading: "草原を目覚めさせています…", back: "WeightPlayに戻る", settings: "設定", soundOn: "サウンド：オン", soundOff: "サウンド：オフ", language: "言語", kicker: "静かな連動フローパズル", title: "メドウ・デューライン", intro: "3つの連動する露のバルブを草原のメモに合わせ、朝の花を目覚めさせましょう。", start: "草原を始める", plots: "草原を選ぶ", best: "ベスト記録", noBest: "まだ記録なし", guideTitle: "遊び方", guideOneTitle: "1. メモを読む", guideOne: "各草原には花が必要とする3つの水流レベルがあります。", guideTwoTitle: "2. バルブを調整", guideTwo: "− と + で連動するバルブを設定し、合計を確認します。", guideThreeTitle: "3. やさしく確認", guideThree: "不一致なら最初に見直すバルブを知らせます。時間制限もライフもありません。", round: "草原 {n}／{total}", tries: "試行", noteLabel: "草原のメモ", target: "目標", current: "現在", valve: "バルブ {n}", decrease: "バルブ {n}を下げる", increase: "バルブ {n}を上げる", battleHint: "各バルブをメモに合わせてから流れを確認します。", total: "現在の合計", check: "流れを確認", reset: "バルブをリセット", ready: "流れを確認できます。", wrong: "バルブ {n} が目標と違います。調整してもう一度。", correct: "花たちがうれしそうに水を飲んでいます。", finishTitle: "デューライン完成！", finishText: "3つの草原を {n} 回の試行で開きました。ベストは {best} 回です。", next: "次の草原", map: "草原マップ", home: "メニューに戻る", allDone: "3つの朝の草原がすべて目覚めました。"
  },
  ko: {
    loading: "초원을 깨우는 중…", back: "WeightPlay로 돌아가기", settings: "설정", soundOn: "소리: 켜짐", soundOff: "소리: 꺼짐", language: "언어", kicker: "차분한 연결 흐름 퍼즐", title: "초원의 이슬길", intro: "연결된 이슬 밸브 세 개를 초원 쪽지에 맞춰 아침 꽃을 깨워 보세요.", start: "초원 시작", plots: "초원 선택", best: "최고 기록", noBest: "아직 기록 없음", guideTitle: "게임 방법", guideOneTitle: "1. 쪽지 읽기", guideOne: "각 초원에는 꽃에 필요한 세 가지 물 흐름 단계가 표시돼요.", guideTwoTitle: "2. 밸브 조절", guideTwo: "−와 +로 연결된 밸브를 맞추고 현재 합계를 확인하세요.", guideThreeTitle: "3. 차분히 확인", guideThree: "맞지 않으면 먼저 다시 볼 밸브를 알려 줍니다. 시간 제한이나 목숨은 없어요.", round: "초원 {n} / {total}", tries: "시도", noteLabel: "초원 쪽지", target: "목표", current: "현재", valve: "밸브 {n}", decrease: "밸브 {n} 낮추기", increase: "밸브 {n} 높이기", battleHint: "각 밸브를 쪽지에 맞춘 뒤 흐름을 확인하세요.", total: "현재 합계", check: "흐름 확인", reset: "밸브 초기화", ready: "흐름을 확인할 준비가 됐어요.", wrong: "밸브 {n}이 목표와 달라요. 조절한 뒤 다시 시도하세요.", correct: "꽃들이 기쁘게 물을 마시고 있어요.", finishTitle: "이슬길 완료!", finishText: "세 초원을 {n}번 시도로 열었어요. 최고 기록은 {best}번이에요.", next: "다음 초원", map: "초원 지도", home: "메뉴로 돌아가기", allDone: "세 아침 초원이 모두 깨어났어요."
  },
  es: {
    loading: "Despertando la pradera…", back: "Volver a WeightPlay", settings: "Ajustes", soundOn: "Sonido: activado", soundOff: "Sonido: desactivado", language: "Idioma", kicker: "Un rompecabezas sereno de flujos conectados", title: "Línea de Rocío", intro: "Ajusta tres válvulas de rocío conectadas según la nota de la pradera y despierta las flores del amanecer.", start: "Comenzar pradera", plots: "Elegir pradera", best: "Mejor marca", noBest: "Aún no hay marca", guideTitle: "Cómo jugar", guideOneTitle: "1. Lee la nota", guideOne: "Cada pradera muestra los tres niveles de flujo que necesitan las flores.", guideTwoTitle: "2. Ajusta las válvulas", guideTwo: "Usa − y + para fijar cada válvula conectada y ver el total en directo.", guideThreeTitle: "3. Comprueba con calma", guideThree: "Si no coincide, nombra la primera válvula que debes revisar. No hay tiempo ni vidas.", round: "Pradera {n} de {total}", tries: "Intentos", noteLabel: "Nota de la pradera", target: "Objetivo", current: "Actual", valve: "Válvula {n}", decrease: "Bajar válvula {n}", increase: "Subir válvula {n}", battleHint: "Ajusta cada válvula a la nota y comprueba el flujo.", total: "Total actual", check: "Comprobar flujo", reset: "Reiniciar válvulas", ready: "El flujo está listo para comprobarse.", wrong: "La válvula {n} no coincide con el objetivo. Ajústala y vuelve a intentarlo.", correct: "Las flores beben felices.", finishTitle: "¡Línea de Rocío completada!", finishText: "Abriste tres praderas en {n} intentos. Tu mejor marca es {best}.", next: "Siguiente pradera", map: "Mapa de praderas", home: "Volver al menú", allDone: "Las tres praderas del amanecer están despiertas."
  },
  "pt-BR": {
    loading: "Despertando o prado…", back: "Voltar ao WeightPlay", settings: "Configurações", soundOn: "Som: ligado", soundOff: "Som: desligado", language: "Idioma", kicker: "Um quebra-cabeça calmo de fluxos conectados", title: "Linha de Orvalho", intro: "Ajuste três válvulas de orvalho conectadas à nota do prado e desperte as flores da manhã.", start: "Começar prado", plots: "Escolher prado", best: "Melhor marca", noBest: "Ainda não há marca", guideTitle: "Como jogar", guideOneTitle: "1. Leia a nota", guideOne: "Cada prado mostra os três níveis de fluxo que as flores precisam.", guideTwoTitle: "2. Ajuste as válvulas", guideTwo: "Use − e + para definir cada válvula conectada e ver o total ao vivo.", guideThreeTitle: "3. Confira com calma", guideThree: "Se não combinar, a primeira válvula a revisar será indicada. Não há tempo nem vidas.", round: "Prado {n} de {total}", tries: "Tentativas", noteLabel: "Nota do prado", target: "Meta", current: "Atual", valve: "Válvula {n}", decrease: "Diminuir válvula {n}", increase: "Aumentar válvula {n}", battleHint: "Ajuste cada válvula à nota e confira o fluxo.", total: "Total atual", check: "Conferir fluxo", reset: "Redefinir válvulas", ready: "O fluxo está pronto para conferir.", wrong: "A válvula {n} não está na meta. Ajuste e tente novamente.", correct: "As flores estão bebendo felizes.", finishTitle: "Linha de Orvalho concluída!", finishText: "Você abriu três prados em {n} tentativas. Sua melhor marca é {best}.", next: "Próximo prado", map: "Mapa dos prados", home: "Voltar ao menu", allDone: "Os três prados da manhã estão acordados."
  },
  fr: {
    loading: "Réveil de la prairie…", back: "Retour à WeightPlay", settings: "Réglages", soundOn: "Son : activé", soundOff: "Son : désactivé", language: "Langue", kicker: "Un puzzle paisible de flux liés", title: "Ligne de Rosée", intro: "Règle trois vannes de rosée liées selon la note de la prairie et réveille les fleurs de l’aube.", start: "Commencer la prairie", plots: "Choisir une prairie", best: "Meilleur score", noBest: "Pas encore de score", guideTitle: "Comment jouer", guideOneTitle: "1. Lire la note", guideOne: "Chaque prairie indique les trois niveaux de flux dont les fleurs ont besoin.", guideTwoTitle: "2. Régler les vannes", guideTwo: "Utilise − et + pour régler chaque vanne liée et garder le total visible.", guideThreeTitle: "3. Vérifier doucement", guideThree: "En cas d’écart, la première vanne à revoir est indiquée. Il n’y a ni temps ni vies.", round: "Prairie {n} sur {total}", tries: "Essais", noteLabel: "Note de la prairie", target: "Objectif", current: "Actuel", valve: "Vanne {n}", decrease: "Baisser la vanne {n}", increase: "Monter la vanne {n}", battleHint: "Aligne chaque vanne sur la note, puis vérifie le flux.", total: "Total actuel", check: "Vérifier le flux", reset: "Réinitialiser les vannes", ready: "Le flux est prêt à être vérifié.", wrong: "La vanne {n} n’est pas sur l’objectif. Règle-la et réessaie.", correct: "Les fleurs boivent joyeusement.", finishTitle: "Ligne de Rosée terminée !", finishText: "Tu as ouvert trois prairies en {n} essais. Ton meilleur score est {best}.", next: "Prairie suivante", map: "Carte des prairies", home: "Retour au menu", allDone: "Les trois prairies de l’aube sont réveillées."
  },
  de: {
    loading: "Die Wiese erwacht…", back: "Zurück zu WeightPlay", settings: "Einstellungen", soundOn: "Ton: an", soundOff: "Ton: aus", language: "Sprache", kicker: "Ein ruhiges Rätsel mit verbundenen Strömen", title: "Taupfad", intro: "Stelle drei verbundene Tauschleusen nach der Wiesennotiz ein und wecke die Blumen der Morgendämmerung.", start: "Wiese beginnen", plots: "Wiese wählen", best: "Bestleistung", noBest: "Noch keine Bestleistung", guideTitle: "Spielanleitung", guideOneTitle: "1. Notiz lesen", guideOne: "Jede Wiese zeigt die drei Wasserstufen, die die Blumen brauchen.", guideTwoTitle: "2. Ventile einstellen", guideTwo: "Mit − und + stellst du jedes verbundene Ventil ein; die Summe bleibt sichtbar.", guideThreeTitle: "3. Ruhig prüfen", guideThree: "Bei einer Abweichung wird das erste zu prüfende Ventil genannt. Es gibt weder Zeitlimit noch Leben.", round: "Wiese {n} von {total}", tries: "Versuche", noteLabel: "Wiesennotiz", target: "Ziel", current: "Aktuell", valve: "Ventil {n}", decrease: "Ventil {n} senken", increase: "Ventil {n} erhöhen", battleHint: "Richte jedes Ventil nach der Notiz aus und prüfe den Strom.", total: "Aktuelle Summe", check: "Strom prüfen", reset: "Ventile zurücksetzen", ready: "Der Strom ist bereit zur Prüfung.", wrong: "Ventil {n} liegt nicht auf dem Ziel. Stelle es ein und versuche es erneut.", correct: "Die Blumen trinken fröhlich.", finishTitle: "Taupfad geschafft!", finishText: "Du hast drei Wiesen in {n} Versuchen geöffnet. Deine Bestleistung ist {best}.", next: "Nächste Wiese", map: "Wiesenkarte", home: "Zum Menü", allDone: "Alle drei Morgenwiesen sind erwacht."
  },
  it: {
    loading: "Risveglio del prato…", back: "Torna a WeightPlay", settings: "Impostazioni", soundOn: "Suono: attivo", soundOff: "Suono: disattivato", language: "Lingua", kicker: "Un tranquillo rompicapo di flussi collegati", title: "Linea di Rugiada", intro: "Regola tre valvole di rugiada collegate seguendo la nota del prato e risveglia i fiori dell’alba.", start: "Inizia il prato", plots: "Scegli un prato", best: "Miglior risultato", noBest: "Nessun risultato", guideTitle: "Come si gioca", guideOneTitle: "1. Leggi la nota", guideOne: "Ogni prato mostra i tre livelli di flusso necessari ai fiori.", guideTwoTitle: "2. Regola le valvole", guideTwo: "Usa − e + per impostare ogni valvola collegata e vedere il totale in tempo reale.", guideThreeTitle: "3. Controlla con calma", guideThree: "Se non coincide, viene indicata la prima valvola da rivedere. Non ci sono tempo o vite.", round: "Prato {n} di {total}", tries: "Tentativi", noteLabel: "Nota del prato", target: "Obiettivo", current: "Attuale", valve: "Valvola {n}", decrease: "Abbassa valvola {n}", increase: "Alza valvola {n}", battleHint: "Allinea ogni valvola alla nota, poi controlla il flusso.", total: "Totale attuale", check: "Controlla il flusso", reset: "Azzera le valvole", ready: "Il flusso è pronto per il controllo.", wrong: "La valvola {n} non è sull’obiettivo. Regolala e riprova.", correct: "I fiori bevono felici.", finishTitle: "Linea di Rugiada completata!", finishText: "Hai aperto tre prati in {n} tentativi. Il tuo miglior risultato è {best}.", next: "Prato successivo", map: "Mappa dei prati", home: "Torna al menu", allDone: "Tutti e tre i prati dell’alba sono svegli."
  },
  ru: {
    loading: "Пробуждаем луг…", back: "Вернуться в WeightPlay", settings: "Настройки", soundOn: "Звук: вкл.", soundOff: "Звук: выкл.", language: "Язык", kicker: "Спокойная головоломка со связанными потоками", title: "Роса на лугу", intro: "Настройте три связанные росовые заслонки по заметке луга и разбудите цветы рассвета.", start: "Начать луг", plots: "Выбрать луг", best: "Лучший результат", noBest: "Пока нет записи", guideTitle: "Как играть", guideOneTitle: "1. Прочитайте заметку", guideOne: "На каждом лугу указаны три уровня потока, нужные цветам.", guideTwoTitle: "2. Настройте заслонки", guideTwo: "Используйте − и + для настройки связанных заслонок; текущая сумма всегда видна.", guideThreeTitle: "3. Проверьте спокойно", guideThree: "При несовпадении игра назовёт первую заслонку для повторной проверки. Таймера и жизней нет.", round: "Луг {n} из {total}", tries: "Попытки", noteLabel: "Заметка луга", target: "Цель", current: "Сейчас", valve: "Заслонка {n}", decrease: "Уменьшить заслонку {n}", increase: "Увеличить заслонку {n}", battleHint: "Настройте каждую заслонку по заметке и проверьте поток.", total: "Текущая сумма", check: "Проверить поток", reset: "Сбросить заслонки", ready: "Поток готов к проверке.", wrong: "Заслонка {n} не совпадает с целью. Настройте её и попробуйте снова.", correct: "Цветы радостно пьют воду.", finishTitle: "Роса на лугу завершена!", finishText: "Вы открыли три луга за {n} попыток. Лучший результат — {best}.", next: "Следующий луг", map: "Карта лугов", home: "В меню", allDone: "Все три рассветных луга проснулись."
  },
  hi: {
    loading: "मैदान को जगाया जा रहा है…", back: "WeightPlay पर लौटें", settings: "सेटिंग्स", soundOn: "ध्वनि: चालू", soundOff: "ध्वनि: बंद", language: "भाषा", kicker: "जुड़ी हुई धाराओं की शांत पहेली", title: "ओस की पगडंडी", intro: "तीन जुड़े ओस वाल्व को मैदान की पर्ची से मिलाकर सुबह के फूल जगाएँ।", start: "मैदान शुरू करें", plots: "मैदान चुनें", best: "सर्वश्रेष्ठ प्रयास", noBest: "अभी कोई रिकॉर्ड नहीं", guideTitle: "कैसे खेलें", guideOneTitle: "1. पर्ची पढ़ें", guideOne: "हर मैदान फूलों के लिए ज़रूरी तीन जल-प्रवाह स्तर दिखाता है।", guideTwoTitle: "2. वाल्व समायोजित करें", guideTwo: "हर जुड़े वाल्व को − और + से सेट करें; कुल मान हमेशा दिखाई देता है।", guideThreeTitle: "3. शांति से जाँचें", guideThree: "मेल न होने पर फिर देखने वाला पहला वाल्व बताया जाएगा। समय या जीवन नहीं हैं।", round: "मैदान {n} / {total}", tries: "प्रयास", noteLabel: "मैदान की पर्ची", target: "लक्ष्य", current: "वर्तमान", valve: "वाल्व {n}", decrease: "वाल्व {n} घटाएँ", increase: "वाल्व {n} बढ़ाएँ", battleHint: "हर वाल्व को पर्ची से मिलाएँ, फिर प्रवाह जाँचें।", total: "वर्तमान कुल", check: "प्रवाह जाँचें", reset: "वाल्व रीसेट करें", ready: "प्रवाह जाँचने के लिए तैयार है।", wrong: "वाल्व {n} लक्ष्य से अलग है। उसे समायोजित करके फिर प्रयास करें।", correct: "फूल खुशी से पानी पी रहे हैं।", finishTitle: "ओस की पगडंडी पूरी हुई!", finishText: "आपने तीन मैदान {n} प्रयासों में खोले। आपका सर्वश्रेष्ठ {best} है।", next: "अगला मैदान", map: "मैदान का नक्शा", home: "मेनू पर लौटें", allDone: "सुबह के तीनों मैदान जाग गए हैं।"
  },
  ar: {
    loading: "نوقظ المرج…", back: "العودة إلى WeightPlay", settings: "الإعدادات", soundOn: "الصوت: مفعّل", soundOff: "الصوت: متوقف", language: "اللغة", kicker: "لغز هادئ بتدفقات مترابطة", title: "خط الندى", intro: "اضبط صمامات الندى الثلاثة المترابطة وفق ملاحظة المرج وأيقظ زهور الفجر.", start: "ابدأ المرج", plots: "اختر مرجاً", best: "أفضل المحاولات", noBest: "لا يوجد سجل بعد", guideTitle: "طريقة اللعب", guideOneTitle: "1. اقرأ الملاحظة", guideOne: "يعرض كل مرج مستويات التدفق الثلاثة التي تحتاجها الزهور.", guideTwoTitle: "2. اضبط الصمامات", guideTwo: "استخدم − و + لضبط كل صمام مترابط، وسيبقى المجموع الحالي ظاهراً.", guideThreeTitle: "3. افحص بهدوء", guideThree: "عند عدم التطابق سيُذكر أول صمام تحتاج إلى مراجعته. لا يوجد مؤقت أو أرواح.", round: "المرج {n} من {total}", tries: "المحاولات", noteLabel: "ملاحظة المرج", target: "الهدف", current: "الحالي", valve: "الصمام {n}", decrease: "خفض الصمام {n}", increase: "رفع الصمام {n}", battleHint: "طابق كل صمام مع الملاحظة ثم افحص التدفق.", total: "المجموع الحالي", check: "افحص التدفق", reset: "إعادة ضبط الصمامات", ready: "التدفق جاهز للفحص.", wrong: "الصمام {n} لا يطابق الهدف. اضبطه وحاول مرة أخرى.", correct: "الزهور تشرب بسعادة.", finishTitle: "اكتمل خط الندى!", finishText: "فتحت ثلاثة مروج خلال {n} محاولات. أفضل نتيجة لك هي {best}.", next: "المرج التالي", map: "خريطة المروج", home: "العودة إلى القائمة", allDone: "استيقظت مروج الفجر الثلاثة كلها."
  }
};
