// Authored guide presentation; stage names and campaign data remain unchanged.
import {COPY} from './locales.mjs';
import {upgradeText} from './upgrade-copy.mjs';
// Each locale describes this game's actual removal/absorption rules. These
// compact paragraphs are also consumed by the static route generator.
const rules={
 en:['Tap connected matching blocks to remove the whole group; blocks do not fall or refill. Your fox falls, then approaches the nearest guard on the same platform (left on a tie). Greater power wins and absorbs the guard’s power; equal or lower loses.','Keys open gates; runes remove shields. Defeat flag bearers to remove their bonuses. Avoid spikes and meet the boss conditions before taking the crown.','Progress and an unfinished puzzle stay in this browser. Retry preserves unlocked stages.'],
 'zh-Hant':['點相連的同色方塊，整群消除；方塊不會下落或補入。狐狸落地後會走向同平台最近的守衛，同距離先往左。戰力較高才能獲勝並吸收敵方戰力；相等也會輸。','鑰匙開門、符文解除護盾。先擊敗旗手可消除敵方加成；避開尖刺，完成首領條件再取皇冠。','進度與未完成的棋局儲存在此瀏覽器；重玩不會清除已解鎖關卡。'],
 'zh-Hans':['点相连的同色方块，整群消除；方块不会下落或补入。狐狸落地后会走向同平台最近的守卫，同距离先往左。战力较高才能获胜并吸收敌方战力；相等也会输。','钥匙开门、符文解除护盾。先击败旗手可消除敌方加成；避开尖刺，完成首领条件再取皇冠。','进度与未完成的棋局保存在此浏览器；重玩不会清除已解锁关卡。'],
 ja:['つながった同色ブロックをタップしてまとめて消します。ブロックは落下も補充もしません。キツネは着地後、同じ足場の最寄りの敵へ（同距離なら左へ）。戦力が上回れば勝って吸収し、同じか下なら負けます。','鍵で扉、ルーンで盾を解除。旗持ちを倒すと敵の強化が消えます。針を避け、ボスの条件を満たして王冠を取りましょう。','進行状況と中断した盤面はこのブラウザに保存。再挑戦しても解放済みステージは残ります。'],
 ko:['연결된 같은 색 블록을 눌러 묶음째 없애세요. 블록은 떨어지거나 채워지지 않습니다. 여우는 착지 후 같은 발판의 가장 가까운 적에게 갑니다(동률이면 왼쪽). 전투력이 높아야 이기고 적의 힘을 흡수하며, 같아도 집니다.','열쇠는 문을, 룬은 방패를 해제합니다. 기수를 쓰러뜨리면 적의 강화가 사라집니다. 가시를 피하고 보스 조건을 충족한 뒤 왕관을 얻으세요.','진행도와 미완성 퍼즐은 이 브라우저에 저장됩니다. 재도전해도 열린 단계는 유지됩니다.'],
 es:['Toca bloques iguales conectados para quitar el grupo; no caen ni se reponen. El zorro aterriza y va al guardia más cercano de la misma plataforma (izquierda si empatan). Más poder gana y absorbe al rival; igual o menos pierde.','Las llaves abren puertas y las runas quitan escudos. Derrota a los abanderados para eliminar sus bonificaciones. Evita pinchos y cumple las condiciones del jefe antes de tomar la corona.','El progreso y el puzle pendiente se guardan en este navegador. Reiniciar conserva los niveles abiertos.'],
 'pt-BR':['Toque blocos iguais conectados para remover o grupo; eles não caem nem são repostos. A raposa pousa e vai ao guarda mais próximo na mesma plataforma (à esquerda no empate). Poder maior vence e absorve o rival; igual ou menor perde.','Chaves abrem portas; runas removem escudos. Derrote porta-bandeiras para tirar seus bônus. Evite espinhos e cumpra as condições do chefe antes de pegar a coroa.','O progresso e o quebra-cabeça em andamento ficam neste navegador. Reiniciar preserva as fases abertas.'],
 fr:['Touchez les blocs identiques reliés pour retirer le groupe ; ils ne tombent pas et ne sont pas remplacés. Le renard rejoint ensuite le garde le plus proche sur sa plateforme (à gauche en cas d’égalité). Une puissance supérieure gagne et absorbe celle du garde ; sinon, c’est perdu.','Clés : portes. Runes : boucliers. Éliminez les porte-drapeaux pour retirer leurs bonus. Évitez les pointes et remplissez les conditions du boss avant de prendre la couronne.','La progression et la partie inachevée restent dans ce navigateur. Recommencer conserve les niveaux ouverts.'],
 de:['Tippe verbundene gleichfarbige Blöcke an: Die Gruppe verschwindet, ohne Nachfallen oder Auffüllen. Der Fuchs fällt und geht zum nächsten Wächter auf seiner Plattform (bei Gleichstand links). Mehr Stärke gewinnt und absorbiert den Gegner; gleich viel oder weniger verliert.','Schlüssel öffnen Tore, Runen entfernen Schilde. Besiege Fahnenträger gegen ihre Boni. Meide Stacheln und erfülle die Bossbedingungen, bevor du die Krone nimmst.','Fortschritt und das offene Rätsel bleiben in diesem Browser. Neustart erhält freigeschaltete Stufen.'],
 it:['Tocca blocchi uguali collegati per rimuovere il gruppo; non cadono né si rigenerano. La volpe atterra e raggiunge la guardia più vicina sulla stessa piattaforma (a sinistra in parità). Più forza vince e assorbe il rivale; uguale o minore perde.','Le chiavi aprono porte e le rune tolgono scudi. Sconfiggi gli alfieri per rimuovere i bonus. Evita le punte e soddisfa le condizioni del boss prima di prendere la corona.','Progressi ed enigma in corso restano in questo browser. Ricominciare conserva i livelli aperti.'],
 ru:['Нажмите на связанные блоки одного цвета: группа исчезнет без падения и пополнения блоков. Лис приземлится и пойдёт к ближайшему стражу на своей платформе (при равенстве — влево). Большая сила побеждает и поглощает силу врага; равная или меньшая проигрывает.','Ключи открывают ворота, руны снимают щиты. Победите знаменосцев, чтобы убрать их усиления. Избегайте шипов и выполните условия босса до взятия короны.','Прогресс и незавершённая задача сохраняются в этом браузере. Перезапуск не закрывает открытые уровни.'],
 hi:['जुड़े समान रंग के ब्लॉक दबाकर पूरा समूह हटाएँ; ब्लॉक गिरते या फिर भरते नहीं हैं। लोमड़ी उतरकर उसी मंच के निकटतम रक्षक की ओर जाती है (बराबरी पर बाएँ)। अधिक शक्ति होने पर जीतकर दुश्मन की शक्ति मिलती है; बराबर या कम पर हार होती है।','चाबियाँ द्वार खोलती हैं, रून्स ढाल हटाते हैं। ध्वजवाहकों को हराकर उनका बोनस हटाएँ। काँटों से बचें और ताज लेने से पहले मुखिया की शर्तें पूरी करें।','प्रगति और अधूरी पहेली इसी ब्राउज़र में रहती हैं। दोबारा खेलने पर खुले स्तर सुरक्षित रहते हैं।'],
 ar:['اضغط كتلًا متصلة من اللون نفسه لإزالة المجموعة؛ الكتل لا تسقط ولا تتجدد. يهبط الثعلب ثم يتجه لأقرب حارس على المنصة نفسها (يسارًا عند التعادل). القوة الأعلى تفوز وتمتص قوة الخصم؛ التعادل أو الأقل يعني الخسارة.','المفاتيح تفتح الأبواب والرون يزيل الدروع. اهزم حاملي الرايات لإزالة تعزيزاتهم. تجنب الأشواك وأكمل شروط الزعيم قبل أخذ التاج.','التقدم واللغز غير المكتمل محفوظان في هذا المتصفح. الإعادة تحتفظ بالمراحل المفتوحة.'],
};
const stageLabels={en:'Stage','zh-Hant':'關卡','zh-Hans':'关卡',ja:'ステージ',ko:'단계',es:'Nivel','pt-BR':'Fase',fr:'Niveau',de:'Stufe',it:'Livello',ru:'Этап',hi:'स्तर',ar:'المرحلة'};
const progression={
 en:['Campaign','Clear a puzzle to unlock the next. Try new routes around hazards and boss conditions; replay for no-hint and move-target badges. Undo restores the last action.'],
 'zh-Hant':['挑戰進程','過關解鎖下一關，依地形與首領條件安排路線。重玩可挑戰不用提示或目標步數徽章；撤銷可還原上一步。'],
 'zh-Hans':['挑战进程','过关解锁下一关，依地形与首领条件安排路线。重玩可挑战不用提示或目标步数徽章；撤销可还原上一步。'],
 ja:['挑戦の進め方','クリアすると次のステージが開きます。地形やボスの条件に合わせて道を選び、再挑戦でヒントなし・目標手数のバッジを狙いましょう。一手を戻すこともできます。'],
 ko:['도전 진행','퍼즐을 풀면 다음 단계가 열립니다. 지형과 보스 조건에 맞춰 경로를 고르세요. 다시 도전해 무힌트·목표 이동 수 배지를 얻고, 되돌리기로 마지막 행동을 취소할 수 있습니다.'],
 es:['Progresión','Resuelve un puzle para abrir el siguiente. Adapta la ruta a los peligros y al jefe. Repite para lograr insignias sin pistas o dentro del límite de movimientos; deshacer restaura la última acción.'],
 'pt-BR':['Progressão','Resolva um quebra-cabeça para abrir o próximo. Adapte a rota aos perigos e ao chefe. Jogue novamente pelas medalhas sem dicas e de meta de movimentos; desfazer restaura a última ação.'],
 fr:['Progression','Résolvez une énigme pour ouvrir la suivante. Adaptez le trajet aux dangers et au boss. Rejouez pour les badges sans indice et avec un nombre limité de coups ; annuler restaure la dernière action.'],
 de:['Fortschritt','Löse ein Rätsel, um das nächste freizuschalten. Passe den Weg an Gefahren und Bossregeln an. Wiederhole es für Abzeichen ohne Hinweise oder mit Zugziel. Rückgängig stellt die letzte Aktion wieder her.'],
 it:['Progressione','Risolvi un enigma per aprire il successivo. Adatta il percorso ai pericoli e al boss. Rigioca per i distintivi senza indizi e con obiettivo di mosse; annulla ripristina l’ultima azione.'],
 ru:['Прохождение','Решите головоломку, чтобы открыть следующую. Учитывайте ловушки и условия босса. Повторяйте ради значков без подсказок и за число ходов. Отмена восстанавливает последнее действие.'],
 hi:['चुनौती की प्रगति','पहेली पूरी करने पर अगला स्तर खुलता है। खतरों और मुखिया की शर्तों के अनुसार रास्ता चुनें। बिना संकेत और लक्ष्य चालों के पदक पाने के लिए फिर खेलें। वापसी आखिरी कार्रवाई बहाल करती है।'],
 ar:['التقدم','حل اللغز لفتح التالي واختر طريقًا يناسب المخاطر وشروط الزعيم. أعد اللعب لشارات بلا تلميحات وهدف الحركات. التراجع يعيد الإجراء الأخير.'],
};
export const DETAILS=Object.fromEntries(Object.entries(rules).map(([locale,parts])=>{
 const [heading,body]=progression[locale];
 COPY[locale].campaign=heading;
 COPY[locale].stage=stageLabels[locale];
 return [locale,[parts[0],parts[1],body,parts[2]]];
}));

// Current single-power rules; native routes use this same guide.
for(const [locale,parts] of Object.entries(DETAILS)){
 parts[0]=`${upgradeText(locale,'previewHelp')} ${parts[0]}`;
 parts[1]+=' '+upgradeText(locale,'mathGuide');
 parts[2]+=' '+['gate','runeLesson','finale'].map(key=>upgradeText(locale,key)).join(' ');
}

import {cameraText} from './camera-copy.mjs';
for(const [locale,parts] of Object.entries(DETAILS))parts[0]+=' '+cameraText(locale,'guide');

// Complete factual General guide. Indices 0–3 remain stable for existing clients.
const extendedGuide={
  "en": [
    "The castle and your mission",
    "Guide a fox down a block-built castle to its crown. You choose which floors disappear; the fox, guards and supplies then fall onto the supports that remain. The challenge is arranging a safe sequence of encounters, not steering every sword swing. Strong guards, spikes, locked floors and shielded enemies can stop a descent that looked safe from above. A clear means reaching the crown after every required guard, boss and seal condition is satisfied. Power gained during a puzzle belongs to that attempt; the campaign reward is access to the next puzzle and replay badges.",
    "Start an unlocked stage and inspect the whole map before removing a support.",
    "Tap a connected colour group, read its route preview, then confirm the removal or cancel it.",
    "Let the fall and encounters finish. Compare the new power with the next guard before choosing another group.",
    "Reach the crown, then choose the next stage or replay. After a mistake, undo the last action or retry the puzzle.",
    "How the challenge grows",
    "Stages 1–4 introduce dropping, absorption and a landing sword. From stage 5, addition before multiplication matters; split floors can require dropping a strong guard away before releasing the fox. Middle stages mix keys, mirrored routes, shield runes and linked rooms. Later puzzles demand preparation across several floors rather than simply clearing the floor beneath you. Stage 20 checks the side of approach; stage 25 has a second boss phase; stage 30 combines a banner, a shield and seals in order. These are fixed puzzles with increasing combinations, not a selectable difficulty mode.",
    "Useful decisions",
    "Compare both orders: collecting +10 before ×2 gives 10 more power than collecting it afterward.",
    "Inspect the lower landing before releasing the fox; a guard or supply may need to fall first.",
    "Keep required guards, supplies and the crown away from spikes. Losing an objective can end the attempt.",
    "Use undo to compare routes. A hint can help recovery, but a no-hint badge requires a clear without one.",
    "Design note",
    "Each removal is a deliberate turn. Connected blocks vanish without refilling, so their absence is a lasting change to the route. The same choices produce the same outcome, letting a retry test a different order instead of hoping for a lucky drop. Attacks happen automatically after an approach: the visible wind-up and contact explain the calculation, rather than asking for a reaction tap. The camera follows the descent, while dragging, arrows and overview let you inspect floors outside the current view. This keeps a tall castle readable on a phone without shrinking the entire puzzle into one screen. The preview supports planning but does not supply a winning sequence.",
    "Player, device and save information",
    "Play with touch or mouse; keyboard controls are available for focused board cells. There is no timer, login or in-game spending. Allow roughly 1–3 minutes per attempt, longer for harder routes. Unlocks, badges, settings and an unfinished run use this browser’s local storage; they do not sync between devices. Clearing browser data can remove them. If saving is unavailable, play can continue in the session.",
    "Questions about the castle",
    "Is power also health?",
    "No. The displayed number is attack power, with no separate health pool. A guard is beaten only with strictly greater power and the required conditions; equal power loses. Victory adds the guard’s power.",
    "Why did the fox fight before taking a nearby item?",
    "The nearest reachable guard normally takes priority. An item directly under the fox is collected first only if no guard shares that cell. On equal guard distances, the fox approaches left first.",
    "Can enough power ignore a shield or boss rule?",
    "No. Obtain the matching rune for a shield, defeat required deputies, obey the indicated approach side and collect seals in order where required. A two-phase boss must also be defeated in its final form.",
    "Must every guard be defeated?",
    "Only the stage’s required targets and living bosses block the crown; some side guards are optional. Check the target display and route before skipping one. Clearing a stage unlocks the next, while replaying can improve badges."
  ],
  "zh-Hant": [
    "古堡與任務",
    "帶領狐狸沿方塊古堡向下奪取皇冠。你決定哪些地板消失，狐狸、守衛與補給便會落在剩下的支撐上。重點是安排安全的交戰順序，不是逐次操控揮劍。強敵、尖刺、鎖住的地板與護盾都可能截斷路線。滿足指定守衛、首領與印記條件後抵達皇冠才算過關。關內戰力只屬於這次挑戰；通關可解鎖下一關並取得重玩徽章。",
    "選擇已解鎖關卡，先查看整張地圖與下方支撐。",
    "點相連的同色方塊，讀取路線預覽，再確認消除或取消。",
    "等待落下與交戰結束，比較新戰力與下一位守衛，再選另一群方塊。",
    "抵達皇冠後前往下一關或重玩；失誤時可撤銷上一手或重試。",
    "難度如何變化",
    "第1–4關介紹落下、吸收與落點武器。第5關起要比較加法與乘法順序；分開的平台可能要先放走強敵，再讓狐狸落下。中段加入鑰匙、鏡像路線、護盾符文與相連房間。後段需提前安排數層樓的落點，不能只消除腳下地板。第20關檢查接近方向，第25關有第二階段首領，第30關結合旗手、護盾與依序印記。難度來自固定謎題的組合增加，沒有可選的難度模式。",
    "實用技巧",
    "比較兩種順序：先拿+10再×2，比先×2再拿+10多出10戰力。",
    "放下狐狸前先看下一層；有時要讓守衛或補給先落下。",
    "保留必要守衛、補給與皇冠的安全支撐；目標落到尖刺可能直接失敗。",
    "用撤銷比較路線；提示能協助脫困，但無提示徽章需要不用提示通關。",
    "設計筆記",
    "每次消除都是一個可思考的回合。同色群消失後不會補入，因此地形改變會持續影響後續路線。同樣的操作產生同樣的結果，重試是驗證不同順序，不必等待幸運掉落。狐狸接近敵人後自動攻擊；蓄力與接觸動作用來呈現計算結果，不要求反應點擊。鏡頭跟隨下降，也能拖曳、用箭頭或全圖查看畫面外樓層，讓手機維持清楚的局部視野。路線預覽協助計算，但不直接提供通關步驟。",
    "玩家、裝置與存檔",
    "支援觸控、滑鼠及取得焦點的棋盤格鍵盤操作。不需登入，沒有計時或遊戲內付費。每次挑戰約1–3分鐘，難題可花更久。解鎖、徽章、設定與未完成棋局存於此瀏覽器，不跨裝置同步；清除瀏覽器資料可能刪除進度。無法儲存時仍可在當次工作階段遊玩。",
    "古堡常見問題",
    "戰力也是血量嗎？",
    "不是。畫面的數字是攻擊戰力，沒有另一條血量。必須嚴格高於敵方且滿足條件才能獲勝；相等也會輸。獲勝後吸收敵方戰力。",
    "為何狐狸先打敵人，沒有先拿旁邊的道具？",
    "通常優先面對同平台最近且可到達的守衛。只有道具正在狐狸腳下、且該格沒有敵人時，才會優先撿取；守衛距離相同則先往左。",
    "戰力夠高就能忽略護盾與首領條件嗎？",
    "不行。護盾需要對應符文；必要副官、接近方向與印記順序也必須遵守。遇到兩階段首領時，還要擊敗最後形態。",
    "每個守衛都必須擊敗嗎？",
    "只有本關指定目標與仍存活的首領會擋住皇冠；部分側邊守衛可以略過。先看目標顯示與路線。通關解鎖下一關，重玩則可改善徽章。"
  ],
  "zh-Hans": [
    "古堡与任务",
    "带领狐狸沿方块古堡向下夺取皇冠。你决定哪些地板消失，狐狸、守卫与补给便会落在剩下的支撑上。重点是安排安全的交战顺序，不是逐次操控挥剑。强敌、尖刺、锁住的地板与护盾都可能截断路线。满足指定守卫、首领与印记条件后抵达皇冠才算过关。关内战力只属于这次挑战；通关可解锁下一关并获得重玩徽章。",
    "选择已解锁关卡，先查看整张地图与下方支撑。",
    "点相连的同色方块，读取路线预览，再确认消除或取消。",
    "等待落下与交战结束，比较新战力与下一位守卫，再选另一群方块。",
    "抵达皇冠后前往下一关或重玩；失误时可撤销上一手或重试。",
    "难度如何变化",
    "第1–4关介绍落下、吸收与落点武器。第5关起要比较加法与乘法顺序；分开的平台可能要先放走强敌，再让狐狸落下。中段加入钥匙、镜像路线、护盾符文与相连房间。后段需提前安排数层楼的落点，不能只消除脚下地板。第20关检查接近方向，第25关有第二阶段首领，第30关结合旗手、护盾与依序印记。难度来自固定谜题的组合增加，没有可选的难度模式。",
    "实用技巧",
    "比较两种顺序：先拿+10再×2，比先×2再拿+10多出10战力。",
    "放下狐狸前先看下一层；有时要让守卫或补给先落下。",
    "保留必要守卫、补给与皇冠的安全支撑；目标落到尖刺可能直接失败。",
    "用撤销比较路线；提示能协助脱困，但无提示徽章需要不用提示通关。",
    "设计笔记",
    "每次消除都是一个可思考的回合。同色群消失后不会补入，因此地形改变会持续影响后续路线。同样的操作产生同样的结果，重试是验证不同顺序，不必等待幸运掉落。狐狸接近敌人后自动攻击；蓄力与接触动作用来呈现计算结果，不要求反应点击。镜头跟随下降，也能拖曳、用箭头或全图查看画面外楼层，让手机维持清楚的局部视野。路线预览协助计算，但不直接提供通关步骤。",
    "玩家、设备与存档",
    "支持触控、鼠标及获得焦点的棋盘格键盘操作。不需登录，没有计时或游戏内付费。每次挑战约1–3分钟，难题可花更久。解锁、徽章、设置与未完成棋局存于此浏览器，不跨设备同步；清除浏览器数据可能删除进度。无法保存时仍可在当次会话游玩。",
    "古堡常见问题",
    "战力也是血量吗？",
    "不是。画面的数字是攻击战力，没有另一条血量。必须严格高于敌方且满足条件才能获胜；相等也会输。获胜后吸收敌方战力。",
    "为何狐狸先打敌人，没有先拿旁边的道具？",
    "通常优先面对同平台最近且可到达的守卫。只有道具正在狐狸脚下、且该格没有敌人时，才会优先拾取；守卫距离相同则先往左。",
    "战力够高就能忽略护盾与首领条件吗？",
    "不行。护盾需要对应符文；必要副官、接近方向与印记顺序也必须遵守。遇到两阶段首领时，还要击败最后形态。",
    "每个守卫都必须击败吗？",
    "只有本关指定目标与仍存活的首领会挡住皇冠；部分侧边守卫可以略过。先看目标显示与路线。通关解锁下一关，重玩则可改善徽章。"
  ],
  "ja": [
    "古城と目的",
    "キツネをブロックの城の下へ導き、王冠を手に入れます。床を消すとキツネ、敵、道具が残った足場へ落ちます。剣を一振りずつ操作するのではなく、安全な遭遇順を組み立てるゲームです。強敵、針、閉じた床、盾が道を阻みます。指定の敵、ボス、印の条件をすべて満たして王冠に着けばクリア。戦力はその挑戦だけのもので、クリアすると次のステージと再挑戦のバッジにつながります。",
    "開放済みのステージを選び、消す前に全体と下の足場を確認します。",
    "つながる同色のブロックを選び、経路の予告を読んで消去を確定するか取り消します。",
    "落下と戦闘が終わるのを待ち、新しい戦力と次の敵を比べます。",
    "王冠に着いたら次へ進むか再挑戦。失敗した手は戻すか、最初からやり直せます。",
    "難しさの変化",
    "1〜4面は落下、吸収、着地点の剣を紹介。5面以降は足し算と掛け算の順序や、強敵を先に落とす判断が必要です。中盤は鍵、左右反転の道、盾のルーン、連続する部屋が加わります。後半は足元だけでなく数階先の準備が重要。20面は接近方向、25面はボスの第2形態、30面は旗、盾、印の順序を組み合わせます。難易度選択はなく、固定パズルの組合せが複雑になります。",
    "役立つ判断",
    "+10の後に×2なら、×2の後に+10より戦力が10多くなります。",
    "キツネを落とす前に下を確認。敵や道具を先に落とす必要がある場合があります。",
    "必要な敵、道具、王冠を針から守りましょう。目標を失うと失敗することがあります。",
    "一手戻して道を比較。ヒントは助けになりますが、ヒントなしのバッジには使わずクリアする必要があります。",
    "設計について",
    "消去は考えて決める一手です。ブロックは補充されず、空いた場所が後の道を変えます。同じ操作は同じ結果になるため、再挑戦では運ではなく順序を試せます。攻撃は接近後に自動で行われ、構えと接触が計算結果を伝えます。反射的なタップは不要です。カメラは下降を追い、ドラッグ、矢印、全体表示で画面外の階も確認できます。城全体を小さく縮めずにスマートフォンで読める構成です。予告は計画を助けますが、正解の手順は示しません。",
    "操作・端末・保存",
    "タッチ、マウス、フォーカスしたマスのキーボード操作に対応。時間制限、ログイン、ゲーム内課金はありません。1回約1〜3分、難問にはより長くかけられます。開放状況、バッジ、設定、中断した盤面はこのブラウザに保存され、端末間では同期しません。ブラウザデータの削除で失う場合があります。保存できなくても、そのセッションでは遊べます。",
    "城のよくある質問",
    "戦力は体力でもありますか？",
    "いいえ。数字は攻撃の戦力で、別の体力はありません。条件を満たし、敵より厳密に高い戦力なら勝てます。同値は負けで、勝つと敵の戦力を吸収します。",
    "近くの道具より先に戦うのはなぜ？",
    "通常は到達できる最寄りの敵が優先です。ただしキツネの真下に道具があり、そのマスに敵がいなければ先に取ります。敵までの距離が同じなら左からです。",
    "高い戦力で盾やボス条件を無視できますか？",
    "できません。対応するルーン、必要な副官の撃破、接近方向、指定の印の順序が必要です。2段階のボスは最後の形態も倒してください。",
    "すべての敵を倒す必要がありますか？",
    "王冠を妨げるのは指定目標と生きているボスです。一部の脇道の敵は任意なので、目標表示と経路を確認しましょう。クリアで次が開き、再挑戦でバッジを改善できます。"
  ],
  "ko": [
    "고성과 임무",
    "여우를 블록 성 아래로 이끌어 왕관을 얻으세요. 바닥을 없애면 여우, 적, 보급품이 남은 발판으로 떨어집니다. 검을 직접 휘두르기보다 안전한 만남 순서를 정하는 게임입니다. 강한 적, 가시, 잠긴 바닥과 방패가 길을 막습니다. 필수 적과 보스, 인장 조건을 모두 만족한 뒤 왕관에 도착하면 성공입니다. 전투력은 해당 도전에만 적용되며, 클리어하면 다음 단계와 재도전 배지를 얻을 수 있습니다.",
    "열린 단계를 선택하고 바닥을 없애기 전에 전체 지도와 아래 발판을 살펴보세요.",
    "연결된 같은 색 묶음을 누르고 경로 미리보기를 읽은 뒤 제거를 확인하거나 취소하세요.",
    "낙하와 전투가 끝나면 새 전투력을 다음 적과 비교하고 다음 묶음을 고르세요.",
    "왕관에 도착한 뒤 다음 단계나 재도전을 선택하세요. 실수하면 되돌리기 또는 다시 시작을 쓰세요.",
    "난이도의 변화",
    "1–4단계는 낙하, 흡수, 착지점의 검을 소개합니다. 5단계부터는 덧셈과 곱셈 순서, 강한 적을 먼저 떨어뜨리는 선택이 중요합니다. 중반에는 열쇠, 반전 경로, 방패 룬과 연결된 방이 추가됩니다. 후반에는 발밑뿐 아니라 여러 층 아래를 준비해야 합니다. 20단계는 접근 방향, 25단계는 보스의 두 번째 형태, 30단계는 기수·방패·인장 순서를 결합합니다. 난이도 선택 없이 고정 퍼즐의 조합이 복잡해집니다.",
    "유용한 판단",
    "+10 다음 ×2는 ×2 다음 +10보다 전투력이 10 높습니다.",
    "여우를 내리기 전에 아래를 확인하세요. 적이나 보급품을 먼저 떨어뜨려야 할 수 있습니다.",
    "필수 적, 보급품과 왕관을 가시에서 지키세요. 목표물을 잃으면 실패할 수 있습니다.",
    "되돌리기로 경로를 비교하세요. 힌트는 도움이 되지만 무힌트 배지는 힌트 없이 클리어해야 합니다.",
    "설계 노트",
    "제거 한 번은 생각해서 고르는 한 수입니다. 블록은 다시 채워지지 않아 빈자리가 이후 경로에도 영향을 줍니다. 같은 선택은 같은 결과를 내므로 재도전에서는 운 대신 순서를 시험할 수 있습니다. 접근 후 공격은 자동이며, 준비와 타격 동작이 계산 결과를 보여 줍니다. 반사적인 터치는 필요 없습니다. 카메라는 하강을 따라가고 드래그, 화살표와 전체 보기로 화면 밖 층을 확인할 수 있습니다. 성 전체를 작게 줄이지 않고도 휴대전화에서 읽을 수 있습니다. 미리보기는 계획을 돕지만 정답 순서를 알려 주지는 않습니다.",
    "조작·기기·저장",
    "터치, 마우스와 초점을 둔 칸의 키보드 조작을 지원합니다. 시간제한, 로그인, 게임 내 결제는 없습니다. 한 번에 약 1–3분이며 어려운 경로에는 더 오래 쓸 수 있습니다. 열린 단계, 배지, 설정과 미완성 퍼즐은 이 브라우저에 저장되고 기기 간 동기화되지 않습니다. 브라우저 데이터를 지우면 사라질 수 있습니다. 저장할 수 없어도 현재 세션에서는 계속 플레이할 수 있습니다.",
    "고성 질문",
    "전투력은 체력이기도 한가요?",
    "아닙니다. 표시 숫자는 공격 전투력이며 별도 체력은 없습니다. 조건을 만족하고 적보다 반드시 높아야 이깁니다. 같으면 지고, 이기면 적의 전투력을 흡수합니다.",
    "왜 근처 아이템보다 적을 먼저 공격하나요?",
    "보통 도달 가능한 가장 가까운 적이 우선입니다. 다만 여우 바로 아래에 아이템이 있고 같은 칸에 적이 없으면 먼저 줍습니다. 적과 거리가 같으면 왼쪽부터 접근합니다.",
    "전투력이 높으면 방패나 보스 조건을 무시할 수 있나요?",
    "없습니다. 맞는 룬, 필수 부하 처치, 접근 방향과 지정 인장 순서를 따라야 합니다. 두 형태 보스는 마지막 형태도 쓰러뜨려야 합니다.",
    "모든 적을 쓰러뜨려야 하나요?",
    "단계의 필수 목표와 살아 있는 보스가 왕관을 막습니다. 일부 곁길 적은 선택 사항이니 목표 표시와 경로를 확인하세요. 클리어는 다음 단계를 열고 재도전은 배지를 개선합니다."
  ],
  "es": [
    "El castillo y tu misión",
    "Guía al zorro por un castillo de bloques hasta la corona. Tú eliges qué suelos desaparecen; el zorro, los guardias y los objetos caen sobre los soportes restantes. Debes ordenar encuentros seguros, no controlar cada espadazo. Enemigos fuertes, pinchos, suelos cerrados y escudos pueden cortar la ruta. Ganas al llegar a la corona tras cumplir los objetivos, jefes y sellos necesarios. El poder pertenece a ese intento; completar el puzle abre el siguiente y permite ganar insignias.",
    "Elige un nivel abierto e inspecciona el mapa completo y los apoyos inferiores.",
    "Toca un grupo conectado del mismo color, lee la vista previa y confirma o cancela.",
    "Espera a que terminen las caídas y los combates; compara tu nuevo poder con el siguiente guardia.",
    "Al obtener la corona, avanza o repite. Deshaz una acción equivocada o reinicia el puzle.",
    "Cómo aumenta el desafío",
    "Los niveles 1–4 presentan caída, absorción y espada de aterrizaje. Desde el 5 importa sumar antes de multiplicar; ciertos suelos separados exigen apartar primero al guardia fuerte. El tramo medio añade llaves, rutas reflejadas, runas y salas conectadas. Después debes preparar varios pisos, no solo quitar el suelo bajo tus pies. El nivel 20 comprueba el lado de llegada; el 25 tiene una segunda fase de jefe; el 30 combina bandera, escudo y sellos ordenados. Son puzles fijos con más combinaciones, sin selector de dificultad.",
    "Decisiones útiles",
    "Recoger +10 antes de ×2 da 10 puntos más que hacerlo después.",
    "Mira el piso inferior antes de soltar al zorro; quizá deban caer primero un guardia o un objeto.",
    "Protege de los pinchos a los objetivos, objetos y corona. Perder un objetivo puede terminar el intento.",
    "Compara rutas con deshacer. Las pistas ayudan, pero la insignia sin pistas exige ganar sin usarlas.",
    "Nota de diseño",
    "Cada eliminación es un turno deliberado. Los bloques no se reponen: el hueco cambia permanentemente la ruta. Las mismas decisiones dan el mismo resultado, de modo que repetir permite probar otro orden en lugar de esperar suerte. Los ataques son automáticos tras acercarse; la preparación y el impacto explican el cálculo, sin exigir un toque por reflejo. La cámara sigue el descenso y permite arrastrar, usar flechas o ver el mapa completo. Así puedes inspeccionar pisos fuera de pantalla sin reducir todo el castillo a una imagen diminuta. La vista previa ayuda a planear, pero no entrega la solución.",
    "Jugador, dispositivo y guardado",
    "Usa pantalla táctil, ratón o teclado en casillas enfocadas. No hay reloj, inicio de sesión ni compras dentro del juego. Calcula 1–3 minutos por intento, más en rutas difíciles. Niveles, insignias, ajustes y partida pendiente se guardan en este navegador, sin sincronización entre dispositivos. Borrar sus datos puede eliminarlos. Si el guardado no está disponible, puedes seguir en la sesión.",
    "Preguntas del castillo",
    "¿El poder también es salud?",
    "No. El número indica poder de ataque, sin salud separada. Necesitas superar estrictamente al guardia y cumplir las condiciones; un empate pierde. Al vencer, absorbes su poder.",
    "¿Por qué lucha antes de recoger un objeto cercano?",
    "Normalmente tiene prioridad el guardia alcanzable más cercano. Un objeto justo bajo el zorro se recoge antes solo si ningún enemigo ocupa esa casilla. A igual distancia, va primero a la izquierda.",
    "¿Mucho poder permite ignorar un escudo o una regla del jefe?",
    "No. Necesitas la runa correspondiente, derrotar a los ayudantes exigidos, respetar el lado de llegada y recoger los sellos en orden. Un jefe de dos fases también debe caer en su forma final.",
    "¿Hay que derrotar a todos los guardias?",
    "Solo los objetivos obligatorios y los jefes vivos bloquean la corona; algunos guardias laterales son opcionales. Revisa los objetivos y la ruta. Ganar abre el siguiente nivel; repetir mejora insignias."
  ],
  "pt-BR": [
    "O castelo e sua missão",
    "Guie a raposa por um castelo de blocos até a coroa. Você decide quais pisos somem; raposa, guardas e suprimentos caem nos apoios restantes. O desafio é ordenar encontros seguros, não controlar cada golpe. Inimigos fortes, espinhos, pisos trancados e escudos podem interromper o caminho. Vença chegando à coroa após cumprir os alvos, chefes e selos exigidos. O poder vale apenas nessa tentativa; completar o desafio abre o próximo e rende medalhas.",
    "Escolha uma fase aberta e examine o mapa inteiro e os apoios abaixo.",
    "Toque um grupo conectado da mesma cor, leia a prévia e confirme a remoção ou cancele.",
    "Espere quedas e combates terminarem; compare o novo poder com o próximo guarda.",
    "Ao pegar a coroa, avance ou repita. Desfaça uma ação errada ou reinicie o desafio.",
    "Como o desafio cresce",
    "As fases 1–4 apresentam queda, absorção e espada no ponto de pouso. Desde a 5, somar antes de multiplicar importa; pisos separados podem exigir afastar primeiro o guarda forte. No meio surgem chaves, rotas espelhadas, runas e salas conectadas. Depois é preciso preparar vários andares, não apenas tirar o chão dos pés. A fase 20 verifica o lado de aproximação; a 25 tem um chefe de duas fases; a 30 combina bandeira, escudo e selos ordenados. São desafios fixos com mais combinações, sem seleção de dificuldade.",
    "Decisões úteis",
    "Pegar +10 antes de ×2 dá 10 pontos a mais que pegar depois.",
    "Confira o pouso inferior antes de soltar a raposa; um guarda ou suprimento pode precisar cair primeiro.",
    "Proteja alvos, suprimentos e coroa dos espinhos. Perder um objetivo pode encerrar a tentativa.",
    "Compare rotas desfazendo ações. Dicas ajudam, mas a medalha sem dicas exige vencer sem usá-las.",
    "Nota de design",
    "Cada remoção é um turno pensado. Os blocos não voltam: o espaço vazio muda a rota das próximas ações. As mesmas escolhas produzem o mesmo resultado, permitindo testar outra ordem ao repetir, sem depender da sorte. O ataque acontece automaticamente após a aproximação; preparação e impacto mostram o cálculo, sem toque de reflexo. A câmera acompanha a descida; arrastar, setas e visão geral permitem olhar andares fora da tela. Assim o castelo alto fica legível no celular sem diminuir todo o desafio. A prévia ajuda a planejar, mas não fornece a sequência vencedora.",
    "Jogador, dispositivo e salvamento",
    "Use toque, mouse ou teclado nas casas em foco. Não há cronômetro, login nem compras no jogo. Reserve cerca de 1–3 minutos por tentativa, mais nas rotas difíceis. Fases abertas, medalhas, configurações e partida pendente ficam neste navegador, sem sincronizar dispositivos. Apagar seus dados pode removê-los. Se não for possível salvar, ainda dá para jogar na sessão.",
    "Perguntas do castelo",
    "Poder também é vida?",
    "Não. O número representa ataque, sem vida separada. É preciso superar estritamente o guarda e cumprir suas condições; empate perde. Ao vencer, você absorve o poder dele.",
    "Por que lutar antes de pegar um item próximo?",
    "Normalmente o guarda alcançável mais próximo tem prioridade. Um item logo sob a raposa vem primeiro apenas se nenhum inimigo ocupa aquela casa. Em distâncias iguais, a esquerda vem primeiro.",
    "Poder alto ignora escudos ou regras do chefe?",
    "Não. Obtenha a runa certa, derrote os ajudantes exigidos, respeite o lado de aproximação e recolha selos na ordem. Um chefe de duas fases também precisa ser vencido na forma final.",
    "É preciso vencer todos os guardas?",
    "Só os alvos obrigatórios e chefes vivos bloqueiam a coroa; alguns guardas laterais são opcionais. Verifique alvos e caminho antes de ignorá-los. Vencer abre a próxima fase; repetir melhora medalhas."
  ],
  "fr": [
    "Le château et votre mission",
    "Guidez le renard dans un château de blocs jusqu’à la couronne. Vous choisissez les sols qui disparaissent ; renard, gardes et objets tombent sur les appuis restants. Il faut organiser des rencontres sûres, sans commander chaque coup d’épée. Ennemis puissants, pointes, sols verrouillés et boucliers peuvent interrompre la descente. Atteignez la couronne après avoir rempli toutes les conditions de cibles, boss et sceaux. La puissance appartient à cette tentative ; une réussite ouvre l’énigme suivante et permet de gagner des badges.",
    "Choisissez un niveau ouvert et examinez toute la carte ainsi que les appuis inférieurs.",
    "Touchez un groupe relié de même couleur, lisez l’aperçu puis confirmez ou annulez.",
    "Attendez la fin des chutes et combats ; comparez votre nouvelle puissance au prochain garde.",
    "À la couronne, continuez ou rejouez. Annulez une mauvaise action ou recommencez l’énigme.",
    "Évolution du défi",
    "Les niveaux 1–4 présentent chute, absorption et épée à l’atterrissage. Dès le 5, l’ordre addition-multiplication compte ; des sols séparés demandent parfois d’écarter d’abord un garde puissant. Au milieu arrivent clés, trajets en miroir, runes et salles liées. Ensuite, préparez plusieurs étages au lieu de retirer seulement le sol sous vos pieds. Le niveau 20 impose un côté d’approche, le 25 un boss à deux phases et le 30 combine bannière, bouclier et sceaux ordonnés. La difficulté vient des combinaisons fixes, sans mode à sélectionner.",
    "Décisions utiles",
    "Prendre +10 avant ×2 donne 10 points de plus que le prendre après.",
    "Inspectez l’étage inférieur avant de lâcher le renard ; un garde ou un objet doit parfois tomber d’abord.",
    "Gardez les cibles, objets et couronne loin des pointes. Perdre un objectif peut terminer la tentative.",
    "Comparez les trajets avec Annuler. Les indices aident, mais le badge sans indice exige une réussite sans en utiliser.",
    "Note de conception",
    "Chaque retrait est un tour réfléchi. Les blocs ne reviennent pas : le vide modifie durablement le trajet. Les mêmes choix donnent le même résultat, permettant de tester un autre ordre plutôt que d’attendre la chance. L’attaque est automatique après l’approche ; préparation et contact rendent le calcul visible, sans demander un toucher réflexe. La caméra suit la descente ; glissement, flèches et vue d’ensemble dévoilent les étages hors écran. Le château reste ainsi lisible sur téléphone sans réduire tout le puzzle à une miniature. L’aperçu aide à planifier, mais ne fournit pas la solution.",
    "Joueur, appareil et sauvegarde",
    "Jouez au toucher, à la souris ou au clavier sur les cases ciblées. Aucun chrono, compte ou achat en jeu. Prévoyez environ 1–3 minutes par tentative, davantage pour les trajets difficiles. Niveaux, badges, réglages et partie inachevée restent dans ce navigateur, sans synchronisation entre appareils. Effacer ses données peut les supprimer. Sans stockage disponible, vous pouvez continuer pendant la session.",
    "Questions du château",
    "La puissance représente-t-elle aussi la santé ?",
    "Non. Le nombre est la puissance d’attaque, sans réserve de santé distincte. Il faut strictement dépasser le garde et remplir ses conditions ; l’égalité perd. La victoire absorbe sa puissance.",
    "Pourquoi combattre avant de prendre un objet proche ?",
    "Le garde accessible le plus proche est normalement prioritaire. Un objet sous le renard passe d’abord uniquement si aucun ennemi n’occupe cette case. À distance égale, le renard va à gauche.",
    "Une grande puissance ignore-t-elle boucliers et règles du boss ?",
    "Non. Il faut la bonne rune, battre les adjoints requis, respecter le côté d’approche et ramasser les sceaux dans l’ordre. Un boss à deux phases doit aussi être vaincu sous sa forme finale.",
    "Faut-il battre tous les gardes ?",
    "Seules les cibles imposées et les boss vivants bloquent la couronne ; certains gardes latéraux sont facultatifs. Vérifiez les objectifs et le trajet. Réussir ouvre le niveau suivant ; rejouer améliore les badges."
  ],
  "de": [
    "Burg und Aufgabe",
    "Führe den Fuchs durch eine Blockburg zur Krone. Du bestimmst, welche Böden verschwinden; Fuchs, Wächter und Vorräte fallen auf die übrigen Stützen. Plane sichere Begegnungen, statt jeden Schwertschlag zu steuern. Starke Gegner, Stacheln, verschlossene Böden und Schilde versperren den Weg. Erfolg bedeutet, die Krone nach allen Pflichtgegnern, Bossen und Siegelbedingungen zu erreichen. Stärke gilt nur für diesen Versuch; ein Sieg öffnet das nächste Rätsel und bringt Abzeichen.",
    "Wähle eine offene Stufe und prüfe die gesamte Karte sowie die unteren Stützen.",
    "Tippe eine verbundene Farbgruppe an, lies die Vorschau und bestätige oder verwirf den Zug.",
    "Warte auf das Ende von Fall und Kampf. Vergleiche die neue Stärke mit dem nächsten Wächter.",
    "Nach der Krone geht es weiter oder erneut los. Nimm einen Fehler zurück oder starte das Rätsel neu.",
    "So wächst die Herausforderung",
    "Stufen 1–4 zeigen Fallen, Absorption und ein Schwert am Landeplatz. Ab Stufe 5 zählt die Reihenfolge von Addition und Multiplikation; getrennte Böden verlangen manchmal, zuerst einen starken Wächter wegfallen zu lassen. In der Mitte kommen Schlüssel, gespiegelte Wege, Runen und verbundene Räume hinzu. Später musst du mehrere Stockwerke vorbereiten. Stufe 20 prüft die Annäherungsseite, 25 enthält eine zweite Bossphase und 30 kombiniert Banner, Schild und geordnete Siegel. Feste Rätsel werden komplexer; es gibt keine Schwierigkeitsauswahl.",
    "Nützliche Entscheidungen",
    "+10 vor ×2 bringt 10 Stärkepunkte mehr als +10 danach.",
    "Prüfe vor dem Fallen den unteren Landeplatz. Manchmal muss erst ein Wächter oder Vorrat hinunter.",
    "Schütze Pflichtgegner, Vorräte und Krone vor Stacheln. Ein verlorenes Ziel kann den Versuch beenden.",
    "Vergleiche Wege mit Rückgängig. Hinweise helfen, aber das Abzeichen ohne Hinweise verlangt einen Sieg ohne sie.",
    "Gedanken zum Design",
    "Jede Entfernung ist ein überlegter Zug. Blöcke werden nicht aufgefüllt; ihre Lücke verändert spätere Wege dauerhaft. Gleiche Entscheidungen liefern gleiche Ergebnisse, sodass ein neuer Versuch eine andere Reihenfolge prüft, statt auf Glück zu hoffen. Nach der Annäherung erfolgt der Angriff automatisch. Ausholen und Kontakt zeigen die Rechnung, ohne einen schnellen Reaktionstipp zu verlangen. Die Kamera folgt dem Abstieg; Ziehen, Pfeile und Übersicht zeigen Stockwerke außerhalb des Bildes. So bleibt eine hohe Burg auf dem Handy lesbar, ohne das gesamte Rätsel winzig darzustellen. Die Vorschau hilft beim Planen, verrät aber keine Gewinnfolge.",
    "Spieler, Geräte und Speichern",
    "Nutze Touch, Maus oder Tastatur für fokussierte Felder. Es gibt weder Zeitlimit noch Anmeldung oder Käufe im Spiel. Ein Versuch dauert ungefähr 1–3 Minuten, schwierige Wege länger. Freischaltungen, Abzeichen, Einstellungen und ein offener Versuch bleiben lokal in diesem Browser, ohne Gerätesynchronisation. Gelöschte Browserdaten können sie entfernen. Ohne Speicher kannst du in der Sitzung weiterspielen.",
    "Fragen zur Burg",
    "Ist Stärke auch Gesundheit?",
    "Nein. Die Zahl ist Angriffsstärke, ohne getrennte Gesundheit. Du musst den Wächter strikt übertreffen und seine Bedingungen erfüllen; Gleichstand verliert. Ein Sieg übernimmt seine Stärke.",
    "Warum kämpft der Fuchs vor dem nahen Gegenstand?",
    "Normalerweise hat der nächste erreichbare Wächter Vorrang. Ein Gegenstand direkt unter dem Fuchs kommt zuerst, wenn kein Gegner dasselbe Feld besetzt. Bei gleicher Entfernung geht es zuerst nach links.",
    "Kann hohe Stärke Schilde oder Bossregeln umgehen?",
    "Nein. Hole die passende Rune, besiege erforderliche Stellvertreter, beachte die Annäherungsseite und sammle Siegel in der Reihenfolge. Ein Zweiphasenboss muss auch in seiner letzten Form fallen.",
    "Müssen alle Wächter besiegt werden?",
    "Nur Pflichtziele und lebende Bosse blockieren die Krone; manche Seitenwächter sind optional. Prüfe Zielanzeige und Weg vor dem Überspringen. Siege öffnen die nächste Stufe, Wiederholungen verbessern Abzeichen."
  ],
  "it": [
    "Il castello e la missione",
    "Guida la volpe nel castello di blocchi fino alla corona. Scegli quali pavimenti spariscono; volpe, guardie e oggetti cadono sui sostegni rimasti. Devi ordinare incontri sicuri, non controllare ogni colpo di spada. Nemici forti, punte, pavimenti chiusi e scudi possono fermarti. Vinci raggiungendo la corona dopo tutti gli obiettivi, boss e sigilli richiesti. La forza vale per quel tentativo; completare l’enigma apre il successivo e permette di ottenere distintivi.",
    "Scegli un livello aperto e osserva tutta la mappa e i sostegni inferiori.",
    "Tocca un gruppo collegato dello stesso colore, leggi l’anteprima e conferma o annulla.",
    "Aspetta la fine di cadute e scontri; confronta la nuova forza con la guardia successiva.",
    "Dopo la corona, avanza o riprova. Annulla una mossa sbagliata o ricomincia l’enigma.",
    "Come cresce la sfida",
    "I livelli 1–4 introducono caduta, assorbimento e spada all’atterraggio. Dal 5 conta l’ordine tra somma e moltiplicazione; i pavimenti separati possono richiedere di allontanare prima una guardia forte. A metà arrivano chiavi, percorsi specchiati, rune e stanze collegate. Più avanti devi preparare diversi piani, non solo eliminare quello sotto i piedi. Il livello 20 verifica il lato d’approccio; il 25 ha un boss a due fasi; il 30 combina bandiera, scudo e sigilli ordinati. La difficoltà deriva da combinazioni fisse, senza modalità selezionabili.",
    "Decisioni utili",
    "Prendere +10 prima di ×2 dà 10 punti in più che prenderlo dopo.",
    "Controlla l’atterraggio inferiore prima di far scendere la volpe: una guardia o un oggetto potrebbe dover cadere prima.",
    "Proteggi obiettivi, oggetti e corona dalle punte. Perdere un obiettivo può terminare il tentativo.",
    "Confronta i percorsi annullando le mosse. Gli indizi aiutano, ma il distintivo senza indizi richiede una vittoria senza usarli.",
    "Nota di progettazione",
    "Ogni rimozione è un turno ragionato. I blocchi non si rigenerano: il vuoto cambia stabilmente il percorso. Le stesse scelte producono lo stesso risultato, quindi riprovare serve a verificare un ordine diverso, senza aspettare fortuna. L’attacco è automatico dopo l’avvicinamento; preparazione e impatto mostrano il calcolo, senza richiedere un tocco di riflesso. La telecamera segue la discesa; trascinamento, frecce e panoramica permettono di vedere i piani fuori schermo. Il castello resta leggibile sul telefono senza ridurre tutto l’enigma a una miniatura. L’anteprima aiuta a pianificare, ma non fornisce la soluzione.",
    "Giocatore, dispositivo e salvataggio",
    "Usa tocco, mouse o tastiera sulle caselle selezionate. Non ci sono timer, accesso obbligatorio o acquisti nel gioco. Considera circa 1–3 minuti per tentativo, di più per i percorsi difficili. Livelli, distintivi, impostazioni e partita incompleta restano in questo browser, senza sincronizzazione tra dispositivi. Cancellarne i dati può eliminarli. Se il salvataggio non funziona, puoi continuare nella sessione.",
    "Domande sul castello",
    "La forza è anche salute?",
    "No. Il numero indica forza d’attacco, senza salute separata. Devi superare strettamente la guardia e rispettare le condizioni; la parità perde. Vincendo ne assorbi la forza.",
    "Perché combatte prima di prendere un oggetto vicino?",
    "Di norma ha priorità la guardia raggiungibile più vicina. Un oggetto sotto la volpe viene raccolto prima solo se nessun nemico occupa quella casella. A pari distanza, va prima a sinistra.",
    "La forza elevata ignora scudi e regole dei boss?",
    "No. Servono la runa giusta, i sottoposti obbligatori sconfitti, il lato d’approccio corretto e i sigilli nell’ordine. Un boss a due fasi va battuto anche nella forma finale.",
    "Devo battere tutte le guardie?",
    "Solo gli obiettivi obbligatori e i boss vivi bloccano la corona; alcune guardie laterali sono facoltative. Controlla obiettivi e percorso. Vincere apre il livello seguente; ripetere migliora i distintivi."
  ],
  "ru": [
    "Замок и ваша задача",
    "Проведите лиса вниз по блочному замку к короне. Вы выбираете исчезающие полы; лис, стражи и припасы падают на оставшиеся опоры. Нужно выстроить безопасный порядок встреч, а не управлять каждым взмахом меча. Сильные враги, шипы, запертые полы и щиты преграждают путь. Победа — корона после выполнения всех условий обязательных целей, боссов и печатей. Сила действует только в этой попытке; прохождение открывает следующий этап и даёт значки.",
    "Выберите открытый этап и осмотрите всю карту и опоры внизу.",
    "Нажмите на связанную одноцветную группу, изучите предварительный маршрут и подтвердите или отмените удаление.",
    "Дождитесь конца падений и боёв, сравните новую силу со следующим стражем.",
    "Получив корону, продолжайте или повторите этап. Ошибочную операцию можно отменить либо начать заново.",
    "Как растёт сложность",
    "Этапы 1–4 знакомят с падением, поглощением и мечом на месте приземления. С 5-го важен порядок сложения и умножения; иногда сначала нужно сбросить сильного стража с отдельной опоры. В середине появляются ключи, зеркальные пути, руны и связанные комнаты. Позднее требуется готовить несколько этажей. Этап 20 проверяет сторону подхода, 25 содержит вторую фазу босса, а 30 объединяет знамя, щит и порядок печатей. Усложняются сочетания фиксированных задач; выбора режима сложности нет.",
    "Полезные решения",
    "+10 перед ×2 даёт на 10 силы больше, чем +10 после умножения.",
    "Осмотрите нижнюю площадку до спуска лиса: сначала может понадобиться сбросить стража или припас.",
    "Берегите обязательные цели, припасы и корону от шипов. Потеря цели может закончить попытку.",
    "Сравнивайте пути через отмену. Подсказка помогает, но значок без подсказок требует победить без неё.",
    "О замысле игры",
    "Каждое удаление — обдуманный ход. Блоки не восполняются, поэтому пустота надолго меняет маршрут. Одинаковые решения дают одинаковый результат: повтор позволяет проверить другой порядок, а не ждать удачи. Атака происходит автоматически после сближения; замах и удар показывают расчёт, не требуя быстрой реакции. Камера следует вниз, а перетаскивание, стрелки и обзор показывают этажи за пределами экрана. Высокий замок остаётся читаемым на телефоне без уменьшения всей задачи до миниатюры. Предпросмотр помогает планировать, но не выдаёт последовательность победы.",
    "Устройства и сохранение",
    "Доступны касание, мышь и клавиатура для ячеек в фокусе. Нет таймера, входа в аккаунт или покупок в игре. Попытка занимает примерно 1–3 минуты, сложные пути — дольше. Открытые этапы, значки, настройки и незаконченная задача хранятся в этом браузере без синхронизации устройств. Очистка его данных может удалить прогресс. Если сохранение недоступно, можно продолжать в текущем сеансе.",
    "Вопросы о замке",
    "Сила — это ещё и здоровье?",
    "Нет. Число обозначает силу атаки, отдельного здоровья нет. Нужно строго превосходить стража и выполнить условия; равенство проигрывает. Победа добавляет его силу.",
    "Почему лис сражается раньше, чем берёт предмет рядом?",
    "Обычно приоритет у ближайшего доступного стража. Предмет прямо под лисом берётся первым, только если в той же ячейке нет врага. При равных расстояниях лис сначала идёт влево.",
    "Можно ли большой силой обойти щит или условие босса?",
    "Нет. Нужны подходящая руна, победа над обязательными помощниками, правильная сторона подхода и порядок печатей. Двухфазного босса надо победить и в последней форме.",
    "Нужно побеждать всех стражей?",
    "Корону блокируют обязательные цели и живые боссы; некоторые боковые стражи необязательны. Проверьте цели и путь перед пропуском. Победа открывает следующий этап, повтор улучшает значки."
  ],
  "hi": [
    "महल और आपका लक्ष्य",
    "लोमड़ी को ब्लॉक वाले महल में नीचे ताज तक पहुँचाएँ। आप तय करते हैं कि कौन-सा फर्श हटेगा; लोमड़ी, रक्षक और सामान बचे हुए सहारों पर गिरते हैं। हर तलवार का वार चलाने के बजाय सुरक्षित मुठभेड़ों का क्रम बनाना है। शक्तिशाली शत्रु, काँटे, बंद फर्श और ढाल रास्ता रोक सकते हैं। सभी आवश्यक शत्रु, मुखिया और मुहर की शर्तें पूरी करके ताज तक पहुँचना जीत है। शक्ति केवल उस प्रयास की होती है; जीत अगला स्तर खोलती है और पदक दिलाती है।",
    "खुला स्तर चुनें और फर्श हटाने से पहले पूरा नक्शा तथा नीचे के सहारे देखें।",
    "जुड़े एक रंग के समूह को दबाएँ, रास्ते का पूर्वावलोकन पढ़ें और हटाना स्वीकार करें या रद्द करें।",
    "गिरना और लड़ाई समाप्त होने दें; नई शक्ति को अगले रक्षक से तुलना करें।",
    "ताज मिलने पर आगे जाएँ या फिर खेलें। गलत चाल वापस लें या पहेली फिर शुरू करें।",
    "चुनौती कैसे बढ़ती है",
    "स्तर 1–4 में गिरना, शक्ति सोखना और उतरने की जगह पर तलवार मिलती है। स्तर 5 से जोड़ और गुणा का क्रम महत्त्वपूर्ण है; अलग फर्श पर कभी शक्तिशाली रक्षक को पहले हटाना होता है। बीच में चाबियाँ, उल्टे रास्ते, रून्स और जुड़े कमरे आते हैं। आगे कई मंज़िलों की तैयारी करनी होती है। स्तर 20 में पहुँचने की दिशा, 25 में मुखिया का दूसरा रूप और 30 में ध्वज, ढाल तथा क्रम वाली मुहरें हैं। तय पहेलियों के मेल कठिन होते हैं; कठिनाई चुनने का अलग विकल्प नहीं है।",
    "उपयोगी फैसले",
    "×2 से पहले +10 लेने पर, बाद में +10 लेने से 10 शक्ति अधिक मिलती है।",
    "लोमड़ी गिराने से पहले नीचे देखें; कभी रक्षक या सामान को पहले गिराना पड़ता है।",
    "आवश्यक रक्षक, सामान और ताज को काँटों से बचाएँ। लक्ष्य खोने पर प्रयास समाप्त हो सकता है।",
    "चाल वापस लेकर रास्ते तुलना करें। संकेत मदद करते हैं, पर बिना संकेत पदक के लिए उनका उपयोग किए बिना जीतना होगा।",
    "डिज़ाइन टिप्पणी",
    "हर हटाना सोचकर लिया गया एक मोड़ है। ब्लॉक फिर नहीं भरते, इसलिए खाली जगह आगे का रास्ता स्थायी रूप से बदलती है। समान चालों से समान परिणाम मिलता है; दोबारा खेलना भाग्य के बजाय दूसरे क्रम को जाँचता है। पास आने के बाद हमला अपने आप होता है। तैयारी और संपर्क का दृश्य गणना बताता है, तेज़ प्रतिक्रिया वाला स्पर्श नहीं माँगता। कैमरा नीचे चलता है; खींचना, तीर और पूरा दृश्य स्क्रीन से बाहर की मंज़िलें दिखाते हैं। इससे फोन पर पूरे महल को बहुत छोटा किए बिना रास्ता पढ़ा जा सकता है। पूर्वावलोकन योजना में मदद करता है, जीत का पूरा क्रम नहीं बताता।",
    "खिलाड़ी, उपकरण और सहेजना",
    "स्पर्श, माउस और फ़ोकस वाले खाने के लिए कीबोर्ड उपलब्ध हैं। समय सीमा, लॉगिन या खेल में खरीदारी नहीं है। प्रति प्रयास लगभग 1–3 मिनट रखें; कठिन रास्तों में अधिक लग सकता है। खुले स्तर, पदक, सेटिंग और अधूरी पहेली इसी ब्राउज़र में रहती हैं, उपकरणों के बीच सिंक नहीं होतीं। ब्राउज़र डेटा मिटाने से ये हट सकती हैं। सहेजना उपलब्ध न हो तो भी वर्तमान सत्र में खेल सकते हैं।",
    "महल के प्रश्न",
    "क्या शक्ति ही स्वास्थ्य भी है?",
    "नहीं। अंक हमले की शक्ति है; अलग स्वास्थ्य नहीं है। रक्षक से शक्ति अधिक और उसकी शर्तें पूरी होनी चाहिए; बराबरी पर हार है। जीतने पर उसकी शक्ति जुड़ती है।",
    "लोमड़ी पास का सामान लेने से पहले क्यों लड़ती है?",
    "आमतौर पर निकटतम पहुँच योग्य रक्षक पहले आता है। लोमड़ी के ठीक नीचे का सामान पहले तभी मिलता है जब उसी खाने में शत्रु न हो। दूरी बराबर हो तो पहले बाएँ जाती है।",
    "क्या अधिक शक्ति ढाल या मुखिया की शर्तों को अनदेखा कर सकती है?",
    "नहीं। सही रून लें, आवश्यक सहायकों को हराएँ, सही दिशा से पहुँचें और मुहरें क्रम से लें। दो रूप वाले मुखिया को अंतिम रूप में भी हराना होगा।",
    "क्या हर रक्षक को हराना ज़रूरी है?",
    "केवल आवश्यक लक्ष्य और जीवित मुखिया ताज रोकते हैं; कुछ किनारे के रक्षक वैकल्पिक हैं। छोड़ने से पहले लक्ष्य और रास्ता देखें। जीत अगला स्तर खोलती है; दोबारा खेलकर पदक बेहतर होते हैं।"
  ],
  "ar": [
    "القلعة ومهمتك",
    "قد الثعلب نزولًا عبر قلعة الكتل إلى التاج. تختار الأرضيات التي تختفي، ثم يسقط الثعلب والحراس والمؤن على الدعامات الباقية. المطلوب ترتيب مواجهات آمنة، لا التحكم بكل ضربة سيف. قد يوقفك عدو قوي أو شوك أو أرضية مقفلة أو درع. الفوز هو الوصول للتاج بعد تحقيق شروط الأهداف والزعماء والأختام المطلوبة. القوة تخص هذه المحاولة؛ إكمال اللغز يفتح التالي ويتيح كسب الشارات.",
    "اختر مرحلة مفتوحة وافحص الخريطة كاملة والدعامات السفلى قبل الإزالة.",
    "اضغط مجموعة متصلة من لون واحد، واقرأ معاينة المسار ثم أكد الإزالة أو ألغها.",
    "انتظر نهاية السقوط والقتال، ثم قارن قوتك الجديدة بالحارس التالي.",
    "بعد التاج انتقل أو أعد اللعب. تراجع عن حركة خاطئة أو ابدأ اللغز مجددًا.",
    "كيف تتطور الصعوبة",
    "تقدم المراحل 1–4 السقوط وامتصاص القوة وسيف الهبوط. من المرحلة 5 يهم ترتيب الجمع والضرب؛ وقد تتطلب الأرضيات المنفصلة إسقاط الحارس القوي أولًا. في الوسط تظهر مفاتيح ومسارات معكوسة ورونات وغرف متصلة. لاحقًا يجب تجهيز عدة طوابق بدل إزالة ما تحتك فقط. المرحلة 20 تفحص جهة الاقتراب، و25 تضم طورًا ثانيًا للزعيم، و30 تجمع الراية والدرع والأختام المرتبة. تتعقد تركيبات الألغاز الثابتة دون خيار لاختيار الصعوبة.",
    "قرارات مفيدة",
    "جمع +10 قبل ×2 يمنح قوة إضافية قدرها 10 مقارنة بجمعها بعد الضرب.",
    "افحص موضع الهبوط السفلي قبل إسقاط الثعلب؛ قد يلزم إسقاط حارس أو مؤن أولًا.",
    "احم الأهداف المطلوبة والمؤن والتاج من الأشواك. فقدان هدف قد ينهي المحاولة.",
    "قارن المسارات بالتراجع. التلميح يساعد، لكن شارة بلا تلميحات تتطلب الفوز دون استخدامه.",
    "ملاحظة التصميم",
    "كل إزالة دور يمكن التفكير فيه. لا تتجدد الكتل، لذا تغير الفجوة المسارات التالية بصورة دائمة. تؤدي الخيارات نفسها إلى النتيجة نفسها؛ فالإعادة تختبر ترتيبًا مختلفًا بدل انتظار الحظ. الهجوم تلقائي بعد الاقتراب، وتوضح حركة الاستعداد والاصطدام العملية الحسابية دون طلب نقرة سريعة. تتبع الكاميرا النزول، ويتيح السحب والأسهم والمنظر العام رؤية الطوابق خارج الشاشة. تبقى القلعة الطويلة واضحة على الهاتف دون تصغير اللغز كله. تساعد المعاينة على التخطيط لكنها لا تقدم تسلسل الفوز.",
    "اللاعب والجهاز والحفظ",
    "استخدم اللمس أو الفأرة أو لوحة المفاتيح للخلايا المحددة. لا مؤقت ولا تسجيل دخول ولا مشتريات داخل اللعبة. تستغرق المحاولة نحو 1–3 دقائق، وقد تطول المسارات الصعبة. تحفظ المراحل والشارات والإعدادات واللغز غير المكتمل في هذا المتصفح دون مزامنة بين الأجهزة. قد يؤدي مسح بياناته إلى فقدانها. إذا تعذر الحفظ يمكنك مواصلة اللعب خلال الجلسة.",
    "أسئلة القلعة",
    "هل القوة تعني الصحة أيضًا؟",
    "لا. الرقم هو قوة الهجوم ولا يوجد رصيد صحة منفصل. يجب أن تتجاوز الحارس فعلًا وتستوفي الشروط؛ التعادل خسارة. عند الفوز تضاف قوته إلى قوتك.",
    "لماذا يقاتل الثعلب قبل التقاط غرض قريب؟",
    "عادة تكون الأولوية لأقرب حارس يمكن الوصول إليه. يلتقط الغرض الموجود تحت الثعلب أولًا فقط إن لم يشغل عدو الخلية نفسها. وعند تساوي المسافات يتجه يسارًا أولًا.",
    "هل تسمح القوة العالية بتجاهل الدرع أو شروط الزعيم؟",
    "لا. اجمع الرون المطابق واهزم المساعدين المطلوبين والتزم بجهة الاقتراب وترتيب الأختام. يجب هزيمة الزعيم ذي الطورين في صورته النهائية أيضًا.",
    "هل يجب هزيمة كل الحراس؟",
    "تمنع التاج الأهداف الإلزامية والزعماء الأحياء فقط؛ بعض الحراس الجانبيين اختياريون. افحص الأهداف والمسار قبل تجاوزهم. الفوز يفتح المرحلة التالية، والإعادة تحسن الشارات."
  ]
};
for(const [locale,parts] of Object.entries(DETAILS))parts.push(...extendedGuide[locale]);
