// Hand-authored topology, encounters and rule combinations, not random seeds.
const H=(x=1,power=10)=>({x,y:0,power});
const E=(id,x,y,power,extra={})=>({id,x,y,power,...extra});
const I=(id,kind,x,y,link)=>({id,kind,x,y,link});
const C=(x=5,y=10)=>I('crown','crown',x,y);
const B=(rows)=>rows.split('/');
function L(id,name,decision,rows,enemies,items=[C()],extra={}) {return {id,name,decision,board:B(rows),hero:H(),enemies,items,...extra};}
const ORIGINAL_LEVELS=[
L(1,'First foothold','Remove the support to meet a weaker guard.','......./.AA..../......./#######',[E('guard',4,2,6)],[C(5,2)]),
L(2,'Weak before strong','Absorb the upper guard before descending again.','......./.AA..../......./BBBBBBB/......./#######',[E('first',4,2,6),E('last',2,4,12)],[C(5,4)]),
L(3,'A whole group','The linked middle floor must survive until the first fight.','......./.AA..../......./BBBAAAA/......./#######',[E('first',3,2,7),E('last',1,4,15)],[C(5,4)]),

];

// v3: supplies are physical pieces. Dropping them early/late changes the
// encounter budget; no random loot or permanent grind can bypass a puzzle.
const P=(id,kind,x,y,amount)=>({...I(id,kind,x,y),amount});
export const LEVELS=[...ORIGINAL_LEVELS.slice(0,3),
L(4,'Arm before battle','Release the sword balcony before opening the guard floor.','......./AAA.CCC/......./BBBBBBB/......./#######',[E('last',4,4,20)],[P('blade','sword',5,0,14),C(6,4)]),
L(5,'Gate captain','Cut both banners; sword lets you duel, fruit lets you survive.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./#######',[E('flag1',2,2,6,{buff:{targets:['boss'],amount:30}}),E('flag2',4,4,14,{buff:{targets:['boss'],amount:30}}),E('boss',2,6,38,{boss:true})],[P('blade','sword',5,0,16),P('fruit','heart',5,2,60),C(6,6)]),
L(6,'Life fruit','Power alone cannot survive the deep duel; rescue the fruit first.','......./AAA.CCC/......./BBBBBBB/......./#######',[E('last',4,4,70)],[P('fruit','heart',5,0,80),C(6,4)],{hero:{...H(1,80),hp:20,maxHp:20}}),
L(7,'Multiply later','Fruit before elixir grants 200 life; reversing them grants only 140.','......./AAA.CCC/......./BBBBBBB/......./AAAAAAA/......./#######',[E('boss',4,6,260,{boss:true})],[P('fruit','heart',5,0,60),P('brew','elixir',2,4),C(6,6)],{hero:H(1,280)}),
L(8,'Armor workshop','Equip armor before the chain of duels to save life each time.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./AAAAAAA/......./#######',[E('one',4,4,26),E('two',2,6,50),E('last',4,8,90)],[P('mail','armor',5,0,18),C(6,8)],{hero:H(1,30)}),
L(9,'One charged strike','Keep the fury crystal for the stronger guard; it lasts one duel.','......./.AA..../......./BBB.CCC/......./AAAAAAA/......./#######',[E('weak',2,2,6),E('last',4,6,29)],[P('charge','fury',5,2),P('fruit','heart',2,4,60),C(6,6)]),
L(10,'Twin banners','Both deputies first; release supplies before committing to the chief.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./AAAAAAA/......./#######',[E('west',2,2,6),E('east',4,4,20),E('boss',2,8,58,{boss:true,requires:['west','east']})],[P('blade','sword',5,0,24),P('fruit','heart',5,2,60),P('mail','armor',2,6,10),C(6,8)],{required:['west','east']}),
L(11,'Key with a cost','Opening the gate drops a guard; collect a sword while the gate still supports you.','......./AAA.CCC/......./1111111/......./BBBBBBB/......./#######',[E('last',4,4,24)],[P('blade','sword',5,0,18),I('key','key',6,2,'1'),C(6,6)]),
L(12,'The suspended flask','The key releases the elixir; grow life before triggering the cascade.','......./AAA.CCC/......./BBBBBBB/......./1111111/......./#######',[E('boss',4,6,250,{boss:true})],[P('fruit','heart',5,0,60),I('key','key',2,4,'1'),P('brew','elixir',2,4),C(6,6)],{hero:H(1,270)}),
L(13,'Gear over the pit','Keep the safe center landing; armor cannot save a fall onto spikes.','......./AAA.CCC/......./BBBBBBB/......./^CCCC^^/......./#######',[E('first',3,2,8),E('last',2,4,22)],[P('blade','sword',4,0,12),P('fruit','heart',1,2,60),C(5,6)]),
L(14,'Two vaults','One key opens the armory, the next commits you to the final fight.','......./.AA..../......./1111111/......./BBBBBBB/......./2222222/......./#######',[E('first',4,4,6),E('last',4,8,38)],[I('key1','key',1,2,'1'),P('blade','sword',5,4,26),P('fruit','heart',2,6,60),I('key2','key',3,6,'2'),C(6,8)]),
L(15,'Lockcrown lion','Use two vaults to assemble blade and life before the locked guardian.','......./AAA.CCC/......./BBBBBBB/......./1111111/......./2222222/......./#######',[E('guard',3,2,8),E('boss',4,8,62,{boss:true})],[P('blade','sword',5,0,50),P('fruit','heart',2,4,60),I('key1','key',3,4,'1'),P('brew','elixir',3,6),I('key2','key',4,6,'2'),C(6,8)]),
L(16,'Rune before steel','The blade raises power but cannot break a rune shield.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./#######',[E('shield',4,6,25,{shield:'sun'})],[P('blade','sword',5,0,20),I('rune','rune',2,4,'sun'),C(6,6)]),
L(17,'Shielded crossroads','Release the rune on the far ledge before dropping into the shield guard.','......./AAA.CCC/......./BBB.CCC/......./AAAAAAA/......./#######',[E('first',2,2,7),E('shield',5,6,30,{shield:'sun'})],[P('blade','sword',5,0,18),I('rune','rune',4,4,'sun'),P('fruit','heart',1,4,60),C(6,6)]),
L(18,'Move the sentry','Drop the stronger sentry, defeat the weak one, then join the lower route.','......./AAA.CCC/......./BBB.CCC/......./AAAAAAA/......./#######',[E('weak',2,2,6),E('high',5,2,24),E('last',2,6,45)],[P('blade','sword',1,0,12),P('fruit','heart',5,4,60),C(6,6)]),
L(19,'Shield and supply','Collect the rune and life before using the key to collapse the last bridge.','......./AAA.CCC/......./BBBBBBB/......./1111111/......./#######',[E('shield',3,4,18,{shield:'sun'}),E('last',4,6,35)],[P('blade','sword',5,0,14),I('rune','rune',2,2,'sun'),P('fruit','heart',1,2,60),I('key','key',4,4,'1'),C(6,6)]),
L(20,'Mirror marshal','Assemble armor and charge, then keep the left approach to the marshal.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./AAAAAAA/......./#######',[E('first',3,2,7),E('second',1,4,12),E('boss',5,8,54,{boss:true,direction:'left'})],[P('mail','armor',5,0,12),P('charge','fury',1,6),C(6,8)]),
L(21,'Banner fortress','Power is inflated while the banner lives; preserve the fruit balcony.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./AAAAAAA/......./#######',[E('flag',3,2,6,{buff:{targets:['shield'],amount:90}}),E('shield',4,8,28,{shield:'sun'})],[P('blade','sword',5,0,16),P('fruit','heart',5,2,60),I('rune','rune',2,4,'sun'),P('brew','elixir',3,6),C(6,8)]),
L(22,'The long gauntlet','Every duel grows power and drains life; equip before the first trade.','......./AAA.CCC/......./BBBAAAA/......./CCCCCCC/......./AAAAAAA/......./#######',[E('one',2,2,8),E('two',1,4,24),E('three',4,6,45),E('last',2,8,90)],[P('blade','sword',5,0,16),P('fruit','heart',6,2,60),P('mail','armor',1,6,12),C(6,8)]),
L(23,'Treasure on the edge','Collect the safe crown without sacrificing the healing ledge to spikes.','......./AAA.CCC/......./BBBBBBB/......./CCC.CCC/......./####^^^',[E('first',2,2,7),E('second',1,4,24)],[P('blade','sword',2,0,14),P('fruit','heart',2,2,60),C(0,4)]),
L(24,'Chain reaction','A key merges two foes; take armor and life before opening it.','......./AAA.CCC/......./BBBBBBB/......./1111111/......./1111111/......./#######',[E('first',3,2,6),E('weak',2,6,24),E('last',5,8,45)],[P('blade','sword',5,0,16),P('mail','armor',5,2,10),P('fruit','heart',2,4,60),I('key','key',3,4,'1'),C(6,8)]),
L(25,'Two-phase castellan','The first form retreats; save fury and multiply life before following.','......./AAA.CCC/......./BBBBBBB/......./1111111/......./CCCCCCC/......./#######',[E('first',3,2,8),E('boss',4,4,22,{boss:true,open:'1',next:{x:5,y:8,power:120}}),E('supply',2,6,35)],[P('blade','sword',5,0,16),P('fruit','heart',5,2,60),P('brew','elixir',3,6),P('charge','fury',5,6),C(6,8)]),
L(26,'Choose your loadout','Two armory balconies: safer armor or extra life, then charge the last duel.','......./AAA.CCC/......./BBB.CCC/......./AAAAAAA/......./BBBBBBB/......./#######',[E('left',2,2,6),E('right',5,2,7),E('last',3,8,30)],[P('mail','armor',5,0,12),P('fruit','heart',1,4,60),P('charge','fury',3,6),C(6,8)]),
L(27,'Linked gates','Rune and elixir descend with the gate; collect fruit before the key.','......./AAA.CCC/......./BBBBBBB/......./1111111/......./1111111/......./#######',[E('first',3,2,6),E('shield',5,8,28,{shield:'sun'})],[P('blade','sword',5,0,16),P('fruit','heart',1,4,60),I('key','key',3,4,'1'),I('rune','rune',3,6,'sun'),P('brew','elixir',3,6),C(6,8)]),
L(28,'Break the supply line','Banner, rune and key first; a fury crystal is wasted on the shield escort.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./1111111/......./#######',[E('flag',3,2,6,{buff:{targets:['shield'],amount:70}}),E('shield',3,6,28,{shield:'sun'}),E('last',4,8,80)],[P('blade','sword',5,0,16),P('fruit','heart',5,2,60),I('rune','rune',2,4,'sun'),P('charge','fury',4,6),I('key','key',5,6,'1'),C(6,8)]),
L(29,'The last safe landing','Keep the narrow bridge; combine armor, rune and charge without dropping onto spikes.','......./AAA.CCC/......./BBB.CCC/......./AAAAAAA/......./1111111/......./^CCC^^^/......./#######',[E('flag',2,2,6,{buff:{targets:['shield'],amount:60}}),E('shield',3,6,24,{shield:'sun'}),E('last',2,8,70)],[P('blade','sword',5,0,12),P('mail','armor',2,4,18),I('rune','rune',2,4,'sun'),P('charge','fury',3,6),I('key','key',3,6,'1'),C(6,10)]),
L(30,'Guardian of the crown','Fruit then elixir, rune then shield, all seals then fury: assemble the complete final route.','......./AAA.CCC/......./BBBBBBB/......./CCCCCCC/......./AAAAAAA/......./BBBBBBB/......./#######',[E('flag',3,2,6,{buff:{targets:['boss'],amount:200}}),E('shield',4,6,28,{shield:'sun'}),E('boss',4,10,90,{boss:true,ordered:true})],[P('blade','sword',5,0,16),P('fruit','heart',1,2,60),I('s1','seal',4,2,'1'),I('rune','rune',3,4,'sun'),I('s2','seal',4,4,'2'),P('brew','elixir',5,4),I('s3','seal',4,8,'3'),P('charge','fury',5,8),C(6,10)],{sealOrder:['1','2','3']})
];

// Mark mandatory duels explicitly; unmarked side guards remain optional routes.
for(const [id,required] of [[13,['first','last']],[18,['weak','high','last']],[22,['one','two','three','last']],[23,['first','second']],[24,['first','weak','last']],[28,['flag','shield','last']],[29,['flag','shield','last']]])LEVELS[id-1].required=required;
