export const NAMES={
en:'First foothold|Weak before strong|A whole group|Keep a foothold|Gate captain|A fork below|Stone detour|Sharp shortcut|Nearest first|Twin banners|The first key|A door is a floor|Fight then unlock|Two keys|Lockcrown lion|The shield rune|Power is not enough|Falling sentry|Rune and key|Mirror marshal|Banner above|Leave a stepping stone|Crown over danger|A single cascade|Two-phase castellan|Two valid routes|Linked gates|Break the line|The final foothold|Guardian of the crown',
'zh-Hant':'第一塊踏板|先弱後強|一整片的代價|留住落腳處|門庭隊長|左右分岔|石台繞行|危險捷徑|同層先後|雙旗統領|第一把鑰匙|門也是地板|先戰後開|雙鑰分流|鎖冠獅王|符文破盾|強者也要繞路|落下的守衛|盾與鑰匙|鏡盾守將|旗手在上方|留敵養力|皇冠旁的陷阱|一步連鎖|雙階城主|雙路皆通|開門連鎖|破盾行軍|最後的踏板|王冠守護者',
'zh-Hans':'第一块踏板|先弱后强|一整片的代价|留住落脚处|门庭队长|左右分岔|石台绕行|危险捷径|同层先后|双旗统领|第一把钥匙|门也是地板|先战后开|双钥分流|锁冠狮王|符文破盾|强者也要绕路|落下的守卫|盾与钥匙|镜盾守将|旗手在上方|留敌养力|皇冠旁的陷阱|一步连锁|双阶城主|双路皆通|开门连锁|破盾行军|最后的踏板|王冠守护者',
ja:'最初の足場|弱い相手から|ひとつながりの代償|足場を残そう|門の隊長|左右の分岐|石の回り道|危険な近道|近い相手から|二旗の統領|最初の鍵|扉も床になる|戦ってから開ける|二つの鍵|封冠の獅子|盾を解くルーン|強さだけでは足りない|落ちる衛兵|盾と鍵|鏡盾の将|上の旗手|敵を残して強くなる|王冠の罠|一手の連鎖|二段階の城主|二つの正解|連動する扉|盾を突破|最後の足場|王冠の守護者',
ko:'첫 발판|약한 적부터|한 그룹의 대가|발판 지키기|성문 대장|좌우 갈림길|돌 우회로|위험한 지름길|가까운 적부터|쌍기 지휘관|첫 열쇠|문도 바닥이다|전투 후 개방|두 열쇠|봉인 사자왕|방패 룬|힘만으로는 부족해|떨어지는 경비병|룬과 열쇠|거울 방패 장군|위쪽 기수|적을 남겨 성장|왕관의 함정|한 수의 연쇄|두 단계 성주|두 정답 길|연결된 문|방패 돌파|마지막 발판|왕관 수호자',
es:'Primer apoyo|Débil antes que fuerte|El grupo completo|Conserva un apoyo|Capitán del portal|La bifurcación|Desvío de piedra|Atajo peligroso|El más cercano|Dos estandartes|La primera llave|La puerta es suelo|Lucha y abre|Dos llaves|León de la corona|Runa del escudo|No basta la fuerza|Centinela que cae|Runa y llave|Mariscal del espejo|Bandera arriba|Reserva un rival|Trampa de la corona|Una cascada|Señor de dos fases|Dos rutas válidas|Puertas unidas|Rompe la línea|Último apoyo|Guardián de la corona',
'pt-BR':'Primeiro apoio|Fraco antes do forte|O grupo inteiro|Guarde um apoio|Capitão do portão|A bifurcação|Desvio de pedra|Atalho perigoso|O mais próximo|Duas bandeiras|Primeira chave|A porta é o chão|Lute e abra|Duas chaves|Leão da coroa|Runa do escudo|Força não basta|Sentinela em queda|Runa e chave|Marechal do espelho|Bandeira acima|Guarde um rival|Armadilha da coroa|Uma cascata|Senhor de duas fases|Duas rotas válidas|Portões ligados|Rompa a linha|Último apoio|Guardião da coroa',
fr:'Premier appui|Le faible avant le fort|Tout un groupe|Gardez un appui|Capitaine du portail|La bifurcation|Détour de pierre|Raccourci dangereux|Le plus proche|Deux bannières|La première clé|La porte est un sol|Combattre puis ouvrir|Deux clés|Lion de la couronne|Rune du bouclier|La force ne suffit pas|Sentinelle en chute|Rune et clé|Maréchal du miroir|Bannière en hauteur|Gardez un adversaire|Piège de la couronne|Une cascade|Seigneur en deux phases|Deux chemins possibles|Portes liées|Brisez la ligne|Dernier appui|Gardien de la couronne',
de:'Erster Halt|Schwach vor stark|Eine ganze Gruppe|Bewahre den Halt|Torhauptmann|Die Weggabelung|Steinumweg|Gefährliche Abkürzung|Der Nächste zuerst|Zwei Banner|Der erste Schlüssel|Die Tür als Boden|Kämpfen dann öffnen|Zwei Schlüssel|Kronenlöwe|Schildrune|Stärke reicht nicht|Fallende Wache|Rune und Schlüssel|Spiegelmarschall|Banner oben|Gegner aufheben|Kronenfalle|Eine Kaskade|Zweiphasiger Burgherr|Zwei gültige Wege|Verbundene Tore|Durchbruch|Letzter Halt|Hüter der Krone',
it:'Primo appoggio|Debole prima del forte|Un intero gruppo|Conserva un appoggio|Capitano del portone|La biforcazione|Deviazione di pietra|Scorciatoia pericolosa|Il più vicino|Due stendardi|La prima chiave|La porta è pavimento|Combatti poi apri|Due chiavi|Leone della corona|Runa dello scudo|La forza non basta|Sentinella in caduta|Runa e chiave|Maresciallo dello specchio|Stendardo in alto|Conserva un rivale|Trappola della corona|Una cascata|Signore a due fasi|Due percorsi validi|Porte collegate|Sfonda la linea|Ultimo appoggio|Guardiano della corona',
ru:'Первая опора|Сначала слабый|Целая группа|Сохранить опору|Капитан ворот|Развилка|Каменный обход|Опасный срез|Ближайший первым|Два знамени|Первый ключ|Дверь как пол|Сначала бой|Два ключа|Коронованный лев|Руна щита|Силы мало|Падающий страж|Руна и ключ|Зеркальный маршал|Знамя наверху|Оставить врага|Ловушка короны|Один каскад|Двухфазный хозяин|Два верных пути|Связанные ворота|Прорыв|Последняя опора|Хранитель короны',
hi:'पहला सहारा|पहले कमज़ोर|पूरा समूह|सहारा बचाएँ|द्वार कप्तान|दो रास्ते|पत्थर का चक्कर|खतरनाक छोटा रास्ता|पहले निकट वाला|दो ध्वज|पहली चाबी|दरवाज़ा भी फर्श|लड़ें फिर खोलें|दो चाबियाँ|ताज का शेर|ढाल का रून|शक्ति काफी नहीं|गिरता पहरेदार|रून और चाबी|दर्पण सेनापति|ऊपर का ध्वज|विरोधी बचाएँ|ताज का जाल|एक श्रृंखला|दो चरणों का स्वामी|दो सही रास्ते|जुड़े द्वार|पंक्ति तोड़ें|अंतिम सहारा|ताज का रक्षक',
ar:'الموطئ الأول|الأضعف أولًا|مجموعة كاملة|احتفظ بموطئ|قائد البوابة|مفترق الطريق|التفاف حجري|اختصار خطير|الأقرب أولًا|رايتان|المفتاح الأول|الباب أرضية أيضًا|قاتل ثم افتح|مفتاحان|أسد التاج|رون الدرع|القوة لا تكفي|الحارس الساقط|رون ومفتاح|قائد المرآة|راية في الأعلى|احتفظ بخصم|فخ التاج|سلسلة واحدة|سيد بمرحلتين|طريقان صحيحان|بوابات مترابطة|اكسر الصف|الموطئ الأخير|حارس التاج'
};
for(const k of Object.keys(NAMES))NAMES[k]=NAMES[k].split('|');
export const DETAILS={
en:['Connected blocks disappear together; remaining blocks stay fixed. Actors fall, then approach the nearest enemy on a continuous platform (ties go left). Win only with greater power; absorb the displayed enemy power. Equal power loses.','Keys open matching gates, runes remove shields, and living banner guards strengthen their linked enemy. Read the visible bonus and boss conditions. Collect the crown after required guards and seals. Spikes destroy necessary targets.','Thirty authored puzzles teach routes, stone and spikes, keys, shields, banners and six different bosses. Clear a stage to unlock the next. Earn separate badges for a clear, no hints and the target move count. Free undo restores the entire last action.','Progress, badges, best moves and a stable unfinished run stay in this browser. No login, waiting energy or cross-stage power grinding. Restart does not erase unlocked stages.'],
'zh-Hant':['相連同色方塊整群消失，其餘方塊不會掉落或補入。角色落地後自動接近同平台最近的敵人，等距先左。戰力必須大於敵人才能獲勝，勝利吸收敵人顯示的戰力；相等也會失敗。','鑰匙開啟對應門，符文解除護盾，存活旗手替指定敵人加成。注意敵人標示的加成及首領條件。完成必要守衛與封印後取得皇冠；尖刺會摧毀必要目標。','30 道原創謎題逐步介紹路線、石台與尖刺、鑰匙、護盾、旗手及六種首領。過關解鎖下一關。通關、不用提示及目標步數內完成各有徽章，免費撤銷會完整回復上一步。','解鎖、徽章、最佳步數及未完成關卡的穩定局面儲存在此瀏覽器。不需登入、等待體力或跨關練等。重新挑戰不會清除已解鎖關卡。'],
'zh-Hans':['相连同色方块整群消失，其余方块不会掉落或补入。角色落地后自动接近同平台最近的敌人，等距先左。战力必须大于敌人才能获胜，胜利吸收敌人显示的战力；相等也会失败。','钥匙开启对应门，符文解除护盾，存活旗手为指定敌人加成。注意敌人标示的加成及首领条件。完成必要守卫与封印后取得皇冠；尖刺会摧毁必要目标。','30 道原创谜题逐步介绍路线、石台与尖刺、钥匙、护盾、旗手及六种首领。过关解锁下一关。通关、不用提示及目标步数内完成各有徽章，免费撤销会完整恢复上一步。','解锁、徽章、最佳步数及未完成关卡的稳定局面保存在此浏览器。不需登录、等待体力或跨关练级。重新挑战不会清除已解锁关卡。'],
ja:['同色のつながったブロックをまとめて消します。残りは固定されます。着地後は同じ足場の最も近い敵へ進み、同距離なら左が先です。戦力が敵より大きい時だけ勝ち、その表示戦力を吸収します。同値は敗北です。','鍵で対応する扉を開き、ルーンで盾を解除します。生きている旗手は対応する敵を強化します。ボスの条件と加算表示を確認し、必要な敵と封印を終えて王冠を取りましょう。トゲは目標を壊します。','30の盤面で道、石、トゲ、鍵、盾、旗手と6種のボスを学びます。クリアで次を解放。クリア、ヒントなし、目標手数のバッジを別々に獲得できます。無料で一手全体を戻せます。','解放状況、バッジ、最少手数と途中の盤面をこのブラウザーに保存します。ログインや待ち時間、戦力稼ぎはありません。やり直しても解放は残ります。'],
ko:['연결된 같은 색 블록을 함께 지웁니다. 나머지는 고정됩니다. 착지 후 같은 발판의 가장 가까운 적에게 이동하며 거리가 같으면 왼쪽부터입니다. 전투력이 더 클 때만 승리하고 표시된 적의 전투력을 흡수합니다. 같으면 패배합니다.','열쇠는 맞는 문을 열고 룬은 방패를 해제합니다. 살아 있는 기수는 연결된 적을 강화합니다. 보스 조건과 추가 전투력을 확인하고 필수 적과 봉인을 완료한 뒤 왕관을 얻으세요. 가시는 목표를 파괴합니다.','30개 퍼즐에서 길, 돌, 가시, 열쇠, 방패, 기수와 여섯 보스를 배웁니다. 완료하면 다음 스테이지가 열립니다. 완료, 힌트 없음, 목표 이동 배지를 따로 모으세요. 무료 되돌리기는 한 수 전체를 복구합니다.','해금, 배지, 최고 기록과 진행 중인 상태는 이 브라우저에 저장됩니다. 로그인, 에너지 대기, 전투력 반복 훈련이 없습니다. 다시 시작해도 해금은 유지됩니다.'],
es:['Los bloques conectados del mismo color desaparecen juntos; los demás quedan fijos. Al caer, avanzas hacia el enemigo más cercano en la misma plataforma; en empate, a la izquierda. Solo ganas con más poder y absorbes el valor mostrado. El empate pierde.','Las llaves abren puertas, las runas quitan escudos y los abanderados vivos refuerzan a su objetivo. Lee las bonificaciones y condiciones del jefe. Completa los requisitos antes de la corona. Los pinchos destruyen objetivos.','30 tableros enseñan rutas, piedra, pinchos, llaves, escudos, banderas y seis jefes. Cada victoria desbloquea otro nivel. Hay insignias por victoria, sin pistas y objetivo de movimientos. Deshacer restaura toda la última acción gratis.','El navegador guarda progreso, insignias, récords y una partida estable. Sin cuenta, energía ni poder permanente. Reintentar conserva los niveles desbloqueados.'],
'pt-BR':['Blocos conectados da mesma cor desaparecem juntos; os demais ficam fixos. Após cair, você vai ao inimigo mais próximo na mesma plataforma; empate escolhe a esquerda. Só vence com poder maior e absorve o valor exibido. Poder igual perde.','Chaves abrem portas, runas removem escudos e porta-bandeiras vivos fortalecem seu alvo. Leia os bônus e condições do chefe. Cumpra os requisitos antes da coroa. Espinhos destroem objetivos.','30 tabuleiros ensinam rotas, pedra, espinhos, chaves, escudos, bandeiras e seis chefes. Cada vitória libera outra fase. Ganhe medalhas por vitória, sem dicas e meta de jogadas. Desfazer restaura toda a última ação gratuitamente.','Este navegador salva progresso, medalhas, recordes e uma partida estável. Sem conta, energia ou poder permanente. Reiniciar mantém as fases liberadas.'],
fr:['Les blocs reliés de même couleur disparaissent ensemble ; les autres restent fixes. Après la chute, vous rejoignez l’ennemi le plus proche sur la même plateforme, à gauche en cas d’égalité. Une puissance supérieure gagne et absorbe la valeur affichée. L’égalité perd.','Les clés ouvrent les portes, les runes retirent les boucliers et les porte-drapeaux vivants renforcent leur cible. Lisez bonus et conditions du boss. Remplissez les conditions avant la couronne. Les piques détruisent les objectifs.','30 plateaux enseignent chemins, pierre, piques, clés, boucliers, bannières et six boss. Chaque victoire débloque la suite. Badges de victoire, sans indice et objectif de coups. Annuler restaure gratuitement toute l’action précédente.','Le navigateur sauvegarde progression, badges, records et partie stable. Sans compte, énergie ni puissance permanente. Recommencer conserve les niveaux débloqués.'],
de:['Verbundene gleichfarbige Blöcke verschwinden zusammen; andere bleiben fest. Nach dem Fallen gehst du zum nächsten Gegner derselben Plattform, bei Gleichstand nach links. Nur höhere Stärke gewinnt und absorbiert den angezeigten Wert. Gleichstand verliert.','Schlüssel öffnen Tore, Runen entfernen Schilde und lebende Bannerträger stärken ihr Ziel. Beachte Boni und Bossbedingungen. Erfülle die Vorgaben vor der Krone. Stacheln zerstören Ziele.','30 Bretter lehren Wege, Stein, Stacheln, Schlüssel, Schilde, Banner und sechs Bosse. Siege öffnen das nächste Level. Abzeichen für Sieg, ohne Tipps und Zugziel. Rückgängig stellt die ganze letzte Aktion kostenlos wieder her.','Der Browser speichert Fortschritt, Abzeichen, Rekorde und einen stabilen Spielstand. Kein Konto, Energie oder permanente Stärke. Neustart erhält freigeschaltete Level.'],
it:['I blocchi collegati dello stesso colore scompaiono insieme; gli altri restano fermi. Dopo la caduta vai al nemico più vicino sulla stessa piattaforma, a sinistra in caso di parità. Vinci solo con potenza maggiore e assorbi il valore mostrato. La parità perde.','Le chiavi aprono porte, le rune rimuovono scudi e gli alfieri vivi potenziano il loro bersaglio. Leggi bonus e condizioni del boss. Completa i requisiti prima della corona. Le punte distruggono gli obiettivi.','30 tavole insegnano percorsi, pietre, punte, chiavi, scudi, stendardi e sei boss. Le vittorie sbloccano il seguito. Medaglie per vittoria, nessun indizio e obiettivo mosse. Annullare ripristina gratis tutta l’ultima azione.','Il browser salva progressi, medaglie, record e partita stabile. Niente account, energia o potenza permanente. Ricominciare conserva i livelli sbloccati.'],
ru:['Связанные блоки одного цвета исчезают вместе, остальные неподвижны. После падения герой идёт к ближайшему врагу на той же платформе; при равенстве — влево. Побеждает только большая сила и поглощает показанное значение. Равенство — поражение.','Ключи открывают двери, руны снимают щиты, живые знаменосцы усиливают свою цель. Читайте бонусы и условия босса. Выполните требования до короны. Шипы уничтожают цели.','30 полей знакомят с путями, камнем, шипами, ключами, щитами, знамёнами и шестью боссами. Победа открывает следующий уровень. Значки за победу, без подсказок и цель ходов. Бесплатная отмена возвращает всю последнюю операцию.','Браузер сохраняет прогресс, значки, рекорды и устойчивую позицию. Без аккаунта, энергии и постоянной силы. Перезапуск сохраняет открытые уровни.'],
hi:['जुड़े एक रंग के ब्लॉक साथ हटते हैं; बाकी स्थिर रहते हैं। गिरने के बाद उसी मंच के निकटतम दुश्मन के पास जाते हैं; बराबर दूरी पर बायाँ पहले। केवल अधिक शक्ति जीतती है और दिखी दुश्मन शक्ति मिलती है। बराबरी पर हारते हैं।','चाबियाँ द्वार खोलती हैं, रून ढाल हटाते हैं और जीवित ध्वजवाहक अपने लक्ष्य को मजबूत करते हैं। बोनस और मुखिया की शर्तें पढ़ें। ताज से पहले ज़रूरी लक्ष्य पूरे करें। काँटे लक्ष्य नष्ट करते हैं।','30 पहेलियाँ रास्ते, पत्थर, काँटे, चाबियाँ, ढाल, ध्वज और छह मुखिया सिखाती हैं। जीत अगला स्तर खोलती है। जीत, बिना संकेत और लक्ष्य चालों के अलग पदक हैं। मुफ्त वापसी पूरी पिछली चाल लौटाती है।','ब्राउज़र प्रगति, पदक, श्रेष्ठ चालें और स्थिर अधूरा खेल सहेजता है। खाता, ऊर्जा या स्थायी शक्ति नहीं। फिर शुरू करने पर खुले स्तर बने रहते हैं।'],
ar:['تختفي المكعبات المتصلة من اللون نفسه معًا وتبقى البقية ثابتة. بعد السقوط تتجه إلى أقرب عدو على المنصة نفسها، وإلى اليسار عند التعادل. تفوز فقط بقوة أكبر وتمتص القوة المعروضة للعدو. تعادل القوة يعني الخسارة.','تفتح المفاتيح الأبواب وتزيل الرونات الدروع وتقوي الرايات الحية العدو المرتبط بها. اقرأ الإضافات وشروط الزعيم. أكمل المتطلبات قبل التاج. الأشواك تدمر الأهداف.','30 لوحة تعلّم الطرق والحجر والأشواك والمفاتيح والدروع والرايات وستة زعماء. الفوز يفتح المرحلة التالية. شارات للفوز وبلا تلميحات وهدف الحركات. التراجع المجاني يعيد الحركة السابقة كاملة.','يحفظ المتصفح التقدم والشارات والأرقام وأحدث وضعية مستقرة. بلا حساب أو طاقة أو قوة دائمة. إعادة المحاولة تحتفظ بالمراحل المفتوحة.']
};

import {REVISED_STAGE_IDS,REVISED_NAMES} from './upgrade-copy.mjs';
for(const [locale,names] of Object.entries(REVISED_NAMES))names.split('|').forEach((name,i)=>NAMES[locale][REVISED_STAGE_IDS[i]-1]=name);
