/* Internal prototype only. Foam characters and props are temporary until the art gate. */
(() => {
  const $ = (id) => document.getElementById(id);
  const loadingPanel = $("loadingPanel");
  if (loadingPanel) { const hideLoading = () => { loadingPanel.hidden = true; loadingPanel.classList.add("hidden"); }; if (document.readyState === "complete") hideLoading(); else window.addEventListener("load", hideLoading, { once: true }); }
  const canvas = $("arena");
  const ctx = canvas.getContext("2d");
  const heroArt = new Image(); heroArt.src = "assets/animal-bounce-brawl-original-assets-v1.png";
  const rivalArt = heroArt;
  const impactArt = heroArt;
  const propArt = new Image(); propArt.src = "assets/animal-bounce-brawl-props.png";
  const tools = [{ name: "BUMP", damage: 14, force: 8, cooldown: 18, crop: [0,0,650,360] }, { name: "SPRING", damage: 10, force: 12, cooldown: 24, crop: [30,360,620,360] }, { name: "PAD", damage: 20, force: 5, cooldown: 30, crop: [1470,0,700,370] }];
  const COPY = {
    en: { hint: "Hold ◀/▶ to move closer, then BOUNCE.", tooFar: "Too far — move closer before the next bump.", selected: "Selected tool:", BUMP: "BUMP", SPRING: "SPRING", PAD: "PAD", BOUNCE: "BOUNCE" },
    "zh-Hant": { hint: "按住 ◀/▶ 靠近對手，再按 BOUNCE。", tooFar: "距離太遠——請先靠近，再進行下一次撞擊。", selected: "目前工具：", BUMP: "撞擊", SPRING: "彈簧", PAD: "泡棉墊", BOUNCE: "彈跳" },
    "zh-Hans": { hint: "按住 ◀/▶ 靠近对手，再按 BOUNCE。", tooFar: "距离太远——请先靠近，再进行下一次撞击。", selected: "当前工具：", BUMP: "撞击", SPRING: "弹簧", PAD: "泡棉垫", BOUNCE: "弹跳" },
    ja: { hint: "◀/▶を長押しして近づき、BOUNCEを押します。", tooFar: "遠すぎます。次のバンプの前に近づいてください。", selected: "選択中のツール：", BUMP: "バンプ", SPRING: "スプリング", PAD: "パッド", BOUNCE: "バウンス" },
    ko: { hint: "◀/▶를 길게 눌러 가까이 간 뒤 BOUNCE를 누르세요.", tooFar: "너무 멉니다. 다음 범프 전에 가까이 가세요.", selected: "선택한 도구:", BUMP: "범프", SPRING: "스프링", PAD: "패드", BOUNCE: "바운스" },
    es: { hint: "Mantén ◀/▶ para acercarte y pulsa BOUNCE.", tooFar: "Demasiado lejos: acércate antes del próximo empujón.", selected: "Herramienta seleccionada:", BUMP: "EMPUJÓN", SPRING: "MUELLE", PAD: "ALMOHADILLA", BOUNCE: "REBOTE" },
    "pt-BR": { hint: "Segure ◀/▶ para se aproximar e toque em BOUNCE.", tooFar: "Muito longe: aproxime-se antes do próximo impacto.", selected: "Ferramenta selecionada:", BUMP: "IMPACTO", SPRING: "MOLA", PAD: "ALMOFADA", BOUNCE: "SALTO" },
    fr: { hint: "Maintenez ◀/▶ pour vous rapprocher, puis appuyez sur BOUNCE.", tooFar: "Trop loin : rapprochez-vous avant la prochaine bousculade.", selected: "Outil sélectionné :", BUMP: "BOUSCULADE", SPRING: "RESSORT", PAD: "COUSSIN", BOUNCE: "REBOND" },
    de: { hint: "Halte ◀/▶, um näher zu kommen, und drücke dann BOUNCE.", tooFar: "Zu weit weg – komme vor dem nächsten Stoß näher.", selected: "Ausgewähltes Werkzeug:", BUMP: "STOSS", SPRING: "FEDER", PAD: "POLSTER", BOUNCE: "SPRUNG" },
    it: { hint: "Tieni premuto ◀/▶ per avvicinarti, poi premi BOUNCE.", tooFar: "Troppo lontano: avvicinati prima del prossimo urto.", selected: "Strumento selezionato:", BUMP: "URTO", SPRING: "MOLLA", PAD: "CUSCINO", BOUNCE: "RIMBALZO" },
    ru: { hint: "Удерживайте ◀/▶, чтобы приблизиться, затем нажмите BOUNCE.", tooFar: "Слишком далеко — приблизьтесь перед следующим ударом.", selected: "Выбранный инструмент:", BUMP: "УДАР", SPRING: "ПРУЖИНА", PAD: "ПОДУШКА", BOUNCE: "ПРЫЖОК" },
    hi: { hint: "पास आने के लिए ◀/▶ दबाए रखें, फिर BOUNCE दबाएँ।", tooFar: "बहुत दूर हैं—अगली टक्कर से पहले पास आएँ।", selected: "चुना गया उपकरण:", BUMP: "टक्कर", SPRING: "स्प्रिंग", PAD: "पैड", BOUNCE: "उछाल" },
    ar: { hint: "اضغط مطولًا على ◀/▶ للاقتراب، ثم اضغط BOUNCE.", tooFar: "المسافة بعيدة — اقترب قبل الدفع التالي.", selected: "الأداة المحددة:", BUMP: "دفع", SPRING: "نابض", PAD: "وسادة", BOUNCE: "ارتداد" }
  };
  const STAGE_COPY = {
    en: { title: "Foam Arenas", status: "Choose one of six foam arenas.", tab: "Stages", nav: "Stage sections", stageBack: "Back to Main", battleBack: "Back to Arenas", cards: [["Arena 1", "warm-up"], ["Arena 2", "spring lanes"], ["Arena 3", "moving pads"], ["Arena 4", "tight corners"], ["Arena 5", "fast rival"], ["Arena 6", "final rhythm"]] },
    "zh-Hant": { title: "泡棉競技場", status: "選擇六座泡棉競技場之一。", tab: "關卡", nav: "關卡區段", stageBack: "返回主選單", battleBack: "返回競技場", cards: [["競技場 1", "熱身"], ["競技場 2", "彈簧通道"], ["競技場 3", "移動泡棉墊"], ["競技場 4", "狹窄轉角"], ["競技場 5", "高速對手"], ["競技場 6", "最終節奏"]] },
    "zh-Hans": { title: "泡棉竞技场", status: "选择六座泡棉竞技场之一。", tab: "关卡", nav: "关卡区段", stageBack: "返回主菜单", battleBack: "返回竞技场", cards: [["竞技场 1", "热身"], ["竞技场 2", "弹簧通道"], ["竞技场 3", "移动泡棉垫"], ["竞技场 4", "狭窄转角"], ["竞技场 5", "高速对手"], ["竞技场 6", "最终节奏"]] },
    ja: { title: "フォームアリーナ", status: "6つのフォームアリーナから1つ選びます。", tab: "ステージ", nav: "ステージセクション", stageBack: "メインへ戻る", battleBack: "アリーナへ戻る", cards: [["アリーナ 1", "ウォームアップ"], ["アリーナ 2", "スプリングレーン"], ["アリーナ 3", "動くパッド"], ["アリーナ 4", "狭いコーナー"], ["アリーナ 5", "素早いライバル"], ["アリーナ 6", "最終リズム"]] },
    ko: { title: "폼 아레나", status: "6개의 폼 아레나 중 하나를 선택하세요.", tab: "스테이지", nav: "스테이지 섹션", stageBack: "메인으로 돌아가기", battleBack: "아레나로 돌아가기", cards: [["아레나 1", "워밍업"], ["아레나 2", "스프링 레인"], ["아레나 3", "움직이는 패드"], ["아레나 4", "좁은 코너"], ["아레나 5", "빠른 라이벌"], ["아레나 6", "최종 리듬"]] },
    es: { title: "Arenas de espuma", status: "Elige una de las seis arenas de espuma.", tab: "Arenas", nav: "Secciones de arena", stageBack: "Volver al inicio", battleBack: "Volver a las arenas", cards: [["Arena 1", "calentamiento"], ["Arena 2", "carriles con muelles"], ["Arena 3", "plataformas móviles"], ["Arena 4", "esquinas estrechas"], ["Arena 5", "rival veloz"], ["Arena 6", "ritmo final"]] },
    "pt-BR": { title: "Arenas de espuma", status: "Escolha uma das seis arenas de espuma.", tab: "Arenas", nav: "Seções de arena", stageBack: "Voltar ao início", battleBack: "Voltar às arenas", cards: [["Arena 1", "aquecimento"], ["Arena 2", "pistas de molas"], ["Arena 3", "almofadas móveis"], ["Arena 4", "cantos apertados"], ["Arena 5", "rival veloz"], ["Arena 6", "ritmo final"]] },
    fr: { title: "Arènes en mousse", status: "Choisissez l’une des six arènes en mousse.", tab: "Arènes", nav: "Sections d’arène", stageBack: "Retour à l’accueil", battleBack: "Retour aux arènes", cards: [["Arène 1", "échauffement"], ["Arène 2", "couloirs à ressorts"], ["Arène 3", "plateformes mobiles"], ["Arène 4", "virages serrés"], ["Arène 5", "rival rapide"], ["Arène 6", "rythme final"]] },
    de: { title: "Schaumstoff-Arenen", status: "Wähle eine von sechs Schaumstoff-Arenen.", tab: "Arenen", nav: "Arenenbereiche", stageBack: "Zurück zum Hauptmenü", battleBack: "Zurück zu den Arenen", cards: [["Arena 1", "Aufwärmen"], ["Arena 2", "Federbahnen"], ["Arena 3", "bewegliche Polster"], ["Arena 4", "enge Ecken"], ["Arena 5", "schneller Rivale"], ["Arena 6", "finaler Rhythmus"]] },
    it: { title: "Arene di gommapiuma", status: "Scegli una delle sei arene di gommapiuma.", tab: "Arene", nav: "Sezioni arena", stageBack: "Torna al menu", battleBack: "Torna alle arene", cards: [["Arena 1", "riscaldamento"], ["Arena 2", "corsie a molla"], ["Arena 3", "pedane mobili"], ["Arena 4", "angoli stretti"], ["Arena 5", "rivale veloce"], ["Arena 6", "ritmo finale"]] },
    ru: { title: "Поролоновые арены", status: "Выберите одну из шести поролоновых арен.", tab: "Арены", nav: "Разделы арен", stageBack: "Вернуться в меню", battleBack: "Вернуться к аренам", cards: [["Арена 1", "разминка"], ["Арена 2", "пружинные дорожки"], ["Арена 3", "подвижные платформы"], ["Арена 4", "тесные углы"], ["Арена 5", "быстрый соперник"], ["Арена 6", "финальный ритм"]] },
    hi: { title: "फोम अखाड़े", status: "छह फोम अखाड़ों में से एक चुनें।", tab: "अखाड़े", nav: "अखाड़ा अनुभाग", stageBack: "मुख्य मेन्यू पर लौटें", battleBack: "अखाड़ों पर लौटें", cards: [["अखाड़ा 1", "वार्म-अप"], ["अखाड़ा 2", "स्प्रिंग गलियारे"], ["अखाड़ा 3", "चलते पैड"], ["अखाड़ा 4", "तंग कोने"], ["अखाड़ा 5", "तेज़ प्रतिद्वंद्वी"], ["अखाड़ा 6", "अंतिम लय"]] },
    ar: { title: "ساحات الرغوة", status: "اختر ساحة رغوة واحدة من أصل ست ساحات.", tab: "الساحات", nav: "أقسام الساحات", stageBack: "العودة إلى القائمة الرئيسية", battleBack: "العودة إلى الساحات", cards: [["الساحة 1", "إحماء"], ["الساحة 2", "ممرات نابضة"], ["الساحة 3", "وسائد متحركة"], ["الساحة 4", "زوايا ضيقة"], ["الساحة 5", "منافس سريع"], ["الساحة 6", "الإيقاع النهائي"]] }
  };
  const locale = document.documentElement.lang || "en";
  const copy = COPY[locale] || COPY.en;
  const stageCopy = STAGE_COPY[locale] || STAGE_COPY.en;
  const state = { screen: "main", arena: 1, best: Number(localStorage.getItem("wp-brawl-best") || 0), keys: new Set(), player: null, rival: null, tool: 0, raf: 0, last: 0, attack: 0, flash: 0, elapsed: 0 };
  const text = (value) => window.wpFiveText ? window.wpFiveText(value) : value;
  function ensureBattleStatusControls() { const status = $("battle-status"); if (!status) return; let message = $("battle-status-copy"); let selected = $("selected-tool-label"); if (!message || !selected) { const initial = status.textContent.trim(); status.replaceChildren(); message = document.createElement("span"); message.id = "battle-status-copy"; message.textContent = initial; selected = document.createElement("span"); selected.id = "selected-tool-label"; selected.className = "selected-tool-label"; status.append(message, selected); } }
  function setStatus(value) { ensureBattleStatusControls(); const message = $("battle-status-copy"); if (message) message.textContent = value; }
  function localizeBattleControls() { ensureBattleStatusControls(); const selected = $("selected-tool-label"); if (selected) selected.textContent = `${copy.selected} ${copy[tools[state.tool].name]}`; const bounce = document.querySelector('[data-key="Space"]'); if (bounce) bounce.textContent = copy.BOUNCE; document.querySelectorAll("[data-tool]").forEach((button) => { button.textContent = copy[tools[Number(button.dataset.tool)].name]; }); }
  function show(name) { state.screen = name; document.body.dataset.screen = name === "result" ? "battle" : name; cancelAnimationFrame(state.raf); const result = document.querySelector("#result-screen"); document.querySelectorAll(".screen").forEach((el) => { const isResult = el === result && name === "result"; const keepBattle = name === "result" && el.id === "battle-screen"; const on = isResult || keepBattle || el.dataset.screen === name; el.hidden = !on; el.classList.toggle("active", on); }); if (name === "battle") result?.setAttribute("hidden", ""); if (name === "battle") { state.last = performance.now(); state.raf = requestAnimationFrame(frame); } }
  function localizeStageSurface() { $("stage-title").textContent = stageCopy.title; $("stage-status").textContent = stageCopy.status; $("stage-tab").textContent = stageCopy.tab; document.querySelector(".stage-tabs")?.setAttribute("aria-label", stageCopy.nav); $("stage-back").setAttribute("aria-label", stageCopy.stageBack); $("battle-back").setAttribute("aria-label", stageCopy.battleBack); }
  function stageCards() { localizeStageSurface(); $("stage-list").innerHTML = stageCopy.cards.map((card, index) => `<button data-arena="${index + 1}" aria-label="${card[0]}: ${card[1]}">${card[0]}<br><small>${card[1]}</small></button>`).join(""); $("stage-list").querySelectorAll("button").forEach((b) => b.addEventListener("click", () => startArena(Number(b.dataset.arena)))); }
  function startArena(arena = 1) { state.arena = arena; state.player = { x: 230, y: 390, vx: 0, vy: 0, hp: 100 }; state.rival = { x: 720, y: 390, vx: 0, vy: 0, hp: 90 + arena * 10 }; state.tool = 0; state.attack = 0; state.flash = 0; state.elapsed = 0; $("arena-label").textContent = `Arena ${arena} / 6`; $("health-label").textContent = "You 100 · Rival " + state.rival.hp; localizeBattleControls(); setStatus(copy.hint); show("battle"); }
  function selectTool(index) { state.tool = Math.max(0, Math.min(tools.length - 1, Number(index))); document.querySelectorAll("[data-tool]").forEach((b) => b.classList.toggle("selected", Number(b.dataset.tool) === state.tool)); localizeBattleControls(); setStatus(copy.hint); }
  function strike() { if (state.attack > 0 || state.screen !== "battle") return; const p = state.player, r = state.rival, kit = tools[state.tool]; state.attack = kit.cooldown; const d = Math.hypot(p.x-r.x,p.y-r.y); if (d < 170) { r.hp -= kit.damage; r.vx += p.x < r.x ? kit.force : -kit.force; r.vy = -4.8; state.flash = 8; setStatus(`${copy[kit.name]} impact! Keep the rival off balance.`); } else { setStatus(copy.tooFar); } }
  function update(dt) { const p=state.player,r=state.rival; const left=state.keys.has("ArrowLeft")||state.keys.has("KeyA"); const right=state.keys.has("ArrowRight")||state.keys.has("KeyD"); if(left)p.vx-=.42*dt;if(right)p.vx+=.42*dt;p.vx*=.92;p.x+=p.vx*dt;p.vy+=.42*dt;p.y+=p.vy*dt;if(p.y>390){p.y=390;p.vy=-Math.abs(p.vy)*.52;p.vy=Math.max(p.vy,-6)} if(Math.abs(p.vy)<.8&&p.y===390)p.vy=-4.2;
    const approach = p.x > r.x ? -1 : 1; r.vx += approach * (.08 + state.arena * .012) * dt; r.vx *= .96; r.x += r.vx * dt; r.vy += .42 * dt; r.y += r.vy * dt; if(r.y>390){r.y=390;r.vy=-Math.abs(r.vy)*.48;r.vy=Math.max(r.vy,-5)}
    if(Math.abs(p.x-r.x)<118){r.vx+=(r.x>p.x?.14:-.14)*dt;p.hp-= (.018 + state.arena*.004)*dt;} p.x=Math.max(70,Math.min(890,p.x));r.x=Math.max(70,Math.min(890,r.x)); state.attack=Math.max(0,state.attack-dt);state.flash=Math.max(0,state.flash-dt);state.elapsed += dt/60; $("health-label").textContent=`You ${Math.max(0,Math.ceil(p.hp))} · Rival ${Math.max(0,Math.ceil(r.hp))}`;if(r.hp<=0)finish(true);else if(p.hp<=0 || state.elapsed>35)finish(false); }
  function finish(win) { state.best = win ? Math.max(state.best,state.arena) : state.best; if(win)localStorage.setItem("wp-brawl-best",String(state.best)); $("result-title").textContent=win?"Arena clear":"Bounced out"; $("result-copy").textContent=win?`Arena ${state.arena} won with ${Math.max(0,Math.ceil(state.player.hp))} energy remaining.`:`Arena ${state.arena} lost. Read the rival's approach and try again.`; $("next").textContent=state.arena>=6?"Replay Arena":"Next Arena"; show("result"); }
  function draw() { ctx.clearRect(0,0,960,540);const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,"#3d2b59");g.addColorStop(1,"#171122");ctx.fillStyle=g;ctx.fillRect(0,0,960,540);ctx.fillStyle="#e77e9a";ctx.fillRect(0,435,960,105);ctx.fillStyle="#6e4b92";ctx.fillRect(0,430,960,8);ctx.fillStyle="#ffd36b";ctx.font="bold 18px system-ui";ctx.fillText(text("FOAM ZONE"),24,34);ctx.fillStyle="#cbb7d9";ctx.font="15px system-ui";ctx.fillText(text("A toy physics test arena"),24,58);const pads=[[190,330,150,16],[610,330,160,16],[400,250,150,16]];pads.forEach(([x,y,w,h])=>{ctx.fillStyle="#9e77bd";ctx.fillRect(x,y,w,h)});if(state.player&&state.rival){actor(state.player,heroArt,"#9ee9e0","#2a1b3b",[10,5,620,620]);actor(state.rival,rivalArt,"#ffb36b","#3c2131",[650,55,580,530]);if(propArt.complete&&propArt.naturalWidth){const kit=tools[state.tool];ctx.drawImage(propArt,kit.crop[0],kit.crop[1],kit.crop[2],kit.crop[3],state.player.x+20,state.player.y-88,54,42);}if(state.attack>0){ctx.strokeStyle="#ffd36b";ctx.lineWidth=12;ctx.beginPath();ctx.arc(state.player.x+(state.player.x<state.rival.x?38:-38),state.player.y-8,34,-.8,.8);ctx.stroke()}if(state.flash>0){if(propArt.complete&&propArt.naturalWidth){ctx.drawImage(propArt,1470,350,700,374,(state.player.x+state.rival.x)/2-48,(state.player.y+state.rival.y)/2-48,96,96);}else{ctx.fillStyle="#fff2a1";ctx.beginPath();ctx.arc((state.player.x+state.rival.x)/2,(state.player.y+state.rival.y)/2,18+state.flash,0,Math.PI*2);ctx.fill();}}} }
  function actor(o,art,body,ink,crop){ctx.save();ctx.translate(o.x,o.y-38);ctx.rotate(o.vx*.03);if(art.complete&&art.naturalWidth){ctx.drawImage(art,crop[0],crop[1],crop[2],crop[3],-48,-48,96,96);}else{ctx.fillStyle=body;ctx.beginPath();ctx.arc(0,-28,23,0,Math.PI*2);ctx.fill();ctx.fillRect(-18,-8,36,38);ctx.fillStyle=ink;ctx.fillRect(-11,-34,7,7);ctx.fillRect(4,-34,7,7);ctx.fillRect(-27,24,18,8);ctx.fillRect(9,24,18,8);}ctx.restore();}
  function frame(now){if(state.screen!=="battle")return;const dt=Math.min((now-state.last)/16.67,2);state.last=now;update(dt);if(state.screen==="battle"){draw();state.raf=requestAnimationFrame(frame)}}
  window.addEventListener("keydown",(e)=>{const k=e.code==="Space"?"Space":e.code;const digit=k[0]==="D"&&k.length===6;if(["ArrowLeft","ArrowRight","KeyA","KeyD","Space"].includes(k)||digit){e.preventDefault();if(k==="Space")strike();else if(digit)selectTool(Number(k.slice(-1))-1);else state.keys.add(k)}}); window.addEventListener("keyup",(e)=>state.keys.delete(e.code==="Space"?"Space":e.code));
  function bindHeldControl(button,k){
    const release=(e)=>{if(e?.pointerId!=null&&button.hasPointerCapture?.(e.pointerId))button.releasePointerCapture(e.pointerId);state.keys.delete(k)};
    button.addEventListener("pointerdown",(e)=>{e.preventDefault();if(e.pointerId!=null)button.setPointerCapture?.(e.pointerId);if(k==="Space")strike();else state.keys.add(k)});
    ["pointerup","pointercancel","lostpointercapture"].forEach((ev)=>button.addEventListener(ev,release));
    ["pointerup","pointercancel"].forEach((ev)=>window.addEventListener(ev,release,true));
    window.addEventListener("blur",release);
  }
  document.querySelectorAll("[data-key]").forEach((b)=>bindHeldControl(b,b.dataset.key)); document.querySelectorAll("[data-tool]").forEach((b)=>b.addEventListener("click",()=>selectTool(b.dataset.tool)));
  $("start-game").addEventListener("click",()=>{show("stage");stageCards()});document.querySelectorAll("[data-back]").forEach((b)=>b.addEventListener("click",()=>show(b.dataset.back)));$("retry").addEventListener("click",()=>startArena(state.arena));$("next").addEventListener("click",()=>startArena(state.arena>=6?1:state.arena+1));$("to-stages").addEventListener("click",()=>{show("stage");stageCards()});$("main-progress").textContent=`Best wins: ${state.best}`;localizeBattleControls();stageCards();draw();
})();
