/* Game-owned guided practice for the Bounce Brawl foam arena. */
(() => {
  const COPY = {
    en: { practice: "Guided Practice", move: "Move right to the foam wall.", wall: "At the wall, press BOUNCE with BUMP.", springNeed: "Switch to SPRING, then cross the marked pad.", springReady: "SPRING set—cross the marked pad.", targetNeed: "Move near the target, land, then switch to PAD.", targetReady: "PAD ready—move within range, then BOUNCE.", done: "Lovely rebound! Practice complete—head back to the arenas.", wallLabel: "FOAM WALL", padLabel: "SPRING PAD", target: "Practice target" },
    "zh-Hant": { practice: "操作教學", move: "往右移動到泡棉牆。", wall: "到牆邊後，使用撞擊工具按「彈跳」。", springNeed: "切換成彈簧工具，再走過標記彈跳墊。", springReady: "已選彈簧—走過標記彈跳墊。", targetNeed: "移到目標附近並落地，再切換成泡棉墊。", targetReady: "已選泡棉墊—靠近目標後按「彈跳」。", done: "漂亮的反彈！教學完成，返回競技場選單吧。", wallLabel: "泡棉牆", padLabel: "彈跳墊", target: "練習目標" },
    "zh-Hans": { practice: "操作教学", move: "向右移动到泡棉墙。", wall: "到墙边后，使用撞击工具按“弹跳”。", springNeed: "切换成弹簧工具，再走过标记弹跳垫。", springReady: "已选弹簧—走过标记弹跳垫。", targetNeed: "移到目标附近并落地，再切换成泡棉垫。", targetReady: "已选泡棉垫—靠近目标后按“弹跳”。", done: "漂亮的反弹！教学完成，返回竞技场菜单吧。", wallLabel: "泡棉墙", padLabel: "弹跳垫", target: "练习目标" },
    ja: { practice: "操作チュートリアル", move: "右へ進んでフォームの壁へ。", wall: "壁の前でBUMPを選び、バウンスを押します。", springNeed: "SPRINGに切り替え、光るパッドを通過します。", springReady: "SPRING選択中—光るパッドを通過します。", targetNeed: "ターゲット近くに着地してからPADに切り替えます。", targetReady: "PAD選択中—近づいてバウンスします。", done: "ナイスリバウンド！練習完了。アリーナへ戻りましょう。", wallLabel: "フォームの壁", padLabel: "スプリングパッド", target: "練習ターゲット" },
    ko: { practice: "조작 연습", move: "오른쪽으로 이동해 폼 벽에 가세요.", wall: "벽 앞에서 BUMP를 고르고 BOUNCE를 누르세요.", springNeed: "SPRING으로 바꾸고 표시된 패드를 지나가세요.", springReady: "SPRING 선택됨—표시된 패드를 지나가세요.", targetNeed: "표적 근처에 착지한 뒤 PAD로 바꾸세요.", targetReady: "PAD 선택됨—가까이 가서 BOUNCE를 누르세요.", done: "멋진 반동이에요! 연습 완료—아레나로 돌아가세요.", wallLabel: "폼 벽", padLabel: "스프링 패드", target: "연습 표적" },
    es: { practice: "Práctica guiada", move: "Avanza a la derecha hasta el muro de espuma.", wall: "Ante el muro, elige EMPUJÓN y pulsa REBOTE.", springNeed: "Elige MUELLE y cruza la plataforma marcada.", springReady: "MUELLE listo: cruza la plataforma marcada.", targetNeed: "Aterriza cerca del objetivo y cambia a ALMOHADILLA.", targetReady: "ALMOHADILLA lista: acércate y pulsa REBOTE.", done: "¡Buen rebote! Práctica completada; vuelve a las arenas.", wallLabel: "MURO DE ESPUMA", padLabel: "PLATAFORMA ELÁSTICA", target: "Objetivo de práctica" },
    "pt-BR": { practice: "Treino guiado", move: "Vá para a direita até a parede de espuma.", wall: "Na parede, escolha IMPACTO e toque em SALTO.", springNeed: "Escolha MOLA e atravesse a plataforma marcada.", springReady: "MOLA selecionada—atravesse a plataforma marcada.", targetNeed: "Pouse perto do alvo e troque para ALMOFADA.", targetReady: "ALMOFADA selecionada—aproxime-se e toque em SALTO.", done: "Belo rebote! Treino concluído—volte às arenas.", wallLabel: "PAREDE DE ESPUMA", padLabel: "PLATAFORMA ELÁSTICA", target: "Alvo de treino" },
    fr: { practice: "Entraînement guidé", move: "Avancez à droite jusqu’au mur en mousse.", wall: "Devant le mur, choisissez BOUSCULADE et appuyez sur REBOND.", springNeed: "Choisissez RESSORT et traversez le coussin marqué.", springReady: "RESSORT choisi—traversez le coussin marqué.", targetNeed: "Atterrissez près de la cible, puis choisissez COUSSIN.", targetReady: "COUSSIN choisi—approchez et appuyez sur REBOND.", done: "Beau rebond ! Entraînement terminé—retour aux arènes.", wallLabel: "MUR EN MOUSSE", padLabel: "COUSSIN À RESSORT", target: "Cible d’entraînement" },
    de: { practice: "Geführtes Training", move: "Gehe nach rechts bis zur Schaumstoffwand.", wall: "Wähle vor der Wand STOSS und drücke SPRUNG.", springNeed: "Wähle FEDER und überquere das markierte Polster.", springReady: "FEDER gewählt—überquere das markierte Polster.", targetNeed: "Lande nahe am Ziel und wechsle zu POLSTER.", targetReady: "POLSTER gewählt—nähere dich und drücke SPRUNG.", done: "Schöner Rückprall! Training geschafft—zurück zu den Arenen.", wallLabel: "SCHAUMSTOFFWAND", padLabel: "FEDERPOLSTER", target: "Trainingsziel" },
    it: { practice: "Allenamento guidato", move: "Vai a destra fino al muro di gommapiuma.", wall: "Davanti al muro scegli URTO e premi RIMBALZO.", springNeed: "Scegli MOLLA e attraversa il cuscino segnato.", springReady: "MOLLA selezionata—attraversa il cuscino segnato.", targetNeed: "Atterra vicino al bersaglio e passa a CUSCINO.", targetReady: "CUSCINO selezionato—avvicinati e premi RIMBALZO.", done: "Bel rimbalzo! Allenamento completato—torna alle arene.", wallLabel: "MURO DI GOMMAPIUMA", padLabel: "CUSCINO A MOLLA", target: "Bersaglio di allenamento" },
    ru: { practice: "Обучение управлению", move: "Двигайтесь вправо к поролоновой стене.", wall: "У стены выберите УДАР и нажмите ОТСКОК.", springNeed: "Выберите ПРУЖИНУ и пройдите по отмеченной подушке.", springReady: "ПРУЖИНА выбрана—пройдите по отмеченной подушке.", targetNeed: "Приземлитесь рядом с целью и выберите ПОДУШКУ.", targetReady: "ПОДУШКА выбрана—подойдите и нажмите ОТСКОК.", done: "Отличный отскок! Обучение пройдено—вернитесь на арену.", wallLabel: "ПОРОЛОНОВАЯ СТЕНА", padLabel: "ПРУЖИННАЯ ПОДУШКА", target: "Учебная цель" },
    hi: { practice: "निर्देशित अभ्यास", move: "दाईं ओर जाकर फोम की दीवार तक पहुँचें।", wall: "दीवार के पास टक्कर चुनें और उछाल दबाएँ।", springNeed: "स्प्रिंग चुनें, फिर निशान वाले पैड से गुजरें।", springReady: "स्प्रिंग चुना—निशान वाले पैड से गुजरें।", targetNeed: "लक्ष्य के पास उतरें, फिर पैड चुनें।", targetReady: "पैड चुना—पास जाकर उछाल दबाएँ।", done: "शानदार उछाल! अभ्यास पूरा—अखाड़ों पर लौटें।", wallLabel: "फोम की दीवार", padLabel: "स्प्रिंग पैड", target: "अभ्यास लक्ष्य" },
    ar: { practice: "تدريب إرشادي", move: "تحرك يميناً حتى جدار الرغوة.", wall: "عند الجدار اختر دفع واضغط ارتداد.", springNeed: "اختر نابضاً ثم اعبر الوسادة المحددة.", springReady: "تم اختيار النابض—اعبر الوسادة المحددة.", targetNeed: "اهبط قرب الهدف ثم اختر وسادة.", targetReady: "تم اختيار الوسادة—اقترب واضغط ارتداد.", done: "ارتداد رائع! اكتمل التدريب—عُد إلى الساحات.", wallLabel: "جدار الرغوة", padLabel: "وسادة نابضة", target: "هدف التدريب" }
  };
  const locale = document.documentElement.lang || "en";
  const copy = COPY[locale] || COPY.en;
  const panel = () => document.getElementById("tutorialPanel");
  window.BounceBrawlTutorial = {
    copy,
    render(step, tool) {
      const node = panel();
      if (!node) return;
      const key = step === 0 ? "move" : step === 1 ? "wall" : step === 2 ? (tool === 1 ? "springReady" : "springNeed") : step === 3 ? (tool === 2 ? "targetReady" : "targetNeed") : "done";
      node.textContent = copy[key];
      node.hidden = false;
    },
    clear() { const node = panel(); if (node) { node.textContent = ""; node.hidden = true; } }
  };
})();
