const keys=['title','start','resume','back','undo','restart','hint','turn','thinking','check','win','lose','draw','promote','queen','rook','bishop','knight','retry','unavailable','saved','guide','intro','help','confirm','cancel'];
const rows={
 en:['Chess','New match','Continue','Back','Undo turn','Restart','Hint','Your turn · White','Black is thinking…','Check — protect your king','You win by checkmate','Black wins by checkmate','Draw','Choose a promotion','Queen','Rook','Bishop','Knight','Try again','3D or computer unavailable. Retry or return.','Progress saved on this device','How to play','Play a complete match against the computer.','Select a white piece, then a marked square. Protect your king; checkmate wins. Pawns may promote to one of four pieces. Undo takes back your last turn.','Start a new match?','Cancel'],
 'zh-Hant':['西洋棋','新對局','繼續對局','返回','復原一回合','重新開始','提示','輪到你 · 白方','黑方思考中…','被將軍了，請保護國王','你將死對手，獲勝！','黑方將死，對局落敗','和局','選擇升變棋子','后','城堡','主教','騎士','重試','3D 或電腦暫時無法使用，請重試或返回。','進度儲存在此裝置','玩法指南','與電腦進行完整西洋棋對局。','先選白棋，再選標示格。保護國王，將死對手即獲勝。兵到底線可選四種升變棋子；復原會退回上一回合。','開始新對局？','取消'],
 'zh-Hans':['国际象棋','新对局','继续对局','返回','撤销一回合','重新开始','提示','轮到你 · 白方','黑方思考中…','被将军了，请保护国王','你将死对手，获胜！','黑方将死，对局落败','和棋','选择升变棋子','后','车','象','马','重试','3D 或电脑暂时无法使用，请重试或返回。','进度保存在此设备','玩法指南','与电脑进行完整国际象棋对局。','先选白棋，再选标示格。保护国王，将死对手即获胜。兵到底线可选四种升变棋子；撤销会退回上一回合。','开始新对局？','取消'],
 ja:['チェス','新しい対局','続ける','戻る','一手戻す','最初から','ヒント','あなたの番 · 白','黒が思考中…','チェック — キングを守って','チェックメイトで勝利','黒のチェックメイトで敗北','引き分け','昇格する駒を選択','クイーン','ルーク','ビショップ','ナイト','再試行','3D またはコンピューターを利用できません。再試行するか戻ってください。','進行はこの端末に保存','遊び方','コンピューターと最後まで対局します。','白い駒を選び、印のあるマスへ動かします。キングを守り、チェックメイトを目指しましょう。ポーンは４種類に昇格できます。戻すと前の手番に戻ります。','新しい対局を始めますか？','キャンセル'],
 ko:['체스','새 대국','계속하기','돌아가기','한 턴 되돌리기','다시 시작','힌트','내 차례 · 백','흑이 생각 중…','체크 — 킹을 보호하세요','체크메이트로 승리','흑의 체크메이트로 패배','무승부','승격할 기물 선택','퀸','룩','비숍','나이트','다시 시도','3D 또는 컴퓨터를 사용할 수 없습니다. 다시 시도하거나 돌아가세요.','진행 상황은 이 기기에 저장','게임 방법','컴퓨터와 끝까지 체스를 두세요.','백 기물을 고른 뒤 표시된 칸을 선택하세요. 킹을 보호하고 체크메이트하세요. 폰은 네 기물 중 하나로 승격합니다. 되돌리기는 이전 턴으로 돌아갑니다.','새 대국을 시작할까요?','취소'],
 es:['Ajedrez','Nueva partida','Continuar','Volver','Deshacer turno','Reiniciar','Pista','Tu turno · Blancas','Las negras están pensando…','Jaque — protege al rey','Ganas por jaque mate','Las negras ganan por jaque mate','Tablas','Elige la promoción','Dama','Torre','Alfil','Caballo','Reintentar','3D o rival no disponible. Reintenta o vuelve.','Progreso guardado en este dispositivo','Cómo jugar','Juega una partida completa contra el ordenador.','Elige una pieza blanca y una casilla marcada. Protege al rey y gana con jaque mate. Los peones pueden promocionar a cuatro piezas. Deshacer recupera tu turno anterior.','¿Empezar una nueva partida?','Cancelar'],
 'pt-BR':['Xadrez','Nova partida','Continuar','Voltar','Desfazer turno','Reiniciar','Dica','Sua vez · Brancas','As pretas estão pensando…','Xeque — proteja o rei','Você vence por xeque-mate','As pretas vencem por xeque-mate','Empate','Escolha a promoção','Dama','Torre','Bispo','Cavalo','Tentar novamente','3D ou adversário indisponível. Tente novamente ou volte.','Progresso salvo neste dispositivo','Como jogar','Jogue uma partida completa contra o computador.','Escolha uma peça branca e uma casa marcada. Proteja o rei e vença com xeque-mate. Peões podem promover a quatro peças. Desfazer retorna ao seu turno anterior.','Começar uma nova partida?','Cancelar'],
 fr:['Échecs','Nouvelle partie','Continuer','Retour','Annuler le tour','Recommencer','Indice','À vous · Blancs','Les noirs réfléchissent…','Échec — protégez le roi','Vous gagnez par échec et mat','Les noirs gagnent par échec et mat','Partie nulle','Choisir la promotion','Dame','Tour','Fou','Cavalier','Réessayer','3D ou adversaire indisponible. Réessayez ou revenez.','Progression enregistrée sur cet appareil','Comment jouer','Jouez une partie complète contre l’ordinateur.','Choisissez une pièce blanche, puis une case indiquée. Protégez le roi et gagnez par échec et mat. Un pion peut être promu en quatre pièces. Annuler revient à votre tour précédent.','Commencer une nouvelle partie ?','Annuler'],
 de:['Schach','Neue Partie','Fortsetzen','Zurück','Zug zurück','Neustart','Tipp','Du bist dran · Weiß','Schwarz denkt nach…','Schach — schütze den König','Du gewinnst durch Schachmatt','Schwarz gewinnt durch Schachmatt','Remis','Umwandlung wählen','Dame','Turm','Läufer','Springer','Erneut versuchen','3D oder Gegner nicht verfügbar. Erneut versuchen oder zurückkehren.','Fortschritt auf diesem Gerät gespeichert','Spielanleitung','Spiele eine vollständige Partie gegen den Computer.','Wähle eine weiße Figur und ein markiertes Feld. Schütze den König und setze den Gegner matt. Bauern können in vier Figuren umgewandelt werden. Zurück nimmt deinen letzten Zug zurück.','Neue Partie beginnen?','Abbrechen'],
 it:['Scacchi','Nuova partita','Continua','Indietro','Annulla turno','Ricomincia','Suggerimento','Tocca a te · Bianco','Il nero sta pensando…','Scacco — proteggi il re','Vinci per scacco matto','Il nero vince per scacco matto','Patta','Scegli la promozione','Donna','Torre','Alfiere','Cavallo','Riprova','3D o avversario non disponibile. Riprova o torna indietro.','Progressi salvati su questo dispositivo','Come giocare','Gioca una partita completa contro il computer.','Scegli un pezzo bianco, poi una casa indicata. Proteggi il re e vinci con scacco matto. I pedoni possono promuovere a quattro pezzi. Annulla torna al tuo turno precedente.','Iniziare una nuova partita?','Annulla'],
 ru:['Шахматы','Новая партия','Продолжить','Назад','Отменить ход','Начать заново','Подсказка','Ваш ход · Белые','Чёрные думают…','Шах — защитите короля','Вы победили матом','Чёрные победили матом','Ничья','Выберите превращение','Ферзь','Ладья','Слон','Конь','Повторить','3D или соперник недоступен. Повторите или вернитесь.','Прогресс сохранён на этом устройстве','Как играть','Сыграйте полную партию против компьютера.','Выберите белую фигуру и отмеченную клетку. Защищайте короля и поставьте мат. Пешка превращается в одну из четырёх фигур. Отмена возвращает ваш предыдущий ход.','Начать новую партию?','Отмена'],
 hi:['शतरंज','नई बाज़ी','जारी रखें','वापस','चाल वापस लें','फिर शुरू करें','संकेत','आपकी चाल · सफ़ेद','काला पक्ष सोच रहा है…','शह — राजा को बचाएँ','शह और मात से आपकी जीत','काले पक्ष ने शह और मात दी','ड्रॉ','पदोन्नति चुनें','वज़ीर','हाथी','ऊँट','घोड़ा','फिर कोशिश करें','3D या प्रतिद्वंद्वी उपलब्ध नहीं है। फिर कोशिश करें या वापस जाएँ।','प्रगति इस उपकरण पर सहेजी गई','कैसे खेलें','कंप्यूटर के विरुद्ध पूरी बाज़ी खेलें।','सफ़ेद मोहरा चुनें, फिर चिह्नित खाना चुनें। राजा को बचाएँ और शह-मात दें। प्यादा चार मोहरों में बदल सकता है। वापस लेने से आपकी पिछली चाल लौटती है।','नई बाज़ी शुरू करें?','रद्द करें'],
 ar:['شطرنج','مباراة جديدة','متابعة','رجوع','التراجع عن الدور','إعادة البدء','تلميح','دورك · الأبيض','الأسود يفكر…','كش — احمِ الملك','فزت بكش مات','فاز الأسود بكش مات','تعادل','اختر الترقية','وزير','قلعة','فيل','حصان','إعادة المحاولة','3D أو الخصم غير متاح. أعد المحاولة أو ارجع.','التقدم محفوظ على هذا الجهاز','طريقة اللعب','العب مباراة كاملة ضد الكمبيوتر.','اختر قطعة بيضاء ثم مربعاً محدداً. احمِ الملك وافز بكش مات. يمكن ترقية البيدق إلى أربع قطع. التراجع يعيد دورك السابق.','هل تبدأ مباراة جديدة؟','إلغاء']
};
export const chessLocales=Object.fromEntries(Object.entries(rows).map(([locale,row])=>{if(row.length!==keys.length)throw Error(`Incomplete chess locale ${locale}`);return [locale,Object.fromEntries(keys.map((k,i)=>[k,row[i]]))];}));
