(function(){"use strict";
  const COPY={
    en:{eyebrow:"Forest postcards · 6+",title:"Costume Workshop",lede:"Read each animal's outing brief, choose a matching outfit, and save a cheerful postcard.",fact1:"3 animals",fact2:"Match + make",fact3:"Local postcards",ready:"3 animals ready",start:"Start workshop",guideButton:"How to play",guide:"Read the outing brief, choose one of three outfits, and make a postcard. A wrong match gives a gentle clue; three matches finish the workshop.",soundOn:"Sound: on",soundOff:"Sound: off",back:"Back to Main",choose:"Choose outfit",reset:"Reset",next:"Next animal",retry:"Try again",home:"Workshop home",saved:"Postcard saved",great:"Great match!",wrong:"Try a different outfit",sun:"Sunny",rain:"Rainy",snow:"Snowy",brief1:"Pip needs a sunny picnic outfit.",brief2:"Panko needs a rainy trail outfit.",brief3:"Moss Shell Taro needs a snowy mountain outfit.",done:"Workshop complete!",doneCopy:"Three postcards are ready for the forest album.",animal:"Animal",briefTitle:"Outing brief",postcard:"Postcard",canvasLabel:"Costume postcard preview",settings:"Settings",language:"Language"},
    "zh-Hant":{eyebrow:"森林明信片 · 6+",title:"動物造型工坊",lede:"讀懂動物的出遊需求，選出合適造型，保存開心明信片。",fact1:"3 隻動物",fact2:"配對＋創作",fact3:"本機明信片",ready:"準備好 3 隻動物",start:"開始工坊",guideButton:"玩法說明",guide:"讀出遊需求，選三種造型之一製作明信片。配錯會得到溫和提示；完成三次配對即可完成工坊。",soundOn:"音效：開",soundOff:"音效：關",back:"返回主畫面",choose:"選擇造型",reset:"重設",next:"下一隻動物",retry:"再試一次",home:"返回工坊",saved:"明信片已保存",great:"配對成功！",wrong:"換一種造型試試",sun:"晴日",rain:"雨天",snow:"雪地",brief1:"Pip 需要晴日野餐造型。",brief2:"Panko 需要雨天步道造型。",brief3:"Moss Shell Taro 需要雪山造型。",done:"工坊完成！",doneCopy:"三張明信片已準備好放進森林相簿。",animal:"動物",briefTitle:"出遊需求",postcard:"明信片",canvasLabel:"造型明信片預覽",settings:"設定",language:"語言"},
    "zh-Hans":{eyebrow:"森林明信片 · 6+",title:"动物造型工坊",lede:"读懂动物的出游需求，选出合适造型，保存开心明信片。",fact1:"3 只动物",fact2:"配对＋创作",fact3:"本地明信片",ready:"3 只动物已准备好",start:"开始工坊",guideButton:"玩法说明",guide:"读出游需求，从三种造型中选择一种制作明信片。选错会得到温和提示；完成三次配对即可完成工坊。",soundOn:"音效：开",soundOff:"音效：关",back:"返回主画面",choose:"选择造型",reset:"重置",next:"下一只动物",retry:"再试一次",home:"返回工坊",saved:"明信片已保存",great:"配对成功！",wrong:"换一种造型试试",sun:"晴天",rain:"雨天",snow:"雪地",brief1:"Pip 需要晴天野餐造型。",brief2:"Panko 需要雨天步道造型。",brief3:"Moss Shell Taro 需要雪山造型。",done:"工坊完成！",doneCopy:"三张明信片已准备好放进森林相册。",animal:"动物",briefTitle:"出游需求",postcard:"明信片",canvasLabel:"造型明信片预览",settings:"设置",language:"语言"},
    ja:{eyebrow:"森のポストカード · 6+",title:"どうぶつコスチューム工房",lede:"どうぶつのおでかけメモを読み、ぴったりの衣装を選んでポストカードを作ろう。",fact1:"3匹のどうぶつ",fact2:"マッチして作る",fact3:"ローカルカード",ready:"3匹のどうぶつを準備中",start:"工房を始める",guideButton:"遊び方",guide:"おでかけメモを読み、3つの衣装から選んでカードを作ります。まちがえてもヒントが出ます。3回マッチすれば完成です。",soundOn:"サウンド：オン",soundOff:"サウンド：オフ",back:"メインに戻る",choose:"衣装を選ぶ",reset:"リセット",next:"次のどうぶつ",retry:"もう一度",home:"工房ホーム",saved:"ポストカードを保存しました",great:"マッチ成功！",wrong:"別の衣装を試そう",sun:"晴れ",rain:"雨",snow:"雪",brief1:"Pipには晴れの日のピクニック衣装が必要です。",brief2:"Pankoには雨の日の小道衣装が必要です。",brief3:"Moss Shell Taroには雪山の衣装が必要です。",done:"工房クリア！",doneCopy:"3枚のポストカードを森のアルバムに保存しました。",animal:"どうぶつ",briefTitle:"おでかけメモ",postcard:"ポストカード",canvasLabel:"コスチュームポストカードのプレビュー",settings:"設定",language:"言語"},
    ko:{eyebrow:"숲 엽서 · 6+",title:"동물 의상 공방",lede:"동물의 외출 메모를 읽고 어울리는 의상을 골라 즐거운 엽서를 만드세요.",fact1:"동물 3마리",fact2:"맞추고 만들기",fact3:"로컬 엽서",ready:"동물 3마리 준비 완료",start:"공방 시작",guideButton:"게임 방법",guide:"외출 메모를 읽고 세 의상 중 하나를 골라 엽서를 만드세요. 틀려도 부드러운 힌트가 나옵니다. 세 번 맞추면 완성됩니다.",soundOn:"소리: 켜짐",soundOff:"소리: 꺼짐",back:"메인으로",choose:"의상 선택",reset:"초기화",next:"다음 동물",retry:"다시 시도",home:"공방 홈",saved:"엽서를 저장했어요",great:"멋진 매치!",wrong:"다른 의상을 시도하세요",sun:"맑은 날",rain:"비 오는 날",snow:"눈 오는 날",brief1:"Pip에게는 맑은 날 소풍 의상이 필요해요.",brief2:"Panko에게는 비 오는 날 산책로 의상이 필요해요.",brief3:"Moss Shell Taro에게는 눈 내리는 산 의상이 필요해요.",done:"공방 완료!",doneCopy:"숲 앨범에 넣을 엽서 3장이 준비됐어요.",animal:"동물",briefTitle:"외출 메모",postcard:"엽서",canvasLabel:"동물 의상 엽서 미리보기",settings:"설정",language:"언어"},
    es:{eyebrow:"Postales del bosque · 6+",title:"Taller de disfraces",lede:"Lee la nota de salida de cada animal, elige un disfraz y guarda una postal alegre.",fact1:"3 animales",fact2:"Combina y crea",fact3:"Postales locales",ready:"3 animales listos",start:"Empezar taller",guideButton:"Cómo jugar",guide:"Lee la nota, elige uno de tres disfraces y crea una postal. Un error da una pista amable; tres aciertos completan el taller.",soundOn:"Sonido: activado",soundOff:"Sonido: desactivado",back:"Volver al inicio",choose:"Elegir disfraz",reset:"Reiniciar",next:"Siguiente animal",retry:"Intentar de nuevo",home:"Inicio del taller",saved:"Postal guardada",great:"¡Buena combinación!",wrong:"Prueba otro disfraz",sun:"Soleado",rain:"Lluvioso",snow:"Nevado",brief1:"Pip necesita un disfraz para un picnic soleado.",brief2:"Panko necesita un disfraz para un sendero lluvioso.",brief3:"Moss Shell Taro necesita un disfraz para una montaña nevada.",done:"¡Taller completado!",doneCopy:"Tres postales están listas para el álbum del bosque.",animal:"Animal",briefTitle:"Nota de salida",postcard:"Postal",canvasLabel:"Vista previa de postal con disfraz",settings:"Ajustes",language:"Idioma"},
    "pt-BR":{eyebrow:"Cartões-postais da floresta · 6+",title:"Oficina de Fantasias",lede:"Leia o passeio de cada animal, escolha a fantasia certa e guarde um cartão-postal alegre.",fact1:"3 animais",fact2:"Combine e crie",fact3:"Cartões locais",ready:"3 animais prontos",start:"Começar oficina",guideButton:"Como jogar",guide:"Leia a mensagem, escolha uma de três fantasias e crie um cartão. Um erro traz uma dica tranquila; três acertos concluem a oficina.",soundOn:"Som: ligado",soundOff:"Som: desligado",back:"Voltar ao início",choose:"Escolher fantasia",reset:"Redefinir",next:"Próximo animal",retry:"Tentar de novo",home:"Início da oficina",saved:"Cartão salvo",great:"Boa combinação!",wrong:"Tente outra fantasia",sun:"Ensolarado",rain:"Chuvoso",snow:"Nevado",brief1:"Pip precisa de uma fantasia para um piquenique ensolarado.",brief2:"Panko precisa de uma fantasia para uma trilha chuvosa.",brief3:"Moss Shell Taro precisa de uma fantasia para uma montanha nevada.",done:"Oficina concluída!",doneCopy:"Três cartões estão prontos para o álbum da floresta.",animal:"Animal",briefTitle:"Mensagem do passeio",postcard:"Cartão-postal",canvasLabel:"Prévia do cartão com fantasia",settings:"Configurações",language:"Idioma"},
    fr:{eyebrow:"Cartes de la forêt · 6+",title:"Atelier des costumes",lede:"Lis la sortie de chaque animal, choisis le bon costume et garde une jolie carte.",fact1:"3 animaux",fact2:"Associer et créer",fact3:"Cartes locales",ready:"3 animaux prêts",start:"Commencer l'atelier",guideButton:"Comment jouer",guide:"Lis le message, choisis un costume parmi trois et crée une carte. Une erreur donne un indice doux ; trois réussites terminent l'atelier.",soundOn:"Son : activé",soundOff:"Son : désactivé",back:"Retour à l'accueil",choose:"Choisir le costume",reset:"Réinitialiser",next:"Animal suivant",retry:"Réessayer",home:"Accueil de l'atelier",saved:"Carte enregistrée",great:"Belle association !",wrong:"Essaie un autre costume",sun:"Ensoleillé",rain:"Pluvieux",snow:"Neigeux",brief1:"Pip a besoin d'un costume pour un pique-nique au soleil.",brief2:"Panko a besoin d'un costume pour un sentier sous la pluie.",brief3:"Moss Shell Taro a besoin d'un costume pour une montagne enneigée.",done:"Atelier terminé !",doneCopy:"Trois cartes sont prêtes pour l'album de la forêt.",animal:"Animal",briefTitle:"Message de sortie",postcard:"Carte",canvasLabel:"Aperçu de la carte costumée",settings:"Réglages",language:"Langue"},
    de:{eyebrow:"Waldpostkarten · 6+",title:"Kostümwerkstatt",lede:"Lies den Ausflugshinweis, wähle ein passendes Kostüm und speichere eine fröhliche Postkarte.",fact1:"3 Tiere",fact2:"Zuordnen und gestalten",fact3:"Lokale Postkarten",ready:"3 Tiere bereit",start:"Werkstatt starten",guideButton:"So wird gespielt",guide:"Lies den Hinweis, wähle eines von drei Kostümen und gestalte eine Postkarte. Bei einem Fehler gibt es einen freundlichen Tipp; drei Treffer beenden die Werkstatt.",soundOn:"Ton: an",soundOff:"Ton: aus",back:"Zurück zum Start",choose:"Kostüm wählen",reset:"Zurücksetzen",next:"Nächstes Tier",retry:"Noch einmal",home:"Werkstatt-Start",saved:"Postkarte gespeichert",great:"Gut kombiniert!",wrong:"Versuche ein anderes Kostüm",sun:"Sonnig",rain:"Regnerisch",snow:"Verschneit",brief1:"Pip braucht ein Kostüm für ein sonniges Picknick.",brief2:"Panko braucht ein Kostüm für einen regnerischen Pfad.",brief3:"Moss Shell Taro braucht ein Kostüm für einen verschneiten Berg.",done:"Werkstatt abgeschlossen!",doneCopy:"Drei Postkarten sind für das Waldalbum bereit.",animal:"Tier",briefTitle:"Ausflugshinweis",postcard:"Postkarte",canvasLabel:"Vorschau der Kostüm-Postkarte",settings:"Einstellungen",language:"Sprache"},
    it:{eyebrow:"Cartoline del bosco · 6+",title:"Laboratorio dei costumi",lede:"Leggi il messaggio di ogni animale, scegli il costume giusto e salva una cartolina allegra.",fact1:"3 animali",fact2:"Abbina e crea",fact3:"Cartoline locali",ready:"3 animali pronti",start:"Inizia il laboratorio",guideButton:"Come si gioca",guide:"Leggi il messaggio, scegli uno dei tre costumi e crea una cartolina. Un errore offre un indizio gentile; tre abbinamenti completano il laboratorio.",soundOn:"Audio: acceso",soundOff:"Audio: spento",back:"Torna all'inizio",choose:"Scegli il costume",reset:"Azzera",next:"Animale successivo",retry:"Riprova",home:"Home del laboratorio",saved:"Cartolina salvata",great:"Abbinamento riuscito!",wrong:"Prova un altro costume",sun:"Soleggiato",rain:"Piovoso",snow:"Nevoso",brief1:"Pip ha bisogno di un costume per un picnic soleggiato.",brief2:"Panko ha bisogno di un costume per un sentiero piovoso.",brief3:"Moss Shell Taro ha bisogno di un costume per una montagna innevata.",done:"Laboratorio completato!",doneCopy:"Tre cartoline sono pronte per l'album del bosco.",animal:"Animale",briefTitle:"Messaggio d'uscita",postcard:"Cartolina",canvasLabel:"Anteprima della cartolina in costume",settings:"Impostazioni",language:"Lingua"},
    ru:{eyebrow:"Лесные открытки · 6+",title:"Мастерская костюмов",lede:"Прочитайте заметку о прогулке животного, выберите костюм и сохраните радостную открытку.",fact1:"3 животных",fact2:"Подбери и создай",fact3:"Локальные открытки",ready:"Готовы 3 животных",start:"Начать мастерскую",guideButton:"Как играть",guide:"Прочитайте заметку, выберите один из трёх костюмов и создайте открытку. Ошибка даст спокойную подсказку; три совпадения завершат мастерскую.",soundOn:"Звук: включён",soundOff:"Звук: выключен",back:"На главную",choose:"Выбрать костюм",reset:"Сбросить",next:"Следующее животное",retry:"Попробовать снова",home:"Главная мастерской",saved:"Открытка сохранена",great:"Отличное совпадение!",wrong:"Попробуйте другой костюм",sun:"Солнечно",rain:"Дождливо",snow:"Снег",brief1:"Pip нужен костюм для солнечного пикника.",brief2:"Panko нужен костюм для дождливой тропы.",brief3:"Moss Shell Taro нужен костюм для снежной горы.",done:"Мастерская завершена!",doneCopy:"Три открытки готовы для лесного альбома.",animal:"Животное",briefTitle:"Заметка о прогулке",postcard:"Открытка",canvasLabel:"Предпросмотр открытки с костюмом",settings:"Настройки",language:"Язык"},
    hi:{eyebrow:"जंगल के पोस्टकार्ड · 6+",title:"पोशाक कार्यशाला",lede:"हर जानवर की सैर की बात पढ़ें, सही पोशाक चुनें और खुशहाल पोस्टकार्ड बचाएँ।",fact1:"3 जानवर",fact2:"मिलाएँ और बनाएँ",fact3:"स्थानीय पोस्टकार्ड",ready:"3 जानवर तैयार",start:"कार्यशाला शुरू करें",guideButton:"कैसे खेलें",guide:"सैर की बात पढ़ें, तीन पोशाकों में से एक चुनें और पोस्टकार्ड बनाएँ। गलत चुनाव पर शांत संकेत मिलेगा; तीन सही मेल से कार्यशाला पूरी होगी।",soundOn:"ध्वनि: चालू",soundOff:"ध्वनि: बंद",back:"मुख्य पृष्ठ पर लौटें",choose:"पोशाक चुनें",reset:"रीसेट",next:"अगला जानवर",retry:"फिर कोशिश करें",home:"कार्यशाला होम",saved:"पोस्टकार्ड सहेजा गया",great:"बहुत अच्छा मेल!",wrong:"दूसरी पोशाक आज़माएँ",sun:"धूप",rain:"बारिश",snow:"बर्फ़",brief1:"Pip को धूप वाली पिकनिक की पोशाक चाहिए।",brief2:"Panko को बारिश वाली पगडंडी की पोशाक चाहिए।",brief3:"Moss Shell Taro को बर्फ़ीले पहाड़ की पोशाक चाहिए।",done:"कार्यशाला पूरी!",doneCopy:"जंगल के एल्बम के लिए तीन पोस्टकार्ड तैयार हैं।",animal:"जानवर",briefTitle:"सैर की बात",postcard:"पोस्टकार्ड",canvasLabel:"पोशाक पोस्टकार्ड का पूर्वावलोकन",settings:"सेटिंग्स",language:"भाषा"},
    ar:{eyebrow:"بطاقات بريدية من الغابة · 6+",title:"ورشة أزياء الحيوانات",lede:"اقرأ رسالة نزهة كل حيوان، واختر الزي المناسب، واحفظ بطاقة بريدية مبهجة.",fact1:"3 حيوانات",fact2:"طابق وابتكر",fact3:"بطاقات محلية",ready:"3 حيوانات جاهزة",start:"ابدأ الورشة",guideButton:"طريقة اللعب",guide:"اقرأ الرسالة، واختر زياً من ثلاثة أزياء لصنع بطاقة. يمنحك الاختيار الخاطئ تلميحاً لطيفاً؛ أكمل ثلاث مطابقات لإنهاء الورشة.",soundOn:"الصوت: تشغيل",soundOff:"الصوت: إيقاف",back:"العودة إلى الرئيسية",choose:"اختر الزي",reset:"إعادة ضبط",next:"الحيوان التالي",retry:"حاول مرة أخرى",home:"رئيسية الورشة",saved:"حُفظت البطاقة",great:"مطابقة رائعة!",wrong:"جرّب زياً آخر",sun:"مشمس",rain:"ممطر",snow:"ثلجي",brief1:"يحتاج Pip إلى زي لنزهة مشمسة.",brief2:"يحتاج Panko إلى زي لمسار ممطر.",brief3:"يحتاج Moss Shell Taro إلى زي لجبل ثلجي.",done:"اكتملت الورشة!",doneCopy:"ثلاث بطاقات جاهزة لألبوم الغابة.",animal:"الحيوان",briefTitle:"رسالة النزهة",postcard:"بطاقة بريدية",canvasLabel:"معاينة بطاقة الزي",settings:"الإعدادات",language:"اللغة"}
  };
  const REPLAY_COPY={
    en:{modeLabel:"Album mode",classic:"Classic album",shuffle:"Shuffle album",modeHelp:"Classic keeps the first postcard order. Shuffle rotates the same three briefs for a fresh route.",bestLabel:"Best checks",bestNone:"Not yet",newBest:"New best: {value} checks!"},
    "zh-Hant":{modeLabel:"相簿模式",classic:"經典相簿",shuffle:"輪換相簿",modeHelp:"經典模式保留第一次的明信片順序；輪換模式用同樣三則需求換一條新路線。",bestLabel:"最佳檢查次數",bestNone:"尚無紀錄",newBest:"新最佳：{value} 次檢查！"},
    "zh-Hans":{modeLabel:"相册模式",classic:"经典相册",shuffle:"轮换相册",modeHelp:"经典模式保留第一次的明信片顺序；轮换模式用同样三则需求换一条新路线。",bestLabel:"最佳检查次数",bestNone:"暂无记录",newBest:"新最佳：{value} 次检查！"},
    ja:{modeLabel:"アルバムモード",classic:"クラシックアルバム",shuffle:"シャッフルアルバム",modeHelp:"クラシックは最初のカード順を保ちます。シャッフルは同じ3つのメモを別の順で出します。",bestLabel:"ベスト手数",bestNone:"まだありません",newBest:"新記録：{value}回！"},
    ko:{modeLabel:"앨범 모드",classic:"클래식 앨범",shuffle:"셔플 앨범",modeHelp:"클래식은 첫 엽서 순서를 유지해요. 셔플은 같은 세 메모를 새 순서로 보여줘요.",bestLabel:"최고 시도 횟수",bestNone:"아직 없음",newBest:"새 기록: {value}회!"},
    es:{modeLabel:"Modo de álbum",classic:"Álbum clásico",shuffle:"Álbum mezclado",modeHelp:"El clásico mantiene el primer orden. El mezclado cambia el orden de las mismas tres notas.",bestLabel:"Mejor número de intentos",bestNone:"Todavía no",newBest:"¡Nuevo mejor: {value} intentos!"},
    "pt-BR":{modeLabel:"Modo do álbum",classic:"Álbum clássico",shuffle:"Álbum embaralhado",modeHelp:"O clássico mantém a primeira ordem. O embaralhado muda a ordem das mesmas três mensagens.",bestLabel:"Melhor número de tentativas",bestNone:"Ainda não",newBest:"Novo recorde: {value} tentativas!"},
    fr:{modeLabel:"Mode album",classic:"Album classique",shuffle:"Album mélangé",modeHelp:"Le mode classique garde le premier ordre. Le mode mélangé change l'ordre des trois mêmes messages.",bestLabel:"Meilleur nombre d'essais",bestNone:"Pas encore",newBest:"Nouveau meilleur score : {value} essais !"},
    de:{modeLabel:"Albummodus",classic:"Klassisches Album",shuffle:"Gemischtes Album",modeHelp:"Der klassische Modus behält die erste Reihenfolge. Der gemischte Modus ordnet dieselben drei Hinweise neu.",bestLabel:"Beste Versuche",bestNone:"Noch nicht",newBest:"Neuer Bestwert: {value} Versuche!"},
    it:{modeLabel:"Modalità album",classic:"Album classico",shuffle:"Album mescolato",modeHelp:"Il classico mantiene il primo ordine. Il mescolato cambia l'ordine degli stessi tre messaggi.",bestLabel:"Miglior numero di tentativi",bestNone:"Non ancora",newBest:"Nuovo record: {value} tentativi!"},
    ru:{modeLabel:"Режим альбома",classic:"Классический альбом",shuffle:"Перемешанный альбом",modeHelp:"Классический режим сохраняет первый порядок. Перемешанный меняет порядок тех же трёх заметок.",bestLabel:"Лучшее число попыток",bestNone:"Пока нет",newBest:"Новый лучший результат: {value} попыток!"},
    hi:{modeLabel:"एल्बम मोड",classic:"क्लासिक एल्बम",shuffle:"शफल एल्बम",modeHelp:"क्लासिक पहली पोस्टकार्ड क्रम बनाए रखता है। शफल उन्हीं तीन बातों का नया क्रम देता है।",bestLabel:"सबसे कम कोशिशें",bestNone:"अभी नहीं",newBest:"नया सर्वश्रेष्ठ: {value} कोशिशें!"},
    ar:{modeLabel:"وضع الألبوم",classic:"الألبوم الكلاسيكي",shuffle:"الألبوم المتناوب",modeHelp:"يحافظ الكلاسيكي على ترتيب البطاقة الأول. يغيّر المتناوب ترتيب الرسائل الثلاث نفسها لمسار جديد.",bestLabel:"أفضل عدد للمحاولات",bestNone:"لا يوجد بعد",newBest:"أفضل نتيجة جديدة: {value} محاولات!"}
  };
  Object.keys(REPLAY_COPY).forEach(locale=>Object.assign(COPY[locale],REPLAY_COPY[locale]));
  const ROUND_DATA=[{animal:"Pip",correct:"sun",briefKey:"brief1"},{animal:"Panko",correct:"rain",briefKey:"brief2"},{animal:"Moss Shell Taro",correct:"snow",briefKey:"brief3"}];
  const BEST_KEY="weightplay-animal-costume-workshop-best-v3";
  const readBest=()=>{try{const value=Number(window.localStorage.getItem(BEST_KEY));return Number.isFinite(value)&&value>=3?value:null;}catch(_error){return null;}};
  let bestChecks=readBest();
  const saveBest=checks=>{if(bestChecks!==null&&checks>=bestChecks)return false;try{window.localStorage.setItem(BEST_KEY,String(checks));}catch(_error){}bestChecks=checks;return true;};
  const ROUNDS=ROUND_DATA;
  const $=s=>document.querySelector(s); const canvas=$("#costumeCanvas"),ctx=canvas.getContext("2d"); const requestedLocale=new URLSearchParams(location.search).get("lang"); const state={locale:Object.prototype.hasOwnProperty.call(COPY,requestedLocale)?requestedLocale:"en",round:0,selected:"sun",sound:true,done:0,mode:"classic",order:[0,1,2],checks:0};
  const t=(k)=>COPY[state.locale][k]||COPY.en[k]||k; const track=(name,payload)=>window.WonderAnalytics?.track?.(name,{game_id:"animal-costume-workshop",game_version:"v3",interface_version:6,...payload});
  const currentRound=()=>ROUND_DATA[state.order[state.round]];
  function updateProgress(){$("#mainProgress").textContent=t("ready");$("#bestProgress").textContent=`${t("bestLabel")}: ${bestChecks===null?t("bestNone"):bestChecks}`;}
  function setupReplayUi(){const progress=$("#mainProgress"),best=document.createElement("p"),picker=document.createElement("div");best.id="bestProgress";best.className="progress replay-progress";best.setAttribute("aria-live","polite");progress.insertAdjacentElement("afterend",best);picker.className="mode-picker actions";picker.innerHTML='<label for="modeSelect" data-copy="modeLabel">Album mode</label><select id="modeSelect" aria-describedby="modeHelp"><option value="classic" data-copy="classic">Classic album</option><option value="shuffle" data-copy="shuffle">Shuffle album</option></select><p id="modeHelp" class="status" data-copy="modeHelp"></p>';progress.insertAdjacentElement("beforebegin",picker);}
  function setScreen(name){$("#mainScreen").classList.toggle("active",name==="main");$("#battleScreen").classList.toggle("active",name==="battle");const g=$("[data-wp-game-guide]");if(g)g.hidden=name!=="main";const r=$(".battle-ad-reserve");if(r)r.hidden=name!=="battle";document.body.dataset.screen=name;}
  function applyCopy(){document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==="ar"?"rtl":"ltr";document.title=`${t("title")} | WeightPlay`;document.querySelector('meta[name="description"]')?.setAttribute("content",t("lede"));document.querySelectorAll("[data-copy]").forEach(n=>n.textContent=t(n.dataset.copy));updateProgress();$("#locale").value=state.locale;$("#modeSelect").value=state.mode;$("#modeSelect").setAttribute("aria-label",t("modeLabel"));$("#soundButton").textContent=state.sound?t("soundOn"):t("soundOff");$("#soundButton").setAttribute("aria-pressed",String(state.sound));$("#soundButton").setAttribute("aria-label",t("soundOn"));$("#settingsButton").setAttribute("aria-label",t("settings"));$("#locale").setAttribute("aria-label",t("language"));$("#battleBack").setAttribute("aria-label",t("back"));$("#battleTitle").textContent=t("briefTitle");$("#postcardMark").textContent=t("postcard");$("#costumeCanvas").setAttribute("aria-label",t("canvasLabel"));$(".outfits").setAttribute("aria-label",t("choose"));$("#chooseButton").textContent=t("choose");$("#resetButton").textContent=t("reset");$("#nextButton").textContent=t("next");$("#retryButton").textContent=t("retry");$("#homeButton").textContent=t("home");renderRound();}
  function renderRound(){const round=currentRound();$("#roundLabel").textContent=`${t("animal")} ${state.round+1} / 3`;$("#brief").textContent=t(round.briefKey);$("#instruction").textContent=`${round.animal}: ${t("choose")}`;document.querySelectorAll(".outfit").forEach(b=>{const icon=b.dataset.outfit==="sun"?"☀️":b.dataset.outfit==="rain"?"🌧️":"❄️";b.innerHTML=`${icon}<br>${t(b.dataset.outfit)}`;b.classList.toggle("selected",b.dataset.outfit===state.selected);b.setAttribute("aria-label",`${t(b.dataset.outfit)}: ${t("choose")}`);});draw();}
  function draw(){if(!ctx||!$("#battleScreen").classList.contains("active"))return;const round=currentRound();ctx.fillStyle="#182f48";ctx.fillRect(0,0,900,700);ctx.fillStyle="#225062";ctx.fillRect(0,480,900,220);ctx.fillStyle="#ffd27d";ctx.beginPath();ctx.arc(730,130,72,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff7e8";ctx.font="800 34px system-ui";ctx.textAlign="center";ctx.fillText(round.animal,450,150);ctx.font="800 92px system-ui";ctx.fillText(state.selected==="sun"?"☀️":state.selected==="rain"?"🌧️":"❄️",450,360);ctx.font="700 22px system-ui";ctx.fillText(t(state.selected),450,420);ctx.strokeStyle="#78d0b0";ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(240,530);ctx.lineTo(660,530);ctx.stroke();}
  function start(){state.mode=$("#modeSelect").value==="shuffle"?"shuffle":"classic";state.order=state.mode==="shuffle"?[1,2,0]:[0,1,2];state.round=0;state.done=0;state.checks=0;state.selected=currentRound().correct;$("#resultCard").hidden=true;setScreen("battle");renderRound();track("costume_start",{mode:state.mode});}
  function choose(){if(!$("#resultCard").hidden)return;const round=currentRound(),good=state.selected===round.correct;state.checks+=1;$("#resultCard").hidden=false;$("#resultCard").classList.toggle("success",good);$("#resultCard").classList.toggle("fail",!good);$("#resultEyebrow").textContent=good?t("saved"):t("wrong");$("#resultTitle").textContent=good?t("great"):t("wrong");$("#resultCopy").textContent=good?t("saved"):t("wrong");$("#nextButton").hidden=!good;$("#retryButton").hidden=good;state.done=good?state.done+1:state.done;track(good?"costume_match":"costume_mismatch",{round:state.round+1,outfit:state.selected,mode:state.mode});}
  function finishWorkshop(){const isNewBest=saveBest(state.checks);$("#resultEyebrow").textContent=t("saved");$("#resultTitle").textContent=t("done");$("#resultCopy").textContent=`${t("doneCopy")} ${isNewBest?t("newBest").replace("{value}",state.checks):`${t("bestLabel")}: ${bestChecks}`}`;$("#nextButton").hidden=true;$("#retryButton").hidden=true;track("costume_complete",{checks:state.checks,best_checks:bestChecks,mode:state.mode});updateProgress();}
  function next(){if(state.round>=ROUND_DATA.length-1){finishWorkshop();return;}state.round+=1;state.selected=currentRound().correct;$("#resultCard").hidden=true;renderRound();track("costume_round_start",{round:state.round+1,mode:state.mode});}
  function retry(){$("#resultCard").hidden=true;renderRound();} function reset(){state.selected=currentRound().correct;$("#resultCard").hidden=true;renderRound();}
  $("#startButton").addEventListener("click",start);$("#guideButton").addEventListener("click",()=>$("[data-wp-game-guide]")?.scrollIntoView({behavior:"smooth",block:"center"}));$("#settingsButton").addEventListener("click",()=>{const p=$("#settingsPopover"),open=p.hidden;p.hidden=!open;$("#settingsButton").setAttribute("aria-expanded",String(open));});$("#soundButton").addEventListener("click",()=>{state.sound=!state.sound;applyCopy();});$("#battleBack").addEventListener("click",()=>setScreen("main"));document.querySelectorAll(".outfit").forEach(b=>b.addEventListener("click",()=>{state.selected=b.dataset.outfit;renderRound();}));$("#chooseButton").addEventListener("click",choose);$("#resetButton").addEventListener("click",reset);$("#nextButton").addEventListener("click",next);$("#retryButton").addEventListener("click",retry);$("#homeButton").addEventListener("click",()=>setScreen("main"));$("#locale").addEventListener("change",e=>{state.locale=e.target.value;applyCopy();});applyCopy();
  $("#modeSelect").addEventListener("change",e=>{state.mode=e.target.value==="shuffle"?"shuffle":"classic";});
  const syncSoundLabel = () => $("#soundButton").setAttribute("aria-label", state.sound ? t("soundOn") : t("soundOff"));
  $("#soundButton").addEventListener("click", syncSoundLabel);
  $("#locale").addEventListener("change", syncSoundLabel);
  document.querySelector(".lede")?.classList.add("main-summary");
  setupReplayUi();
  applyCopy();
})();
