(() => {
  "use strict";
  const LOCALES=window.SKYDROP_LOCALES;
  const localeOrder=["en","zh-Hant","zh-Hans","ja","ko","es","pt-BR","fr","de","it","ru"];
  const localeLabels={en:"English","zh-Hant":"繁體中文","zh-Hans":"简体中文",ja:"日本語",ko:"한국어",es:"Español","pt-BR":"Português",fr:"Français",de:"Deutsch",it:"Italiano",ru:"Русский"};
  const routeLocales={en:"en","zh-tw":"zh-Hant","zh-cn":"zh-Hans",ja:"ja",ko:"ko",es:"es","pt-br":"pt-BR",fr:"fr",de:"de",it:"it",ru:"ru"};
  const storageKey="weightplay:animal-skyspire-drop:v1",sessionStore=new Map();
  const $=id=>document.getElementById(id);
  const els={loading:$("loading"),mainGroup:$("mainGroup"),stageScreen:$("stageScreen"),battleScreen:$("battleScreen"),localeSelect:$("localeSelect"),mainProgress:$("mainProgress"),start:$("start"),stageBack:$("stageBack"),stageRail:$("stageRail"),stageSummary:$("stageSummary"),racesTab:$("racesTab"),forgeTab:$("forgeTab"),towerPanel:$("towerPanel"),forgePanel:$("forgePanel"),stageHint:$("stageHint"),shardCount:$("shardCount"),upgrades:$("upgrades"),auraButton:$("auraButton"),forgeFeedback:$("forgeFeedback"),battleBack:$("battleBack"),battleHelp:$("battleHelp"),towerLabel:$("towerLabel"),depthValue:$("depthValue"),comboValue:$("comboValue"),timeValue:$("timeValue"),shieldValue:$("shieldValue"),objective:$("objective"),arenaWrap:$("arenaWrap"),arena:$("arena"),powerBadge:$("powerBadge"),powerValue:$("powerValue"),feedback:$("feedback"),helpModal:$("helpModal"),helpClose:$("helpClose"),leaveModal:$("leaveModal"),leaveContinue:$("leaveContinue"),leaveStage:$("leaveStage"),resultModal:$("resultModal"),resultKicker:$("resultKicker"),resultTitle:$("resultTitle"),resultText:$("resultText"),resultTime:$("resultTime"),resultCombo:$("resultCombo"),resultStars:$("resultStars"),retry:$("retry"),resultMap:$("resultMap"),next:$("next")};
  const defaultSave={unlocked:1,stars:{},best:{},shards:0,upgrades:{grip:0,aegis:0,spark:0},tutorial:false,aura:false};
  let lang=detectLocale(),save=loadSave(),stageIndex=Math.max(0,Math.min(29,save.unlocked-1)),run=null,raf=0,lastFrame=0,screen="main",activeTab="towers",resizeObserver=null;
  const images={};
  const imagePaths={background:"../../assets/animal-skyspire-drop/spire-bg.webp",hero:"../../assets/animal-skyspire-drop/fia-orb.webp",safe:"../../assets/animal-skyspire-drop/safe-texture.webp",hazard:"../../assets/animal-skyspire-drop/hazard-texture.webp",fragile:"../../assets/animal-skyspire-drop/fragile-texture.webp",goal:"../../assets/animal-skyspire-drop/goal-texture.webp"};
  const ctx=els.arena.getContext("2d");
  const TAU=Math.PI*2,PLAYER_ANGLE=-Math.PI/2;

  function detectLocale(){const segment=location.pathname.split("/").filter(Boolean)[0]?.toLowerCase();if(routeLocales[segment])return routeLocales[segment];try{const stored=localStorage.getItem("weightplayLocale");if(localeOrder.includes(stored))return stored}catch{}return "en"}
  function storageRead(key){try{return localStorage.getItem(key)}catch{return sessionStore.get(key)||null}}
  function storageWrite(key,value){try{localStorage.setItem(key,value)}catch{sessionStore.set(key,value)}}
  function normalizeSave(raw={}){const upgrades=raw.upgrades||{};return{unlocked:boundInt(raw.unlocked,1,30,1),stars:raw.stars&&typeof raw.stars==="object"?raw.stars:{},best:raw.best&&typeof raw.best==="object"?raw.best:{},shards:boundInt(raw.shards,0,99999,0),upgrades:{grip:boundInt(upgrades.grip,0,3,0),aegis:boundInt(upgrades.aegis,0,3,0),spark:boundInt(upgrades.spark,0,2,0)},tutorial:Boolean(raw.tutorial),aura:Boolean(raw.aura)}}
  function loadSave(){try{return normalizeSave(JSON.parse(storageRead(storageKey)||"{}"))}catch{return normalizeSave()}}
  function persist(){storageWrite(storageKey,JSON.stringify(save))}
  function boundInt(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):fallback}
  function t(key,vars={}){let value=LOCALES[lang]?.[key]??LOCALES.en[key]??key;if(Array.isArray(value))return value;return String(value).replace(/\{(\w+)\}/g,(_,name)=>vars[name]??`{${name}}`)}
  function applyLocale(){document.documentElement.lang=lang;document.title=`${t("title")} | Internal WeightPlay Trial`;document.querySelectorAll("[data-t]").forEach(node=>{node.textContent=t(node.dataset.t)});document.querySelectorAll("[data-t-aria]").forEach(node=>node.setAttribute("aria-label",t(node.dataset.tAria)));document.querySelectorAll("[data-t-alt]").forEach(node=>node.setAttribute("alt",t(node.dataset.tAlt)));renderMainProgress();renderStages();renderForge();if(run)renderHud()}
  function initLocale(){els.localeSelect.innerHTML=localeOrder.map(code=>`<option value="${code}">${localeLabels[code]}</option>`).join("");els.localeSelect.value=lang;els.localeSelect.addEventListener("change",()=>{lang=els.localeSelect.value;try{localStorage.setItem("weightplayLocale",lang)}catch{}applyLocale()})}
  function track(event,details={}){window.WonderAnalytics?.track?.(event,{game_id:"animal-skyspire-drop",stage:stageIndex+1,locale:lang,...details})}

  function seeded(seed){let x=(seed|0)||1;return()=>{x=(x*1664525+1013904223)|0;return((x>>>0)/4294967296)}}
  function normAngle(angle){angle%=TAU;return angle<0?angle+TAU:angle}
  function angleDistance(a,b){return Math.abs(Math.atan2(Math.sin(a-b),Math.cos(a-b)))}
  function buildStage(index){const chapter=Math.floor(index/5),within=index%5,ringCount=8+chapter*2+within;const rand=seeded(9127+index*733);const rings=[];for(let i=0;i<ringCount;i++){const gapWidth=Math.max(.54,1.18-chapter*.075-within*.025);const gap=rand()*TAU;let hazard=normAngle(gap+Math.PI*(.72+rand()*.56));const hazardWidth=Math.min(1.5,.58+chapter*.1+within*.035);rings.push({gap,gapWidth,hazard,hazardWidth,offset:(rand()-.5)*.25,drift:chapter>=2&&i%3!==0?(rand()>.5?1:-1)*(.09+chapter*.018+within*.008):0,fragile:chapter>=1&&i%3===1,reverse:chapter>=3&&i%4===2,crystal:chapter>=4&&i%5===2,cracked:false,broken:false})}return{index,chapter,within,ringCount,rings,target:Math.round(ringCount*(1.45-chapter*.035)+5),name:t("chapters")[chapter],rule:t("rules")[chapter]}}
  const stages=Array.from({length:30},(_,i)=>buildStage(i));
  function refreshStageLocale(){for(let i=0;i<stages.length;i++){stages[i].name=t("chapters")[stages[i].chapter];stages[i].rule=t("rules")[stages[i].chapter]}}

  function setScreen(next){screen=next;document.body.dataset.screen=next;els.mainGroup.hidden=next!=="main";els.stageScreen.hidden=next!=="stage";els.battleScreen.hidden=next!=="battle";if(next!=="battle")cancelAnimationFrame(raf);if(next==="stage"){renderStages();renderForge();requestAnimationFrame(centerCurrentStage)}if(next==="battle")startLoop();}
  function renderMainProgress(){const done=Object.keys(save.stars).filter(key=>Number(save.stars[key])>0).length;els.mainProgress.textContent=`${done} / 30`}
  function renderStages(){if(!els.stageRail)return;refreshStageLocale();els.stageRail.innerHTML="";for(const stage of stages){const locked=stage.index+1>save.unlocked,stars=Number(save.stars[stage.index]||0);const card=document.createElement("button");card.type="button";card.className=`stage-card${locked?" locked":""}`;card.disabled=locked;card.dataset.stage=String(stage.index);card.innerHTML=`<small>${t("chapter",{n:stage.chapter+1})} · ${stage.name}</small><strong>${t("stage",{n:stage.index+1})}</strong><span>${t("ringCount",{n:stage.ringCount})} · ${stars?"★".repeat(stars):locked?t("locked"):t("cleared")}</span><small>${stage.rule}</small>`;card.addEventListener("click",()=>{if(!locked)startBattle(stage.index)});els.stageRail.append(card)}els.stageSummary.textContent=`${Math.min(save.unlocked,30)} / 30 · ★ ${Object.values(save.stars).reduce((sum,n)=>sum+Number(n||0),0)}`;markCentered()}
  function centerCurrentStage(){const card=els.stageRail.querySelector(`[data-stage="${stageIndex}"]`);card?.scrollIntoView({inline:"center",block:"nearest",behavior:"instant"});requestAnimationFrame(markCentered)}
  function markCentered(){const cards=[...els.stageRail.querySelectorAll(".stage-card")];if(!cards.length)return;const railRect=els.stageRail.getBoundingClientRect(),cx=(railRect.left+railRect.right)/2;let best=cards[0],distance=Infinity;for(const card of cards){const rect=card.getBoundingClientRect(),d=Math.abs((rect.left+rect.right)/2-cx);if(d<distance){best=card;distance=d}}cards.forEach(card=>card.classList.toggle("centered",card===best));if(best)stageIndex=Number(best.dataset.stage)}
  let stageScrollTimer=0;els.stageRail.addEventListener("scroll",()=>{clearTimeout(stageScrollTimer);stageScrollTimer=setTimeout(markCentered,80)},{passive:true});
  function setTab(tab){activeTab=tab;const towers=tab==="towers";els.towerPanel.hidden=!towers;els.forgePanel.hidden=towers;els.racesTab.classList.toggle("active",towers);els.forgeTab.classList.toggle("active",!towers);if(towers)requestAnimationFrame(centerCurrentStage)}
  function renderForge(){els.shardCount.textContent=t("shards",{n:save.shards});const defs=[{id:"grip",title:"upgradeGrip",desc:"upgradeGripDesc",cost:[12,24,42]},{id:"aegis",title:"upgradeAegis",desc:"upgradeAegisDesc",cost:[18,34,54]},{id:"spark",title:"upgradeSpark",desc:"upgradeSparkDesc",cost:[28,52]}];els.upgrades.innerHTML="";for(const def of defs){const level=save.upgrades[def.id],max=def.cost.length,cost=def.cost[level];const button=document.createElement("button");button.type="button";button.dataset.upgrade=def.id;button.className=`upgrade${level>=max?" maxed":""}`;button.innerHTML=`<strong>${t(def.title)} · ${level}/${max}</strong><small>${t(def.desc)}</small><b>${level>=max?t("maxed"):t("upgradeButton",{n:cost})}</b>`;button.disabled=level>=max;button.addEventListener("click",()=>{if(save.shards<cost){els.forgeFeedback.textContent=`${t("shards",{n:save.shards})} / ${t("upgradeButton",{n:cost})}`;return}save.shards-=cost;save.upgrades[def.id]++;els.forgeFeedback.textContent="";persist();renderForge();track("skyspire_upgrade",{upgrade:def.id,level:save.upgrades[def.id]})});els.upgrades.append(button)}els.auraButton.textContent=save.aura?t("auraOwned"):t("auraBuy");els.auraButton.disabled=save.aura}

  function startBattle(index,{skipTutorial=false}={}){stageIndex=Math.max(0,Math.min(29,index));const stage=buildStage(stageIndex);run={stage,current:0,rotation:0,bounce:0.18,transition:0,elapsed:0,combo:0,bestCombo:0,power:false,shield:save.upgrades.aegis>=2?2:save.upgrades.aegis>=1?1:0,paused:false,ended:false,result:null,lastFeedback:"",dragging:false,lastX:0,keys:new Set(),landings:0,shieldsUsed:0};els.resultModal.hidden=true;els.leaveModal.hidden=true;els.helpModal.hidden=true;els.feedback.textContent="";setScreen("battle");syncArenaSize();renderHud();track("game_start");if(!save.tutorial&&!skipTutorial){run.paused=true;els.helpModal.hidden=false}else{save.tutorial=true;persist()}}
  function startLoop(){cancelAnimationFrame(raf);lastFrame=performance.now();raf=requestAnimationFrame(frame)}
  function frame(now){if(screen!=="battle"||!run)return;const dt=Math.min(.04,(now-lastFrame)/1000||0);lastFrame=now;if(!run.paused&&!run.ended)update(dt);draw();raf=requestAnimationFrame(frame)}
  function update(dt){run.elapsed+=dt;const grip=1+save.upgrades.grip*.18;if(run.keys.has("left"))run.rotation-=dt*2.35*grip*(currentReverse()?-1:1);if(run.keys.has("right"))run.rotation+=dt*2.35*grip*(currentReverse()?-1:1);run.rotation=normAngle(run.rotation);if(run.transition>0)run.transition=Math.max(0,run.transition-dt*2.8);run.bounce+=dt*(1.12+run.stage.chapter*.035+run.stage.within*.012);if(run.bounce>=1)land();renderHud()}
  function currentRing(){return run?.stage.rings[run.current]}
  function currentReverse(){return Boolean(currentRing()?.reverse)}
  function ringAngle(ring){return normAngle(ring.offset+ring.drift*run.elapsed)}
  function sectorAtPlayer(ring){if(!ring||ring.broken)return"gap";const local=normAngle(PLAYER_ANGLE-run.rotation-ringAngle(ring));if(angleDistance(local,ring.gap)<ring.gapWidth/2)return"gap";if(angleDistance(local,ring.hazard)<ring.hazardWidth/2)return"hazard";return ring.fragile?"fragile":"safe"}
  function threshold(){return Math.max(2,3-save.upgrades.spark)}
  function passRing(kind){run.current++;run.combo++;run.bestCombo=Math.max(run.bestCombo,run.combo);if(run.combo>=threshold())run.power=true;run.transition=1;run.bounce=.13;run.lastFeedback=t(kind==="gap"?"gapPass":"cometSmash",{n:run.combo});els.feedback.textContent=run.lastFeedback;if(run.current>=run.stage.ringCount)finish(true)}
  function land(){run.landings++;run.bounce=0;const ring=currentRing(),sector=sectorAtPlayer(ring);if(sector==="gap"){passRing("gap");return}if(sector==="hazard"){if(run.power){run.power=false;run.combo=0;ring.broken=true;passRing("smash");return}if(run.shield>0){run.shield--;run.shieldsUsed++;run.combo=0;run.lastFeedback=t("shieldSave");els.feedback.textContent=run.lastFeedback;return}run.lastFeedback=t("hazardHit");els.feedback.textContent=run.lastFeedback;finish(false);return}if(sector==="fragile"){if(ring.cracked){ring.broken=true;run.lastFeedback=t("fragileBreak");els.feedback.textContent=run.lastFeedback;passRing("smash")}else{ring.cracked=true;run.combo=0;run.lastFeedback=t("fragileCrack");els.feedback.textContent=run.lastFeedback}return}run.combo=0;if(ring.crystal&&run.shield<2){run.shield++;ring.crystal=false;run.lastFeedback=t("crystal")}else run.lastFeedback=currentReverse()?t("reversed"):t("safeBounce");els.feedback.textContent=run.lastFeedback}
  function finish(win){if(run.ended)return;run.ended=true;run.paused=true;const time=Number(run.elapsed.toFixed(1));let stars=0,newBest=false;if(win){stars=time<=run.stage.target?3:time<=run.stage.target*1.35?2:1;const old=Number(save.best[stageIndex]||Infinity);newBest=time<old;save.best[stageIndex]=Math.min(old,time);save.stars[stageIndex]=Math.max(Number(save.stars[stageIndex]||0),stars);save.unlocked=Math.max(save.unlocked,Math.min(30,stageIndex+2));const reward=4+stars*2+run.stage.chapter;save.shards+=reward;persist();renderMainProgress();track("game_complete",{time,stars,best_combo:run.bestCombo})}else track("game_fail",{depth:run.current,time});run.result={win,time,stars,newBest};showResult()}
  function syncResultActions(won){const terminal=won&&stageIndex>=29;els.next.hidden=!won||terminal;const primary=won?(terminal?els.resultMap:els.next):els.retry;for(const action of [els.retry,els.resultMap,els.next])action.classList.toggle("primary",action===primary);requestAnimationFrame(()=>primary.focus({preventScroll:true}))}
  function showResult(){const r=run.result;els.resultKicker.textContent=t(r.win?"winKicker":"failKicker");els.resultTitle.textContent=t(r.win?"winTitle":"failTitle");els.resultText.textContent=r.win?t("winText",{n:stageIndex+1,time:r.time}):t("failText");els.resultTime.textContent=`${r.time}s`;els.resultCombo.textContent=String(run.bestCombo);els.resultStars.textContent=r.win?"★".repeat(r.stars):"—";els.resultModal.hidden=false;syncResultActions(r.win)}
  function renderHud(){if(!run)return;els.towerLabel.textContent=`${t("stage",{n:stageIndex+1})} · ${run.stage.name}`;els.depthValue.textContent=`${Math.min(run.current+1,run.stage.ringCount)} / ${run.stage.ringCount}`;els.comboValue.textContent=String(run.combo);els.timeValue.textContent=run.elapsed.toFixed(1);els.shieldValue.textContent=String(run.shield);els.powerValue.textContent=run.power?t("maxed"):`${Math.min(run.combo,threshold())} / ${threshold()}`;els.powerBadge.classList.toggle("ready",run.power)}

  function syncArenaSize(){const rect=els.arena.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(els.arena.width!==w||els.arena.height!==h){els.arena.width=w;els.arena.height=h;els.arena.dataset.dpr=String(dpr)}}
  function coverImage(img,x,y,w,h){if(!img?.complete)return;const ratio=Math.max(w/img.naturalWidth,h/img.naturalHeight),sw=w/ratio,sh=h/ratio,sx=(img.naturalWidth-sw)/2,sy=(img.naturalHeight-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
  function draw(){if(!run)return;const dpr=Number(els.arena.dataset.dpr||1),W=els.arena.width/dpr,H=els.arena.height/dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);coverImage(images.background,0,0,W,H);ctx.fillStyle="#03132966";ctx.fillRect(0,0,W,H);const cx=W/2,currentY=H*.61,radius=Math.min(W*.42,H*.48,270),spacing=Math.max(68,Math.min(118,H*.155));ctx.fillStyle="#d8f7ff22";ctx.fillRect(cx-radius*.12,0,radius*.24,H);for(let i=Math.max(0,run.current-2);i<Math.min(run.stage.ringCount,run.current+5);i++){const y=currentY+(i-run.current)*spacing+run.transition*spacing;drawRing(run.stage.rings[i],cx,y,radius,i===run.current)}if(run.current>=run.stage.ringCount)drawGoal(cx,currentY,radius);const bounceHeight=Math.sin(Math.min(1,run.bounce)*Math.PI)*Math.min(88,H*.15);const heroSize=Math.min(112,Math.max(68,W*.19)),heroY=currentY-radius*.16-heroSize*.72-bounceHeight;if(save.aura){ctx.save();ctx.globalAlpha=.7;ctx.fillStyle="#c786ff";for(let i=0;i<6;i++){ctx.beginPath();ctx.arc(cx+(i%2?1:-1)*i*3,heroY+heroSize*.55+i*8,Math.max(2,7-i),0,TAU);ctx.fill()}ctx.restore()}if(run.power){ctx.save();ctx.shadowBlur=32;ctx.shadowColor="#ffe56d";ctx.fillStyle="#fff2a855";ctx.beginPath();ctx.arc(cx,heroY+heroSize/2,heroSize*.58,0,TAU);ctx.fill();ctx.restore()}ctx.drawImage(images.hero,cx-heroSize/2,heroY,heroSize,heroSize);if(run.ended&&!run.result?.win){ctx.fillStyle="#d56eff33";ctx.fillRect(0,0,W,H)}}
  function drawRing(ring,cx,y,radius,isCurrent){const yScale=.31,inner=radius*.43,slices=24;ctx.save();ctx.translate(cx,y+9);ctx.scale(1,yScale);ctx.globalAlpha=.72;for(let s=0;s<slices;s++){const a0=s/slices*TAU+.018,a1=(s+1)/slices*TAU-.018,mid=(a0+a1)/2,type=visualSector(ring,mid);if(type==="gap")continue;drawWedge(a0,a1,inner,radius,"#06101e")}ctx.restore();ctx.save();ctx.translate(cx,y);ctx.scale(1,yScale);for(let s=0;s<slices;s++){const a0=s/slices*TAU+.018,a1=(s+1)/slices*TAU-.018,mid=(a0+a1)/2,type=visualSector(ring,mid);if(type==="gap")continue;const image=images[type==="hazard"?"hazard":type==="fragile"?"fragile":"safe"];drawWedge(a0,a1,inner,radius,ctx.createPattern(image,"repeat"));ctx.strokeStyle=type==="hazard"?"#c66cff":type==="fragile"?"#bffaff":"#f4c860";ctx.lineWidth=isCurrent?5:3;ctx.stroke()}ctx.restore();if(ring.crystal){ctx.save();ctx.translate(cx,y-radius*.06);ctx.fillStyle="#fff4a8";ctx.shadowBlur=18;ctx.shadowColor="#61edff";ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(11,0);ctx.lineTo(0,16);ctx.lineTo(-11,0);ctx.closePath();ctx.fill();ctx.restore()}}
  function visualSector(ring,screenAngle){if(ring.broken)return"gap";const local=normAngle(screenAngle-run.rotation-ringAngle(ring));if(angleDistance(local,ring.gap)<ring.gapWidth/2)return"gap";if(angleDistance(local,ring.hazard)<ring.hazardWidth/2)return"hazard";return ring.fragile?"fragile":"safe"}
  function drawWedge(a0,a1,inner,outer,fill){ctx.beginPath();ctx.arc(0,0,outer,a0,a1);ctx.arc(0,0,inner,a1,a0,true);ctx.closePath();ctx.fillStyle=fill||"#38b9c2";ctx.fill()}
  function drawGoal(cx,y,radius){ctx.save();ctx.translate(cx,y);ctx.scale(1,.31);ctx.beginPath();ctx.arc(0,0,radius,0,TAU);ctx.arc(0,0,radius*.32,TAU,0,true);ctx.closePath();ctx.fillStyle=ctx.createPattern(images.goal,"repeat");ctx.fill();ctx.strokeStyle="#fff4a2";ctx.lineWidth=6;ctx.stroke();ctx.restore()}

  function rotateBy(delta){if(!run||run.paused||run.ended)return;const grip=1+save.upgrades.grip*.18;run.rotation=normAngle(run.rotation+delta*grip*(currentReverse()?-1:1))}
  els.arena.addEventListener("pointerdown",event=>{if(!run||run.paused||run.ended)return;run.dragging=true;run.lastX=event.clientX;els.arena.setPointerCapture(event.pointerId);event.preventDefault()});
  els.arena.addEventListener("pointermove",event=>{if(!run?.dragging)return;const dx=event.clientX-run.lastX;run.lastX=event.clientX;rotateBy(dx*.012);event.preventDefault()});
  const stopDrag=()=>{if(run)run.dragging=false};els.arena.addEventListener("pointerup",stopDrag);els.arena.addEventListener("pointercancel",stopDrag);
  window.addEventListener("keydown",event=>{if(screen!=="battle"||!run||run.paused)return;if(["ArrowLeft","a","A"].includes(event.key)){run.keys.add("left");event.preventDefault()}if(["ArrowRight","d","D"].includes(event.key)){run.keys.add("right");event.preventDefault()}});
  window.addEventListener("keyup",event=>{if(!run)return;if(["ArrowLeft","a","A"].includes(event.key))run.keys.delete("left");if(["ArrowRight","d","D"].includes(event.key))run.keys.delete("right")});

  els.start.addEventListener("click",()=>{setScreen("stage");track("game_start_menu")});els.stageBack.addEventListener("click",()=>setScreen("main"));els.racesTab.addEventListener("click",()=>setTab("towers"));els.forgeTab.addEventListener("click",()=>setTab("forge"));els.battleBack.addEventListener("click",()=>{if(!run||run.ended){setScreen("stage");return}run.paused=true;els.leaveModal.hidden=false});els.leaveContinue.addEventListener("click",()=>{els.leaveModal.hidden=true;run.paused=false;lastFrame=performance.now()});els.leaveStage.addEventListener("click",()=>{els.leaveModal.hidden=true;run=null;setScreen("stage")});els.battleHelp.addEventListener("click",()=>{if(!run)return;run.paused=true;els.helpModal.hidden=false});els.helpClose.addEventListener("click",()=>{els.helpModal.hidden=true;if(run){run.paused=false;save.tutorial=true;persist();lastFrame=performance.now()}});els.retry.addEventListener("click",()=>startBattle(stageIndex,{skipTutorial:true}));els.resultMap.addEventListener("click",()=>{run=null;setScreen("stage")});els.next.addEventListener("click",()=>startBattle(Math.min(29,stageIndex+1),{skipTutorial:true}));els.auraButton.addEventListener("click",()=>{if(save.aura)return;if(window.WeightPlayWallet?.spendDiamonds?.(10)){save.aura=true;els.forgeFeedback.textContent="";persist();renderForge()}else els.forgeFeedback.textContent=`${t("auraTitle")} · ${t("auraBuy")}`});
  window.addEventListener("resize",syncArenaSize,{passive:true});if("ResizeObserver"in window){resizeObserver=new ResizeObserver(syncArenaSize);resizeObserver.observe(els.arenaWrap)}

  function preload(){return Promise.all(Object.entries(imagePaths).map(([key,src])=>new Promise(resolve=>{const image=new Image;image.onload=()=>{images[key]=image;resolve()};image.onerror=()=>{images[key]=image;resolve()};image.src=src})))}
  window.__animalSkyspireDropSmoke={stages,startBattle:(index=0)=>startBattle(index,{skipTutorial:true}),snapshot:()=>run?{stage:run.stage.index,current:run.current,rotation:run.rotation,bounce:run.bounce,combo:run.combo,bestCombo:run.bestCombo,power:run.power,shield:run.shield,elapsed:run.elapsed,paused:run.paused,ended:run.ended,result:run.result,screen}:null,rotateToGap:()=>{const ring=currentRing();if(!ring)return false;run.rotation=normAngle(PLAYER_ANGLE-ringAngle(ring)-ring.gap);return true},forceLanding:()=>{if(!run||run.ended)return false;run.bounce=1;land();return true},forceWin:()=>{if(!run)return;run.current=run.stage.ringCount;finish(true)},forceFail:()=>{if(!run)return;finish(false)},save:()=>JSON.parse(JSON.stringify(save)),setSave:value=>{save=normalizeSave(value);persist();renderMainProgress();renderStages();renderForge()}};
  initLocale();applyLocale();preload().then(()=>{els.loading.hidden=true;syncArenaSize();renderMainProgress();renderStages();renderForge()});
})();
