(function () {
  "use strict";

  const languageNames = { en: "English", "zh-Hant": "繁體中文", "zh-Hans": "简体中文", ja: "日本語", ko: "한국어", es: "Español", "pt-BR": "Português (Brasil)", fr: "Français", de: "Deutsch", it: "Italiano", ru: "Русский", hi: "हिन्दी", ar: "العربية" };
  const base = {
    direction: "ltr", language: "Language", languageNames, title: "Grove Chain", kicker: "A calm habitat-chain puzzle", intro: "Match each habitat end to complete a gentle loop through the moonlit grove.", facts: "Three short chains · no timer · no lives", start: "Start the chain", guideTitle: "How to play", guideOneTitle: "1. Read the end", guideOne: "Look at the habitat shown at the open end of the chain.", guideTwoTitle: "2. Choose a match", guideTwo: "Tap a tile whose left habitat matches that open end.", guideThreeTitle: "3. Close the loop", guideThree: "Use all five tiles. A wrong pick is safe and can be tried again.", settings: "Settings", soundOn: "Sound: On", soundOff: "Sound: Off", back: "Back", round: "Chain {current} of {total}", end: "Open habitat: {habitat}", tilesPlaced: "Tiles", chainTitle: "Habitat chain", instruction: "Choose a tile that starts with the open habitat.", chooseTile: "Choose tile: {left} to {right}", wrong: "That habitat belongs later. Try another tile.", right: "A good match. The grove path continues.", completeKicker: "Grove loop complete", finishTitle: "The grove is connected.", finishText: "You closed three habitat loops with {picks} picks.", best: "Best picks", noBest: "Not yet", replay: "Chain again", home: "Return home", footer: "Internal prototype · planned Coming Soon · no public playable route", leaveTitle: "Leave this chain?", leaveBody: "Your current picks will be lost, but your best run stays saved.", continue: "Continue", confirmLeave: "Return home", tokenNames: { den: "Den", creek: "Creek", moss: "Moss", nest: "Nest", moon: "Moon", reef: "Reef", tide: "Tide", shell: "Shell", grove: "Grove", pine: "Pine", snow: "Snow", burrow: "Burrow", pond: "Pond", meadow: "Meadow" }
  };
  const overrides = {
    "zh-Hant": { direction: "ltr", title: "林間接龍", kicker: "平靜的棲地接龍益智", intro: "配對每個棲地端點，完成月光森林裡的溫柔環路。", facts: "三段短接龍・沒有計時・沒有生命損失", start: "開始接龍", guideTitle: "玩法說明", guideOneTitle: "1. 讀取端點", guideOne: "先看接龍開放端顯示的棲地。", guideTwoTitle: "2. 選擇配對", guideTwo: "點選左側棲地與開放端相同的木牌。", guideThreeTitle: "3. 闔上環路", guideThree: "用完五張木牌；選錯不會受罰，可以再試。", settings: "設定", soundOn: "音效：開", soundOff: "音效：關", back: "返回", round: "第 {current} 段／共 {total} 段", end: "開放棲地：{habitat}", tilesPlaced: "木牌", instruction: "選擇以開放棲地開始的木牌。", wrong: "這個棲地稍後才會出現，再找找看。", right: "配對成功，森林小徑繼續延伸。", completeKicker: "森林環路完成", finishTitle: "森林連起來了。", finishText: "你用 {picks} 次選擇完成三段棲地環路。", best: "最佳選擇次數", noBest: "尚未完成", replay: "再接一次", home: "回到首頁", footer: "內部原型・規劃中 Coming Soon・尚未公開遊玩", leaveTitle: "要離開這段接龍嗎？", leaveBody: "目前選擇會消失，但最佳紀錄會保留。", continue: "繼續", confirmLeave: "回到首頁", tokenNames: { den: "巢穴", creek: "溪流", moss: "苔蘚", nest: "鳥巢", moon: "月光", reef: "礁岩", tide: "潮汐", shell: "貝殼", grove: "林地", pine: "松林", snow: "雪地", burrow: "地穴", pond: "池塘", meadow: "草地" } },
    "zh-Hans": { title: "林间接龙", intro: "配对每个栖地端点，完成月光森林里的温柔环路。", start: "开始接龙", guideTitle: "玩法说明", back: "返回", home: "回到首页", soundOn: "音效：开", soundOff: "音效：关", footer: "内部原型・规划中 Coming Soon・尚未公开游玩" },
    ja: { title: "グローブ・チェーン", kicker: "静かな生息地チェーンパズル", intro: "月明かりの森で、生息地の端を合わせてやさしい輪を完成させよう。", start: "チェーンを始める", guideTitle: "遊び方", back: "戻る", home: "ホームへ", soundOn: "サウンド：オン", soundOff: "サウンド：オフ" },
    ko: { title: "그로브 체인", kicker: "차분한 서식지 연결 퍼즐", intro: "서식지 끝을 맞춰 달빛 숲의 부드러운 고리를 완성하세요.", start: "연결 시작", guideTitle: "게임 방법", back: "뒤로", home: "홈으로", soundOn: "소리: 켜짐", soundOff: "소리: 꺼짐" },
    es: { title: "Cadena del Bosque", kicker: "Un puzle tranquilo de hábitats", intro: "Une cada extremo de hábitat para cerrar un ciclo sereno bajo la luna.", start: "Empezar la cadena", guideTitle: "Cómo jugar", back: "Volver", home: "Volver al inicio" },
    "pt-BR": { title: "Corrente do Bosque", kicker: "Um quebra-cabeça calmo de habitats", intro: "Combine cada ponta de habitat para fechar um ciclo sereno sob a lua.", start: "Começar a corrente", guideTitle: "Como jogar", back: "Voltar", home: "Voltar ao início" },
    fr: { title: "Chaîne du Bosquet", kicker: "Un puzzle paisible d’habitats", intro: "Associez chaque extrémité d’habitat pour fermer une boucle sous la lune.", start: "Commencer la chaîne", guideTitle: "Comment jouer", back: "Retour", home: "Retour à l’accueil" },
    de: { title: "Waldkette", kicker: "Ein ruhiges Lebensraum-Puzzle", intro: "Verbinde die Lebensraum-Enden und schließe einen sanften Mondwald-Kreis.", start: "Kette starten", guideTitle: "So wird gespielt", back: "Zurück", home: "Zum Start" },
    it: { title: "Catena del Bosco", kicker: "Un tranquillo puzzle di habitat", intro: "Abbina ogni estremità dell’habitat per chiudere un ciclo al chiaro di luna.", start: "Inizia la catena", guideTitle: "Come si gioca", back: "Indietro", home: "Torna all’inizio" },
    ru: { title: "Лесная цепочка", kicker: "Спокойная головоломка о местах обитания", intro: "Соединяйте края мест обитания и замыкайте тихий лунный круг.", start: "Начать цепочку", guideTitle: "Как играть", back: "Назад", home: "На главную" },
    hi: { title: "वन श्रृंखला", kicker: "शांत आवास-श्रृंखला पहेली", intro: "हर आवास के सिरे को मिलाकर चाँदनी वन का कोमल चक्र पूरा करें।", start: "श्रृंखला शुरू करें", guideTitle: "कैसे खेलें", back: "वापस", home: "मुख्य पृष्ठ" },
    ar: { direction: "rtl", language: "اللغة", title: "سلسلة الغابة", kicker: "لغز هادئ لربط المواطن", intro: "طابق نهايات المواطن لإكمال حلقة لطيفة في الغابة المضيئة بالقمر.", facts: "ثلاث سلاسل قصيرة · بلا مؤقت · بلا خسارة حياة", start: "ابدأ السلسلة", guideTitle: "طريقة اللعب", guideOneTitle: "١. اقرأ النهاية", guideOne: "انظر إلى الموطن الظاهر عند الطرف المفتوح من السلسلة.", guideTwoTitle: "٢. اختر التطابق", guideTwo: "اضغط على قطعة يبدأ موطنها الأيسر من الطرف المفتوح نفسه.", guideThreeTitle: "٣. أغلق الحلقة", guideThree: "استخدم القطع الخمس. الاختيار الخاطئ آمن ويمكن المحاولة مجددًا.", settings: "الإعدادات", back: "رجوع", home: "العودة إلى الصفحة الرئيسية", soundOn: "الصوت: تشغيل", soundOff: "الصوت: إيقاف", round: "السلسلة {current} من {total}", end: "الموطن المفتوح: {habitat}", tilesPlaced: "القطع", instruction: "اختر قطعة تبدأ بالموطن المفتوح.", completeKicker: "اكتملت حلقة الغابة", finishTitle: "اتصلت الغابة.", finishText: "أغلقت ثلاث حلقات من المواطن باستخدام {picks} اختيارًا.", best: "أفضل عدد اختيارات", noBest: "ليس بعد", replay: "سلسلة أخرى", footer: "نموذج أولي داخلي · قادم قريبًا · لا توجد لعبة عامة", leaveTitle: "هل تريد مغادرة هذه السلسلة؟", leaveBody: "ستفقد اختياراتك الحالية، لكن ستبقى أفضل نتيجة محفوظة.", continue: "متابعة", confirmLeave: "العودة إلى الصفحة الرئيسية", wrong: "هذا الموطن يأتي لاحقًا. جرّب قطعة أخرى.", right: "تطابق جيد. يستمر مسار الغابة." }
  };
  const locales = {};
  for (const key of Object.keys(languageNames)) locales[key] = { ...base, ...(overrides[key] || {}), languageNames };
  locales.__localeKeys = Object.keys(languageNames);
  window.GROVE_CHAIN_LOCALES = locales;
})();
