(()=>{
  "use strict";
  const codes=["en","zh-Hant","zh-Hans","ja","ko","es","pt-BR","fr","de","it","ru","hi","ar"],levels=window.SUNBEAM_LEVELS.levels;
  const $=s=>document.querySelector(s),screens=[...document.querySelectorAll(".screen")],key="wp-animal-sunbeam-v1";
  let locale=read("wp-locale")||"en";if(!codes.includes(locale))locale="en";let unlocked=Number(read(key))||1,selected=Math.min(unlocked,30)-1,level=null,mirrors=[],moves=0;
  function read(k){try{return localStorage.getItem(k)}catch{return null}}function write(k,v){try{localStorage.setItem(k,v)}catch{}}
  function t(k,v={}){const value=window.SUNBEAM_LOCALES[locale]?.[k]??window.SUNBEAM_LOCALES.en[k]??k;return String(value).replace(/\{(\w+)\}/g,(_,n)=>v[n]??"")}
  function show(id){screens.forEach(screen=>screen.hidden=screen.id!==id);$("#generalReserve").hidden=id!=="battle";document.body.dataset.screen=id;window.scrollTo(0,0);if(id==="stage")renderStages()}
  function selectStage(index,center=false){selected=Math.max(0,Math.min(29,index));document.querySelectorAll("#stageGrid .stage-card").forEach((card,cardIndex)=>{const active=cardIndex===selected;card.classList.toggle("selected",active);card.classList.toggle("centered",active);card.setAttribute("aria-current",active?"true":"false")});if(center)document.querySelector(`#stageGrid [data-index="${selected}"]`)?.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})}
  function renderStages(){$("#progress").textContent=t("progress",{done:Math.min(unlocked-1,30)});$("#stageGrid").innerHTML="";levels.forEach((item,index)=>{const b=document.createElement("button"),locked=index+1>unlocked;b.className="stage-card"+(index===selected?" selected centered":"")+(locked?" locked":"");b.dataset.index=index;b.dataset.stageIndex=index;b.setAttribute("aria-current",index===selected?"true":"false");b.setAttribute("aria-disabled",locked?"true":"false");b.innerHTML="<strong>"+t("garden",{n:index+1})+"</strong><span>"+(locked?t("locked"):t("chapter",{n:Math.floor(index/5)+1}))+"</span>";b.onclick=()=>{selectStage(index,true);if(!locked)startLevel(index)};$("#stageGrid").append(b)});selectStage(selected)}
  function startLevel(index){selected=index;level=levels[index];mirrors=level.mirrors.map(mirror=>({...mirror}));moves=0;$("#chapter").textContent=t("chapter",{n:Math.floor(index/5)+1});$("#stageName").textContent=t("garden",{n:index+1});show("battle");renderBoard()}
  function reflect(direction,rotation){if(rotation===0)return[1,0,3,2][direction];return[3,2,1,0][direction]}
  function trace(){const beam=[],seen=new Set();let cell=level.source,direction=level.startDir,hit=false;for(let step=0;step<80;step++){const marker=cell+":"+direction;if(seen.has(marker))break;seen.add(marker);beam.push(cell);if(cell===level.goal){hit=true;break}const mirror=mirrors.find(item=>item.cell===cell);if(mirror)direction=reflect(direction,mirror.rot);const row=Math.floor(cell/6),col=cell%6,nr=row+[-1,0,1,0][direction],nc=col+[0,1,0,-1][direction];if(nr<0||nr>5||nc<0||nc>5)break;cell=nr*6+nc}return{beam,hit}}
  function renderBoard(){const result=trace(),map=new Map(mirrors.map(mirror=>[mirror.cell,mirror])),board=$("#board");board.innerHTML="";for(let i=0;i<36;i++){const cell=document.createElement("button"),mirror=map.get(i);cell.className="cell"+(i===level.source?" source":"")+(i===level.goal?" goal":"")+(mirror?" mirror":"")+(result.beam.includes(i)?" beam":"")+(result.hit&&i===level.goal?" hit":"");cell.dataset.cell=i;cell.setAttribute("role","gridcell");if(mirror){cell.dataset.rot=mirror.rot;cell.setAttribute("aria-label",t("mirrorLabel",{row:Math.floor(i/6)+1,col:i%6+1}));cell.onclick=()=>{mirror.rot=(mirror.rot+1)%2;moves++;$("#status").textContent=t("beam");renderBoard();checkComplete()}}else cell.setAttribute("aria-label",i===level.source?t("kicker"):i===level.goal?t("complete"):t("boardLabel"));board.append(cell)}$("#beamState").textContent=result.hit?t("complete"):t("beamState");$("#status").textContent=result.hit?t("beam"):t("status")}
  function checkComplete(){if(!trace().hit)return;if(selected+2>unlocked){unlocked=Math.min(31,selected+2);write(key,String(unlocked))}$("#resultBody").textContent=t("resultBody",{n:selected+1,moves});$("#next").textContent=selected===29?t("allDone"):t("next");setTimeout(()=>$("#result").showModal(),160)}
  function hint(){const item=mirrors.find(mirror=>mirror.rot!==mirror.solution);if(!item)return;item.rot=item.solution;moves++;renderBoard();checkComplete()}
  function applyLocale(){document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr";document.title=t("title")+" | WeightPlay";document.querySelectorAll("[data-t]").forEach(node=>node.textContent=t(node.dataset.t));document.querySelectorAll("[data-t-aria]").forEach(node=>node.setAttribute("aria-label",t(node.dataset.tAria)));document.querySelectorAll("[data-t-alt]").forEach(node=>node.setAttribute("alt",t(node.dataset.tAlt)));$("#locale").value=locale;if(!$("#stage").hidden)renderStages();if(!$("#battle").hidden)renderBoard()}
  codes.forEach(code=>{const option=document.createElement("option");option.value=code;option.textContent=window.SUNBEAM_LOCALES[code].label;$("#locale").append(option)});$("#locale").onchange=e=>{locale=e.target.value;write("wp-locale",locale);try{window.WonderI18n?.setLocale?.(locale)}catch{}applyLocale()};
  $("#start").onclick=()=>show("stage");$("#stageGrid").addEventListener("wonder:stage-snap",event=>{const index=Number(event.detail?.index);if(Number.isInteger(index)&&index>=0)selectStage(index)});document.querySelectorAll("[data-back]").forEach(button=>button.onclick=()=>show(button.closest("#battle")?"stage":"main"));$("#hint").onclick=hint;$("#reset").onclick=()=>startLevel(selected);$("#retry").onclick=()=>{$("#result").close();startLevel(selected)};$("#next").onclick=()=>{$("#result").close();selected===29?show("stage"):startLevel(selected+1)};applyLocale();show("main");
})();
