/** Authored 10×10 animal mosaics. Dots are intentional negative space, never padding. */
export const MOSAICS=Object.freeze([
"........../.....AA.../...AAAAA../A.AAAA.AA./AAAAAAAABA/AAABBBBBBA/A.BBBBBBB./...BBBBB../.....BB.../..........",
"....AA..../...AAAA.../...A.AAB../..AAAAA.../.AABBBA.../AAABBBA.../.AAAAA..../...BB...../..B..B..../..........",
"..AA..AA../..AA..AA../..AB..BA../..AB..BA../.AAAAAAAA./.AA.AA.AA./.AABBBBAA./..ABBBBA../...A..A.../..AA..AA..",
"A........A/.A......A./AAA.BB.AAA/ABAABBAABA/ABBABBABBA/.AAABBAAA./.ABBBBBBA./..AABBAA../..A.BB.A../..........",
".AA....AA./ABBAAAABBA/ABAAAAAABA/.AAAAAAAA./.AA.AA.AA./.AABBBBAA./.AABB.BAA./..AABBAA../...AAAA.../..........",
"A........A/AA......AA/ABA....ABA/ABAAAAAABA/.AAAAAAAA./.AB.AA.BA./.ABBAABBA./..ABBBBA../...A..A.../....AA....",
"AA......AA/ABA....ABA/ABBAAAABBA/AAAAAAAAAA/AA.AAAA.AA/AABBBBBBAA/BBABBBBABB/..AA..AA../...AAAA.../..........",
"...CCC..../..CCCCC.../..C.C.C.../..CCBCC.../.CCBBBCC../CCCBBBCCC./C.CBBBC.C./..CCCCC.../..CC.CC.../.BBB.BBB..",
"AAA......./ABAA...A../ABBA..AAA./ABBA..A.A./.ABBAAAAA./..ABBAABA./...AABBBA./...AABBBA./....AAA.../...BB.BB..",
"....C.C.../.....C..../...AAAAA../..AAAAAAA./.AAAAA.AAA/.AAAAAAAAA/AAAABBBBBA/AABBBBBBA./BB.BBBB.../..........",
"A........A/AAA....AAA/AAAABBAAAA/ABBABBABBA/AB.ABBA.BA/ABBABBABBA/.AAADDAAA./.ACACACCA./..AAAAAA../..B....B..",
"..AAAAAA../AAABBBBAAA/AAABBBBAAA/AA.BBBB.AA/AAABBBBAAA/AAAB..BAAA/.AAADDAAA./..AADDAA../...AAAA.../..........",
"....CC..../....C.C.../.C.CCCC.C./CCACBBCACC/.CCBCCBCC./.CCCBCCCC./CCACBBCACC/.C.CCCC.C./....CC..../....C.....",
"..CCCC..../.CCCCCC.../CCCBBCCC../CCCBBC.CC./CCCBBCCCCC/.CCCCCC.CC/..CCCCC.CC/..CC.CC.CC/..CC.CCCCC/.BBB.BB...",
"....B.B.../....AAA.../...AA.AAB./....AAA.../....ABA.../....AAA.../.AAAAAA.../AABAABA.../A.A..AA.../..B..B....",
"A..B..B..A/ACACCACCAC/ACCACCACCA/.CCCCCCCC./.CCCDDCCC./..CCDDCC../...DDDD.../....DD..../...B..B.../..........",
".CCC..CCC./.C.C..C.C./.CCCCCCCC./CCCCCCCCCC/CCABBBBACC/.CCBBBBCC./..CCCCCC../.CCCCCCCC./CCC....CCC/C.C....C.C",
".....AA.../....A.AAA./....AAAAAB/...AABA.../..AABBA.../...ABBA.../....ABA.../....ABAAA./....A...A./.....AAA..",
"..BBBBBB../.BBBAABBB./BBAAAAAABB/BA.AAAA.AB/BAAABBAAAB/BAABB.BBAB/BBAABBAABB/.BBAAAABB./..BBBBBB../...B..B...",
"DD......DD/DCD....DCD/DCDD..DDCD/DDDDDDDDDD/.DD.DD.DD./.DCCDDCCD./..DCCCCD../...DCCD.../....DD..../..........",
"...EEEE.../..EEEEEE../.EEEEEEEE./.EE.EE.EE./.EEEBBEEE./..EEEEEE../.EE.EE.EE./EEB.EE.BEE/E.B.BB.B.E/..........",
"........AA/...A....AB/...AAA.AAB/..A.AAAAB./.AAAAAAA../AABBBBBA../ABBBAAAA../.BB.A..A../....B..B../..........",
"A........A/AA......AA/ABA.AA.ABA/ABBAAAABBA/.ABAAAABA./..AABBAA../...AAAA.../....AA..../...B..B.../..........",
"A.A....A.A/.AA....AA./..A....A../ABAAAAAABA/.AAAAAAAA./.AA.AA.AA./..ABBBBA../...A..A.../....AA..../..........",
".DD....DD./DDDBBBBDDD/DDBBBBBBDD/.BBDBBDBB./.BD.BB.DB./.BBDBBDBB./..BB..BB../...BBBB.../..DD..DD../..........",
"...D..D.../.D.DDDD.D./..DDBBDD../.DDDD.DDD./DDBBBBBBDD/.DDBBBBDD./..DDBBDD../.D.DDDD.D./...D..D.../..........",
"....AAA.../...A.ABB../...AAA.B../..AAAA..../.AACCA..../AACCCA..../AACCDA..../..CDDD..../..D..D..../..B..B....",
".AA....AA./ABAADDAABA/AAADDDDAAA/ADAAAAAADA/AA.AAAA.AA/ADDABBADDA/AAAB..BAAA/.AABBBBAA./..AAAAAA../..........",
"....DDD.../...DD.DDD./..DDDDDDDD/.DDDBDDD../DDDBBDD.../DDD.BD..../DDD......./.DD......./..DDD...../.DD.DD....",
"B...BB...B/BB.BBBB.BB/.BBBBBBBB./A.AAAAAA.A/AAAACCAAAA/AB.AAAA.BA/.ABBAABBA./..ABBBBA../...A..A.../....EE...."
]);
const TITLES={
 "en": "Little Fish|Songbird|Long-Eared Rabbit|Butterfly|Little Bear|Fox Face|Whiskered Cat|Penguin|Squirrel|Whale|Owl|Floppy-Eared Dog|Sea Turtle|Elephant|Giraffe|Peacock|Frog|Seahorse|Lion|Grey Wolf|Octopus|Running Fox|Soaring Eagle|Deer|Panda|Pufferfish|Parrot|Tiger|Dolphin|Fox Crest",
 "zh-Hant": "小魚|小鳥|長耳兔|蝴蝶|小熊|狐狸臉|貓咪|企鵝|松鼠|鯨魚|貓頭鷹|垂耳犬|海龜|大象|長頸鹿|孔雀|青蛙|海馬|獅子|灰狼|章魚|奔跑狐狸|展翅雄鷹|小鹿|熊貓|河豚|鸚鵡|老虎|海豚|狐狸徽章",
 "zh-Hans": "小鱼|小鸟|长耳兔|蝴蝶|小熊|狐狸脸|猫咪|企鹅|松鼠|鲸鱼|猫头鹰|垂耳犬|海龟|大象|长颈鹿|孔雀|青蛙|海马|狮子|灰狼|章鱼|奔跑狐狸|展翅雄鹰|小鹿|熊猫|河豚|鹦鹉|老虎|海豚|狐狸徽章",
 "ja": "小さな魚|小鳥|長耳ウサギ|チョウ|子グマ|キツネの顔|ネコ|ペンギン|リス|クジラ|フクロウ|垂れ耳の犬|ウミガメ|ゾウ|キリン|クジャク|カエル|タツノオトシゴ|ライオン|灰色オオカミ|タコ|走るキツネ|羽ばたくワシ|シカ|パンダ|フグ|オウム|トラ|イルカ|キツネの紋章",
 "ko": "작은 물고기|작은 새|긴귀 토끼|나비|아기 곰|여우 얼굴|고양이|펭귄|다람쥐|고래|부엉이|처진 귀 강아지|바다거북|코끼리|기린|공작|개구리|해마|사자|회색 늑대|문어|달리는 여우|날개 편 독수리|사슴|판다|복어|앵무새|호랑이|돌고래|여우 문장",
 "es": "Pececito|Pajarito|Conejo orejudo|Mariposa|Osito|Cara de zorro|Gato|Pingüino|Ardilla|Ballena|Búho|Perro orejudo|Tortuga marina|Elefante|Jirafa|Pavo real|Rana|Caballito de mar|León|Lobo gris|Pulpo|Zorro corriendo|Águila en vuelo|Ciervo|Panda|Pez globo|Loro|Tigre|Delfín|Emblema del zorro",
 "pt-BR": "Peixinho|Passarinho|Coelho orelhudo|Borboleta|Ursinho|Rosto de raposa|Gato|Pinguim|Esquilo|Baleia|Coruja|Cão orelhudo|Tartaruga marinha|Elefante|Girafa|Pavão|Sapo|Cavalo-marinho|Leão|Lobo-cinzento|Polvo|Raposa correndo|Águia em voo|Cervo|Panda|Baiacu|Papagaio|Tigre|Golfinho|Emblema da raposa",
 "fr": "Petit poisson|Petit oiseau|Lapin aux longues oreilles|Papillon|Ourson|Tête de renard|Chat|Manchot|Écureuil|Baleine|Hibou|Chien aux oreilles tombantes|Tortue marine|Éléphant|Girafe|Paon|Grenouille|Hippocampe|Lion|Loup gris|Pieuvre|Renard en course|Aigle en vol|Cerf|Panda|Poisson-globe|Perroquet|Tigre|Dauphin|Emblème du renard",
 "de": "Kleiner Fisch|Singvogel|Langohrhase|Schmetterling|Kleiner Bär|Fuchsgesicht|Katze|Pinguin|Eichhörnchen|Wal|Eule|Schlappohrhund|Meeresschildkröte|Elefant|Giraffe|Pfau|Frosch|Seepferdchen|Löwe|Grauwolf|Oktopus|Rennender Fuchs|Fliegender Adler|Hirsch|Panda|Kugelfisch|Papagei|Tiger|Delfin|Fuchswappen",
 "it": "Pesciolino|Uccellino|Coniglio dalle lunghe orecchie|Farfalla|Orsetto|Muso di volpe|Gatto|Pinguino|Scoiattolo|Balena|Gufo|Cane dalle orecchie lunghe|Tartaruga marina|Elefante|Giraffa|Pavone|Rana|Cavalluccio marino|Leone|Lupo grigio|Polpo|Volpe in corsa|Aquila in volo|Cervo|Panda|Pesce palla|Pappagallo|Tigre|Delfino|Stemma della volpe",
 "ru": "Рыбка|Птичка|Длинноухий кролик|Бабочка|Медвежонок|Мордочка лисы|Кошка|Пингвин|Белка|Кит|Сова|Вислоухая собака|Морская черепаха|Слон|Жираф|Павлин|Лягушка|Морской конёк|Лев|Серый волк|Осьминог|Бегущая лиса|Парящий орёл|Олень|Панда|Рыба-шар|Попугай|Тигр|Дельфин|Лисий герб",
 "hi": "छोटी मछली|नन्ही चिड़िया|लंबे कानों वाला खरगोश|तितली|नन्हा भालू|लोमड़ी का चेहरा|बिल्ली|पेंगुइन|गिलहरी|व्हेल|उल्लू|लटके कानों वाला कुत्ता|समुद्री कछुआ|हाथी|जिराफ़|मोर|मेंढक|समुद्री घोड़ा|शेर|भेड़िया|ऑक्टोपस|दौड़ती लोमड़ी|उड़ता गरुड़|हिरन|पांडा|पफर मछली|तोता|बाघ|डॉल्फ़िन|लोमड़ी का प्रतीक",
 "ar": "سمكة صغيرة|عصفور|أرنب طويل الأذنين|فراشة|دب صغير|وجه ثعلب|قطة|بطريق|سنجاب|حوت|بومة|كلب متدلي الأذنين|سلحفاة بحرية|فيل|زرافة|طاووس|ضفدع|فرس البحر|أسد|ذئب رمادي|أخطبوط|ثعلب يركض|عقاب محلّق|أيل|باندا|سمكة منتفخة|ببغاء|نمر|دلفين|شعار الثعلب"
};
export const MOSAIC_NAMES=Object.freeze(Object.fromEntries(Object.entries(TITLES).map(([locale,row])=>[locale,Object.freeze(row.split("|"))])));
