/** Mount persistent play roots once. Shared frame remains the sole chrome owner. */
export function mountScreens(d){
 if(document.getElementById('stageScreen'))return;
 const app=document.getElementById('app'),template=document.createElement('template');
 template.innerHTML=`<section id="stageScreen" data-wp-stage-workspace hidden><div id="stageCanvas" data-wp-standard-stage-screen data-wp-logical-stage-canvas data-wp-canvas-max-width="920" data-wp-stage-landscape-width="760" data-wp-stage-landscape-height="334" data-wp-stage-art="/games/pawflow/assets/poster.webp" style="--wp-stage-art:url('/games/pawflow/assets/poster.webp')">
 <header id="stageHeader"><button type="button" data-wp-return="stage" data-aria="back"></button><h2 data-wp-frame-title hidden></h2></header>
 <div id="stageContent"><div id="stageHud" data-wp-frame-info><div><span data-t="stages"></span><strong id="stageProgress"></strong></div><div><span data-t="stars"></span><strong id="stageStars"></strong></div></div>
 <section id="missionPane" role="tabpanel" aria-labelledby="missionTab"><div id="stageRail" class="stage-rail" data-wp-stage-rail data-wp-stage-settle-duration="340"></div></section>
 </div><nav data-wp-frame-stage-nav role="tablist"><button id="missionTab" type="button" role="tab" aria-controls="missionPane" aria-selected="true" data-wp-frame-stage-slot="stages" data-wp-frame-action="tab" data-t="stages"></button></nav></div></section>
 <section id="battleScreen" hidden><div id="battleCanvas" class="battle-shell" data-wp-battle-canvas-root data-wp-logical-battle-canvas data-wp-canvas-max-width="920" data-wp-battle-min-width="390" data-wp-battle-min-height="700" data-wp-battle-landscape-width="760" data-wp-battle-landscape-height="334">
 <header id="battleHeader"><button type="button" data-wp-return="battle" data-aria="back"></button><h2 data-wp-frame-title hidden></h2></header>
 <div id="battleContent"><div id="battleHud" data-wp-frame-info><div><span data-t="stages"></span><strong id="battleLevel"></strong></div><div><span data-t="remaining"></span><strong id="battlePixels"></strong></div><div><span data-t="dispatches"></span><strong id="battleDispatch"></strong></div></div>
 <p id="ruleLine"></p><div id="arenaFrame"><div id="arenaHost"></div><div id="arenaLabels"><span id="beltInfo"></span><span id="keyInfo"></span><span id="gateInfo"></span></div><progress id="boardProgress" max="1" value="1" data-aria="remaining"></progress></div>
 <div id="commands"><section class="supply-group"><div class="group-label"><span data-t="queue"></span><span id="supplyCount"></span></div><div id="supplyButtons"></div></section><section class="reserve-group"><div class="group-label"><span data-t="reserve"></span><span id="reserveCount"></span></div><div id="reserveButtons"></div></section><div class="utility-row"><button id="pause" type="button" data-wp-frame-action="secondary" data-t="pause"></button><button id="help" type="button" data-wp-frame-action="secondary">?</button><button id="hint" type="button" data-wp-frame-action="secondary" data-t="hint"></button><button id="rewind" type="button" data-wp-frame-action="secondary" data-t="rewind"></button></div><p id="feedback" role="status" aria-live="polite"></p></div></div>
 <section id="battleDialog" hidden role="dialog" aria-modal="true" aria-labelledby="dialogTitle" aria-describedby="dialogBody"><div class="dialog-card"><h2 id="dialogTitle"></h2><div id="dialogDetails" data-wp-scroll-owner><p id="dialogBody"></p><p id="dialogStats"></p></div><div class="dialog-actions"><button id="modalLeft" type="button" data-wp-frame-action="secondary"></button><button id="modalMiddle" type="button" data-wp-frame-action="primary"></button><button id="modalRight" type="button" data-wp-frame-action="secondary"></button></div></div></section></div></section>`;
 app.append(template.content);
 for(const n of app.querySelectorAll('[data-t]'))n.textContent=d[n.dataset.t];
 for(const n of app.querySelectorAll('[data-aria]'))n.setAttribute('aria-label',d[n.dataset.aria]);
 document.getElementById('help').setAttribute('aria-label',d.help);
}
