(() => {
  "use strict";
  const $ = (s) => document.querySelector(s), $$ = (s) => [...document.querySelectorAll(s)];
  const ASSET = "../../assets/", trial = new URLSearchParams(location.search).get("trial") === "1";
  const storageKey = "weightplay.animalRuneReels.v4", legacyStorageKey = "weightplay.animalRuneReels.v3", memory = new Map();
  const LOCALES = window.RUNE_REELS_LOCALES, localeKeys = Object.keys(LOCALES);
  const localeRouteSegments={en:"en","zh-Hant":"zh-tw","zh-Hans":"zh-cn",ja:"ja",ko:"ko",es:"es","pt-BR":"pt-br",fr:"fr",de:"de",it:"it",ru:"ru",hi:"hi",ar:"ar"};
  const HEROES = {
    lion:{name:"heroLion",img:"weightplay-character-boom-mane-lion-cutout.webp",stars:1,atk:15,def:4,heal:2,special:"specialLion",specialDesc:"specialLionDesc",mode:"allDamage",power:1.6,leader:"leaderLion",leaderDesc:"leaderLionDesc",leaderEffect:{type:"atk",value:.2}},
    turtle:{name:"heroTurtle",img:"weightplay-character-moss-shell-turtle-cutout.webp",stars:1,atk:8,def:14,heal:3,special:"specialTurtle",specialDesc:"specialTurtleDesc",mode:"reflect",power:2.6},
    rabbit:{name:"heroRabbit",img:"weightplay-character-rainbow-hop-mimi-clean-cutout.webp",stars:1,atk:5,def:5,heal:10,special:"specialRabbit",specialDesc:"specialRabbitDesc",mode:"surge",power:3.2},
    panda:{name:"heroPanda",img:"weightplay-character-drum-belly-panda-clean-cutout.webp",stars:1,atk:10,def:10,heal:6,special:"specialPanda",specialDesc:"specialPandaDesc",mode:"waveRage",power:1.2,waveStep:.25},
    fox:{name:"heroFox",img:"weightplay-character-spark-paw-fox-cutout.webp",stars:2,atk:16,def:7,heal:4,special:"specialFox",specialDesc:"specialFoxDesc",mode:"multihit",power:2.5,leader:"leaderFox",leaderDesc:"leaderFoxDesc",leaderEffect:{type:"attackRune",value:.15}},
    owl:{name:"heroOwl",img:"weightplay-character-moon-cap-owl-cutout.webp",stars:2,atk:10,def:8,heal:10,special:"specialOwl",specialDesc:"specialOwlDesc",mode:"drainAll",power:1.25,leader:"leaderOwl",leaderDesc:"leaderOwlDesc",leaderEffect:{type:"heal",value:.2}},
    otter:{name:"heroOtter",img:"weightplay-character-bubble-fin-otter-cutout.webp",stars:2,atk:13,def:9,heal:8,special:"specialOtter",specialDesc:"specialOtterDesc",mode:"resonance",power:1.4,leader:"leaderOtter",leaderDesc:"leaderOtterDesc",leaderEffect:{type:"allRune",value:.1}},
    rhino:{name:"heroRhino",img:"weightplay-character-gear-horn-rhino-cutout.webp",stars:2,atk:15,def:14,heal:3,special:"specialRhino",specialDesc:"specialRhinoDesc",mode:"bulwarkCharge",power:1.4,leader:"leaderRhino",leaderDesc:"leaderRhinoDesc",leaderEffect:{type:"def",value:.2}},
    astra:{name:"heroAstra",img:"animal-rune-reels-hero-prism-antler-astra.webp",stars:3,atk:18,def:18,heal:14,special:"specialAstra",specialDesc:"specialAstraDesc",mode:"aurora",power:1.6,leader:"leaderAstra",leaderDesc:"leaderAstraDesc",leaderEffect:{type:"hp",value:.2}},
    nyra:{name:"heroNyra",img:"animal-rune-reels-hero-frost-claw-nyra.webp",stars:3,atk:24,def:9,heal:7,special:"specialNyra",specialDesc:"specialNyraDesc",mode:"frostAll",power:2.2,leader:"leaderNyra",leaderDesc:"leaderNyraDesc",leaderEffect:{type:"special",value:.2}}
  };
  const MATERIALS = {
    runeDust:{name:"materialRuneDust",desc:"materialRuneDustDesc",img:"animal-rune-tactics-fx-dust-burst.webp"},
    sunShard:{name:"materialSunShard",desc:"materialSunShardDesc",img:"animal-rune-tactics-reward-rune-shard.webp"},
    moonCrystal:{name:"materialMoonCrystal",desc:"materialMoonCrystalDesc",img:"animal-crystal-survivor-xp-crystal.webp"},
    guardianCore:{name:"materialGuardianCore",desc:"materialGuardianCoreDesc",img:"animal-rift-salvage/rescue-core.webp"}
  };
  const RUNE_MATERIAL = {attack:"sunShard",special:"sunShard",echo:"sunShard",defense:"guardianCore",heal:"guardianCore",focus:"guardianCore",coin:"moonCrystal",luck:"moonCrystal",wild:"moonCrystal"};
  const RUNE_BALANCE = {attack:{base:.2,step:.05},defense:{base:.25,step:.05},heal:{base:.25,step:.05},wild:{base:2,step:.1},coin:{base:8,step:2},special:{base:1,step:.1},focus:{base:.12,step:.03},echo:{base:.25,step:.05},luck:{base:.08,step:.02},blank:{base:0,step:0}};
  const RUNES = {
    attack:{name:"runeAttack",desc:"runeAttackDesc",img:"animal-rune-reels/rune-attack.webp",color:"#ff9b42"},
    defense:{name:"runeDefense",desc:"runeDefenseDesc",img:"animal-rune-reels/rune-defense.webp",color:"#68dfff"},
    heal:{name:"runeHeal",desc:"runeHealDesc",img:"animal-rune-reels/rune-heal.webp",color:"#ff6f9e"},
    wild:{name:"runeWild",desc:"runeWildDesc",img:"animal-rune-reels/rune-wild.webp",color:"#fff28a"},
    coin:{name:"runeCoin",desc:"runeCoinDesc",img:"animal-rune-reels/rune-coin.webp",color:"#ffd45b"},
    special:{name:"runeSpecial",desc:"runeSpecialDesc",img:"animal-rune-reels/rune-special.webp",color:"#c77bff"},
    focus:{name:"runeFocus",desc:"runeFocusDesc",img:"animal-rune-reels/rune-focus.webp",color:"#62eaff"},
    echo:{name:"runeEcho",desc:"runeEchoDesc",img:"animal-rune-reels/rune-echo.webp",color:"#ffbd59"},
    luck:{name:"runeLuck",desc:"runeLuckDesc",img:"animal-rune-reels/rune-luck.webp",color:"#71ef8c"},
    blank:{name:"runeBlank",desc:"runeBlankDesc",img:"animal-rune-reels/dormant-rune-stone.webp",color:"#9ba4bb"}
  };
  const runeIds = Object.keys(RUNES), heroIds = Object.keys(HEROES);
  // Enemies threaten early, then repeat at different rhythms so target priority matters.
  const ENEMIES=[
    {id:"root",img:"animal-gearpack-expedition-enemy-root-guardian.webp",hp:1.35,damage:1.25,startCd:2,attackCd:2},
    {id:"boar",img:"animal-gearpack-expedition-enemy-armored-boar.webp",hp:1.5,damage:1.1,startCd:1,attackCd:2},
    {id:"crow",img:"animal-gearpack-expedition-enemy-crystal-crow.webp",hp:.9,damage:.9,startCd:1,attackCd:2},
    {id:"wolf",img:"animal-rune-tactics-enemy-wolf.webp",hp:1,damage:.8,startCd:1,attackCd:2},
    {id:"raven",img:"animal-rune-tactics-enemy-raven.webp",hp:.75,damage:1.5,startCd:2,attackCd:1}
  ];
  const chapterKeys=["chapter1","chapter2","chapter3","chapter4","chapter5","chapter6"];
  const materialIds=Object.keys(MATERIALS), missionTypes=["main","daily","event"];
  let locale, profile=load(), selectedStage=1, missionType="main", selectedMissionId="main-1", battle=null, currentHero="lion", selectedTeamSlot=null, characterReturnFocus=null, summonReturnFocus=null, windowFocused=document.hasFocus(), battleLifecycleSuspended=false, pausedBattleAnimations=[], leaveConfirmOpen=false, resultActionClaimed=false;
  let stageToastNode=null,stageToastTimer=0,stageToastStartedAt=0,stageToastRemaining=0,stageToastToken=0;
  const battleWaiters=new Set(),battleAnimations=new Set(),battleCancellation=Object.freeze({cancelled:true}),isForeground=()=>windowFocused&&!document.hidden,currentBattleSpeed=()=>battle?.speed===2?2:1;
  function syncBattleAnimationSpeed(){const speed=currentBattleSpeed();($('#battlePage')?.getAnimations({subtree:true})||[]).forEach(animation=>{if(animation.playbackRate!==speed)animation.playbackRate=speed})}
  function startBattleWait(waiter){if(waiter.timer||battleLifecycleSuspended||!isForeground())return;waiter.startedAt=performance.now();waiter.timer=setTimeout(()=>{waiter.timer=0;battleWaiters.delete(waiter);waiter.resolve()},waiter.remaining);requestAnimationFrame(syncBattleAnimationSpeed)}
  function setBattleSpeed(next){if(!battle||battle.ended)return;next=next===2?2:1;const prior=currentBattleSpeed();if(next===prior)return;const now=performance.now();for(const waiter of battleWaiters){if(waiter.timer){clearTimeout(waiter.timer);waiter.timer=0;waiter.remaining=Math.max(0,waiter.remaining-(now-waiter.startedAt))}waiter.remaining*=prior/next}battle.speed=next;profile.battleSpeed=next;save();battleWaiters.forEach(startBattleWait);syncBattleAnimationSpeed();renderBattle(false)}
  function suspendBattleLifecycle(){if(!battle||battle.ended||battleLifecycleSuspended)return;battleLifecycleSuspended=true;for(const waiter of battleWaiters){if(!waiter.timer)continue;clearTimeout(waiter.timer);waiter.timer=0;waiter.remaining=Math.max(0,waiter.remaining-(performance.now()-waiter.startedAt))}pausedBattleAnimations=($('#battlePage')?.getAnimations({subtree:true})||[]).filter(animation=>animation.playState==='running');pausedBattleAnimations.forEach(animation=>animation.pause())}
  function resumeBattleLifecycle(){if(!battleLifecycleSuspended||!isForeground()||leaveConfirmOpen)return;battleLifecycleSuspended=false;const animations=pausedBattleAnimations;pausedBattleAnimations=[];animations.forEach(animation=>{if(animation.playState==='paused')animation.play()});battleWaiters.forEach(startBattleWait)}
  function resetBattleLifecycle(){battleLifecycleSuspended=false;pausedBattleAnimations=[];for(const waiter of battleWaiters){if(waiter.timer)clearTimeout(waiter.timer);waiter.reject(battleCancellation)}battleWaiters.clear();for(const animation of battleAnimations)animation.cancel();battleAnimations.clear()}
  const soundLog=[];

  function read(k){try{return localStorage.getItem(k)}catch{return memory.get(k)||null}}
  function write(k,v){memory.set(k,v);try{localStorage.setItem(k,v)}catch{}}
  function saneInt(v,min,max,f){v=Number(v);return Number.isInteger(v)&&v>=min&&v<=max?v:f}
  function load(){
    try{
      const d=JSON.parse(read(storageKey)||read(legacyStorageKey)||"{}"); const cards={}; heroIds.forEach(id=>cards[id]={unlocked:id==="lion"||!!d.cards?.[id]?.unlocked,level:saneInt(d.cards?.[id]?.level,1,20,1),copies:saneInt(d.cards?.[id]?.copies,0,999,0)});
      const sourceSlots=Array.isArray(d.slots)?d.slots:Array.isArray(d.team)?d.team:["lion"],seen=new Set(),slots=Array(5).fill(null);sourceSlots.slice(0,5).forEach((id,index)=>{if(cards[id]?.unlocked&&!seen.has(id)){slots[index]=id;seen.add(id)}});if(!slots.some(Boolean))slots[0]="lion";
      const materials={};materialIds.forEach(id=>materials[id]=saneInt(d.materials?.[id],0,999999,id==="runeDust"?30:4));
      const runeLevels={};runeIds.forEach(id=>runeLevels[id]=id==="blank"?1:saneInt(d.runeLevels?.[id],1,5,1));
      const rewardClaims={};["daily-materials","event-moon","event-guardian"].forEach(id=>{if(typeof d.rewardClaims?.[id]==="string")rewardClaims[id]=d.rewardClaims[id].slice(0,10)});
      return {unlocked:saneInt(d.unlocked,1,30,1),coins:saneInt(d.coins,0,999999,300),diamonds:saneInt(d.diamonds,0,999999,300),materials,runeLevels,cards,slots,team:slots.filter(Boolean),best:Array.isArray(d.best)?d.best.slice(0,30):Array(30).fill(0),tutorial:!!d.tutorial,battleSpeed:saneInt(d.battleSpeed,1,2,1),rewardClaims};
    }catch{return loadDefault()}
  }
  function loadDefault(){const cards={};heroIds.forEach(id=>cards[id]={unlocked:id==="lion",level:1,copies:0});return{unlocked:1,coins:300,diamonds:300,materials:{runeDust:30,sunShard:4,moonCrystal:4,guardianCore:4},runeLevels:Object.fromEntries(runeIds.map(id=>[id,1])),cards,slots:["lion",null,null,null,null],team:["lion"],best:Array(30).fill(0),tutorial:false,battleSpeed:1,rewardClaims:{}}}
  function activeTeam(){return profile.slots.filter(Boolean)}
  function save(){profile.team=activeTeam();write(storageKey,JSON.stringify(profile))}
  function t(k){return LOCALES[locale]?.[k]??LOCALES.en?.[k]??k}
  function rewardPeriods(date=new Date()){const day=new Date(date),daily=day.toISOString().slice(0,10),monday=new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth(),day.getUTCDate()));monday.setUTCDate(monday.getUTCDate()-((monday.getUTCDay()+6)%7));return{daily,event:monday.toISOString().slice(0,10)}}
  function ownPeriodReward(mission){if(!Object.keys(mission.rewards||{}).length||!["daily","event"].includes(mission.type))return mission;const rewardPeriod=rewardPeriods()[mission.type];return{...mission,rewardPeriod,rewardClaimed:profile.rewardClaims?.[mission.id]===rewardPeriod}}
  function playSound(name){soundLog.push(name);window.WonderSound?.play(name)}
  function pickLocale(){const q=new URLSearchParams(location.search).get("lang"), shared=window.WonderI18n?.actualLocale?.(), saved=read(`${storageKey}.locale`)||read(`${legacyStorageKey}.locale`);return localeKeys.includes(q)?q:localeKeys.includes(shared)?shared:localeKeys.includes(saved)?saved:"en"}
  function fitStageCanvas(){const page=$("#stagePage"),canvas=page?.querySelector('.stage-canvas'),reserve=page?.querySelector('.ad-reserve');if(!canvas||!reserve)return;const viewport=window.visualViewport,width=Math.max(1,document.documentElement.clientWidth||innerWidth,viewport?.width||0),height=Math.max(1,document.documentElement.clientHeight||innerHeight,viewport?.height||0),availableWidth=Math.min(width,920),availableHeight=Math.max(1,height-56),landscape=availableWidth/availableHeight>=1.5,minWidth=landscape?760:390,minHeight=landscape?334:788,scale=Math.min(availableWidth/minWidth,availableHeight/minHeight),logicalWidth=availableWidth/scale,logicalHeight=availableHeight/scale,left=(width-availableWidth)/2;Object.assign(canvas.style,{position:'fixed',inset:'auto',left:`${left}px`,top:'0px',width:`${logicalWidth}px`,minWidth:`${logicalWidth}px`,maxWidth:`${logicalWidth}px`,height:`${logicalHeight}px`,minHeight:`${logicalHeight}px`,maxHeight:`${logicalHeight}px`,margin:'0',transform:`scale(${scale})`,transformOrigin:'top left'});Object.assign(reserve.style,{position:'fixed',inset:'auto',left:`${left}px`,top:`${availableHeight}px`,width:`${availableWidth}px`,height:'56px',margin:'0',transform:'none'})}
  function show(id){if(locale){document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr"}["mainPage","stagePage","battlePage"].forEach(x=>$("#"+x).hidden=x!==id);if(id==="mainPage"&&$("#mainProgress"))$("#mainProgress").textContent=`Stage ${profile.unlocked} / 30`;if(id==='stagePage')requestAnimationFrame(fitStageCanvas);else clearStageToast()}
  function setBattleInert(value){['.battle-head','#arena','.reel-console'].forEach(s=>{const n=$(s);if(n)n.inert=value})}
  function setStageModalInert(value){const canvas=$(".stage-canvas");if(canvas)canvas.inert=value}
  function closeHero(){
    const modal=$("#characterModal");
    if(modal.hidden)return;
    modal.hidden=true;
    setStageModalInert(false);
    const fallback=$(`.roster-card[data-hero="${currentHero}"]`);
    const target=characterReturnFocus?.isConnected?characterReturnFocus:fallback;
    characterReturnFocus=null;
    target?.focus();
  }
  function openBattleModal(id,focusSelector){if(battle){battle.auto=false;renderBattle(false)}setBattleInert(true);const modal=$(id);modal.hidden=false;setTimeout(()=>(focusSelector?modal.querySelector(focusSelector):modal.querySelector('button:not([disabled]):not([hidden])'))?.focus({preventScroll:true}),0)}
  function closeBattleModal(id){$(id).hidden=true;setBattleInert(false);$("#battleBack")?.focus()}
  function openLeaveConfirmation(){if(!battle||battle.ended||leaveConfirmOpen)return;leaveConfirmOpen=true;suspendBattleLifecycle();openBattleModal('#leaveConfirm')}
  function continueBattle(){if(!leaveConfirmOpen)return;leaveConfirmOpen=false;closeBattleModal('#leaveConfirm');resumeBattleLifecycle()}
  function syncSoundToggle(){const button=$("#soundToggle"),muted=window.WonderSound?.isMuted?.()===true;if(!button)return;button.textContent=muted?"🔇":"🔊";button.title=t("sound");button.setAttribute("aria-label",t(muted?"enableSound":"disableSound"));button.setAttribute("aria-pressed",String(muted))}
  function applyLocale(){document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr";document.title=`${t("title")} | WeightPlay`;$$('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));$$('[data-i18n-aria]').forEach(n=>n.setAttribute("aria-label",t(n.dataset.i18nAria)));syncSoundToggle();renderStage();if(battle)renderBattle()}
  function populateLocales(){const s=$("#localeSelect");s.innerHTML="";localeKeys.forEach(k=>{const o=document.createElement("option");o.value=k;o.textContent=LOCALES[k].name;o.selected=k===locale;s.append(o)})}
  function stats(id){const h=HEROES[id],lv=profile.cards[id].level,m=1+(lv-1)*.18;return{atk:Math.round(h.atk*m),def:Math.round(h.def*m),heal:Math.round(h.heal*m)}}
  function leaderEffect(type){const id=profile.slots[0],effect=id&&HEROES[id].leaderEffect;return effect?.type===type?effect.value:0}
  function combatStats(id){const s=stats(id);return{atk:Math.round(s.atk*(1+leaderEffect('atk'))),def:Math.round(s.def*(1+leaderEffect('def'))),heal:Math.round(s.heal*(1+leaderEffect('heal')))}}
  function totals(){return activeTeam().reduce((a,id)=>{const s=combatStats(id);a.def+=s.def;a.heal+=s.heal;return a},{def:0,heal:0})}
  function addDefenseBonus(amount){battle.defenseBonus=(battle.defenseBonus||0)+amount;battle.defenseDisplay=totals().def+battle.defenseBonus;battle.defenseBuff=battle.defenseBonus>0;return battle.defenseDisplay}
  function addFocus(amount){battle.focus=Math.min(.9,(battle.focus||0)+amount);return battle.focus}
  function runeEffectScale(){return 1+leaderEffect('allRune')+(battle?.runeAmp||0)}
  function requiredCopies(level){return level}
  function runeValue(id,level=profile.runeLevels[id]){const value=RUNE_BALANCE[id];return value.base+(level-1)*value.step}
  function linePower(line,type){return line.line&&line.type===type?runeValue('wild'):1}

  function waveEnemyCount(n,wave){return n%5===0?3:1+(n+wave)%3}
  function waveEnemies(mission,wave){const count=waveEnemyCount(mission.stage,wave),typeOffset={main:0,daily:2,event:4}[mission.type]||0,start=(mission.stage*2+wave*3+typeOffset)%ENEMIES.length;return Array.from({length:count},(_,index)=>ENEMIES[(start+index)%ENEMIES.length])}
  function mainWaves(n){return n===30?10:n%5===0?5:3}
  const EVENT_DAYS={moon:[0,1,3,5],guardian:[2,4,6]};
  function weekdayNames(days){const formatter=new Intl.DateTimeFormat(locale||'en',{weekday:'short',timeZone:'UTC'});return days.map(day=>formatter.format(new Date(Date.UTC(2024,0,7+day)))).join(' · ')}
  function missions(type=missionType,weekday=new Date().getDay()){
    if(type==="main")return Array.from({length:30},(_,i)=>{const n=i+1;return{id:`main-${n}`,type,stage:n,name:t(chapterKeys[Math.floor(i/5)]),label:`${t(n%5===0?'guardian':'stage')} ${n}`,waves:mainWaves(n),locked:n>profile.unlocked,rewards:{runeDust:2+Math.floor(n/5)}}});
    if(type==="daily")return[{id:"daily-gold",type,stage:Math.max(1,profile.unlocked),name:t("dailyGold"),label:t("dailyMissions"),waves:3,locked:false,coinBonus:3,rule:"dailyCoinBonus",rewards:{}},{id:"daily-materials",type,stage:Math.max(5,profile.unlocked),name:t("dailyMaterials"),label:t("dailyMissions"),waves:5,locked:false,rewards:{runeDust:24,sunShard:2,guardianCore:2}}].map(ownPeriodReward);
    return[{id:"event-moon",type,stage:18,name:t("eventMoon"),label:t("eventMissions"),waves:7,locked:!EVENT_DAYS.moon.includes(weekday),schedule:`${t('weekly')} · ${weekdayNames(EVENT_DAYS.moon)}`,rewards:{diamonds:40,moonCrystal:5,runeDust:15}},{id:"event-guardian",type,stage:30,name:t("eventGuardian"),label:t("eventMissions"),waves:10,locked:!EVENT_DAYS.guardian.includes(weekday),schedule:`${t('weekly')} · ${weekdayNames(EVENT_DAYS.guardian)}`,rewards:{diamonds:60,guardianCore:4,sunShard:4}}].map(ownPeriodReward);
  }
  function currentMission(){return missions(missionType).find(x=>x.id===selectedMissionId)||missions(missionType)[0]}
  function rewardText(rewards){return Object.entries(rewards).map(([id,n])=>`${id==='coins'?t('coins'):id==='diamonds'?t('diamonds'):t(MATERIALS[id].name)} ×${n}`).join(" · ")}
  function renderStages(){
    const rail=$("#stageRail");rail.innerHTML="";missions().forEach((m,index)=>{const card=document.createElement("button"),rewards=m.rewardClaimed?"":rewardText(m.rewards),rule=m.rewardClaimed?t("rewardClaimed"):m.rule?t(m.rule):"",summary=rule||`${t("waves")} ${m.waves}${rewards?` · ${rewards}`:""}`;card.className=`stage-card${m.locked?" locked":""}`;card.dataset.mission=m.id;card.dataset.stage=m.stage;card.dataset.stageIndex=index;card.dataset.waves=m.waves;card.setAttribute("aria-label",[m.label,m.name,`${t("waves")} ${m.waves}`,rewards,rule,m.schedule,m.locked?t("locked"):""].filter(Boolean).join(". "));
      card.innerHTML=`<small>${m.label}</small><h3>${m.name}</h3><div class="stage-rift-mark"><img src="${ASSET}${RUNES.wild.img}" alt=""></div><p>${summary}</p>${m.schedule?`<span class="mission-schedule">${m.schedule}</span>`:""}<span class="monster-chip">${m.locked?t("locked"):m.type==='main'&&profile.best[m.stage-1]?"★".repeat(profile.best[m.stage-1]):t("readyStage")}<b>${t('waves')} ${m.waves}</b></span>`;
      card.onclick=()=>{selectedMissionId=m.id;selectedStage=m.stage;centerMission(m.id);if(!m.locked)startBattle()};rail.append(card)
    });centerMission(selectedMissionId,false)
  }
  function markCenteredMission(card){$$('.stage-card').forEach(c=>{const current=c===card;c.classList.toggle('centered',current);if(current)c.setAttribute('aria-current','true');else c.removeAttribute('aria-current')})}
  function centerMission(id,smooth=true){const card=$(`.stage-card[data-mission="${id}"]`),rail=$("#stageRail");if(!card)return;selectedMissionId=id;selectedStage=+card.dataset.stage;markCenteredMission(card);rail.scrollTo({left:card.offsetLeft-rail.offsetLeft-(rail.clientWidth-card.offsetWidth)/2,behavior:smooth?'smooth':'auto'});updateEnter()}
  function centerStage(n,smooth=true){const card=$(`.stage-card[data-stage="${n}"]`);if(card)centerMission(card.dataset.mission,smooth)}
  function syncCenteredStage(){const rail=$("#stageRail"),cards=$$('.stage-card');if(!cards.length||!rail.getClientRects().length)return;const cx=rail.getBoundingClientRect().left+rail.getBoundingClientRect().width/2,card=cards.reduce((a,c)=>Math.abs(c.getBoundingClientRect().left+c.getBoundingClientRect().width/2-cx)<Math.abs(a.getBoundingClientRect().left+a.getBoundingClientRect().width/2-cx)?c:a);selectedMissionId=card.dataset.mission;selectedStage=+card.dataset.stage;markCenteredMission(card);updateEnter()}
  function updateEnter(){const locked=currentMission().locked;$("#enterBattle").disabled=locked;$("#enterBattle").textContent=locked?t("locked"):t("enter")}
  function setMissionType(type){if(!missionTypes.includes(type))return;missionType=type;const list=missions(type),first=type==='event'?(list.find(m=>!m.locked)||list[0]):list[0],heading=type==='main'?'mainMissions':type==='daily'?'dailyMissions':'eventMissions';selectedMissionId=first.id;selectedStage=first.stage;$$('.mission-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.missionType===type));$("#missionHeading").textContent=t(heading);$("#campaignProgress").textContent=type==='main'?`${profile.unlocked} / 30`:t(heading);renderStages()}
  function renderTeamSlots(){const box=$("#teamSlots");box.innerHTML=profile.slots.map((id,index)=>`<button class="team-slot${id?' filled':''}${index===0?' leader-slot':''}${selectedTeamSlot===index?' selected':''}" data-team-slot="${index}" aria-label="${t('teamSlot')} ${index+1}${index===0?` · ${t('leaderAbility')}`:''}">${id?`<img src="${ASSET}${HEROES[id].img}" alt=""><b>${index===0?'♛ ':''}${t(HEROES[id].name)}</b>`:`<span>＋</span><b>${t('teamSlot')} ${index+1}</b>`}</button>`).join('');$$('[data-team-slot]').forEach(button=>button.onclick=()=>{selectedTeamSlot=+button.dataset.teamSlot;renderTeamSlots();$("#teamSlotHint").textContent=t('chooseHeroForSlot')})}
  function assignHeroToSlot(id){if(selectedTeamSlot===null){const modal=$("#characterModal");characterReturnFocus=document.activeElement;modal.setAttribute("role","dialog");modal.setAttribute("aria-modal","true");modal.setAttribute("aria-labelledby","characterName");modal.hidden=false;openHero(id);$("#characterClose").focus();return}profile.slots=profile.slots.map(hero=>hero===id?null:hero);profile.slots[selectedTeamSlot]=id;selectedTeamSlot=null;save();renderRoster();$("#teamSlotHint").textContent=t('chooseTeamSlot')}
  function renderRoster(){
    renderTeamSlots();const grid=$("#rosterGrid");grid.innerHTML="";heroIds.filter(id=>profile.cards[id].unlocked).forEach(id=>{const c=profile.cards[id],s=stats(id),need=requiredCopies(c.level),shown=Math.min(c.copies,need),b=document.createElement('button');b.className=`roster-card${profile.slots.includes(id)?' active':''}`;b.dataset.hero=id;b.innerHTML=`${profile.slots.includes(id)?'<span class="active-dot">✓</span>':''}<img src="${ASSET}${HEROES[id].img}" alt=""><span class="hero-stars">${"★".repeat(HEROES[id].stars)}</span><b>${t(HEROES[id].name)}</b><small>${t('level')} ${c.level} · ${t('attackShort')} ${s.atk}</small><span class="roster-copy-progress" style="--copy-progress:${shown/need*100}%" role="progressbar" aria-label="${t('upgrade')} ${shown} / ${need}" aria-valuemin="0" aria-valuemax="${need}" aria-valuenow="${shown}"><i></i><em>[ ${shown} / ${need} ]</em></span>`;b.onclick=()=>assignHeroToSlot(id);grid.append(b)});
    const x=totals();$("#teamCount").textContent=`${activeTeam().length} / 5`;$("#teamTotals").textContent=`${t('teamDefense')} ${x.def} · ${t('teamHealing')} ${x.heal}`
  }
  function renderMaterials(){const g=$("#materialGrid");g.innerHTML=materialIds.map(id=>`<article class="material-card"><img src="${ASSET}${MATERIALS[id].img}" alt=""><div><b>${t(MATERIALS[id].name)}</b><small>${t(MATERIALS[id].desc)}</small></div><strong>×${profile.materials[id]}</strong></article>`).join("");$("#packCoins").textContent=profile.coins;$("#packDiamonds").textContent=profile.diamonds}
  function runeCost(id){const level=profile.runeLevels[id],material=RUNE_MATERIAL[id];return material?{runeDust:level*10,[material]:level}:null}
  function upgradeRune(id){const cost=runeCost(id);if(!cost||profile.runeLevels[id]>=5)return;const can=Object.entries(cost).every(([m,n])=>profile.materials[m]>=n);if(!can)return toast(t('needMaterials'));const restoreFocus=document.activeElement?.dataset.upgradeRune===id;Object.entries(cost).forEach(([m,n])=>profile.materials[m]-=n);profile.runeLevels[id]++;save();renderStage();if(restoreFocus)requestAnimationFrame(()=>{const same=$(`[data-upgrade-rune="${id}"]`),next=same&&!same.disabled?same:$$('[data-upgrade-rune]:not([disabled])')[0];next?.focus({preventScroll:true})})}
  function runeEffectText(id,level){const value=runeValue(id,level),pct=Math.round(value*100);if(id==='attack')return`+${pct}% ATK / ${t('perRune')} · ${t('lineX2')}`;if(id==='defense')return`+${pct}% DEF → SHIELD / ${t('perRune')} · ${t('lineX2')}`;if(id==='heal')return`+${pct}% HEAL / ${t('perRune')} · ${t('lineX2')}`;if(id==='coin')return`+${value} ${t('coins')} / ${t('perRune')} · ${t('lineX2')}`;if(id==='focus')return`-${pct}% DMG / ${t('perRune')} · ${t('lineX2')}`;if(id==='echo')return`${pct}% DMG ECHO / ${t('perRune')} · ${t('lineX2')}`;if(id==='luck')return`+${pct}% ATK / ${t('perRune')} · ${t('lineX2')}`;if(id==='special')return`×${value.toFixed(1)} SP / ${t('perRune')} · ${t('lineX2')}`;if(id==='wild')return`LINE ×${value.toFixed(1)}`;return"0"}
  function renderRunes(){const g=$("#runeGuide");g.innerHTML=runeIds.map(id=>{const level=profile.runeLevels[id],cost=runeCost(id),max=id==='blank'||level>=5;return`<article class="rune-guide-card"><img src="${ASSET}${RUNES[id].img}" alt=""><b>${t(RUNES[id].name)}</b><span>${t('runeLevel')} ${level} / 5</span><small>${t(RUNES[id].desc)}</small><div class="rune-values"><strong>${t('currentEffect')}</strong><i>${runeEffectText(id,level)}</i>${max||id==='blank'?'':`<strong>${t('nextEffect')}</strong><i>${runeEffectText(id,level+1)}</i>`}</div>${id==='blank'?'':`<button data-upgrade-rune="${id}" ${max?'disabled':''}>${max?t('maxLevel'):`${t('upgradeRune')} · ${rewardText(cost)}`}</button>`}</article>`}).join("");$$('[data-upgrade-rune]').forEach(b=>{b.addEventListener('keydown',event=>{if(event.repeat&&(event.key==='Enter'||event.key===' '))event.preventDefault()});b.onclick=()=>upgradeRune(b.dataset.upgradeRune)})}
  function renderStage(){if(!$("#stageRail"))return;$("#missionHeading").textContent=t(missionType==='main'?'mainMissions':missionType==='daily'?'dailyMissions':'eventMissions');$("#campaignProgress").textContent=missionType==='main'?`${profile.unlocked} / 30`:missionType==='daily'?t('dailyMissions'):t('eventMissions');$("#coinCount").textContent=profile.coins;$("#diamondCount").textContent=profile.diamonds;renderStages();renderMaterials();renderRoster();renderRunes();updateEnter()}
  function setTab(name){$$('.stage-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['stages','pack','team','summon','runes'].forEach(x=>$("#"+x+"Panel").hidden=x!==name);$("#enterBattle").hidden=name!=="stages";requestAnimationFrame(()=>{fitStageCanvas();if(name==='stages')centerMission(selectedMissionId,false)})}
  function openHero(id){const modal=$("#characterModal"),opening=modal.hidden;if(opening)characterReturnFocus=document.activeElement;currentHero=id;const h=HEROES[id],c=profile.cards[id],s=stats(id),need=requiredCopies(c.level),progress=$("#duplicateProgress"),leader=$("#leaderDetail");$("#characterArt").src=ASSET+h.img;$("#characterStars").textContent="★".repeat(h.stars);$("#characterName").textContent=t(h.name);$("#characterStats").textContent=`${t('attackShort')} ${s.atk} · ${t('defenseShort')} ${s.def} · ${t('healingShort')} ${s.heal}`;$("#characterSpecial").textContent=t(h.special);$("#characterSpecialDesc").textContent=t(h.specialDesc);leader.hidden=!h.leader;$("#characterLeader").textContent=h.leader?t(h.leader):t('leaderNone');$("#characterLeaderDesc").textContent=h.leader?t(h.leaderDesc):"";progress.hidden=false;const shown=Math.min(c.copies,need);progress.querySelector('span').textContent=`${t('upgrade')} ${shown} / ${need}`;progress.style.setProperty('--upgrade-progress',`${shown/need*100}%`);progress.setAttribute('aria-valuemax',need);progress.setAttribute('aria-valuenow',shown);progress.setAttribute('aria-valuetext',`${t('upgrade')} ${shown} / ${need}`);$("#equipBtn").hidden=false;$("#equipBtn").textContent=profile.slots.includes(id)?t('removeTeam'):t('addTeam');$("#upgradeBtn").hidden=false;$("#upgradeBtn").disabled=c.copies<need;$("#upgradeBtn").textContent=t('upgrade');$("#characterClose").setAttribute("aria-label",`${t('back')} · ${t(h.name)}`);modal.hidden=false;setStageModalInert(true);if(opening)requestAnimationFrame(()=>$("#characterClose").focus())}
  function rarityPick(pool){const stars=pool==='diamond'?(Math.random()<.8?2:3):(Math.random()<.8?1:2),choices=heroIds.filter(id=>HEROES[id].stars===stars);return choices[Math.floor(Math.random()*choices.length)]}
  function closeSummonResult(){const result=$("#summonResult");if(result.hidden)return;result.hidden=true;setStageModalInert(false);const target=summonReturnFocus;summonReturnFocus=null;requestAnimationFrame(()=>target?.focus?.({preventScroll:true}))}
  function summon(pool='coin',forced){const result=$("#summonResult");if(!result.hidden)return;const currency=pool==='diamond'?'diamonds':'coins';if(profile[currency]<100)return toast(t(pool==='diamond'?'needDiamonds':'needCoins'));if(forced&&!heroIds.includes(forced))return;summonReturnFocus=document.activeElement;profile[currency]-=100;const id=forced||rarityPick(pool),c=profile.cards[id],fresh=!c.unlocked;c.unlocked=true;if(!fresh)c.copies++;save();renderStage();playSound('success');$("#summonArt").src=ASSET+HEROES[id].img;$("#summonName").textContent=`${"★".repeat(HEROES[id].stars)} ${t(HEROES[id].name)}`;$("#summonCopy").textContent=fresh?t('newHero'):`${t('duplicateCards')} ${c.copies} / ${requiredCopies(c.level)}`;result.setAttribute("role","dialog");result.setAttribute("aria-modal","true");result.setAttribute("aria-labelledby","summonName");result.hidden=false;setStageModalInert(true);$("#summonClose").focus({preventScroll:true})}

  function buildEnemies(mission=currentMission(),wave=1){const baseDamage=10+Math.ceil(mission.stage*1.2)+Math.floor((wave-1)*1.5),earlyDamageScale=mission.type==='main'?Math.min(1,.6+mission.stage*.08):1;return waveEnemies(mission,wave).map((type,i)=>{const hp=Math.round((65+mission.stage*13+i*8)*(1+(wave-1)*.12)*type.hp),damage=Math.max(1,Math.round(baseDamage*type.damage*earlyDamageScale));return{id:type.id,img:type.img,hp,maxHp:hp,name:`${t('guardian')} ${i+1}`,slot:i,startCd:type.startCd,attackCd:type.attackCd,cd:type.startCd,damage,damageScale:type.damage,hpScale:type.hp,attacking:false}})}
  function startBattle(){const mission=currentMission(),team=activeTeam();if(mission.locked||!team.length)return;resetBattleLifecycle();const maxHp=Math.round(180*(1+leaderEffect('hp')));battle={mission:{...mission,rewards:{...mission.rewards}},wave:1,totalWaves:mission.waves,hp:maxHp,maxHp,shield:0,coins:0,turn:0,busy:false,ended:false,auto:false,speed:profile.battleSpeed===2?2:1,reels:['blank','blank','blank'],enemies:buildEnemies(mission,1),targetIndex:0,forced:null,currentPhase:null,phaseLog:[],stopLog:[],lastResolution:null,attackDisplay:null,attackBonusActive:false,attackCharge:0,runeAmp:0,reflect:0,defenseBonus:0,defenseDisplay:null,defenseBuff:false,focus:0};show('battlePage');setBattleInert(false);renderBattle();if(!profile.tutorial)openBattleModal('#tutorial')}
  function living(){return battle.enemies.filter(e=>e.hp>0)}
  function currentTargetIndex(){if(battle.enemies[battle.targetIndex]?.hp>0)return battle.targetIndex;const next=battle.enemies.findIndex(e=>e.hp>0);battle.targetIndex=Math.max(0,next);return battle.targetIndex}
  function selectTarget(index){if(!battle||battle.busy||battle.enemies[index]?.hp<=0)return;battle.targetIndex=index;renderEnemies()}
  function renderEnemies(){const box=$("#enemySquad"),slotCount=Math.max(1,battle.enemies.length);box.innerHTML="";box.dataset.count=slotCount;box.style.setProperty('--enemy-count',slotCount);const target=currentTargetIndex();battle.enemies.forEach((e,i)=>{const d=document.createElement('button');d.type='button';d.className=`enemy-unit${e.hp<=0?' defeated':''}${i===target&&e.hp>0?' targeted':''}${e.cd===0&&e.hp>0?' enemy-ready':''}${e.attacking?' enemy-attacking':''}`;d.dataset.enemy=i;d.dataset.slot=e.slot;d.disabled=e.hp<=0;d.setAttribute('aria-pressed',String(i===target&&e.hp>0));d.setAttribute('aria-label',`${t('targetEnemy')} ${e.name}, ${t('hp')} ${Math.max(0,e.hp)} / ${e.maxHp}, ${t('cooldown')} ${e.cd}`);d.innerHTML=`<span class="target-marker" aria-hidden="true"></span><span class="enemy-cd">CD:${e.cd}</span><img src="${ASSET}${e.img}" alt=""><span class="hpbar"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i><span>${Math.max(0,e.hp)} / ${e.maxHp}</span></span>`;d.onclick=()=>selectTarget(i);box.append(d)})}
  function renderParty(){const box=$("#partyHeroes");box.innerHTML=activeTeam().map(id=>{const s=combatStats(id),shown=battle?.attackDisplay?.[id]??s.atk,boosted=!!battle?.attackBonusActive;return`<div class="party-hero${boosted?' attack-boosted':''}" data-hero="${id}"><img src="${ASSET}${HEROES[id].img}" alt=""><small>${t('attackShort')} ${shown}</small></div>`}).join('')}
  function syncPlayerHealth(){if(!battle)return;const healthBar=$(".summoner-hp");$("#playerHpFill").style.width=`${Math.max(0,battle.hp/battle.maxHp*100)}%`;$("#playerHpText").textContent=`${battle.hp} / ${battle.maxHp}`;healthBar.setAttribute("role","progressbar");healthBar.setAttribute("aria-valuemin","0");healthBar.setAttribute("aria-valuemax",String(battle.maxHp));healthBar.setAttribute("aria-valuenow",String(battle.hp));healthBar.setAttribute("aria-label",`${t("hp")}: ${battle.hp} / ${battle.maxHp}`)}
  function renderBattle(reels=true){if(!battle)return;renderEnemies();renderParty();const sum=totals(),shownDefense=battle.defenseDisplay??sum.def,speed=currentBattleSpeed(),speedBtn=$("#speedBtn");$("#battleStage").textContent=battle.mission.type==='main'?`${t('stage')} ${battle.mission.stage}`:battle.mission.name;$("#waveText").textContent=`${t('wave')} ${battle.wave} / ${battle.totalWaves}`;syncPlayerHealth();$("#shieldText").textContent=battle.shield;$("#defenseTotal").textContent=shownDefense;$("#defenseMetric").classList.toggle('defense-buffed',!!battle.defenseBuff);$("#healTotal").textContent=sum.heal;$("#battleCoins").textContent=battle.coins;$("#spinBtn").disabled=battle.busy||battle.ended;$("#autoBtn").classList.toggle('on',battle.auto);$("#autoBtn small").textContent=t(battle.auto?'autoOn':'autoOff');speedBtn.textContent=`x${speed}`;speedBtn.classList.toggle('speed-2x',speed===2);speedBtn.setAttribute('aria-pressed',String(speed===2));speedBtn.setAttribute('aria-label',`${t('battleSpeed')}: x${speed}`);speedBtn.title=`${t('battleSpeed')}: x${speed}`;if(reels)renderReels()}
  function cell(id){return`<div class="reel-cell" data-symbol="${id}"><img src="${ASSET}${RUNES[id].img}" alt="${t(RUNES[id].name)}"></div>`}
  function renderReels(){const box=$("#reels");box.innerHTML=battle.reels.map((id,i)=>`<div class="reel" data-reel="${i}" data-symbol="${id}" aria-label="${t(RUNES[id].name)}"><div class="reel-strip">${cell(id)}</div></div>`).join('')}
  function targets(){if(trial&&battle.forced)return battle.forced.slice();return [0,1,2].map(()=>runeIds[Math.floor(Math.random()*runeIds.length)])}
  function seededSeq(target,index){const n=12+index*3,arr=[target];for(let i=1;i<n;i++)arr.push(runeIds[(battle.turn*7+i*3+index*5)%runeIds.length]);return arr}
  async function animateReel(index,target){const owner=battle,reel=$(`.reel[data-reel="${index}"]`),strip=reel.querySelector('.reel-strip'),seq=seededSeq(target,index);strip.innerHTML=seq.map(cell).join('');reel.classList.add('spinning');const h=reel.clientHeight,start=-(seq.length-1)*h,dur=(matchMedia('(prefers-reduced-motion: reduce)').matches?260:920)+index*260;owner.spinFrames[index]=seq.length;const a=strip.animate([{transform:`translateY(${start}px)`},{transform:'translateY(6px)',offset:.94},{transform:'translateY(0)'}],{duration:dur,easing:'cubic-bezier(.12,.72,.16,1)',fill:'forwards'});battleAnimations.add(a);a.playbackRate=currentBattleSpeed();try{await a.finished}catch(error){if(!owner.cancelled)throw error;throw battleCancellation}finally{battleAnimations.delete(a)}reel.classList.remove('spinning');owner.reels[index]=target;owner.stopLog.push({index,at:performance.now()});playSound('click')}
  function lineInfo(){const non=battle.reels.filter(x=>x!=='wild'),types=[...new Set(non)],line=types.length===1&&non.length>0&&types[0]!=="blank";return{line,type:line?types[0]:null,count:line?3:0,factor:line?6:0}}
  function counts(){const c=Object.fromEntries(runeIds.map(x=>[x,0]));battle.reels.forEach(x=>c[x]++);const l=lineInfo();if(l.line)c[l.type]=3;return{c,line:l}}
  async function spin(){if(!battle||battle.busy||battle.ended||!isForeground())return;try{battle.busy=true;battle.turn++;battle.currentPhase='spinning';battle.phaseLog=[];battle.stopLog=[];battle.spinFrames=[];battle.attackDisplay=null;battle.attackBonusActive=false;battle.runeAmp=0;clearRuneEffects();playSound('start');$("#spinBtn").disabled=true;$("#comboBanner").textContent=t('spinningDown');const ts=targets();battle.forced=null;await Promise.all(ts.map((x,i)=>animateReel(i,x)));battle.reels=ts;renderReels();await resolve();if(!living().length&&battle.hp>0&&battle.wave<battle.totalWaves)await advanceWave();else if(living().length&&battle.hp>0)await enemyTurn();finishTurn()}catch(error){if(error!==battleCancellation)throw error}}
  async function advanceWave(){battle.currentPhase='wave';const arena=$("#arena"),banner=$("#waveTransition");arena.classList.add('wave-out');await wait(380);battle.wave++;battle.targetIndex=0;battle.enemies=buildEnemies(battle.mission,battle.wave);banner.querySelector('span').textContent=`${t('wave')} ${battle.wave} / ${battle.totalWaves}`;banner.hidden=false;banner.classList.add('show');playSound('boss');arena.classList.remove('wave-out');arena.classList.add('wave-in');renderBattle(false);await wait(1200);banner.classList.remove('show');banner.hidden=true;arena.classList.remove('wave-in');battle.currentPhase=null}
  async function showLine(line){if(!line.line)return;$$('.reel').forEach(r=>r.classList.add('line-win'));$("#comboBanner").textContent=t('lineComplete');await wait(1000);$$('.reel').forEach(r=>r.classList.remove('line-win'))}
  function clearRuneEffects(){$$('.reel').forEach(r=>r.classList.remove('effect-active'))}
  function setRuneEffect(type,on,line=false){$$('.reel').forEach(r=>{const match=r.dataset.symbol===type||(line&&r.dataset.symbol==='wild');r.classList.toggle('effect-active',on&&match);if(match)r.style.setProperty('--effect-color',RUNES[type].color)})}
  function dealTarget(amount){const index=currentTargetIndex(),enemy=battle.enemies[index];if(!enemy||enemy.hp<=0)return-1;enemy.hp=Math.max(0,enemy.hp-amount);return index}
  function pointFor(element,vertical=.42){const arena=$("#arena").getBoundingClientRect(),box=element?.getBoundingClientRect();return box?{x:(box.left+box.width/2-arena.left)/arena.width*100,y:(box.top+box.height*vertical-arena.top)/arena.height*100,w:box.width/arena.width*100,h:box.height/arena.height*100}:{x:50,y:20,w:20,h:20}}
  function cleanupAfter(ms,cleanup){wait(ms).then(cleanup).catch(error=>{cleanup();if(error!==battleCancellation)throw error})}
  function impactFx(x,y,color,ultimate=false){const layer=$("#fxLayer"),burst=document.createElement('i');burst.className=`impact-burst${ultimate?' ultimate-impact':''}`;burst.style.cssText=`--impact-x:${x}%;--impact-y:${y}%;--spell-color:${color}`;layer.append(burst);for(let i=0;i<(ultimate?12:8);i++){const spark=document.createElement('i');spark.className='impact-spark';spark.style.cssText=`--impact-x:${x}%;--impact-y:${y}%;--spark-angle:${i*(ultimate?30:45)}deg;--spell-color:${color}`;layer.append(spark);cleanupAfter(700,()=>spark.remove())}cleanupAfter(700,()=>burst.remove())}
  function ultimateFx(origin,color){const layer=$("#fxLayer"),sigil=document.createElement('i'),flash=document.createElement('i'),safe={x:Math.min(75,Math.max(25,origin.x)),y:Math.min(82,Math.max(18,origin.y))};sigil.className='ultimate-sigil';flash.className='ultimate-flash';sigil.style.cssText=flash.style.cssText=`--cast-x:${safe.x}%;--cast-y:${safe.y}%;--spell-color:${color}`;layer.append(flash,sigil);cleanupAfter(950,()=>{flash.remove();sigil.remove()})}
  async function petAttack(id,amount,label,ultimate=false){const hero=$(`.party-hero[data-hero="${id}"]`),targetIndex=currentTargetIndex(),enemy=$(`.enemy-unit[data-enemy="${targetIndex}"]`),origin=pointFor(hero,.46),target=pointFor(enemy),color={lion:'#ffb43c',turtle:'#57e8c8',rabbit:'#ff79d1',panda:'#b88cff',fox:'#63ff9b',owl:'#9d8cff',otter:'#43ddff',rhino:'#ff6d55',astra:'#8ff7ff',nyra:'#a9d7ff'}[id];$$('.party-hero').forEach(x=>x.classList.toggle('active',x===hero));hero?.classList.add('attack-launch',`spell-${id}`);if(ultimate){hero?.classList.add('ultimate-cast');ultimateFx(origin,color)}playSound('shoot');const shot=document.createElement('i');shot.className=`magic-projectile spell-${id}${ultimate?' ultimate-projectile':''}`;shot.style.cssText=`--shot-x:${origin.x}%;--shot-y:${origin.y}%;--target-x:${target.x}%;--target-y:${target.y}%;--spell-color:${color}`;$("#fxLayer").append(shot);await wait(ultimate?640:500);shot.classList.add('impacting');const hitIndex=dealTarget(amount);renderEnemies();const hit=$(`.enemy-unit[data-enemy="${hitIndex}"]`);hit?.classList.add('enemy-hit');playSound('hit');impactFx(target.x,target.y,color,ultimate);const num=document.createElement('b');num.className='damage-number';num.style.cssText=`--damage-x:${target.x}%;--damage-y:${Math.max(8,target.y-5)}%`;num.textContent=`-${amount}`;$("#fxLayer").append(num);await wait(ultimate?720:560);hero?.classList.remove('attack-launch','ultimate-cast','active',`spell-${id}`);shot.remove();num.remove();hit?.classList.remove('enemy-hit');if(!battle.enemies[battle.targetIndex]?.hp)currentTargetIndex();renderEnemies()}
  async function petAttackAll(id,amount,label){const hero=$(`.party-hero[data-hero="${id}"]`),indices=battle.enemies.map((enemy,index)=>enemy.hp>0?index:-1).filter(index=>index>=0);if(!indices.length)return 0;const origin=pointFor(hero,.46),target=pointFor($("#enemySquad"),.45),color={lion:'#ffb43c',panda:'#b88cff',owl:'#9d8cff',rhino:'#ff6d55',astra:'#8ff7ff',nyra:'#a9d7ff'}[id]||'#ffe06b',points=indices.map(index=>({index,point:pointFor($(`.enemy-unit[data-enemy="${index}"]`))}));$$('.party-hero').forEach(node=>node.classList.toggle('active',node===hero));hero?.classList.add('attack-launch','ultimate-cast',`spell-${id}`);ultimateFx(origin,color);playSound('shoot');const shot=document.createElement('i');shot.className=`magic-projectile spell-${id} ultimate-projectile group-projectile`;shot.style.cssText=`--shot-x:${origin.x}%;--shot-y:${origin.y}%;--target-x:${target.x}%;--target-y:${target.y}%;--spell-color:${color}`;$("#fxLayer").append(shot);await wait(640);shot.classList.add('impacting');indices.forEach(index=>battle.enemies[index].hp=Math.max(0,battle.enemies[index].hp-amount));renderEnemies();playSound('hit');const numbers=[];points.forEach(({index,point})=>{const hit=$(`.enemy-unit[data-enemy="${index}"]`);hit?.classList.add('enemy-hit');impactFx(point.x,point.y,color,true);const num=document.createElement('b');num.className='damage-number group-damage';num.style.cssText=`--damage-x:${point.x}%;--damage-y:${Math.max(8,point.y-5)}%`;num.textContent=`-${amount}`;$("#fxLayer").append(num);numbers.push(num)});await wait(720);hero?.classList.remove('attack-launch','ultimate-cast','active',`spell-${id}`);shot.remove();numbers.forEach(node=>node.remove());$$('.enemy-hit').forEach(node=>node.classList.remove('enemy-hit'));if(!battle.enemies[battle.targetIndex]?.hp)currentTargetIndex();renderEnemies();return amount*indices.length}
  async function supportCast(id,type,ultimate=false){const hero=$(`.party-hero[data-hero="${id}"]`),origin=pointFor(hero,.55),color=type==='heal'?'#65ff9a':type==='shield'?'#63eaff':'#c386ff';$$('.party-hero').forEach(x=>x.classList.toggle('active',x===hero));hero?.classList.add('support-cast',`cast-${type}`);if(ultimate)ultimateFx(origin,color);const aura=document.createElement('i');aura.className=`support-aura ${type}-aura${ultimate?' ultimate-aura':''}`;aura.style.cssText=`--cast-x:${origin.x}%;--cast-y:${origin.y}%;--spell-color:${color}`;$("#fxLayer").append(aura);await wait(ultimate?850:650);hero?.classList.remove('support-cast',`cast-${type}`);aura.remove()}
  async function showHealEffect(amount){renderBattle(false);const hp=$(".summoner-hp"),delta=$("#healDelta"),wave=document.createElement('i');wave.className='heal-wave';$("#fxLayer").append(wave);hp.classList.add('healing');playSound('success');delta.textContent=`+${amount}`;delta.hidden=false;await wait(900);hp.classList.remove('healing');delta.hidden=true;wave.remove()}
  async function showDefenseEffect(){renderBattle(false);const dome=document.createElement('i');dome.className='shield-dome';$("#fxLayer").append(dome);playSound('upgrade');await wait(780);dome.remove()}
  async function showRuneTransfer(type,targets,line=false){const root=$(".battle-canvas"),sources=$$(`.reel[data-symbol="${type}"]${line?',.reel[data-symbol="wild"]':''}`);if(!sources.length||!targets.length)return;const rootBox=root.getBoundingClientRect(),sx=rootBox.width/root.offsetWidth||1,sy=rootBox.height/root.offsetHeight||1,point=node=>{const box=node.getBoundingClientRect();return{x:(box.left+box.width/2-rootBox.left)/sx,y:(box.top+box.height/2-rootBox.top)/sy}},flights=targets.map((target,index)=>{const start=point(sources[index%sources.length]),end=point(target),img=document.createElement('img');img.className=`rune-flight rune-flight-${type}`;img.src=ASSET+RUNES[type].img;img.alt='';img.style.cssText=`--rune-from-x:${start.x}px;--rune-from-y:${start.y}px;--rune-to-x:${end.x}px;--rune-to-y:${end.y}px;--rune-flight-delay:${index*70}ms`;root.append(img);return img});await wait(760+Math.max(0,targets.length-1)*70);targets.forEach(target=>target.classList.add('metric-impact'));flights.forEach(img=>img.remove());await wait(300);targets.forEach(target=>target.classList.remove('metric-impact'))}
  async function normalAttacks(attackBonus,luckBonus,runeBonus,lineBonus){let total=0;const team=activeTeam(),attackCharge=battle.attackCharge||0,mult=1+attackBonus+attackCharge;battle.attackDisplay={};team.forEach(id=>{const s=combatStats(id);battle.attackDisplay[id]=Math.round(s.atk*mult*(1+luckBonus))});if(runeBonus){setRuneEffect('attack',true,lineBonus);await showRuneTransfer('attack',$$('.party-hero small'),lineBonus)}battle.attackBonusActive=!!runeBonus||luckBonus>0||attackCharge>0;renderParty();battle.attackReadyAt=performance.now();if(luckBonus){setRuneEffect('luck',true);await showFieldEffect('luck-field')}const boosted=battle.attackBonusActive;if(boosted)await wait(340);battle.attackLaunchAt=performance.now();$("#comboBanner").textContent=t('attackPhase');for(const id of team){const s=combatStats(id),dmg=battle.attackDisplay[id];battle.phaseLog.push({phase:'attack',hero:id,base:s.atk,runeCount:runeBonus,lineBonus:lineBonus?linePower({line:true,type:'attack'},'attack'):1,mult,attackCharge,luckBonus,amount:dmg,target:currentTargetIndex(),readyDelay:battle.attackLaunchAt-battle.attackReadyAt});await petAttack(id,dmg,t(HEROES[id].name));total+=dmg;if(!living().length)break}battle.attackCharge=0;setRuneEffect('attack',false);setRuneEffect('luck',false);return total}
  async function specials(mult,lineBonus){let total=0;setRuneEffect('special',true,lineBonus);for(const id of activeTeam()){const h=HEROES[id],s=combatStats(id),attack=Math.round(s.atk*h.power*mult),defense=Math.round(s.def*h.power*mult),healing=Math.round(s.heal*h.power*mult);$("#comboBanner").textContent=t(h.special);const log={phase:'special',hero:id,mode:h.mode,amount:0,target:currentTargetIndex()};
      if(h.mode==='allDamage'){const dealt=await petAttackAll(id,attack,t(h.special));log.amount=attack;log.totalDamage=dealt;log.targets=dealt?dealt/attack:0;total+=dealt}
      else if(h.mode==='reflect'){await supportCast(id,'shield',true);battle.shield+=defense;battle.reflect=Math.min(1,(battle.reflect||0)+.5);log.shield=defense;log.reflect=.5;log.reflectTotal=battle.reflect;log.defenseDisplay=addDefenseBonus(defense);await showDefenseEffect()}
      else if(h.mode==='surge'){await supportCast(id,'heal',true);const actual=Math.min(healing,battle.maxHp-battle.hp);battle.hp+=actual;battle.attackCharge=Math.min(.6,(battle.attackCharge||0)+.2);log.amount=healing;log.actual=actual;log.attackCharge=.2;log.attackChargeTotal=battle.attackCharge;await showHealEffect(actual)}
      else if(h.mode==='waveRage'){const waveMultiplier=h.power+(battle.wave-1)*h.waveStep,waveDamage=Math.round(s.atk*waveMultiplier*mult),dealt=await petAttackAll(id,waveDamage,t(h.special));log.amount=waveDamage;log.wave=battle.wave;log.waveMultiplier=waveMultiplier;log.totalDamage=dealt;log.targets=dealt?dealt/waveDamage:0;total+=dealt}
      else if(h.mode==='multihit'&&living().length){const hits=[.32,.32,.36].map(n=>Math.max(1,Math.round(attack*n)));for(const hit of hits){if(!living().length)break;await petAttack(id,hit,t(h.special),true);total+=hit}log.amount=hits.reduce((a,n)=>a+n,0);log.totalDamage=log.amount;log.hits=hits}
      else if(h.mode==='drainAll'){const dealt=await petAttackAll(id,attack,t(h.special)),heal=Math.min(Math.round(dealt*.35),battle.maxHp-battle.hp);battle.hp+=heal;log.amount=attack;log.totalDamage=dealt;log.targets=dealt?dealt/attack:0;log.healing=heal;total+=dealt;await showHealEffect(heal)}
      else if(h.mode==='resonance'){await supportCast(id,'heal',true);const actual=Math.min(healing,battle.maxHp-battle.hp);battle.hp+=actual;battle.runeAmp=Math.min(.75,(battle.runeAmp||0)+.25);log.amount=healing;log.actual=actual;log.runeAmp=.25;log.runeAmpTotal=battle.runeAmp;$("#comboBanner").textContent=`${t(h.special)} · ${t('allRunesBoosted')} +25%`;await showHealEffect(actual);await showFieldEffect('luck-field')}
      else if(h.mode==='bulwarkCharge'){await supportCast(id,'shield',true);battle.shield+=defense;log.shield=defense;log.focus=.2;log.focusTotal=addFocus(.2);log.defenseDisplay=addDefenseBonus(defense);await showDefenseEffect();const groupDamage=Math.max(1,Math.round(defense*.75)),dealt=await petAttackAll(id,groupDamage,t(h.special));log.amount=groupDamage;log.totalDamage=dealt;log.targets=dealt?dealt/groupDamage:0;total+=dealt}
      else if(h.mode==='aurora'){const dealt=await petAttackAll(id,attack,t(h.special)),heal=Math.min(Math.round(healing*.5),battle.maxHp-battle.hp);battle.hp+=heal;log.amount=attack;log.totalDamage=dealt;log.targets=dealt?dealt/attack:0;log.healing=heal;total+=dealt;await showHealEffect(heal)}
      else if(h.mode==='frostAll'){const dealt=await petAttackAll(id,attack,t(h.special));log.amount=attack;log.totalDamage=dealt;log.targets=dealt?dealt/attack:0;log.focus=.2;log.focusTotal=addFocus(.2);total+=dealt;await showFieldEffect('focus-field')}
      battle.phaseLog.push(log);renderBattle(false)}setRuneEffect('special',false);return total}
  async function showFieldEffect(className,element=$("#partyHeroes")){const point=pointFor(element,.55),field=document.createElement('i');field.className=className;field.style.cssText=`--effect-x:${point.x}%;--effect-y:${point.y}%;--effect-w:${Math.min(82,Math.max(24,point.w*1.15))}%;--effect-h:${Math.min(30,Math.max(18,point.h*1.45))}%`;$("#fxLayer").append(field);await wait(720);field.remove()}
  async function runeBlast(type,amount){const enemy=$(`.enemy-unit[data-enemy="${currentTargetIndex()}"]`),target=pointFor(enemy),pulse=document.createElement('i');pulse.className=`${type}-pulse`;pulse.style.cssText=`--effect-x:${target.x}%;--effect-y:${target.y}%`;$("#fxLayer").append(pulse);await wait(260);const index=dealTarget(amount);renderEnemies();impactFx(target.x,target.y,RUNES[type].color);const num=document.createElement('b');num.className='damage-number rune-damage';num.style.cssText=`--damage-x:${target.x}%;--damage-y:${Math.max(8,target.y-5)}%`;num.textContent=`-${amount}`;$("#fxLayer").append(num);await wait(720);pulse.remove();num.remove();if(!battle.enemies[battle.targetIndex]?.hp)currentTargetIndex();renderEnemies();return index}
  function logicalCenter(element,root){const a=root.getBoundingClientRect(),b=element.getBoundingClientRect(),sx=a.width/root.offsetWidth||1,sy=a.height/root.offsetHeight||1;return{x:(b.left+b.width/2-a.left)/sx,y:(b.top+b.height/2-a.top)/sy}}
  async function showCoinEffect(value){const root=$(".battle-canvas"),sources=$$('.reel[data-symbol="coin"]'),bank=$("#battleCoins"),bankBox=logicalCenter(bank,root),coins=sources.map((source,i)=>{const start=logicalCenter(source,root),coin=document.createElement('img');coin.className='coin-flight';coin.src=ASSET+RUNES.coin.img;coin.alt='';coin.style.cssText=`--coin-x:${start.x}px;--coin-y:${start.y}px;--bank-x:${bankBox.x}px;--bank-y:${bankBox.y}px;--coin-delay:${i*90}ms`;root.append(coin);return coin});playSound('coin');await wait(900+Math.max(0,sources.length-1)*90);battle.coins+=value;renderBattle(false);const metric=$("#battleCoins").closest('span');metric.classList.add('coin-received');coins.forEach(x=>x.remove());await wait(520);metric.classList.remove('coin-received')}
  async function resolve(){const {c,line}=counts(),storedLuck=battle.luckCharge||0;battle.lastResolution={counts:c,line,attacks:[],defense:0,healing:0,special:false};await showLine(line);let attackTotal=0;
    const specialLine=line.line&&line.type==='special',attackLine=line.line&&line.type==='attack';
    if(c.special){battle.currentPhase='special';const mult=c.special*runeValue('special')*linePower(line,'special')*(1+leaderEffect('special'))*runeEffectScale();battle.lastResolution.special=true;attackTotal=await specials(mult,specialLine)}
    else{battle.currentPhase='attack';const scale=runeEffectScale(),attackBonus=c.attack*(runeValue('attack')+leaderEffect('attackRune'))*linePower(line,'attack')*scale,luckBonus=(c.luck*runeValue('luck')*scale+storedLuck)*linePower(line,'luck');attackTotal=await normalAttacks(attackBonus,luckBonus,c.attack,attackLine)}
    if(c.echo&&(attackTotal||battle.lastDamage)&&living().length){battle.currentPhase='echo';const base=attackTotal||battle.lastDamage,echoMult=c.echo*runeValue('echo')*linePower(line,'echo')*runeEffectScale(),echo=Math.round(base*echoMult);setRuneEffect('echo',true,line.line&&line.type==='echo');$("#comboBanner").textContent=t('runeEcho');await runeBlast('echo',echo);setRuneEffect('echo',false);battle.phaseLog.push({phase:'echo',base,mult:echoMult,amount:echo})}
    if(c.heal){battle.currentPhase='healing';const sum=totals().heal,mult=c.heal*runeValue('heal')*linePower(line,'heal')*runeEffectScale(),value=Math.round(sum*mult),actual=Math.min(value,battle.maxHp-battle.hp);setRuneEffect('heal',true,line.line&&line.type==='heal');$("#comboBanner").textContent=t('healingPhase');battle.hp+=actual;battle.lastResolution.healing=value;battle.phaseLog.push({phase:'healing',base:sum,mult,amount:value,actual});await showHealEffect(actual);setRuneEffect('heal',false)}
    if(c.focus){battle.currentPhase='focus';const amount=c.focus*runeValue('focus')*linePower(line,'focus')*runeEffectScale(),before=battle.focus||0,total=addFocus(amount);setRuneEffect('focus',true,line.line&&line.type==='focus');$("#comboBanner").textContent=t('runeFocus');battle.phaseLog.push({phase:'focus',before,amount,total});await showFieldEffect('focus-field');setRuneEffect('focus',false)}
    if(c.defense){battle.currentPhase='defense';const sum=totals().def,bonusRatio=c.defense*runeValue('defense')*linePower(line,'defense')*runeEffectScale(),value=Math.round(sum*bonusRatio),priorBonus=battle.defenseBonus||0;setRuneEffect('defense',true,line.line&&line.type==='defense');$("#comboBanner").textContent=t('defensePhase');await showRuneTransfer('defense',[$("#defenseMetric")],line.line&&line.type==='defense');battle.shield+=value;const display=addDefenseBonus(value);battle.lastResolution.defense=value;battle.phaseLog.push({phase:'defense',base:sum,priorBonus,bonusRatio,amount:value,totalBonus:battle.defenseBonus,display});renderBattle(false);await showDefenseEffect()}
    if(c.coin){battle.currentPhase='coin';const value=Math.round(c.coin*runeValue('coin')*linePower(line,'coin')*(battle.mission.coinBonus||1)*runeEffectScale());setRuneEffect('coin',true,line.line&&line.type==='coin');$("#comboBanner").textContent=t('runeCoin');battle.phaseLog.push({phase:'coin',scale:runeEffectScale(),amount:value});await showCoinEffect(value);setRuneEffect('coin',false)}
    if(attackTotal)battle.lastDamage=attackTotal;battle.luckCharge=line.line&&line.type==='luck'?c.luck*runeValue('luck')*linePower(line,'luck')*runeEffectScale():0;battle.attackDisplay=null;battle.attackBonusActive=false;battle.currentPhase=null;renderBattle(false)
  }
  async function enemyStrike(index){const enemy=battle.enemies[index];if(!enemy||enemy.hp<=0||battle.hp<=0)return;const startedAt=performance.now(),reduction=Math.min(.9,battle.focus||0),rawDamage=enemy.damage,mitigated=Math.max(0,Math.round(rawDamage*(1-reduction)));battle.focus=0;enemy.attacking=true;$("#comboBanner").textContent=`${enemy.name} · CD:0`;renderEnemies();await wait(320);const blocked=Math.min(battle.shield,mitigated),damage=mitigated-blocked;battle.shield-=blocked;battle.hp=Math.max(0,battle.hp-damage);syncPlayerHealth();$("#shieldText").textContent=battle.shield;const hp=$(".summoner-hp"),v=document.createElement('i'),hit=document.createElement('b');hp.classList.add('player-hit');playSound('wallHit');v.className='damage-vignette';hit.className='player-damage';hit.textContent=`-${damage}`;$("#arena").append(v);$("#fxLayer").append(hit);await wait(650);hp.classList.remove('player-hit');v.remove();hit.remove();enemy.cd=enemy.attackCd;enemy.attacking=false;renderEnemies();const reflected=blocked&&battle.reflect&&living().length?Math.max(1,Math.round(blocked*battle.reflect)):0;if(reflected){$("#comboBanner").textContent=t('specialTurtle');await runeBlast('echo',reflected)}battle.phaseLog.push({phase:'enemy',enemy:index,enemyType:enemy.id,startedAt,rawDamage,damage,blocked,reduction,reflected,cdReset:enemy.attackCd})}
  async function enemyTurn(){battle.currentPhase='enemy';$("#comboBanner").textContent=t('enemyPhase');const ready=[];battle.enemies.forEach((enemy,index)=>{if(enemy.hp<=0)return;enemy.cd=Math.max(0,enemy.cd-1);if(enemy.cd===0)ready.push(index)});renderEnemies();if(!ready.length){battle.phaseLog.push({phase:'enemy-wait',cooldowns:battle.enemies.map(enemy=>enemy.hp>0?enemy.cd:null)});await wait(450)}else{await wait(220);for(const index of ready){if(battle.hp<=0)break;await enemyStrike(index)}battle.reflect=0}battle.defenseBonus=0;battle.defenseDisplay=null;battle.defenseBuff=false;setRuneEffect('defense',false);battle.currentPhase=null;renderBattle(false)}
  function finishTurn(){battle.busy=false;if(!living().length&&battle.wave>=battle.totalWaves)return endBattle(true);if(battle.hp<=0)return endBattle(false);renderBattle(false);if(battle.auto)wait(500).then(()=>{if(battle?.auto&&!battle.busy&&!battle.ended)spin()}).catch(error=>{if(error!==battleCancellation)throw error})}
  function endBattle(win){battle.ended=true;battle.auto=false;playSound(win?'win':'wrong');const fixedClaimed=win&&!!battle.mission.rewardClaimed,rewards=win&&!fixedClaimed?{...battle.mission.rewards}:{ };if(win&&!fixedClaimed&&battle.mission.rewardPeriod&&Object.keys(battle.mission.rewards).length)profile.rewardClaims[battle.mission.id]=battle.mission.rewardPeriod;if(battle.coins>0)rewards.coins=battle.coins;profile.coins+=rewards.coins||0;profile.diamonds+=rewards.diamonds||0;materialIds.forEach(id=>profile.materials[id]+=rewards[id]||0);if(win&&battle.mission.type==='main'){const n=battle.mission.stage;profile.best[n-1]=Math.max(profile.best[n-1]||0,battle.hp/battle.maxHp>.7?3:battle.hp/battle.maxHp>.35?2:1);profile.unlocked=Math.max(profile.unlocked,Math.min(30,n+1))}save();$("#resultTitle").textContent=t(win?'win':'lose');$("#resultBody").textContent=t(win?'winBodyV3':'loseBodyV3');$("#rewardDetails").innerHTML=Object.entries(rewards).filter(([,n])=>n>0).map(([id,n])=>`<span><b>+${n}</b>${id==='coins'?t('coins'):id==='diamonds'?t('diamonds'):t(MATERIALS[id].name)}</span>`).join('')||`<span>${t(fixedClaimed?'rewardClaimed':'noRewards')}</span>`;const next=$("#nextBtn"),retry=$("#retryBtn"),stages=$("#resultStages"),canAdvance=win&&battle.mission.type==='main'&&battle.mission.stage<30,primary=canAdvance?next:win?stages:retry;resultActionClaimed=false;next.hidden=!canAdvance;[next,retry,stages].forEach(action=>{action.disabled=false;action.classList.toggle('primary',action===primary);action.classList.toggle('secondary',action!==primary)});renderBattle(false);openBattleModal('#result',`#${primary.id}`)}
  function claimResultAction(){const result=$("#result");if(result.hidden||resultActionClaimed)return false;resultActionClaimed=true;$$('#result button').forEach(action=>action.disabled=true);return true}
  function leaveBattle(){leaveConfirmOpen=false;if(battle)battle.cancelled=true;resetBattleLifecycle();battle=null;$("#fxLayer").replaceChildren();$$('.reel').forEach(reel=>reel.classList.remove('spinning','line-win'));$("#arena").classList.remove('wave-out','wave-in');$("#waveTransition").hidden=true;$("#waveTransition").classList.remove('show');$("#result").hidden=true;$("#leaveConfirm").hidden=true;setBattleInert(false);show('stagePage');renderStage();setTab('stages')}
  function ensureStageToast(){if(stageToastNode)return stageToastNode;stageToastNode=document.createElement("output");stageToastNode.id="stageToast";stageToastNode.className="stage-toast";stageToastNode.setAttribute("role","status");stageToastNode.setAttribute("aria-live","polite");stageToastNode.setAttribute("aria-atomic","true");stageToastNode.hidden=true;$(".stage-canvas").append(stageToastNode);return stageToastNode}
  function clearStageToast(){stageToastToken++;if(stageToastTimer)clearTimeout(stageToastTimer);stageToastTimer=0;stageToastRemaining=0;if(stageToastNode){stageToastNode.hidden=true;stageToastNode.textContent=""}}
  function startStageToastTimer(){if(stageToastTimer||!stageToastNode||stageToastNode.hidden||!isForeground())return;stageToastStartedAt=performance.now();stageToastTimer=setTimeout(clearStageToast,stageToastRemaining)}
  function suspendStageToast(){if(!stageToastTimer)return;clearTimeout(stageToastTimer);stageToastTimer=0;stageToastRemaining=Math.max(0,stageToastRemaining-(performance.now()-stageToastStartedAt))}
  function resumeStageToast(){if(stageToastRemaining>0)startStageToastTimer()}
  function toast(text){const node=ensureStageToast(),token=++stageToastToken;if(stageToastTimer)clearTimeout(stageToastTimer);stageToastTimer=0;stageToastRemaining=1600;node.hidden=false;node.textContent="";requestAnimationFrame(()=>{if(token!==stageToastToken)return;node.textContent=text;startStageToastTimer()})}
  const wait=(ms)=>new Promise((resolve,reject)=>{const waiter={remaining:Math.max(0,ms/currentBattleSpeed()),startedAt:0,timer:0,resolve,reject};battleWaiters.add(waiter);startBattleWait(waiter)});
  function bind(){
    $("#runeStartBtn").onclick=()=>{show('stagePage');renderStage();setTab('stages')};$("#stageBack").onclick=()=>show('mainPage');$("#enterBattle").onclick=startBattle;$("#spinBtn").onclick=spin;$("#autoBtn").onclick=()=>{if(!battle||battle.ended)return;battle.auto=!battle.auto;renderBattle(false);if(battle.auto&&!battle.busy)spin()};$("#speedBtn").onclick=()=>setBattleSpeed(currentBattleSpeed()===1?2:1);$("#battleBack").onclick=openLeaveConfirmation;$("#leaveContinue").onclick=continueBattle;$("#leaveStages").onclick=leaveBattle;$("#resultStages").onclick=()=>{if(claimResultAction())leaveBattle()};$("#retryBtn").onclick=()=>{if(!claimResultAction())return;closeBattleModal('#result');startBattle()};$("#nextBtn").onclick=()=>{if(!claimResultAction())return;selectedStage=battle.mission.stage+1;selectedMissionId=`main-${selectedStage}`;closeBattleModal('#result');startBattle()};$("#tutorialClose").onclick=()=>{profile.tutorial=true;save();closeBattleModal('#tutorial')};$("#helpBtn").onclick=()=>setTab('runes');
    $$('.stage-tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('.mission-tabs button').forEach(b=>b.onclick=()=>setMissionType(b.dataset.missionType));["#coinSummonBtn","#diamondSummonBtn","#summonClose","#equipBtn","#upgradeBtn"].forEach(selector=>$(selector).addEventListener("keydown",event=>{if(event.repeat&&(event.key==="Enter"||event.key===" "))event.preventDefault()}));$("#coinSummonBtn").onclick=()=>summon('coin');$("#diamondSummonBtn").onclick=()=>summon('diamond');$("#summonClose").onclick=closeSummonResult;$("#characterClose").onclick=closeHero;$("#equipBtn").onclick=()=>{const slot=profile.slots.indexOf(currentHero);if(slot>=0){if(activeTeam().length===1)return toast(t('needOneHero'));profile.slots[slot]=null}else{const empty=profile.slots.indexOf(null);if(empty<0)return toast(t('teamFull'));profile.slots[empty]=currentHero}selectedTeamSlot=null;save();openHero(currentHero);renderRoster()};$("#upgradeBtn").onclick=()=>{const c=profile.cards[currentHero],need=requiredCopies(c.level);if(c.copies<need)return;c.copies-=need;c.level++;playSound('upgrade');save();openHero(currentHero);renderRoster()};
    $("#soundToggle").addEventListener("keydown",event=>{if(event.repeat&&(event.key==="Enter"||event.key===" "))event.preventDefault()});$("#soundToggle").onclick=()=>{const sound=window.WonderSound;if(!sound)return;sound.unlock();sound.setMuted(!sound.isMuted());syncSoundToggle();if(!sound.isMuted())sound.play("click")};
    $("#localeSelect").onchange=e=>{locale=e.target.value;write(`${storageKey}.locale`,locale);window.WonderI18n?.setLocale(locale);const target=new URL(`/${localeRouteSegments[locale]}/games/animal-rune-reels/`,location.origin);if(trial)target.searchParams.set("trial","1");location.replace(target)};
    const rail=$("#stageRail");rail.addEventListener('wonder:stage-snap',()=>requestAnimationFrame(syncCenteredStage));
    document.addEventListener('keydown',e=>{const summonModal=$("#summonResult:not([hidden])");if(summonModal){if(e.key==='Escape'){e.preventDefault();closeSummonResult()}else if(e.key==='Tab'){e.preventDefault();$("#summonClose").focus()}return}const characterModal=$("#characterModal:not([hidden])");if(characterModal){if(e.key==='Escape'){e.preventDefault();closeHero();return}if(e.key==='Tab'){const buttons=[...characterModal.querySelectorAll('button:not([disabled]):not([hidden])')];if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return}const modal=$('.v3-battle .modal:not([hidden])');if(!modal)return;if(e.key==='Escape'&&modal.id==='leaveConfirm'){e.preventDefault();continueBattle();return}if(e.key==='Tab'){const buttons=[...modal.querySelectorAll('button:not([disabled]):not([hidden])')];if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
    addEventListener('blur',()=>{windowFocused=false;suspendBattleLifecycle();suspendStageToast()});addEventListener('focus',()=>{windowFocused=true;resumeBattleLifecycle();resumeStageToast()});addEventListener('pagehide',()=>{suspendBattleLifecycle();suspendStageToast()});addEventListener('pageshow',()=>{resumeBattleLifecycle();resumeStageToast()});document.addEventListener('visibilitychange',()=>{if(document.hidden){suspendBattleLifecycle();suspendStageToast()}else{resumeBattleLifecycle();resumeStageToast()}});
  }
  async function preload(){const urls=["animal-rune-reels/cover.webp","animal-rune-reels/arena.webp",...Object.values(RUNES).map(x=>x.img),...Object.values(HEROES).map(x=>x.img),...Object.values(MATERIALS).map(x=>x.img),...ENEMIES.map(x=>x.img)];let done=0;await Promise.all(urls.map(src=>new Promise(r=>{const im=new Image();let settled=false;const finish=()=>{if(settled)return;settled=true;$("#loadFill").style.width=`${++done/urls.length*100}%`;r()};im.onload=finish;im.onerror=finish;im.src=ASSET+src;setTimeout(finish,4000)})));$("#loading").hidden=true;$("#app").hidden=false}
  async function init(){locale=pickLocale();selectedStage=Math.min(profile.unlocked,30);selectedMissionId=`main-${selectedStage}`;new MutationObserver(()=>{const root=document.documentElement,dir=locale==='ar'?'rtl':'ltr';if(root.lang!==locale)root.lang=locale;if(root.dir!==dir)root.dir=dir}).observe(document.documentElement,{attributes:true,attributeFilter:['lang','dir']});addEventListener('resize',fitStageCanvas,{passive:true});visualViewport?.addEventListener('resize',fitStageCanvas,{passive:true});ensureStageToast();populateLocales();bind();applyLocale();await preload();show('mainPage')}
  if(trial)window.__RUNE_REELS_TEST__={state:()=>battle?JSON.parse(JSON.stringify(battle)):null,profile:()=>JSON.parse(JSON.stringify(profile)),sounds:()=>soundLog.slice(),rewardPeriods:date=>rewardPeriods(new Date(date)),weeklyEvents:()=>Array.from({length:7},(_,weekday)=>missions('event',weekday).map(({id,locked,schedule})=>({id,locked,schedule}))),enemyBalance:()=>ENEMIES.map(enemy=>({...enemy})),forceReels:x=>{if(battle)battle.forced=x},forceSummon:(id,pool='coin')=>summon(pool,id),selectMission:(type,id)=>{setMissionType(type);if(missions(type).some(x=>x.id===id))centerMission(id,false)},upgradeRune,selectTarget:i=>selectTarget(i),selectTeamSlot:index=>{selectedTeamSlot=index;renderTeamSlots()},setTeam:ids=>{const unique=[...new Set(ids.filter(id=>HEROES[id]&&profile.cards[id].unlocked))].slice(0,5);profile.slots=[...unique,...Array(5-unique.length).fill(null)];save();renderStage()},setRuneLevel:(id,level)=>{if(runeIds.includes(id)&&id!=='blank')profile.runeLevels[id]=Math.max(1,Math.min(5,level));save();renderStage()},unlockAll:()=>{profile.unlocked=30;save();renderStage()},unlockRoster:()=>{heroIds.forEach(id=>profile.cards[id].unlocked=true);profile.slots=['lion','turtle','rabbit','panda','fox'];save();renderStage()},resetTeamLevels:()=>{activeTeam().forEach(id=>{profile.cards[id].level=1;profile.cards[id].copies=0});save();renderStage()},resetRuneLevels:()=>{runeIds.forEach(id=>profile.runeLevels[id]=1);save();renderStage()},setMaterials:n=>{materialIds.forEach(id=>profile.materials[id]=n);save();renderStage()},setBattleCoins:n=>{if(battle){battle.coins=Math.max(0,Math.round(n));renderBattle(false)}},setFinalWave:()=>{if(battle){battle.wave=battle.totalWaves;renderBattle(false)}},setHealth:n=>{if(battle){battle.hp=Math.max(1,Math.min(battle.maxHp,n));renderBattle(false)}},setEnemyHealth:n=>{if(battle){battle.enemies.forEach((e,i)=>e.hp=i?0:Math.max(1,Math.min(e.maxHp,n)));renderBattle(false)}},setEnemyPool:n=>{if(battle){battle.enemies.forEach(e=>{e.maxHp=n;e.hp=n});renderBattle(false)}},setEnemyCooldowns:values=>{if(battle){battle.enemies.forEach((enemy,index)=>enemy.cd=Math.max(0,Math.round(values[index]??enemy.cd)));renderEnemies()}}};
  if(trial){const unlockRosterOnly=window.__RUNE_REELS_TEST__.unlockRoster;window.__RUNE_REELS_TEST__.unlockRoster=()=>{unlockRosterOnly();setTab('team')}}
  init();
})();
