(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const LOCALES=window.RUNE_REELS_LOCALES, localeKeys=Object.keys(LOCALES), storageKey='weightplay.animalRuneReels.v1', trialMode=new URLSearchParams(location.search).get('trial')==='1';
const ASSET_ROOT='../../assets/';
const symbols={
 fia:{key:'fia',img:'weightplay-character-spark-paw-fox-cutout.webp',color:'#5ddcff'},
 leo:{key:'leo',img:'weightplay-character-boom-mane-lion-cutout.webp',color:'#ffd360'},
 orla:{key:'orla',img:'weightplay-character-moon-cap-owl-cutout.webp',color:'#c791ff'},
 mimi:{key:'mimi',img:'weightplay-character-rainbow-hop-mimi-clean-cutout.webp',color:'#65efab'},
 crystal:{key:'crystal',img:'weightplay-character-drum-belly-panda-safe-face-cutout.webp',color:'#72e7ff'},
 claw:{key:'claw',img:'animal-gearpack-expedition-enemy-root-guardian.webp',color:'#ff668a'}
};
const enemyAssets=['animal-gearpack-expedition-enemy-root-guardian.webp','animal-gearpack-expedition-enemy-armored-boar.webp','animal-gearpack-expedition-enemy-crystal-crow.webp','animal-rune-tactics-enemy-wolf.webp','animal-rune-tactics-enemy-raven.webp'];
const chapterNames={en:['Whispering Gate','Moonforge Steps','Thornveil Court','Stormglass Ring','Voidpaw Spire','Astral Crown'],'zh-Hant':['低語之門','月爐階梯','棘幕王庭','風暴晶環','虛爪高塔','星界王冠'],'zh-Hans':['低语之门','月炉阶梯','棘幕王庭','风暴晶环','虚爪高塔','星界王冠']};
let profile=loadProfile(), locale=pickLocale(), selectedStage=Math.min(profile.unlocked,30), battle=null, centerTimer=0;
function loadProfile(){try{const x=JSON.parse(localStorage.getItem(storageKey)||'{}');return{unlocked:clampInt(x.unlocked,1,30,1),sparks:clampInt(x.sparks,0,99999,0),upgrades:{attack:clampInt(x.upgrades?.attack,1,8,1),heal:clampInt(x.upgrades?.heal,1,8,1),guard:clampInt(x.upgrades?.guard,1,8,1)},best:Array.isArray(x.best)?x.best.slice(0,30).map(v=>clampInt(v,0,3,0)):Array(30).fill(0),tutorial:Boolean(x.tutorial)}}catch(e){return{unlocked:1,sparks:0,upgrades:{attack:1,heal:1,guard:1},best:Array(30).fill(0),tutorial:false}}}
function clampInt(v,min,max,d){v=Number(v);return Number.isInteger(v)&&v>=min&&v<=max?v:d}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(profile))}catch(e){}}
function pickLocale(){const shared=window.WonderI18n?.actualLocale?.();const q=new URLSearchParams(location.search).get('lang');const saved=localStorage.getItem(storageKey+'.locale');const nav=navigator.language;return localeKeys.includes(shared)?shared:localeKeys.includes(q)?q:localeKeys.includes(saved)?saved:localeKeys.find(k=>nav.toLowerCase().startsWith(k.toLowerCase().split('-')[0]))||'en'}
function t(k){return LOCALES[locale]?.[k]||LOCALES.en[k]||k}
function applyLocale(){document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.title=t('title')+' — Internal Trial';$$('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});$('#localeSelect').value=locale;if(battle)renderBattle()}
function initLocales(){localeKeys.forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=LOCALES[k].name;$('#localeSelect').append(o)});$('#localeSelect').addEventListener('change',e=>{locale=e.target.value;localStorage.setItem(storageKey+'.locale',locale);applyLocale();renderStages()})}
function show(id){$$('.page').forEach(p=>p.hidden=p.id!==id);scrollTo(0,0)}
function stageData(n){const boss=n%5===0,chapter=Math.ceil(n/5);return{n,boss,chapter,maxHp:boss?145+chapter*32:66+n*8,playerHp:100+profile.upgrades.guard*5,enemyPower:7+Math.floor(n*1.22)+(boss?5:0),reward:8+n+(boss?12:0)}}
function chapterName(n){const arr=chapterNames[locale]||chapterNames[locale.startsWith('zh')?locale:'en']||chapterNames.en;return arr[Math.floor((n-1)/5)]}
function renderStages(){const rail=$('#stageRail');rail.innerHTML='';for(let n=1;n<=30;n++){const d=stageData(n),locked=n>profile.unlocked,card=document.createElement('button'),stars=profile.best[n-1]?' · '+'★'.repeat(profile.best[n-1]):'';card.className='stage-card'+(locked?' locked':'');card.style.gridTemplateRows='auto auto minmax(70px,1fr) auto auto';card.dataset.stage=n;card.setAttribute('aria-disabled',String(locked));card.innerHTML=`<small>${chapterName(n)}${locked?' · '+t('locked'):stars}</small><h3>${d.boss?t('boss'):t('stage')} ${n}</h3><img src="${ASSET_ROOT+enemyAssets[Math.min(4,Math.floor((n-1)/6))]}" alt="" style="width:100%;height:100%;min-height:70px;object-fit:contain;filter:drop-shadow(0 8px 8px #0009)"><p>${d.boss?'Boss · ':''}HP ${d.maxHp} · ATK ${d.enemyPower}</p><div class="monster-chip">${t('enemy')} ${Math.min(5,Math.ceil(n/6))}</div>`;card.addEventListener('click',()=>{if(!locked){selectedStage=n;centerStage(n,true)}});rail.append(card)}updateStageUi();requestAnimationFrame(()=>centerStage(selectedStage,false))}
function centerStage(n,smooth){const card=$(`.stage-card[data-stage="${n}"]`);if(!card)return;card.scrollIntoView({behavior:smooth?'smooth':'auto',inline:'center',block:'nearest'});selectedStage=n;updateStageUi()}
function updateStageUi(){$$('.stage-card').forEach(c=>c.classList.toggle('centered',Number(c.dataset.stage)===selectedStage));$('#campaignProgress').textContent=`${profile.unlocked} / 30`;$('#sparkCount').textContent=profile.sparks;for(const k of ['attack','heal','guard'])$('#'+k+'Level').textContent='Lv. '+profile.upgrades[k]}
function settleRail(){clearTimeout(centerTimer);centerTimer=setTimeout(()=>{const rail=$('#stageRail'),mid=rail.getBoundingClientRect().left+rail.clientWidth/2;let best=null,dist=Infinity;$$('.stage-card').forEach(c=>{const r=c.getBoundingClientRect(),d=Math.abs(r.left+r.width/2-mid);if(d<dist){best=c;dist=d}});if(best){const n=Number(best.dataset.stage);selectedStage=n;updateStageUi();best.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}},100)}
function upgrade(kind){const level=profile.upgrades[kind],cost=level*18;if(level>=8)return toast('MAX');if(profile.sparks<cost)return toast(t('needSparks'));profile.sparks-=cost;profile.upgrades[kind]++;save();updateStageUi();toast(t('upgradeOk'))}
function seedRand(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
function startBattle(){const d=stageData(selectedStage);battle={...d,hp:d.playerHp,maxPlayerHp:d.playerHp,enemyHp:d.maxHp,shield:0,focus:1,turn:0,held:null,reels:['fia','mimi','leo'],busy:false,ended:false,intent:'strike',rage:0};show('battlePage');rollIntent();renderBattle();if(!profile.tutorial)$('#tutorial').hidden=false}
function rollIntent(){const r=seedRand(selectedStage*7919+(battle.turn+1)*104729)();battle.intent=r<.38?'strike':r<.66?'heavy':r<.84?'drain':'rage'}
function intentDamage(){const base=battle.enemyPower+battle.rage;return battle.intent==='heavy'?Math.round(base*1.55):battle.intent==='drain'?Math.round(base*.78):battle.intent==='rage'?Math.round(base*1.25):base}
function renderBattle(){if(!battle)return;$('#chapterName').textContent=chapterName(selectedStage);$('#battleStage').textContent=`${t('stage')} ${selectedStage}`;$('#enemyName').textContent=(battle.boss?t('boss'):t('enemy'))+' '+Math.min(5,Math.ceil(selectedStage/6));$('#enemyImg').src=ASSET_ROOT+enemyAssets[Math.min(4,Math.floor((selectedStage-1)/6))];$('#enemyHpFill').style.width=Math.max(0,battle.enemyHp/battle.maxHp*100)+'%';$('#enemyHpText').textContent=`${Math.max(0,battle.enemyHp)} / ${battle.maxHp}`;$('#playerHpFill').style.width=Math.max(0,battle.hp/battle.maxPlayerHp*100)+'%';$('#playerHpText').textContent=`${Math.max(0,battle.hp)} / ${battle.maxPlayerHp}`;$('#shieldText').textContent=battle.shield;$('#focusText').textContent=battle.focus;$('#intentText').textContent=t('intent'+battle.intent[0].toUpperCase()+battle.intent.slice(1))+` · ${intentDamage()}`;$('#burstBtn').disabled=battle.focus<3||battle.busy||battle.ended;$('#spinBtn').disabled=battle.busy||battle.ended;renderReels()}
function renderReels(){$('#reels').innerHTML='';battle.reels.forEach((id,i)=>{const s=symbols[id],r=document.createElement('button');r.className='reel'+(battle.held===i?' held':'');r.dataset.index=i;r.innerHTML=`<span class="symbol"><img src="${ASSET_ROOT+s.img}" alt=""><b>${t(s.key)}</b></span>`;r.setAttribute('aria-label',`${t(s.key)}${battle.held===i?', '+t('hold'):''}`);r.addEventListener('click',()=>toggleHold(i));$('#reels').append(r)})}
function toggleHold(i){if(!battle||battle.busy||battle.ended)return;if(battle.held===i){battle.held=null}else{battle.held=i}renderBattle()}
async function spin(){if(!battle||battle.busy||battle.ended)return;if(battle.held!==null&&battle.focus<1){toast(t('needSparks'));battle.held=null}battle.busy=true;if(battle.held!==null)battle.focus--;battle.turn++;$$('.reel').forEach((r,i)=>{if(i!==battle.held)r.classList.add('spinning')});renderBattle();await wait(520);const rng=seedRand(selectedStage*1000003+battle.turn*9176+profile.upgrades.attack*17),pool=stagePool(),forced=trialMode&&Array.isArray(battle.forcedReels)?battle.forcedReels:null;for(let i=0;i<3;i++)if(i!==battle.held)battle.reels[i]=forced?.[i]||pool[Math.floor(rng()*pool.length)];battle.forcedReels=null;battle.held=null;renderBattle();await resolveRunes();if(battle.enemyHp>0&&battle.hp>0)await enemyTurn();finishTurn()}
function stagePool(){const p=['fia','fia','leo','mimi','orla','crystal','claw'];if(selectedStage>10)p.push('claw');if(selectedStage>20)p.push('claw','crystal');return p}
async function resolveRunes(){const counts={};battle.reels.forEach(x=>counts[x]=(counts[x]||0)+1);for(let i=0;i<3;i++){if(battle.enemyHp<=0)break;const id=battle.reels[i];await resolveSymbol(id,i)}const triple=Object.values(counts).some(v=>v===3);if(triple&&battle.enemyHp>0){$('#comboBanner').textContent=t('combo');const dmg=16+profile.upgrades.attack*4;damageEnemy(dmg,'✦ '+dmg,'#ffe56c');battle.focus=Math.min(5,battle.focus+1);await wait(600)}else $('#comboBanner').textContent=''}
async function resolveSymbol(id,index){const atk=10+profile.upgrades.attack*3;flashReel(index,symbols[id].color);if(id==='fia')damageEnemy(atk,'-'+atk,symbols[id].color);if(id==='leo'){const gain=9+profile.upgrades.guard*3;battle.shield+=gain;floatFx('◆ +'+gain,25,65,'#74ddff')}if(id==='orla'){const dmg=Math.round(atk*.65);damageEnemy(dmg,'-'+dmg,'#cf8cff');battle.rage=Math.max(-4,battle.rage-2)}if(id==='mimi'){const heal=10+profile.upgrades.heal*4,actual=Math.min(heal,battle.maxPlayerHp-battle.hp);battle.hp+=actual;$('#arena').classList.add('healflash');floatFx('♥ +'+actual,18,72,'#65efab');setTimeout(()=>$('#arena').classList.remove('healflash'),650)}if(id==='crystal'){battle.focus=Math.min(5,battle.focus+1);floatFx('Focus +1',45,68,'#7fe9ff')}if(id==='claw'){battle.rage+=3;floatFx('⚠ +3',55,35,'#ff668a')}renderBattle();await wait(350)}
function damageEnemy(dmg,text,color){battle.enemyHp=Math.max(0,battle.enemyHp-dmg);$('#enemyWrap').classList.add('hit');setTimeout(()=>$('#enemyWrap').classList.remove('hit'),360);floatFx(text,50,35,color);renderBattle()}
async function enemyTurn(){await wait(350);let dmg=intentDamage();if(battle.intent==='drain')battle.enemyHp=Math.min(battle.maxHp,battle.enemyHp+Math.round(dmg*.65));const block=Math.min(battle.shield,dmg);battle.shield-=block;dmg-=block;battle.hp=Math.max(0,battle.hp-dmg);floatFx(dmg?'-'+dmg:'BLOCK',20,72,dmg?'#ff668a':'#7fe9ff');$('#arena').classList.add('hit');setTimeout(()=>$('#arena').classList.remove('hit'),340);await wait(500)}
function burst(){if(!battle||battle.focus<3||battle.busy)return;battle.focus-=3;const dmg=30+profile.upgrades.attack*6;damageEnemy(dmg,'✦ -'+dmg,'#ffe36d');battle.shield+=10;finishTurn()}
function finishTurn(){battle.busy=false;if(battle.enemyHp<=0)return endBattle(true);if(battle.hp<=0)return endBattle(false);rollIntent();renderBattle()}
function endBattle(win){battle.ended=true;const modal=$('#result');modal.hidden=false;$('#resultKicker').textContent=win?'★★★':'◇';$('#resultTitle').textContent=t(win?'win':'lose');$('#resultBody').textContent=t(win?'winBody':'loseBody');const reward=win?battle.reward:Math.max(2,Math.floor(battle.reward*.25));$('#rewardValue').textContent='+'+reward;profile.sparks+=reward;if(win){const stars=battle.hp/battle.maxPlayerHp>.7?3:battle.hp/battle.maxPlayerHp>.35?2:1;profile.best[selectedStage-1]=Math.max(profile.best[selectedStage-1]||0,stars);if(selectedStage===profile.unlocked&&profile.unlocked<30)profile.unlocked++;}save();$('#nextBtn').hidden=!win||selectedStage>=30;$('#retryBtn').hidden=win;renderBattle()}
function floatFx(text,x,y,color){const e=document.createElement('span');e.className='float-fx';e.textContent=text;e.style.left=x+'%';e.style.top=y+'%';e.style.color=color;$('#fxLayer').append(e);setTimeout(()=>e.remove(),950)}
function flashReel(i,color){const r=$$('.reel')[i];if(r){r.style.boxShadow=`0 0 26px ${color}`;setTimeout(()=>r.style.boxShadow='',320)}}
function toast(text){$('#comboBanner').textContent=text;setTimeout(()=>{if($('#comboBanner').textContent===text)$('#comboBanner').textContent=''},1200)}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function leaveToStages(){$('#pauseModal').hidden=true;$('#result').hidden=true;battle=null;show('stagePage');renderStages()}
function bind(){initLocales();$('#startBtn').onclick=()=>{show('stagePage');renderStages()};$('#stageBack').onclick=()=>show('mainPage');$('#helpBtn').onclick=()=>{$('#tutorial').hidden=false};$('#stageRail').addEventListener('scroll',settleRail,{passive:true});$('#enterBattle').onclick=startBattle;$$('.upgrade').forEach(b=>b.onclick=()=>upgrade(b.dataset.upgrade));$('#battleBack').onclick=()=>{$('#pauseModal').hidden=false};$('#pauseBtn').onclick=()=>{$('#pauseModal').hidden=false};$('#resumeBtn').onclick=()=>{$('#pauseModal').hidden=true};$('#leaveBtn').onclick=leaveToStages;$('#spinBtn').onclick=spin;$('#burstBtn').onclick=burst;$('#tutorialClose').onclick=()=>{profile.tutorial=true;save();$('#tutorial').hidden=true};$('#resultStages').onclick=leaveToStages;$('#retryBtn').onclick=startBattle;$('#nextBtn').onclick=()=>{selectedStage=Math.min(30,selectedStage+1);$('#result').hidden=true;startBattle()};document.addEventListener('keydown',e=>{if($('#battlePage').hidden||battle?.busy)return;if(e.code==='Space'){e.preventDefault();spin()}if(['Digit1','Digit2','Digit3'].includes(e.code))toggleHold(Number(e.code.slice(-1))-1)})}
async function preload(){const urls=['../../assets/animal-rune-reels/cover.webp','../../assets/animal-rune-reels/arena.webp','../../assets/weightplay-logo.png',...Object.values(symbols).map(s=>ASSET_ROOT+s.img),...enemyAssets.map(x=>ASSET_ROOT+x)];let done=0;await Promise.all(urls.map(src=>new Promise(resolve=>{const im=new Image;const end=()=>{$('#loadFill').style.width=(++done/urls.length*100)+'%';resolve()};im.onload=end;im.onerror=end;im.src=src})));await wait(180)}
if(trialMode)window.__RUNE_REELS_TEST__={state:()=>battle?JSON.parse(JSON.stringify(battle)):null,forceReels:reels=>{if(battle)battle.forcedReels=reels},setHealth:hp=>{if(battle){battle.hp=Math.max(1,Math.min(battle.maxPlayerHp,hp));renderBattle()}},setEnemyHealth:hp=>{if(battle){battle.enemyHp=Math.max(1,Math.min(battle.maxHp,hp));renderBattle()}},unlockAll:()=>{profile.unlocked=30;save();renderStages()}};
bind();applyLocale();preload().then(()=>{$('#loading').remove();$('#app').hidden=false;show('mainPage')});
})();
