(() => {
  "use strict";
  const L=window.RUNE_REELS_LOCALES;
  const ui={
    en:['Select a slot, then choose an owned hero below.','Choose a hero for the selected slot.','Team slot','Leader ability','No leader ability','Current','Next','per rune','Line ×2'],
    'zh-Hant':['先選擇隊伍欄位，再從下方選擇已擁有的英雄。','為選取的欄位選擇英雄。','隊伍欄位','隊長能力','無隊長能力','目前','下一級','每個符文','連線 ×2'],
    'zh-Hans':['先选择队伍栏位，再从下方选择已拥有的英雄。','为选取的栏位选择英雄。','队伍栏位','队长能力','无队长能力','当前','下一级','每个符文','连线 ×2'],
    ja:['チーム枠を選び、所持ヒーローを選んでください。','選択中の枠に入れるヒーローを選んでください。','チーム枠','リーダー能力','リーダー能力なし','現在','次のレベル','ルーン1個ごと','ライン ×2'],
    ko:['팀 슬롯을 선택한 뒤 보유 영웅을 선택하세요.','선택한 슬롯에 배치할 영웅을 고르세요.','팀 슬롯','리더 능력','리더 능력 없음','현재','다음 레벨','룬 1개당','라인 ×2'],
    es:['Selecciona una ranura y luego un héroe obtenido.','Elige un héroe para la ranura seleccionada.','Ranura de equipo','Habilidad de líder','Sin habilidad de líder','Actual','Siguiente','por runa','Línea ×2'],
    'pt-BR':['Selecione um espaço e depois um herói obtido.','Escolha um herói para o espaço selecionado.','Espaço da equipe','Habilidade de líder','Sem habilidade de líder','Atual','Próximo','por runa','Linha ×2'],
    fr:['Sélectionnez un emplacement, puis un héros obtenu.','Choisissez un héros pour l’emplacement sélectionné.','Emplacement','Compétence de chef','Aucune compétence de chef','Actuel','Suivant','par rune','Ligne ×2'],
    de:['Wähle einen Platz und dann einen erhaltenen Helden.','Wähle einen Helden für den markierten Platz.','Teamplatz','Anführerfähigkeit','Keine Anführerfähigkeit','Aktuell','Nächste Stufe','pro Rune','Reihe ×2'],
    it:['Seleziona uno spazio, poi un eroe ottenuto.','Scegli un eroe per lo spazio selezionato.','Spazio squadra','Abilità leader','Nessuna abilità leader','Attuale','Successivo','per runa','Linea ×2'],
    ru:['Выберите ячейку, затем полученного героя.','Выберите героя для отмеченной ячейки.','Ячейка команды','Навык лидера','Нет навыка лидера','Сейчас','Следующий','за руну','Линия ×2'],
    hi:['पहले टीम स्लॉट, फिर प्राप्त हीरो चुनें।','चुने हुए स्लॉट के लिए हीरो चुनें।','टीम स्लॉट','लीडर क्षमता','कोई लीडर क्षमता नहीं','वर्तमान','अगला स्तर','प्रति रून','लाइन ×2'],
    ar:['اختر خانة فريق، ثم اختر بطلاً تملكه.','اختر بطلاً للخانة المحددة.','خانة الفريق','قدرة القائد','لا توجد قدرة قائد','الحالي','المستوى التالي','لكل رون','خط ×2']
  };
  const uiKeys=['chooseTeamSlot','chooseHeroForSlot','teamSlot','leaderAbility','leaderNone','currentEffect','nextEffect','perRune','lineX2'];
  const leaders={
    en:['Pride Command','All heroes gain 20% ATK.','Flame Circuit','Attack runes gain +15% ATK per rune.','Moonlit Remedy','All heroes gain 20% HEAL.','Treasure Current','Coin rune gains are increased by 25%.','Iron Formation','All heroes gain 20% DEF.','Aurora Heart','Maximum HP is increased by 20%.','Winter Oath','Special rune power is increased by 20%.'],
    'zh-Hant':['獅群號令','全體英雄 ATK +20%。','烈焰迴路','每個攻擊符文額外提供 15% ATK。','月光療法','全體英雄 HEAL +20%。','寶藏洋流','金幣符文收益 +25%。','鋼鐵陣形','全體英雄 DEF +20%。','極光之心','最大 HP +20%。','寒冬誓約','特殊符文威力 +20%。'],
    'zh-Hans':['狮群号令','全体英雄 ATK +20%。','烈焰回路','每个攻击符文额外提供 15% ATK。','月光疗法','全体英雄 HEAL +20%。','宝藏洋流','金币符文收益 +25%。','钢铁阵形','全体英雄 DEF +20%。','极光之心','最大 HP +20%。','寒冬誓约','特殊符文威力 +20%。'],
    ja:['群れの号令','全ヒーローのATKが20%上昇。','炎の回路','攻撃ルーン1個につきATKがさらに15%上昇。','月光の治療','全ヒーローのHEALが20%上昇。','宝の潮流','コインルーンの獲得量が25%上昇。','鉄壁陣形','全ヒーローのDEFが20%上昇。','オーロラの心','最大HPが20%上昇。','冬の誓い','特殊ルーンの威力が20%上昇。'],
    ko:['무리의 명령','모든 영웅의 ATK가 20% 증가합니다.','불꽃 회로','공격 룬 1개당 ATK가 추가로 15% 증가합니다.','달빛 치료','모든 영웅의 HEAL이 20% 증가합니다.','보물의 물결','코인 룬 획득량이 25% 증가합니다.','강철 진형','모든 영웅의 DEF가 20% 증가합니다.','오로라의 심장','최대 HP가 20% 증가합니다.','겨울의 맹세','특수 룬 위력이 20% 증가합니다.'],
    es:['Orden de la manada','Todos los héroes obtienen 20% de ATK.','Circuito ígneo','Las runas de ataque añaden 15% de ATK por runa.','Remedio lunar','Todos los héroes obtienen 20% de HEAL.','Corriente del tesoro','Las runas de moneda otorgan 25% más.','Formación férrea','Todos los héroes obtienen 20% de DEF.','Corazón aurora','El HP máximo aumenta un 20%.','Juramento invernal','El poder de runa especial aumenta un 20%.'],
    'pt-BR':['Comando da alcateia','Todos os heróis ganham 20% de ATK.','Circuito de chamas','Runas de ataque dão +15% de ATK por runa.','Remédio lunar','Todos os heróis ganham 20% de HEAL.','Corrente do tesouro','Runas de moeda rendem 25% a mais.','Formação de ferro','Todos os heróis ganham 20% de DEF.','Coração aurora','O HP máximo aumenta em 20%.','Juramento de inverno','O poder da runa especial aumenta em 20%.'],
    fr:['Ordre de la troupe','Tous les héros gagnent 20 % d’ATK.','Circuit ardent','Les runes d’attaque ajoutent 15 % d’ATK par rune.','Remède lunaire','Tous les héros gagnent 20 % de HEAL.','Courant au trésor','Les runes de pièces rapportent 25 % de plus.','Formation de fer','Tous les héros gagnent 20 % de DEF.','Cœur boréal','Les HP maximum augmentent de 20 %.','Serment d’hiver','La puissance de rune spéciale augmente de 20 %.'],
    de:['Rudelkommando','Alle Helden erhalten 20 % ATK.','Flammenkreis','Angriffsrunen geben zusätzlich 15 % ATK je Rune.','Mondheilung','Alle Helden erhalten 20 % HEAL.','Schatzstrom','Münzrunen bringen 25 % mehr.','Eisenformation','Alle Helden erhalten 20 % DEF.','Auroraherz','Maximale HP steigen um 20 %.','Winterschwur','Spezialrunenkraft steigt um 20 %.'],
    it:['Comando del branco','Tutti gli eroi ottengono 20% ATK.','Circuito ardente','Le rune attacco danno +15% ATK per runa.','Rimedio lunare','Tutti gli eroi ottengono 20% HEAL.','Corrente del tesoro','Le rune moneta rendono il 25% in più.','Formazione ferrea','Tutti gli eroi ottengono 20% DEF.','Cuore aurora','Gli HP massimi aumentano del 20%.','Giuramento invernale','La potenza della runa speciale aumenta del 20%.'],
    ru:['Команда стаи','Все герои получают +20% ATK.','Огненный контур','Руны атаки дают ещё +15% ATK за руну.','Лунное лечение','Все герои получают +20% HEAL.','Поток сокровищ','Руны монет дают на 25% больше.','Железный строй','Все герои получают +20% DEF.','Сердце авроры','Максимум HP увеличен на 20%.','Зимняя клятва','Сила особой руны увеличена на 20%.'],
    hi:['दल का आदेश','सभी हीरो को 20% ATK मिलता है।','अग्नि परिपथ','हर अटैक रून पर 15% अतिरिक्त ATK।','चंद्र उपचार','सभी हीरो को 20% HEAL मिलता है।','खजाने की धारा','कॉइन रून से 25% अधिक सिक्के।','लौह गठन','सभी हीरो को 20% DEF मिलता है।','ऑरोरा हृदय','अधिकतम HP 20% बढ़ता है।','शीत शपथ','स्पेशल रून की शक्ति 20% बढ़ती है।'],
    ar:['أمر القطيع','يحصل جميع الأبطال على ATK‏ +20%.','دائرة اللهب','تضيف رون الهجوم ATK‏ +15% لكل رون.','علاج القمر','يحصل جميع الأبطال على HEAL‏ +20%.','تيار الكنز','تزيد مكاسب رون العملات بنسبة 25%.','تشكيل الحديد','يحصل جميع الأبطال على DEF‏ +20%.','قلب الشفق','يزداد الحد الأقصى للصحة 20%.','قسم الشتاء','تزداد قوة الرون الخاص 20%.']
  };
  const leaderKeys=['leaderLion','leaderLionDesc','leaderFox','leaderFoxDesc','leaderOwl','leaderOwlDesc','leaderOtter','leaderOtterDesc','leaderRhino','leaderRhinoDesc','leaderAstra','leaderAstraDesc','leaderNyra','leaderNyraDesc'];
  const specials={
    en:['Three sequential strikes deal 2.5× ATK in total.','Attack, then heal for half the damage dealt.','Heal for 1.5× HEAL and grant a 1.5× DEF shield.','Grant a 2.3× DEF shield and reduce the next enemy hit by 30%.','Heal for 2.1× HEAL and grant a 2.1× DEF shield.','Deal 3.2× ATK and reduce the next enemy hit by 15%.','Each attack rune gives every hero +20% ATK. A completed line doubles the rune effect.'],
    'zh-Hant':['依序攻擊三次，合計造成 2.5× ATK。','攻擊後，回復造成傷害一半的 HP。','回復 1.5× HEAL，並獲得 1.5× DEF 護盾。','獲得 2.3× DEF 護盾，下一次敵方傷害降低 30%。','回復 2.1× HEAL，並獲得 2.1× DEF 護盾。','造成 3.2× ATK，下一次敵方傷害降低 15%。','每個攻擊符文使全體英雄 ATK +20%；完成連線時效果加倍。'],
    'zh-Hans':['依次攻击三次，合计造成 2.5× ATK。','攻击后，回复造成伤害一半的 HP。','回复 1.5× HEAL，并获得 1.5× DEF 护盾。','获得 2.3× DEF 护盾，下一次敌方伤害降低 30%。','回复 2.1× HEAL，并获得 2.1× DEF 护盾。','造成 3.2× ATK，下一次敌方伤害降低 15%。','每个攻击符文使全体英雄 ATK +20%；完成连线时效果加倍。'],
    ja:['3回連続で攻撃し、合計2.5×ATKのダメージ。','攻撃後、与えたダメージの半分だけHPを回復。','1.5×HEALを回復し、1.5×DEFのシールドを付与。','2.3×DEFのシールドを付与し、次の敵ダメージを30%軽減。','2.1×HEALを回復し、2.1×DEFのシールドを付与。','3.2×ATKのダメージを与え、次の敵ダメージを15%軽減。','攻撃ルーン1個で全ヒーローのATKが20%上昇。ライン完成で効果2倍。'],
    ko:['3회 연속 공격해 총 2.5× ATK 피해를 줍니다.','공격 후 준 피해의 절반만큼 HP를 회복합니다.','1.5× HEAL을 회복하고 1.5× DEF 보호막을 얻습니다.','2.3× DEF 보호막을 얻고 다음 적 피해를 30% 줄입니다.','2.1× HEAL을 회복하고 2.1× DEF 보호막을 얻습니다.','3.2× ATK 피해를 주고 다음 적 피해를 15% 줄입니다.','공격 룬 1개마다 모든 영웅의 ATK가 20% 증가합니다. 라인은 효과가 2배입니다.'],
    es:['Tres golpes seguidos infligen 2,5× ATK en total.','Ataca y cura la mitad del daño infligido.','Cura 1,5× HEAL y otorga un escudo de 1,5× DEF.','Otorga 2,3× DEF de escudo y reduce un 30% el próximo golpe enemigo.','Cura 2,1× HEAL y otorga un escudo de 2,1× DEF.','Inflige 3,2× ATK y reduce un 15% el próximo golpe enemigo.','Cada runa de ataque da +20% ATK a todos. Una línea duplica el efecto.'],
    'pt-BR':['Três golpes seguidos causam 2,5× ATK no total.','Ataca e cura metade do dano causado.','Cura 1,5× HEAL e concede escudo de 1,5× DEF.','Concede escudo de 2,3× DEF e reduz o próximo golpe inimigo em 30%.','Cura 2,1× HEAL e concede escudo de 2,1× DEF.','Causa 3,2× ATK e reduz o próximo golpe inimigo em 15%.','Cada runa de ataque dá +20% ATK a todos. Uma linha duplica o efeito.'],
    fr:['Trois frappes successives infligent 2,5× ATK au total.','Attaque, puis soigne la moitié des dégâts infligés.','Soigne 1,5× HEAL et accorde un bouclier de 1,5× DEF.','Accorde un bouclier de 2,3× DEF et réduit de 30 % le prochain coup ennemi.','Soigne 2,1× HEAL et accorde un bouclier de 2,1× DEF.','Inflige 3,2× ATK et réduit de 15 % le prochain coup ennemi.','Chaque rune d’attaque donne +20 % ATK à tous. Une ligne double l’effet.'],
    de:['Drei Treffer verursachen zusammen 2,5× ATK.','Greift an und heilt die Hälfte des verursachten Schadens.','Heilt 1,5× HEAL und gibt 1,5× DEF als Schild.','Gibt 2,3× DEF als Schild und senkt den nächsten Gegnertreffer um 30 %.','Heilt 2,1× HEAL und gibt 2,1× DEF als Schild.','Verursacht 3,2× ATK und senkt den nächsten Gegnertreffer um 15 %.','Jede Angriffsrune gibt allen +20 % ATK. Eine Reihe verdoppelt den Effekt.'],
    it:['Tre colpi consecutivi infliggono 2,5× ATK in totale.','Attacca e cura metà del danno inflitto.','Cura 1,5× HEAL e concede uno scudo di 1,5× DEF.','Concede uno scudo di 2,3× DEF e riduce del 30% il prossimo colpo nemico.','Cura 2,1× HEAL e concede uno scudo di 2,1× DEF.','Infligge 3,2× ATK e riduce del 15% il prossimo colpo nemico.','Ogni runa attacco dà +20% ATK a tutti. Una linea raddoppia l’effetto.'],
    ru:['Три последовательных удара наносят суммарно 2,5× ATK.','Атакует и лечит на половину нанесённого урона.','Лечит на 1,5× HEAL и даёт щит 1,5× DEF.','Даёт щит 2,3× DEF и снижает следующий удар врага на 30%.','Лечит на 2,1× HEAL и даёт щит 2,1× DEF.','Наносит 3,2× ATK и снижает следующий удар врага на 15%.','Каждая руна атаки даёт всем +20% ATK. Линия удваивает эффект.'],
    hi:['तीन लगातार वार कुल 2.5× ATK नुकसान देते हैं।','हमला करके हुए नुकसान के आधे के बराबर HP भरता है।','1.5× HEAL भरता और 1.5× DEF शील्ड देता है।','2.3× DEF शील्ड देता और अगला दुश्मन वार 30% घटाता है।','2.1× HEAL भरता और 2.1× DEF शील्ड देता है।','3.2× ATK नुकसान देता और अगला दुश्मन वार 15% घटाता है।','हर अटैक रून सबको +20% ATK देता है। लाइन पर प्रभाव दोगुना।'],
    ar:['ثلاث ضربات متتالية تسبب إجمالاً 2.5× ATK.','يهاجم ثم يعالج نصف الضرر الذي سببه.','يعالج 1.5× HEAL ويمنح درع 1.5× DEF.','يمنح درع 2.3× DEF ويخفض ضربة العدو التالية 30%.','يعالج 2.1× HEAL ويمنح درع 2.1× DEF.','يسبب 3.2× ATK ويخفض ضربة العدو التالية 15%.','كل رون هجوم يمنح الجميع ATK‏ +20%. الخط يضاعف التأثير.']
  };
  const specialKeys=['specialFoxDesc','specialOwlDesc','specialOtterDesc','specialRhinoDesc','specialAstraDesc','specialNyraDesc','runeAttackDesc'];
  const variedKeys=['specialLionDesc','specialTurtleDesc','specialRabbitDesc','specialPandaDesc','specialFoxDesc','specialOwlDesc','specialOtterDesc','specialRhinoDesc','specialAstraDesc','specialNyraDesc'];
  const varied={
    en:['Hit every enemy for 1.6× ATK.','Gain a 2.6× DEF shield and reflect 50% of blocked damage.','Heal 3.2× HEAL and charge the next normal attack by 20%.','Hit every enemy for 1.5× ATK and reduce the next enemy hit by 15%.','Strike three times for 2.5× ATK in total.','Hit every enemy for 1.25× ATK and heal 35% of total damage.','Heal 1.4× HEAL and boost every remaining rune effect this Spin by 25%.','Gain a 1.4× DEF shield, reduce the next hit by 20%, then charge every enemy.','Hit every enemy for 1.6× ATK and heal 50% of 1.6× HEAL.','Hit every enemy for 2.2× ATK and reduce the next enemy hit by 20%.'],
    'zh-Hant':['對所有敵人造成 1.6× ATK。','獲得 2.6× DEF 護盾，並反射 50% 被阻擋的傷害。','回復 3.2× HEAL，下一次普通攻擊額外 +20%。','對所有敵人造成 1.5× ATK，下一次敵方傷害降低 15%。','連續攻擊三次，合計造成 2.5× ATK。','對所有敵人造成 1.25× ATK，並回復總傷害 35% 的 HP。','回復 1.4× HEAL，本次轉輪剩餘所有符石效果 +25%。','獲得 1.4× DEF 護盾、降低下次傷害 20%，再衝撞所有敵人。','對所有敵人造成 1.6× ATK，並回復 1.6× HEAL 的 50%。','對所有敵人造成 2.2× ATK，下一次敵方傷害降低 20%。'],
    'zh-Hans':['对所有敌人造成 1.6× ATK。','获得 2.6× DEF 护盾，并反射 50% 被阻挡的伤害。','回复 3.2× HEAL，下一次普通攻击额外 +20%。','对所有敌人造成 1.5× ATK，下一次敌方伤害降低 15%。','连续攻击三次，合计造成 2.5× ATK。','对所有敌人造成 1.25× ATK，并回复总伤害 35% 的 HP。','回复 1.4× HEAL，本次转轮剩余所有符石效果 +25%。','获得 1.4× DEF 护盾、降低下次伤害 20%，再冲撞所有敌人。','对所有敌人造成 1.6× ATK，并回复 1.6× HEAL 的 50%。','对所有敌人造成 2.2× ATK，下一次敌方伤害降低 20%。'],
    ja:['全敵に1.6×ATKのダメージ。','2.6×DEFのシールドを得て、ブロックしたダメージの50%を反射。','3.2×HEALを回復し、次の通常攻撃を20%強化。','全敵に1.5×ATKを与え、次の敵ダメージを15%軽減。','3回攻撃し、合計2.5×ATKのダメージ。','全敵に1.25×ATKを与え、総ダメージの35%を回復。','1.4×HEALを回復し、このスピンの残り全ルーン効果を25%強化。','1.4×DEFシールドと20%軽減を得て、全敵へ突進。','全敵に1.6×ATKを与え、1.6×HEALの50%を回復。','全敵に2.2×ATKを与え、次の敵ダメージを20%軽減。'],
    ko:['모든 적에게 1.6× ATK 피해를 줍니다.','2.6× DEF 보호막을 얻고 막은 피해의 50%를 반사합니다.','3.2× HEAL을 회복하고 다음 일반 공격을 20% 강화합니다.','모든 적에게 1.5× ATK 피해를 주고 다음 적 피해를 15% 줄입니다.','3회 공격해 총 2.5× ATK 피해를 줍니다.','모든 적에게 1.25× ATK 피해를 주고 총 피해의 35%를 회복합니다.','1.4× HEAL을 회복하고 이번 스핀의 남은 모든 룬 효과를 25% 강화합니다.','1.4× DEF 보호막과 20% 피해 감소를 얻은 뒤 모든 적을 돌진합니다.','모든 적에게 1.6× ATK 피해를 주고 1.6× HEAL의 50%를 회복합니다.','모든 적에게 2.2× ATK 피해를 주고 다음 적 피해를 20% 줄입니다.'],
    es:['Golpea a todos por 1,6× ATK.','Obtén 2,6× DEF de escudo y refleja el 50% del daño bloqueado.','Cura 3,2× HEAL y potencia un 20% el próximo ataque normal.','Golpea a todos por 1,5× ATK y reduce un 15% el próximo golpe enemigo.','Ataca tres veces por 2,5× ATK total.','Golpea a todos por 1,25× ATK y cura el 35% del daño total.','Cura 1,4× HEAL y aumenta un 25% todas las runas restantes de este giro.','Obtén 1,4× DEF de escudo, 20% de reducción y embiste a todos.','Golpea a todos por 1,6× ATK y cura el 50% de 1,6× HEAL.','Golpea a todos por 2,2× ATK y reduce un 20% el próximo golpe enemigo.'],
    'pt-BR':['Atinge todos por 1,6× ATK.','Ganha escudo de 2,6× DEF e reflete 50% do dano bloqueado.','Cura 3,2× HEAL e fortalece o próximo ataque normal em 20%.','Atinge todos por 1,5× ATK e reduz o próximo golpe inimigo em 15%.','Ataca três vezes, totalizando 2,5× ATK.','Atinge todos por 1,25× ATK e cura 35% do dano total.','Cura 1,4× HEAL e aumenta em 25% todas as runas restantes deste giro.','Ganha escudo de 1,4× DEF, 20% de redução e investe contra todos.','Atinge todos por 1,6× ATK e cura 50% de 1,6× HEAL.','Atinge todos por 2,2× ATK e reduz o próximo golpe inimigo em 20%.'],
    fr:['Frappe tous les ennemis pour 1,6× ATK.','Gagne un bouclier de 2,6× DEF et renvoie 50 % des dégâts bloqués.','Soigne 3,2× HEAL et renforce de 20 % la prochaine attaque normale.','Frappe tous pour 1,5× ATK et réduit de 15 % le prochain coup ennemi.','Frappe trois fois pour un total de 2,5× ATK.','Frappe tous pour 1,25× ATK et soigne 35 % des dégâts totaux.','Soigne 1,4× HEAL et renforce de 25 % toutes les runes restantes de ce tour.','Gagne 1,4× DEF de bouclier, 20 % de réduction, puis charge tous les ennemis.','Frappe tous pour 1,6× ATK et soigne 50 % de 1,6× HEAL.','Frappe tous pour 2,2× ATK et réduit de 20 % le prochain coup ennemi.'],
    de:['Trifft alle Gegner mit 1,6× ATK.','Erhält 2,6× DEF als Schild und reflektiert 50 % des geblockten Schadens.','Heilt 3,2× HEAL und stärkt den nächsten normalen Angriff um 20 %.','Trifft alle mit 1,5× ATK und senkt den nächsten Gegnertreffer um 15 %.','Greift dreimal für insgesamt 2,5× ATK an.','Trifft alle mit 1,25× ATK und heilt 35 % des Gesamtschadens.','Heilt 1,4× HEAL und verstärkt alle übrigen Runen dieses Drehs um 25 %.','Erhält 1,4× DEF Schild, 20 % Reduktion und stürmt durch alle Gegner.','Trifft alle mit 1,6× ATK und heilt 50 % von 1,6× HEAL.','Trifft alle mit 2,2× ATK und senkt den nächsten Gegnertreffer um 20 %.'],
    it:['Colpisce tutti i nemici con 1,6× ATK.','Ottiene uno scudo di 2,6× DEF e riflette il 50% del danno bloccato.','Cura 3,2× HEAL e potenzia del 20% il prossimo attacco normale.','Colpisce tutti con 1,5× ATK e riduce del 15% il prossimo colpo nemico.','Attacca tre volte per un totale di 2,5× ATK.','Colpisce tutti con 1,25× ATK e cura il 35% del danno totale.','Cura 1,4× HEAL e potenzia del 25% tutte le rune restanti di questo giro.','Ottiene 1,4× DEF di scudo, 20% riduzione e carica tutti i nemici.','Colpisce tutti con 1,6× ATK e cura il 50% di 1,6× HEAL.','Colpisce tutti con 2,2× ATK e riduce del 20% il prossimo colpo nemico.'],
    ru:['Наносит всем врагам 1,6× ATK.','Даёт щит 2,6× DEF и отражает 50% заблокированного урона.','Лечит на 3,2× HEAL и усиливает следующую обычную атаку на 20%.','Наносит всем 1,5× ATK и снижает следующий удар врага на 15%.','Трижды атакует, суммарно нанося 2,5× ATK.','Наносит всем 1,25× ATK и лечит 35% общего урона.','Лечит на 1,4× HEAL и усиливает все оставшиеся руны хода на 25%.','Даёт щит 1,4× DEF, 20% снижения и таранит всех врагов.','Наносит всем 1,6× ATK и лечит 50% от 1,6× HEAL.','Наносит всем 2,2× ATK и снижает следующий удар врага на 20%.'],
    hi:['सभी दुश्मनों को 1.6× ATK नुकसान।','2.6× DEF शील्ड और रोके नुकसान का 50% पलटवार।','3.2× HEAL भरता और अगला सामान्य हमला 20% बढ़ाता है।','सभी को 1.5× ATK नुकसान और अगला दुश्मन वार 15% कम।','तीन वार, कुल 2.5× ATK नुकसान।','सभी को 1.25× ATK नुकसान और कुल नुकसान का 35% उपचार।','1.4× HEAL भरता और इस स्पिन के सभी बचे रून 25% बढ़ाता है।','1.4× DEF शील्ड, 20% कमी और सभी दुश्मनों पर धावा।','सभी को 1.6× ATK नुकसान और 1.6× HEAL का 50% उपचार।','सभी को 2.2× ATK नुकसान और अगला दुश्मन वार 20% कम।'],
    ar:['يصيب جميع الأعداء بضرر 1.6× ATK.','يمنح درع 2.6× DEF ويرد 50% من الضرر المحجوب.','يعالج 3.2× HEAL ويقوي الهجوم العادي التالي 20%.','يصيب الجميع بضرر 1.5× ATK ويخفض الضربة التالية 15%.','يهاجم ثلاث مرات بإجمالي 2.5× ATK.','يصيب الجميع بضرر 1.25× ATK ويعالج 35% من الضرر الكلي.','يعالج 1.4× HEAL ويقوي كل الرونات المتبقية في هذه اللفة 25%.','يمنح درع 1.4× DEF وتخفيض 20% ثم يندفع عبر جميع الأعداء.','يصيب الجميع بضرر 1.6× ATK ويعالج 50% من 1.6× HEAL.','يصيب الجميع بضرر 2.2× ATK ويخفض الضربة التالية 20%.']
  };
  const otterUpdates={
    en:['Rune Current','All rune effects are increased by 10%.','Tidal Resonance'],'zh-Hant':['符文洋流','所有符石效果 +10%。','潮汐共鳴'],'zh-Hans':['符文洋流','所有符石效果 +10%。','潮汐共鸣'],ja:['ルーン潮流','全ルーン効果が10%上昇。','潮流共鳴'],ko:['룬의 물결','모든 룬 효과가 10% 증가합니다.','해류 공명'],es:['Corriente rúnica','Todos los efectos de runa aumentan un 10%.','Resonancia de marea'],'pt-BR':['Corrente rúnica','Todos os efeitos de runa aumentam em 10%.','Ressonância da maré'],fr:['Courant runique','Tous les effets de rune augmentent de 10 %.','Résonance des marées'],de:['Runenstrom','Alle Runeneffekte steigen um 10 %.','Gezeitenresonanz'],it:['Corrente runica','Tutti gli effetti runa aumentano del 10%.','Risonanza di marea'],ru:['Рунный поток','Все эффекты рун усилены на 10%.','Резонанс прилива'],hi:['रून धारा','सभी रून प्रभाव 10% बढ़ते हैं।','ज्वार अनुनाद'],ar:['تيار الرون','تزداد كل تأثيرات الرون 10%.','رنين المد']
  };
  const allRunesBoosted={en:'All runes','zh-Hant':'所有符石','zh-Hans':'所有符石',ja:'全ルーン',ko:'모든 룬',es:'Todas las runas','pt-BR':'Todas as runas',fr:'Toutes les runes',de:'Alle Runen',it:'Tutte le rune',ru:'Все руны',hi:'सभी रून',ar:'كل الرونات'};
  const dailyCoinBonus={
    en:'Coin rune rewards ×3','zh-Hant':'金幣符文收益 ×3','zh-Hans':'金币符文收益 ×3',ja:'コインルーン報酬 ×3',ko:'코인 룬 보상 ×3',es:'Recompensas de runa moneda ×3','pt-BR':'Recompensas da runa de moeda ×3',fr:'Gains des runes de pièces ×3',de:'Münzrunen-Erträge ×3',it:'Ricompense runa moneta ×3',ru:'Доход от рун монет ×3',hi:'सिक्का रूण पुरस्कार ×3',ar:'مكافآت رونة العملات ×3'
  };
  const stageSelection={
    en:'Rift selection','zh-Hant':'裂隙選擇','zh-Hans':'裂隙选择',ja:'裂け目選択',ko:'균열 선택',es:'Selección de grieta','pt-BR':'Seleção de fenda',fr:'Sélection de faille',de:'Spaltauswahl',it:'Selezione frattura',ru:'Выбор разлома',hi:'दरार चयन',ar:'اختيار الصدع'
  };
  Object.keys(L).forEach(code=>{
    const map={};uiKeys.forEach((key,i)=>map[key]=(ui[code]||ui.en)[i]);leaderKeys.forEach((key,i)=>map[key]=(leaders[code]||leaders.en)[i]);
    const translated=specials[code]||specials.en;specialKeys.forEach((key,i)=>map[key]=translated[i]);const richer=varied[code]||varied.en;variedKeys.forEach((key,i)=>map[key]=richer[i]);const otter=otterUpdates[code]||otterUpdates.en;Object.assign(map,{leaderOtter:otter[0],leaderOtterDesc:otter[1],specialOtter:otter[2],allRunesBoosted:allRunesBoosted[code]||allRunesBoosted.en,dailyCoinBonus:dailyCoinBonus[code]||dailyCoinBonus.en,stageSelection:stageSelection[code]||stageSelection.en});Object.assign(L[code],map);
  });
})();
