(() => {
  "use strict";
  const en = { loading:"Opening the folio…", title:"Firefly Folio", kicker:"A calm route-code puzzle", intro:"Read the field note, then trace the exact three-turn route to the firefly's lantern.", start:"Open the first folio", choose:"Choose a folio", best:"Best turns", noBest:"Not yet", guideTitle:"How to play", guideOne:"Read the destination clue.", guideTwo:"Tap the four direction cards to trace the route.", guideThree:"A wrong route clears gently; no timer or lives are used.", back:"Back", settings:"Settings", language:"Language", stages:"Folio pages", round:"Page {n} of {total}", open:"Open", complete:"Complete", note1:"From the moss stone, go east, then north, then east to the lantern.", note2:"Leave the reeds by going north, west, then north.", note3:"Follow the moonlit fence: west, south, then east.", routeLabel:"Your route", check:"Check route", clear:"Clear route", turnCount:"{n} turns", waiting:"Choose a direction card.", wrong:"That route misses the lantern. The page is clear for another try.", correct:"The firefly found its lantern!", resultTitle:"Folio complete", resultPartial:"Page complete", resultText:"You guided {count} of {total} pages in {turns} turns.", next:"Next page", map:"Folio pages", home:"Back to menu", north:"North", east:"East", south:"South", west:"West" };
  const tables = { en,
    "zh-Hant":{...en,title:"螢火筆記",kicker:"平靜的路線密碼益智",intro:"讀懂田野筆記，再畫出通往螢火蟲燈盞的三步路線。",start:"開啟第一頁",choose:"選擇筆記",best:"最佳步數",noBest:"尚無紀錄",guideTitle:"玩法",guideOne:"讀懂目的地線索。",guideTwo:"點選四張方向卡畫出路線。",guideThree:"走錯會平靜清空；沒有計時或生命。",back:"返回",settings:"設定",language:"語言",stages:"筆記頁面",round:"第 {n} 頁／共 {total} 頁",open:"開啟",complete:"完成",note1:"從苔蘚石向東、向北，再向東到燈盞。",note2:"向北、向西，再向北離開蘆葦。",note3:"沿著月光籬笆：向西、向南，再向東。",routeLabel:"你的路線",check:"檢查路線",clear:"清除路線",turnCount:"{n} 步",waiting:"請選一張方向卡。",wrong:"這條路線錯過燈盞，頁面已清空，請再試一次。",correct:"螢火蟲找到燈盞了！",resultTitle:"筆記完成",resultPartial:"頁面完成",resultText:"你用 {turns} 步引導 {count}／{total} 頁。",next:"下一頁",map:"筆記頁面",home:"返回選單",north:"北",east:"東",south:"南",west:"西"},
    "zh-Hans":{...en,title:"萤火笔记",intro:"读懂田野笔记，再画出通往萤火虫灯盏的三步路线。",start:"打开第一页",choose:"选择笔记",stages:"笔记页面",back:"返回",check:"检查路线",clear:"清除路线",wrong:"路线错过灯盏，页面已清空，请再试一次。",correct:"萤火虫找到灯盏了！",next:"下一页",map:"笔记页面",home:"返回菜单"},
    ja:{...en,title:"ホタルの手帳",intro:"野帳を読み、ホタルの灯りまで3手の道順をたどります。",start:"最初のページを開く",choose:"ページを選ぶ",stages:"手帳のページ",back:"戻る",check:"道順を確認",clear:"道順を消す",wrong:"灯りに届かない道順です。もう一度。",correct:"ホタルが灯りを見つけました！",next:"次のページ",map:"ページ一覧",home:"メニューへ"},
    ko:{...en,title:"반딧불 기록장",intro:"현장 기록을 읽고 반딧불 등불까지 세 번의 길을 그려 보세요.",start:"첫 페이지 열기",choose:"기록 선택",stages:"기록 페이지",back:"뒤로",check:"경로 확인",clear:"경로 지우기",wrong:"등불을 놓친 경로예요. 다시 시도하세요.",correct:"반딧불이 등불을 찾았어요!",next:"다음 페이지",map:"기록 페이지",home:"메뉴로"},
    es:{...en,title:"Cuaderno de Luciérnagas",intro:"Lee la nota y traza la ruta exacta de tres giros hasta la linterna.",start:"Abrir la primera página",choose:"Elegir página",stages:"Páginas",back:"Atrás",check:"Comprobar ruta",clear:"Borrar ruta",wrong:"La ruta no llega a la linterna. Inténtalo otra vez.",correct:"¡La luciérnaga encontró su linterna!",next:"Siguiente página",map:"Páginas",home:"Al menú"},
    "pt-BR":{...en,title:"Caderno dos Vaga-lumes",intro:"Leia a nota e trace a rota exata de três giros até a lanterna.",start:"Abrir a primeira página",choose:"Escolher página",stages:"Páginas",back:"Voltar",check:"Conferir rota",clear:"Limpar rota",wrong:"A rota não chega à lanterna. Tente de novo.",correct:"O vaga-lume encontrou sua lanterna!",next:"Próxima página",map:"Páginas",home:"Ao menu"},
    fr:{...en,title:"Carnet des Lucioles",intro:"Lis la note et trace le trajet exact de trois virages jusqu’à la lanterne.",start:"Ouvrir la première page",choose:"Choisir une page",stages:"Pages",back:"Retour",check:"Vérifier le trajet",clear:"Effacer le trajet",wrong:"Ce trajet manque la lanterne. Réessaie.",correct:"La luciole a trouvé sa lanterne !",next:"Page suivante",map:"Pages",home:"Au menu"},
    de:{...en,title:"Glühwürmchen-Folio",intro:"Lies den Feldhinweis und zeichne den genauen Dreischritt zur Laterne.",start:"Erste Seite öffnen",choose:"Seite wählen",stages:"Folio-Seiten",back:"Zurück",check:"Route prüfen",clear:"Route löschen",wrong:"Diese Route verfehlt die Laterne. Versuch es erneut.",correct:"Das Glühwürmchen hat die Laterne gefunden!",next:"Nächste Seite",map:"Folio-Seiten",home:"Zum Menü"},
    it:{...en,title:"Taccuino delle Lucciole",intro:"Leggi la nota e traccia il percorso esatto di tre svolte fino alla lanterna.",start:"Apri la prima pagina",choose:"Scegli pagina",stages:"Pagine",back:"Indietro",check:"Controlla percorso",clear:"Cancella percorso",wrong:"Il percorso non arriva alla lanterna. Riprova.",correct:"La lucciola ha trovato la lanterna!",next:"Pagina seguente",map:"Pagine",home:"Al menu"},
    ru:{...en,title:"Альбом светлячка",intro:"Прочитайте заметку и проложите точный маршрут из трёх поворотов к фонарю.",start:"Открыть первую страницу",choose:"Выбрать страницу",stages:"Страницы",back:"Назад",check:"Проверить путь",clear:"Очистить путь",wrong:"Путь не ведёт к фонарю. Попробуйте ещё раз.",correct:"Светлячок нашёл фонарь!",next:"Следующая страница",map:"Страницы",home:"В меню"},
    hi:{...en,title:"जुगनू पुस्तिका",intro:"मैदानी नोट पढ़ें और जुगनू की लालटेन तक तीन मोड़ का सही रास्ता बनाएँ।",start:"पहला पन्ना खोलें",choose:"पन्ना चुनें",stages:"पन्ने",back:"वापस",check:"रास्ता जाँचें",clear:"रास्ता साफ़ करें",wrong:"यह रास्ता लालटेन तक नहीं पहुँचा। फिर प्रयास करें।",correct:"जुगनू को अपनी लालटेन मिल गई!",next:"अगला पन्ना",map:"पन्ने",home:"मेनू पर"},
    ar:{...en,title:"دفتر اليراعات",intro:"اقرأ ملاحظة الحقل وارسم المسار الدقيق بثلاث منعطفات إلى الفانوس.",start:"افتح الصفحة الأولى",choose:"اختر صفحة",stages:"صفحات الدفتر",back:"رجوع",check:"تحقق من المسار",clear:"امسح المسار",wrong:"هذا المسار لا يصل إلى الفانوس. حاول مجدداً.",correct:"وجدت اليراعة فانوسها!",next:"الصفحة التالية",map:"صفحات الدفتر",home:"إلى القائمة"}
  };
  const sharedExtras = {
    "zh-Hans": { guideTitle:"玩法", guideOne:"读懂目的地线索。", guideTwo:"点击四张方向卡画出路线。", guideThree:"走错会平静清空；没有计时或生命。", note1:"从苔藓石向东、向北，再向东到灯盏。", note2:"向北、向西，再向北离开芦苇。", note3:"沿着月光篱笆：向西、向南，再向东。", routeLabel:"你的路线", waiting:"请选择一张方向卡。", turnCount:"{n} 步", north:"北", east:"东", south:"南", west:"西", resultPartial:"页面完成", resultText:"你用 {turns} 步引导 {count}／{total} 页。" },
    ja: { guideTitle:"遊び方", guideOne:"目的地の手がかりを読む。", guideTwo:"4枚の方向カードで道順をたどる。", guideThree:"間違えた道順は静かに消えます。タイマーもライフもありません。", note1:"苔の石から東、北、東へ灯りに向かう。", note2:"北、西、北へ進んでアシを抜ける。", note3:"月明かりの柵を西、南、東へ進む。", routeLabel:"あなたの道順", waiting:"方向カードを選びます。", turnCount:"{n} 手", north:"北", east:"東", south:"南", west:"西", resultPartial:"ページ完了", resultText:"{turns} 手で {count}/{total} ページを案内しました。" },
    ko: { guideTitle:"게임 방법", guideOne:"목적지 단서를 읽으세요.", guideTwo:"네 방향 카드로 경로를 따라가세요.", guideThree:"틀린 경로는 조용히 지워집니다. 타이머와 목숨은 없어요.", note1:"이끼 돌에서 동쪽, 북쪽, 다시 동쪽 등불로 가세요.", note2:"북쪽, 서쪽, 북쪽으로 갈대를 빠져나오세요.", note3:"달빛 울타리를 서쪽, 남쪽, 동쪽으로 따라가세요.", routeLabel:"내 경로", waiting:"방향 카드를 선택하세요.", turnCount:"{n}번", north:"북", east:"동", south:"남", west:"서", resultPartial:"페이지 완료", resultText:"{turns}번으로 {count}/{total}페이지를 안내했어요." },
    es: { guideTitle:"Cómo jugar", guideOne:"Lee la pista del destino.", guideTwo:"Toca las cuatro tarjetas de dirección para trazar la ruta.", guideThree:"Una ruta incorrecta se borra con calma; no hay tiempo ni vidas.", note1:"Desde la piedra de musgo, ve este, norte y este hasta la linterna.", note2:"Sal de los juncos: norte, oeste y norte.", note3:"Sigue la valla lunar: oeste, sur y este.", routeLabel:"Tu ruta", waiting:"Elige una tarjeta de dirección.", turnCount:"{n} giros", north:"Norte", east:"Este", south:"Sur", west:"Oeste", resultPartial:"Página completa", resultText:"Guiaste {count} de {total} páginas en {turns} giros." },
    "pt-BR": { guideTitle:"Como jogar", guideOne:"Leia a pista do destino.", guideTwo:"Toque nas quatro cartas de direção para traçar a rota.", guideThree:"Uma rota errada é limpa com calma; não há tempo nem vidas.", note1:"Da pedra de musgo, siga leste, norte e leste até a lanterna.", note2:"Saia dos juncos: norte, oeste e norte.", note3:"Siga a cerca iluminada: oeste, sul e leste.", routeLabel:"Sua rota", waiting:"Escolha uma carta de direção.", turnCount:"{n} giros", north:"Norte", east:"Leste", south:"Sul", west:"Oeste", resultPartial:"Página completa", resultText:"Você guiou {count} de {total} páginas em {turns} giros." },
    fr: { guideTitle:"Comment jouer", guideOne:"Lis l’indice de destination.", guideTwo:"Touche les quatre cartes de direction pour tracer le trajet.", guideThree:"Un mauvais trajet s’efface calmement ; pas de chrono ni de vies.", note1:"Depuis la pierre moussue, va à l’est, au nord, puis à l’est vers la lanterne.", note2:"Quitte les roseaux par le nord, l’ouest, puis le nord.", note3:"Suis la clôture au clair de lune : ouest, sud, est.", routeLabel:"Ton trajet", waiting:"Choisis une carte de direction.", turnCount:"{n} tours", north:"Nord", east:"Est", south:"Sud", west:"Ouest", resultPartial:"Page terminée", resultText:"Tu as guidé {count} pages sur {total} en {turns} tours." },
    de: { guideTitle:"So wird gespielt", guideOne:"Lies den Zielhinweis.", guideTwo:"Tippe die vier Richtungskarten, um die Route zu zeichnen.", guideThree:"Eine falsche Route wird ruhig gelöscht; ohne Timer oder Leben.", note1:"Vom Moosstein nach Osten, Norden und wieder Osten zur Laterne.", note2:"Verlasse das Schilf nach Norden, Westen und Norden.", note3:"Folge dem Mondzaun: Westen, Süden, Osten.", routeLabel:"Deine Route", waiting:"Wähle eine Richtungskarte.", turnCount:"{n} Züge", north:"Norden", east:"Osten", south:"Süden", west:"Westen", resultPartial:"Seite geschafft", resultText:"Du hast {count} von {total} Seiten in {turns} Zügen geführt." },
    it: { guideTitle:"Come si gioca", guideOne:"Leggi l’indizio della destinazione.", guideTwo:"Tocca le quattro carte direzionali per tracciare il percorso.", guideThree:"Un percorso errato si cancella con calma; niente timer o vite.", note1:"Dalla pietra muschiosa vai a est, nord, poi est verso la lanterna.", note2:"Esci dalle canne andando nord, ovest, poi nord.", note3:"Segui la recinzione lunare: ovest, sud, est.", routeLabel:"Il tuo percorso", waiting:"Scegli una carta direzionale.", turnCount:"{n} svolte", north:"Nord", east:"Est", south:"Sud", west:"Ovest", resultPartial:"Pagina completata", resultText:"Hai guidato {count} pagine su {total} in {turns} svolte." },
    ru: { guideTitle:"Как играть", guideOne:"Прочитайте подсказку о цели.", guideTwo:"Нажимайте четыре карточки направлений, чтобы проложить путь.", guideThree:"Ошибочный путь спокойно очистится; таймера и жизней нет.", note1:"От мшистого камня идите на восток, север, затем восток к фонарю.", note2:"Выйдите из камышей: север, запад, север.", note3:"Следуйте лунному забору: запад, юг, восток.", routeLabel:"Ваш путь", waiting:"Выберите карточку направления.", turnCount:"{n} поворотов", north:"Север", east:"Восток", south:"Юг", west:"Запад", resultPartial:"Страница готова", resultText:"Вы провели {count} из {total} страниц за {turns} поворотов." },
    hi: { guideTitle:"कैसे खेलें", guideOne:"गंतव्य का संकेत पढ़ें।", guideTwo:"रास्ता बनाने के लिए चार दिशा कार्ड दबाएँ।", guideThree:"गलत रास्ता शांति से साफ़ हो जाता है; कोई टाइमर या जीवन नहीं।", note1:"काई वाले पत्थर से पूर्व, उत्तर, फिर पूर्व लालटेन तक जाएँ।", note2:"उत्तर, पश्चिम, फिर उत्तर जाकर सरकंडों से निकलें।", note3:"चाँदनी बाड़ का अनुसरण करें: पश्चिम, दक्षिण, पूर्व।", routeLabel:"आपका रास्ता", waiting:"एक दिशा कार्ड चुनें।", turnCount:"{n} मोड़", north:"उत्तर", east:"पूर्व", south:"दक्षिण", west:"पश्चिम", resultPartial:"पन्ना पूरा", resultText:"आपने {turns} मोड़ों में {count}/{total} पन्ने पूरे किए।" },
    ar: { guideTitle:"طريقة اللعب", guideOne:"اقرأ دليل الوجهة.", guideTwo:"اضغط بطاقات الاتجاه الأربعة لرسم المسار.", guideThree:"يُمسح المسار الخاطئ بهدوء؛ لا مؤقت ولا أرواح.", note1:"من حجر الطحلب اتجه شرقاً ثم شمالاً ثم شرقاً إلى الفانوس.", note2:"غادر القصب شمالاً ثم غرباً ثم شمالاً.", note3:"اتبع السياج المضيء: غرباً ثم جنوباً ثم شرقاً.", routeLabel:"مسارك", waiting:"اختر بطاقة اتجاه.", turnCount:"{n} منعطفات", north:"شمال", east:"شرق", south:"جنوب", west:"غرب", resultPartial:"اكتملت الصفحة", resultText:"قدت {count} من {total} صفحات في {turns} منعطفات." }
  };
  Object.entries(sharedExtras).forEach(([locale, extras]) => Object.assign(tables[locale], extras));
  const resultTitles = { "zh-Hans":"笔记完成", ja:"手帳完成", ko:"기록 완료", es:"Cuaderno completo", "pt-BR":"Caderno completo", fr:"Carnet terminé", de:"Folio abgeschlossen", it:"Taccuino completato", ru:"Альбом завершён", hi:"पुस्तिका पूरी", ar:"اكتمل الدفتر" };
  Object.entries(resultTitles).forEach(([locale, title]) => { tables[locale].resultTitle = title; });
  window.ANIMAL_FIREFLY_FOLIO_LOCALES = tables;
})();
