// These exact answers appear visibly in HTML and in its FAQPage structured data.
export const FAQ_ANSWERS={
 en:['Yes. Any two soldiers of the same rank can merge, even of different types. The new type comes only from your five equipped types, each with a 20% chance. Rank 6 cannot merge.','No. Campaign unlocks, stars, best times and squad are saved locally when storage is available, but refreshing resets the current battle.','Clear all 15 waves and their descendants while keeping the wall alive. On a checkpoint mission, defeat its boss before it reaches the wall.'],
 'zh-Hant':['可以。相同等級即可合成，兵種不必相同。結果只會從五種出戰兵種中抽取，每種機率 20%；六級士兵不能再合成。','不會。儲存可用時會保留本機關卡、星數、最佳時間與陣容，但重新整理會重置當前戰鬥。','清完 15 波及分裂小怪，城牆仍有血量；頭目關還必須在頭目抵達城牆前將其擊敗。'],
 'zh-Hans':['可以。同等级即可合成，兵种不必相同。结果只会从五种出战兵种中抽取，每种概率 20%；六级士兵不能再合成。','不会。存储可用时会保留本机关卡、星数、最佳时间与阵容，但刷新会重置当前战斗。','清完 15 波及分裂小怪，城墙仍有血量；首领关还必须在首领抵达城墙前将其击败。'],
 ja:['はい。同ランクなら別兵種でも合成できます。新兵種は編成した5種類から各20%で選ばれます。ランク6は合成できません。','いいえ。保存可能なら解放状況、スター、最速時間、部隊は端末に残りますが、再読み込みすると現在の戦闘はリセットされます。','15ウェーブと分裂した敵を倒して城壁を残してください。ボスのいるステージでは、城壁に到達する前に倒す必要があります。'],
 ko:['네. 같은 등급이면 다른 병종도 합성됩니다. 결과는 출전한 다섯 병종에서 각각 20%로 나오며 6등급은 더 합성할 수 없습니다.','아니요. 저장 가능 시 열린 스테이지, 별, 최단 기록과 부대는 남지만 새로고침은 현재 전투를 초기화합니다.','15공세와 분열한 적을 모두 처치하고 성벽을 유지하세요. 보스 스테이지에서는 보스가 성벽에 도착하기 전에 처치해야 합니다.'],
 es:['Sí. Dos soldados del mismo rango pueden fusionarse aunque sean de tipos distintos. El resultado sale de tus cinco tipos equipados, cada uno al 20%. El rango 6 no se fusiona.','No. Si el almacenamiento está disponible, se guardan misiones, estrellas, mejores tiempos y equipo, pero recargar reinicia la batalla actual.','Elimina las 15 oleadas y sus descendientes sin perder la muralla. En una misión de jefe, derrótalo antes de que llegue a ella.'],
 'pt-BR':['Sim. Soldados do mesmo nível podem se fundir mesmo sendo de tipos diferentes. O resultado vem dos cinco tipos equipados, cada um com 20%. Nível 6 não se funde.','Não. Com armazenamento disponível, missões, estrelas, melhores tempos e equipe ficam salvos, mas recarregar reinicia a batalha atual.','Elimine as 15 ondas e seus descendentes mantendo a muralha. Em missão de chefe, derrote-o antes que ele chegue à muralha.'],
 fr:['Oui. Deux soldats de même rang peuvent fusionner malgré des types différents. Le résultat vient des cinq types équipés, chacun à 20 %. Le rang 6 ne fusionne plus.','Non. Si le stockage fonctionne, missions, étoiles, meilleurs temps et équipe sont conservés, mais actualiser réinitialise le combat en cours.','Éliminez les 15 vagues et leurs descendants sans perdre le rempart. Dans une mission de boss, battez-le avant qu’il atteigne le rempart.'],
 de:['Ja. Soldaten gleichen Rangs können auch bei verschiedenen Typen verschmelzen. Das Ergebnis stammt aus deinen fünf Typen, jeweils mit 20 %. Rang 6 kann nicht weiter verschmelzen.','Nein. Bei verfügbarem Speicher bleiben Missionen, Sterne, Bestzeiten und Team erhalten, aber Neuladen setzt den aktuellen Kampf zurück.','Besiege die 15 Wellen und ihre Untergegner bei intakter Mauer. Besiege in einer Bossmission den Boss, bevor er die Mauer erreicht.'],
 it:['Sì. Soldati dello stesso rango si fondono anche se di tipi diversi. Il risultato viene dai cinque tipi equipaggiati, ciascuno al 20%. Il rango 6 non può fondersi ancora.','No. Se la memoria è disponibile, missioni, stelle, tempi migliori e squadra restano salvati, ma ricaricare azzera la battaglia in corso.','Elimina le 15 ondate e i loro discendenti mantenendo le mura. Nelle missioni con boss, sconfiggilo prima che le raggiunga.'],
 ru:['Да. Бойцы одного ранга сливаются даже при разных типах. Новый тип берётся из ваших пяти, каждый с вероятностью 20%. Ранг 6 дальше не сливается.','Нет. При доступном хранилище остаются миссии, звёзды, лучшие времена и отряд, но обновление сбрасывает текущий бой.','Уничтожьте 15 волн и появившихся потомков, сохранив стену. В миссии с боссом победите его до прибытия к стене.'],
 hi:['हाँ। समान रैंक के अलग प्रकार भी मिल सकते हैं। नया प्रकार चुने पाँच में से हर एक की 20% संभावना से आता है। रैंक 6 का आगे विलय नहीं होता।','नहीं। संग्रहण उपलब्ध हो तो मिशन, सितारे, सबसे अच्छे समय और दल बचते हैं, लेकिन रीफ़्रेश वर्तमान लड़ाई को रीसेट करता है।','दीवार बचाते हुए 15 लहरें और उनसे बने छोटे दुश्मन हराएँ। बॉस मिशन में उसे दीवार तक पहुँचने से पहले हराना ज़रूरी है।'],
 ar:['نعم. يندمج جنديان من الرتبة نفسها ولو اختلف نوعاهما. يأتي النوع الجديد من الخمسة المجهزة باحتمال 20% لكل منها. الرتبة 6 لا تندمج أكثر.','لا. عند توفر التخزين تبقى المهام والنجوم وأفضل الأوقات والفريق محفوظة، لكن التحديث يعيد المعركة الحالية من البداية.','اهزم 15 موجة وجميع الأعداء المتولدين مع بقاء السور. في مهمة الزعيم اهزمه قبل أن يصل إلى السور.']
};
