import {guides} from './guides.mjs?v=7';
// Complete game-owned dictionaries. Delimited rows share an asserted schema.
export const LOCALES=['en','zh-Hant','zh-Hans','ja','ko','es','pt-BR','fr','de','it','ru','hi','ar'];
export const LABELS=['English','繁體中文','简体中文','日本語','한국어','Español','Português (Brasil)','Français','Deutsch','Italiano','Русский','हिन्दी','العربية'];
const keys='title|tagline|start|guide|campaign|deck|level|wave|goldLabel|wall|summon|upgrade|spell|speed|target|front|strong|pause|resume|leaveTitle|leaveText|leave|back|next|retry|victory|defeat|stars|time|saved|noStorage|loading|unavailable|recover|selected|selectPrompt|empty|full|gold|rank|max|frozen|cooldown|invalid|inactive|moved|merged|summoned|upgraded|cast|locked|deckHint|deckFull|deckMin|best|warnFreeze|warnBoss|theft|complete|helpMerge'.split('|');
const rows={
'en':`Fusekeep|Build a squad. Risk a merge. Hold the winter wall.|Start|How to play|Missions|Squad|Mission {n}|Wave {n}/15|Gold|Wall|Summon|Upgrade|Frost burst|Speed|Priority|Front|Strongest|Pause|Resume|Leave this battle?|This run will reset. Your campaign progress stays saved.|Leave|Back|Next|Retry|Wall defended!|Wall breached|Stars|Time|Progress saved on this device|Storage unavailable: progress lasts only this session.|Preparing the arena…|The 3D arena could not start or its graphics context was lost.|Restore arena|Pad {n} selected|Select a soldier, then a destination.|Empty|All usable pads are occupied.|Not enough gold.|Only soldiers of the same type and rank can merge.|Maximum level reached.|That pad is frozen.|The spell is recharging.|Choose a different valid destination.|Resume the battle first.|Soldier moved.|Merge complete: a random equipped troop!|Soldier summoned.|Formation upgraded.|Frost burst cast.|Clear the previous mission to unlock.|Equip exactly five different troop types.|Remove a troop before adding another.|Equip five troop types to play.|Best|Ice warning: move before these pads freeze!|Boss preparing: {name}|Gold stolen: {n}|All 30 missions cleared|Drag matching soldiers of the same type and rank, or tap source and destination.`,
'zh-Hant':`合成守城|組建陣容，冒險合成，守住冰雪城牆。|開始遊戲|玩法說明|關卡|出戰陣容|第 {n} 關|第 {n}/15 波|金幣|城牆|召喚|強化|冰霜爆發|速度|優先目標|最前方|最強敵人|暫停|繼續|離開這場戰鬥？|本場進度將重置，已完成的關卡仍會保留。|離開|返回|下一關|重試|守城成功！|城牆失守|星星|時間|進度已儲存在此裝置|無法使用儲存空間：進度僅保留於本次開啟期間。|正在準備戰場…|無法啟動 3D 戰場，或繪圖連線已中斷。|恢復戰場|已選取第 {n} 格|先選士兵，再選目的地。|空位|可用的格子已滿。|金幣不足。|兵種與等級都相同才能合成。|已達最高等級。|這個格子已結冰。|技能冷卻中。|請選擇其他有效的目的地。|請先繼續戰鬥。|士兵已移動。|合成成功：隨機產生出戰兵種！|召喚成功。|全隊強化成功。|已施放冰霜爆發。|通過前一關後解鎖。|請配置五種不同的出戰兵種。|請先移除一種兵種再新增。|需配置五種兵種才能出戰。|最佳紀錄|結冰預警：請在結冰前移開士兵！|頭目正在蓄力：{name}|金幣被偷走：{n}|已通過全部 30 關|拖曳同兵種、同等級士兵合成，或依序點選來源與目的地。`,
'zh-Hans':`合成守城|组建阵容，冒险合成，守住冰雪城墙。|开始游戏|玩法说明|关卡|出战阵容|第 {n} 关|第 {n}/15 波|金币|城墙|召唤|强化|冰霜爆发|速度|优先目标|最前方|最强敌人|暂停|继续|离开这场战斗？|本场进度将重置，已完成的关卡仍会保留。|离开|返回|下一关|重试|守城成功！|城墙失守|星星|时间|进度已保存在此设备|无法使用存储空间：进度仅保留于本次打开期间。|正在准备战场…|无法启动 3D 战场，或图形连接已中断。|恢复战场|已选取第 {n} 格|先选士兵，再选目的地。|空位|可用的格子已满。|金币不足。|兵种与等级都相同才能合成。|已达最高等级。|这个格子已结冰。|技能冷却中。|请选择其他有效的目的地。|请先继续战斗。|士兵已移动。|合成成功：随机产生出战兵种！|召唤成功。|全队强化成功。|已施放冰霜爆发。|通过前一关后解锁。|请配置五种不同的出战兵种。|请先移除一种兵种再新增。|需配置五种兵种才能出战。|最佳纪录|结冰预警：请在结冰前移开士兵！|首领正在蓄力：{name}|金币被偷走：{n}|已通过全部 30 关|拖动同兵种、同等级士兵合成，或依次点击来源与目的地。`,
'ja':`合成の砦|部隊を組み、合成に挑み、雪の城壁を守ろう。|始める|遊び方|ステージ|出撃部隊|ステージ {n}|第 {n}/15 波|コイン|城壁|召喚|強化|氷の衝撃|速度|優先対象|先頭|最強|一時停止|再開|戦闘を終了しますか？|今回の戦闘はリセットされます。クリア済みの記録は残ります。|終了|戻る|次へ|再挑戦|防衛成功！|城壁陥落|スター|時間|この端末に保存しました|保存できません。進行状況は今回のセッションのみ有効です。|戦場を準備中…|3D 戦場を開始できないか、描画接続が失われました。|戦場を復元|マス {n} を選択中|兵士を選び、移動先を選んでください。|空き|使用できるマスがいっぱいです。|コイン不足です。|同じ兵種・同じランクの兵士だけ合成できます。|最高レベルです。|このマスは凍っています。|スキルの再使用待ちです。|別の有効な移動先を選んでください。|先に戦闘を再開してください。|移動しました。|合成成功！出撃兵種からランダムに変化！|召喚しました。|部隊を強化しました。|氷の衝撃を使用しました。|前のステージをクリアすると解放されます。|異なる兵種をちょうど5種類選んでください。|追加する前に1種類外してください。|出撃には5種類の兵種が必要です。|最高記録|凍結予告：凍る前に兵士を移動！|ボスの予備動作：{name}|奪われたコイン：{n}|全30ステージをクリア|同じ兵種・同じランクの兵士をドラッグするか、移動元と先をタップ。`,
'ko':`합성 요새|부대를 꾸리고 합성하여 겨울 성벽을 지키세요.|시작|게임 방법|스테이지|출전 부대|스테이지 {n}|공세 {n}/15|골드|성벽|소환|강화|서리 폭발|속도|우선 대상|선두|가장 강한 적|일시 정지|계속|전투를 나갈까요?|이번 전투는 초기화되며 완료한 스테이지 기록은 유지됩니다.|나가기|뒤로|다음|재도전|방어 성공!|성벽 함락|별|시간|이 기기에 저장됨|저장할 수 없습니다. 진행 상황은 이번 세션에만 유지됩니다.|전장 준비 중…|3D 전장을 시작하지 못했거나 그래픽 연결이 끊겼습니다.|전장 복구|{n}번 칸 선택됨|병사를 선택한 뒤 목적지를 선택하세요.|빈칸|사용할 수 있는 칸이 가득 찼습니다.|골드가 부족합니다.|병종과 등급이 모두 같아야 합성할 수 있습니다.|최고 레벨입니다.|이 칸은 얼어 있습니다.|스킬 재사용 대기 중입니다.|다른 유효한 목적지를 선택하세요.|먼저 전투를 계속하세요.|병사를 이동했습니다.|합성 완료! 출전 병종 중 무작위로 변합니다!|소환했습니다.|부대를 강화했습니다.|서리 폭발을 사용했습니다.|이전 스테이지를 완료하면 열립니다.|서로 다른 병종 다섯 가지를 장착하세요.|추가하기 전에 병종 하나를 제외하세요.|출전하려면 병종 다섯 가지가 필요합니다.|최고 기록|빙결 경고: 얼기 전에 병사를 옮기세요!|보스 준비 동작: {name}|도난당한 골드: {n}|30개 스테이지 모두 완료|같은 병종과 등급의 병사를 드래그하거나 출발 칸과 도착 칸을 누르세요.`,
'es':`Fortaleza Fusión|Forma tu equipo, arriesga una fusión y protege la muralla.|Jugar|Cómo jugar|Misiones|Equipo|Misión {n}|Oleada {n}/15|Oro|Muralla|Invocar|Mejorar|Estallido helado|Velocidad|Prioridad|Primero|Más fuerte|Pausa|Continuar|¿Salir de la batalla?|Esta partida se reiniciará. El progreso de campaña se conserva.|Salir|Volver|Siguiente|Reintentar|¡Muralla defendida!|Muralla destruida|Estrellas|Tiempo|Progreso guardado en este dispositivo|No se puede guardar: el progreso dura solo esta sesión.|Preparando la arena…|No se pudo iniciar la arena 3D o se perdió la conexión gráfica.|Restaurar arena|Casilla {n} seleccionada|Elige un soldado y después su destino.|Vacía|Todas las casillas disponibles están ocupadas.|No hay suficiente oro.|Solo se fusionan soldados del mismo tipo y rango.|Nivel máximo alcanzado.|Esa casilla está congelada.|El hechizo se está recargando.|Elige otro destino válido.|Reanuda la batalla primero.|Soldado movido.|¡Fusión completada: un tipo equipado al azar!|Soldado invocado.|Formación mejorada.|Estallido helado lanzado.|Completa la misión anterior para desbloquear.|Equipa exactamente cinco tipos distintos.|Retira un tipo antes de añadir otro.|Necesitas cinco tipos para jugar.|Mejor marca|¡Aviso de hielo: mueve las tropas antes de la congelación!|El jefe se prepara: {name}|Oro robado: {n}|Las 30 misiones completadas|Arrastra soldados del mismo tipo y rango, o toca origen y destino.`,
'pt-BR':`Fortaleza da Fusão|Monte sua equipe, arrisque uma fusão e defenda a muralha.|Jogar|Como jogar|Missões|Equipe|Missão {n}|Onda {n}/15|Ouro|Muralha|Invocar|Melhorar|Explosão de gelo|Velocidade|Prioridade|Frente|Mais forte|Pausar|Continuar|Sair da batalha?|Esta partida será reiniciada. O progresso da campanha será mantido.|Sair|Voltar|Próxima|Tentar de novo|Muralha defendida!|Muralha destruída|Estrelas|Tempo|Progresso salvo neste dispositivo|Não foi possível salvar: o progresso dura apenas nesta sessão.|Preparando a arena…|Não foi possível iniciar a arena 3D ou a conexão gráfica foi perdida.|Restaurar arena|Casa {n} selecionada|Escolha um soldado e depois o destino.|Vazia|Todas as casas disponíveis estão ocupadas.|Ouro insuficiente.|Só soldados do mesmo tipo e nível podem se fundir.|Nível máximo alcançado.|Essa casa está congelada.|O feitiço está recarregando.|Escolha outro destino válido.|Continue a batalha primeiro.|Soldado movido.|Fusão concluída: um tipo equipado aleatório!|Soldado invocado.|Formação melhorada.|Explosão de gelo lançada.|Conclua a missão anterior para desbloquear.|Equipe exatamente cinco tipos diferentes.|Remova um tipo antes de adicionar outro.|São necessários cinco tipos para jogar.|Melhor marca|Aviso de gelo: mova as tropas antes que congelem!|O chefe está se preparando: {name}|Ouro roubado: {n}|Todas as 30 missões concluídas|Arraste soldados do mesmo tipo e nível ou toque na origem e no destino.`,
'fr':`Forteresse Fusion|Formez une équipe, tentez une fusion et défendez le rempart.|Jouer|Règles du jeu|Missions|Équipe|Mission {n}|Vague {n}/15|Or|Rempart|Invoquer|Améliorer|Souffle de givre|Vitesse|Priorité|En tête|Plus puissant|Pause|Reprendre|Quitter cette bataille ?|Cette partie sera réinitialisée. La progression de campagne est conservée.|Quitter|Retour|Suivante|Réessayer|Rempart défendu !|Rempart détruit|Étoiles|Temps|Progression enregistrée sur cet appareil|Sauvegarde indisponible : la progression ne dure que cette session.|Préparation de l’arène…|L’arène 3D n’a pas démarré ou la connexion graphique a été perdue.|Restaurer l’arène|Case {n} sélectionnée|Choisissez un soldat, puis sa destination.|Libre|Toutes les cases utilisables sont occupées.|Pas assez d’or.|Seuls les soldats de même type et de même rang fusionnent.|Niveau maximal atteint.|Cette case est gelée.|Le sort se recharge.|Choisissez une autre destination valide.|Reprenez d’abord la bataille.|Soldat déplacé.|Fusion réussie : un type équipé au hasard !|Soldat invoqué.|Formation améliorée.|Souffle de givre lancé.|Terminez la mission précédente pour débloquer.|Équipez exactement cinq types différents.|Retirez un type avant d’en ajouter un.|Cinq types sont nécessaires pour jouer.|Meilleur résultat|Alerte au gel : déplacez les troupes avant qu’elles ne gèlent !|Le boss se prépare : {name}|Or volé : {n}|Les 30 missions sont terminées|Glissez des soldats de même type et rang, ou touchez la source puis la destination.`,
'de':`Fusionsfestung|Stelle dein Team auf, wage Fusionen und schütze die Mauer.|Spielen|Spielanleitung|Missionen|Team|Mission {n}|Welle {n}/15|Gold|Mauer|Beschwören|Verstärken|Froststoß|Tempo|Priorität|Vorne|Stärkster|Pause|Fortsetzen|Diesen Kampf verlassen?|Diese Runde wird zurückgesetzt. Der Kampagnenfortschritt bleibt erhalten.|Verlassen|Zurück|Weiter|Erneut|Mauer verteidigt!|Mauer durchbrochen|Sterne|Zeit|Fortschritt auf diesem Gerät gespeichert|Speichern nicht verfügbar: Fortschritt gilt nur für diese Sitzung.|Arena wird vorbereitet…|Die 3D-Arena konnte nicht starten oder die Grafikverbindung wurde unterbrochen.|Arena wiederherstellen|Feld {n} ausgewählt|Wähle einen Soldaten und dann ein Ziel.|Leer|Alle nutzbaren Felder sind belegt.|Nicht genug Gold.|Nur Soldaten gleichen Typs und Rangs können verschmelzen.|Maximale Stufe erreicht.|Dieses Feld ist eingefroren.|Der Zauber lädt noch auf.|Wähle ein anderes gültiges Ziel.|Setze zuerst den Kampf fort.|Soldat bewegt.|Fusion gelungen: ein zufälliger ausgerüsteter Typ!|Soldat beschworen.|Formation verstärkt.|Froststoß gewirkt.|Schließe zum Freischalten die vorherige Mission ab.|Rüste genau fünf verschiedene Typen aus.|Entferne einen Typ, bevor du einen hinzufügst.|Zum Spielen sind fünf Typen nötig.|Bestleistung|Frostwarnung: Bewege die Truppen vor dem Einfrieren!|Boss bereitet sich vor: {name}|Gestohlenes Gold: {n}|Alle 30 Missionen abgeschlossen|Ziehe Soldaten gleichen Typs und Rangs zusammen oder tippe Quelle und Ziel an.`,
'it':`Fortezza Fusione|Forma la squadra, rischia una fusione e difendi le mura.|Gioca|Come giocare|Missioni|Squadra|Missione {n}|Ondata {n}/15|Oro|Mura|Evoca|Potenzia|Esplosione gelida|Velocità|Priorità|Davanti|Più forte|Pausa|Riprendi|Lasciare la battaglia?|Questa partita sarà azzerata. I progressi della campagna resteranno salvati.|Esci|Indietro|Avanti|Riprova|Mura difese!|Mura distrutte|Stelle|Tempo|Progressi salvati su questo dispositivo|Salvataggio non disponibile: i progressi durano solo questa sessione.|Preparazione dell’arena…|Impossibile avviare l’arena 3D o connessione grafica persa.|Ripristina arena|Casella {n} selezionata|Scegli un soldato, poi la destinazione.|Vuota|Tutte le caselle utilizzabili sono occupate.|Oro insufficiente.|Si fondono solo soldati dello stesso tipo e rango.|Livello massimo raggiunto.|Questa casella è congelata.|L’incantesimo si sta ricaricando.|Scegli un’altra destinazione valida.|Riprendi prima la battaglia.|Soldato spostato.|Fusione completata: un tipo equipaggiato casuale!|Soldato evocato.|Formazione potenziata.|Esplosione gelida lanciata.|Completa la missione precedente per sbloccare.|Equipaggia esattamente cinque tipi diversi.|Rimuovi un tipo prima di aggiungerne un altro.|Servono cinque tipi per giocare.|Record|Allarme gelo: sposta le truppe prima che si congelino!|Il boss si prepara: {name}|Oro rubato: {n}|Tutte le 30 missioni completate|Trascina soldati dello stesso tipo e rango, oppure tocca origine e destinazione.`,
'ru':`Крепость слияния|Соберите отряд, рискните слиянием и защитите зимнюю стену.|Играть|Как играть|Миссии|Отряд|Миссия {n}|Волна {n}/15|Золото|Стена|Призвать|Усилить|Морозный взрыв|Скорость|Приоритет|Впереди|Сильнейший|Пауза|Продолжить|Покинуть бой?|Этот бой начнётся заново. Прогресс кампании сохранится.|Выйти|Назад|Далее|Повторить|Стена защищена!|Стена разрушена|Звёзды|Время|Прогресс сохранён на этом устройстве|Сохранение недоступно: прогресс действует только в этом сеансе.|Подготовка арены…|Не удалось запустить 3D-арену или потеряно графическое соединение.|Восстановить арену|Выбрана клетка {n}|Выберите бойца, затем место назначения.|Пусто|Все доступные клетки заняты.|Недостаточно золота.|Сливаются только бойцы одного типа и ранга.|Достигнут максимальный уровень.|Эта клетка заморожена.|Заклинание перезаряжается.|Выберите другое допустимое место.|Сначала продолжите бой.|Боец перемещён.|Слияние завершено: случайный тип из отряда!|Боец призван.|Построение усилено.|Морозный взрыв применён.|Пройдите предыдущую миссию для открытия.|Выберите ровно пять разных типов бойцов.|Уберите один тип перед добавлением другого.|Для игры нужны пять типов бойцов.|Рекорд|Угроза заморозки: переместите бойцов заранее!|Босс готовится: {name}|Украдено золота: {n}|Все 30 миссий пройдены|Перетащите бойцов одного типа и ранга или нажмите источник и цель.`,
'hi':`विलय दुर्ग|दल बनाएँ, विलय का जोखिम लें और बर्फीली दीवार बचाएँ।|खेलें|कैसे खेलें|मिशन|दल|मिशन {n}|लहर {n}/15|सोना|दीवार|बुलाएँ|मज़बूत करें|हिम विस्फोट|गति|प्राथमिकता|सबसे आगे|सबसे ताकतवर|रोकें|जारी रखें|यह लड़ाई छोड़ें?|यह दौर फिर शुरू होगा। अभियान की प्रगति सुरक्षित रहेगी।|छोड़ें|वापस|अगला|फिर खेलें|दीवार बच गई!|दीवार टूट गई|सितारे|समय|प्रगति इस उपकरण पर सहेजी गई|संग्रहण उपलब्ध नहीं: प्रगति केवल इस सत्र तक रहेगी।|मैदान तैयार हो रहा है…|3D मैदान शुरू नहीं हुआ या ग्राफ़िक्स कनेक्शन टूट गया।|मैदान बहाल करें|खाना {n} चुना गया|पहले सैनिक, फिर उसका गंतव्य चुनें।|खाली|सभी उपयोगी खाने भरे हैं।|पर्याप्त सोना नहीं है।|केवल समान प्रकार और रैंक के सैनिक मिल सकते हैं।|अधिकतम स्तर आ गया।|यह खाना जम गया है।|जादू फिर तैयार हो रहा है।|दूसरा मान्य गंतव्य चुनें।|पहले लड़ाई जारी रखें।|सैनिक हटा दिया गया।|विलय पूरा: चुने हुए दल से एक अनियमित प्रकार!|सैनिक बुलाया गया।|पूरा दल मज़बूत हुआ।|हिम विस्फोट किया गया।|खोलने के लिए पिछला मिशन पूरा करें।|ठीक पाँच अलग प्रकार चुनें।|नया प्रकार जोड़ने से पहले एक हटाएँ।|खेलने के लिए पाँच प्रकार चाहिए।|सर्वश्रेष्ठ|बर्फ की चेतावनी: जमने से पहले सैनिक हटाएँ!|बॉस तैयारी कर रहा है: {name}|चुराया गया सोना: {n}|सभी 30 मिशन पूरे|समान प्रकार और रैंक के सैनिक खींचें या पहले स्रोत, फिर गंतव्य छुएँ।`,
'ar':`حصن الدمج|شكّل فريقك وجرّب الدمج واحمِ سور الشتاء.|العب|طريقة اللعب|المهام|الفريق|المهمة {n}|الموجة {n}/15|الذهب|السور|استدعاء|تعزيز|انفجار الصقيع|السرعة|الأولوية|المتقدم|الأقوى|إيقاف مؤقت|متابعة|مغادرة المعركة؟|ستبدأ هذه الجولة من جديد. سيبقى تقدم الحملة محفوظًا.|مغادرة|رجوع|التالي|إعادة المحاولة|نجح الدفاع عن السور!|انهار السور|النجوم|الوقت|حُفظ التقدم على هذا الجهاز|التخزين غير متاح: يستمر التقدم لهذه الجلسة فقط.|جارٍ إعداد الساحة…|تعذر تشغيل الساحة ثلاثية الأبعاد أو انقطع اتصال الرسوميات.|استعادة الساحة|الخانة {n} محددة|اختر جنديًا ثم وجهته.|فارغة|جميع الخانات المتاحة مشغولة.|الذهب غير كافٍ.|لا يندمج إلا جنديان من النوع والرتبة نفسيهما.|تم بلوغ المستوى الأقصى.|هذه الخانة متجمدة.|التعويذة قيد التجهيز.|اختر وجهة أخرى صالحة.|تابع المعركة أولًا.|تم نقل الجندي.|اكتمل الدمج: نوع عشوائي من الفريق المجهز!|تم استدعاء الجندي.|تم تعزيز التشكيل.|تم إطلاق انفجار الصقيع.|أكمل المهمة السابقة لفتحها.|جهّز خمسة أنواع مختلفة بالضبط.|أزل نوعًا قبل إضافة آخر.|تحتاج إلى خمسة أنواع للعب.|أفضل نتيجة|تحذير جليد: انقل الجنود قبل تجمد الخانات!|الزعيم يستعد: {name}|الذهب المسروق: {n}|اكتملت المهام الثلاثون|اسحب جنديين من النوع والرتبة نفسيهما، أو المس المصدر ثم الوجهة.`
};
const names={
 en:'Fox Ranger|Bear Gunner|Owl Frostcaller|Rabbit Stormcaller|Wolf Sentinel|Raccoon Alchemist|Deer Banner|Cat Treasurer',
 'zh-Hant':'狐狸遊俠|巨熊砲手|冰霜貓頭鷹|雷電兔|野狼守衛|浣熊鍊金師|鹿旗手|招財貓',
 'zh-Hans':'狐狸游侠|巨熊炮手|冰霜猫头鹰|雷电兔|野狼守卫|浣熊炼金师|鹿旗手|招财猫',
 ja:'キツネの射手|クマの砲手|フクロウの氷術師|ウサギの雷術師|オオカミの衛兵|アライグマの錬金術師|シカの旗手|ネコの会計係',
 ko:'여우 궁수|곰 포수|올빼미 서리술사|토끼 번개술사|늑대 파수꾼|너구리 연금술사|사슴 기수|고양이 회계사',
 es:'Zorro arquero|Oso artillero|Búho de escarcha|Conejo de tormenta|Lobo centinela|Mapache alquimista|Ciervo abanderado|Gato tesorero',
 'pt-BR':'Raposa arqueira|Urso artilheiro|Coruja do gelo|Coelho da tempestade|Lobo sentinela|Guaxinim alquimista|Cervo porta-bandeira|Gato tesoureiro',
 fr:'Renard archer|Ours artilleur|Hibou du givre|Lapin de l’orage|Loup sentinelle|Raton alchimiste|Cerf porte-bannière|Chat trésorier',
 de:'Fuchs-Bogenschütze|Bären-Kanonier|Frost-Eule|Sturm-Hase|Wolf-Wächter|Waschbär-Alchemist|Hirsch-Bannerträger|Katzen-Schatzmeister',
 it:'Volpe arciera|Orso cannoniere|Gufo del gelo|Coniglio della tempesta|Lupo sentinella|Procione alchimista|Cervo portabandiera|Gatto tesoriere',
 ru:'Лис-стрелок|Медведь-пушкарь|Сова мороза|Кролик грозы|Волк-страж|Енот-алхимик|Олень-знаменосец|Кот-казначей',
 hi:'लोमड़ी धनुर्धर|भालू तोपची|हिम उल्लू|बिजली खरगोश|भेड़िया रक्षक|रैकून रसायनज्ञ|हिरण ध्वजवाहक|बिल्ली कोषाध्यक्ष',
 ar:'الثعلب الرامي|الدب المدفعي|بومة الصقيع|أرنب العاصفة|الذئب الحارس|الراكون الكيميائي|الأيل حامل الراية|القط أمين الخزينة'
};
const roles={
 en:'Fast single-target shots|Splash damage to clustered enemies|Slows enemies|Chains across three enemies|Ignores armor|Poison damage over time|Adjacent troops deal 30% more damage|Earns 20 gold per rank after each wave',
 'zh-Hant':'快速單體射擊|對密集敵人造成範圍傷害|減緩敵人速度|連鎖攻擊三個敵人|無視護甲|持續毒傷|相鄰士兵傷害增加 30%|每波結束依等級賺取 20 金幣',
 'zh-Hans':'快速单体射击|对密集敌人造成范围伤害|减缓敌人速度|连锁攻击三个敌人|无视护甲|持续毒伤|相邻士兵伤害增加 30%|每波结束依等级赚取 20 金币',
 ja:'素早い単体攻撃|密集した敵に範囲攻撃|敵を減速|3体の敵へ連鎖攻撃|装甲を無視|継続的な毒ダメージ|隣接する兵士のダメージが30%増加|各ウェーブ終了時にランク×20コイン獲得',
 ko:'빠른 단일 공격|밀집한 적에게 범위 피해|적의 속도를 낮춤|세 적에게 연쇄 공격|방어구 무시|지속 독 피해|인접 병사의 피해량 30% 증가|공세 종료 시 등급당 골드 20 획득',
 es:'Disparos rápidos a un objetivo|Daño de área a grupos|Ralentiza enemigos|Encadena tres enemigos|Ignora la armadura|Veneno continuo|Los aliados adyacentes infligen un 30% más de daño|Gana 20 de oro por rango tras cada oleada',
 'pt-BR':'Tiros rápidos em um alvo|Dano em área contra grupos|Desacelera inimigos|Atinge três inimigos em cadeia|Ignora armadura|Dano contínuo de veneno|Aliados adjacentes causam 30% mais dano|Ganha 20 de ouro por nível após cada onda',
 fr:'Tirs rapides sur une cible|Dégâts de zone sur les groupes|Ralentit les ennemis|Enchaîne trois ennemis|Ignore l’armure|Poison continu|Les alliés adjacents infligent 30 % de dégâts en plus|Gagne 20 pièces par rang après chaque vague',
 de:'Schnelle Einzelschüsse|Flächenschaden gegen Gruppen|Verlangsamt Gegner|Kette über drei Gegner|Ignoriert Rüstung|Giftschaden über Zeit|Benachbarte Truppen verursachen 30 % mehr Schaden|Verdient nach jeder Welle 20 Gold je Rang',
 it:'Colpi rapidi su un bersaglio|Danni ad area sui gruppi|Rallenta i nemici|Colpisce tre nemici a catena|Ignora l’armatura|Veleno nel tempo|Gli alleati adiacenti infliggono il 30% di danni in più|Guadagna 20 monete per rango dopo ogni ondata',
 ru:'Быстрые одиночные выстрелы|Урон по скоплениям врагов|Замедляет врагов|Цепь по трём врагам|Игнорирует броню|Постепенный урон ядом|Соседние бойцы наносят на 30% больше урона|После волны приносит 20 золота за ранг',
 hi:'तेज़ एकल निशाना|समूह पर क्षेत्रीय नुकसान|दुश्मन धीमे होते हैं|तीन दुश्मनों पर श्रृंखला हमला|कवच को अनदेखा करता है|समय के साथ ज़हर का नुकसान|पास के सैनिक 30% अधिक नुकसान देते हैं|हर लहर के बाद प्रति रैंक 20 सोना मिलता है',
 ar:'طلقات سريعة لهدف واحد|ضرر جماعي للأعداء المتقاربين|يبطئ الأعداء|يضرب ثلاثة أعداء بالتتابع|يتجاهل الدرع|ضرر سم مستمر|الجنود المجاورون يسببون ضررًا إضافيًا بنسبة 30%|يكسب 20 ذهبًا لكل رتبة بعد كل موجة'
};
const chapters={
 en:'First watch|Iron procession|Second life|Frozen stones|Lean purse|Winter crown',
 'zh-Hant':'初次守望|鐵甲軍勢|再生魔巢|冰封石陣|拮据軍餉|凜冬王冠',
 'zh-Hans':'初次守望|铁甲军势|再生魔巢|冰封石阵|拮据军饷|凛冬王冠',
 ja:'初めての守備|鉄の行進|再生する敵|凍った石畳|乏しい軍資金|冬の王冠',
 ko:'첫 경계|강철 행진|두 번째 생명|얼어붙은 돌|부족한 군자금|겨울 왕관',
 es:'Primera guardia|Procesión de hierro|Segunda vida|Piedras heladas|Bolsa vacía|Corona invernal',
 'pt-BR':'Primeira vigília|Marcha de ferro|Segunda vida|Pedras congeladas|Bolsa vazia|Coroa do inverno',
 fr:'Première garde|Marche de fer|Seconde vie|Pierres gelées|Bourse légère|Couronne d’hiver',
 de:'Erste Wache|Eiserner Zug|Zweites Leben|Gefrorene Steine|Knappes Gold|Winterkrone',
 it:'Prima guardia|Marcia di ferro|Seconda vita|Pietre gelate|Borsa vuota|Corona d’inverno',
 ru:'Первый дозор|Железный поход|Вторая жизнь|Мёрзлые камни|Скудная казна|Зимняя корона',
 hi:'पहली पहरेदारी|लोहे का जुलूस|दूसरा जीवन|जमे हुए पत्थर|खाली खज़ाना|शीत मुकुट',
 ar:'الحراسة الأولى|المسيرة الحديدية|الحياة الثانية|الحجارة المتجمدة|الخزينة الشحيحة|تاج الشتاء'
};
const bossNames={
 en:'Ram Captain|Mirror Warden|Brood Mother|Frost Regent|Coin Reaver|Winter Crown',
 'zh-Hant':'衝城隊長|鏡甲守衛|蟲巢母后|冰霜攝政|掠金盜王|凜冬王冠',
 'zh-Hans':'冲城队长|镜甲守卫|虫巢母后|冰霜摄政|掠金盗王|凛冬王冠',
 ja:'突撃隊長|鏡の守護者|群れの母|霜の摂政|金貨の略奪者|冬の王冠',
 ko:'돌격 대장|거울 파수꾼|군체 여왕|서리 섭정|금화 약탈자|겨울 왕관',
 es:'Capitán ariete|Guardián espejo|Madre de la prole|Regente de escarcha|Saqueador de oro|Corona invernal',
 'pt-BR':'Capitão aríete|Guardião espelhado|Mãe da ninhada|Regente do gelo|Ladrão de moedas|Coroa do inverno',
 fr:'Capitaine bélier|Gardien miroir|Mère de la nuée|Régent du givre|Voleur d’or|Couronne d’hiver',
 de:'Rammhauptmann|Spiegelwächter|Brutmutter|Frostregent|Goldräuber|Winterkrone',
 it:'Capitano ariete|Guardiano specchio|Madre della covata|Reggente del gelo|Predone d’oro|Corona d’inverno',
 ru:'Капитан таран|Зеркальный страж|Мать выводка|Регент мороза|Похититель монет|Зимняя корона',
 hi:'मेढ़ा कप्तान|दर्पण रक्षक|झुंड माता|हिम शासक|सोना लुटेरा|शीत मुकुट',
 ar:'قائد الكبش|حارس المرآة|أم السرب|وصي الصقيع|ناهب الذهب|تاج الشتاء'
};
export const DICT=Object.fromEntries(LOCALES.map(locale=>{
 const values=rows[locale].split('|');if(values.length!==keys.length)throw Error(`Locale schema mismatch: ${locale}`);
 const value=Object.fromEntries(keys.map((key,i)=>[key,values[i]]));
 return [locale,Object.freeze({...value,troops:names[locale].split('|'),roles:roles[locale].split('|'),chapters:chapters[locale].split('|'),bosses:bossNames[locale].split('|'),guideText:guides[locale]})];
}));
export function translator(locale){const d=DICT[locale]||DICT.en;return (key,vars={})=>String(d[key]??key).replace(/\{(\w+)\}/g,(_,k)=>String(vars[k]??`{${k}}`));}
