// Canonical visible guide copy for both static locale pages and runtime help.
// New game remains noindex until the independent release workflow accepts it.
export const PAGES={
 en:{title:'Fusekeep',description:'Merge same-rank animal soldiers into random equipped troops and defend a winter wall through 30 missions of 15 waves.',headings:['Defend the winter wall','Same rank, a new random troop','Build a five-type squad','Thirty missions, six checkpoint bosses','Win, lose and choose your next move','Local progress and browser recovery'],faqTitle:'Questions about Fusekeep',questions:['Can different troop types merge?','Does refreshing preserve a battle?','How do I clear a mission?'],related:'Related game',start:'Start',retry:'Reload',back:'Back',campaign:'Missions',stars:'Stars',guide:[
 'Fusekeep is a single-player browser defense game. Enemies march down from the upper portal while animal soldiers fire automatically from nine floor tiles. Choose five of eight troop types, open an unlocked mission card, and hold the wall through fifteen waves. Spend round gold to summon or strengthen your formation.',
 'Drag the actual 3D soldier onto another soldier of the same rank. Different troop types can merge: the source tile becomes empty, the target gains one rank, and its new type is selected from your five equipped types with a 20% chance each. Rank 6 is the maximum. Moving to an empty tile is free. Tap source and destination or use Tab, arrow keys and Enter/Space for the same actions.',
 'Foxes fire quickly; bears deal splash damage; owls slow enemies; rabbits chain attacks; wolves ignore armor; raccoons poison; deer boost orthogonally adjacent troops; cats earn wave-end gold. A summon starts at rank 1 and makes the next summon more expensive. Formation upgrades improve all soldiers. Keep enough active attacks before risking a merge that could replace an important role.',
 'The chapter contains thirty named missions in six arcs. Entrance patterns, runners, armor, healers, splitting enemies, frozen tiles and limited gold change your decisions. Missions 5, 10, 15, 20, 25 and 30 have distinct bosses: charge, alternating armor, summoned helpers, row freeze, gold theft and combined attacks. Defeat a boss before it reaches the wall. Frost Burst damages, slows and interrupts a boss wind-up.',
 'Clear all fifteen waves with wall health remaining, including every spawned descendant and the checkpoint boss. A boss reaching the wall ends the defense. At least 90% wall health earns three stars; 50% earns two; another clear earns one. Frozen tiles cannot move or attack until thawed: move during the warning. Front targets the enemy nearest the wall; Strongest targets the highest current health. The 1x/2x switch changes both sides equally.',
 'Unlocked missions, best stars, best times and your five-type squad are stored in this browser. Gold, soldiers and formation upgrades reset for each new battle. Refreshing does not restore an active battle; unavailable storage keeps progress only for this session. Hidden pages pause without time catch-up. Back asks before leaving. Graphics recovery preserves the current simulation until you leave or reload. There is no gameplay account, purchase or advertising slot; shared site services follow WeightPlay policy.'
 ]},
 'zh-Hant':{title:'合成守城',description:'拖曳同級動物士兵，隨機合成出戰兵種，配置五種陣容，挑戰 30 關、每關 15 波的冰雪守城戰。',headings:['守住冰雪城牆','同級合成，兵種重新隨機','配置五種出戰兵種','三十關與六種頭目','過關、失敗與下一步','本機進度與瀏覽器恢復'],faqTitle:'合成守城常見問題',questions:['不同兵種也能合成嗎？','重新整理會保留這場戰鬥嗎？','要怎樣才算過關？'],related:'相關遊戲',start:'開始遊戲',retry:'重新整理',back:'返回',campaign:'關卡',stars:'星星',guide:[
 '合成守城是單人瀏覽器防守遊戲。敵人從上方入口向下進軍，動物士兵站在九個地板格上自動攻擊。從八種兵種中選擇五種，點擊已解鎖的關卡卡片，守住十五波敵人。使用本場金幣召喚士兵，或強化整支陣容。',
 '直接拖曳畫面中的 3D 士兵，放到相同等級的另一位士兵身上。兵種不同也能合成：來源格清空、目標升一級，再從五種出戰兵種中隨機產生新兵種，每種機率皆為 20%，最高六級。移動到空格不需金幣。也可依序點選來源與目的地，或用 Tab、方向鍵及 Enter／空白鍵操作。',
 '狐狸快速射擊，巨熊造成範圍傷害，貓頭鷹減速，兔子連鎖攻擊，野狼無視護甲，浣熊持續毒傷，鹿旗手強化上下左右鄰兵，招財貓提供每波收入。召喚產生一級士兵，並提高下一次召喚費用；強化則提高全隊傷害。合成可能換掉關鍵兵種，請先保留足夠的有效火力。',
 '本章有三十個命名關卡，分為六個區段。進場路線、快跑敵人、護甲、治療、分裂、結冰與金幣壓力會改變決策。第 5、10、15、20、25、30 關分別出現衝鋒、交替護甲、召喚小怪、冰凍整排、偷金幣與混合招式頭目。必須在頭目抵達城牆前擊敗；冰霜爆發能造成傷害、減速並打斷蓄力。',
 '清完十五波及所有分裂小怪、擊敗該關頭目，且城牆仍有血量才算過關。頭目抵達城牆會直接失守。城牆剩餘至少九成得三星、至少五成得兩星，其餘過關得一星。結冰格上的士兵無法移動或攻擊，請在預警時搬離。「最前方」優先打靠近城牆的敵人，「最強」優先打目前血量最高者；一倍、兩倍速同時影響雙方。',
 '已解鎖關卡、最高星數、最佳時間及五種出戰陣容會儲存在此瀏覽器。本場金幣、士兵與強化每場重置；重新整理不會接續當前戰鬥。儲存空間不可用時，僅保留本次開啟期間的進度。移至背景會暫停，不追趕流逝時間；返回會先確認。繪圖恢復會保留當前模擬，直到離開或重新整理。本遊戲沒有帳號、購買或廣告版位，共用網站服務依 WeightPlay 政策運作。'
 ]},
 'zh-Hans':{title:'合成守城',description:'拖动同级动物士兵，随机合成出战兵种，配置五种阵容，挑战 30 关、每关 15 波的冰雪守城战。',headings:['守住冰雪城墙','同级合成，兵种重新随机','配置五种出战兵种','三十关与六种首领','过关、失败与下一步','本机进度与浏览器恢复'],faqTitle:'合成守城常见问题',questions:['不同兵种也能合成吗？','刷新会保留这场战斗吗？','怎样才算过关？'],related:'相关游戏',start:'开始游戏',retry:'刷新',back:'返回',campaign:'关卡',stars:'星星',guide:[
 '合成守城是单人浏览器防守游戏。敌人从上方入口向下进军，动物士兵站在九个地板格上自动攻击。从八种兵种中选择五种，点击已解锁的关卡卡片，守住十五波敌人。使用本场金币召唤士兵，或强化整支阵容。',
 '直接拖动画面中的 3D 士兵，放到相同等级的另一位士兵身上。兵种不同也能合成：来源格清空、目标升一级，再从五种出战兵种中随机产生新兵种，每种概率均为 20%，最高六级。移动到空格不需金币。也可依次点击来源与目的地，或用 Tab、方向键及 Enter／空格键操作。',
 '狐狸快速射击，巨熊造成范围伤害，猫头鹰减速，兔子连锁攻击，野狼无视护甲，浣熊持续毒伤，鹿旗手强化上下左右邻兵，招财猫提供每波收入。召唤产生一级士兵，并提高下一次召唤费用；强化则提高全队伤害。合成可能换掉关键兵种，请先保留足够的有效火力。',
 '本章有三十个命名关卡，分为六个区段。进场路线、快跑敌人、护甲、治疗、分裂、结冰与金币压力会改变决策。第 5、10、15、20、25、30 关分别出现冲锋、交替护甲、召唤小怪、冰冻整排、偷金币与混合招式首领。必须在首领抵达城墙前击败；冰霜爆发能造成伤害、减速并打断蓄力。',
 '清完十五波及所有分裂小怪、击败该关首领，且城墙仍有血量才算过关。首领抵达城墙会直接失守。城墙剩余至少九成得三星、至少五成得两星，其余过关得一星。结冰格上的士兵无法移动或攻击，请在预警时搬离。“最前方”优先打靠近城墙的敌人，“最强”优先打目前血量最高者；一倍、两倍速同时影响双方。',
 '已解锁关卡、最高星数、最佳时间及五种出战阵容会保存在此浏览器。本场金币、士兵与强化每场重置；刷新不会接续当前战斗。存储空间不可用时，仅保留本次打开期间的进度。移至后台会暂停，不追赶流逝时间；返回会先确认。图形恢复保留当前模拟，直到离开或刷新。本游戏没有账号、购买或广告位，共用网站服务依 WeightPlay 政策运行。'
 ]},
 ja:{title:'合成の砦',description:'同ランクの動物兵士をランダム合成。5種類の部隊を組み、各15ウェーブの30ステージで冬の城壁を守ろう。',headings:['冬の城壁を守る','同ランクからランダムな兵種へ','5種類の部隊を編成','30ステージと6体のボス','クリア条件と戦術','端末の記録と復旧'],faqTitle:'合成の砦の質問',questions:['違う兵種も合成できますか？','再読み込みで戦闘は戻りますか？','クリア条件は何ですか？'],related:'関連ゲーム',start:'始める',retry:'再読み込み',back:'戻る',campaign:'ステージ',stars:'スター',guide:[
 '合成の砦は1人用ブラウザー防衛ゲームです。上の門から進む敵を、9枚の床に立つ動物兵士が自動攻撃します。8種類から5種類を編成し、解放済みカードを押して15ウェーブを防衛。戦闘中のコインで召喚や全体強化を選びます。',
 '画面の3D兵士を同ランクの兵士へ直接ドラッグします。別兵種でも合成でき、元の床は空き、先の兵士は1ランク上がります。新兵種は編成した5種類から各20%で選ばれ、最高ランクは6です。空き床への移動は無料。順番にタップするか、Tab・矢印・Enter／スペースでも操作できます。',
 'キツネは高速射撃、クマは範囲、フクロウは減速、ウサギは連鎖、オオカミは装甲無視、アライグマは毒。シカは上下左右の仲間を強化し、ネコはウェーブ終了時に収入を生みます。召喚はランク1で次回費用が上昇。強化は全兵士に有効です。大事な役割を合成で失う前に火力を確保しましょう。',
 '章は6区間、名前付き30ステージ。入り口、走る敵、装甲、回復、分裂、凍結、コイン不足を組み合わせます。5・10・15・20・25・30では突撃、交互装甲、増援、列凍結、強奪、複合攻撃のボスが登場。城壁に着く前に倒してください。氷の衝撃はダメージと減速を与え、予備動作を中断します。',
 '15ウェーブと分裂した子敵をすべて倒し、該当ボスも倒して城壁を残せばクリア。ボスが城壁に到達すると敗北です。城壁HP90%以上で星3、50%以上で星2、それ以外のクリアで星1。凍結床は移動と攻撃ができないため予告中に移動。「先頭」は壁に近い敵、「最強」は現在HPが最大の敵を狙います。1倍・2倍速は両軍共通です。',
 '解放状況、最高スター、最速時間、部隊はこのブラウザーに保存。コイン、兵士、強化は毎戦リセットされ、再読み込みでは戦闘を復元しません。保存不可の場合は今回のセッションのみ保持。非表示中は停止して時間を追いかけません。戻る際は確認し、描画復旧は退出や再読み込みまで戦闘状態を保ちます。アカウント、課金、広告枠はなく、共通サイトサービスはWeightPlayの方針に従います。'
 ]},
 ko:{title:'합성 요새',description:'같은 등급의 동물 병사를 무작위 출전 병종으로 합성하세요. 다섯 병종을 꾸려 15공세씩 30스테이지의 겨울 성벽을 지킵니다.',headings:['겨울 성벽 방어','같은 등급으로 무작위 합성','다섯 병종의 부대','30스테이지와 여섯 보스','승리 조건과 전술','로컬 기록과 복구'],faqTitle:'합성 요새 질문',questions:['서로 다른 병종도 합성되나요?','새로고침으로 전투가 복구되나요?','스테이지 완료 조건은 무엇인가요?'],related:'관련 게임',start:'시작',retry:'새로고침',back:'뒤로',campaign:'스테이지',stars:'별',guide:[
 '합성 요새는 싱글 플레이 브라우저 방어 게임입니다. 위쪽 문에서 내려오는 적을 아홉 바닥 칸의 동물 병사가 자동 공격합니다. 여덟 병종 중 다섯을 선택하고 열린 스테이지 카드를 누르세요. 15공세를 막으며 전투 골드로 소환하거나 부대 전체를 강화합니다.',
 '화면의 3D 병사를 같은 등급의 병사에게 직접 드래그하세요. 병종이 달라도 합성되어 시작 칸은 비고 대상은 한 등급 오릅니다. 새 병종은 출전한 다섯 종류 중 각각 20%로 정해지며 최고 6등급입니다. 빈칸 이동은 무료입니다. 두 칸을 차례로 누르거나 Tab, 방향키, Enter/스페이스로도 같은 동작을 합니다.',
 '여우는 속사, 곰은 범위, 올빼미는 감속, 토끼는 연쇄, 늑대는 관통, 너구리는 독 공격을 합니다. 사슴은 상하좌우 병사를 강화하고 고양이는 공세 종료 수입을 줍니다. 소환은 1등급이며 다음 소환이 비싸집니다. 강화는 모든 병사에 적용됩니다. 합성으로 핵심 역할을 잃기 전에 충분한 화력을 유지하세요.',
 '장에는 여섯 구간으로 나뉜 이름 있는 30스테이지가 있습니다. 입구, 빠른 적, 방어구, 치료, 분열, 얼음, 골드 부족이 결합됩니다. 5, 10, 15, 20, 25, 30에는 돌격, 교대 방어구, 지원군, 행 빙결, 절도, 복합 공격 보스가 나옵니다. 성벽에 닿기 전에 처치하세요. 서리 폭발은 피해와 감속을 주며 준비 동작을 끊습니다.',
 '분열한 적까지 포함한 15공세와 해당 보스를 모두 처치하고 성벽이 남아 있으면 완료입니다. 보스가 성벽에 도착하면 패배합니다. 성벽 체력 90% 이상은 별 셋, 50% 이상은 둘, 나머지 승리는 하나입니다. 얼어 있는 칸은 이동과 공격을 못 하니 경고 중 옮기세요. 선두는 성벽에 가까운 적, 최강은 현재 체력이 가장 높은 적을 겨냥합니다. 1배와 2배속은 양쪽에 동일합니다.',
 '열린 스테이지, 최고 별, 최단 시간, 부대는 이 브라우저에 저장됩니다. 골드, 병사, 강화는 전투마다 초기화되며 새로고침은 전투를 복구하지 않습니다. 저장 불가 시 이번 세션만 유지됩니다. 숨겨진 페이지는 멈추고 시간을 따라잡지 않습니다. 뒤로 가기는 확인하며 그래픽 복구는 떠나거나 새로고침하기 전까지 상태를 보존합니다. 계정, 구매, 광고 슬롯은 없으며 공용 사이트 서비스는 WeightPlay 정책을 따릅니다.'
 ]},
 es:{title:'Fortaleza Fusión',description:'Fusiona soldados animales del mismo rango en tropas equipadas aleatorias y defiende una muralla invernal en 30 misiones de 15 oleadas.',headings:['Defiende la muralla invernal','Mismo rango, tipo aleatorio','Forma un equipo de cinco tipos','Treinta misiones y seis jefes','Victoria, derrota y decisiones','Progreso local y recuperación'],faqTitle:'Preguntas sobre Fortaleza Fusión',questions:['¿Puedo fusionar tipos distintos?','¿Recargar conserva la batalla?','¿Cómo completo una misión?'],related:'Juego relacionado',start:'Jugar',retry:'Recargar',back:'Volver',campaign:'Misiones',stars:'Estrellas',guide:[
 'Fortaleza Fusión es un juego de defensa individual para navegador. Los enemigos bajan del portal y los soldados animales atacan solos desde nueve casillas. Elige cinco de ocho tipos y toca una misión desbloqueada para resistir quince oleadas. Usa el oro de la partida para invocar tropas o mejorar toda la formación.',
 'Arrastra el soldado 3D directamente sobre otro del mismo rango. Los tipos pueden ser distintos: el origen queda libre, el destino sube un rango y su nuevo tipo se elige entre los cinco equipados con un 20% de probabilidad cada uno. El máximo es rango 6. Mover a una casilla vacía es gratis. También puedes tocar origen y destino o usar Tab, flechas y Enter/Espacio.',
 'Zorros disparan rápido; osos dañan grupos; búhos ralentizan; conejos encadenan; lobos ignoran armadura; mapaches envenenan; ciervos refuerzan vecinos ortogonales; gatos dan ingresos tras las oleadas. Invocar crea rango 1 y encarece la próxima invocación. Las mejoras afectan a todos. Conserva ataques útiles antes de arriesgar una fusión que sustituya un papel clave.',
 'Hay treinta misiones con nombre en seis tramos. Entradas, corredores, armadura, curación, división, hielo y escasez de oro cambian las decisiones. Los niveles 5, 10, 15, 20, 25 y 30 tienen jefes de carga, armadura alternante, refuerzos, fila helada, robo y ataques combinados. Derrótalos antes de llegar a la muralla. El estallido helado daña, ralentiza e interrumpe preparaciones.',
 'Elimina las quince oleadas, sus descendientes y el jefe correspondiente conservando salud de muralla. Si un jefe llega, pierdes. Con al menos 90% de salud ganas tres estrellas; con 50%, dos; otra victoria, una. Una casilla congelada no puede moverse ni atacar: actúa durante el aviso. Primero apunta al más cercano a la muralla; Más fuerte, a la mayor salud actual. La velocidad 1x/2x afecta a ambos bandos.',
 'Misiones desbloqueadas, mejores estrellas, tiempos y equipo se guardan en este navegador. Oro, soldados y mejoras se reinician en cada batalla; recargar no recupera el combate. Sin almacenamiento, el progreso dura esta sesión. Las páginas ocultas pausan sin recuperar tiempo. Volver pide confirmación y la recuperación gráfica conserva la simulación hasta salir o recargar. No hay cuenta de juego, compras ni espacio publicitario; los servicios comunes siguen la política de WeightPlay.'
 ]},
 'pt-BR':{title:'Fortaleza da Fusão',description:'Funda soldados animais do mesmo nível em tropas equipadas aleatórias e defenda uma muralha de inverno em 30 missões de 15 ondas.',headings:['Defenda a muralha de inverno','Mesmo nível, tipo aleatório','Monte cinco tipos de tropas','Trinta missões e seis chefes','Vitória, derrota e decisões','Progresso local e recuperação'],faqTitle:'Perguntas sobre Fortaleza da Fusão',questions:['Tipos diferentes podem se fundir?','Recarregar mantém a batalha?','Como concluo uma missão?'],related:'Jogo relacionado',start:'Jogar',retry:'Recarregar',back:'Voltar',campaign:'Missões',stars:'Estrelas',guide:[
 'Fortaleza da Fusão é um jogo de defesa individual no navegador. Inimigos descem do portal enquanto soldados animais atacam automaticamente de nove casas. Escolha cinco de oito tipos e toque em uma missão liberada para resistir a quinze ondas. Use o ouro da partida para invocar tropas ou melhorar toda a formação.',
 'Arraste o soldado 3D diretamente sobre outro do mesmo nível. Os tipos podem ser diferentes: a origem fica vazia, o destino sobe um nível e o novo tipo é sorteado entre os cinco equipados, com 20% para cada. O máximo é nível 6. Mover para uma casa vazia é grátis. Também pode tocar origem e destino ou usar Tab, setas e Enter/Espaço.',
 'Raposas disparam rápido; ursos acertam grupos; corujas desaceleram; coelhos encadeiam; lobos ignoram armadura; guaxinins envenenam; cervos fortalecem vizinhos ortogonais; gatos geram renda após ondas. Invocar cria nível 1 e aumenta o próximo preço. Melhorias afetam todos. Mantenha ataques úteis antes de arriscar uma fusão que troque uma função importante.',
 'São trinta missões com nomes em seis trechos. Entradas, corredores, armaduras, curadores, divisão, gelo e pouco ouro mudam decisões. As missões 5, 10, 15, 20, 25 e 30 trazem chefes com carga, armadura alternada, reforços, fileira congelada, roubo e golpes combinados. Derrote-os antes da muralha. A explosão de gelo causa dano, desacelera e interrompe preparações.',
 'Elimine as quinze ondas, os descendentes e o chefe da missão mantendo vida na muralha. Um chefe que chega causa derrota. Pelo menos 90% de vida dá três estrelas; 50%, duas; outra vitória, uma. Casas congeladas impedem movimento e ataque: mova durante o aviso. Frente mira o mais próximo da muralha; Mais forte, a maior vida atual. A velocidade 1x/2x vale para ambos.',
 'Missões, melhores estrelas, tempos e equipe ficam salvos neste navegador. Ouro, soldados e melhorias reiniciam por batalha; recarregar não recupera o combate. Sem armazenamento, a sessão mantém o progresso. Páginas ocultas pausam sem compensar tempo. Voltar pede confirmação e a recuperação gráfica preserva a simulação até sair ou recarregar. Não há conta, compras ou espaço de anúncios no jogo; serviços comuns seguem a política do WeightPlay.'
 ]},
 fr:{title:'Forteresse Fusion',description:'Fusionnez des soldats animaux de même rang en types équipés aléatoires et défendez un rempart d’hiver dans 30 missions de 15 vagues.',headings:['Défendre le rempart d’hiver','Même rang, nouveau type aléatoire','Composer cinq types de troupes','Trente missions et six boss','Victoire, défaite et décisions','Progression locale et récupération'],faqTitle:'Questions sur Forteresse Fusion',questions:['Peut-on fusionner des types différents ?','Actualiser conserve-t-il la bataille ?','Comment réussir une mission ?'],related:'Jeu associé',start:'Jouer',retry:'Recharger',back:'Retour',campaign:'Missions',stars:'Étoiles',guide:[
 'Forteresse Fusion est un jeu de défense solo sur navigateur. Les ennemis descendent du portail tandis que les soldats animaux attaquent seuls depuis neuf cases. Choisissez cinq types sur huit et touchez une mission débloquée pour affronter quinze vagues. L’or de la partie sert à invoquer ou à renforcer toute la formation.',
 'Glissez directement le soldat 3D sur un autre de même rang. Les types peuvent différer : la case source se libère, la cible gagne un rang et son nouveau type est tiré parmi les cinq équipés, chacun à 20 %. Le rang maximal est 6. Aller sur une case vide est gratuit. Vous pouvez aussi toucher source puis destination, ou utiliser Tab, les flèches et Entrée/Espace.',
 'Renard : tirs rapides ; ours : zone ; hibou : ralentissement ; lapin : chaîne ; loup : perforation ; raton : poison ; cerf : soutien des voisins orthogonaux ; chat : revenu après les vagues. Une invocation crée un rang 1 et augmente le prochain prix. Les améliorations affectent tous les soldats. Gardez assez de puissance avant une fusion pouvant remplacer un rôle essentiel.',
 'Trente missions nommées forment six sections. Entrées, coureurs, armures, soins, division, gel et manque d’or modifient les décisions. Les missions 5, 10, 15, 20, 25 et 30 ajoutent charge, armure alternée, renforts, rangée gelée, vol et attaques combinées. Battez chaque boss avant le rempart. Le souffle de givre blesse, ralentit et interrompt sa préparation.',
 'Éliminez les quinze vagues, tous les descendants et le boss concerné en conservant le rempart. Un boss qui arrive entraîne la défaite. Au moins 90 % de PV donne trois étoiles ; 50 %, deux ; une autre victoire, une. Une case gelée interdit mouvement et attaque : agissez pendant l’alerte. En tête vise le plus proche du rempart ; Plus puissant, les PV actuels maximaux. La vitesse 1x/2x affecte les deux camps.',
 'Missions débloquées, étoiles, meilleurs temps et équipe sont enregistrés dans ce navigateur. Or, soldats et améliorations repartent de zéro à chaque combat ; actualiser ne restaure pas une bataille. Sans stockage, la progression dure cette session. Une page masquée se met en pause sans rattrapage. Retour demande confirmation ; la récupération graphique garde la simulation jusqu’à la sortie ou au rechargement. Aucun compte, achat ou emplacement publicitaire de jeu ; les services communs suivent la politique WeightPlay.'
 ]},
 de:{title:'Fusionsfestung',description:'Verschmelze Tiersoldaten gleichen Rangs zu zufälligen ausgerüsteten Typen und verteidige die Wintermauer in 30 Missionen mit je 15 Wellen.',headings:['Die Wintermauer verteidigen','Gleicher Rang, zufälliger Typ','Fünf Truppentypen aufstellen','Dreißig Missionen, sechs Bosse','Sieg, Niederlage und Entscheidungen','Lokaler Fortschritt und Wiederherstellung'],faqTitle:'Fragen zur Fusionsfestung',questions:['Können verschiedene Typen verschmelzen?','Bleibt der Kampf beim Neuladen erhalten?','Wie schließe ich eine Mission ab?'],related:'Ähnliches Spiel',start:'Spielen',retry:'Neu laden',back:'Zurück',campaign:'Missionen',stars:'Sterne',guide:[
 'Fusionsfestung ist ein Einzelspieler-Verteidigungsspiel im Browser. Gegner kommen von oben, während Tiersoldaten auf neun Bodenfeldern automatisch angreifen. Wähle fünf von acht Typen und öffne eine freigeschaltete Missionskarte für fünfzehn Wellen. Mit Rundengold beschwörst du Soldaten oder verstärkst die gesamte Formation.',
 'Ziehe den 3D-Soldaten direkt auf einen Soldaten gleichen Rangs. Verschiedene Typen sind erlaubt: Das Quellfeld wird leer, das Ziel steigt einen Rang und erhält zufällig einen deiner fünf ausgerüsteten Typen, jeweils mit 20 %. Maximum ist Rang 6. Leere Felder sind kostenlos erreichbar. Alternativ Quelle und Ziel antippen oder Tab, Pfeile und Enter/Leertaste verwenden.',
 'Fuchs schießt schnell, Bär trifft Gruppen, Eule verlangsamt, Hase verkettet, Wolf ignoriert Rüstung, Waschbär vergiftet, Hirsch stärkt orthogonale Nachbarn und Katze verdient Gold nach Wellen. Beschwörung erzeugt Rang 1 und erhöht den nächsten Preis. Verstärkungen betreffen alle. Sichere genug Angriffe, bevor eine Fusion eine wichtige Rolle ersetzt.',
 'Dreißig benannte Missionen bilden sechs Abschnitte. Eingänge, Läufer, Rüstung, Heilung, Teilung, Frost und Goldmangel verändern Entscheidungen. Missionen 5, 10, 15, 20, 25 und 30 bringen Ansturm, wechselnde Rüstung, Helfer, Reihenfrost, Raub und kombinierte Bosse. Besiege sie vor der Mauer. Froststoß schädigt, verlangsamt und unterbricht Vorbereitungen.',
 'Besiege alle fünfzehn Wellen, entstandene Untergegner und den jeweiligen Boss mit verbleibendem Mauerleben. Erreicht ein Boss die Mauer, verlierst du. Mindestens 90 % Leben gibt drei Sterne, 50 % zwei, ein anderer Sieg einen. Auf gefrorenen Feldern sind Bewegung und Angriff unmöglich; handle während der Warnung. Vorne zielt auf den mauernächsten Gegner, Stark auf die höchsten aktuellen Lebenspunkte. Tempo 1x/2x gilt für beide Seiten.',
 'Freigeschaltete Missionen, Sterne, Bestzeiten und Team werden in diesem Browser gespeichert. Gold, Soldaten und Verstärkungen starten jeden Kampf neu; Neuladen stellt keinen laufenden Kampf wieder her. Ohne Speicher bleibt nur Sitzungsfortschritt. Verborgene Seiten pausieren ohne Aufholen. Zurück fragt nach; Grafik-Wiederherstellung behält die Simulation bis zum Verlassen oder Neuladen. Keine Spielkonten, Käufe oder Werbeflächen; gemeinsame Dienste folgen der WeightPlay-Richtlinie.'
 ]},
 it:{title:'Fortezza Fusione',description:'Fondi soldati animali dello stesso rango in tipi equipaggiati casuali e difendi le mura invernali in 30 missioni da 15 ondate.',headings:['Difendi le mura invernali','Stesso rango, tipo casuale','Prepara cinque tipi di truppe','Trenta missioni e sei boss','Vittoria, sconfitta e decisioni','Progressi locali e ripristino'],faqTitle:'Domande su Fortezza Fusione',questions:['Posso fondere tipi diversi?','Ricaricare conserva la battaglia?','Come completo una missione?'],related:'Gioco correlato',start:'Gioca',retry:'Ricarica',back:'Indietro',campaign:'Missioni',stars:'Stelle',guide:[
 'Fortezza Fusione è un gioco di difesa per un giocatore nel browser. I nemici scendono dal portale mentre i soldati animali attaccano automaticamente da nove caselle. Scegli cinque tipi su otto e apri una missione sbloccata per affrontare quindici ondate. Spendi l’oro della partita per evocare o potenziare l’intera formazione.',
 'Trascina direttamente il soldato 3D su un altro dello stesso rango. I tipi possono differire: l’origine si svuota, la destinazione sale di un rango e il nuovo tipo viene scelto tra i cinque equipaggiati, ciascuno al 20%. Il massimo è rango 6. Spostarsi su una casella vuota è gratis. Puoi anche toccare origine e destinazione o usare Tab, frecce e Invio/Spazio.',
 'Volpe spara veloce, orso colpisce gruppi, gufo rallenta, coniglio concatena, lupo ignora armatura, procione avvelena, cervo rafforza vicini ortogonali e gatto genera entrate dopo le ondate. Evocare crea rango 1 e aumenta il prossimo prezzo. I potenziamenti valgono per tutti. Mantieni abbastanza attacchi prima di rischiare una fusione che cambi un ruolo essenziale.',
 'Trenta missioni con nome formano sei sezioni. Ingressi, corridori, armatura, guarigione, divisione, gelo e scarsità d’oro cambiano le scelte. Le missioni 5, 10, 15, 20, 25 e 30 hanno boss con carica, armatura alternata, rinforzi, fila gelata, furto e attacchi combinati. Sconfiggili prima delle mura. L’esplosione gelida danneggia, rallenta e interrompe le preparazioni.',
 'Elimina tutte le quindici ondate, i discendenti e il boss previsto conservando salute delle mura. Un boss che arriva causa sconfitta. Almeno il 90% di salute dà tre stelle; il 50%, due; un’altra vittoria, una. Le caselle gelate impediscono movimento e attacco: agisci durante l’avviso. Davanti mira al più vicino alle mura, Forte alla maggiore salute attuale. La velocità 1x/2x vale per entrambe le parti.',
 'Missioni sbloccate, stelle, tempi migliori e squadra sono salvati nel browser. Oro, soldati e potenziamenti ripartono a ogni battaglia; ricaricare non riprende un combattimento. Senza memoria disponibile, i progressi durano questa sessione. Le pagine nascoste si fermano senza recuperare tempo. Indietro chiede conferma e il ripristino grafico conserva la simulazione fino all’uscita o al ricaricamento. Niente account, acquisti o spazi pubblicitari di gioco; i servizi comuni seguono la politica WeightPlay.'
 ]},
 ru:{title:'Крепость слияния',description:'Сливайте звериных бойцов одного ранга в случайные выбранные типы и защищайте зимнюю стену в 30 миссиях по 15 волн.',headings:['Защитите зимнюю стену','Один ранг, случайный новый тип','Соберите пять типов бойцов','Тридцать миссий и шесть боссов','Победа, поражение и решения','Локальный прогресс и восстановление'],faqTitle:'Вопросы о Крепости слияния',questions:['Можно ли сливать разные типы?','Сохраняется ли бой при обновлении?','Как пройти миссию?'],related:'Похожая игра',start:'Играть',retry:'Обновить',back:'Назад',campaign:'Миссии',stars:'Звёзды',guide:[
 'Крепость слияния — одиночная браузерная защита. Враги идут сверху от портала, а звериные бойцы автоматически стреляют с девяти плиток. Выберите пять из восьми типов и откройте доступную карточку миссии на пятнадцать волн. Тратьте золото раунда на призыв или усиление всей формации.',
 'Перетащите 3D-бойца прямо на другого того же ранга. Типы могут различаться: исходная плитка пустеет, целевой боец получает следующий ранг и случайный тип из ваших пяти, каждый с вероятностью 20%. Максимум — ранг 6. Движение на пустую плитку бесплатно. Можно нажать источник и цель либо использовать Tab, стрелки и Enter/Пробел.',
 'Лис стреляет быстро, медведь бьёт по площади, сова замедляет, кролик атакует цепью, волк игнорирует броню, енот отравляет, олень усиливает соседей по сторонам, кот приносит доход после волн. Призыв даёт ранг 1 и повышает следующую цену. Усиления действуют на всех. Сохраняйте достаточно атак перед слиянием, способным заменить важную роль.',
 'Тридцать именованных миссий образуют шесть разделов. Входы, бегуны, броня, лечение, деление, заморозка и нехватка золота меняют решения. На 5, 10, 15, 20, 25 и 30 встречаются боссы с тараном, сменой брони, подмогой, заморозкой ряда, кражей и смешанными атаками. Победите их до стены. Морозный взрыв ранит, замедляет и прерывает подготовку.',
 'Уничтожьте пятнадцать волн, всех появившихся потомков и нужного босса, сохранив здоровье стены. Прибытие босса означает поражение. От 90% здоровья — три звезды, от 50% — две, иная победа — одна. Замёрзшие плитки запрещают движение и атаку: действуйте во время предупреждения. Впереди выбирает ближайшего к стене, Сильный — с максимальным текущим здоровьем. Скорость 1x/2x одинакова для сторон.',
 'Открытые миссии, звёзды, лучшие времена и отряд сохраняются в этом браузере. Золото, бойцы и усиления начинаются заново в каждом бою; обновление не возвращает текущую битву. Без хранилища прогресс живёт только в сеансе. Скрытая страница ставит паузу без догоняющего времени. Назад просит подтверждение, графическое восстановление сохраняет симуляцию до выхода или обновления. Нет игровых аккаунтов, покупок и рекламных мест; общие службы следуют правилам WeightPlay.'
 ]},
 hi:{title:'विलय दुर्ग',description:'समान रैंक के पशु सैनिकों को चुने दल के अनियमित प्रकार में मिलाएँ और 15 लहरों वाले 30 मिशनों में शीत दीवार बचाएँ।',headings:['बर्फीली दीवार की रक्षा','समान रैंक, नया अनियमित प्रकार','पाँच प्रकारों का दल','तीस मिशन और छह बॉस','जीत, हार और निर्णय','स्थानीय प्रगति और बहाली'],faqTitle:'विलय दुर्ग के प्रश्न',questions:['क्या अलग प्रकार मिल सकते हैं?','क्या रीफ़्रेश लड़ाई बचाता है?','मिशन कैसे पूरा होता है?'],related:'संबंधित खेल',start:'खेलें',retry:'रीफ़्रेश',back:'वापस',campaign:'मिशन',stars:'सितारे',guide:[
 'विलय दुर्ग एकल खिलाड़ी का ब्राउज़र रक्षा खेल है। दुश्मन ऊपरी द्वार से नीचे आते हैं और नौ फ़र्श खानों पर पशु सैनिक अपने आप हमला करते हैं। आठ में से पाँच प्रकार चुनकर खुले मिशन का कार्ड दबाएँ और पंद्रह लहरों को रोकें। दौर के सोने से सैनिक बुलाएँ या पूरा दल मज़बूत करें।',
 'दिख रहे 3D सैनिक को उसी रैंक के दूसरे सैनिक पर सीधे खींचें। प्रकार अलग हो सकते हैं: पहला खाना खाली, दूसरा एक रैंक ऊँचा और नया प्रकार चुने पाँच में से हर एक की 20% संभावना से मिलता है। अधिकतम रैंक 6 है। खाली खाने में जाना मुफ़्त है। क्रम से दोनों खाने छुएँ या Tab, तीर कुंजियाँ और Enter/स्पेस उपयोग करें।',
 'लोमड़ी तेज़ गोली, भालू समूह नुकसान, उल्लू धीमापन, खरगोश श्रृंखला, भेड़िया कवच भेदन, रैकून ज़हर देता है। हिरण ऊपर-नीचे-दाएँ-बाएँ साथियों को मज़बूत और बिल्ली लहर के बाद आय देती है। बुलाया सैनिक रैंक 1 का है और अगली कीमत बढ़ती है। मज़बूती सभी सैनिकों पर लगती है। ज़रूरी भूमिका खो सकने वाले विलय से पहले पर्याप्त हमले रखें।',
 'तीस नाम वाले मिशन छह भागों में हैं। प्रवेश, तेज़ शत्रु, कवच, उपचार, विभाजन, बर्फ और कम सोना निर्णय बदलते हैं। 5, 10, 15, 20, 25, 30 पर धावा, बदलता कवच, सहायक, जमी पंक्ति, चोरी और मिश्रित हमले वाले बॉस आते हैं। दीवार से पहले उन्हें हराएँ। हिम विस्फोट नुकसान और धीमापन देता और तैयारी रोकता है।',
 'पंद्रह लहरें, पैदा हुए छोटे शत्रु और संबंधित बॉस हराकर दीवार की कुछ सेहत बचाना जीत है। बॉस दीवार तक आया तो हार होगी। कम से कम 90% सेहत पर तीन सितारे, 50% पर दो, दूसरी जीत पर एक। जमे खाने में चलना और हमला रुकता है; चेतावनी में हटाएँ। सबसे आगे दीवार का निकटतम शत्रु चुनता है, ताकतवर सबसे अधिक वर्तमान सेहत। 1x/2x दोनों पक्षों पर समान है।',
 'खुले मिशन, सबसे अच्छे सितारे, समय और दल इस ब्राउज़र में सहेजे जाते हैं। सोना, सैनिक और मज़बूती हर लड़ाई में नए हैं; रीफ़्रेश वर्तमान लड़ाई नहीं लौटाता। संग्रहण न हो तो प्रगति इसी सत्र तक रहती है। छिपे पृष्ठ रुकते हैं और बीता समय नहीं पकड़ते। वापस जाने पर पुष्टि और ग्राफ़िक्स बहाली से बाहर निकलने या रीफ़्रेश तक स्थिति बचती है। खेल में खाते, खरीद या विज्ञापन स्थान नहीं हैं; साझा सेवाएँ WeightPlay नीति मानती हैं।'
 ]},
 ar:{title:'حصن الدمج',description:'ادمج جنود الحيوانات من الرتبة نفسها في أنواع عشوائية من فريقك، ودافع عن سور الشتاء عبر 30 مهمة من 15 موجة.',headings:['احمِ سور الشتاء','الرتبة نفسها ونوع عشوائي جديد','جهّز خمسة أنواع','ثلاثون مهمة وستة زعماء','الفوز والخسارة والقرارات','التقدم المحلي والاستعادة'],faqTitle:'أسئلة حصن الدمج',questions:['هل يمكن دمج أنواع مختلفة؟','هل يحفظ تحديث الصفحة المعركة؟','كيف أكمل المهمة؟'],related:'لعبة ذات صلة',start:'العب',retry:'إعادة التحميل',back:'رجوع',campaign:'المهام',stars:'النجوم',guide:[
 'حصن الدمج لعبة دفاع فردية في المتصفح. ينزل الأعداء من البوابة العلوية ويهاجم جنود الحيوانات تلقائيًا من تسع خانات أرضية. اختر خمسة أنواع من ثمانية وافتح بطاقة مهمة متاحة لمواجهة خمس عشرة موجة. أنفق ذهب الجولة لاستدعاء الجنود أو تعزيز التشكيل كله.',
 'اسحب الجندي ثلاثي الأبعاد مباشرة فوق جندي من الرتبة نفسها. يمكن اختلاف النوعين: تفرغ خانة المصدر وترتفع رتبة الهدف درجة، ويُختار نوعه الجديد من الأنواع الخمسة المجهزة باحتمال 20% لكل منها. الحد الأقصى رتبة 6. النقل لخانة فارغة مجاني. يمكن لمس المصدر ثم الوجهة أو استخدام Tab والأسهم وEnter/المسافة.',
 'الثعلب يطلق بسرعة، والدب يضرب المجموعات، والبومة تبطئ، والأرنب يتسلسل، والذئب يخترق الدرع، والراكون يسمّم، والأيل يقوي المجاورين أفقيًا وعموديًا، والقط يولد دخلًا بعد الموجات. الاستدعاء يعطي رتبة 1 ويرفع السعر التالي. التعزيز يشمل الجميع. احتفظ بهجمات كافية قبل دمج قد يستبدل دورًا مهمًا.',
 'ثلاثون مهمة مسماة موزعة على ستة أقسام. تتغير المداخل والعداؤون والدروع والعلاج والانقسام والجليد وقلة الذهب. مهام 5 و10 و15 و20 و25 و30 لها زعماء بالاندفاع والدرع المتناوب والمساعدين وتجميد الصف والسرقة والهجمات المركبة. اهزمهم قبل السور. انفجار الصقيع يضر ويبطئ ويقطع الاستعداد.',
 'اهزم الموجات الخمس عشرة وجميع الأعداء المتولدين والزعيم مع بقاء صحة للسور. وصول الزعيم يعني الخسارة. بقاء 90% على الأقل يعطي ثلاث نجوم، و50% نجمتين، وأي فوز آخر نجمة. تمنع الخانة المتجمدة الحركة والهجوم؛ انقل خلال التحذير. المتقدم يستهدف الأقرب للسور، والأقوى صاحب أعلى صحة حالية. سرعة 1x/2x تؤثر في الطرفين بالتساوي.',
 'تُحفظ المهام المفتوحة وأفضل النجوم والأوقات والفريق في هذا المتصفح. يبدأ الذهب والجنود والتعزيز من جديد كل معركة؛ التحديث لا يستعيد القتال الجاري. عند غياب التخزين يبقى التقدم للجلسة فقط. تتوقف الصفحات المخفية بلا تعويض للوقت. الرجوع يطلب التأكيد واستعادة الرسوميات تحفظ المحاكاة حتى الخروج أو التحديث. لا حسابات لعب أو مشتريات أو مواضع إعلانية؛ الخدمات المشتركة تتبع سياسة WeightPlay.'
 ]}
};
export const RELATED_NAMES={en:'Rune Reels','zh-Hant':'符文轉輪','zh-Hans':'符文转轮',ja:'ルーンリール',ko:'룬 릴',es:'Carretes de Runas','pt-BR':'Roletas de Runas',fr:'Roues de runes',de:'Runenräder',it:'Rulli di rune',ru:'Животные: рунические барабаны',hi:'रूण रील',ar:'بكرات الرون للحيوانات'};
export const FAQ_ANSWER_INDICES=[1,5,4];
