// Game-owned copy; presentation stays with the shared guide stylesheet.
export const guideCopy = {
 en: ['Cross ruined platforms, dodge hazards and defeat every enemy to open the next route.', 'Controls', 'Move with A/D or arrows; jump with W, Up or Space and jump again in midair. J attacks; K or Shift dashes. On mobile, use the visible buttons.', 'Growth and tactics', 'Collect experience and spend both upgrade points to resume combat. Save your second jump for a safe landing; bait guarded enemies into attacking, then strike during recovery. Later routes combine moving platforms, projectiles and timed hazards. Zero health ends the attempt; cleared routes stay unlocked.', 'Saving', 'Progress is saved in this browser; clearing site data may erase it. Diamonds buy only the optional Mist Amulet, never access to the campaign.'],
 'zh-Hant': ['穿越遺跡平台、閃避危險，擊敗所有敵人以開啟下一段路線。', '操作', 'A/D 或方向鍵移動；W、上鍵或空白鍵跳躍，空中可再跳一次。J 攻擊，K 或 Shift 衝刺。手機使用畫面按鈕。', '成長與攻略', '拾取經驗，升級後分配兩點屬性才能繼續。保留第二跳尋找安全落點，引誘有護盾的敵人出招後再反擊。後續路線會組合移動平台、飛彈與週期陷阱。生命歸零結束本次挑戰，已解鎖路線仍保留。', '存檔', '進度存在目前瀏覽器，清除網站資料可能遺失。鑽石只用於可選的迷霧護符，闖關不需要購買。'],
 'zh-Hans': ['穿越遗迹平台、闪避危险，击败所有敌人以开启下一段路线。', '操作', 'A/D 或方向键移动；W、上键或空格键跳跃，空中可再跳一次。J 攻击，K 或 Shift 冲刺。手机使用画面按钮。', '成长与攻略', '拾取经验，升级后分配两点属性才能继续。保留第二跳寻找安全落点，引诱有护盾的敌人出招后再反击。后续路线会组合移动平台、飞弹与周期陷阱。生命归零结束本次挑战，已解锁路线仍保留。', '存档', '进度存在当前浏览器，清除网站数据可能丢失。钻石只用于可选的迷雾护符，闯关不需要购买。'],
 ja: ['遺跡の足場を渡り、危険を避けて全ての敵を倒すと次の道が開きます。', '操作', 'A/Dまたは矢印で移動。W・上矢印・スペースでジャンプし、空中でもう一度跳べます。Jで攻撃、KまたはShiftでダッシュ。スマホでは画面のボタンを使います。', '成長と攻略', '経験値を集め、レベルアップ時の2ポイントを割り振ると戦闘が再開します。二段ジャンプは安全な着地のために残し、守りの固い敵は攻撃後の隙を狙いましょう。後半は動く足場、弾、周期的な罠が組み合わさります。体力がなくなると挑戦終了ですが、解放済みの道は残ります。', '保存', '進行はこのブラウザに保存されます。サイトデータを消すと失われる場合があります。ダイヤは任意の霧のお守り専用で、進行には不要です。'],
 ko: ['유적 발판을 건너 위험을 피하고 모든 적을 물리치면 다음 길이 열립니다.', '조작', 'A/D 또는 방향키로 이동합니다. W·위쪽·스페이스로 점프하고 공중에서 한 번 더 뛸 수 있습니다. J는 공격, K 또는 Shift는 돌진입니다. 휴대폰에서는 화면 버튼을 사용하세요.', '성장과 공략', '경험치를 모으고 레벨업한 뒤 두 포인트를 배분해야 전투가 재개됩니다. 두 번째 점프를 안전한 착지에 쓰고, 방어 중인 적은 공격 후 빈틈을 노리세요. 후반에는 이동 발판, 투사체, 주기적 함정이 조합됩니다. 체력이 바닥나면 도전은 끝나지만 열린 길은 유지됩니다.', '저장', '진행은 이 브라우저에 저장되며 사이트 데이터 삭제 시 사라질 수 있습니다. 다이아는 선택 사항인 안개 부적에만 쓰며 진행에는 필요하지 않습니다.'],
 es: ['Cruza las ruinas, esquiva peligros y derrota a todos los enemigos para abrir la siguiente ruta.', 'Controles', 'Muévete con A/D o flechas; salta con W, Arriba o Espacio y vuelve a saltar en el aire. J ataca; K o Mayús permite desplazarte rápidamente. En móvil, usa los botones visibles.', 'Mejoras y consejos', 'Recoge experiencia y asigna los dos puntos al subir de nivel para continuar. Reserva el segundo salto para aterrizar a salvo y contraataca cuando el enemigo baje la guardia. Más adelante se combinan plataformas móviles, proyectiles y trampas periódicas. Sin salud termina el intento, pero conservas las rutas abiertas.', 'Guardado', 'El progreso se guarda en este navegador; borrar los datos del sitio puede eliminarlo. Los diamantes solo compran el amuleto opcional, no el acceso a la campaña.'],
 'pt-BR': ['Atravesse as ruínas, desvie dos perigos e derrote todos os inimigos para abrir a próxima rota.', 'Controles', 'Mova-se com A/D ou setas; pule com W, Cima ou Espaço e pule novamente no ar. J ataca; K ou Shift avança rapidamente. No celular, use os botões da tela.', 'Evolução e dicas', 'Recolha experiência e distribua os dois pontos ao subir de nível para continuar. Guarde o segundo salto para um pouso seguro e ataque quando a guarda inimiga baixar. Depois, plataformas móveis, projéteis e armadilhas periódicas se combinam. Sem vida, a tentativa termina, mas as rotas abertas permanecem.', 'Salvamento', 'O progresso fica neste navegador; apagar os dados do site pode removê-lo. Diamantes compram apenas o amuleto opcional, não o acesso à campanha.'],
 fr: ['Traversez les ruines, évitez les dangers et battez tous les ennemis pour ouvrir le passage suivant.', 'Commandes', 'A/D ou flèches pour avancer ; W, Haut ou Espace pour sauter, puis sauter encore en l’air. J attaque ; K ou Maj permet une ruée. Sur mobile, utilisez les boutons visibles.', 'Progression et conseils', 'Ramassez l’expérience et attribuez les deux points de niveau pour reprendre le combat. Gardez le second saut pour une réception sûre et frappez après l’attaque d’un ennemi protégé. Les parcours suivants mêlent plateformes mobiles, projectiles et pièges périodiques. Sans vie, l’essai se termine ; les passages ouverts restent accessibles.', 'Sauvegarde', 'La progression reste dans ce navigateur ; effacer les données du site peut la supprimer. Les diamants servent uniquement à l’amulette facultative, pas à accéder à la campagne.'],
 de: ['Überquere die Ruinen, weiche Gefahren aus und besiege alle Gegner, um den nächsten Weg zu öffnen.', 'Steuerung', 'A/D oder Pfeile bewegen dich. W, Pfeil hoch oder Leertaste springt; in der Luft ist ein zweiter Sprung möglich. J greift an, K oder Umschalt führt einen Sprint aus. Mobil nutzt du die Bildschirmtasten.', 'Fortschritt und Tipps', 'Sammle Erfahrung und verteile beide Punkte beim Aufstieg, um weiterzukämpfen. Spare den zweiten Sprung für eine sichere Landung und kontere geschützte Gegner nach ihrem Angriff. Später treffen bewegliche Plattformen, Geschosse und zeitgesteuerte Fallen zusammen. Ohne Leben endet der Versuch; offene Wege bleiben erhalten.', 'Speichern', 'Der Fortschritt bleibt in diesem Browser. Gelöschte Websitedaten können ihn entfernen. Diamanten sind nur für das optionale Nebelamulett, nicht für den Kampagnenzugang nötig.'],
 it: ['Attraversa le rovine, evita i pericoli e sconfiggi tutti i nemici per aprire il percorso successivo.', 'Comandi', 'Muoviti con A/D o frecce; salta con W, Su o Spazio e salta ancora in aria. J attacca; K o Maiusc esegue uno scatto. Su mobile usa i pulsanti sullo schermo.', 'Crescita e consigli', 'Raccogli esperienza e assegna entrambi i punti del livello per riprendere. Conserva il secondo salto per atterrare al sicuro e contrattacca quando il nemico abbassa la guardia. Più avanti si combinano piattaforme mobili, proiettili e trappole periodiche. Senza salute termina il tentativo, ma i percorsi aperti restano disponibili.', 'Salvataggio', 'I progressi restano in questo browser; cancellare i dati del sito può eliminarli. I diamanti servono solo per l’amuleto facoltativo, non per accedere alla campagna.'],
 ru: ['Пересекайте руины, избегайте опасностей и побеждайте всех врагов, чтобы открыть следующий путь.', 'Управление', 'A/D или стрелки — движение; W, вверх или пробел — прыжок, в воздухе можно прыгнуть ещё раз. J — атака, K или Shift — рывок. На телефоне используйте экранные кнопки.', 'Развитие и советы', 'Собирайте опыт и распределяйте оба очка уровня, чтобы продолжить бой. Берегите второй прыжок для безопасного приземления и атакуйте защищённого врага после его удара. Дальше сочетаются движущиеся платформы, снаряды и периодические ловушки. Потеря здоровья завершает попытку, но открытые пути сохраняются.', 'Сохранение', 'Прогресс хранится в этом браузере; очистка данных сайта может его удалить. Алмазы нужны только для необязательного амулета, а не для доступа к кампании.'],
 hi: ['खंडहरों के मंच पार करें, खतरों से बचें और सभी दुश्मनों को हराकर अगला रास्ता खोलें।', 'नियंत्रण', 'A/D या तीर से चलें। W, ऊपर या स्पेस से कूदें और हवा में फिर कूद सकते हैं। J से हमला, K या Shift से डैश करें। मोबाइल पर स्क्रीन के बटन इस्तेमाल करें।', 'विकास और सुझाव', 'अनुभव इकट्ठा करें और स्तर बढ़ने पर दोनों अंक बाँटकर लड़ाई जारी रखें। दूसरी छलांग सुरक्षित उतरने के लिए बचाएँ और सुरक्षित दुश्मन के हमले के बाद पलटवार करें। आगे चलते मंच, प्रक्षेप्य और समयबद्ध जाल साथ आते हैं। स्वास्थ्य खत्म होने पर प्रयास समाप्त होता है, खुले रास्ते बने रहते हैं।', 'सेव', 'प्रगति इसी ब्राउज़र में रहती है; साइट डेटा मिटाने पर खो सकती है। हीरे केवल वैकल्पिक धुंध ताबीज के लिए हैं, अभियान खोलने के लिए नहीं।'],
 ar: ['اعبر منصات الأطلال وتجنب المخاطر واهزم جميع الأعداء لفتح الطريق التالي.', 'التحكم', 'تحرك بمفتاحي A/D أو الأسهم. اقفز بـ W أو سهم الأعلى أو المسافة، واقفز مرة ثانية في الهواء. J للهجوم وK أو Shift للاندفاع. على الهاتف استخدم أزرار الشاشة.', 'التطور والنصائح', 'اجمع الخبرة ووزع نقطتي الترقية لاستئناف القتال. احتفظ بالقفزة الثانية لهبوط آمن وهاجم العدو المحمي بعد انتهاء هجومه. تجمع الطرق اللاحقة منصات متحركة ومقذوفات وفخاخًا دورية. ينتهي المحاولة عند نفاد الصحة، لكن الطرق المفتوحة تبقى متاحة.', 'الحفظ', 'يُحفظ التقدم في هذا المتصفح؛ قد يؤدي مسح بيانات الموقع إلى فقدانه. الألماس للتميمة الاختيارية فقط وليس لفتح الحملة.'],
};
const faqCopy = {
 en: [['Is progress saved?', 'Yes. Cleared routes and upgrades stay in this browser; clearing site data may erase them.'], ['Are Diamonds required for the campaign?', 'No. Diamonds buy only the optional Mist Amulet and never unlock campaign access.']],
 'zh-Hant': [['進度會保存嗎？', '會，已完成路線與升級會保存在這個瀏覽器；清除網站資料可能會遺失。'], ['闖關需要鑽石嗎？', '不需要。鑽石只用於可選的迷霧護符，不會解鎖戰役進度。']],
 'zh-Hans': [['进度会保存吗？', '会，已完成路线与升级会保存在此浏览器；清除网站数据可能会丢失。'], ['闯关需要钻石吗？', '不需要。钻石只用于可选的迷雾护符，不会解锁战役进度。']],
 ja: [['進行状況は保存されますか？', 'はい。クリアした道とアップグレードはこのブラウザに保存されますが、サイトデータを消すと失われる場合があります。'], ['キャンペーンにダイヤは必要ですか？', 'いいえ。ダイヤは任意の霧のお守りにのみ使い、キャンペーンの解放には必要ありません。']],
 ko: [['진행 상황은 저장되나요?', '네. 클리어한 길과 업그레이드는 이 브라우저에 저장되지만 사이트 데이터를 지우면 사라질 수 있습니다.'], ['캠페인에 다이아가 필요한가요?', '아니요. 다이아는 선택 사항인 안개 부적에만 사용하며 캠페인을 여는 데 필요하지 않습니다.']],
 es: [['¿Se guarda el progreso?', 'Sí. Las rutas completadas y las mejoras se guardan en este navegador; borrar los datos del sitio puede eliminarlas.'], ['¿Necesito diamantes para la campaña?', 'No. Los diamantes solo compran el amuleto opcional y nunca desbloquean el acceso a la campaña.']],
 'pt-BR': [['O progresso é salvo?', 'Sim. As rotas concluídas e as melhorias ficam salvas neste navegador; limpar os dados do site pode apagá-las.'], ['Preciso de diamantes para a campanha?', 'Não. Os diamantes compram apenas o amuleto opcional e nunca liberam o acesso à campanha.']],
 fr: [['La progression est-elle sauvegardée ?', 'Oui. Les passages terminés et les améliorations restent dans ce navigateur ; effacer les données du site peut les supprimer.'], ['Faut-il des diamants pour la campagne ?', 'Non. Les diamants servent uniquement à l’amulette facultative et ne débloquent jamais la campagne.']],
 de: [['Wird der Fortschritt gespeichert?', 'Ja. Offene Wege und Verbesserungen werden in diesem Browser gespeichert; gelöschte Websitedaten können sie entfernen.'], ['Brauche ich Diamanten für die Kampagne?', 'Nein. Diamanten kaufen nur das optionale Nebelamulett und schalten die Kampagne nicht frei.']],
 it: [['I progressi vengono salvati?', 'Sì. I percorsi completati e i potenziamenti restano in questo browser; cancellare i dati del sito può eliminarli.'], ['Servono diamanti per la campagna?', 'No. I diamanti servono solo per l’amuleto facoltativo e non sbloccano la campagna.']],
 ru: [['Прогресс сохраняется?', 'Да. Открытые пути и улучшения хранятся в этом браузере; очистка данных сайта может их удалить.'], ['Нужны ли алмазы для кампании?', 'Нет. Алмазы нужны только для необязательного амулета и не открывают доступ к кампании.']],
 hi: [['क्या प्रगति सेव होती है?', 'हाँ। पूरे किए गए रास्ते और अपग्रेड इसी ब्राउज़र में सेव होते हैं; साइट डेटा मिटाने पर वे खो सकते हैं।'], ['क्या अभियान के लिए हीरे चाहिए?', 'नहीं। हीरे केवल वैकल्पिक धुंध ताबीज के लिए हैं और अभियान नहीं खोलते।']],
 ar: [['هل يُحفظ التقدم؟', 'نعم. تُحفظ الطرق المكتملة والترقيات في هذا المتصفح، وقد يؤدي مسح بيانات الموقع إلى فقدانها.'], ['هل أحتاج إلى الألماس للحملة؟', 'لا. الألماس للتميمة الاختيارية فقط، ولا يفتح الوصول إلى الحملة.']],
};
const escape = value => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function replaceShadowGuide(html, locale='en') {
 const c=guideCopy[locale];
 if(!c) throw Error(`Missing Shadow guide locale: ${locale}`);
 const summary=/<p\b[^>]*data-ui="menuHint"[^>]*>[\s\S]*?<\/p>/;
 if(!summary.test(html)) throw Error('Shadow Main summary missing');
 html=html.replace(summary,()=>`<p class="menu-hint" data-ui="menuHint" data-shadow-authored-summary="true" data-runtime-localize="off">${escape(c[0])}</p>`);
 const pattern=/<section\b[^>]*class="game-page-info game-page-info-static"[^>]*>[\s\S]*?<\/section>/;
 const old=html.match(pattern)?.[0];
 const title=old?.match(/<h2\b[^>]*>([\s\S]*?)<\/h2>/)?.[1];
 if(!title) throw Error('Shadow guide title missing');
 html=html.replace(/<body\b(?![^>]*data-wp-game-owned-guide)/,'<body data-wp-game-owned-guide="true"');
 const faq = (faqCopy[locale] || faqCopy.en).map(([question, answer]) => `<div><dt>${escape(question)}</dt><dd>${escape(answer)}</dd></div>`).join('');
 return html.replace(pattern,()=>`<section id="gameGuide" class="game-page-info game-page-info-static" data-wp-guide-complete="true" data-runtime-localize="off"><div class="game-info-hero"><div class="game-info-title"><h2>${title}</h2><p>${escape(c[0])}</p></div></div><div class="game-info-sections">${[1,3,5].map(i=>`<div class="game-info-section"><h3>${escape(c[i])}</h3><p>${escape(c[i+1])}</p></div>`).join('')}<div class="game-info-section"><h3>FAQ</h3><dl>${faq}</dl></div></div></section>`);
}
