(function () {
  "use strict";
  const en = {
    loading: "Waking the trail…", title: "Cairn Courier", world: "Mossy Ridge Trail",
    kicker: "A calm support-order puzzle", intro: "Read the trail note, then stack three marked stones from base to cap.",
    start: "Build the first cairn", choose: "Choose a trail", guideTitle: "How to play", guideOne: "Read the note and spot the support order.", guideTwo: "Tap stones from the ground up.", guideThree: "A wrong order clears gently so you can try again.",
    stages: "Trail map", back: "Back", round: "Cairn {n} of {total}", stageReady: "Build this cairn from the strongest base to the light cap.", stageTab: "Trails", roundName1: "Cedar Landing", roundName2: "Fern Turn", roundName3: "Moon Ridge", backToMain: "Back to Main", backToMap: "Back to Trail map", stageSections: "Trail sections",
    chooseStone: "Choose a stone", stackLabel: "Current stack", check: "Check the stack", clear: "Clear stack", selected: "{n} stones placed", waiting: "Choose the base stone first.",
    wrong: "That support order is not stable yet. Try the note again.", correct: "The cairn stands steady!", resultTitle: "Trail complete", resultPartial: "Cairn complete", resultText: "You built {count} of {total} cairns in {picks} picks.", next: "Next cairn", map: "Trail map", home: "Back to menu", settings: "Settings", sound: "Sound", soundOn: "Sound: On", soundOff: "Sound: Off", language: "Language", best: "Best picks", noBest: "Not yet", stoneBase: "Base stone", stoneMiddle: "Middle stone", stoneCap: "Cap stone", note1: "The broad stone carries the trail.", note2: "The notch faces the ridge.", note3: "The light mark closes the cairn.", complete: "Complete", open: "Open", coverAlt: "Pebble Paw builds a cairn on a sunlit mountain trail", guideAlt: "Pebble Paw holds a smooth trail stone", atlasAlt: "Three cairn stones and a steady completed cairn", resultAlt: "Pebble Paw celebrates a steady cairn", returnMain: "Back to WeightPlay", guideLabel: "Cairn Courier game guide"
  };
  const tables = {
    en,
    "zh-Hant": {
      loading: "正在喚醒步道…", title: "石堆信使", world: "苔蘚山脊步道", kicker: "平靜的支撐順序益智", intro: "讀懂步道筆記，再由底座到頂端堆好三顆標記石頭。", start: "堆好第一座石堆", choose: "選擇步道", guideTitle: "玩法", guideOne: "讀懂筆記，找出支撐順序。", guideTwo: "由地面往上點選石頭。", guideThree: "順序錯了會平靜清空，再試一次。", stages: "步道路線", back: "返回", round: "第 {n} 座／共 {total} 座", stageReady: "由最穩固的底座到輕巧頂石堆好這座石堆。", stageTab: "步道", roundName1: "雪松落腳處", roundName2: "蕨類轉彎", roundName3: "月光山脊", backToMain: "回到主選單", backToMap: "回到步道路線", stageSections: "步道路段", chooseStone: "選擇石頭", stackLabel: "目前堆疊", check: "檢查堆疊", clear: "清空堆疊", selected: "已放置 {n} 顆石頭", waiting: "請先選擇底座石。", wrong: "這個支撐順序還不穩，再讀一次筆記。", correct: "石堆穩穩站好了！", resultTitle: "步道完成", resultPartial: "石堆完成", resultText: "你用 {picks} 次選擇完成 {count}／{total} 座石堆。", next: "下一座石堆", map: "步道路線", home: "返回選單", settings: "設定", sound: "音效", soundOn: "音效：開", soundOff: "音效：關", language: "語言", best: "最佳選擇次數", noBest: "尚無紀錄", stoneBase: "底座石", stoneMiddle: "中層石", stoneCap: "頂石", note1: "寬大的石頭承托步道。", note2: "凹槽朝向山脊。", note3: "輕巧標記封住石堆。", complete: "已完成", open: "開放", coverAlt: "圓石爪在陽光山路上堆起石堆", guideAlt: "圓石爪拿著光滑的步道石", atlasAlt: "三顆石頭與穩固完成的石堆", resultAlt: "圓石爪為穩固石堆慶祝", returnMain: "返回 WeightPlay", guideLabel: "石堆信使遊戲指南"
    },
    "zh-Hans": {
      loading: "正在唤醒步道…", title: "石堆信使", world: "苔藓山脊步道", kicker: "平静的支撑顺序益智游戏", intro: "读懂步道笔记，再从底座到顶端堆好三颗标记石头。", start: "堆好第一座石堆", choose: "选择步道", guideTitle: "玩法", guideOne: "读懂笔记，找出支撑顺序。", guideTwo: "从地面向上点选石头。", guideThree: "顺序错了会平静清空，再试一次。", stages: "步道路线", back: "返回", round: "第 {n} 座／共 {total} 座", stageReady: "从最稳固的底座到轻巧的顶石堆好这座石堆。", stageTab: "步道", roundName1: "雪松落脚处", roundName2: "蕨类转弯", roundName3: "月光山脊", backToMain: "返回主菜单", backToMap: "返回步道路线", stageSections: "步道路段", chooseStone: "选择石头", stackLabel: "当前堆叠", check: "检查堆叠", clear: "清空堆叠", selected: "已放置 {n} 颗石头", waiting: "请先选择底座石。", wrong: "这个支撑顺序还不稳，再读一次笔记。", correct: "石堆稳稳站好了！", resultTitle: "步道完成", resultPartial: "石堆完成", resultText: "你用 {picks} 次选择完成 {count}／{total} 座石堆。", next: "下一座石堆", map: "步道路线", home: "返回菜单", settings: "设置", sound: "音效", soundOn: "音效：开", soundOff: "音效：关", language: "语言", best: "最佳选择次数", noBest: "尚无记录", stoneBase: "底座石", stoneMiddle: "中层石", stoneCap: "顶石", note1: "宽大的石头承托步道。", note2: "凹槽朝向山脊。", note3: "轻巧标记封住石堆。", complete: "已完成", open: "开放", coverAlt: "圆石爪在阳光山路上堆起石堆", guideAlt: "圆石爪拿着光滑的步道石", atlasAlt: "三颗石头与稳固完成的石堆", resultAlt: "圆石爪为稳固石堆庆祝", returnMain: "返回 WeightPlay", guideLabel: "石堆信使游戏指南"
    },
    ja: {
      loading: "道を目覚めさせています…", title: "ケルン・クーリエ", world: "苔むした尾根道", kicker: "支えの順番を読む静かなパズル", intro: "道しるべを読み、土台から頂石まで3つの印付きの石を積もう。", start: "最初のケルンを作る", choose: "道を選ぶ", guideTitle: "遊び方", guideOne: "道しるべを読み、支えの順番を見つけます。", guideTwo: "地面から上へ石をタップします。", guideThree: "順番を間違えても静かにリセットしてやり直せます。", stages: "道の地図", back: "戻る", round: "ケルン {n}／{total}", stageReady: "いちばん強い土台から軽い頂石まで、このケルンを積みます。", stageTab: "道", roundName1: "杉の降り場", roundName2: "シダの曲がり角", roundName3: "月の尾根", backToMain: "メインへ戻る", backToMap: "道の地図へ戻る", stageSections: "道の区間", chooseStone: "石を選ぶ", stackLabel: "現在の積み重ね", check: "積み方を確認", clear: "積み重ねを消す", selected: "{n}個の石を配置", waiting: "まず土台の石を選んでください。", wrong: "支えの順番がまだ安定しません。道しるべを読み直しましょう。", correct: "ケルンが安定しました！", resultTitle: "道を踏破", resultPartial: "ケルン完成", resultText: "{picks}回の選択で{total}基中{count}基のケルンを作りました。", next: "次のケルン", map: "道の地図", home: "メニューへ戻る", settings: "設定", sound: "サウンド", soundOn: "サウンド：オン", soundOff: "サウンド：オフ", language: "言語", best: "最少選択回数", noBest: "まだ記録なし", stoneBase: "土台の石", stoneMiddle: "中段の石", stoneCap: "頂石", note1: "幅広い石が道を支えます。", note2: "切り込みを尾根へ向けます。", note3: "軽い印の石でケルンを閉じます。", complete: "完了", open: "開放", coverAlt: "ペブル・ポーが日なたの山道でケルンを作る", guideAlt: "ペブル・ポーが滑らかな道の石を持つ", atlasAlt: "3つのケルン石と安定した完成形", resultAlt: "ペブル・ポーが安定したケルンを祝う", returnMain: "WeightPlayへ戻る", guideLabel: "ケルン・クーリエのゲームガイド"
    },
    ko: {
      loading: "길을 깨우는 중…", title: "돌무덤 배달부", world: "이끼 낀 능선 길", kicker: "지지 순서를 읽는 차분한 퍼즐", intro: "길 안내를 읽고 바닥부터 꼭대기까지 표시된 돌 세 개를 쌓아 보세요.", start: "첫 돌무덤 쌓기", choose: "길 선택", guideTitle: "게임 방법", guideOne: "안내를 읽고 지지 순서를 찾아보세요.", guideTwo: "땅에서 위로 돌을 탭하세요.", guideThree: "순서가 틀리면 조용히 비워지고 다시 시도할 수 있어요.", stages: "길 지도", back: "뒤로", round: "돌무덤 {n}／{total}", stageReady: "가장 튼튼한 바닥돌부터 가벼운 꼭대기돌까지 쌓으세요.", stageTab: "길", roundName1: "삼나무 쉼터", roundName2: "고사리 굽이", roundName3: "달빛 능선", backToMain: "메인으로 돌아가기", backToMap: "길 지도로 돌아가기", stageSections: "길 구간", chooseStone: "돌 선택", stackLabel: "현재 쌓기", check: "쌓기 확인", clear: "쌓기 비우기", selected: "돌 {n}개 배치됨", waiting: "먼저 바닥돌을 선택하세요.", wrong: "지지 순서가 아직 안정적이지 않아요. 안내를 다시 읽어 보세요.", correct: "돌무덤이 안정됐어요!", resultTitle: "길 완주", resultPartial: "돌무덤 완성", resultText: "{picks}번 선택으로 {total}개 중 {count}개의 돌무덤을 만들었어요.", next: "다음 돌무덤", map: "길 지도", home: "메뉴로 돌아가기", settings: "설정", sound: "소리", soundOn: "소리: 켜짐", soundOff: "소리: 꺼짐", language: "언어", best: "최고 선택 횟수", noBest: "아직 기록 없음", stoneBase: "바닥돌", stoneMiddle: "중간돌", stoneCap: "꼭대기돌", note1: "넓은 돌이 길을 받칩니다.", note2: "홈이 능선을 향합니다.", note3: "가벼운 표시돌이 돌무덤을 마무리합니다.", complete: "완료", open: "열림", coverAlt: "페블 포가 햇살 비치는 산길에서 돌무덤을 쌓는 모습", guideAlt: "페블 포가 매끄러운 길돌을 들고 있는 모습", atlasAlt: "돌무덤 돌 세 개와 안정된 완성 돌무덤", resultAlt: "페블 포가 안정된 돌무덤을 축하하는 모습", returnMain: "WeightPlay로 돌아가기", guideLabel: "돌무덤 배달부 게임 안내"
    },
    es: {
      loading: "Despertando el sendero…", title: "Mensajero de Cairns", world: "Sendero de la cresta musgosa", kicker: "Un rompecabezas tranquilo de apoyos", intro: "Lee la nota y apila tres piedras marcadas desde la base hasta la cima.", start: "Construir el primer cairn", choose: "Elegir sendero", guideTitle: "Cómo jugar", guideOne: "Lee la nota y descubre el orden de apoyo.", guideTwo: "Toca las piedras desde el suelo hacia arriba.", guideThree: "Si te equivocas, la pila se vacía suavemente para volver a intentarlo.", stages: "Mapa del sendero", back: "Atrás", round: "Cairn {n} de {total}", stageReady: "Construye este cairn desde la base más fuerte hasta la piedra ligera de arriba.", stageTab: "Senderos", roundName1: "Descanso del cedro", roundName2: "Curva del helecho", roundName3: "Cresta lunar", backToMain: "Volver al inicio", backToMap: "Volver al mapa del sendero", stageSections: "Secciones del sendero", chooseStone: "Elegir piedra", stackLabel: "Pila actual", check: "Comprobar pila", clear: "Vaciar pila", selected: "{n} piedras colocadas", waiting: "Elige primero la piedra base.", wrong: "El orden de apoyo aún no es estable. Lee la nota otra vez.", correct: "¡El cairn está firme!", resultTitle: "Sendero completado", resultPartial: "Cairn completado", resultText: "Construiste {count} de {total} cairns en {picks} elecciones.", next: "Siguiente cairn", map: "Mapa del sendero", home: "Volver al menú", settings: "Ajustes", sound: "Sonido", soundOn: "Sonido: activado", soundOff: "Sonido: desactivado", language: "Idioma", best: "Mejor número de elecciones", noBest: "Aún no", stoneBase: "Piedra base", stoneMiddle: "Piedra central", stoneCap: "Piedra superior", note1: "La piedra ancha sostiene el sendero.", note2: "La muesca mira hacia la cresta.", note3: "La marca ligera cierra el cairn.", complete: "Completado", open: "Abierto", coverAlt: "Piedra Pata construye un cairn en un sendero soleado", guideAlt: "Piedra Pata sostiene una piedra lisa del sendero", atlasAlt: "Tres piedras de cairn y un cairn firme terminado", resultAlt: "Piedra Pata celebra un cairn estable", returnMain: "Volver a WeightPlay", guideLabel: "Guía del juego Mensajero de Cairns"
    },
    "pt-BR": {
      loading: "Despertando a trilha…", title: "Mensageiro dos Marcos", world: "Trilha da serra coberta de musgo", kicker: "Um quebra-cabeça calmo de apoios", intro: "Leia a nota e empilhe três pedras marcadas da base ao topo.", start: "Construir o primeiro marco", choose: "Escolher trilha", guideTitle: "Como jogar", guideOne: "Leia a nota e descubra a ordem dos apoios.", guideTwo: "Toque nas pedras do chão para cima.", guideThree: "Se errar, a pilha esvazia suavemente para você tentar de novo.", stages: "Mapa da trilha", back: "Voltar", round: "Marco {n} de {total}", stageReady: "Construa este marco da base mais forte até a pedra leve do topo.", stageTab: "Trilhas", roundName1: "Descanso do cedro", roundName2: "Curva da samambaia", roundName3: "Serra da lua", backToMain: "Voltar ao início", backToMap: "Voltar ao mapa da trilha", stageSections: "Trechos da trilha", chooseStone: "Escolher pedra", stackLabel: "Pilha atual", check: "Conferir pilha", clear: "Limpar pilha", selected: "{n} pedras colocadas", waiting: "Escolha primeiro a pedra da base.", wrong: "A ordem de apoio ainda não está estável. Leia a nota novamente.", correct: "O marco ficou firme!", resultTitle: "Trilha concluída", resultPartial: "Marco concluído", resultText: "Você construiu {count} de {total} marcos em {picks} escolhas.", next: "Próximo marco", map: "Mapa da trilha", home: "Voltar ao menu", settings: "Configurações", sound: "Som", soundOn: "Som: ligado", soundOff: "Som: desligado", language: "Idioma", best: "Menor número de escolhas", noBest: "Ainda não", stoneBase: "Pedra da base", stoneMiddle: "Pedra do meio", stoneCap: "Pedra do topo", note1: "A pedra larga sustenta a trilha.", note2: "O entalhe aponta para a serra.", note3: "A marca leve fecha o marco.", complete: "Concluído", open: "Aberto", coverAlt: "Pata de Pedra constrói um marco em uma trilha ensolarada", guideAlt: "Pata de Pedra segura uma pedra lisa da trilha", atlasAlt: "Três pedras de marco e um marco firme concluído", resultAlt: "Pata de Pedra comemora um marco estável", returnMain: "Voltar ao WeightPlay", guideLabel: "Guia do jogo Mensageiro dos Marcos"
    },
    fr: {
      loading: "Réveil du sentier…", title: "Messager des Cairns", world: "Sentier de la crête moussue", kicker: "Un puzzle calme sur l’ordre des appuis", intro: "Lis la note puis empile trois pierres marquées, de la base au sommet.", start: "Construire le premier cairn", choose: "Choisir un sentier", guideTitle: "Comment jouer", guideOne: "Lis la note et trouve l’ordre des appuis.", guideTwo: "Touche les pierres du sol vers le haut.", guideThree: "Un mauvais ordre vide doucement la pile pour réessayer.", stages: "Carte du sentier", back: "Retour", round: "Cairn {n} sur {total}", stageReady: "Construis ce cairn de la base la plus solide jusqu’à la pierre légère du sommet.", stageTab: "Sentiers", roundName1: "Halte des cèdres", roundName2: "Virage des fougères", roundName3: "Crête de lune", backToMain: "Retour à l’accueil", backToMap: "Retour à la carte du sentier", stageSections: "Sections du sentier", chooseStone: "Choisir une pierre", stackLabel: "Pile actuelle", check: "Vérifier la pile", clear: "Vider la pile", selected: "{n} pierres posées", waiting: "Choisis d’abord la pierre de base.", wrong: "Cet ordre d’appui n’est pas encore stable. Relis la note.", correct: "Le cairn tient bien !", resultTitle: "Sentier terminé", resultPartial: "Cairn terminé", resultText: "Tu as construit {count} cairns sur {total} en {picks} choix.", next: "Cairn suivant", map: "Carte du sentier", home: "Retour au menu", settings: "Réglages", sound: "Son", soundOn: "Son : activé", soundOff: "Son : désactivé", language: "Langue", best: "Meilleur nombre de choix", noBest: "Pas encore", stoneBase: "Pierre de base", stoneMiddle: "Pierre centrale", stoneCap: "Pierre du sommet", note1: "La pierre large soutient le sentier.", note2: "L’encoche regarde la crête.", note3: "La marque légère ferme le cairn.", complete: "Terminé", open: "Ouvert", coverAlt: "Patte de Galet construit un cairn sur un sentier ensoleillé", guideAlt: "Patte de Galet tient une pierre lisse du sentier", atlasAlt: "Trois pierres de cairn et un cairn terminé bien stable", resultAlt: "Patte de Galet fête un cairn stable", returnMain: "Retour à WeightPlay", guideLabel: "Guide du jeu Messager des Cairns"
    },
    de: {
      loading: "Der Pfad erwacht…", title: "Steinmal-Bote", world: "Moosiger Höhenweg", kicker: "Ein ruhiges Rätsel der Stützfolge", intro: "Lies den Hinweis und stapel drei markierte Steine von der Basis bis zur Spitze.", start: "Erstes Steinmal bauen", choose: "Pfad wählen", guideTitle: "Spielanleitung", guideOne: "Lies den Hinweis und finde die Stützfolge.", guideTwo: "Tippe die Steine vom Boden nach oben an.", guideThree: "Bei einer falschen Folge wird der Stapel sanft geleert und du kannst es erneut versuchen.", stages: "Pfadkarte", back: "Zurück", round: "Steinmal {n} von {total}", stageReady: "Baue dieses Steinmal von der stärksten Basis bis zum leichten Deckstein.", stageTab: "Pfade", roundName1: "Zedernrast", roundName2: "Farnkurve", roundName3: "Mondgrat", backToMain: "Zum Hauptmenü", backToMap: "Zurück zur Pfadkarte", stageSections: "Pfadabschnitte", chooseStone: "Stein wählen", stackLabel: "Aktueller Stapel", check: "Stapel prüfen", clear: "Stapel leeren", selected: "{n} Steine gelegt", waiting: "Wähle zuerst den Basisstein.", wrong: "Diese Stützfolge ist noch nicht stabil. Lies den Hinweis erneut.", correct: "Das Steinmal steht sicher!", resultTitle: "Pfad geschafft", resultPartial: "Steinmal fertig", resultText: "Du hast {count} von {total} Steinmalen mit {picks} Auswahlen gebaut.", next: "Nächstes Steinmal", map: "Pfadkarte", home: "Zum Menü", settings: "Einstellungen", sound: "Ton", soundOn: "Ton: an", soundOff: "Ton: aus", language: "Sprache", best: "Wenigste Auswahlen", noBest: "Noch nicht", stoneBase: "Basisstein", stoneMiddle: "Mittelstein", stoneCap: "Deckstein", note1: "Der breite Stein trägt den Pfad.", note2: "Die Kerbe zeigt zum Grat.", note3: "Der leichte Markierungsstein schließt das Steinmal.", complete: "Fertig", open: "Offen", coverAlt: "Kieselpfote baut ein Steinmal auf einem sonnigen Bergpfad", guideAlt: "Kieselpfote hält einen glatten Pfadstein", atlasAlt: "Drei Steinmal-Steine und ein stabiles fertiges Steinmal", resultAlt: "Kieselpfote feiert ein stabiles Steinmal", returnMain: "Zurück zu WeightPlay", guideLabel: "Spielanleitung für Steinmal-Bote"
    },
    it: {
      loading: "Il sentiero si risveglia…", title: "Messaggero dei Cairn", world: "Sentiero della cresta muschiosa", kicker: "Un tranquillo rompicapo dell’ordine dei sostegni", intro: "Leggi la nota e impila tre pietre segnate dalla base alla cima.", start: "Costruisci il primo cairn", choose: "Scegli il sentiero", guideTitle: "Come si gioca", guideOne: "Leggi la nota e trova l’ordine dei sostegni.", guideTwo: "Tocca le pietre dal suolo verso l’alto.", guideThree: "Un ordine errato svuota delicatamente la pila per riprovare.", stages: "Mappa del sentiero", back: "Indietro", round: "Cairn {n} di {total}", stageReady: "Costruisci questo cairn dalla base più solida alla pietra leggera in cima.", stageTab: "Sentieri", roundName1: "Sosta dei cedri", roundName2: "Curva delle felci", roundName3: "Cresta lunare", backToMain: "Torna al menu principale", backToMap: "Torna alla mappa del sentiero", stageSections: "Sezioni del sentiero", chooseStone: "Scegli una pietra", stackLabel: "Pila attuale", check: "Controlla la pila", clear: "Svuota la pila", selected: "{n} pietre posate", waiting: "Scegli prima la pietra di base.", wrong: "L’ordine dei sostegni non è ancora stabile. Rileggi la nota.", correct: "Il cairn è stabile!", resultTitle: "Sentiero completato", resultPartial: "Cairn completato", resultText: "Hai costruito {count} cairn su {total} con {picks} scelte.", next: "Cairn successivo", map: "Mappa del sentiero", home: "Torna al menu", settings: "Impostazioni", sound: "Audio", soundOn: "Audio: attivo", soundOff: "Audio: disattivato", language: "Lingua", best: "Miglior numero di scelte", noBest: "Non ancora", stoneBase: "Pietra di base", stoneMiddle: "Pietra centrale", stoneCap: "Pietra superiore", note1: "La pietra larga sostiene il sentiero.", note2: "L’incavo guarda verso la cresta.", note3: "Il segno leggero chiude il cairn.", complete: "Completato", open: "Aperto", coverAlt: "Zampa di Ciottolo costruisce un cairn su un sentiero di montagna soleggiato", guideAlt: "Zampa di Ciottolo tiene una pietra liscia del sentiero", atlasAlt: "Tre pietre da cairn e un cairn stabile completato", resultAlt: "Zampa di Ciottolo festeggia un cairn stabile", returnMain: "Torna a WeightPlay", guideLabel: "Guida del gioco Messaggero dei Cairn"
    },
    ru: {
      loading: "Тропа просыпается…", title: "Курьер каменных пирамид", world: "Мшистая горная тропа", kicker: "Спокойная головоломка о порядке опор", intro: "Прочитайте заметку и сложите три отмеченных камня от основания до вершины.", start: "Сложить первую пирамиду", choose: "Выбрать тропу", guideTitle: "Как играть", guideOne: "Прочитайте заметку и найдите порядок опор.", guideTwo: "Нажимайте камни снизу вверх.", guideThree: "Неверный порядок мягко очистит кладку — попробуйте снова.", stages: "Карта тропы", back: "Назад", round: "Пирамида {n} из {total}", stageReady: "Сложите эту пирамиду от самой прочной основы до лёгкого верхнего камня.", stageTab: "Тропы", roundName1: "Кедровая стоянка", roundName2: "Поворот папоротников", roundName3: "Лунный хребет", backToMain: "Вернуться в главное меню", backToMap: "Вернуться к карте тропы", stageSections: "Участки тропы", chooseStone: "Выбрать камень", stackLabel: "Текущая кладка", check: "Проверить кладку", clear: "Очистить кладку", selected: "Уложено камней: {n}", waiting: "Сначала выберите камень основания.", wrong: "Порядок опор пока неустойчив. Перечитайте заметку.", correct: "Пирамида стоит ровно!", resultTitle: "Тропа пройдена", resultPartial: "Пирамида готова", resultText: "Вы сложили {count} из {total} пирамид за {picks} выборов.", next: "Следующая пирамида", map: "Карта тропы", home: "В меню", settings: "Настройки", sound: "Звук", soundOn: "Звук: включён", soundOff: "Звук: выключен", language: "Язык", best: "Лучшее число выборов", noBest: "Пока нет", stoneBase: "Камень основания", stoneMiddle: "Средний камень", stoneCap: "Верхний камень", note1: "Широкий камень держит тропу.", note2: "Выемка смотрит на хребет.", note3: "Лёгкий отмеченный камень завершает пирамиду.", complete: "Готово", open: "Открыто", coverAlt: "Каменная Лапка складывает пирамиду на солнечной горной тропе", guideAlt: "Каменная Лапка держит гладкий дорожный камень", atlasAlt: "Три камня пирамиды и устойчивая готовая кладка", resultAlt: "Каменная Лапка празднует устойчивую пирамиду", returnMain: "Вернуться в WeightPlay", guideLabel: "Руководство к игре «Курьер каменных пирамид»"
    },
    hi: {
      loading: "पगडंडी जाग रही है…", title: "पत्थर-ढेर संदेशवाहक", world: "काई से ढकी पहाड़ी पगडंडी", kicker: "सहारे के क्रम वाली शांत पहेली", intro: "पथ-नोट पढ़ें और तीन चिन्हित पत्थरों को आधार से शिखर तक रखें।", start: "पहला पत्थर-ढेर बनाएँ", choose: "पथ चुनें", guideTitle: "कैसे खेलें", guideOne: "नोट पढ़ें और सहारा क्रम खोजें।", guideTwo: "पत्थरों को ज़मीन से ऊपर की ओर टैप करें।", guideThree: "गलत क्रम पर ढेर धीरे से खाली हो जाता है, फिर कोशिश करें।", stages: "पथ मानचित्र", back: "वापस", round: "पत्थर-ढेर {n} / {total}", stageReady: "इस ढेर को सबसे मज़बूत आधार से हल्के शीर्ष पत्थर तक बनाएँ।", stageTab: "पथ", roundName1: "देवदार पड़ाव", roundName2: "फर्न मोड़", roundName3: "चाँदनी कटक", backToMain: "मुख्य मेनू पर लौटें", backToMap: "पथ मानचित्र पर लौटें", stageSections: "पथ खंड", chooseStone: "पत्थर चुनें", stackLabel: "वर्तमान ढेर", check: "ढेर जाँचें", clear: "ढेर खाली करें", selected: "{n} पत्थर रखे गए", waiting: "पहले आधार पत्थर चुनें।", wrong: "सहारा क्रम अभी स्थिर नहीं है। नोट फिर पढ़ें।", correct: "ढेर स्थिर खड़ा है!", resultTitle: "पथ पूरा", resultPartial: "ढेर पूरा", resultText: "आपने {picks} चयन में {total} में से {count} ढेर बनाए।", next: "अगला ढेर", map: "पथ मानचित्र", home: "मेनू पर लौटें", settings: "सेटिंग", sound: "ध्वनि", soundOn: "ध्वनि: चालू", soundOff: "ध्वनि: बंद", language: "भाषा", best: "सबसे कम चयन", noBest: "अभी नहीं", stoneBase: "आधार पत्थर", stoneMiddle: "बीच का पत्थर", stoneCap: "शीर्ष पत्थर", note1: "चौड़ा पत्थर पगडंडी को थामता है।", note2: "खांचा कटक की ओर है।", note3: "हल्का चिन्हित पत्थर ढेर को पूरा करता है।", complete: "पूरा", open: "खुला", coverAlt: "कंकड़ पंजा धूप वाली पहाड़ी पगडंडी पर पत्थर-ढेर बना रहा है", guideAlt: "कंकड़ पंजा चिकना पथर-पत्थर पकड़े हुए है", atlasAlt: "तीन ढेर-पत्थर और एक स्थिर पूरा ढेर", resultAlt: "कंकड़ पंजा स्थिर ढेर का जश्न मना रहा है", returnMain: "WeightPlay पर लौटें", guideLabel: "पत्थर-ढेर संदेशवाहक गेम गाइड"
    },
    ar: {
      loading: "إيقاظ الدرب…", title: "رسول أكوام الحجارة", world: "درب التلال المغطاة بالطحالب",
      kicker: "لغز هادئ لترتيب الدعائم", intro: "اقرأ ملاحظة الدرب، ثم رتّب ثلاث حجارة مميزة من القاعدة إلى القمة.",
      start: "ابنِ الكومة الأولى", choose: "اختر دربًا", guideTitle: "طريقة اللعب", guideOne: "اقرأ الملاحظة وحدد ترتيب الدعائم.", guideTwo: "اضغط الحجارة من الأرض إلى الأعلى.", guideThree: "الترتيب الخاطئ يفرغ الكومة بهدوء لتعيد المحاولة.",
      stages: "خريطة الدرب", back: "رجوع", round: "الكومة {n} من {total}", stageReady: "ابنِ هذه الكومة من أقوى قاعدة إلى الحجر العلوي الخفيف.", stageTab: "الدروب", roundName1: "منحدر الأرز", roundName2: "منعطف السرخس", roundName3: "حافة القمر", backToMain: "العودة إلى القائمة الرئيسية", backToMap: "العودة إلى خريطة الدرب", stageSections: "أقسام الدرب",
      chooseStone: "اختر حجرًا", stackLabel: "الكومة الحالية", check: "تحقق من الكومة", clear: "أفرغ الكومة", selected: "وُضعت {n} حجارة", waiting: "اختر حجر القاعدة أولًا.",
      wrong: "ترتيب الدعائم غير مستقر بعد. أعد قراءة الملاحظة.", correct: "الكومة ثابتة!", resultTitle: "اكتمل الدرب", resultPartial: "اكتملت الكومة", resultText: "بنيت {count} من {total} أكوام باستخدام {picks} اختيارات.", next: "الكومة التالية", map: "خريطة الدرب", home: "العودة إلى القائمة", settings: "الإعدادات", sound: "الصوت", soundOn: "الصوت: مفعّل", soundOff: "الصوت: متوقف", language: "اللغة", best: "أفضل عدد من الاختيارات", noBest: "لا يوجد بعد",
      stoneBase: "حجر القاعدة", stoneMiddle: "الحجر الأوسط", stoneCap: "الحجر العلوي", note1: "الحجر العريض يحمل الدرب.", note2: "الشق باتجاه التلال.", note3: "العلامة الخفيفة تغلق الكومة.", complete: "مكتملة", open: "مفتوحة",
      coverAlt: "بيبل باو يبني كومة حجارة على درب جبلي مشمس", guideAlt: "بيبل باو يحمل حجرًا أملس للدرب", atlasAlt: "ثلاث حجارة للكومة وكومة مكتملة ثابتة", resultAlt: "بيبل باو يحتفل بكومة ثابتة", returnMain: "العودة إلى WeightPlay", guideLabel: "دليل لعبة رسول أكوام الحجارة"
    }
  };
  window.ANIMAL_CAIRN_COURIER_LOCALES = tables;
}());
