(() => {
  const $ = (id) => document.getElementById(id);
  const saveKey = "weightplay_animal_cafe_rush_v1";
  const localeKey = "weightPlayLocale";
  const legacyLocaleKey = "weightplayLocale";
  const sessionStorageFallback = new Map();
  function readStorage(key) { try { const value=localStorage.getItem(key); if(value!==null) sessionStorageFallback.set(key,value); return value??sessionStorageFallback.get(key)??null; } catch { return sessionStorageFallback.get(key)??null; } }
  function writeStorage(key,value) { const serialized=String(value); sessionStorageFallback.set(key,serialized); try { localStorage.setItem(key,serialized); return true; } catch { return false; } }
  const canonicalSavedLocale = readStorage(localeKey);
  const legacySavedLocale = readStorage(legacyLocaleKey);
  if (!canonicalSavedLocale && ["en", "zh-Hant", "zh-Hans", "es", "ja"].includes(legacySavedLocale)) {
    writeStorage(localeKey, legacySavedLocale);
    window.WonderI18n?.setLocale?.(legacySavedLocale);
  }
  const food = ["smoothie", "sandwich", "fruit", "cookie"];
  const customers = ["lion", "giraffe", "panda", "rabbit"];
  const stations = { smoothie: "station-smoothie", sandwich: "station-sandwich", fruit: "station-fruit", cookie: "station-bakery" };
  const CAMPAIGN_DAYS = 30;
  if (!$("leavePanel")) {
    const panel = document.createElement("section");
    panel.id = "leavePanel";
    panel.className = "result-panel cafe-leave-panel is-hidden";
    panel.setAttribute("role", "dialog");
    panel.setAttribute("aria-modal", "true");
    panel.setAttribute("aria-labelledby", "leaveTitle");
    panel.innerHTML = '<div class="result-card cafe-leave-card"><h2 id="leaveTitle" data-ui="leaveTitle"></h2><p id="leaveText" data-ui="leaveText"></p><div><button id="continueDayBtn" class="primary-btn" type="button" data-ui="continueDay"></button><button id="leaveDayBtn" class="secondary-btn" type="button" data-ui="leaveDay"></button></div></div>';
    $("playPanel")?.append(panel);
  }
  const nodes = { locale: $("localeSelect"), menu: $("menuPanel"), stage: $("stagePanel"), play: $("playPanel"), result: $("resultPanel"), leave: $("leavePanel"), leaveTitle: $("leaveTitle"), leaveText: $("leaveText"), continueDay: $("continueDayBtn"), leaveDay: $("leaveDayBtn"), mainStart: $("mainStartBtn"), start: $("startBtn"), stageBack: $("stageBackBtn"), back: $("backToMenuBtn"), day: $("dayText"), coins: $("coinText"), best: $("bestText"), stageDay: $("stageDayText"), stageCoins: $("stageCoinText"), stageBest: $("stageBestText"), dayRail: $("dayRail"), playDay: $("playDay"), playCoins: $("playCoins"), served: $("servedText"), objective: $("objectiveRow"), customers: $("customerRow"), stations: $("stationRow"), tray: $("tray"), message: $("playMessage"), upgrades: $("upgradeCards"), resultTitle: $("resultTitle"), resultText: $("resultText"), skillText: $("skillText"), retry: $("retryBtn"), next: $("nextBtn"), menuBtn: $("menuBtn") };
  nodes.stage?.setAttribute("data-wp-stage-landscape-width", "760");
  nodes.stage?.setAttribute("data-wp-stage-landscape-height", "360");
  nodes.play?.setAttribute("data-wp-battle-landscape-width", "760");
  nodes.play?.setAttribute("data-wp-battle-landscape-height", "360");
  const copy = { en: { title:"Animal Cafe Rush", language:"Language", internal:"Internal prototype", menuTitle:"Serve the animal cafe.", menuHint:"Tap a customer, prepare each pictured order, then tap the ready tray to serve.", day:"Day", coins:"Coins", best:"Best", upgrades:"Cafe upgrades", upgradeHint:"Coins make future days friendlier.", start:"Start day", served:"Served", select:"Choose a customer", tray:"Ready tray", empty:"Choose the matching station", serve:"Serve selected customer", complete:"Day complete", next:"Next day", retry:"Try again", pause:"Customers need a break", pauseText:"Take it slowly and plan this day again.", menu:"Menu", skill:"You practiced planning, matching, and quick decisions.", speed:"Quick stations", capacity:"Extra tray", comfort:"Cozy cafe", smoothie:"Smoothie", sandwich:"Sandwich", fruit:"Fruit bowl", cookie:"Bakery treat", buy:"Upgrade {cost}", max:"Max", servedMessage:"Perfect service!", wrong:"That order belongs to another customer.", noTray:"Prepare the pictured order first.", locked:"Unlocks after Day {day}" }, "zh-Hant": { title:"動物咖啡快手", language:"語言", internal:"內部原型", menuTitle:"經營動物咖啡館。", menuHint:"點選客人，準備圖示餐點，再點選托盤完成服務。", day:"天數", coins:"金幣", best:"最佳", upgrades:"咖啡館升級", upgradeHint:"金幣讓之後的咖啡日更順利。", start:"開始營業", served:"已服務", select:"選擇一位客人", tray:"完成托盤", empty:"選擇對應工作站", serve:"服務選定客人", complete:"今日完成", next:"下一天", retry:"再試一次", pause:"客人需要休息", pauseText:"慢慢來，重新安排這一天的訂單。", menu:"選單", skill:"你練習了規劃、配對與快速判斷。", speed:"快速工作站", capacity:"加大托盤", comfort:"舒適咖啡館", smoothie:"果昔", sandwich:"三明治", fruit:"水果碗", cookie:"烘焙點心", buy:"升級 {cost}", max:"已滿", servedMessage:"服務得很完美！", wrong:"這份餐點屬於另一位客人。", noTray:"先準備圖示中的餐點。", locked:"通過第 {day} 天後解鎖" } };
  const flowCopy = { en: { pickFood:"Pick the food tiles for an order.", deliver:"Tap the customer whose bubble matches your selected food.", selected:"Selected food", queue:"More customers are joining the line.", priority:"VIP", rating:"Business rating", leaving:"A customer left unhappy.", basics:"Match the pictured foods", sequence:"Cook from 1 to 2 to 3", vip:"Serve a waiting VIP first", table:"Serve Table A, then Table B", variety:"Serve a different animal next", festival:"Festival: combine the visible rules", checkpoint:"Cafe Review", sequenceWrong:"Follow the numbered recipe order.", vipWrong:"A VIP is waiting. Serve that guest first.", tableWrong:"Serve Table {table} next.", varietyWrong:"Choose a different animal next.", tableTag:"Table {table}" }, "zh-Hant": { pickFood:"\u9ede\u9078\u9910\u9ede\u65b9\u584a\u7d44\u51fa\u8a02\u55ae\u3002", deliver:"\u9ede\u9078\u982d\u4e0a\u8a02\u55ae\u8207\u5df2\u9078\u9910\u9ede\u76f8\u540c\u7684\u5ba2\u4eba\u3002", selected:"\u5df2\u9078\u9910\u9ede", queue:"\u66f4\u591a\u5ba2\u4eba\u6b63\u5728\u6392\u968a\u3002", priority:"VIP", rating:"\u71df\u696d\u8a55\u5206", leaving:"\u5ba2\u4eba\u4e0d\u958b\u5fc3\u5730\u96e2\u958b\u4e86\u3002", basics:"\u914d\u5c0d\u5716\u7247\u9910\u9ede", sequence:"\u4f9d 1\u30012\u30013 \u7684\u9806\u5e8f\u6599\u7406", vip:"\u5148\u670d\u52d9\u7b49\u5f85\u4e2d\u7684 VIP", table:"A \u684c\u3001B \u684c\u8f2a\u6d41\u670d\u52d9", variety:"\u4e0b\u4e00\u4f4d\u8981\u63db\u4e0d\u540c\u52d5\u7269", festival:"\u6176\u5178\uff1a\u7d44\u5408\u756b\u9762\u4e0a\u7684\u898f\u5247", checkpoint:"\u5496\u5561\u9928\u5be9\u67e5", sequenceWrong:"\u8acb\u6309\u7167\u6578\u5b57\u9806\u5e8f\u6e96\u5099\u9910\u9ede\u3002", vipWrong:"VIP \u6b63\u5728\u7b49\u5f85\uff0c\u8acb\u5148\u670d\u52d9\u3002", tableWrong:"\u4e0b\u4e00\u4f4d\u8acb\u670d\u52d9 {table} \u684c\u3002", varietyWrong:"\u4e0b\u4e00\u4f4d\u8acb\u63db\u4e0d\u540c\u52d5\u7269\u3002", tableTag:"{table} \u684c" } };
  copy.es = { title:"Café Animal Exprés", language:"Idioma", internal:"Prototipo interno", menuTitle:"Atiende el café de los animales.", menuHint:"Toca a un cliente, prepara cada pedido ilustrado y sirve la bandeja cuando esté lista.", day:"Día", coins:"Monedas", best:"Mejor", upgrades:"Mejoras del café", upgradeHint:"Las monedas facilitan los próximos días.", start:"Abrir el café", served:"Atendidos", select:"Elige un cliente", tray:"Bandeja lista", empty:"Elige la estación correcta", serve:"Atender al cliente elegido", complete:"Día completado", next:"Siguiente día", retry:"Intentar de nuevo", pause:"Los clientes necesitan un descanso", pauseText:"Ve con calma y vuelve a planificar este día.", menu:"Menú", skill:"Practicaste planificación, asociación y decisiones rápidas.", speed:"Estaciones rápidas", capacity:"Bandeja extra", comfort:"Café acogedor", smoothie:"Batido", sandwich:"Sándwich", fruit:"Bol de fruta", cookie:"Dulce de panadería", buy:"Mejorar {cost}", max:"Máximo", servedMessage:"¡Servicio perfecto!", wrong:"Ese pedido pertenece a otro cliente.", noTray:"Prepara primero el pedido de la imagen.", locked:"Se desbloquea después del día {day}" };
  flowCopy.es = { pickFood:"Elige las fichas de comida del pedido.", deliver:"Toca al cliente cuyo pedido coincide con la comida elegida.", selected:"Comida elegida", queue:"Hay más clientes entrando en la fila.", priority:"VIP", rating:"Valoración del café", leaving:"Un cliente se fue descontento.", basics:"Asocia las comidas de las imágenes", sequence:"Cocina en orden: 1, 2 y 3", vip:"Atiende primero al VIP que espera", table:"Atiende la mesa A y después la B", variety:"Atiende ahora a un animal diferente", festival:"Festival: combina las reglas visibles", checkpoint:"Revisión del café", sequenceWrong:"Sigue el orden numérico de la receta.", vipWrong:"Hay un VIP esperando. Atiéndelo primero.", tableWrong:"Ahora atiende la mesa {table}.", varietyWrong:"Elige ahora un animal diferente.", tableTag:"Mesa {table}" };
  copy.ja = { title:"どうぶつカフェラッシュ", language:"言語", internal:"カフェ営業中", menuTitle:"動物たちのカフェを開こう。", menuHint:"注文に描かれた料理を選び、そのお客さんをタップして届けよう。", day:"営業日", coins:"コイン", best:"ベスト", upgrades:"カフェのアップグレード", upgradeHint:"コインで次の営業日をもっと遊びやすくできます。", start:"営業を始める", served:"お届け", select:"お客さんを選ぶ", tray:"できあがりトレー", empty:"注文と同じ料理を選ぼう", serve:"選んだお客さんに届ける", complete:"本日の営業完了！", next:"次の営業日", retry:"もう一度", pause:"ひと休みしよう", pauseText:"あせらずに、もう一度注文の順番を考えてみよう。", menu:"メニュー", skill:"計画する力、見分ける力、すばやく決める力を練習しました。", speed:"すばやい調理台", capacity:"大きなトレー", comfort:"くつろぎカフェ", smoothie:"スムージー", sandwich:"サンドイッチ", fruit:"フルーツボウル", cookie:"ベーカリーのおやつ", buy:"アップグレード {cost}", max:"最大", servedMessage:"ぴったりの注文を届けました！", wrong:"その料理は別のお客さんの注文です。", noTray:"先に注文どおりの料理を用意しよう。", locked:"{day}日目をクリアすると開きます" };
  flowCopy.ja = { pickFood:"注文する料理タイルを選ぼう。", deliver:"選んだ料理と注文が同じお客さんをタップしよう。", selected:"選んだ料理", queue:"新しいお客さんが列に加わります。", priority:"VIP", rating:"お店の評価", leaving:"お客さんが残念そうに帰りました。", basics:"絵と同じ料理をそろえよう", sequence:"1、2、3の順番で料理しよう", vip:"待っているVIPを先におもてなししよう", table:"テーブルA、テーブルBの順に届けよう", variety:"次は別の動物に届けよう", festival:"フェスティバル：画面のルールを組み合わせよう", checkpoint:"カフェレビュー", sequenceWrong:"レシピの数字どおりに料理を選ぼう。", vipWrong:"VIPが待っています。先におもてなししよう。", tableWrong:"次はテーブル{table}に届けよう。", varietyWrong:"次は別の動物のお客さんを選ぼう。", tableTag:"テーブル{table}" };
  Object.assign(copy.en, { startGame:"Start Game", chooseDay:"Choose a Day", startSelected:"Start Selected Day", goalLabel:"Serve {goal}", lockedDay:"Complete Day {day} first", backStage:"Back to Days" });
  Object.assign(copy["zh-Hant"], { startGame:"\u958b\u59cb\u904a\u6232", chooseDay:"\u9078\u64c7\u71df\u696d\u65e5", startSelected:"\u958b\u59cb\u9078\u5b9a\u95dc\u5361", goalLabel:"\u670d\u52d9 {goal} \u4f4d\u5ba2\u4eba", lockedDay:"\u5148\u5b8c\u6210\u7b2c {day} \u5929", backStage:"\u8fd4\u56de\u95dc\u5361" });
  Object.assign(copy.es, { startGame:"Empezar", chooseDay:"Elige un día", startSelected:"Empezar el día elegido", goalLabel:"Atiende a {goal}", lockedDay:"Completa primero el día {day}", backStage:"Volver a los días" });
  Object.assign(copy.ja, { startGame:"ゲームを始める", chooseDay:"営業日を選ぶ", startSelected:"この営業日を始める", goalLabel:"{goal}人に料理を届けよう", lockedDay:"{day}日目を先にクリアしよう", backStage:"営業日一覧へ" });
  Object.assign(copy.en, { leaveTitle:"Pause this cafe day?", leaveText:"Your orders will wait while you decide.", continueDay:"Continue serving", leaveDay:"Return to days" });
  Object.assign(copy["zh-Hant"], { leaveTitle:"\u8981\u66ab\u505c\u9019\u500b\u71df\u696d\u65e5\u55ce\uff1f", leaveText:"\u8a02\u55ae\u6703\u7559\u5728\u539f\u8655\uff0c\u60f3\u597d\u518d\u7e7c\u7e8c\u3002", continueDay:"\u7e7c\u7e8c\u670d\u52d9", leaveDay:"\u8fd4\u56de\u71df\u696d\u65e5" });
  Object.assign(copy.es, { leaveTitle:"\u00bfPausar este d\u00eda del caf\u00e9?", leaveText:"Los pedidos esperar\u00e1n mientras decides.", continueDay:"Seguir atendiendo", leaveDay:"Volver a los d\u00edas" });
  Object.assign(copy.ja, { leaveTitle:"この営業日を休憩しますか？", leaveText:"考えている間、注文とお客さんはそのまま待っています。", continueDay:"お店を続ける", leaveDay:"営業日一覧へ" });
  Object.assign(copy.en, { customerLion:"Lion customer", customerGiraffe:"Giraffe customer", customerPanda:"Panda customer", customerRabbit:"Rabbit customer", customerLabel:"{customer}. Order: {order}. {priority}Patience {patience}%." });
  Object.assign(copy["zh-Hant"], { customerLion:"\u7345\u5b50\u5ba2\u4eba", customerGiraffe:"\u9577\u9838\u9e7f\u5ba2\u4eba", customerPanda:"\u718a\u8c93\u5ba2\u4eba", customerRabbit:"\u5154\u5b50\u5ba2\u4eba", customerLabel:"{customer}\u3002\u9910\u9ede\uff1a{order}\u3002{priority}\u8010\u5fc3 {patience}%\u3002" });
  Object.assign(copy.es, { customerLion:"Cliente león", customerGiraffe:"Cliente jirafa", customerPanda:"Cliente panda", customerRabbit:"Cliente conejo", customerLabel:"{customer}. Pedido: {order}. {priority}Paciencia: {patience}%." });
  Object.assign(copy.ja, { customerLion:"ライオンのお客さん", customerGiraffe:"キリンのお客さん", customerPanda:"パンダのお客さん", customerRabbit:"ウサギのお客さん", customerLabel:"{customer}。注文：{order}。{priority}がまんメーター {patience}％。" });
  const dayTitles = [
    ["Welcome Morning","\u6b61\u8fce\u65e9\u6668"],["Smoothie Smiles","\u679c\u6614\u5fae\u7b11"],["Sandwich Noon","\u4e09\u660e\u6cbb\u4e2d\u5348"],["Fruit Break","\u6c34\u679c\u4f11\u606f"],["First Lunch Bell","\u7b2c\u4e00\u6b21\u5348\u9910\u9418"],
    ["Recipe Steps","\u6599\u7406\u6b65\u9a5f"],["Bakery Order","\u70d8\u7119\u9806\u5e8f"],["Two-Step Tray","\u5169\u6b65\u9a5f\u6258\u76e4"],["Three-Step Practice","\u4e09\u6b65\u9a5f\u7df4\u7fd2"],["Recipe Review","\u98df\u8b5c\u5be9\u67e5"],
    ["VIP Ribbon","VIP \u7dde\u5e36"],["Priority Lunch","\u512a\u5148\u5348\u9910"],["Star Guest","\u660e\u661f\u5ba2\u4eba"],["VIP Pair","VIP \u96d9\u4eba\u7d44"],["VIP Parade","VIP \u904a\u884c"],
    ["Table A Opens","A \u684c\u958b\u5e2d"],["Table B Answers","B \u684c\u63a5\u68d2"],["Twin Tables","\u96d9\u684c\u8f2a\u6d41"],["Dining Rhythm","\u9910\u684c\u7bc0\u594f"],["Table Review","\u9910\u684c\u5be9\u67e5"],
    ["New Friend Next","\u4e0b\u4e00\u4f4d\u65b0\u670b\u53cb"],["Animal Variety","\u52d5\u7269\u8f2a\u66ff"],["Four Friends","\u56db\u4f4d\u670b\u53cb"],["Changing Queue","\u8f2a\u66ff\u968a\u4f0d"],["Friendship Review","\u53cb\u8abc\u5be9\u67e5"],
    ["Festival Recipe","\u6176\u5178\u98df\u8b5c"],["Festival VIP","\u6176\u5178 VIP"],["Festival Tables","\u6176\u5178\u9910\u684c"],["Festival Friends","\u6176\u5178\u670b\u53cb"],["Grand Cafe Festival","\u5496\u5561\u9928\u5927\u6176\u5178"]
  ];
  const dayTitlesEs = [
    "Mañana de bienvenida","Sonrisas con batido","Mediodía de sándwich","Pausa de fruta","Primera campana del almuerzo",
    "Pasos de la receta","Pedido de panadería","Bandeja en dos pasos","Práctica en tres pasos","Revisión de recetas",
    "Cinta VIP","Almuerzo prioritario","Cliente estrella","Pareja VIP","Desfile VIP",
    "Abre la mesa A","Responde la mesa B","Mesas gemelas","Ritmo del comedor","Revisión de mesas",
    "Un nuevo amigo","Variedad animal","Cuatro amigos","Fila cambiante","Revisión de amistad",
    "Receta del festival","VIP del festival","Mesas del festival","Amigos del festival","Gran festival del café"
  ];
  const dayTitlesJa = [
    "はじめての朝","スムージーでにっこり","サンドイッチの昼","フルーツ休憩","最初のランチベル",
    "レシピの手順","ベーカリーの注文","2ステップトレー","3ステップ練習","レシピレビュー",
    "VIPリボン","優先ランチ","スターゲスト","VIPペア","VIPパレード",
    "テーブルA開店","テーブルBの番","2つのテーブル","テーブルのリズム","テーブルレビュー",
    "次は新しい友だち","いろいろな動物","4人の友だち","入れかわる列","友だちレビュー",
    "フェスティバルレシピ","フェスティバルVIP","フェスティバルテーブル","フェスティバルの友だち","グランドカフェフェスティバル"
  ];
  const chapterOrders = [
    [["smoothie"],["sandwich"],["fruit"],["cookie"],["smoothie","fruit"]],
    [["smoothie","cookie"],["sandwich","fruit"],["fruit","smoothie"],["cookie","sandwich","fruit"]],
    [["sandwich"],["smoothie","fruit"],["cookie"],["fruit","sandwich"]],
    [["fruit"],["cookie","smoothie"],["sandwich","fruit"],["smoothie","cookie"]],
    [["smoothie"],["sandwich","cookie"],["fruit","smoothie"],["cookie","fruit"]],
    [["sandwich","smoothie"],["fruit","cookie"],["smoothie","fruit","cookie"],["sandwich","cookie","fruit"]]
  ];
  const chapterRules = [[],["sequence"],["vip"],["table"],["variety"],["festival"]];
  const dayModes = Array.from({ length:CAMPAIGN_DAYS }, (_, index) => {
    const day=index+1; const chapter=Math.floor(index/5); const checkpoint=day%5===0;
    let rules=[...chapterRules[chapter]];
    if(chapter===5) rules=day===26?["sequence","vip"]:day===27?["sequence","table"]:day===28?["vip","table"]:day===29?["vip","variety"]:["sequence","vip","table","variety"];
    return { id:`day-${day}`, day, chapter, label:chapterRules[chapter][0]||"basics", titleEn:dayTitles[index][0], titleZh:dayTitles[index][1], titleEs:dayTitlesEs[index], titleJa:dayTitlesJa[index], checkpoint, rules, priorityEvery:chapter>=2?2:4, flatBonus:chapter, orders:chapterOrders[chapter] };
  });
  const requestedLocale = window.WonderI18n?.locale?.() || readStorage(localeKey) || "zh-Hant";
  let locale = copy[requestedLocale] ? requestedLocale : "en";
  dayModes.forEach((mode, index) => Object.defineProperty(mode, "titleEn", {
    configurable: true,
    get: () => locale === "es" ? dayTitlesEs[index] : locale === "ja" ? dayTitlesJa[index] : dayTitles[index][0],
  }));
  let profile = load(); let run = null; let selectedDay = Math.max(1, Math.min(CAMPAIGN_DAYS, profile.day || 1)); let runTimersSuspended = document.hidden || !document.hasFocus(); let leaveOpen = false; let centeredDayFrame = 0;
  function t(key, vars={}) { return Object.entries(vars).reduce((text,[name,value]) => text.replace(`{${name}}`, value), flowCopy[locale]?.[key] || copy[locale]?.[key] || copy.en[key] || key); }
  function wholeNumber(value, minimum, maximum, fallback) { const number=typeof value==="string"&&value.trim()?Number(value):value; return Number.isSafeInteger(number)?Math.min(maximum,Math.max(minimum,number)):fallback; }
  function normalizeProfile(raw) { const source=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:{}; const upgrades=source.upgrades&&typeof source.upgrades==="object"&&!Array.isArray(source.upgrades)?source.upgrades:{}; return { day:wholeNumber(source.day,1,CAMPAIGN_DAYS,1), coins:wholeNumber(source.coins,0,Number.MAX_SAFE_INTEGER,0), best:wholeNumber(source.best,0,8,0), upgrades:{ speed:wholeNumber(upgrades.speed,0,3,0), capacity:wholeNumber(upgrades.capacity,0,3,0), comfort:wholeNumber(upgrades.comfort,0,3,0) } }; }
  function load() { let stored={}; try { stored=JSON.parse(readStorage(saveKey)||"{}"); } catch { stored={}; } const normalized=normalizeProfile(stored); writeStorage(saveKey,JSON.stringify(normalized)); return normalized; }
  function save() { writeStorage(saveKey, JSON.stringify(profile)); }
  function applyLocale() {
    document.documentElement.lang = locale;
    document.title = `${(copy[locale] || copy.en).title} - WeightPlay`;
    document.querySelectorAll("[data-ui]").forEach((node) => node.textContent = t(node.dataset.ui));
    const releaseCopy = locale === "zh-Hant"
      ? { internal: "\u6b63\u5f0f\u71df\u696d", menuHint: "\u9ede\u9078\u5ba2\u4eba\u6c23\u6ce1\u88e1\u7684\u9910\u9ede\uff0c\u518d\u9ede\u8a72\u5ba2\u4eba\u5b8c\u6210\u51fa\u9910\u3002" }
      : locale === "es"
        ? { internal: "Café abierto", menuHint: "Elige la comida que aparece en el pedido y toca al cliente para servirla." }
        : locale === "ja"
          ? { internal: "カフェ営業中", menuHint: "注文に描かれた料理を選び、そのお客さんをタップして届けよう。" }
        : { internal: "Cafe open", menuHint: "Pick the food shown in a customer's bubble, then tap that customer to serve." };
    document.querySelector('[data-ui="internal"]').textContent = releaseCopy.internal;
    document.querySelector('[data-ui="menuHint"]').textContent = releaseCopy.menuHint;
    renderMenu();
    if (run) renderPlay();
  }
  function dayGoal(day) { return Math.min(8, 3 + Math.floor((day-1)/5) + (day%5===0?1:0)); }
  function dayMode(day) { return dayModes[Math.max(0,Math.min(CAMPAIGN_DAYS-1,Number(day)-1))] || dayModes[0]; }
  function makeOrder(index) { const patterns=run.mode.orders || [["smoothie","smoothie","cookie"],["sandwich"],["fruit","cookie"],["smoothie","fruit"],["cookie","cookie"],["sandwich","smoothie","fruit"]]; return [...patterns[(run.day + index) % patterns.length]]; }
  function orderBonus(order) { return (run.mode.flatBonus || 0) + (run.mode.cookieBonus && order.includes("cookie") ? run.mode.cookieBonus : 0); }
  function orderName(order) { const counts=new Map(); order.forEach((item)=>counts.set(item,(counts.get(item)||0)+1)); return [...counts].map(([item,count])=>`${t(item)}${count>1?` \u00d7${count}`:""}`).join(locale==="zh-Hant"||locale==="ja"?"\u3001":", "); }
  function customerName(id) { return t(`customer${id[0].toUpperCase()}${id.slice(1)}`); }
  function customerLabel(customer) { return t("customerLabel", { customer:customerName(customer.id), order:orderName(customer.order), priority:customer.priority?`${t("priority")}${locale==="ja"?"。 ":". "}`:"", patience:Math.round(customer.patience) }); }
  function stopRunTimers() { if(!run) return; cancelAnimationFrame(run.timerFrame); run.timerFrame=0; run.lastTimerFrame=null; }
  function scheduleRunTask(activeRun, task, delay) { if(run!==activeRun || activeRun.finishing) return; activeRun.tasks.push({ task, remaining:delay }); startRunTimers(activeRun); }
  function startRunTimers(activeRun=run) { if(!activeRun || run!==activeRun || activeRun.finishing || runTimersSuspended || document.hidden || activeRun.timerFrame) return; const tick=(now)=>{ if(run!==activeRun || activeRun.finishing){ activeRun.timerFrame=0; return; } if(runTimersSuspended || document.hidden){ activeRun.lastTimerFrame=null; activeRun.timerFrame=requestAnimationFrame(tick); return; } if(activeRun.lastTimerFrame!==null){ const elapsed=Math.max(0,now-activeRun.lastTimerFrame); activeRun.patienceRemaining-=elapsed; activeRun.queueRemaining-=elapsed; activeRun.tasks.forEach((pending)=>pending.remaining-=elapsed); const due=activeRun.tasks.filter((pending)=>pending.remaining<=0); activeRun.tasks=activeRun.tasks.filter((pending)=>pending.remaining>0); for(const pending of due){ if(run!==activeRun || activeRun.finishing) break; pending.task(); } } if(run!==activeRun || activeRun.finishing){ activeRun.timerFrame=0; return; } activeRun.lastTimerFrame=now; if(activeRun.patienceRemaining<=0){ activeRun.patienceRemaining+=1400; if(!tickPatience()){ renderQueue(); updateHud(); } } if(activeRun.queueRemaining<=0){ activeRun.queueRemaining+=2200; if(spawnCustomer()) renderQueue(); } activeRun.timerFrame=requestAnimationFrame(tick); }; activeRun.lastTimerFrame=null; activeRun.timerFrame=requestAnimationFrame(tick); }
  function suspendRunTimers() { runTimersSuspended=true; stopRunTimers(); }
  function resumeRunTimers() { runTimersSuspended=document.hidden || !document.hasFocus(); if(!runTimersSuspended && document.body.classList.contains("is-cafe-playing")) startRunTimers(run); }
  function setBattleCovered(covered) { [...nodes.play.children].forEach((child)=>{ if(child===nodes.result||child===nodes.leave) return; child.inert=covered; child.setAttribute("aria-hidden",covered?"true":"false"); }); }
  function setResultPrimary(primary) { [nodes.retry,nodes.next,nodes.menuBtn].forEach((action)=>{ action.classList.toggle("primary-btn",action===primary); action.classList.toggle("secondary-btn",action!==primary); }); primary.focus({preventScroll:true}); }
  function resetLeaveDecision() { leaveOpen=false; nodes.leave.classList.add("is-hidden"); setBattleCovered(false); }
  function openLeaveDecision() { if(leaveOpen||!run||run.finishing||!document.body.classList.contains("is-cafe-playing")) return; leaveOpen=true; suspendRunTimers(); setBattleCovered(true); nodes.leave.classList.remove("is-hidden"); requestAnimationFrame(()=>nodes.continueDay.focus({preventScroll:true})); }
  function closeLeaveDecision(restoreFocus=true) { if(!leaveOpen) return; leaveOpen=false; nodes.leave.classList.add("is-hidden"); setBattleCovered(false); resumeRunTimers(); if(restoreFocus) requestAnimationFrame(()=>nodes.back.focus({preventScroll:true})); }
  function leaveCafeDay() { const activeDay=run?.day||selectedDay; resetLeaveDecision(); showStage(activeDay); updateCafeBattleScale(); }
  function keepResultFocus(event) { if(event.key!=="Tab" || nodes.result.classList.contains("is-hidden")) return; const actions=[...nodes.result.querySelectorAll("button:not(:disabled), a[href]")].filter((action)=>!action.classList.contains("is-hidden")&&action.getClientRects().length); if(!actions.length) return; event.preventDefault(); const current=actions.indexOf(document.activeElement); const next=event.shiftKey?(current<=0?actions.length-1:current-1):(current<0||current===actions.length-1?0:current+1); actions[next].focus({preventScroll:true}); }
  function keepLeaveFocus(event) { if(nodes.leave.classList.contains("is-hidden")) return; if(event.repeat&&(event.key==="Enter"||event.key===" ")){ event.preventDefault(); event.stopImmediatePropagation(); return; } if(event.key==="Escape"){ event.preventDefault(); closeLeaveDecision(true); return; } if(event.key!=="Tab") return; event.preventDefault(); const actions=[nodes.continueDay,nodes.leaveDay]; const current=actions.indexOf(document.activeElement); const next=event.shiftKey?(current<=0?actions.length-1:current-1):(current<0||current===actions.length-1?0:current+1); actions[next].focus({preventScroll:true}); }
  function activeRules() { return run?.mode?.rules || []; }
  function usesRule(id) { return activeRules().includes(id); }
  function ruleSummary(mode=run?.mode) { const rules=mode?.rules || []; return rules.length ? rules.map((rule)=>t(rule)).join(" + ") : t("basics"); }
  function spawnCustomer() { if(!run || run.queue.length>=10) return false; const index=run.spawned; run.queue.push({ uid:`${Date.now()}-${index}`, id:customers[index % customers.length], order:makeOrder(index), patience:100, leaving:false, priority:index>0&&index%run.mode.priorityEvery===0, table:index%2===0?"A":"B" }); run.spawned+=1; return true; }
  function makeFoodDeck() { return Array.from({length:32}, (_,index)=>food[(index + run.day) % food.length]); }
  function syncSharedScene(scene) { if(scene==="battle"){ window.dispatchEvent(new Event("weightplay:stage-sync")); window.dispatchEvent(new Event("weightplay:battle-sync")); } else { window.dispatchEvent(new Event("weightplay:battle-sync")); window.dispatchEvent(new Event("weightplay:stage-sync")); } window.dispatchEvent(new Event("weightplay:shell-sync")); }
  function startDay(day=selectedDay) { stopRunTimers(); const activeDay=Math.max(1,Math.min(profile.day,Number(day)||1)); run = { day:activeDay, mode:dayMode(activeDay), served:0, coins:0, rating:100, selectedFoods:[], goal:dayGoal(activeDay), spawned:0, queue:[], foodDeck:[], foodBoard:[], timerFrame:0, lastTimerFrame:null, patienceRemaining:1400, queueRemaining:2200, tasks:[], finishing:false, tableTurn:"A", lastServedAnimal:"" }; run.foodDeck=makeFoodDeck(); run.foodBoard=run.foodDeck.splice(0,8); spawnCustomer(); spawnCustomer(); spawnCustomer(); document.body.classList.add("is-cafe-playing"); document.body.classList.remove("is-cafe-stage"); nodes.menu.classList.add("is-hidden"); nodes.stage.classList.add("is-hidden"); nodes.play.classList.remove("is-hidden"); nodes.result.classList.add("is-hidden"); setBattleCovered(false); syncSharedScene("battle"); updateCafeBattleScale(); nodes.message.textContent=t(run.mode.label); runTimersSuspended=document.hidden || !document.hasFocus(); startRunTimers(run); renderPlay(); requestAnimationFrame(()=>nodes.stations.querySelector(".food-tile")?.focus({preventScroll:true})); window.WonderAnalytics?.track?.("cafe_start_day", { day:run.day, mode:run.mode.id, rules:run.mode.rules.join(",") }); }
  function renderMenu() { nodes.locale.value = locale; nodes.day.textContent = profile.day; nodes.coins.textContent = profile.coins; nodes.best.textContent = profile.best; renderStage(); }
  function updateCenteredDayCard() { centeredDayFrame=0; const cards=[...nodes.dayRail.querySelectorAll(".day-card")]; if(!cards.length||!document.body.classList.contains("is-cafe-stage")) return; const railRect=nodes.dayRail.getBoundingClientRect(); const center=railRect.left+railRect.width/2; const nearest=cards.reduce((best,card)=>{ const rect=card.getBoundingClientRect(); const distance=Math.abs(rect.left+rect.width/2-center); return !best||distance<best.distance?{card,distance}:best; },null)?.card; cards.forEach((card)=>{ const centered=card===nearest; card.classList.toggle("is-centered",centered); if(centered) card.setAttribute("aria-current","true"); else card.removeAttribute("aria-current"); }); }
  function scheduleCenteredDayCard() { if(centeredDayFrame) cancelAnimationFrame(centeredDayFrame); centeredDayFrame=requestAnimationFrame(updateCenteredDayCard); }
  function renderStage(focusDay=null) { nodes.stageDay.textContent=selectedDay; nodes.stageCoins.textContent=profile.coins; nodes.stageBest.textContent=profile.best; nodes.dayRail.innerHTML=Array.from({length:CAMPAIGN_DAYS},(_,index)=>{ const day=index+1; const mode=dayMode(day); const locked=day>profile.day; const title=locale==="zh-Hant"?mode.titleZh:mode.titleEn; const dayLabel=locale==="ja"?`${day}日目`:`${t("day")} ${day}`; return `<button class="day-card stage-card ${day===selectedDay?"is-selected":""} ${locked?"is-locked":""} ${mode.checkpoint?"is-checkpoint":""}" data-day="${day}" type="button" ${locked?"disabled":""}><span>${dayLabel}${mode.checkpoint?` · ${t("checkpoint")}`:""}</span><strong>${title}</strong><small>${locked?t("lockedDay",{day:day-1}):t("goalLabel",{goal:dayGoal(day)})}</small><em>${ruleSummary(mode)}</em></button>`; }).join(""); nodes.dayRail.querySelectorAll(".day-card:not(.is-locked)").forEach((button)=>button.addEventListener("click",()=>{ selectedDay=Number(button.dataset.day); startDay(selectedDay); })); nodes.upgrades.innerHTML = ""; ["speed","capacity","comfort"].forEach((id) => { const level=profile.upgrades[id]; const cost=8 + level*7; const button=document.createElement("button"); button.className="upgrade-card"; button.disabled=level>=3 || profile.coins<cost; button.innerHTML=`<i class="upgrade-icon upgrade-${id}" aria-hidden="true"></i><span class="upgrade-copy"><b>${t(id)} Lv.${level}</b><span>${level>=3?t("max"):t("buy",{cost})}</span></span>`; button.addEventListener("click",()=>{ if(profile.coins>=cost && level<3){ profile.coins-=cost; profile.upgrades[id]+=1; save(); renderMenu(); window.WonderAnalytics?.track?.("cafe_upgrade",{upgrade:id,level:profile.upgrades[id]}); } }); nodes.upgrades.append(button); }); requestAnimationFrame(()=>{ const selected=nodes.dayRail.querySelector(".is-selected"); selected?.scrollIntoView({inline:"center",block:"nearest"}); scheduleCenteredDayCard(); requestAnimationFrame(scheduleCenteredDayCard); if(Number.isInteger(focusDay)) (nodes.dayRail.querySelector(`.day-card:not(.is-locked)[data-day="${focusDay}"]`)||selected)?.focus({preventScroll:true}); }); }
  function installDayRailSelection() { nodes.dayRail.addEventListener("scroll",scheduleCenteredDayCard,{passive:true}); nodes.dayRail.addEventListener("wonder:stage-snap",()=>{ const railRect=nodes.dayRail.getBoundingClientRect(); const center=railRect.left+railRect.width/2; const nearest=[...nodes.dayRail.querySelectorAll(".day-card")].reduce((best,card)=>{ const rect=card.getBoundingClientRect(); const distance=Math.abs(rect.left+rect.width/2-center); return !best||distance<best.distance?{card,distance}:best; },null)?.card; if(!nearest) return; nodes.dayRail.querySelectorAll(".day-card").forEach((card)=>card.classList.toggle("is-selected",card===nearest)); if(!nearest.classList.contains("is-locked")) selectedDay=Number(nearest.dataset.day); scheduleCenteredDayCard(); }); window.addEventListener("resize",scheduleCenteredDayCard,{passive:true}); window.visualViewport?.addEventListener("resize",scheduleCenteredDayCard,{passive:true}); }
  function showMain() { stopRunTimers(); run=null; document.body.classList.remove("is-cafe-playing","is-cafe-stage"); nodes.play.classList.add("is-hidden"); nodes.stage.classList.add("is-hidden"); nodes.result.classList.add("is-hidden"); nodes.menu.classList.remove("is-hidden"); syncSharedScene("main"); renderMenu(); requestAnimationFrame(()=>requestAnimationFrame(()=>nodes.mainStart.focus({preventScroll:true}))); }
  function showStage(focusDay=selectedDay) { stopRunTimers(); run=null; selectedDay=Math.min(selectedDay,profile.day); document.body.classList.remove("is-cafe-playing"); document.body.classList.add("is-cafe-stage"); nodes.menu.classList.add("is-hidden"); nodes.play.classList.add("is-hidden"); nodes.result.classList.add("is-hidden"); nodes.stage.classList.remove("is-hidden"); syncSharedScene("stage"); renderStage(focusDay); }
  function sameOrder(left, right) { return [...left].sort().join("|")===[...right].sort().join("|"); }
  function orderMatches(order, selected) { return usesRule("sequence") ? order.join("|")===selected.join("|") : sameOrder(order,selected); }
  function orderMarkup(order) { if(usesRule("sequence")) return order.map((item,index)=>`<span class="order-item is-sequence"><b class="recipe-step">${index+1}</b><span class="food-icon food-${item}"></span></span>`).join(""); const counts=new Map(); order.forEach((item)=>counts.set(item,(counts.get(item)||0)+1)); return [...counts].map(([item,count])=>`<span class="order-item"><span class="food-icon food-${item}"></span>${count>1?`<b class="order-count">\u00d7${count}</b>`:""}</span>`).join(""); }
  function updateHud() { if(!run) return; nodes.playDay.textContent=run.day; nodes.playCoins.textContent=`${run.rating}%`; nodes.playCoins.parentElement.querySelector("span").textContent=t("rating"); nodes.served.textContent=`${Math.min(run.served,run.goal)}/${run.goal}`; const instruction=run.selectedFoods.length?t("deliver"):t("pickFood"); nodes.objective.innerHTML=`<span class="step-number">${run.selectedFoods.length?2:1}</span><span class="objective-copy">${instruction}</span><span class="day-rule">${ruleSummary()}</span>`; }
  function renderQueue() { if(!run) return; const live=new Set(run.queue.map((customer)=>customer.uid)); [...nodes.customers.children].forEach((node)=>{ if(!live.has(node.dataset.customerId)) node.remove(); }); run.queue.forEach((customer)=>{ let card=nodes.customers.querySelector(`[data-customer-id="${customer.uid}"]`); if(!card){ card=document.createElement("button"); card.className="customer queue-customer"; card.dataset.customerId=customer.uid; card.innerHTML=`<span class="order-cloud" aria-hidden="true"></span><img src="../../assets/animal-cafe-rush-customer-${customer.id}.webp" alt=""><div class="patience" aria-hidden="true"><i></i></div><small aria-hidden="true"></small>`; card.addEventListener("click",()=>serve(customer.uid)); nodes.customers.append(card); } const orderReady=run.selectedFoods.length>0&&orderMatches(customer.order,run.selectedFoods); card.classList.toggle("is-selected", orderReady); card.classList.toggle("is-priority", customer.priority); card.classList.toggle("is-next-table", usesRule("table")&&customer.table===run.tableTurn); card.classList.toggle("is-leaving", customer.leaving); card.setAttribute("aria-label",`${customerLabel(customer)} ${usesRule("table")?t("tableTag",{table:customer.table}):""}`.trim()); card.querySelector(".order-cloud").innerHTML=orderMarkup(customer.order); card.querySelector(".patience i").style.width=`${customer.patience}%`; card.querySelector("small").textContent=[customer.priority?t("priority"):"",usesRule("table")?t("tableTag",{table:customer.table}):""].filter(Boolean).join(" · ")||t("queue"); }); }
  function renderFoodBoard(focusIndex=null) { if(!run) return; const previousFocus=nodes.stations.contains(document.activeElement)?[...nodes.stations.children].indexOf(document.activeElement):-1; const nextFocus=Number.isInteger(focusIndex)?focusIndex:previousFocus; nodes.stations.innerHTML=""; run.foodBoard.forEach((item,index)=>{ const tile=document.createElement("button"); tile.className=`station food-tile ${index===run.newTileIndex?"is-new":""}`; tile.innerHTML=`<span class="food-icon food-${item}" aria-hidden="true"></span>`; tile.setAttribute("aria-label",t(item)); tile.addEventListener("keydown",(event)=>{ if(event.repeat&&(event.key==="Enter"||event.key===" ")) event.preventDefault(); }); tile.addEventListener("click",()=>selectFood(index)); nodes.stations.append(tile); }); run.newTileIndex=-1; if(nextFocus>=0) requestAnimationFrame(()=>nodes.stations.children[Math.min(nextFocus,nodes.stations.children.length-1)]?.focus({preventScroll:true})); }
  function renderTray() { nodes.tray.classList.toggle("is-ready", Boolean(run?.selectedFoods.length)); nodes.tray.innerHTML=run?.selectedFoods.length?`<div>${run.selectedFoods.map((item)=>`<span class="food-icon food-${item}"></span>`).join("")}</div><b>${t("selected")}</b>`:`<b>${t("pickFood")}</b>`; nodes.tray.onclick=()=>{ if(run?.selectedFoods.length){ run.selectedFoods=[]; renderPlay(); } }; }
  function renderPlay() { if(!run) return; updateHud(); renderQueue(); renderFoodBoard(); renderTray(); }
  function selectFood(index) { if(!run) return; const item=run.foodBoard[index]; if(!item) return; run.selectedFoods.push(item); run.foodBoard.splice(index,1); if(!run.foodDeck.length) run.foodDeck=makeFoodDeck(); run.foodBoard.push(run.foodDeck.shift()); run.newTileIndex=run.foodBoard.length-1; nodes.message.textContent=t("deliver"); window.WonderSound?.play("click"); updateHud(); renderFoodBoard(index); renderTray(); }
  function serviceBlock(customer) { const live=run.queue.filter((item)=>!item.leaving); const tableEligible=usesRule("table")?live.filter((item)=>item.table===run.tableTurn):live; if(usesRule("table")&&customer.table!==run.tableTurn) return t("tableWrong",{table:run.tableTurn}); if(usesRule("vip")&&tableEligible.some((item)=>item.priority)&&!customer.priority) return t("vipWrong"); if(usesRule("variety")&&run.lastServedAnimal===customer.id&&tableEligible.some((item)=>item.id!==run.lastServedAnimal)) return t("varietyWrong"); return ""; }
  function serve(uid) { if(!run || run.finishing) return; const activeRun=run; const customer=run.queue.find((item)=>item.uid===uid); if(!customer || customer.leaving) return; if(!run.selectedFoods.length){ nodes.message.textContent=t("pickFood"); return; } const blocked=serviceBlock(customer); if(blocked){ nodes.message.textContent=blocked; window.WonderSound?.play("wrong"); return; } if(!orderMatches(customer.order,run.selectedFoods)){ const sequenceOnly=usesRule("sequence")&&sameOrder(customer.order,run.selectedFoods); customer.patience=Math.max(0,customer.patience-18); run.selectedFoods=[]; nodes.message.textContent=sequenceOnly?t("sequenceWrong"):t("wrong"); window.WonderSound?.play("wrong"); renderPlay(); return; } customer.leaving=true; run.selectedFoods=[]; run.lastServedAnimal=customer.id; if(usesRule("table")) run.tableTurn=run.tableTurn==="A"?"B":"A"; nodes.message.textContent=t("servedMessage"); window.WonderSound?.play("success"); renderQueue(); renderTray(); scheduleRunTask(activeRun,()=>{ if(run!==activeRun || run.finishing) return; run.queue=run.queue.filter((item)=>item.uid!==uid); run.served=Math.min(run.goal,run.served+1); const bonus=orderBonus(customer.order); run.coins+=3+profile.upgrades.comfort+(customer.priority?2:0)+bonus; window.WonderAnalytics?.track?.("cafe_order_served",{day:run.day,mode:run.mode.id,rules:run.mode.rules.join(","),bonus,priority:Boolean(customer.priority)}); if(run.served>=run.goal) { finishDay(); return; } spawnCustomer(); renderPlay(); requestAnimationFrame(()=>nodes.stations.querySelector(".food-tile")?.focus({preventScroll:true})); }, 450); }
  function tickPatience() { if(!run || run.finishing) return false; const activeRun=run; const waitLoss=Math.max(2,3-profile.upgrades.comfort-profile.upgrades.speed); const leaving=run.queue.filter((customer)=>!customer.leaving && (customer.patience=Math.max(0,customer.patience-waitLoss))<=0); if(!leaving.length) return false; leaving.forEach((customer)=>{ customer.leaving=true; run.rating=Math.max(0,run.rating-15); }); nodes.message.textContent=t("leaving"); renderQueue(); scheduleRunTask(activeRun,()=>{ if(run!==activeRun || run.finishing) return; const leavingIds=new Set(leaving.map((customer)=>customer.uid)); run.queue=run.queue.filter((customer)=>!leavingIds.has(customer.uid)); if(run.rating<=0) failDay(); else renderPlay(); }, 450); return false; }
  function prepareResult(replayDay, nextEnabled, primary) { nodes.retry.classList.remove("is-hidden"); nodes.next.classList.remove("is-hidden"); nodes.menuBtn.classList.remove("is-hidden"); nodes.retry.disabled=false; nodes.retry.removeAttribute("aria-disabled"); nodes.menuBtn.disabled=false; nodes.menuBtn.removeAttribute("aria-disabled"); nodes.next.disabled=!nextEnabled; nodes.next.setAttribute("aria-disabled",String(!nextEnabled)); nodes.retry.onclick=()=>startDay(replayDay); nodes.result.classList.remove("is-hidden"); setBattleCovered(true); setResultPrimary(primary); }
  function failDay() { if(!run || run.finishing) return; run.finishing=true; const retryDay=run.day; stopRunTimers(); nodes.resultTitle.textContent=t("pause"); nodes.resultText.textContent=t("pauseText"); nodes.skillText.textContent=t("skill"); prepareResult(retryDay,false,nodes.retry); window.WonderAnalytics?.track?.("cafe_day_retry",{day:retryDay}); }
  function finishDay() { if(!run || run.finishing) return; run.finishing=true; stopRunTimers(); const completedDay=run.day; profile.coins+=run.coins; profile.best=Math.max(profile.best,run.goal); profile.day=Math.min(CAMPAIGN_DAYS,Math.max(profile.day,completedDay+1)); selectedDay=profile.day; save(); updateHud(); nodes.resultTitle.textContent=t("complete"); nodes.resultText.textContent=`${run.goal}/${run.goal} · +${run.coins} ${t("coins")}`; nodes.skillText.textContent=t("skill"); const nextEnabled=completedDay<CAMPAIGN_DAYS; prepareResult(completedDay,nextEnabled,nextEnabled?nodes.next:nodes.menuBtn); window.WonderAnalytics?.track?.("cafe_day_result",{day:completedDay,served:run.goal,coins:run.coins}); }
  function updateCafeBattleScale() { const isStage=document.body.classList.contains("is-cafe-stage"); const isPlaying=document.body.classList.contains("is-cafe-playing"); const active=isPlaying||isStage; if(!active) return; const viewport=window.visualViewport; const visualWidth=Math.round(viewport?.width||0); const visualHeight=Math.round(viewport?.height||0); const useVisual=visualWidth>0&&visualHeight>0&&Math.abs(visualWidth-innerWidth)<=2&&visualHeight<=innerHeight+2; const safeWidth=useVisual?visualWidth:innerWidth; const height=useVisual?visualHeight:innerHeight; const width=Math.min(Math.max(1,safeWidth),920); const shortCanvas=height<=430&&width>height&&(isStage||isPlaying); const minimumWidth=shortCanvas?760:390; const minimumHeight=shortCanvas?360:788; const scale=Math.min(width/minimumWidth,Math.max(1,height)/minimumHeight); const logicalWidth=width/scale; const logicalHeight=height/scale; const root=document.documentElement.style; root.setProperty("--cafe-vw",`${width}px`); root.setProperty("--cafe-vh",`${height}px`); root.setProperty("--cafe-canvas-scale",String(scale)); root.setProperty("--cafe-logical-width",`${logicalWidth}px`); root.setProperty("--cafe-logical-height",`${logicalHeight}px`); root.setProperty("--cafe-canvas-left",`${Math.max(0,(safeWidth-width)/2)}px`); root.setProperty("--cafe-canvas-top","0px"); }
  window.addEventListener("blur",suspendRunTimers); window.addEventListener("focus",resumeRunTimers); window.addEventListener("pagehide",suspendRunTimers); window.addEventListener("pageshow",resumeRunTimers); document.addEventListener("visibilitychange",()=>{ if(document.hidden) suspendRunTimers(); else resumeRunTimers(); });
  window.addEventListener?.("resize",updateCafeBattleScale,{passive:true}); window.addEventListener?.("orientationchange",updateCafeBattleScale,{passive:true}); window.visualViewport?.addEventListener("resize",updateCafeBattleScale,{passive:true});
  if(new URLSearchParams(location.search).has("test")) window.__AnimalCafeRushTest={ definitions(){ return dayModes.map((mode)=>({day:mode.day,titleEn:mode.titleEn,titleZh:mode.titleZh,checkpoint:mode.checkpoint,rules:[...mode.rules],goal:dayGoal(mode.day),orders:mode.orders.map((order)=>[...order])})); }, prepareDay(day){ profile.day=CAMPAIGN_DAYS; selectedDay=Math.max(1,Math.min(CAMPAIGN_DAYS,Number(day)||1)); startDay(selectedDay); return this.snapshot(); }, setSelectedFoods(items=[]){ if(!run) return null; run.selectedFoods=[...items]; renderPlay(); return this.snapshot(); }, setLastServedAnimal(id=""){ if(!run) return null; run.lastServedAnimal=id; renderPlay(); return this.snapshot(); }, serveIndex(index=0){ const customer=run?.queue[index]; if(customer) serve(customer.uid); return { message:nodes.message.textContent, ...this.snapshot() }; }, ruleDecision(index=0){ const customer=run?.queue[index]; return customer?{customer:{id:customer.id,priority:customer.priority,table:customer.table,order:[...customer.order]},block:serviceBlock(customer),rules:[...activeRules()],tableTurn:run.tableTurn,lastServedAnimal:run.lastServedAnimal}:null; }, forceComplete(){ if(!run) return null; run.served=run.goal; run.coins=run.goal*3; finishDay(); return { served:run.served, goal:run.goal, finishing:run.finishing, resultVisible:!nodes.result.classList.contains("is-hidden"), profile:JSON.parse(readStorage(saveKey)||"{}") }; }, snapshot(){ return { selectedDay, run:run?{ day:run.day, mode:run.mode.id, modeLabel:t(run.mode.label), ruleSummary:ruleSummary(), rules:[...run.mode.rules], checkpoint:run.mode.checkpoint, served:run.served, goal:run.goal, finishing:run.finishing, tableTurn:run.tableTurn, lastServedAnimal:run.lastServedAnimal, queue:run.queue.map((customer)=>({id:customer.id,priority:customer.priority,table:customer.table,order:[...customer.order],leaving:customer.leaving})), firstOrder:[...(run.queue[0]?.order||[])], firstOrderBonus:run.queue[0]?orderBonus(run.queue[0].order):0 }:null, profile:JSON.parse(readStorage(saveKey)||"{}") }; } };
  nodes.locale.addEventListener("change",()=>{ const requested=nodes.locale.value; window.WonderI18n?.setLocale?.(requested); const resolved=window.WonderI18n?.locale?.()||requested; locale=copy[resolved]?resolved:"en"; writeStorage(localeKey,requested); applyLocale(); });
  nodes.mainStart.addEventListener("click",()=>{ showStage(selectedDay); updateCafeBattleScale(); });
  nodes.stageBack.addEventListener("click",showMain);
  nodes.start.addEventListener("click",()=>startDay(selectedDay));
  nodes.back.addEventListener("click",openLeaveDecision);
  nodes.continueDay.addEventListener("click",()=>closeLeaveDecision(true));
  nodes.leaveDay.addEventListener("click",leaveCafeDay);
  nodes.leave.addEventListener("keydown",keepLeaveFocus,true);
  nodes.result.addEventListener("keydown",keepResultFocus);
  nodes.menuBtn.addEventListener("click",()=>{ selectedDay=profile.day; showStage(profile.day); updateCafeBattleScale(); });
  nodes.next.addEventListener("click",()=>startDay(profile.day));
  installDayRailSelection();
  applyLocale();
})();
