(() => {
  const $ = (id) => document.getElementById(id);
  const saveKey = "weightplay_animal_cafe_rush_v1";
  const localeKey = "weightPlayLocale";
  const food = ["smoothie", "sandwich", "fruit", "cookie"];
  const customers = ["lion", "giraffe", "panda", "rabbit"];
  const stations = { smoothie: "station-smoothie", sandwich: "station-sandwich", fruit: "station-fruit", cookie: "station-bakery" };
  const nodes = { locale: $("localeSelect"), menu: $("menuPanel"), stage: $("stagePanel"), play: $("playPanel"), result: $("resultPanel"), mainStart: $("mainStartBtn"), start: $("startBtn"), stageBack: $("stageBackBtn"), back: $("backToMenuBtn"), day: $("dayText"), coins: $("coinText"), best: $("bestText"), stageDay: $("stageDayText"), stageCoins: $("stageCoinText"), stageBest: $("stageBestText"), dayRail: $("dayRail"), playDay: $("playDay"), playCoins: $("playCoins"), served: $("servedText"), objective: $("objectiveRow"), customers: $("customerRow"), stations: $("stationRow"), tray: $("tray"), message: $("playMessage"), upgrades: $("upgradeCards"), resultTitle: $("resultTitle"), resultText: $("resultText"), skillText: $("skillText"), retry: $("retryBtn"), next: $("nextBtn"), menuBtn: $("menuBtn") };
  const copy = { en: { title:"Animal Cafe Rush", language:"Language", internal:"Internal prototype", menuTitle:"Serve the animal cafe.", menuHint:"Tap a customer, prepare each pictured order, then tap the ready tray to serve.", day:"Day", coins:"Coins", best:"Best", upgrades:"Cafe upgrades", upgradeHint:"Coins make future days friendlier.", start:"Start day", served:"Served", select:"Choose a customer", tray:"Ready tray", empty:"Choose the matching station", serve:"Serve selected customer", complete:"Day complete", next:"Next day", retry:"Try again", pause:"Customers need a break", pauseText:"Take it slowly and plan this day again.", menu:"Menu", skill:"You practiced planning, matching, and quick decisions.", speed:"Quick stations", capacity:"Extra tray", comfort:"Cozy cafe", smoothie:"Smoothie", sandwich:"Sandwich", fruit:"Fruit bowl", cookie:"Bakery treat", buy:"Upgrade {cost}", max:"Max", servedMessage:"Perfect service!", wrong:"That order belongs to another customer.", noTray:"Prepare the pictured order first.", locked:"Unlocks after Day {day}" }, "zh-Hant": { title:"動物咖啡快手", language:"語言", internal:"內部原型", menuTitle:"經營動物咖啡館。", menuHint:"點選客人，準備圖示餐點，再點選托盤完成服務。", day:"天數", coins:"金幣", best:"最佳", upgrades:"咖啡館升級", upgradeHint:"金幣讓之後的咖啡日更順利。", start:"開始營業", served:"已服務", select:"選擇一位客人", tray:"完成托盤", empty:"選擇對應工作站", serve:"服務選定客人", complete:"今日完成", next:"下一天", retry:"再試一次", pause:"客人需要休息", pauseText:"慢慢來，重新安排這一天的訂單。", menu:"選單", skill:"你練習了規劃、配對與快速判斷。", speed:"快速工作站", capacity:"加大托盤", comfort:"舒適咖啡館", smoothie:"果昔", sandwich:"三明治", fruit:"水果碗", cookie:"烘焙點心", buy:"升級 {cost}", max:"已滿", servedMessage:"服務得很完美！", wrong:"這份餐點屬於另一位客人。", noTray:"先準備圖示中的餐點。", locked:"通過第 {day} 天後解鎖" } };
  const flowCopy = { en: { pickFood:"Pick the food tiles for an order.", deliver:"Tap the customer whose bubble matches your selected food.", selected:"Selected food", queue:"More customers are joining the line.", priority:"Priority guest +2", rating:"Business rating", leaving:"A customer left unhappy.", basics:"Cafe basics", bakery:"Bakery orders +1", vip:"VIP every 3 guests", fresh:"Fresh menu +1", duo:"Two-item orders +1", festival:"Festival orders +2" }, "zh-Hant": { pickFood:"\u9ede\u9078\u9910\u9ede\u65b9\u584a\u7d44\u51fa\u8a02\u55ae\u3002", deliver:"\u9ede\u9078\u982d\u4e0a\u8a02\u55ae\u8207\u5df2\u9078\u9910\u9ede\u76f8\u540c\u7684\u5ba2\u4eba\u3002", selected:"\u5df2\u9078\u9910\u9ede", queue:"\u66f4\u591a\u5ba2\u4eba\u6b63\u5728\u6392\u968a\u3002", priority:"\u512a\u5148\u5ba2\u4eba +2", rating:"\u751f\u610f\u8a55\u5206", leaving:"\u5ba2\u4eba\u4e0d\u9ad8\u8208\u5730\u96e2\u958b\u4e86\u3002", basics:"\u5496\u5561\u5165\u9580", bakery:"\u70d8\u7119\u8a02\u55ae +1", vip:"\u6bcf 3 \u4f4d\u6709\u8cb4\u8cd3", fresh:"\u9bae\u679c\u83dc\u55ae +1", duo:"\u96d9\u9910\u9ede +1", festival:"\u6176\u5178\u8a02\u55ae +2" } };
  Object.assign(copy.en, { startGame:"Start Game", chooseDay:"Choose a Day", startSelected:"Start Selected Day", goalLabel:"Serve {goal}", lockedDay:"Complete Day {day} first", backStage:"Back to Days" });
  Object.assign(copy["zh-Hant"], { startGame:"\u958b\u59cb\u904a\u6232", chooseDay:"\u9078\u64c7\u71df\u696d\u65e5", startSelected:"\u958b\u59cb\u9078\u5b9a\u95dc\u5361", goalLabel:"\u670d\u52d9 {goal} \u4f4d\u5ba2\u4eba", lockedDay:"\u5148\u5b8c\u6210\u7b2c {day} \u5929", backStage:"\u8fd4\u56de\u95dc\u5361" });
  const dayModes = [
    { id:"basics", from:1, to:2, label:"basics", priorityEvery:4 },
    { id:"bakery", from:3, to:4, label:"bakery", priorityEvery:4, cookieBonus:1 },
    { id:"vip", from:5, to:6, label:"vip", priorityEvery:3 },
    { id:"fresh", from:7, to:8, label:"fresh", priorityEvery:4, flatBonus:1, orders:[["smoothie"],["fruit"],["smoothie","fruit"],["fruit","fruit"]] },
    { id:"duo", from:9, to:10, label:"duo", priorityEvery:4, flatBonus:1, orders:[["sandwich","smoothie"],["fruit","cookie"],["smoothie","fruit"],["cookie","cookie"]] },
    { id:"festival", from:11, to:12, label:"festival", priorityEvery:3, flatBonus:2, orders:[["sandwich","smoothie"],["fruit","cookie"],["smoothie","fruit","cookie"],["sandwich","smoothie","fruit"]] },
  ];
  let locale = localStorage.getItem(localeKey) || "zh-Hant";
  let profile = load(); let run = null; let selectedDay = Math.max(1, Math.min(12, profile.day || 1));
  function t(key, vars={}) { return Object.entries(vars).reduce((text,[name,value]) => text.replace(`{${name}}`, value), flowCopy[locale]?.[key] || copy[locale][key] || key); }
  function load() { try { return { day:1, coins:0, best:0, upgrades:{ speed:0, capacity:0, comfort:0 }, ...JSON.parse(localStorage.getItem(saveKey) || "{}") }; } catch { return { day:1, coins:0, best:0, upgrades:{ speed:0, capacity:0, comfort:0 } }; } }
  function save() { localStorage.setItem(saveKey, JSON.stringify(profile)); }
  function applyLocale() {
    document.documentElement.lang = locale;
    document.title = `${copy[locale].title} - WeightPlay`;
    document.querySelectorAll("[data-ui]").forEach((node) => node.textContent = t(node.dataset.ui));
    const releaseCopy = locale === "zh-Hant"
      ? { internal: "\u6b63\u5f0f\u71df\u696d", menuHint: "\u9ede\u9078\u5ba2\u4eba\u6c23\u6ce1\u88e1\u7684\u9910\u9ede\uff0c\u518d\u9ede\u8a72\u5ba2\u4eba\u5b8c\u6210\u51fa\u9910\u3002" }
      : { internal: "Cafe open", menuHint: "Pick the food shown in a customer's bubble, then tap that customer to serve." };
    document.querySelector('[data-ui="internal"]').textContent = releaseCopy.internal;
    document.querySelector('[data-ui="menuHint"]').textContent = releaseCopy.menuHint;
    renderMenu();
    if (run) renderPlay();
  }
  function dayGoal(day) { return Math.min(18, 10 + day); }
  function dayMode(day) { return dayModes.find((mode) => day >= mode.from && day <= mode.to) || dayModes[0]; }
  function makeOrder(index) { const patterns=run.mode.orders || [["smoothie","smoothie","cookie"],["sandwich"],["fruit","cookie"],["smoothie","fruit"],["cookie","cookie"],["sandwich","smoothie","fruit"]]; return [...patterns[(run.day + index) % patterns.length]]; }
  function orderBonus(order) { return (run.mode.flatBonus || 0) + (run.mode.cookieBonus && order.includes("cookie") ? run.mode.cookieBonus : 0); }
  function stopRunTimers() { if(!run) return; clearInterval(run.patienceTimer); clearInterval(run.queueTimer); run.patienceTimer=0; run.queueTimer=0; }
  function setBattleCovered(covered) { [...nodes.play.children].forEach((child)=>{ if(child===nodes.result) return; child.inert=covered; child.setAttribute("aria-hidden",covered?"true":"false"); }); }
  function spawnCustomer() { if(!run || run.queue.length>=10) return false; const index=run.spawned; run.queue.push({ uid:`${Date.now()}-${index}`, id:customers[index % customers.length], order:makeOrder(index), patience:100, leaving:false, priority:index>0&&index%run.mode.priorityEvery===0 }); run.spawned+=1; return true; }
  function makeFoodDeck() { return Array.from({length:30}, (_,index)=>food[(index * 3 + run.day + Math.floor(Math.random() * food.length)) % food.length]); }
  function startDay(day=selectedDay) { stopRunTimers(); const activeDay=Math.max(1,Math.min(profile.day,Number(day)||1)); run = { day:activeDay, mode:dayMode(activeDay), served:0, coins:0, rating:100, selectedFoods:[], goal:dayGoal(activeDay), spawned:0, queue:[], foodDeck:[], foodBoard:[], patienceTimer:0, queueTimer:0, finishing:false }; run.foodDeck=makeFoodDeck(); run.foodBoard=run.foodDeck.splice(0,8); spawnCustomer(); spawnCustomer(); document.body.classList.add("is-cafe-playing"); document.body.classList.remove("is-cafe-stage"); nodes.menu.classList.add("is-hidden"); nodes.stage.classList.add("is-hidden"); nodes.play.classList.remove("is-hidden"); nodes.result.classList.add("is-hidden"); setBattleCovered(false); updateCafeBattleScale(); nodes.message.textContent=t(run.mode.label); const activeRun=run; run.patienceTimer=window.setInterval(()=>{ if(run!==activeRun || run.finishing) return; if(tickPatience()) return; renderQueue(); updateHud(); }, 1400); run.queueTimer=window.setInterval(()=>{ if(run!==activeRun || run.finishing) return; if(spawnCustomer()) renderQueue(); }, 2200); renderPlay(); window.WonderAnalytics?.track?.("cafe_start_day", { day:run.day, mode:run.mode.id }); }
  function renderMenu() { nodes.locale.value = locale; nodes.day.textContent = profile.day; nodes.coins.textContent = profile.coins; nodes.best.textContent = profile.best; renderStage(); }
  function renderStage() { nodes.stageDay.textContent=selectedDay; nodes.stageCoins.textContent=profile.coins; nodes.stageBest.textContent=profile.best; nodes.dayRail.innerHTML=Array.from({length:12},(_,index)=>{ const day=index+1; const mode=dayMode(day); const locked=day>profile.day; return `<button class="day-card stage-card ${day===selectedDay?"is-selected":""} ${locked?"is-locked":""}" data-day="${day}" type="button" ${locked?"disabled":""}><span>${t("day")}</span><strong>${day}</strong><small>${locked?t("lockedDay",{day:day-1}):t("goalLabel",{goal:dayGoal(day)})}</small><em>${t(mode.label)}</em></button>`; }).join(""); nodes.dayRail.querySelectorAll(".day-card:not(.is-locked)").forEach((button)=>button.addEventListener("click",()=>{ selectedDay=Number(button.dataset.day); startDay(selectedDay); })); nodes.upgrades.innerHTML = ""; ["speed","capacity","comfort"].forEach((id) => { const level=profile.upgrades[id]; const cost=8 + level*7; const button=document.createElement("button"); button.className="upgrade-card"; button.disabled=level>=3 || profile.coins<cost; button.innerHTML=`<i class="upgrade-icon upgrade-${id}" aria-hidden="true"></i><span class="upgrade-copy"><b>${t(id)} Lv.${level}</b><span>${level>=3?t("max"):t("buy",{cost})}</span></span>`; button.addEventListener("click",()=>{ if(profile.coins>=cost && level<3){ profile.coins-=cost; profile.upgrades[id]+=1; save(); renderMenu(); window.WonderAnalytics?.track?.("cafe_upgrade",{upgrade:id,level:profile.upgrades[id]}); } }); nodes.upgrades.append(button); }); requestAnimationFrame(()=>nodes.dayRail.querySelector(".is-selected")?.scrollIntoView({inline:"center",block:"nearest"})); }
  function installDayRail() { let drag=null; nodes.dayRail.addEventListener("pointerdown",(event)=>{ if(event.button!==0 || nodes.dayRail.scrollWidth<=nodes.dayRail.clientWidth) return; drag={ id:event.pointerId, x:event.clientX, scroll:nodes.dayRail.scrollLeft, moved:false }; }); nodes.dayRail.addEventListener("pointermove",(event)=>{ if(!drag || drag.id!==event.pointerId) return; const delta=event.clientX-drag.x; if(!drag.moved && Math.abs(delta)<8) return; if(!drag.moved){ drag.moved=true; nodes.dayRail.setPointerCapture?.(event.pointerId); nodes.dayRail.dataset.dragging="1"; } nodes.dayRail.scrollLeft=drag.scroll-delta; event.preventDefault(); }); const end=(event)=>{ if(!drag || drag.id!==event.pointerId) return; const moved=drag.moved; if(moved) nodes.dayRail.releasePointerCapture?.(event.pointerId); drag=null; if(!moved) return; const railRect=nodes.dayRail.getBoundingClientRect(); const center=railRect.left+railRect.width/2; const nearest=[...nodes.dayRail.querySelectorAll(".day-card")].reduce((best,card)=>{ const rect=card.getBoundingClientRect(); const distance=Math.abs(rect.left+rect.width/2-center); return !best||distance<best.distance?{card,distance}:best; },null); if(nearest){ nodes.dayRail.querySelectorAll(".day-card").forEach((card)=>card.classList.toggle("is-selected",card===nearest.card)); if(!nearest.card.classList.contains("is-locked")) selectedDay=Number(nearest.card.dataset.day); nearest.card.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"}); } setTimeout(()=>delete nodes.dayRail.dataset.dragging,0); }; nodes.dayRail.addEventListener("pointerup",end); nodes.dayRail.addEventListener("pointercancel",end); nodes.dayRail.addEventListener("click",(event)=>{ if(nodes.dayRail.dataset.dragging==="1"){ event.preventDefault(); event.stopImmediatePropagation(); } },true); nodes.dayRail.addEventListener("dragstart",(event)=>event.preventDefault()); }
  function showMain() { stopRunTimers(); run=null; document.body.classList.remove("is-cafe-playing","is-cafe-stage"); nodes.play.classList.add("is-hidden"); nodes.stage.classList.add("is-hidden"); nodes.result.classList.add("is-hidden"); nodes.menu.classList.remove("is-hidden"); renderMenu(); }
  function showStage() { stopRunTimers(); run=null; selectedDay=Math.min(selectedDay,profile.day); document.body.classList.remove("is-cafe-playing"); document.body.classList.add("is-cafe-stage"); nodes.menu.classList.add("is-hidden"); nodes.play.classList.add("is-hidden"); nodes.result.classList.add("is-hidden"); nodes.stage.classList.remove("is-hidden"); renderStage(); }
  function sameOrder(left, right) { return [...left].sort().join("|")===[...right].sort().join("|"); }
  function orderMarkup(order) { const counts=new Map(); order.forEach((item)=>counts.set(item,(counts.get(item)||0)+1)); return [...counts].map(([item,count])=>`<span class="order-item"><span class="food-icon food-${item}"></span>${count>1?`<b class="order-count">\u00d7${count}</b>`:""}</span>`).join(""); }
  function updateHud() { if(!run) return; nodes.playDay.textContent=run.day; nodes.playCoins.textContent=`${run.rating}%`; nodes.playCoins.parentElement.querySelector("span").textContent=t("rating"); nodes.served.textContent=`${Math.min(run.served,run.goal)}/${run.goal}`; const instruction=run.selectedFoods.length?t("deliver"):t("pickFood"); nodes.objective.innerHTML=`<span class="step-number">${run.selectedFoods.length?2:1}</span><span class="objective-copy">${instruction}</span><span class="day-rule">${t(run.mode.label)}</span>`; }
  function renderQueue() { if(!run) return; const live=new Set(run.queue.map((customer)=>customer.uid)); [...nodes.customers.children].forEach((node)=>{ if(!live.has(node.dataset.customerId)) node.remove(); }); run.queue.forEach((customer)=>{ let card=nodes.customers.querySelector(`[data-customer-id="${customer.uid}"]`); if(!card){ card=document.createElement("button"); card.className="customer queue-customer"; card.dataset.customerId=customer.uid; card.innerHTML=`<span class="order-cloud"></span><img src="../../assets/animal-cafe-rush-customer-${customer.id}.webp" alt=""><div class="patience"><i></i></div><small></small>`; card.addEventListener("click",()=>serve(customer.uid)); nodes.customers.append(card); } const orderReady=run.selectedFoods.length>0&&sameOrder(customer.order,run.selectedFoods); card.classList.toggle("is-selected", orderReady); card.classList.toggle("is-priority", customer.priority); card.classList.toggle("is-leaving", customer.leaving); card.querySelector(".order-cloud").innerHTML=orderMarkup(customer.order); card.querySelector(".patience i").style.width=`${customer.patience}%`; card.querySelector("small").textContent=customer.priority?t("priority"):t("queue"); }); }
  function renderFoodBoard() { if(!run) return; nodes.stations.innerHTML=""; run.foodBoard.forEach((item,index)=>{ const tile=document.createElement("button"); tile.className=`station food-tile ${index===run.newTileIndex?"is-new":""}`; tile.innerHTML=`<span class="food-icon food-${item}"></span>`; tile.setAttribute("aria-label",t(item)); tile.addEventListener("click",()=>selectFood(index)); nodes.stations.append(tile); }); run.newTileIndex=-1; }
  function renderTray() { nodes.tray.classList.toggle("is-ready", Boolean(run?.selectedFoods.length)); nodes.tray.innerHTML=run?.selectedFoods.length?`<div>${run.selectedFoods.map((item)=>`<span class="food-icon food-${item}"></span>`).join("")}</div><b>${t("selected")}</b>`:`<b>${t("pickFood")}</b>`; nodes.tray.onclick=()=>{ if(run?.selectedFoods.length){ run.selectedFoods=[]; renderPlay(); } }; }
  function renderPlay() { if(!run) return; updateHud(); renderQueue(); renderFoodBoard(); renderTray(); }
  function selectFood(index) { if(!run) return; const item=run.foodBoard[index]; if(!item) return; run.selectedFoods.push(item); run.foodBoard.splice(index,1); if(!run.foodDeck.length) run.foodDeck=makeFoodDeck(); run.foodBoard.push(run.foodDeck.shift()); run.newTileIndex=run.foodBoard.length-1; nodes.message.textContent=t("deliver"); window.WonderSound?.play("click"); updateHud(); renderFoodBoard(); renderTray(); }
  function serve(uid) { if(!run || run.finishing) return; const activeRun=run; const customer=run.queue.find((item)=>item.uid===uid); if(!customer || customer.leaving) return; if(!run.selectedFoods.length){ nodes.message.textContent=t("pickFood"); return; } if(!sameOrder(customer.order,run.selectedFoods)){ customer.patience=Math.max(0,customer.patience-18); run.selectedFoods=[]; nodes.message.textContent=t("wrong"); window.WonderSound?.play("wrong"); renderPlay(); return; } customer.leaving=true; run.selectedFoods=[]; nodes.message.textContent=t("servedMessage"); window.WonderSound?.play("success"); renderQueue(); renderTray(); window.setTimeout(()=>{ if(run!==activeRun || run.finishing) return; run.queue=run.queue.filter((item)=>item.uid!==uid); run.served=Math.min(run.goal,run.served+1); const bonus=orderBonus(customer.order); run.coins+=3+profile.upgrades.comfort+(customer.priority?2:0)+bonus; window.WonderAnalytics?.track?.("cafe_order_served",{day:run.day,mode:run.mode.id,bonus,priority:Boolean(customer.priority)}); if(run.served>=run.goal) { finishDay(); return; } spawnCustomer(); renderPlay(); }, 450); }
  function tickPatience() { if(!run || run.finishing) return false; const activeRun=run; const waitLoss=Math.max(2,3-profile.upgrades.comfort-profile.upgrades.speed); const leaving=run.queue.filter((customer)=>!customer.leaving && (customer.patience=Math.max(0,customer.patience-waitLoss))<=0); if(!leaving.length) return false; leaving.forEach((customer)=>{ customer.leaving=true; run.rating=Math.max(0,run.rating-15); }); nodes.message.textContent=t("leaving"); renderQueue(); window.setTimeout(()=>{ if(run!==activeRun || run.finishing) return; const leavingIds=new Set(leaving.map((customer)=>customer.uid)); run.queue=run.queue.filter((customer)=>!leavingIds.has(customer.uid)); if(run.rating<=0) failDay(); else renderPlay(); }, 450); return false; }
  function failDay() { if(!run || run.finishing) return; run.finishing=true; const retryDay=run.day; stopRunTimers(); nodes.resultTitle.textContent=t("pause"); nodes.resultText.textContent=t("pauseText"); nodes.skillText.textContent=t("skill"); nodes.retry.classList.remove("is-hidden"); nodes.next.classList.add("is-hidden"); nodes.result.classList.remove("is-hidden"); setBattleCovered(true); nodes.retry.focus({preventScroll:true}); nodes.retry.onclick=()=>startDay(retryDay); window.WonderAnalytics?.track?.("cafe_day_retry",{day:retryDay}); }
  function finishDay() { if(!run || run.finishing) return; run.finishing=true; stopRunTimers(); const completedDay=run.day; profile.coins+=run.coins; profile.best=Math.max(profile.best,run.goal); profile.day=Math.min(12,Math.max(profile.day,completedDay+1)); selectedDay=profile.day; save(); updateHud(); nodes.resultTitle.textContent=t("complete"); nodes.resultText.textContent=`${run.goal}/${run.goal} · +${run.coins} ${t("coins")}`; nodes.skillText.textContent=t("skill"); nodes.retry.classList.add("is-hidden"); nodes.next.classList.toggle("is-hidden",completedDay>=12); nodes.next.disabled=completedDay>=12; nodes.result.classList.remove("is-hidden"); setBattleCovered(true); (completedDay<12?nodes.next:nodes.menuBtn).focus({preventScroll:true}); window.WonderAnalytics?.track?.("cafe_day_result",{day:completedDay,served:run.goal,coins:run.coins}); }
  function updateCafeBattleScale() { const active=document.body.classList.contains("is-cafe-playing")||document.body.classList.contains("is-cafe-stage"); if(!active) return; const viewport=window.visualViewport; const visualWidth=Math.round(viewport?.width||0); const visualHeight=Math.round(viewport?.height||0); const useVisual=visualWidth>0&&visualHeight>0&&Math.abs(visualWidth-innerWidth)<=2&&visualHeight<=innerHeight+2; const width=useVisual?visualWidth:innerWidth; const height=useVisual?visualHeight:innerHeight; const scale=Math.min(Math.max(1,width-8)/390,Math.max(1,height-8)/788); const root=document.documentElement.style; root.setProperty("--cafe-vw",`${width}px`); root.setProperty("--cafe-vh",`${height}px`); root.setProperty("--cafe-canvas-scale",String(scale)); root.setProperty("--cafe-canvas-left",`${(width-390*scale)/2}px`); root.setProperty("--cafe-canvas-top",`${height-788*scale-4}px`); }
  window.addEventListener?.("resize",updateCafeBattleScale,{passive:true}); window.addEventListener?.("orientationchange",updateCafeBattleScale,{passive:true}); window.visualViewport?.addEventListener("resize",updateCafeBattleScale,{passive:true});
  if(new URLSearchParams(location.search).has("test")) window.__AnimalCafeRushTest={ forceComplete(){ if(!run) return null; run.served=run.goal; run.coins=run.goal*3; finishDay(); return { served:run.served, goal:run.goal, finishing:run.finishing, resultVisible:!nodes.result.classList.contains("is-hidden"), profile:JSON.parse(localStorage.getItem(saveKey)||"{}") }; }, snapshot(){ return { selectedDay, run:run?{ day:run.day, mode:run.mode.id, modeLabel:t(run.mode.label), served:run.served, goal:run.goal, finishing:run.finishing, firstOrder:[...(run.queue[0]?.order||[])], firstOrderBonus:run.queue[0]?orderBonus(run.queue[0].order):0 }:null, profile:JSON.parse(localStorage.getItem(saveKey)||"{}") }; } };
  nodes.locale.addEventListener("change",()=>{ locale=nodes.locale.value; localStorage.setItem(localeKey,locale); applyLocale(); }); nodes.mainStart.addEventListener("click",()=>{ showStage(); updateCafeBattleScale(); }); nodes.stageBack.addEventListener("click",showMain); nodes.start.addEventListener("click",()=>startDay(selectedDay)); nodes.back.addEventListener("click",()=>{ showStage(); updateCafeBattleScale(); }); nodes.menuBtn.addEventListener("click",()=>{ showStage(); updateCafeBattleScale(); }); nodes.next.addEventListener("click",()=>startDay(profile.day)); installDayRail(); applyLocale();
})();
