/* Authored TriPeaks guide; ranks are adjacent, never sum-13 or Ace/King wrap. */
(() => {
 const keys=['summary','how','rule1','rule2','rule3','recovery'];
 const packs={
 en:['Clear the three peaks by building a chain on the current card.','How to play','Tap an exposed card exactly one rank above or below the current card. Suit and color do not matter.','A follows 2 only; K follows Q only. A and K cannot connect. Cards under other cards are unavailable.','Remove cards to uncover more choices. If no useful move remains, draw from the stock; this breaks the combo.','Hint shows a move. Undo reverses a move. Restart repeats the deal; New Game deals another.'],
 'zh-tw':['接續目前牌的點數，逐步清空三座牌峰。','玩法說明','點選比目前牌大一點或小一點的未覆蓋牌，花色與顏色不限。','A 只能接 2，K 只能接 Q，A 與 K 不相接。被其他牌壓住的牌暫時不能選。','移除牌會露出更多選擇。沒有合適走法時可翻牌庫，但會中斷連鎖。','提示指出走法，還原撤回一步。重新開始重玩同一牌局，新遊戲另發一局。'],
 'zh-cn':['接续当前牌的点数，逐步清空三座牌峰。','玩法说明','点击比当前牌大一点或小一点的未覆盖牌，花色与颜色不限。','A 只能接 2，K 只能接 Q，A 与 K 不相接。被其他牌压住的牌暂时不能选。','移除牌会露出更多选择。没有合适走法时可翻牌库，但会中断连锁。','提示指出走法，撤销退回一步。重新开始重玩同一牌局，新游戏另发一局。'],
 ja:['現在のカードにつなげて、3つの山を消します。','遊び方','現在のカードより数字が1つ上か下の、重なっていないカードをタップ。スートや色は問いません。','Aは2とだけ、KはQとだけつながります。AとKはつながりません。下に隠れたカードは選べません。','カードを消して選択肢を増やします。必要なら山札を引けますが、コンボは途切れます。','ヒントで手を確認し、元に戻すで取り消せます。リスタートは同じ配札、新しいゲームは別の配札です。'],
 ko:['현재 카드에 이어 붙여 세 봉우리의 카드를 없애세요.','게임 방법','현재 카드보다 숫자가 하나 높거나 낮은, 덮이지 않은 카드를 누르세요. 무늬와 색은 상관없습니다.','A는 2와만, K는 Q와만 이어집니다. A와 K는 연결되지 않으며 덮인 카드는 선택할 수 없습니다.','카드를 없애 새 선택지를 여세요. 필요하면 덱을 뽑을 수 있지만 콤보가 끊깁니다.','힌트는 수를 보여 주고 실행 취소는 되돌립니다. 다시 시작은 같은 배치, 새 게임은 다른 배치입니다.'],
 es:['Encadena cartas sobre la carta actual para vaciar las tres cimas.','Cómo jugar','Toca una carta descubierta de valor uno mayor o menor que la actual. El palo y el color no importan.','El As conecta solo con 2 y el Rey solo con la Reina. As y Rey no conectan. Las cartas cubiertas no están disponibles.','Retira cartas para abrir opciones. Si necesitas robar del mazo, el combo se interrumpe.','Pista muestra una jugada; Deshacer la revierte. Reiniciar repite el reparto; Nueva partida crea otro.'],
 'pt-br':['Encadeie cartas sobre a carta atual para limpar os três picos.','Como jogar','Toque numa carta descoberta com valor um acima ou abaixo da atual. Naipe e cor não importam.','O Ás liga apenas ao 2 e o Rei apenas à Dama. Ás e Rei não ligam. Cartas cobertas não estão disponíveis.','Remova cartas para abrir opções. Comprar do monte quando necessário interrompe o combo.','Dica mostra uma jogada; Desfazer a reverte. Reiniciar repete a distribuição; Novo jogo cria outra.'],
 fr:['Enchaînez les cartes sur la carte actuelle pour vider les trois pics.','Comment jouer','Touchez une carte libre de valeur immédiatement supérieure ou inférieure. La couleur et le symbole ne comptent pas.','L’As se relie seulement au 2, le Roi à la Dame. As et Roi ne se relient pas. Les cartes recouvertes sont indisponibles.','Retirez des cartes pour ouvrir des choix. Piocher si nécessaire interrompt le combo.','Indice montre un coup ; Annuler le retire. Recommencer reprend cette donne ; Nouvelle partie en crée une autre.'],
 de:['Bilde eine Kartenkette und räume die drei Gipfel ab.','Spielanleitung','Tippe eine freie Karte genau einen Rang über oder unter der aktuellen Karte an. Farbe und Symbol sind egal.','Ass verbindet nur mit 2, König nur mit Dame. Ass und König passen nicht zusammen. Bedeckte Karten sind gesperrt.','Entferne Karten, um neue Möglichkeiten zu öffnen. Ziehen vom Stapel unterbricht die Kombo.','Tipp zeigt einen Zug; Rückgängig nimmt ihn zurück. Neustart wiederholt die Verteilung; Neues Spiel mischt neu.'],
 it:['Crea una catena sulla carta attuale per liberare le tre cime.','Come giocare','Tocca una carta libera di valore subito superiore o inferiore. Seme e colore non contano.','L’Asso si collega solo al 2, il Re solo alla Donna. Asso e Re non si collegano. Le carte coperte non sono disponibili.','Rimuovi carte per aprire nuove scelte. Pescare dal mazzo interrompe la combo.','Suggerimento mostra una mossa; Annulla la cancella. Ricomincia ripete la distribuzione; Nuova partita ne crea un’altra.'],
 ru:['Продолжайте цепочку на текущей карте, чтобы убрать три вершины.','Как играть','Нажмите свободную карту на один ранг выше или ниже текущей. Масть и цвет не важны.','Туз соединяется только с 2, король — с дамой. Туз и король не соединяются. Перекрытые карты недоступны.','Убирайте карты, открывая новые варианты. Добор из колоды прерывает комбо.','Подсказка показывает ход, отмена возвращает его. Перезапуск повторяет расклад, новая игра создаёт другой.'],
 hi:['मौजूदा पत्ते पर क्रम बनाकर तीनों चोटियाँ साफ करें।','कैसे खेलें','मौजूदा पत्ते से ठीक एक अंक ऊपर या नीचे का खुला पत्ता दबाएँ। सूट और रंग मायने नहीं रखते।','A केवल 2 से और K केवल Q से जुड़ता है। A और K नहीं जुड़ते। ढके हुए पत्ते उपलब्ध नहीं हैं।','पत्ते हटाकर नए विकल्प खोलें। ज़रूरत पर डेक से लेने से कॉम्बो टूटता है।','संकेत चाल दिखाता है; वापस करें उसे पलटता है। फिर शुरू करें वही बाँट दोहराता है; नया खेल दूसरा बाँट देता है।'],
 ar:['كوّن سلسلة على البطاقة الحالية لإزالة القمم الثلاث.','طريقة اللعب','اضغط بطاقة مكشوفة تزيد رتبتها أو تنقص درجة واحدة عن البطاقة الحالية. النوع واللون لا يهمان.','الآس يتصل بالاثنين فقط، والملك بالملكة فقط. الآس والملك لا يتصلان. البطاقات المغطاة غير متاحة.','أزل البطاقات لفتح خيارات جديدة. السحب من الرزمة عند الحاجة يقطع السلسلة.','التلميح يعرض نقلة والتراجع يلغيها. إعادة البدء تكرر التوزيع نفسه، واللعبة الجديدة تنشئ توزيعًا آخر.'],
 };
 window.TRIPEAKS_GUIDE_LOCALES=Object.fromEntries(Object.entries(packs).map(([code,values])=>[code,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))]));
})();
