(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  const locales=window.ANIMAL_PATCHWORK_PAWS_LOCALES||{};
  const storage={get(key){try{return window.localStorage?.getItem(key)||null}catch(_){return null}},set(key,value){try{window.localStorage?.setItem(key,value)}catch(_){}}};
  const patches=[
    {name:"patch1",animal:"animal1",initial:[1,2,3,1],tiles:[{edges:["sun","leaf","water","moon"]},{edges:["moon","sun","stone","leaf"]},{edges:["water","stone","moon","sun"]},{edges:["stone","leaf","sun","water"]}]},
    {name:"patch2",animal:"animal2",initial:[2,1,3,2],tiles:[{edges:["leaf","water","stone","moon"]},{edges:["moon","leaf","sun","water"]},{edges:["stone","sun","moon","leaf"]},{edges:["sun","water","leaf","stone"]}]},
    {name:"patch3",animal:"animal3",initial:[3,2,1,3],tiles:[{edges:["moon","stone","leaf","sun"]},{edges:["sun","water","moon","stone"]},{edges:["leaf","moon","sun","water"]},{edges:["moon","sun","stone","leaf"]}]},
    {name:"patch4",animal:"animal4",initial:[1,3,2,1],tiles:[{edges:["sun","leaf","moon","stone"]},{edges:["water","sun","stone","leaf"]},{edges:["moon","water","sun","sun"]},{edges:["stone","leaf","water","water"]}]}
  ];
  let locale=storage.get("weightplay-animal-patchwork-paws-locale")||"en";if(!locales[locale])locale="en";
  let sound=storage.get("weightplay-animal-patchwork-paws-sound")!=="off";
  let patchIndex=0,rotations=[],solved=new Set(),turns=0,sessionTurns=0,feedback="",currentScreen="main";
  const copy=(key,vars={})=>Object.entries(vars).reduce((out,[name,value])=>out.replaceAll(`{${name}}`,String(value)),(locales[locale]||locales.en)[key]||locales.en[key]||key);
  const announce=(name,data={})=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:`animal_patchwork_paws_${name}`,patch:patchIndex+1,turns, ...data})};
  const bestValue=()=>Number(storage.get("weightplay-animal-patchwork-paws-best-v2")||0)||"—";
  function show(screen){currentScreen=screen;document.querySelectorAll("[data-screen]").forEach(node=>{node.hidden=node.dataset.screen!==screen});$("settingsPanel").hidden=true;$("backBtn").hidden=screen==="main";}
  function oriented(tile,index){const shift=rotations[index]||0;return tile.edges.map((_,edgeIndex)=>tile.edges[(edgeIndex-shift+4)%4])}
  function renderStatic(){document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(node=>{node.textContent=copy(node.dataset.i18n)});$("backBtn").setAttribute("aria-label",copy("back"));$("settingsBtn").setAttribute("aria-label",copy("settings"));$("closeSettings").setAttribute("aria-label",copy("close"));$("localeSelect").setAttribute("aria-label",copy("language"));$("soundBtn").textContent=sound?copy("on"):copy("off");$("soundBtn").setAttribute("aria-pressed",String(sound));$("best").textContent=copy("best",{best:bestValue()});renderStages();renderBattle();renderResult()}
  function renderStages(){const root=$("stageList");if(!root)return;root.replaceChildren();patches.forEach((patch,index)=>{const button=document.createElement("button");button.type="button";button.className="stage-card";button.innerHTML=`<span><strong>${copy(patch.name)}</strong><small>${solved.has(index)?copy("patchDone"):copy("patchOpen")} · ${copy(patch.animal)}</small></span><span class="arrow">${solved.has(index)?"✓":"→"}</span>`;button.addEventListener("click",()=>startPatch(index,true));root.appendChild(button)})}
  function startPatch(index,fromStage=false){patchIndex=index;rotations=[...patches[index].initial];turns=0;feedback="";if(index===0||fromStage)sessionTurns=0;show("battle");renderBattle();announce("start")}
  function tileSolved(){const patch=patches[patchIndex];return patch.tiles.every((tile,index)=>rotations[index]===0)}
  function boardSolved(){const patch=patches[patchIndex];for(let index=0;index<patch.tiles.length;index+=1){const edges=oriented(patch.tiles[index],index);if(index%2===0&&edges[1]!==oriented(patch.tiles[index+1],index+1)[3])return false;if(index<2&&edges[2]!==oriented(patch.tiles[index+2],index+2)[0])return false}return true}
  function edgeNode(edge,position){const span=document.createElement("span");span.className=`edge edge-${position} edge-${edge}`;span.setAttribute("aria-hidden","true");return span}
  function renderBattle(){if(!$("board")||currentScreen!=="battle")return;const patch=patches[patchIndex];$("patchTitle").textContent=copy(patch.name);$("progressPill").textContent=`${patchIndex+1} / ${patches.length}`;$("prompt").textContent=copy("prompt");$("ruleText").textContent=copy("rule");const root=$("board");root.replaceChildren();patch.tiles.forEach((tile,index)=>{const button=document.createElement("button");button.type="button";button.className="tile";button.setAttribute("role","gridcell");button.setAttribute("aria-label",copy("rotate",{number:index+1}));const edges=oriented(tile,index);["n","e","s","w"].forEach((position,edgeIndex)=>button.appendChild(edgeNode(edges[edgeIndex],position)));const label=document.createElement("span");label.className="tile-label";label.textContent=index===3?"✣":index===0?"❧":index===1?"≈":"◆";label.setAttribute("aria-hidden","true");button.appendChild(label);button.addEventListener("click",()=>rotateTile(index));root.appendChild(button)});$("status").textContent=feedback?copy(feedback,{animal:copy(patch.animal)}):"";$("status").className=feedback==="correct"?"status good":feedback==="wrong"?"status try":"status"}
  function rotateTile(index){if(feedback==="correct")return;rotations[index]=(rotations[index]+1)%4;turns+=1;sessionTurns+=1;feedback="turned";announce("turn",{tile:index+1});renderBattle()}
  function checkBoard(){if(boardSolved()){feedback="correct";solved.add(patchIndex);announce("complete");renderBattle();setTimeout(()=>{show("result");renderResult()},280)}else{feedback="wrong";announce("check",{correct:false});renderBattle()}}
  function renderResult(){if(!$("resultText"))return;const complete=solved.size===patches.length;$("resultTitle").textContent=complete?copy("resultTitle"):copy("resultPartial");$("resultText").textContent=copy("resultText",{count:solved.size,total:patches.length,turns:sessionTurns});$("nextBtn").hidden=complete;$("resultMapBtn").hidden=!complete;if(complete){const old=Number(storage.get("weightplay-animal-patchwork-paws-best-v2")||0);if(!old||sessionTurns<old)storage.set("weightplay-animal-patchwork-paws-best-v2",String(sessionTurns));$("resultText").textContent=copy("resultText",{count:solved.size,total:patches.length,turns:Math.min(old||sessionTurns,sessionTurns)})}}
  function nextPatch(){const next=patchIndex+1;if(next<patches.length)startPatch(next);else{show("stage");renderStages()}}
  function goBack(){if(currentScreen==="battle"){show("stage");renderStages()}else if(currentScreen==="stage"||currentScreen==="result")show("main")}
  function bind(){$("startBtn").addEventListener("click",()=>startPatch(0));$("mapBtn").addEventListener("click",()=>{show("stage");renderStages()});$("resultMapBtn").addEventListener("click",()=>{show("stage");renderStages()});$("nextBtn").addEventListener("click",nextPatch);$("checkBtn").addEventListener("click",checkBoard);$("resetBtn").addEventListener("click",()=>{rotations=[...patches[patchIndex].initial];turns=0;feedback="";renderBattle();announce("reset")});$("backBtn").addEventListener("click",goBack);$("settingsBtn").addEventListener("click",()=>{$("settingsPanel").hidden=false});$("closeSettings").addEventListener("click",()=>{$("settingsPanel").hidden=true});$("soundBtn").addEventListener("click",()=>{sound=!sound;storage.set("weightplay-animal-patchwork-paws-sound",sound?"on":"off");renderStatic()});$("localeSelect").addEventListener("change",event=>{locale=event.target.value;storage.set("weightplay-animal-patchwork-paws-locale",locale);renderStatic()})}
  function boot(){bind();$("localeSelect").value=locale;$("loading").hidden=true;$("app").hidden=false;show("main");renderStatic();announce("loaded")}
  window.__ANIMAL_PATCHWORK_PAWS_TEST__={patches,startPatch,rotateTile,checkBoard,getState:()=>({patchIndex,rotations:[...rotations],solved:[...solved],turns,screen:currentScreen,feedback,boardSolved:boardSolved()})};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
}());
