(function () {
  "use strict";
  const en = {
    loading: "Waking the moon garden…", back: "← Main", gardens: "Gardens", settings: "Settings", language: "Language",
    soundOn: "Sound: On", soundOff: "Sound: Off", close: "Close settings", mainBack: "Back to WeightPlay", mainCoverAlt: "Ring Garden moonlit petal garden", guideAlt: "Rainbow Hop Mimi, your moon-garden guide", resultAlt: "Rainbow Hop Mimi celebrates the blooming garden", summaryLabel: "Gameplay summary", factsLabel: "Game facts", guideLabel: "Ring Garden game guide", stageSections: "Garden sections", battleTargetLabel: "Target pattern", battleRingsLabel: "Three petal rings", eyebrow: "MOONLIGHT PATTERN PUZZLE", title: "Ring Garden",
    lede: "Turn three petal rings until the moon-garden pattern blooms.", summary: "A calm three-ring puzzle with four moonlit gardens.", progress: "Garden progress", guideTitle: "How to bloom",
    guideOne: "1. Start the garden and choose a moonlit scene.", guideTwo: "2. Turn each ring until its petals match the target.", guideThree: "3. Reset anytime, then continue to the next garden.", factOne: "4 gardens", factTwo: "Ring turns", factThree: "Calm replay", start: "Start Garden",
    stageEyebrow: "CHOOSE A GARDEN", stageTitle: "Where will you bloom?", stageLede: "Each garden has a different three-ring pattern.", choose: "Open garden",
    battleEyebrow: "MOON GARDEN", target: "Target", turns: "Turns", clue: "Match the three rings to the target petals.", begin: "Choose a ring to begin.",
    turnLeft: "Turn ring {n} left", turnRight: "Turn ring {n} right", reset: "Reset", wrong: "The pattern is still awake. Try another ring or reset the garden.",
    complete: "The petals align!", completeCopy: "Your moon garden is glowing.", best: "Best", next: "Next Garden", backToGardens: "Back to Gardens", final: "All four moon gardens are blooming.",
    gardenOne: "Firefly Arbor", gardenTwo: "Mosslight Pool", gardenThree: "Rainbow Fern", gardenFour: "Silver Reed", gardenOneClue: "Follow the warm firefly ring into the quiet centre.", gardenTwoClue: "Let the moss ring rest beneath the silver moon.", gardenThreeClue: "Bring the rainbow petals together for the last bloom.", gardenFourClue: "Set the silver reeds in a gentle moonlit line.",
    ringName: "Petal ring {n}", targetPattern: "Target pattern", noBest: "—"
  };
  const copy = {
    en,
    "zh-Hant": { ...en, loading: "喚醒月光花園……", back: "← 主選單", gardens: "花園", settings: "設定", language: "語言", eyebrow: "月光圖樣益智", title: "環影花園", lede: "轉動三層花瓣環，讓月光花園的圖樣綻放。", summary: "四座月光花園，帶來平靜的三環益智挑戰。", progress: "花園進度", guideTitle: "綻放指南", guideOne: "1. 開始花園，選一座月光場景。", guideTwo: "2. 轉動每層花環，讓花瓣對齊目標。", guideThree: "3. 隨時重設，再前往下一座花園。", factOne: "4 座花園", factTwo: "旋環次數", factThree: "平靜重玩", start: "開始花園", stageEyebrow: "選擇花園", stageTitle: "想讓哪座花園綻放？", stageLede: "每座花園都有不同的三環圖樣。", choose: "進入花園", battleEyebrow: "月光花園", target: "目標", turns: "旋轉", clue: "讓三層花環對齊目標花瓣。", begin: "選一層花環開始。", turnLeft: "第 {n} 層花環向左轉", turnRight: "第 {n} 層花環向右轉", reset: "重設", wrong: "圖樣還沒醒來。換一層花環，或重設花園再試一次。", complete: "花瓣對齊了！", completeCopy: "你的月光花園正在發光。", best: "最佳", next: "下一座花園", backToGardens: "回到花園", final: "四座月光花園都綻放了。", gardenOne: "螢火樹蔭", gardenTwo: "苔光池", gardenThree: "彩虹蕨地", gardenFour: "銀蘆花徑", gardenOneClue: "跟著溫暖的螢火環，走進安靜的中心。", gardenTwoClue: "讓苔蘚花環在銀色月光下休息。", gardenThreeClue: "把彩虹花瓣聚在一起，完成最後的綻放。", gardenFourClue: "把銀蘆排成溫柔的月光線條。", ringName: "第 {n} 層花瓣環", targetPattern: "目標圖樣" },
    "zh-Hans": { ...en, title: "环影花园", lede: "转动三层花瓣环，让月光花园的图案绽放。", summary: "四座月光花园，带来平静的三环益智挑战。", progress: "花园进度", guideTitle: "绽放指南", guideOne: "1. 开始花园，选择一座月光场景。", guideTwo: "2. 转动每层花环，让花瓣对齐目标。", guideThree: "3. 随时重置，再前往下一座花园。", factOne: "4 座花园", start: "开始花园", settings: "设置", language: "语言", gardens: "花园", back: "← 主菜单", stageEyebrow: "选择花园", stageTitle: "想让哪座花园绽放？", stageLede: "每座花园都有不同的三环图案。", choose: "进入花园", battleEyebrow: "月光花园", target: "目标", turns: "旋转", clue: "让三层花环对齐目标花瓣。", begin: "选择一层花环开始。", turnLeft: "第 {n} 层花环向左转", turnRight: "第 {n} 层花环向右转", reset: "重置", complete: "花瓣对齐了！", completeCopy: "你的月光花园正在发光。", backToGardens: "回到花园", next: "下一座花园", final: "四座月光花园都绽放了。", ringName: "第 {n} 层花瓣环", targetPattern: "目标图案" },
    ja: { ...en, title: "リングガーデン", lede: "3つの花びらリングを回して、月光の庭を咲かせよう。", summary: "4つの月夜の庭を楽しむ、穏やかな3リングパズル。", progress: "庭の進行", guideTitle: "遊び方", guideOne: "1. 庭を始めて、月明かりの景色を選びます。", guideTwo: "2. リングを回して花びらを目標に合わせます。", guideThree: "3. いつでもリセットして次の庭へ進めます。", start: "庭を始める", settings: "設定", language: "言語", gardens: "庭へ", back: "← メイン", stageEyebrow: "庭を選ぶ", stageTitle: "どの庭を咲かせる？", stageLede: "庭ごとに異なる3リングの模様があります。", choose: "庭を開く", battleEyebrow: "月の庭", target: "目標", turns: "回転", clue: "3つのリングを目標の花びらに合わせます。", begin: "リングを選んで開始。", reset: "リセット", backToGardens: "庭に戻る", next: "次の庭", complete: "花びらが揃いました！", completeCopy: "月の庭が輝いています。", final: "4つの月の庭がすべて咲きました。", ringName: "花びらリング {n}", targetPattern: "目標模様" },
    ko: { ...en, title: "링 가든", lede: "세 겹의 꽃잎 링을 돌려 달빛 정원의 무늬를 피워 보세요.", summary: "네 개의 달빛 정원을 즐기는 차분한 3링 퍼즐입니다.", progress: "정원 진행", guideTitle: "플레이 방법", guideOne: "1. 정원을 시작하고 달빛 장면을 선택하세요.", guideTwo: "2. 각 링을 돌려 꽃잎을 목표에 맞추세요.", guideThree: "3. 언제든 초기화하고 다음 정원으로 가세요.", start: "정원 시작", settings: "설정", language: "언어", gardens: "정원", back: "← 메인", stageEyebrow: "정원 선택", stageTitle: "어느 정원을 피울까요?", stageLede: "정원마다 다른 세 링 무늬가 있습니다.", choose: "정원 열기", battleEyebrow: "달빛 정원", target: "목표", turns: "회전", clue: "세 링을 목표 꽃잎에 맞추세요.", begin: "링을 골라 시작하세요.", reset: "초기화", backToGardens: "정원으로", next: "다음 정원", complete: "꽃잎이 맞았어요!", completeCopy: "달빛 정원이 빛나고 있습니다.", final: "네 정원이 모두 피었습니다.", ringName: "꽃잎 링 {n}", targetPattern: "목표 무늬" },
    es: { ...en, title: "Jardín de Anillos", lede: "Gira tres anillos de pétalos hasta hacer florecer el jardín lunar.", summary: "Un rompecabezas sereno de tres anillos y cuatro jardines nocturnos.", progress: "Progreso del jardín", guideTitle: "Cómo florecer", guideOne: "1. Empieza el jardín y elige una escena lunar.", guideTwo: "2. Gira cada anillo para igualar los pétalos objetivo.", guideThree: "3. Reinicia cuando quieras y sigue al siguiente jardín.", start: "Empezar jardín", settings: "Ajustes", language: "Idioma", gardens: "Jardines", back: "← Inicio", stageEyebrow: "ELIGE UN JARDÍN", stageTitle: "¿Cuál harás florecer?", stageLede: "Cada jardín tiene un patrón distinto de tres anillos.", choose: "Abrir jardín", battleEyebrow: "JARDÍN LUNAR", target: "Objetivo", turns: "Giros", clue: "Haz coincidir los tres anillos con los pétalos objetivo.", begin: "Elige un anillo para empezar.", reset: "Reiniciar", backToGardens: "Volver a jardines", next: "Siguiente jardín", complete: "¡Los pétalos encajan!", completeCopy: "Tu jardín lunar está brillando.", final: "Los cuatro jardines lunares han florecido.", ringName: "Anillo de pétalos {n}", targetPattern: "Patrón objetivo" },
    "pt-BR": { ...en, title: "Jardim de Anéis", lede: "Gire três anéis de pétalas até o padrão do jardim lunar florescer.", summary: "Um quebra-cabeça tranquilo de três anéis e quatro jardins noturnos.", progress: "Progresso do jardim", guideTitle: "Como florescer", guideOne: "1. Comece o jardim e escolha uma cena ao luar.", guideTwo: "2. Gire cada anel para combinar com as pétalas-alvo.", guideThree: "3. Reinicie quando quiser e siga para o próximo jardim.", start: "Começar jardim", settings: "Configurações", language: "Idioma", gardens: "Jardins", back: "← Início", stageEyebrow: "ESCOLHA UM JARDIM", stageTitle: "Qual jardim vai florescer?", stageLede: "Cada jardim tem um padrão diferente de três anéis.", choose: "Abrir jardim", battleEyebrow: "JARDIM AO LUAR", target: "Alvo", turns: "Giros", clue: "Combine os três anéis com as pétalas-alvo.", begin: "Escolha um anel para começar.", reset: "Redefinir", backToGardens: "Voltar aos jardins", next: "Próximo jardim", complete: "As pétalas se alinharam!", completeCopy: "Seu jardim lunar está brilhando.", final: "Os quatro jardins lunares floresceram.", ringName: "Anel de pétalas {n}", targetPattern: "Padrão-alvo" },
    fr: { ...en, title: "Jardin des Anneaux", lede: "Tournez trois anneaux de pétales pour faire fleurir le motif du jardin lunaire.", summary: "Un puzzle paisible à trois anneaux dans quatre jardins nocturnes.", progress: "Progression du jardin", guideTitle: "Comment fleurir", guideOne: "1. Lancez le jardin et choisissez une scène lunaire.", guideTwo: "2. Tournez chaque anneau pour aligner les pétales cibles.", guideThree: "3. Réinitialisez quand vous voulez puis passez au jardin suivant.", start: "Commencer le jardin", settings: "Réglages", language: "Langue", gardens: "Jardins", back: "← Accueil", stageEyebrow: "CHOISISSEZ UN JARDIN", stageTitle: "Quel jardin fera fleurir ?", stageLede: "Chaque jardin possède un motif différent à trois anneaux.", choose: "Ouvrir le jardin", battleEyebrow: "JARDIN LUNAIRE", target: "Cible", turns: "Tours", clue: "Alignez les trois anneaux sur les pétales cibles.", begin: "Choisissez un anneau pour commencer.", reset: "Réinitialiser", backToGardens: "Retour aux jardins", next: "Jardin suivant", complete: "Les pétales sont alignés !", completeCopy: "Votre jardin lunaire brille.", final: "Les quatre jardins lunaires sont en fleurs.", ringName: "Anneau de pétales {n}", targetPattern: "Motif cible" },
    de: { ...en, title: "Ringgarten", lede: "Drehe drei Blütenringe, bis das Muster des Mondgartens erblüht.", summary: "Ein ruhiges Drei-Ringe-Rätsel mit vier Mondgärten.", progress: "Gartenfortschritt", guideTitle: "So blüht der Garten", guideOne: "1. Starte den Garten und wähle eine Mondszene.", guideTwo: "2. Drehe jeden Ring, bis die Blüten zum Ziel passen.", guideThree: "3. Setze jederzeit zurück und spiele im nächsten Garten weiter.", start: "Garten starten", settings: "Einstellungen", language: "Sprache", gardens: "Gärten", back: "← Start", stageEyebrow: "GARTEN WÄHLEN", stageTitle: "Welcher Garten blüht?", stageLede: "Jeder Garten hat ein eigenes Muster aus drei Ringen.", choose: "Garten öffnen", battleEyebrow: "MONDGARTEN", target: "Ziel", turns: "Drehungen", clue: "Richte die drei Ringe auf die Zielblüten aus.", begin: "Wähle einen Ring zum Starten.", reset: "Zurücksetzen", backToGardens: "Zu den Gärten", next: "Nächster Garten", complete: "Die Blüten passen!", completeCopy: "Dein Mondgarten leuchtet.", final: "Alle vier Mondgärten blühen.", ringName: "Blütenring {n}", targetPattern: "Zielmuster" },
    it: { ...en, title: "Giardino degli Anelli", lede: "Ruota tre anelli di petali finché il motivo del giardino lunare sboccia.", summary: "Un tranquillo rompicapo a tre anelli in quattro giardini lunari.", progress: "Progressi del giardino", guideTitle: "Come farlo sbocciare", guideOne: "1. Avvia il giardino e scegli una scena al chiaro di luna.", guideTwo: "2. Ruota ogni anello per allineare i petali bersaglio.", guideThree: "3. Reimposta quando vuoi e passa al giardino successivo.", start: "Avvia giardino", settings: "Impostazioni", language: "Lingua", gardens: "Giardini", back: "← Inizio", stageEyebrow: "SCEGLI UN GIARDINO", stageTitle: "Quale farai sbocciare?", stageLede: "Ogni giardino ha un diverso motivo a tre anelli.", choose: "Apri giardino", battleEyebrow: "GIARDINO LUNARE", target: "Obiettivo", turns: "Giri", clue: "Abbina i tre anelli ai petali obiettivo.", begin: "Scegli un anello per iniziare.", reset: "Reimposta", backToGardens: "Torna ai giardini", next: "Giardino successivo", complete: "I petali sono allineati!", completeCopy: "Il tuo giardino lunare sta brillando.", final: "Tutti e quattro i giardini lunari sono fioriti.", ringName: "Anello di petali {n}", targetPattern: "Motivo obiettivo" },
    ru: { ...en, title: "Сад колец", lede: "Поворачивайте три кольца лепестков, пока узор лунного сада не расцветёт.", summary: "Спокойная головоломка с тремя кольцами и четырьмя садами.", progress: "Прогресс сада", guideTitle: "Как расцвести", guideOne: "1. Начните сад и выберите лунную сцену.", guideTwo: "2. Поворачивайте кольца, совмещая лепестки с целью.", guideThree: "3. Сбрасывайте ход в любой момент и переходите дальше.", start: "Начать сад", settings: "Настройки", language: "Язык", gardens: "Сады", back: "← Главная", stageEyebrow: "ВЫБЕРИТЕ САД", stageTitle: "Какой сад расцветёт?", stageLede: "В каждом саду свой узор из трёх колец.", choose: "Открыть сад", battleEyebrow: "ЛУННЫЙ САД", target: "Цель", turns: "Повороты", clue: "Совместите три кольца с лепестками цели.", begin: "Выберите кольцо, чтобы начать.", reset: "Сбросить", backToGardens: "К садам", next: "Следующий сад", complete: "Лепестки совпали!", completeCopy: "Ваш лунный сад сияет.", final: "Все четыре лунных сада расцвели.", ringName: "Кольцо лепестков {n}", targetPattern: "Целевой узор" },
    hi: { ...en, title: "रिंग गार्डन", lede: "तीन पंखुड़ी रिंग घुमाएँ और चाँदनी बगीचे का पैटर्न खिलाएँ।", summary: "चार चाँदनी बगीचों वाला शांत तीन-रिंग पहेली खेल।", progress: "बगीचे की प्रगति", guideTitle: "कैसे खिलाएँ", guideOne: "1. बगीचा शुरू करें और चाँदनी दृश्य चुनें।", guideTwo: "2. लक्ष्य पंखुड़ियों से मिलाने के लिए हर रिंग घुमाएँ।", guideThree: "3. कभी भी रीसेट करें और अगले बगीचे पर जाएँ।", start: "बगीचा शुरू करें", settings: "सेटिंग्स", language: "भाषा", gardens: "बगीचे", back: "← मुख्य", stageEyebrow: "बगीचा चुनें", stageTitle: "कौन सा बगीचा खिलाएँगे?", stageLede: "हर बगीचे में तीन रिंग का अलग पैटर्न है।", choose: "बगीचा खोलें", battleEyebrow: "चाँदनी बगीचा", target: "लक्ष्य", turns: "घुमाव", clue: "तीनों रिंग को लक्ष्य पंखुड़ियों से मिलाएँ।", begin: "शुरू करने के लिए रिंग चुनें।", reset: "रीसेट", backToGardens: "बगीचों पर लौटें", next: "अगला बगीचा", complete: "पंखुड़ियाँ मिल गईं!", completeCopy: "आपका चाँदनी बगीचा चमक रहा है।", final: "चारों चाँदनी बगीचे खिल गए।", ringName: "पंखुड़ी रिंग {n}", targetPattern: "लक्ष्य पैटर्न" },
    ar: { ...en, loading: "إيقاظ حديقة القمر…", eyebrow: "لغز أنماط ضوء القمر", title: "حديقة الحلقات", lede: "أدر ثلاث حلقات من البتلات حتى يزهر نمط حديقة القمر.", summary: "لغز هادئ من ثلاث حلقات في أربع حدائق مضيئة بالقمر.", progress: "تقدم الحديقة", guideTitle: "طريقة اللعب", guideOne: "1. ابدأ الحديقة واختر مشهداً قمرياً.", guideTwo: "2. أدر كل حلقة لتطابق البتلات الهدف.", guideThree: "3. أعد الضبط متى شئت ثم انتقل إلى الحديقة التالية.", factOne: "4 حدائق قمرية", factTwo: "دورات الحلقات", factThree: "إعادة هادئة", start: "ابدأ الحديقة", settings: "الإعدادات", language: "اللغة", gardens: "الحدائق", back: "← الرئيسية", mainBack: "العودة إلى WeightPlay", mainCoverAlt: "حديقة الحلقات القمرية ذات البتلات", guideAlt: "ميمي قوس قزح، مرشدتك في الحديقة القمرية", resultAlt: "ميمي قوس قزح تحتفل بتفتح الحديقة", summaryLabel: "ملخص طريقة اللعب", factsLabel: "معلومات اللعبة", guideLabel: "دليل لعبة حديقة الحلقات", stageSections: "أقسام الحدائق", stageEyebrow: "اختر حديقة", stageTitle: "أي حديقة ستزهر؟", stageLede: "لكل حديقة نمط مختلف من ثلاث حلقات.", choose: "افتح الحديقة", battleEyebrow: "حديقة القمر", target: "الهدف", turns: "الدورات", clue: "طابق الحلقات الثلاث مع بتلات الهدف.", begin: "اختر حلقة للبدء.", reset: "إعادة ضبط", backToGardens: "العودة إلى الحدائق", next: "الحديقة التالية", complete: "تطابقت البتلات!", completeCopy: "حديقتك القمرية تتوهج.", final: "أزهرت الحدائق القمرية الأربع.", ringName: "حلقة البتلات {n}", targetPattern: "النمط الهدف", soundOn: "الصوت: مفعّل", soundOff: "الصوت: غير مفعّل", close: "إغلاق الإعدادات" }
  };
  const localizedGardenCopy = {
    en: { turnLeft: "Turn ring {n} left", turnRight: "Turn ring {n} right", gardenOne: "Firefly Arbor", gardenTwo: "Mosslight Pool", gardenThree: "Rainbow Fern", gardenFour: "Silver Reed" },
    "zh-Hant": { turnLeft: "第 {n} 層花環向左轉", turnRight: "第 {n} 層花環向右轉", gardenOne: "螢火樹蔭", gardenTwo: "苔光池", gardenThree: "彩虹蕨地", gardenFour: "銀蘆花徑" },
    "zh-Hans": { turnLeft: "第 {n} 个花环向左转", turnRight: "第 {n} 个花环向右转", gardenOne: "萤火树荫", gardenTwo: "苔光池", gardenThree: "彩虹蕨地", gardenFour: "银芦花径" },
    ja: { turnLeft: "リング {n} を左に回す", turnRight: "リング {n} を右に回す", gardenOne: "ホタルの木陰", gardenTwo: "苔光の池", gardenThree: "虹のシダ", gardenFour: "銀のアシ" },
    ko: { turnLeft: "링 {n} 왼쪽으로 돌리기", turnRight: "링 {n} 오른쪽으로 돌리기", gardenOne: "반딧불 나무그늘", gardenTwo: "이끼빛 연못", gardenThree: "무지개 고사리", gardenFour: "은빛 갈대길" },
    es: { turnLeft: "Girar el anillo {n} a la izquierda", turnRight: "Girar el anillo {n} a la derecha", gardenOne: "Arboleda de Luciérnagas", gardenTwo: "Estanque Musgoso", gardenThree: "Helecho Arcoíris", gardenFour: "Juncos Plateados" },
    "pt-BR": { turnLeft: "Girar o anel {n} para a esquerda", turnRight: "Girar o anel {n} para a direita", gardenOne: "Bosque dos Vaga-lumes", gardenTwo: "Lago do Musgo", gardenThree: "Samambaia Arco-íris", gardenFour: "Caniço Prateado" },
    fr: { turnLeft: "Tourner l’anneau {n} à gauche", turnRight: "Tourner l’anneau {n} à droite", gardenOne: "Bosquet des Lucioles", gardenTwo: "Bassin de Mousse", gardenThree: "Fougère Arc-en-ciel", gardenFour: "Roseaux Argentés" },
    de: { turnLeft: "Ring {n} nach links drehen", turnRight: "Ring {n} nach rechts drehen", gardenOne: "Glühwürmchenhain", gardenTwo: "Mooslichtteich", gardenThree: "Regenbogenfarn", gardenFour: "Silberried" },
    it: { turnLeft: "Ruota l’anello {n} a sinistra", turnRight: "Ruota l’anello {n} a destra", gardenOne: "Boschetto delle Lucciole", gardenTwo: "Stagno del Muschio", gardenThree: "Felce Arcobaleno", gardenFour: "Canna d’Argento" },
    ru: { turnLeft: "Повернуть кольцо {n} влево", turnRight: "Повернуть кольцо {n} вправо", gardenOne: "Роща светлячков", gardenTwo: "Моховой пруд", gardenThree: "Радужный папоротник", gardenFour: "Серебряный камыш" },
    hi: { turnLeft: "रिंग {n} को बाईं ओर घुमाएँ", turnRight: "रिंग {n} को दाईं ओर घुमाएँ", gardenOne: "जुगनू उपवन", gardenTwo: "काई की झील", gardenThree: "इंद्रधनुषी फर्न", gardenFour: "चाँदी सरकंडा" },
    ar: { turnLeft: "أدر الحلقة {n} إلى اليسار", turnRight: "أدر الحلقة {n} إلى اليمين", gardenOne: "بستان اليراعات", gardenTwo: "بركة الضوء الطحلبي", gardenThree: "سرخس قوس قزح", gardenFour: "القصب الفضي" }
  };
  Object.entries(localizedGardenCopy).forEach(([localeKey, values]) => Object.assign(copy[localeKey], values));

  const localizedGardenClues = {
    en: { gardenOneClue: "Follow the warm firefly ring into the quiet centre.", gardenTwoClue: "Let the moss ring rest beneath the silver moon.", gardenThreeClue: "Bring the rainbow petals together for the last bloom.", gardenFourClue: "Set the silver reeds in a gentle moonlit line." },
    "zh-Hant": { gardenOneClue: "跟著溫暖的螢火環，走進安靜的中心。", gardenTwoClue: "讓苔蘚花環在銀色月光下休息。", gardenThreeClue: "把彩虹花瓣聚在一起，完成最後的綻放。", gardenFourClue: "把銀蘆排成溫柔的月光線條。" },
    "zh-Hans": { gardenOneClue: "跟随温暖的萤火环，走进安静的中心。", gardenTwoClue: "让苔藓花环在银色月光下歇息。", gardenThreeClue: "把彩虹花瓣聚在一起，完成最后的绽放。", gardenFourClue: "把银芦排成温柔的月光线条。" },
    ja: { gardenOneClue: "あたたかなホタルのリングを、静かな中心へ追いかけよう。", gardenTwoClue: "苔のリングを銀色の月の下で休ませよう。", gardenThreeClue: "虹色の花びらを集めて、最後の花を咲かせよう。", gardenFourClue: "銀のアシをやさしい月明かりの線に並べよう。" },
    ko: { gardenOneClue: "따뜻한 반딧불 링을 따라 고요한 중심으로 들어가세요.", gardenTwoClue: "은빛 달 아래 이끼 링을 쉬게 해 보세요.", gardenThreeClue: "무지개 꽃잎을 모아 마지막 꽃을 피워 보세요.", gardenFourClue: "은빛 갈대를 부드러운 달빛 선으로 놓아 보세요." },
    es: { gardenOneClue: "Sigue el anillo de luciérnagas hasta el centro tranquilo.", gardenTwoClue: "Deja que el anillo de musgo descanse bajo la luna plateada.", gardenThreeClue: "Reúne los pétalos arcoíris para el último brote.", gardenFourClue: "Coloca los juncos plateados en una suave línea lunar." },
    "pt-BR": { gardenOneClue: "Siga o anel quente de vaga-lumes até o centro silencioso.", gardenTwoClue: "Deixe o anel de musgo descansar sob a lua prateada.", gardenThreeClue: "Junte as pétalas arco-íris para a última florada.", gardenFourClue: "Alinhe os caniços prateados numa linha suave de luar." },
    fr: { gardenOneClue: "Suivez l’anneau chaleureux des lucioles jusqu’au centre paisible.", gardenTwoClue: "Laissez l’anneau de mousse reposer sous la lune argentée.", gardenThreeClue: "Rassemblez les pétales arc-en-ciel pour la dernière floraison.", gardenFourClue: "Alignez les roseaux argentés en une douce ligne de lune." },
    de: { gardenOneClue: "Folge dem warmen Glühwürmchenring in die stille Mitte.", gardenTwoClue: "Lass den Moosring unter dem silbernen Mond ruhen.", gardenThreeClue: "Führe die Regenbogenblüten zur letzten Blüte zusammen.", gardenFourClue: "Stelle das Silberried in eine sanfte Mondlinie." },
    it: { gardenOneClue: "Segui l’anello caldo delle lucciole fino al centro tranquillo.", gardenTwoClue: "Lascia riposare l’anello di muschio sotto la luna d’argento.", gardenThreeClue: "Riunisci i petali arcobaleno per l’ultima fioritura.", gardenFourClue: "Disponi la canna d’argento in una dolce linea lunare." },
    ru: { gardenOneClue: "Следуйте за тёплым кольцом светлячков к тихому центру.", gardenTwoClue: "Пусть моховое кольцо отдохнёт под серебряной луной.", gardenThreeClue: "Соберите радужные лепестки для последнего цветения.", gardenFourClue: "Выстройте серебряный камыш в мягкую лунную линию." },
    hi: { gardenOneClue: "गर्म जुगनू रिंग का पीछा करते हुए शांत केंद्र तक जाएँ।", gardenTwoClue: "चाँदी के चाँद के नीचे काई वाली रिंग को ठहरने दें।", gardenThreeClue: "आखिरी खिलने के लिए इंद्रधनुषी पंखुड़ियों को साथ लाएँ।", gardenFourClue: "चाँदी सरकंडों को चाँदनी की कोमल रेखा में सजाएँ।" },
    ar: { gardenOneClue: "اتبع حلقة اليراعات الدافئة إلى المركز الهادئ.", gardenTwoClue: "دع حلقة الطحلب تستريح تحت القمر الفضي.", gardenThreeClue: "اجمع بتلات قوس قزح من أجل الإزهار الأخير.", gardenFourClue: "رتّب القصب الفضي في خط قمري لطيف." }
  };
  Object.entries(localizedGardenClues).forEach(([localeKey, values]) => Object.assign(copy[localeKey], values));

  const localizedWrongTurnCopy = {
    "zh-Hant": "圖樣還沒醒來。換一層花環，或重設花園再試一次。",
    "zh-Hans": "图案还没有醒来。换一个花环，或重置花园再试一次。",
    ja: "模様はまだ目覚めていません。別のリングを回すか、庭をリセットしてみましょう。",
    ko: "무늬가 아직 깨어나지 않았어요. 다른 링을 돌리거나 정원을 초기화해 보세요.",
    es: "El patrón aún no despierta. Prueba otro anillo o reinicia el jardín.",
    "pt-BR": "O padrão ainda não despertou. Tente outro anel ou redefina o jardim.",
    fr: "Le motif n’est pas encore éveillé. Essayez un autre anneau ou réinitialisez le jardin.",
    de: "Das Muster ist noch nicht erwacht. Drehe einen anderen Ring oder setze den Garten zurück.",
    it: "Il motivo non si è ancora risvegliato. Prova un altro anello o reimposta il giardino.",
    ru: "Узор ещё не проснулся. Поверните другое кольцо или сбросьте сад.",
    hi: "पैटर्न अभी जागा नहीं है। कोई दूसरी रिंग घुमाएँ या बगीचा रीसेट करें।",
    ar: "لم يستيقظ النمط بعد. جرّب حلقة أخرى أو أعد ضبط الحديقة."
  };
  Object.entries(localizedWrongTurnCopy).forEach(([localeKey, value]) => { copy[localeKey].wrong = value; });

  const initialAlignmentCopy = {
    en: "Choose a ring to begin; rings marked ↻ still need turns.",
    "zh-Hant": "選一層花環開始；標示 ↻ 的花環還需要旋轉。",
    "zh-Hans": "选择一层花环开始；标有 ↻ 的花环还需要旋转。",
    ja: "リングを選んで開始。↻ のリングはまだ回転が必要です。",
    ko: "링을 골라 시작하세요. ↻ 표시가 있는 링은 더 돌려야 합니다.",
    es: "Elige un anillo para empezar; los anillos con ↻ aún necesitan giros.",
    "pt-BR": "Escolha um anel para começar; os anéis com ↻ ainda precisam de giros.",
    fr: "Choisissez un anneau pour commencer ; les anneaux marqués ↻ doivent encore tourner.",
    de: "Wähle einen Ring zum Starten; Ringe mit ↻ müssen noch gedreht werden.",
    it: "Scegli un anello per iniziare; gli anelli con ↻ devono ancora girare.",
    ru: "Выберите кольцо, чтобы начать; кольца с отметкой ↻ ещё нужно повернуть.",
    hi: "शुरू करने के लिए एक रिंग चुनें; ↻ वाले रिंग को अभी घुमाना है।",
    ar: "اختر حلقة للبدء؛ الحلقات التي تحمل ↻ تحتاج إلى دورات إضافية."
  };
  Object.entries(initialAlignmentCopy).forEach(([localeKey, value]) => { copy[localeKey].begin = value; });
  window.RING_GARDEN_COPY = copy;
})();
