(() => {
const keys=['prep','launch','waveReady','recall','refund','rally','rallyHint','buildHint','incomeHint','blocked','freeFox','unitCat','unitDog','nextWave','waveCount'];
const rows={
en:['Prepare your defence','Send wave','Wave cleared · prepare again','Recall','Recover {n} energy','Rally','Choose a lane to slow every enemy for 2 seconds.','Choose a guard, then a tile. Place at least one guard before starting.','Energy regenerates during combat. Recalling returns part of the remaining guard value.','Stone tile · cannot deploy here','Fox joins after Stage 5; existing purchases stay owned.','Lion archer','Turtle sentinel','Next wave','Wave {n}/{total}'],
'zh-Hant':['布防時間','迎戰','本波守住了，調整陣容再出發','撤回','回收 {n} 能量','集結','點選一路，讓該路所有敵人減速 2 秒。','先選守衛，再點格子。至少放置一名守衛後開始迎戰。','戰鬥中自動恢復能量；撤回守衛可按剩餘血量回收部分能量。','石塊地形，無法部署','通過第 5 關免費獲得狐狸；原有購買保留。','獅子弓手','龜甲衛士','下一波','第 {n}/{total} 波'],
'zh-Hans':['布防时间','迎战','本波守住了，调整阵容再出发','撤回','回收 {n} 能量','集结','点击一路，让该路所有敌人减速 2 秒。','先选守卫，再点格子。至少放置一名守卫后开始迎战。','战斗中自动恢复能量；撤回守卫可按剩余血量回收部分能量。','石块地形，无法部署','通过第 5 关免费获得狐狸；原有购买保留。','狮子弓手','龟甲卫士','下一波','第 {n}/{total} 波'],
ja:['防衛を準備','迎撃開始','ウェーブ突破・再配置しよう','撤退','エネルギー {n} を回収','号令','レーンを選び、敵全員を2秒間減速。','守衛を選んでマスに配置。1体以上置いてから開始。','戦闘中はエネルギーが回復。撤退時は残り体力に応じて一部を回収。','岩のマスには配置できません','ステージ5突破でキツネ加入。購入済みの権利は維持。','ライオン弓兵','カメ守衛','次の波','ウェーブ {n}/{total}'],
ko:['방어 준비','공격 시작','웨이브 방어 성공 · 재정비','회수','에너지 {n} 회수','집결','한 경로를 선택해 모든 적을 2초간 느리게 합니다.','수호자를 고른 뒤 칸에 배치하세요. 한 명 이상 배치한 뒤 시작하세요.','전투 중 에너지가 회복됩니다. 회수하면 남은 체력에 따라 일부를 돌려받습니다.','바위에는 배치할 수 없습니다','5단계 완료 시 여우 합류. 기존 구매는 유지됩니다.','사자 궁수','거북 수호자','다음 웨이브','웨이브 {n}/{total}'],
es:['Prepara la defensa','Enviar oleada','Oleada superada · reorganiza','Retirar','Recuperar {n} de energía','Reagrupar','Elige una fila: ralentiza a todos sus enemigos durante 2 segundos.','Elige un guardián y una casilla. Coloca al menos uno para comenzar.','La energía se regenera en combate. Retirar devuelve una parte según la salud restante.','Roca: no se puede desplegar','El zorro se une tras el nivel 5. Las compras previas se conservan.','León arquero','Tortuga centinela','Siguiente oleada','Oleada {n}/{total}'],
'pt-BR':['Prepare a defesa','Iniciar onda','Onda vencida · reorganize','Recolher','Recuperar {n} de energia','Reagrupar','Escolha uma faixa: todos os inimigos ficam lentos por 2 segundos.','Escolha um guarda e uma casa. Posicione ao menos um antes de iniciar.','A energia regenera em combate. Recolher devolve parte conforme a vida restante.','Pedra: não é possível posicionar','A raposa chega após a fase 5. Compras anteriores são mantidas.','Leão arqueiro','Tartaruga sentinela','Próxima onda','Onda {n}/{total}'],
fr:['Préparez la défense','Lancer la vague','Vague repoussée · réorganisez','Retirer','Récupérer {n} énergie','Ralliement','Choisissez une ligne : ses ennemis sont ralentis pendant 2 secondes.','Choisissez un gardien puis une case. Placez-en au moins un avant de lancer.','L’énergie revient au combat. Retirer rend une partie selon la vie restante.','Rocher : placement impossible','Le renard rejoint après le niveau 5. Les achats restent acquis.','Lion archer','Tortue sentinelle','Vague suivante','Vague {n}/{total}'],
de:['Verteidigung vorbereiten','Welle starten','Welle abgewehrt · neu aufstellen','Zurückrufen','{n} Energie zurück','Sammeln','Wähle eine Reihe: Alle Gegner werden 2 Sekunden verlangsamt.','Wähle einen Wächter und ein Feld. Stelle vor dem Start mindestens einen auf.','Energie regeneriert im Kampf. Rückruf erstattet einen Teil je nach Restleben.','Felsfeld: kein Aufstellen','Der Fuchs kommt nach Stufe 5. Vorherige Käufe bleiben erhalten.','Löwenbogenschütze','Schildkrötenwache','Nächste Welle','Welle {n}/{total}'],
it:['Prepara la difesa','Avvia ondata','Ondata respinta · riorganizza','Ritira','Recupera {n} energia','Raduno','Scegli una corsia: rallenta tutti i nemici per 2 secondi.','Scegli una guardia e una casella. Schierane almeno una prima di iniziare.','L’energia si rigenera in battaglia. Il ritiro ne restituisce parte in base alla salute.','Roccia: schieramento vietato','La volpe arriva dopo il livello 5. Gli acquisti restano validi.','Leone arciere','Tartaruga sentinella','Prossima ondata','Ondata {n}/{total}'],
ru:['Подготовьте оборону','Начать волну','Волна отбита · перестройтесь','Отозвать','Вернуть {n} энергии','Сбор','Выберите ряд: все враги замедлятся на 2 секунды.','Выберите стража и клетку. Разместите хотя бы одного перед началом.','Энергия восстанавливается в бою. Отзыв возвращает часть по оставшемуся здоровью.','Камень: размещение запрещено','Лис присоединится после этапа 5. Покупки сохраняются.','Лев-лучник','Черепаха-страж','Следующая волна','Волна {n}/{total}'],
hi:['रक्षा तैयार करें','लहर शुरू करें','लहर रोकी · फिर तैयारी करें','वापस बुलाएँ','{n} ऊर्जा वापस','एकजुट','एक पंक्ति चुनें: सभी शत्रु 2 सेकंड धीमे होंगे।','रक्षक चुनें और खाने पर रखें। शुरू करने से पहले कम से कम एक रखें।','लड़ाई में ऊर्जा लौटती है। वापस बुलाने पर शेष स्वास्थ्य के अनुसार कुछ ऊर्जा मिलती है।','पत्थर पर तैनाती नहीं','चरण 5 के बाद लोमड़ी मिलेगी। पिछली खरीद बनी रहती है।','सिंह धनुर्धर','कछुआ प्रहरी','अगली लहर','लहर {n}/{total}'],
ar:['جهّز الدفاع','ابدأ الموجة','صددت الموجة · أعد التنظيم','استدعاء','استرجاع {n} طاقة','تجمّع','اختر مساراً لإبطاء كل أعدائه لمدة ثانيتين.','اختر حارساً ثم خانة. ضع حارساً واحداً على الأقل قبل البدء.','تتجدد الطاقة أثناء القتال. يعيد الاستدعاء جزءاً حسب الصحة المتبقية.','صخرة: لا يمكن النشر هنا','ينضم الثعلب بعد المرحلة 5. تبقى المشتريات السابقة محفوظة.','الأسد الرامي','السلحفاة الحارسة','الموجة التالية','الموجة {n}/{total}']};
window.GUARD_YARD_UPGRADE_COPY=Object.fromEntries(Object.entries(rows).map(([locale,values])=>[locale,Object.fromEntries(keys.map((k,i)=>[k,values[i]]))]));
const capacity={en:'Up to 12 guards. Recall one to change your formation.','zh-Hant':'最多 12 名守衛；可撤回一名，重新調整陣容。','zh-Hans':'最多 12 名守卫；可撤回一名，重新调整阵容。',ja:'守衛は最大12体。撤退させると編成を変えられます。',ko:'수호자는 최대 12명입니다. 회수하고 진형을 바꾸세요.',es:'Máximo 12 guardianes. Retira uno para cambiar la formación.','pt-BR':'Até 12 guardas. Recolha um para mudar a formação.',fr:'12 gardiens maximum. Retirez-en un pour changer la formation.',de:'Höchstens 12 Wächter. Rufe einen zurück, um die Formation zu ändern.',it:'Massimo 12 guardie. Ritirane una per cambiare formazione.',ru:'Не более 12 стражей. Отзовите одного, чтобы изменить строй.',hi:'अधिकतम 12 रक्षक। गठन बदलने के लिए एक को वापस बुलाएँ।',ar:'الحد الأقصى 12 حارساً. استدعِ أحدهم لتغيير التشكيل.'};
for(const [code,value] of Object.entries(window.GUARD_YARD_UPGRADE_COPY)){value.capacity=capacity[code];value.shopHint=value.freeFox;}
})();
