(() => {
  "use strict";
  const locales = window.ANIMAL_CONSTELLATION_KEEPER_LOCALES || {};
  const maps = [
    { nameKey: "map1", introKey: "map1Intro", clues: ["clue1a", "clue1b"], hint: "clue1a", options: [
      { id: "fox-centre", labelKey: "map1A", stars: [{ animal: "owl", row: 0, col: 1 }, { animal: "fox", row: 1, col: 1 }, { animal: "rabbit", row: 1, col: 2 }] },
      { id: "rabbit-centre", labelKey: "map1B", stars: [{ animal: "owl", row: 0, col: 1 }, { animal: "rabbit", row: 1, col: 1 }, { animal: "fox", row: 1, col: 2 }] },
      { id: "owl-centre", labelKey: "map1C", stars: [{ animal: "fox", row: 0, col: 1 }, { animal: "owl", row: 1, col: 1 }, { animal: "rabbit", row: 2, col: 1 }] }
    ] },
    { nameKey: "map2", introKey: "map2Intro", clues: ["clue2a", "clue2b"], hint: "clue2b", options: [
      { id: "otter-centre", labelKey: "map2A", stars: [{ animal: "deer", row: 1, col: 0 }, { animal: "otter", row: 1, col: 1 }, { animal: "hare", row: 1, col: 2 }] },
      { id: "deer-centre", labelKey: "map2B", stars: [{ animal: "otter", row: 1, col: 0 }, { animal: "deer", row: 1, col: 1 }, { animal: "hare", row: 1, col: 2 }] },
      { id: "hare-centre", labelKey: "map2C", stars: [{ animal: "deer", row: 1, col: 0 }, { animal: "hare", row: 1, col: 1 }, { animal: "otter", row: 1, col: 2 }] }
    ] },
    { nameKey: "map3", introKey: "map3Intro", clues: ["clue3a", "clue3b"], hint: "clue3a", options: [
      { id: "bear-centre", labelKey: "map3A", stars: [{ animal: "owl", row: 0, col: 1 }, { animal: "bear", row: 1, col: 1 }, { animal: "mole", row: 2, col: 1 }] },
      { id: "owl-centre-final", labelKey: "map3B", stars: [{ animal: "bear", row: 0, col: 1 }, { animal: "owl", row: 1, col: 1 }, { animal: "mole", row: 2, col: 1 }] },
      { id: "mole-centre", labelKey: "map3C", stars: [{ animal: "owl", row: 0, col: 1 }, { animal: "mole", row: 1, col: 1 }, { animal: "bear", row: 2, col: 1 }] }
    ] },
    { nameKey: "map4", introKey: "map4Intro", clues: ["clue4a", "clue4b"], hint: "clue4a", options: [
      { id: "rabbit-west", labelKey: "map4A", stars: [{ animal: "rabbit", row: 1, col: 0 }, { animal: "owl", row: 1, col: 1 }, { animal: "bear", row: 2, col: 0 }] },
      { id: "owl-west", labelKey: "map4B", stars: [{ animal: "owl", row: 1, col: 0 }, { animal: "rabbit", row: 1, col: 1 }, { animal: "bear", row: 2, col: 0 }] },
      { id: "bear-west", labelKey: "map4C", stars: [{ animal: "rabbit", row: 1, col: 0 }, { animal: "bear", row: 1, col: 1 }, { animal: "owl", row: 2, col: 0 }] }
    ] }
  ];
  const correctIds = ["fox-centre", "otter-centre", "bear-centre", "rabbit-west"];
  const state = { locale: "en", map: 0, completed: 0, selected: "", checks: 0, sessionChecks: 0, screen: "main", sound: true };
  const $ = (id) => document.getElementById(id);
  document.querySelector(".battle-canvas")?.setAttribute("data-wp-battle-canvas-root", "");
  const t = (key, vars = {}) => { const table = locales[state.locale] || locales.en || {}; let value = table[key] || locales.en?.[key] || key; Object.entries(vars).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); }); return value; };
  const track = (event, detail = {}) => { window.dispatchEvent(new CustomEvent("weightplay:analytics", { detail: { game: "animal-constellation-keeper", game_version: "v4", interface_version: 6, event, ...detail } })); };
  const tone = (frequency) => { if (!state.sound) return; try { const AudioContextClass = window.AudioContext || window.webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0.035, context.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.12); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.12); oscillator.addEventListener("ended", () => context.close(), { once: true }); } catch (_) {} };
  const show = (screen) => { state.screen = screen; document.querySelectorAll("section[data-screen]").forEach((node) => { node.hidden = node.dataset.screen !== screen; }); document.body.dataset.screen = screen; };
  const readBest = () => { try { const value = Number(localStorage.getItem("weightplay-animal-constellation-keeper-best-v4")); return Number.isFinite(value) && value > 0 ? value : null; } catch (_) { return null; } };
  const saveBest = () => { try { const old = readBest(); if (!old || state.sessionChecks < old) localStorage.setItem("weightplay-animal-constellation-keeper-best-v4", String(state.sessionChecks)); } catch (_) {} };
  const announce = (key, vars = {}, kind = "") => { const node = $("battleStatus"); node.textContent = t(key, vars); node.dataset.kind = kind; };
  const animalAtlas = { fox: "fox", owl: "owl", rabbit: "rabbit", deer: "deer", otter: "bear", hare: "rabbit", bear: "bear", mole: "owl" };
  const renderStages = () => { $("stageList").replaceChildren(...maps.map((map, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "stage-card"; button.setAttribute("role", "listitem"); button.innerHTML = `<strong>${t("round", { n: index + 1, total: maps.length })}</strong><span>${t(map.nameKey)}</span><small>${index < state.completed ? t("complete") : t("open")}</small>`; button.addEventListener("click", () => startMap(index)); return button; })); };
  const renderBoard = (option) => { const board = document.createElement("div"); board.className = "star-board"; for (let row = 0; row < 3; row += 1) for (let col = 0; col < 3; col += 1) { const cell = document.createElement("div"); cell.className = "star-cell"; const star = option.stars.find((item) => item.row === row && item.col === col); if (star) { cell.classList.add("is-star"); const glyph = document.createElement("span"); glyph.className = "star-glyph"; glyph.dataset.animal = animalAtlas[star.animal] || "owl"; glyph.setAttribute("aria-hidden", "true"); cell.append(glyph); } board.append(cell); } return board; };
  const renderBattle = () => { const current = maps[state.map]; $("mapName").textContent = t(current.nameKey); $("mapLabel").textContent = t("round", { n: state.map + 1, total: maps.length }); $("mapIntro").textContent = t(current.introKey); $("ruleOne").textContent = `1. ${t(current.clues[0])}`; $("ruleTwo").textContent = `2. ${t(current.clues[1])}`; $("checkCount").textContent = `${t("best")}: ${state.sessionChecks}`; const grid = $("choiceGrid"); grid.replaceChildren(...current.options.map((option) => { const button = document.createElement("button"); button.type = "button"; button.className = "constellation-choice"; button.dataset.optionId = option.id; button.setAttribute("aria-pressed", String(state.selected === option.id)); button.setAttribute("aria-label", t("mapOption", { label: t(option.labelKey) })); const label = document.createElement("span"); label.className = "choice-label"; label.textContent = t(option.labelKey); button.append(label, renderBoard(option)); button.addEventListener("click", () => chooseOption(option.id)); if (state.selected === option.id && button.dataset.state !== "wrong") button.dataset.state = "selected"; return button; })); $("checkBtn").disabled = !state.selected; };
  const renderResult = () => { const complete = state.completed >= maps.length; $("resultTitle").textContent = complete ? t("resultTitle") : t("resultPartial"); $("resultText").textContent = t("resultText", { count: state.completed, total: maps.length, checks: state.sessionChecks }); $("resultPrimaryBtn").textContent = complete ? t("map") : t("next"); $("resultPrimaryBtn").onclick = complete ? () => { show("stage"); renderStages(); } : () => startMap(state.map + 1); $("resultMapBtn").hidden = complete; };
  const openStage = () => { show("stage"); renderStages(); };
  const startMap = (index) => { state.map = Math.max(0, Math.min(maps.length - 1, index)); state.selected = ""; if (index === 0) { state.checks = 0; state.sessionChecks = 0; } show("battle"); renderBattle(); announce("waiting"); track("map_start", { map: state.map + 1 }); };
  const chooseOption = (id) => { state.selected = id; renderBattle(); announce("selected"); tone(540); track("constellation_select", { map: state.map + 1 }); };
  const clearChoice = () => { state.selected = ""; renderBattle(); announce("waiting"); track("constellation_clear", { map: state.map + 1 }); };
  const checkChoice = () => { if (!state.selected) return; state.checks += 1; state.sessionChecks += 1; const current = maps[state.map]; if (state.selected !== correctIds[state.map]) { const choice = current.options.find((option) => option.id === state.selected); const hint = choice ? (choice.id === "rabbit-centre" ? t("clue1b") : choice.id === "deer-centre" ? t("clue2a") : choice.id === "mole-centre" ? t("clue3b") : t(current.hint)) : t(current.hint); announce("wrong", { hint }, "wrong"); const wrongButton = document.querySelector(`[data-option-id="${state.selected}"]`); if (wrongButton) wrongButton.dataset.state = "wrong"; tone(220); track("map_check", { map: state.map + 1, result: "wrong" }); return; } state.completed = Math.max(state.completed, state.map + 1); announce("correct", {}, "correct"); tone(760); track("map_check", { map: state.map + 1, result: "correct" }); if (state.completed >= maps.length) { saveBest(); $("bestValue").textContent = readBest() || t("noBest"); } show("result"); renderResult(); };
  const applyLocale = () => { document.documentElement.lang = state.locale; document.documentElement.dir = state.locale === "ar" ? "rtl" : "ltr"; document.querySelectorAll("[data-copy]").forEach((node) => { node.textContent = t(node.dataset.copy); }); document.querySelectorAll("[data-copy-aria]").forEach((node) => node.setAttribute("aria-label", t(node.dataset.copyAria))); $("localeSelect").value = state.locale; $("localeSelect").setAttribute("aria-label", t("language")); $("soundState").textContent = state.sound ? t("on") : t("off"); $("soundBtn").setAttribute("aria-pressed", String(state.sound)); $("mainProgress").textContent = `${t("maps")}: ${state.completed} / ${maps.length}`; $("bestValue").textContent = readBest() || t("noBest"); if (state.screen === "stage") renderStages(); if (state.screen === "battle") renderBattle(); if (state.screen === "result") renderResult(); };
  const installSoundBridge = () => { if (!window.WonderSound) window.WonderSound = { isMuted: () => !state.sound, setMuted: (muted) => { state.sound = !muted; applyLocale(); track("sound", { enabled: state.sound }); window.dispatchEvent(new CustomEvent("wonder:audio-volume-change")); } }; if (typeof window.WonderSound.isMuted === "function") state.sound = !window.WonderSound.isMuted(); window.addEventListener("wonder:audio-volume-change", () => { if (typeof window.WonderSound?.isMuted === "function") { state.sound = !window.WonderSound.isMuted(); applyLocale(); } }); };
  const settingsBtn = $("settingsBtn"); const soundBtn = $("soundBtn"); const battleUtility = $("battleSettingsBtn"); if (battleUtility) { battleUtility.textContent = "?"; battleUtility.setAttribute("aria-label", "How to play"); battleUtility.title = "How to play"; } $("startBtn").addEventListener("click", openStage); $("mapBtn").addEventListener("click", openStage); $("stageBackBtn").addEventListener("click", () => { show("main"); applyLocale(); }); $("battleBackBtn").addEventListener("click", () => { openStage(); }); $("resultMapBtn").addEventListener("click", openStage); $("resultReplayBtn").addEventListener("click", () => startMap(state.map)); $("resultHomeBtn").addEventListener("click", () => show("main")); $("checkBtn").addEventListener("click", checkChoice); $("clearBtn").addEventListener("click", clearChoice); settingsBtn?.addEventListener("click", () => { $("settingsPanel").hidden = !$("settingsPanel").hidden; }); soundBtn?.addEventListener("click", () => { state.sound = !state.sound; applyLocale(); }); battleUtility?.addEventListener("click", () => { const rules = document.querySelector(".rule-card"); rules?.setAttribute("tabindex", "-1"); rules?.focus({ preventScroll: true }); announce("waiting"); }); $("localeSelect").addEventListener("change", (event) => { state.locale = locales[event.target.value] ? event.target.value : "en"; try { localStorage.setItem("weightplayLocale", state.locale); } catch (_) {} applyLocale(); });
  const routeLocale = document.documentElement.lang; if (routeLocale && locales[routeLocale]) state.locale = routeLocale; try { const saved = localStorage.getItem("weightplayLocale"); if (saved && locales[saved]) state.locale = saved; } catch (_) {} installSoundBridge(); applyLocale(); show("main"); window.setTimeout(() => $("loadingScreen").classList.add("is-ready"), 0); window.__ANIMAL_CONSTELLATION_KEEPER_TEST__ = { maps, startMap, chooseOption, checkChoice, clearChoice, getState: () => ({ ...state }) };
})();
