(() => {
  "use strict";
  const locales = window.ANIMAL_BLOOM_MIXER_LOCALES || {};
  const recipes = [
    { name: "recipeOne", note: "recipeOneNote", solution: ["mint", "amber", "violet"] },
    { name: "recipeTwo", note: "recipeTwoNote", solution: ["coral", "mint", "amber"] },
    { name: "recipeThree", note: "recipeThreeNote", solution: ["violet", "coral", "mint"] }
  ];
  const petals = ["amber", "mint", "coral", "violet", "gold"];
  const state = { locale: "en", recipe: 0, selected: [], completed: 0, sessionPicks: 0, screen: "main", sound: true };
  const $ = (id) => document.getElementById(id);
  const t = (key, vars = {}) => { const table = locales[state.locale] || locales.en || {}; let value = table[key] || locales.en?.[key] || key; Object.entries(vars).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); }); return value; };
  const show = (screen) => { state.screen = screen; document.querySelectorAll("section[data-screen]").forEach((node) => { node.hidden = node.dataset.screen !== screen; }); document.body.dataset.screen = screen; };
  const readBest = () => { try { const value = Number(localStorage.getItem("weightplay-animal-bloom-mixer-best-v1")); return Number.isFinite(value) && value > 0 ? value : null; } catch (_) { return null; } };
  const saveBest = () => { try { const old = readBest(); if (!old || state.sessionPicks < old) localStorage.setItem("weightplay-animal-bloom-mixer-best-v1", String(state.sessionPicks)); } catch (_) {} };
  const track = (event, detail = {}) => { window.dispatchEvent(new CustomEvent("weightplay:analytics", { detail: { game: "animal-bloom-mixer", event, ...detail } })); };
  const tone = (frequency) => { if (!state.sound) return; try { const AudioContextClass = window.AudioContext || window.webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0.03, context.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.12); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.12); oscillator.addEventListener("ended", () => context.close(), { once: true }); } catch (_) {} };
  const announce = (key, vars = {}, kind = "") => { const node = $("battle-status"); node.textContent = t(key, vars); node.dataset.kind = kind; };
  const renderStages = () => { $("recipe-list").replaceChildren(...recipes.map((recipe, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "recipe-card"; button.setAttribute("aria-label", t("open") + ": " + t(recipe.name)); const number = document.createElement("span"); number.className = "recipe-number"; number.textContent = String(index + 1); const copy = document.createElement("span"); copy.className = "recipe-copy"; copy.innerHTML = `<strong>${t("recipeLabel", { n: index + 1 })} · ${t(recipe.name)}</strong><small>${index < state.completed ? t("complete") : t("open")}</small>`; const arrow = document.createElement("span"); arrow.className = "recipe-arrow"; arrow.textContent = "→"; button.append(number, copy, arrow); button.addEventListener("click", () => startRecipe(index)); return button; })); };
  const renderBattle = () => { const recipe = recipes[state.recipe]; $("recipe-title").textContent = t(recipe.name); $("recipe-note").textContent = t(recipe.note); $("pick-count").textContent = String(state.selected.length); const basket = $("basket"); basket.replaceChildren(...state.selected.map((petal) => { const chip = document.createElement("span"); chip.className = "basket-chip"; chip.textContent = t(petal); return chip; })); const grid = $("petal-grid"); grid.replaceChildren(...petals.map((petal) => { const button = document.createElement("button"); button.type = "button"; button.className = "petal-button"; button.setAttribute("aria-pressed", String(state.selected.includes(petal))); button.setAttribute("aria-label", t("add", { name: t(petal) })); const mark = document.createElement("span"); mark.className = `petal-mark ${petal}`; mark.textContent = petal === "amber" ? "✦" : petal === "mint" ? "✿" : petal === "coral" ? "❋" : petal === "violet" ? "✧" : "☀"; const label = document.createElement("span"); label.textContent = t(petal); button.append(mark, label); button.addEventListener("click", () => choosePetal(petal)); return button; })); $("check-button").disabled = state.selected.length !== 3; };
  const renderResult = () => { const done = state.completed >= recipes.length; $("result-title").textContent = done ? t("resultTitle") : t("resultPartial"); $("result-copy").textContent = done ? t("finalCopy") : t("resultCopy", { picks: state.sessionPicks }); $("result-picks").textContent = String(state.sessionPicks); $("result-best").textContent = readBest() || t("noBest"); $("result-status").textContent = t("correct"); $("next-button").textContent = done ? t("backToRecipes") : t("next"); $("next-button").onclick = done ? () => { show("stage"); renderStages(); } : () => startRecipe(state.recipe + 1); };
  const startRecipe = (index) => { state.recipe = Math.max(0, Math.min(recipes.length - 1, index)); state.selected = []; if (index === 0) state.sessionPicks = 0; $("battle-panel").hidden = false; $("result-panel").hidden = true; show("battle"); renderBattle(); announce("begin"); track("recipe_start", { recipe: state.recipe + 1 }); };
  const choosePetal = (petal) => { if (state.selected.includes(petal)) { state.selected = state.selected.filter((item) => item !== petal); announce("begin"); renderBattle(); track("petal_remove", { petal }); return; } if (state.selected.length >= 3) { announce("full", {}, "wrong"); return; } state.selected = [...state.selected, petal]; state.sessionPicks += 1; renderBattle(); announce("selected", { name: t(petal) }); tone(560); track("petal_select", { petal, recipe: state.recipe + 1 }); };
  const clearBasket = () => { state.selected = []; renderBattle(); announce("begin"); track("basket_clear", { recipe: state.recipe + 1 }); };
  const checkRecipe = () => { if (state.selected.length !== 3) return; const expected = [...recipes[state.recipe].solution].sort(); const actual = [...state.selected].sort(); if (JSON.stringify(expected) !== JSON.stringify(actual)) { announce("wrong", {}, "wrong"); tone(220); track("recipe_check", { recipe: state.recipe + 1, result: "wrong" }); return; } state.completed = Math.max(state.completed, state.recipe + 1); track("recipe_check", { recipe: state.recipe + 1, result: "correct" }); tone(760); if (state.completed >= recipes.length) saveBest(); $("battle-panel").hidden = true; $("result-panel").hidden = false; renderResult(); };
  const applyLocale = () => { document.documentElement.lang = state.locale; document.documentElement.dir = state.locale === "ar" ? "rtl" : "ltr"; document.querySelectorAll("[data-copy]").forEach((node) => { node.textContent = t(node.dataset.copy); }); document.querySelectorAll("[data-copy-aria]").forEach((node) => node.setAttribute("aria-label", t(node.dataset.copyAria))); $("locale-select").value = state.locale; $("locale-select").setAttribute("aria-label", t("language")); $("sound-toggle").textContent = state.sound ? t("soundOn") : t("soundOff"); $("sound-toggle").setAttribute("aria-pressed", String(state.sound)); if (state.screen === "stage") renderStages(); if (state.screen === "battle") renderBattle(); if (state.screen === "battle" && !$("battle-panel").hidden) announce("begin"); if (state.screen === "battle" && !$("result-panel").hidden) renderResult(); };
  const openSettings = () => { const dialog = $("settings-dialog"); if (typeof dialog.showModal === "function") dialog.showModal(); else dialog.setAttribute("open", ""); };
  ["main-settings", "stage-settings", "battle-settings"].forEach((id) => $(id).addEventListener("click", openSettings));
  $("start-button").addEventListener("click", () => startRecipe(0)); $("stage-back").addEventListener("click", () => show("main")); $("battle-back").addEventListener("click", () => { $("battle-panel").hidden = false; $("result-panel").hidden = true; show("stage"); renderStages(); }); $("result-stage").addEventListener("click", () => { $("battle-panel").hidden = false; $("result-panel").hidden = true; show("stage"); renderStages(); }); $("check-button").addEventListener("click", checkRecipe); $("clear-button").addEventListener("click", clearBasket); $("sound-toggle").addEventListener("click", () => { state.sound = !state.sound; applyLocale(); }); $("locale-select").addEventListener("change", (event) => { state.locale = locales[event.target.value] ? event.target.value : "en"; try { localStorage.setItem("weightplayLocale", state.locale); } catch (_) {} applyLocale(); });
  try { const saved = localStorage.getItem("weightplayLocale"); if (saved && locales[saved]) state.locale = saved; } catch (_) {}
  applyLocale(); show("main"); window.setTimeout(() => $("loading-screen").classList.add("is-ready"), 0); window.__ANIMAL_BLOOM_MIXER_TEST__ = { recipes, startRecipe, choosePetal, checkRecipe, clearBasket, getState: () => ({ ...state, selected: [...state.selected] }) };
})();
