(function(){"use strict";
  const dict=window.CANOPY_COMPASS_LOCALES||{}; const locales=["en","zh-Hant","zh-Hans","ja","ko","es","pt-BR","fr","de","it","ru","hi","ar"];
  const rounds=[{hint:"stageHint1",clue:"clue1",target:1},{hint:"stageHint2",clue:"clue2",target:2},{hint:"stageHint3",clue:"clue3",target:3}];
  const names=["north","east","south","west"]; const state={locale:"en",screen:"main",round:0,direction:0,turns:0,completed:[],sound:true}; const $=id=>document.getElementById(id);
  const get=(k,f="")=>{try{return localStorage.getItem(k)||f}catch(_){return f}}; const set=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};
  const t=(k,v={})=>{let s=(dict[state.locale]||dict.en||{})[k]||(dict.en||{})[k]||k; Object.entries(v).forEach(([a,b])=>s=s.replace(new RegExp("\\{"+a+"\\}","g"),String(b))); return s};
  const showToast=m=>{$("toast").textContent=m;$('toast').classList.add('visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('toast').classList.remove('visible'),1600)};
  function applyText(){document.querySelectorAll('[data-copy]').forEach(n=>n.textContent=t(n.dataset.copy));document.querySelectorAll('[data-copy-aria-label]').forEach(n=>n.setAttribute('aria-label',t(n.dataset.copyAriaLabel)));document.documentElement.lang=state.locale;document.documentElement.dir=(dict[state.locale]||{}).direction||'ltr';$('progress').textContent=t('progress',{count:state.completed.length});$('soundBtn').textContent=state.sound?t('soundOn')||'Sound: on':'Sound: off';$('battleSound').setAttribute('aria-label',state.sound?'Sound on':'Sound off'); if(state.screen==='stage')renderStages(); if(state.screen==='battle')renderBattle()}
  function screen(name){state.screen=name;document.body.dataset.screen=name;['main','stage','battle'].forEach(n=>$(n+'Screen').hidden=n!==name);$('settings').hidden=true;if(name==='main')applyText();if(name==='stage')renderStages();if(name==='battle')renderBattle();window.scrollTo(0,0)}
  function renderStages(){ $('stageList').innerHTML=rounds.map((r,i)=>`<button class="stage-card${state.completed.includes(i)?' done':''}" type="button" data-stage="${i}"${i===0||state.completed.includes(i-1)?'':' disabled'}><span class="num">${t('round',{number:i+1,total:3})}</span><strong>${t(r.hint)}</strong><span>${t(r.hint)}</span><b>${state.completed.includes(i)?t('complete'):i===0||state.completed.includes(i-1)?t('readyStage'):'—'}</b></button>`).join('');$('stageList').querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>startRound(Number(b.dataset.stage)))) }
  function renderRoundButtons(){const rack=$('directionRack');rack.replaceChildren();names.forEach((name,i)=>{const b=document.createElement('button');b.className='direction'+(state.direction===i?' active':'');b.type='button';b.textContent=t(name);b.setAttribute('aria-pressed',String(state.direction===i));b.addEventListener('click',()=>{state.direction=i;state.turns++;renderBattle();$('status').textContent=t('changed',{direction:t(name)})});rack.append(b)})}
  function renderBattle(){const r=rounds[state.round];$('roundTitle').textContent=t('round',{number:state.round+1,total:3});$('hint').textContent=t(r.hint);$('badge').textContent=`${state.completed.length}/3`;$('clueText').textContent=t(r.clue);$('compass').className=`compass direction-${state.direction}`;$('facing').textContent=t('facing',{direction:t(names[state.direction])});renderRoundButtons();$('result').hidden=true;$('checkBtn').disabled=false;$('resetBtn').disabled=false}
  function startRound(i){state.round=i;state.direction=0;state.turns=0;screen('battle');$('status').textContent=t('ready')}
  function check(){const r=rounds[state.round];if(state.direction!==r.target){$('status').textContent=t('wrong');return}state.completed=state.completed.includes(state.round)?state.completed:[...state.completed,state.round];$('progress').textContent=t('progress',{count:state.completed.length});$('status').textContent=t('correct');$('checkBtn').disabled=true;$('resetBtn').disabled=true;const final=state.round===2;const key='weightplay-animal-canopy-compass-best';const old=Number(get(key,'0'));if(final&&(!old||state.turns<old))set(key,String(state.turns));$('resultTitle').textContent=t(final?'finishTitle':'resultTitle');$('resultText').textContent=t(final?'finishText':'resultText');$('stats').textContent=t('stats',{turns:state.turns,best:final?Math.min(state.turns,old||state.turns):old||t('noBest')});$('resultPrimary').textContent=t(final?'replay':'next');$('resultPrimary').onclick=()=>final?startRound(0):startRound(state.round+1);$('result').hidden=false}
  function bind(){ $('startBtn').addEventListener('click',()=>startRound(0));$('mapBtn').addEventListener('click',()=>screen('stage'));$('stageBack').addEventListener('click',()=>screen('main'));$('stageHelp').addEventListener('click',()=>showToast(t('mapIntro')));$('battleBack').addEventListener('click',()=>screen('stage'));$('checkBtn').addEventListener('click',check);$('resetBtn').addEventListener('click',()=>{state.direction=0;state.turns=0;renderBattle();$('status').textContent=t('ready')});$('resultMap').addEventListener('click',()=>screen('stage'));$('resultHome').addEventListener('click',()=>screen('main'));$('settingsBtn').addEventListener('click',()=>{$('settings').hidden=!$('settings').hidden;$('settingsBtn').setAttribute('aria-expanded',String(!$('settings').hidden))});$('closeSettings').addEventListener('click',()=>{$('settings').hidden=true});[$('soundBtn'),$('battleSound')].forEach(b=>b.addEventListener('click',()=>{state.sound=!state.sound;set('weightplay-canopy-compass-sound',state.sound?'on':'off');applyText()}));document.addEventListener('keydown',e=>{if(state.screen!=='battle'||!$('result').hidden)return;if((e.key==='Enter'||e.key===' ')&&document.activeElement===$('compass')){e.preventDefault();check();return}const map={ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3};if(!(e.key in map))return;e.preventDefault();state.direction=map[e.key];state.turns++;renderBattle();$('status').textContent=t('changed',{direction:t(names[state.direction])})});$('localeSelect').addEventListener('change',e=>{state.locale=e.target.value;set('weightplay-canopy-compass-locale',state.locale);applyText()});const sel=$('localeSelect');locales.forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=(dict.en.languageNames||{})[k]||k;sel.append(o)});sel.value=state.locale}
  state.sound=get('weightplay-canopy-compass-sound','on')!=='off';state.locale=locales.includes(get('weightplay-canopy-compass-locale','en'))?get('weightplay-canopy-compass-locale','en'):'en';bind();applyText();screen('main');
}());
