(()=>{"use strict";
const $=id=>document.getElementById(id),KEYS=["title","language","genre","pitch","campaign","endless","preview","guideTitle","howTitle","how1","how2","how3","mechanicsTitle","mechanics","chooseStage","stageHint","enter","score","sets","helpText","continue","leaveTitle","leaveText","stageMap","clear","next","retry","invalid","placed","lineClear","gameOver","limitFail","result","lines","dirt","iceStone","colors","gemsLocks","mixed","endlessKind"];
const P={
en:["Block Blast","Language","8×8 BLOCK PUZZLE","Place all three shapes and clear complete rows or columns.","Campaign","Endless","OWNER PREVIEW · RULE-CHECK BUILD","Make space for the next three shapes.","How to play","Drag one of three fixed shapes onto the 8×8 board.","A lifted translucent preview shows a legal landing.","Complete a row or column to clear it immediately.","Campaign rules","Dirt, ice, stone, gems, locks, colors and set limits create thirty distinct missions.","Choose a Stage","Select an unlocked mission.","Enter Stage","Score","Sets","Shapes cannot move or rotate after placement. Complete lines clear immediately.","Continue","Leave this run?","Continue keeps the exact board.","Stage Map","Mission Complete!","Next Stage","Play Again","That shape does not fit there.","Shape placed.","{n} line cleared!","No remaining shape can fit.","The set limit was reached.","Score {score} · {lines} lines · {sets} sets","LINES","DIRT","ICE + STONE","COLOR","GEMS + LOCKS","MIXED","ENDLESS"],
"zh-Hant":["方塊爆破","語言","8×8 方塊益智","放完每組三個形狀，填滿橫排或直列立即消除。","關卡模式","無限模式","擁有者預覽 · 規則檢查版本","為下一組三個形狀保留空間。","玩法說明","拖曳三個固定形狀之一到 8×8 棋盤。","上移的半透明預覽會顯示合法落點。","填滿橫排或直列後立即消除。","關卡規則","泥土、冰塊、石頭、寶石、鎖定格、顏色與組數限制構成三十個任務。","選擇關卡","選擇已解鎖任務。","進入關卡","分數","組數","放置後不能移動或旋轉；完整行列會立即消除。","繼續","要離開這局嗎？","繼續會保留目前棋盤。","關卡地圖","任務完成！","下一關","再玩一次","這個形狀無法放在這裡。","已放置方塊。","消除了 {n} 條線！","剩餘形狀都無法放置。","已達方塊組數上限。","{score} 分 · {lines} 條線 · {sets} 組","行列","泥土","冰與石頭","顏色","寶石與鎖","混合","無限"],
"zh-Hans":["方块爆破","语言","8×8 方块益智","放完每组三个形状，填满横排或直列立即消除。","关卡模式","无限模式","所有者预览 · 规则检查版本","为下一组三个形状保留空间。","玩法说明","拖动三个固定形状之一到 8×8 棋盘。","上移的半透明预览会显示合法落点。","填满横排或直列后立即消除。","关卡规则","泥土、冰块、石头、宝石、锁定格、颜色和组数限制构成三十个任务。","选择关卡","选择已解锁任务。","进入关卡","分数","组数","放置后不能移动或旋转；完整行列会立即消除。","继续","要离开这局吗？","继续会保留当前棋盘。","关卡地图","任务完成！","下一关","再玩一次","这个形状无法放在这里。","已放置方块。","消除了 {n} 条线！","剩余形状都无法放置。","已达方块组数上限。","{score} 分 · {lines} 条线 · {sets} 组","行列","泥土","冰与石头","颜色","宝石与锁","混合","无限"],
ja:["ブロックブラスト","言語","8×8 ブロックパズル","3つの形をすべて置き、行か列を完成させよう。","キャンペーン","エンドレス","オーナープレビュー · ルール確認版","次の3つの形のために空間を残そう。","遊び方","固定された3つの形から1つを8×8盤へドラッグします。","持ち上がった半透明プレビューが置ける場所を示します。","行か列が完成するとすぐ消えます。","キャンペーンルール","土、氷、石、宝石、ロック、色、組数制限で30ミッションを作ります。","ステージ選択","解放済みミッションを選びます。","入る","スコア","セット","配置後は移動も回転もできません。完成ラインは即座に消えます。","続ける","このプレイを離れますか？","続けると盤面を維持します。","ステージマップ","ミッション完了！","次のステージ","もう一度","そこには置けません。","配置しました。","{n}ライン消去！","残りの形を置けません。","セット上限に達しました。","{score}点 · {lines}ライン · {sets}セット","ライン","土","氷 + 石","色","宝石 + ロック","ミックス","エンドレス"],
ko:["블록 블라스트","언어","8×8 블록 퍼즐","세 모양을 모두 놓고 완성된 행이나 열을 지우세요.","캠페인","무한 모드","소유자 미리보기 · 규칙 점검 빌드","다음 세 모양을 위한 공간을 남기세요.","플레이 방법","고정된 세 모양 중 하나를 8×8 보드로 드래그하세요.","위로 뜬 반투명 미리보기가 가능한 위치를 보여 줍니다.","행이나 열을 완성하면 즉시 사라집니다.","캠페인 규칙","흙, 얼음, 돌, 보석, 잠금, 색상, 세트 제한으로 30개 미션을 구성합니다.","스테이지 선택","열린 미션을 선택하세요.","입장","점수","세트","놓은 뒤에는 이동하거나 회전할 수 없습니다. 완성된 줄은 즉시 지워집니다.","계속","이 게임을 나갈까요?","계속하면 현재 보드를 유지합니다.","스테이지 맵","미션 완료!","다음 스테이지","다시 플레이","그곳에는 놓을 수 없습니다.","모양을 놓았습니다.","{n}줄 제거!","남은 모양을 놓을 수 없습니다.","세트 제한에 도달했습니다.","{score}점 · {lines}줄 · {sets}세트","줄","흙","얼음 + 돌","색상","보석 + 잠금","혼합","무한"],
es:["Explosión de bloques","Idioma","PUZLE 8×8","Coloca las tres formas y completa filas o columnas.","Campaña","Sin fin","VISTA DEL PROPIETARIO · REGLAS","Deja espacio para las próximas tres formas.","Cómo jugar","Arrastra una de tres formas fijas al tablero 8×8.","Una vista elevada y translúcida muestra una posición válida.","Completa una fila o columna para borrarla al instante.","Reglas de campaña","Tierra, hielo, piedra, gemas, bloqueos, colores y límites crean treinta misiones.","Elegir nivel","Elige una misión desbloqueada.","Entrar","Puntos","Grupos","Las formas no se mueven ni giran tras colocarlas. Las líneas se borran de inmediato.","Continuar","¿Salir de la partida?","Continuar conserva el tablero.","Mapa","¡Misión completa!","Siguiente","Jugar de nuevo","La forma no cabe ahí.","Forma colocada.","¡{n} línea eliminada!","Ninguna forma restante cabe.","Se alcanzó el límite de grupos.","{score} puntos · {lines} líneas · {sets} grupos","LÍNEAS","TIERRA","HIELO + PIEDRA","COLOR","GEMAS + BLOQUEOS","MIXTO","SIN FIN"],
"pt-BR":["Explosão de blocos","Idioma","QUEBRA-CABEÇA 8×8","Coloque as três formas e complete linhas ou colunas.","Campanha","Infinito","PRÉVIA DO PROPRIETÁRIO · REGRAS","Guarde espaço para as próximas três formas.","Como jogar","Arraste uma das três formas fixas para o tabuleiro 8×8.","Uma prévia elevada e translúcida mostra uma posição válida.","Complete uma linha ou coluna para apagar imediatamente.","Regras da campanha","Terra, gelo, pedra, gemas, travas, cores e limites criam trinta missões.","Escolher fase","Escolha uma missão liberada.","Entrar","Pontos","Grupos","As formas não podem mover nem girar depois. Linhas completas somem na hora.","Continuar","Sair da partida?","Continuar mantém o tabuleiro.","Mapa","Missão concluída!","Próxima","Jogar novamente","A forma não cabe aí.","Forma colocada.","{n} linha eliminada!","Nenhuma forma restante cabe.","O limite de grupos foi atingido.","{score} pontos · {lines} linhas · {sets} grupos","LINHAS","TERRA","GELO + PEDRA","COR","GEMAS + TRAVAS","MISTO","INFINITO"],
fr:["Explosion de blocs","Langue","PUZZLE 8×8","Placez les trois formes et complétez des lignes ou colonnes.","Campagne","Sans fin","APERÇU PROPRIÉTAIRE · RÈGLES","Gardez de la place pour les trois formes suivantes.","Comment jouer","Glissez une des trois formes fixes sur la grille 8×8.","Un aperçu translucide relevé montre un emplacement valide.","Complétez une ligne ou colonne pour l’effacer aussitôt.","Règles de campagne","Terre, glace, pierre, gemmes, verrous, couleurs et limites créent trente missions.","Choisir un niveau","Choisissez une mission débloquée.","Entrer","Score","Séries","Une forme placée ne bouge ni ne tourne. Les lignes complètes disparaissent aussitôt.","Continuer","Quitter la partie ?","Continuer conserve la grille.","Carte","Mission réussie !","Suivant","Rejouer","Cette forme ne tient pas ici.","Forme placée.","{n} ligne effacée !","Aucune forme restante ne tient.","Limite de séries atteinte.","{score} points · {lines} lignes · {sets} séries","LIGNES","TERRE","GLACE + PIERRE","COULEUR","GEMMES + VERROUS","MIXTE","SANS FIN"],
de:["Block-Explosion","Sprache","8×8-BLOCKPUZZLE","Lege alle drei Formen und fülle Reihen oder Spalten.","Kampagne","Endlos","BESITZER-VORSCHAU · REGELTEST","Halte Platz für die nächsten drei Formen frei.","Spielanleitung","Ziehe eine von drei festen Formen auf das 8×8-Brett.","Eine angehobene durchscheinende Vorschau zeigt gültige Plätze.","Volle Reihen oder Spalten verschwinden sofort.","Kampagnenregeln","Erde, Eis, Stein, Juwelen, Sperren, Farben und Limits bilden dreißig Missionen.","Stufe wählen","Wähle eine offene Mission.","Betreten","Punkte","Sätze","Formen können nach dem Legen weder bewegt noch gedreht werden. Volle Linien verschwinden sofort.","Fortsetzen","Runde verlassen?","Fortsetzen bewahrt das Brett.","Stufenkarte","Mission erfüllt!","Nächste Stufe","Noch einmal","Diese Form passt dort nicht.","Form gelegt.","{n} Linie gelöscht!","Keine übrige Form passt.","Satzlimit erreicht.","{score} Punkte · {lines} Linien · {sets} Sätze","LINIEN","ERDE","EIS + STEIN","FARBE","JUWELEN + SPERREN","GEMISCHT","ENDLOS"],
it:["Esplosione di blocchi","Lingua","PUZZLE 8×8","Posiziona tutte e tre le forme e completa righe o colonne.","Campagna","Infinita","ANTEPRIMA PROPRIETARIO · REGOLE","Lascia spazio per le prossime tre forme.","Come giocare","Trascina una delle tre forme fisse sulla griglia 8×8.","Un’anteprima sollevata e trasparente mostra una posizione valida.","Completa una riga o colonna per cancellarla subito.","Regole campagna","Terra, ghiaccio, pietra, gemme, blocchi, colori e limiti creano trenta missioni.","Scegli livello","Scegli una missione sbloccata.","Entra","Punti","Gruppi","Dopo il posizionamento le forme non si muovono né ruotano. Le linee complete spariscono subito.","Continua","Lasciare la partita?","Continua conserva la griglia.","Mappa","Missione completata!","Successivo","Gioca ancora","La forma non entra qui.","Forma posizionata.","{n} linea eliminata!","Nessuna forma rimasta entra.","Limite di gruppi raggiunto.","{score} punti · {lines} linee · {sets} gruppi","LINEE","TERRA","GHIACCIO + PIETRA","COLORE","GEMME + BLOCCHI","MISTO","INFINITA"],
ru:["Взрыв блоков","Язык","ГОЛОВОЛОМКА 8×8","Разместите все три фигуры и заполните ряды или столбцы.","Кампания","Бесконечная","ПРЕДПРОСМОТР ВЛАДЕЛЬЦА · ПРОВЕРКА ПРАВИЛ","Оставляйте место для следующих трёх фигур.","Как играть","Перетащите одну из трёх фиксированных фигур на поле 8×8.","Поднятый полупрозрачный контур показывает допустимое место.","Полный ряд или столбец исчезает сразу.","Правила кампании","Земля, лёд, камень, самоцветы, замки, цвета и лимиты создают тридцать миссий.","Выбор этапа","Выберите открытую миссию.","Войти","Очки","Наборы","После размещения фигуру нельзя двигать или вращать. Полные линии исчезают сразу.","Продолжить","Покинуть игру?","Продолжение сохраняет поле.","Карта","Миссия выполнена!","Следующий этап","Ещё раз","Фигура здесь не помещается.","Фигура размещена.","Удалено линий: {n}!","Ни одна оставшаяся фигура не помещается.","Достигнут лимит наборов.","{score} очков · {lines} линий · {sets} наборов","ЛИНИИ","ЗЕМЛЯ","ЛЁД + КАМЕНЬ","ЦВЕТ","САМОЦВЕТЫ + ЗАМКИ","СМЕШАННО","БЕСКОНЕЧНО"],
hi:["ब्लॉक ब्लास्ट","भाषा","8×8 ब्लॉक पहेली","तीनों आकार रखें और पूरी पंक्ति या स्तंभ मिटाएँ।","अभियान","अनंत","मालिक पूर्वावलोकन · नियम जाँच","अगले तीन आकारों के लिए जगह बनाए रखें।","कैसे खेलें","तीन स्थिर आकारों में से एक को 8×8 बोर्ड पर खींचें।","ऊपर उठा पारदर्शी पूर्वावलोकन सही स्थान दिखाता है।","पूरी पंक्ति या स्तंभ तुरंत मिटता है।","अभियान नियम","मिट्टी, बर्फ, पत्थर, रत्न, ताले, रंग और समूह सीमा तीस मिशन बनाते हैं।","चरण चुनें","खुला मिशन चुनें।","प्रवेश","स्कोर","समूह","रखने के बाद आकार हिल या घूम नहीं सकता। पूरी लाइन तुरंत मिटती है।","जारी रखें","यह खेल छोड़ें?","जारी रखने पर बोर्ड बचा रहेगा।","चरण नक्शा","मिशन पूरा!","अगला चरण","फिर खेलें","यह आकार वहाँ नहीं बैठता।","आकार रखा गया।","{n} लाइन मिटी!","कोई शेष आकार नहीं बैठता।","समूह सीमा पूरी हुई।","{score} अंक · {lines} लाइन · {sets} समूह","लाइन","मिट्टी","बर्फ + पत्थर","रंग","रत्न + ताले","मिश्रित","अनंत"],
ar:["انفجار المكعبات","اللغة","لغز كتل 8×8","ضع الأشكال الثلاثة وأكمل صفوفاً أو أعمدة.","الحملة","بلا نهاية","معاينة المالك · فحص القواعد","اترك مساحة للأشكال الثلاثة التالية.","طريقة اللعب","اسحب واحداً من ثلاثة أشكال ثابتة إلى لوحة 8×8.","تظهر معاينة شفافة مرفوعة موضعاً صالحاً.","أكمل صفاً أو عموداً ليُحذف فوراً.","قواعد الحملة","التراب والجليد والحجر والجواهر والأقفال والألوان والحدود تصنع ثلاثين مهمة.","اختر مرحلة","اختر مهمة مفتوحة.","دخول","النقاط","المجموعات","لا يمكن تحريك الشكل أو تدويره بعد وضعه. تُحذف الخطوط المكتملة فوراً.","متابعة","مغادرة الجولة؟","المتابعة تحفظ اللوحة الحالية.","خريطة المراحل","اكتملت المهمة!","المرحلة التالية","العب مجدداً","لا يناسب الشكل هذا المكان.","تم وضع الشكل.","تم حذف {n} خط!","لا يمكن وضع أي شكل متبقٍ.","تم بلوغ حد المجموعات.","{score} نقطة · {lines} خط · {sets} مجموعة","الخطوط","التراب","الجليد والحجر","اللون","الجواهر والأقفال","مختلط","بلا نهاية"]};
const N={en:"English","zh-Hant":"繁體中文","zh-Hans":"简体中文",ja:"日本語",ko:"한국어",es:"Español","pt-BR":"Português",fr:"Français",de:"Deutsch",it:"Italiano",ru:"Русский",hi:"हिन्दी",ar:"العربية"},I=Object.fromEntries(Object.entries(P).map(([l,v])=>[l,Object.fromEntries(KEYS.map((k,i)=>[k,v[i]]))]));
const COLORS=["#4f8cff","#a866e8","#36c9b2","#ffbd45","#ff668b"],SHAPES=[
{id:"dot",cells:[[0,0]],size:"small"},{id:"domino-h",cells:[[0,0],[0,1]],size:"small"},{id:"domino-v",cells:[[0,0],[1,0]],size:"small"},{id:"tri-h",cells:[[0,0],[0,1],[0,2]],size:"small"},{id:"tri-v",cells:[[0,0],[1,0],[2,0]],size:"small"},{id:"square",cells:[[0,0],[0,1],[1,0],[1,1]],size:"medium"},{id:"line-h",cells:[[0,0],[0,1],[0,2],[0,3]],size:"large"},{id:"line-v",cells:[[0,0],[1,0],[2,0],[3,0]],size:"large"},{id:"l",cells:[[0,0],[1,0],[2,0],[2,1]],size:"medium"},{id:"t",cells:[[0,0],[0,1],[0,2],[1,1]],size:"medium"},{id:"z",cells:[[0,1],[0,2],[1,0],[1,1]],size:"medium"},{id:"cross",cells:[[0,1],[1,0],[1,1],[1,2],[2,1]],size:"large"},{id:"stairs",cells:[[0,0],[1,0],[1,1],[2,1],[2,2]],size:"large"},{id:"irregular",cells:[[0,0],[1,0],[1,1]],size:"small"}];
SHAPES.push(
{id:"line-5h",cells:[[0,0],[0,1],[0,2],[0,3],[0,4]],size:"large",endlessOnly:true},
{id:"line-5v",cells:[[0,0],[1,0],[2,0],[3,0],[4,0]],size:"large",endlessOnly:true},
{id:"rect-2x3",cells:[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2]],size:"large",endlessOnly:true},
{id:"rect-3x2",cells:[[0,0],[0,1],[1,0],[1,1],[2,0],[2,1]],size:"large",endlessOnly:true},
{id:"square-3",cells:[[0,0],[0,1],[0,2],[1,0],[1,1],[1,2],[2,0],[2,1],[2,2]],size:"large",endlessOnly:true}
);
const TERRAIN={NONE:0,DIRT:1,ICE:2,STONE:3,LOCK:4,GEM:5},DIRT_BLOCK=-1,DIRT_COLOR="#a85f2d";
// Explicit mission catalog: objectives and terrain are reviewed per stage.
const STAGES=[
  {"number":1,"band":1,"objective":{"kind":"lines","target":1},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":2,"band":1,"objective":{"kind":"lines","target":1},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":3,"band":1,"objective":{"kind":"lines","target":2},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":4,"band":1,"objective":{"kind":"lines","target":2},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":5,"band":1,"objective":{"kind":"lines","target":3},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":6,"band":2,"objective":{"kind":"dirt","target":3},"terrain":{"dirt":3,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":7,"band":2,"objective":{"kind":"dirt","target":4},"terrain":{"dirt":4,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":8,"band":2,"objective":{"kind":"dirt","target":5},"terrain":{"dirt":5,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":9,"band":2,"objective":{"kind":"dirt","target":6},"terrain":{"dirt":6,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":10,"band":2,"objective":{"kind":"dirt","target":7},"terrain":{"dirt":7,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":11,"band":3,"objective":{"kind":"ice","target":3},"terrain":{"dirt":0,"ice":3,"stone":1,"lock":0,"gem":0}},
  {"number":12,"band":3,"objective":{"kind":"ice","target":4},"terrain":{"dirt":0,"ice":4,"stone":1,"lock":0,"gem":0}},
  {"number":13,"band":3,"objective":{"kind":"ice","target":5},"terrain":{"dirt":0,"ice":5,"stone":2,"lock":0,"gem":0}},
  {"number":14,"band":3,"objective":{"kind":"ice","target":6},"terrain":{"dirt":0,"ice":6,"stone":2,"lock":0,"gem":0}},
  {"number":15,"band":3,"objective":{"kind":"ice","target":7},"terrain":{"dirt":0,"ice":7,"stone":3,"lock":0,"gem":0}},
  {"number":16,"band":4,"objective":{"kind":"colors","target":3,"color":0},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":17,"band":4,"objective":{"kind":"colors","target":4,"color":1},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":18,"band":4,"objective":{"kind":"colors","target":5,"color":2},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":19,"band":4,"objective":{"kind":"colors","target":6,"color":3},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":20,"band":4,"objective":{"kind":"colors","target":7,"color":4},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":0,"gem":0}},
  {"number":21,"band":5,"objective":{"kind":"gems","target":2},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":1,"gem":3}},
  {"number":22,"band":5,"objective":{"kind":"gems","target":2},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":1,"gem":3}},
  {"number":23,"band":5,"objective":{"kind":"gems","target":3},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":2,"gem":4}},
  {"number":24,"band":5,"objective":{"kind":"gems","target":3},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":2,"gem":4}},
  {"number":25,"band":5,"objective":{"kind":"gems","target":4},"terrain":{"dirt":0,"ice":0,"stone":0,"lock":3,"gem":5}},
  {"number":26,"band":6,"objective":{"kind":"mixed","linesTarget":1,"terrainTarget":2,"gemsTarget":1,"setsLimit":12},"terrain":{"dirt":2,"ice":2,"stone":2,"lock":2,"gem":2}},
  {"number":27,"band":6,"objective":{"kind":"mixed","linesTarget":1,"terrainTarget":2,"gemsTarget":1,"setsLimit":11},"terrain":{"dirt":2,"ice":2,"stone":2,"lock":2,"gem":2}},
  {"number":28,"band":6,"objective":{"kind":"mixed","linesTarget":1,"terrainTarget":2,"gemsTarget":1,"setsLimit":10},"terrain":{"dirt":2,"ice":2,"stone":2,"lock":2,"gem":2}},
  {"number":29,"band":6,"objective":{"kind":"mixed","linesTarget":1,"terrainTarget":2,"gemsTarget":1,"setsLimit":9},"terrain":{"dirt":2,"ice":2,"stone":2,"lock":2,"gem":2}},
  {"number":30,"band":6,"objective":{"kind":"mixed","linesTarget":1,"terrainTarget":2,"gemsTarget":1,"setsLimit":8},"terrain":{"dirt":2,"ice":2,"stone":2,"lock":2,"gem":2}}
];
const clone=a=>a.map(item=>Array.isArray(item)?[...item]:item),cellIndex=(r,c)=>r*8+c,dims=shape=>({rows:Math.max(...shape.cells.map(c=>c[0]))+1,cols:Math.max(...shape.cells.map(c=>c[1]))+1});
const ENDLESS_BEST_KEY="blockBlastEndlessBest",readEndlessBest=()=>{try{return Math.max(0,Math.floor(Number(localStorage.getItem(ENDLESS_BEST_KEY))||0));}catch{return 0;}},writeEndlessBest=value=>{try{localStorage.setItem(ENDLESS_BEST_KEY,String(value));}catch{}};
let locale=localStorage.wpLang||"en",sound=localStorage.wpSound!=="off",unlocked=Math.max(1,Math.min(30,Number(localStorage.blockBlastUnlocked)||1)),selectedStage=unlocked,currentStage=1,endless=false,endlessBest=readEndlessBest(),grid=[],terrain=[],tray=[],selected=-1,preview=[],previewAnchor=-1,previewIsValid=false,flashCells=new Set(),flashColors=new Map(),effectLines=[],lastClearBounds={minRow:0,maxRow:7,minCol:0,maxCol:7},clearEffectTimer=0,clearEffectStartedAt=0,clearEffectGeneration=0,scorePopTimer=0,scorePopGeneration=0,finishTimer=0,runGeneration=0,comboStreak=0,score=0,lines=0,sets=0,terrainCleared=0,dirtCleared=0,iceCleared=0,gems=0,colorCleared=0,generation=0,lastTrayHadLarge=false,setsSinceLarge=0,setsSinceNine=0,busy=false,lastFocus=null;
const t=(k,v={})=>String((I[locale]||I.en)[k]||k).replace(/\{(\w+)\}/g,(_,n)=>v[n]??"");
const CLEAR_EFFECT_MS=1100,SCORE_POP_MS=1700,COMBO_LABELS={en:"COMBO","zh-Hant":"連消","zh-Hans":"连消",ja:"コンボ",ko:"콤보",es:"COMBO","pt-BR":"COMBO",fr:"COMBO",de:"KOMBO",it:"COMBO",ru:"КОМБО",hi:"कॉम्बो",ar:"كومبو"};
const BEST_LABELS={en:"Best","zh-Hant":"最高分","zh-Hans":"最高分",ja:"ベスト",ko:"최고 점수",es:"Récord","pt-BR":"Recorde",fr:"Record",de:"Bestwert",it:"Record",ru:"Рекорд",hi:"सर्वश्रेष्ठ",ar:"الأفضل"};
function bestLabel(value=endlessBest){return`${BEST_LABELS[locale]||BEST_LABELS.en} ${value}`;}
function syncEndlessBest(){if($("endlessBtn"))$("endlessBtn").textContent=`${t("endless")} · ${bestLabel()}`;}
function syncCampaignEntry(){const button=$("startBtn"),progress=`${unlocked} / 30`;if(!button)return;button.textContent=`${t("campaign")} · ${progress}`;button.setAttribute("aria-label",button.textContent);button.dataset.campaignProgress=progress;}
function updateEndlessBest(){if(!endless||score<=endlessBest)return false;endlessBest=score;writeEndlessBest(endlessBest);syncEndlessBest();if(document.body.dataset.screen==="battle"&&$("objectiveText"))$("objectiveText").textContent=progress();return true;}
function openingFillCount(number){if(number<=2)return 0;if(number<=5)return number+2;if(number<=10)return number-1;if(number<=15)return number-4;if(number<=20)return number-7;if(number<=25)return number-10;return Math.min(18,number-12);}
function seedOpeningBlocks(def){const target=openingFillCount(def.number),rowCounts=Array.from({length:8},(_,row)=>grid.slice(row*8,row*8+8).filter(value=>value!=null).length),colCounts=Array.from({length:8},(_,col)=>Array.from({length:8},(_,row)=>grid[cellIndex(row,col)]).filter(value=>value!=null).length),objectiveColor=def.objective?.kind==="colors"?def.objective.color:null,candidates=Array.from({length:64},(_,i)=>(i*17+def.number*11)%64);let placed=0;for(const index of candidates){const row=Math.floor(index/8),col=index%8;if(placed>=target)break;if(terrain[index]!==TERRAIN.NONE||rowCounts[row]>=4||colCounts[col]>=4)continue;grid[index]=objectiveColor!=null&&placed%3===0?objectiveColor:(def.number+placed)%COLORS.length;rowCounts[row]++;colCounts[col]++;placed++;}}
function freshBoard(def){grid=Array(64).fill(null);terrain=Array(64).fill(TERRAIN.NONE);const reserved=new Set();for(const [type,count,offset] of[[TERRAIN.STONE,def.terrain.stone,7],[TERRAIN.LOCK,def.terrain.lock,19],[TERRAIN.DIRT,def.terrain.dirt,3],[TERRAIN.ICE,def.terrain.ice,11],[TERRAIN.GEM,def.terrain.gem,23]])for(let i=0;i<count;i++){let index=(def.number*offset+i*13+offset)%64;while(reserved.has(index))index=(index+1)%64;reserved.add(index);terrain[index]=type;}const blockers=new Set([TERRAIN.STONE,TERRAIN.LOCK]);for(let index=0;index<64;index++){if(terrain[index]!==TERRAIN.ICE)continue;const row=Math.floor(index/8),col=index%8,rowBlocked=Array.from({length:8},(_,c)=>terrain[cellIndex(row,c)]).some(value=>blockers.has(value)),colBlocked=Array.from({length:8},(_,r)=>terrain[cellIndex(r,col)]).some(value=>blockers.has(value));if(rowBlocked&&colBlocked){const replacement=terrain.findIndex((value,candidate)=>value===TERRAIN.NONE&&(!Array.from({length:8},(_,c)=>terrain[cellIndex(Math.floor(candidate/8),c)]).some(item=>blockers.has(item))||!Array.from({length:8},(_,r)=>terrain[cellIndex(r,candidate%8)]).some(item=>blockers.has(item))));if(replacement>=0){terrain[replacement]=TERRAIN.ICE;terrain[index]=TERRAIN.NONE;}}}for(let index=0;index<64;index++)if(terrain[index]===TERRAIN.DIRT)grid[index]=DIRT_BLOCK;seedOpeningBlocks(def);}
function fits(shape,anchor,g=grid,tr=terrain){const row=Math.floor(anchor/8),col=anchor%8;return shape.cells.every(([dr,dc])=>{const r=row+dr,c=col+dc,index=cellIndex(r,c);return r>=0&&c>=0&&r<8&&c<8&&g[index]==null&&tr[index]!==TERRAIN.STONE&&tr[index]!==TERRAIN.LOCK;});}
function placements(shape,g=grid,tr=terrain){const out=[];for(let i=0;i<64;i++)if(fits(shape,i,g,tr))out.push(i);return out;}
function projectPlacement(shape,anchor,g,tr){const next=[...g],row=Math.floor(anchor/8),col=anchor%8;for(const[dr,dc]of shape.cells)next[cellIndex(row+dr,col+dc)]=COLORS.length;const rows=[],cols=[];for(let r=0;r<8;r++)if(Array.from({length:8},(_,c)=>next[cellIndex(r,c)]!=null).every(Boolean))rows.push(r);for(let c=0;c<8;c++)if(Array.from({length:8},(_,r)=>next[cellIndex(r,c)]!=null).every(Boolean))cols.push(c);for(const r of rows)for(let c=0;c<8;c++)next[cellIndex(r,c)]=null;for(const c of cols)for(let r=0;r<8;r++)next[cellIndex(r,c)]=null;return next;}
function trayCompletable(shapes,g=grid,tr=terrain){function search(remaining,nextGrid){if(!remaining.length)return true;for(let index=0;index<remaining.length;index++){const shape=remaining[index];for(const anchor of placements(shape,nextGrid,tr)){if(search(remaining.filter((_,i)=>i!==index),projectPlacement(shape,anchor,nextGrid,tr)))return true;}}return false;}return search(shapes,g);}
function seededRoll(salt=0){let value=(generation*2654435761+score*97+grid.filter(item=>item!=null).length*193+salt*1013904223)>>>0;value^=value<<13;value^=value>>>17;value^=value<<5;return(value>>>0)/4294967296;}
function rotatePool(pool,salt=0){if(!pool.length)return[];const start=Math.floor(seededRoll(salt)*pool.length);return pool.map((_,index)=>pool[(start+index)%pool.length]);}
function endlessTray(fitting,boardFill){const regular=fitting.filter(shape=>shape.size!=="large"),medium=regular.filter(shape=>shape.size==="medium"),large=fitting.filter(shape=>shape.size==="large"),largeChance=boardFill<20?.3:boardFill<38?.36:.22,wantLarge=!lastTrayHadLarge&&large.length>0&&(setsSinceLarge>=3||seededRoll(11)<largeChance),nine=large.find(shape=>shape.id==="square-3"),wantNine=wantLarge&&generation>=3&&nine&&(setsSinceNine>=7||seededRoll(23)<.32),largeOrder=rotatePool(large.filter(shape=>shape!==nine||wantNine),31).sort((a,b)=>Number(b===nine&&wantNine)-Number(a===nine&&wantNine)),regularOrder=rotatePool(regular,47),mediumOrder=rotatePool(medium,53);let chosen=null;if(wantLarge)for(const big of largeOrder){for(const anchor of mediumOrder)for(const other of regularOrder){const candidate=[big,anchor,other];if(anchor.id!==other.id&&trayCompletable(candidate)){chosen=candidate;break;}}if(chosen)break;}const smallCap=generation%4===0?2:1;for(let offset=0;offset<regularOrder.length&&!chosen;offset++){const candidate=[];for(let step=0;step<regularOrder.length&&candidate.length<3;step++){const shape=regularOrder[(offset+step)%regularOrder.length];if(!candidate.some(item=>item.id===shape.id))candidate.push(shape);}if(candidate.length===3&&candidate.filter(shape=>shape.size==="small").length<=smallCap&&trayCompletable(candidate))chosen=candidate;}return chosen;}
function generateTray(){generation++;const fitting=SHAPES.filter(shape=>(endless||!shape.endlessOnly)&&placements(shape).length);if(!fitting.length)return false;const objective=endless?null:STAGES[currentStage-1].objective,boardFill=grid.filter(value=>value!=null).length,precision=objective&&["dirt","ice","gems","mixed"].includes(objective.kind);let chosen=endless?endlessTray(fitting,boardFill):null;if(!chosen){const rank=shape=>precision?({small:0,medium:1,large:2}[shape.size]):boardFill>34?({small:0,medium:1,large:2}[shape.size]):({medium:0,small:1,large:2}[shape.size]),ordered=[...fitting].sort((a,b)=>rank(a)-rank(b)||a.id.localeCompare(b.id)),rotated=ordered.map((_,i)=>ordered[(i+generation+currentStage)%ordered.length]),forbidLarge=lastTrayHadLarge&&fitting.filter(shape=>shape.size!=="large").length>=3;for(let offset=0;offset<rotated.length&&!chosen;offset++){const candidate=[];for(let step=0;step<rotated.length&&candidate.length<3;step++){const shape=rotated[(offset+step)%rotated.length];if(candidate.some(item=>item.id===shape.id))continue;if(shape.size==="large"&&(forbidLarge||candidate.some(item=>item.size==="large")))continue;candidate.push(shape);}if(candidate.length===3&&trayCompletable(candidate))chosen=candidate;}}if(!chosen){const small=fitting.filter(shape=>shape.size==="small");for(const a of small)for(const b of small)for(const c of small){const candidate=[a,b,c];if(!chosen&&trayCompletable(candidate))chosen=candidate;}}if(!chosen)return false;tray=chosen.map((shape,index)=>({...shape,color:objective?.kind==="colors"&&index===0?objective.color:(currentStage+generation+index)%COLORS.length,used:false}));lastTrayHadLarge=tray.some(shape=>shape.size==="large");setsSinceLarge=lastTrayHadLarge?0:setsSinceLarge+1;setsSinceNine=tray.some(shape=>shape.id==="square-3")?0:setsSinceNine+1;selected=-1;preview=[];previewAnchor=-1;previewIsValid=false;sets++;return true;}
function kindKey(){if(endless)return"endlessKind";return{lines:"lines",dirt:"dirt",ice:"iceStone",colors:"colors",gems:"gemsLocks",mixed:"mixed"}[STAGES[currentStage-1].objective.kind];}
function progress(){if(endless)return`${score} · ${bestLabel()}`;const stage=STAGES[currentStage-1],o=stage.objective;if(o.kind==="lines")return`${lines} / ${o.target}`;if(o.kind==="dirt")return`${dirtCleared} / ${o.target}`;if(o.kind==="ice")return`${iceCleared} / ${o.target}`;if(o.kind==="colors")return`${colorCleared} / ${o.target}`;if(o.kind==="gems")return`${gems} / ${o.target}`;return`${lines}/${o.linesTarget} · ${dirtCleared}/${stage.terrain.dirt} ${t("dirt")} · ${gems}/${o.gemsTarget} · ${sets}/${o.setsLimit}`;}
function objectiveMet(stage,stats){const o=stage.objective,dirtMet=(stats.dirtCleared||0)>=(stage.terrain?.dirt||0);if(o.kind==="lines")return dirtMet&&stats.lines>=o.target;if(o.kind==="dirt")return dirtMet&&stats.dirtCleared>=o.target;if(o.kind==="ice")return dirtMet&&stats.iceCleared>=o.target;if(o.kind==="colors")return dirtMet&&stats.colorCleared>=o.target;if(o.kind==="gems")return dirtMet&&stats.gems>=o.target;return dirtMet&&stats.lines>=o.linesTarget&&stats.terrainCleared>=o.terrainTarget&&stats.gems>=o.gemsTarget;}
function won(){if(endless)return false;return objectiveMet(STAGES[currentStage-1],{lines,terrainCleared,dirtCleared,iceCleared,gems,colorCleared});}
function setScreen(s){document.body.dataset.screen=s;$("mainGroup").hidden=s!=="main";$("stageScreen").hidden=s!=="stage";$("battleScreen").hidden=s!=="battle";document.body.classList.toggle("is-game-playing",s==="battle");if(s==="stage")$("stageScreen").querySelector(".wp-stage-physical-reserve")?.setAttribute("data-wp-stage-reserve-active","");window.dispatchEvent(new Event("weightplay:stage-sync"));window.dispatchEvent(new Event("weightplay:shell-sync"));}
function applyLocale(){document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t(n.dataset.i18n));$("localeSelect").value=locale;$("localeSelect").setAttribute("aria-label",t("language"));$("stageBack").setAttribute("aria-label",t("chooseStage"));$("battleBack").setAttribute("aria-label",t("stageMap"));$("battleHelp").setAttribute("aria-label",t("howTitle"));$("stageRail").setAttribute("aria-label",t("chooseStage"));$("blockBoard").setAttribute("aria-label",t("title"));$("pieceTray").setAttribute("aria-label",t("guideTitle"));document.querySelector(".guide")?.setAttribute("aria-label",t("howTitle"));document.querySelectorAll(".poster,.result-layout img").forEach(n=>n.setAttribute("alt",t("title")));$("mainProgress").textContent=`${unlocked} / 30`;syncCampaignEntry();syncEndlessBest();renderStages();if(grid.length)render();window.dispatchEvent(new Event("wonder:locale-change"));}
function syncSound(){for(const id of["soundToggle","stageSound"]){$(id).textContent=sound?"🔊":"🔇";$(id).setAttribute("aria-pressed",String(sound));}}
function stageObjectiveSummary(stage){const objective=stage.objective;if(objective.kind!=="mixed")return String(objective.target);return`${objective.linesTarget} ${t("lines")} · ${stage.terrain.dirt} ${t("dirt")} · ${objective.gemsTarget} ${t("gemsLocks")} · ${objective.setsLimit} ${t("sets")}`;}
function renderStages(){if(!$("stageRail"))return;$("stageSummary").textContent=`${unlocked} / 30`;$("stageRail").innerHTML=STAGES.map(s=>`<button class="stage-card" data-stage="${s.number}" data-stage-index="${s.number-1}" ${s.number>unlocked?"disabled":""} aria-current="${s.number===selectedStage}"><span class="stage-number">${String(s.number).padStart(2,"0")}</span><small>${t(["lines","dirt","iceStone","colors","gemsLocks","mixed"][s.band-1])}</small><strong>${stageObjectiveSummary(s)}</strong></button>`).join("");$("enterStage").disabled=selectedStage>unlocked;}
function terrainClass(value){return["","terrain-dirt","terrain-ice","terrain-stone","terrain-lock","terrain-gem"][value];}
function clearEffectState(shouldRender=false){clearEffectGeneration++;if(clearEffectTimer){clearTimeout(clearEffectTimer);clearEffectTimer=0;}clearEffectStartedAt=0;flashCells.clear();flashColors.clear();effectLines=[];$("clearEffectLayer")?.replaceChildren();$("clearEffectLayer")?.classList.remove("line-burst");$("blockBoard")?.classList.remove("line-burst");if(shouldRender&&grid.length)render();}
function scheduleClearEffectEnd(){if(clearEffectTimer)clearTimeout(clearEffectTimer);const generation=++clearEffectGeneration;clearEffectTimer=setTimeout(()=>{if(generation!==clearEffectGeneration)return;clearEffectGeneration++;clearEffectTimer=0;clearEffectStartedAt=0;flashCells.clear();flashColors.clear();effectLines=[];render();},CLEAR_EFFECT_MS);}
function expireClearEffect(){if(clearEffectStartedAt&&Date.now()-clearEffectStartedAt>=CLEAR_EFFECT_MS){clearEffectGeneration++;if(clearEffectTimer)clearTimeout(clearEffectTimer);clearEffectTimer=0;clearEffectStartedAt=0;flashCells.clear();flashColors.clear();effectLines=[];}}
function ensureBattleEffects(){const live=$("battleLive");if(live&&!$("comboBanner"))live.insertAdjacentHTML("beforeend",'<div id="comboBanner" class="combo-banner" role="status" aria-live="polite"></div>');}
function ensureBoardEffectLayer(){const board=$("blockBoard");let layer=$("boardEffectLayer");if(!layer){layer=document.createElement("div");layer.id="boardEffectLayer";layer.className="board-effect-layer";layer.setAttribute("aria-hidden","true");layer.innerHTML='<div id="clearEffectLayer" class="clear-effect-layer"></div><div id="scorePopLayer" class="score-pop-layer"></div>';board.append(layer);}return layer;}
function syncClearEffectLayer(){const layer=$("clearEffectLayer");if(!layer||layer.dataset.generation===String(clearEffectGeneration))return;layer.dataset.generation=String(clearEffectGeneration);layer.classList.toggle("line-burst",flashCells.size>0);$("blockBoard").classList.toggle("line-burst",flashCells.size>0);if(!flashCells.size){layer.replaceChildren();return;}const elapsed=clearEffectStartedAt?Date.now()-clearEffectStartedAt:0,delay=-Math.min(elapsed,CLEAR_EFFECT_MS),beams=effectLines.map(line=>`<i class="line-beam ${line.axis}" style="--line:${line.index};--effect-delay:${delay}ms"></i>`).join(""),bursts=[...flashCells].map(index=>{const row=Math.floor(index/8),col=index%8,color=gridColor(flashColors.get(index)),cellStyle=`grid-row:${row+1};grid-column:${col+1};--burst:${color}`;return`<i class="clear-flash" style="${cellStyle};--burst-delay:${(row+col)*14-elapsed}ms"></i>${[0,1,2].map(fragment=>`<b class="fall-fragment" style="${cellStyle};--fragment-x:${(fragment-1)*(12+(index%3)*3)}px;--fragment-rotate:${(fragment-1)*115+(index%5)*24}deg;--fragment-delay:${fragment*34+(row+col)*10-elapsed}ms"></b>`).join("")}`}).join("");layer.innerHTML=beams+bursts;}
function clearScorePop(){scorePopGeneration++;if(scorePopTimer)clearTimeout(scorePopTimer);scorePopTimer=0;$("scorePopLayer")?.replaceChildren();}
function showScoreGain(points,cleared){updateEndlessBest();if(points<=0||!cleared)return;ensureBoardEffectLayer();const layer=$("scorePopLayer"),generation=++scorePopGeneration;if(scorePopTimer)clearTimeout(scorePopTimer);const gain=document.createElement("b");gain.className="score-gain-pop";gain.style.gridRow=`${lastClearBounds.minRow+1} / ${lastClearBounds.maxRow+2}`;gain.style.gridColumn=`${lastClearBounds.minCol+1} / ${lastClearBounds.maxCol+2}`;gain.textContent=`+${points}`;gain.dataset.lines=String(cleared);layer.replaceChildren(gain);scorePopTimer=setTimeout(()=>{if(generation!==scorePopGeneration)return;scorePopTimer=0;layer.replaceChildren();},SCORE_POP_MS);}
function resetRunAsync(){runGeneration++;if(finishTimer)clearTimeout(finishTimer);finishTimer=0;}
function scheduleFinish(success,delay=1450){if(finishTimer)clearTimeout(finishTimer);const generation=runGeneration;finishTimer=setTimeout(()=>{if(generation!==runGeneration)return;finishTimer=0;finish(success);},delay);}
function prospectiveClearCells(){if(!previewIsValid||!preview.length)return new Set();const occupied=grid.map(value=>value!=null);for(const index of preview)occupied[index]=true;const ready=new Set();for(let r=0;r<8;r++)if(Array.from({length:8},(_,c)=>occupied[cellIndex(r,c)]).every(Boolean))for(let c=0;c<8;c++)ready.add(cellIndex(r,c));for(let c=0;c<8;c++)if(Array.from({length:8},(_,r)=>occupied[cellIndex(r,c)]).every(Boolean))for(let r=0;r<8;r++)ready.add(cellIndex(r,c));return ready;}
function gridColor(value){return value===DIRT_BLOCK?DIRT_COLOR:COLORS[value];}
function render(){ensureBattleEffects();expireClearEffect();const previewSet=new Set(preview),readySet=prospectiveClearCells(),board=$("blockBoard"),effects=ensureBoardEffectLayer();$("battleLive").classList.toggle("combo-active",comboStreak>=2);$("comboBanner").textContent=comboStreak>=2?`${COMBO_LABELS[locale]||COMBO_LABELS.en} ×${comboStreak}`:"";const cells=Array.from({length:64},(_,i)=>{const hasBlock=grid[i]!=null,blockLayer=hasBlock?`<span class="block-fill ${grid[i]===DIRT_BLOCK?"dirt-fill":""}" style="--block-color:${gridColor(grid[i])}"></span>`:"";return`<button type="button" class="block-cell ${hasBlock?"filled":""} ${terrainClass(terrain[i])} ${previewSet.has(i)?`preview ${previewIsValid?"":"invalid"}`:""} ${readySet.has(i)?"will-clear":""} ${flashCells.has(i)?"is-clearing":""}" data-cell="${i}" ${terrain[i]===TERRAIN.STONE||terrain[i]===TERRAIN.LOCK?"disabled":""} aria-label="cell ${Math.floor(i/8)+1},${i%8+1}${terrain[i]===TERRAIN.DIRT?`, ${t("dirt")}`:""}${readySet.has(i)?", line ready to clear":""}">${blockLayer}</button>`;}).join(""),template=document.createElement("template");template.innerHTML=cells;board.querySelectorAll(":scope > .block-cell").forEach(cell=>cell.remove());board.insertBefore(template.content,effects);syncClearEffectLayer();$("pieceTray").innerHTML=tray.map((shape,i)=>{const d=dims(shape);return`<button type="button" class="piece ${i===selected?"selected":""} ${shape.used?"used":""}" data-piece="${i}" ${shape.used?"disabled":""}><span class="piece-shape" style="--rows:${d.rows};--cols:${d.cols};--piece:${COLORS[shape.color]}">${shape.cells.map(([r,c])=>`<i style="grid-row:${r+1};grid-column:${c+1}"></i>`).join("")}</span></button>`}).join("");$("scoreValue").textContent=score;$("setsValue").textContent=Math.max(0,sets-1);$("objectiveKind").textContent=t(kindKey());$("objectiveText").textContent=progress();$("stageLabel").textContent=endless?t("endlessKind"):`STAGE ${currentStage}`;}
function start(n,isEndless=false){resetRunAsync();clearEffectState();clearScorePop();currentStage=n;selectedStage=n;endless=isEndless;comboStreak=0;score=lines=terrainCleared=dirtCleared=iceCleared=gems=colorCleared=generation=sets=0;lastTrayHadLarge=false;setsSinceLarge=setsSinceNine=0;busy=false;freshBoard(isEndless?{number:0,terrain:{dirt:0,ice:0,stone:0,lock:0,gem:0}}:STAGES[n-1]);generateTray();setScreen("battle");$("feedback").textContent="";hide("resultModal");render();}
function previewAt(anchor){if(selected<0||tray[selected]?.used)return;const shape=tray[selected],row=Math.floor(anchor/8),col=anchor%8;previewAnchor=anchor;previewIsValid=fits(shape,anchor);preview=shape.cells.map(([dr,dc])=>[row+dr,col+dc]).filter(([r,c])=>r>=0&&c>=0&&r<8&&c<8).map(([r,c])=>cellIndex(r,c));render();}
function clearLines(){const rows=[],cols=[];for(let r=0;r<8;r++)if(Array.from({length:8},(_,c)=>grid[cellIndex(r,c)]!=null).every(Boolean))rows.push(r);for(let c=0;c<8;c++)if(Array.from({length:8},(_,r)=>grid[cellIndex(r,c)]!=null).every(Boolean))cols.push(c);const clearSet=new Set([...rows.flatMap(r=>Array.from({length:8},(_,c)=>cellIndex(r,c))),...cols.flatMap(c=>Array.from({length:8},(_,r)=>cellIndex(r,c)))]);if(!clearSet.size)return 0;if(clearEffectTimer)clearTimeout(clearEffectTimer);clearEffectTimer=0;clearEffectGeneration++;flashCells=clearSet;flashColors=new Map([...clearSet].map(index=>[index,grid[index]??0]));effectLines=[...rows.map(index=>({axis:"row",index})),...cols.map(index=>({axis:"col",index}))];const clearRows=[...clearSet].map(index=>Math.floor(index/8)),clearCols=[...clearSet].map(index=>index%8);lastClearBounds={minRow:Math.min(...clearRows),maxRow:Math.max(...clearRows),minCol:Math.min(...clearCols),maxCol:Math.max(...clearCols)};clearEffectStartedAt=Date.now();const objective=endless?null:STAGES[currentStage-1].objective;for(const index of clearSet){if(objective?.kind==="colors"&&grid[index]===objective.color)colorCleared++;if(terrain[index]===TERRAIN.ICE){terrain[index]=TERRAIN.NONE;terrainCleared++;iceCleared++;}else if(terrain[index]===TERRAIN.DIRT){terrain[index]=TERRAIN.NONE;terrainCleared++;dirtCleared++;}grid[index]=null;}const cleared=rows.length+cols.length;comboStreak++;lines+=cleared;score+=100*cleared*cleared*Math.min(comboStreak,5);return cleared;}
function anyTrayFit(){return tray.some(shape=>!shape.used&&placements(shape).length);}
function show(id,focus){lastFocus=document.activeElement;$(id).hidden=false;$(focus).focus();}function hide(id){$(id).hidden=true;lastFocus?.focus?.();}
function finish(success,reason=""){if(success){unlocked=Math.max(unlocked,Math.min(30,currentStage+1));localStorage.blockBlastUnlocked=unlocked;syncCampaignEntry();$("mainProgress").textContent=`${unlocked} / 30`;}updateEndlessBest();$("resultTitle").textContent=success?t("clear"):reason;$("resultStage").textContent=endless?t("endlessKind"):`STAGE ${currentStage}`;$("resultText").textContent=endless?`${t("result",{score,lines,sets:Math.max(0,sets-1)})} · ${bestLabel()}`:t("result",{score,lines,sets:Math.max(0,sets-1)});$("nextBtn").disabled=!success||endless||currentStage===30;show("resultModal",success&&!endless&&currentStage<30?"nextBtn":"retryBtn");}
function place(anchor){if(busy||selected<0||tray[selected]?.used)return false;const shape=tray[selected];if(!fits(shape,anchor)){previewAt(anchor);$("feedback").textContent=t("invalid");return false;}busy=true;const scoreBefore=score,row=Math.floor(anchor/8),col=anchor%8;for(const [dr,dc] of shape.cells){const index=cellIndex(row+dr,col+dc);grid[index]=shape.color;if(terrain[index]===TERRAIN.GEM){terrain[index]=TERRAIN.NONE;gems++;const lock=terrain.indexOf(TERRAIN.LOCK);if(lock>=0)terrain[lock]=TERRAIN.NONE;}}shape.used=true;selected=-1;preview=[];previewIsValid=false;const cleared=clearLines();if(!cleared){comboStreak=0;clearScorePop();}$("feedback").textContent=cleared?t("lineClear",{n:cleared}):t("placed");if(cleared)scheduleClearEffectEnd();if(tray.every(item=>item.used)){const objective=endless?null:STAGES[currentStage-1].objective;if(won()){busy=false;render();showScoreGain(score-scoreBefore,cleared);if(cleared)scheduleFinish(true);else finish(true);return true;}if(objective?.setsLimit&&sets>=objective.setsLimit){busy=false;render();showScoreGain(score-scoreBefore,cleared);finish(false,t("limitFail"));return true;}if(!generateTray()){busy=false;render();showScoreGain(score-scoreBefore,cleared);finish(false,t("gameOver"));return true;}}busy=false;render();showScoreGain(score-scoreBefore,cleared);if(won()){if(cleared)scheduleFinish(true);else finish(true);return true;}if(!anyTrayFit())finish(false,t("gameOver"));return true;}
$("localeSelect").innerHTML=Object.entries(N).map(([v,n])=>`<option value="${v}">${n}</option>`).join("");$("localeSelect").onchange=e=>{locale=e.target.value;localStorage.wpLang=locale;applyLocale();};for(const id of["soundToggle","stageSound"])$(id).onclick=()=>{sound=!sound;localStorage.wpSound=sound?"on":"off";syncSound();};
$("startBtn").onclick=()=>{setScreen("stage");renderStages();};$("endlessBtn").onclick=()=>start(1,true);$("stageBack").onclick=()=>setScreen("main");$("stageRail").onclick=e=>{const card=e.target.closest(".stage-card:not(:disabled)");if(card){selectedStage=+card.dataset.stage;renderStages();}};$("stageRail").addEventListener("wonder:stage-snap",e=>{const n=Number(e.detail?.index)+1;if(n>=1&&n<=30){selectedStage=n;renderStages();}});$("enterStage").onclick=()=>{if(selectedStage<=unlocked)start(selectedStage);};$("pieceTray").onclick=e=>{const piece=e.target.closest(".piece:not(:disabled)");if(piece?.parentElement===$("pieceTray")){selected=+piece.dataset.piece;preview=[];render();}};$("blockBoard").onclick=e=>{const cell=e.target.closest("[data-cell]");if(cell?.parentElement===$("blockBoard"))place(+cell.dataset.cell);};
let pointerPiece=-1,dragGhost=null,pointerStart=null,pointerDragging=false;
function anchorFromPointer(clientX,clientY){
  if(pointerPiece<0)return-1;
  const board=$("blockBoard"),shape=tray[pointerPiece],cells=board.querySelectorAll("[data-cell]");
  if(!shape||cells.length<9)return-1;
  const pointY=clientY-72,boardRect=board.getBoundingClientRect();
  if(clientX<boardRect.left||clientX>boardRect.right||pointY<boardRect.top||pointY>boardRect.bottom)return-1;
  const first=cells[0].getBoundingClientRect(),right=cells[1].getBoundingClientRect(),below=cells[8].getBoundingClientRect(),d=dims(shape);
  const col=Math.max(0,Math.min(8-d.cols,Math.round((clientX-(first.left+first.width/2))/(right.left-first.left)-(d.cols-1)/2)));
  const row=Math.max(0,Math.min(8-d.rows,Math.round((pointY-(first.top+first.height/2))/(below.top-first.top)-(d.rows-1)/2)));
  return cellIndex(row,col);
}
function showDragGhost(shape,clientX,clientY){
  dragGhost?.remove();
  const d=dims(shape);
  dragGhost=document.createElement("span");
  dragGhost.className="piece-shape drag-ghost";
  dragGhost.style.cssText=`--rows:${d.rows};--cols:${d.cols};--piece:${COLORS[shape.color]};left:${clientX}px;top:${clientY-72}px`;
  dragGhost.innerHTML=shape.cells.map(([r,c])=>`<i style="grid-row:${r+1};grid-column:${c+1}"></i>`).join("");
  document.body.append(dragGhost);
}
function updateDrag(clientX,clientY){
  if(pointerPiece<0)return;
  if(dragGhost){dragGhost.style.left=`${clientX}px`;dragGhost.style.top=`${clientY-72}px`;}
  const anchor=anchorFromPointer(clientX,clientY);
  if(anchor>=0){previewAt(anchor);dragGhost?.classList.toggle("invalid",!previewIsValid);}
  else{preview=[];previewAnchor=-1;previewIsValid=false;render();dragGhost?.classList.add("invalid");}
}
$("pieceTray").addEventListener("pointerdown",e=>{const piece=e.target.closest(".piece:not(:disabled)");if(!piece||piece.parentElement!==$("pieceTray"))return;e.preventDefault();pointerPiece=selected=+piece.dataset.piece;pointerStart={x:e.clientX,y:e.clientY};pointerDragging=false;preview=[];previewAnchor=-1;previewIsValid=false;render();});
document.addEventListener("pointermove",e=>{if(pointerPiece<0||!pointerStart)return;if(!pointerDragging&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>=8){pointerDragging=true;showDragGhost(tray[pointerPiece],e.clientX,e.clientY);}if(pointerDragging)updateDrag(e.clientX,e.clientY);});
document.addEventListener("pointerup",e=>{if(pointerPiece<0)return;if(!pointerDragging){pointerPiece=-1;pointerStart=null;preview=[];previewAnchor=-1;previewIsValid=false;render();return;}updateDrag(e.clientX,e.clientY);const anchor=previewAnchor;dragGhost?.remove();dragGhost=null;pointerPiece=-1;pointerStart=null;pointerDragging=false;if(anchor>=0)place(anchor);else{$("feedback").textContent=t("invalid");preview=[];previewIsValid=false;render();}});
$("battleBack").onclick=()=>show("leaveModal","leaveContinue");$("leaveContinue").onclick=()=>hide("leaveModal");$("leaveStage").onclick=()=>{hide("leaveModal");resetRunAsync();clearEffectState();clearScorePop();comboStreak=0;if(endless)setScreen("main");else{setScreen("stage");renderStages();}};$("battleHelp").onclick=()=>show("helpModal","helpClose");$("helpClose").onclick=()=>hide("helpModal");$("resultStageBtn").onclick=()=>{hide("resultModal");setScreen(endless?"main":"stage");renderStages();};$("retryBtn").onclick=()=>start(currentStage,endless);$("nextBtn").onclick=()=>start(Math.min(30,currentStage+1));
function mountEndlessEntry(attempt=0){const copy=document.querySelector(".wp-standard-main-copy"),button=$("endlessBtn");if(copy&&button){button.classList.add("wp-standard-main-secondary");copy.append(button);syncEndlessBest();return;}if(attempt<8)setTimeout(()=>mountEndlessEntry(attempt+1),50);}
window.__BLOCK_BLAST__={stages:STAGES,shapes:SHAPES,terrain:TERRAIN,dirtBlock:DIRT_BLOCK,fits,placements,trayCompletable,objectiveMet,start,place,previewAt,getState:()=>({currentStage,endless,grid:[...grid],terrain:[...terrain],tray:tray.map(s=>({...s,cells:clone(s.cells)})),score,lines,sets,comboStreak,terrainCleared,dirtCleared,iceCleared,gems,colorCleared,unlocked,preview:[...preview],previewAnchor,previewIsValid,flashCells:[...flashCells],effectLines:effectLines.map(line=>({...line}))}),loadFixture:fixture=>{resetRunAsync();clearEffectState();clearScorePop();comboStreak=0;grid=[...(fixture.grid||Array(64).fill(null))];terrain=[...(fixture.terrain||Array(64).fill(0))];for(let index=0;index<64;index++)if(terrain[index]===TERRAIN.DIRT&&grid[index]==null)grid[index]=DIRT_BLOCK;tray=(fixture.tray||[SHAPES[0]]).map((shape,index)=>({...shape,color:index%COLORS.length,used:false,cells:clone(shape.cells)}));selected=-1;preview=[];previewAnchor=-1;previewIsValid=false;score=lines=terrainCleared=dirtCleared=iceCleared=gems=colorCleared=0;sets=1;lastTrayHadLarge=false;setsSinceLarge=setsSinceNine=0;render();},generatorProbe:(g,tr,n=30,stage=currentStage)=>{const old={grid,terrain,currentStage,generation,tray,sets,lastTrayHadLarge,setsSinceLarge,setsSinceNine,endless};grid=[...g];terrain=[...tr];currentStage=stage;generation=0;lastTrayHadLarge=false;setsSinceLarge=setsSinceNine=0;endless=false;const groups=[];for(let i=0;i<n;i++){const generated=generateTray();groups.push({generated,complete:generated&&trayCompletable(tray),pieces:tray.map(s=>({id:s.id,size:s.size,color:s.color,fits:placements(s).length}))});}({grid,terrain,currentStage,generation,tray,sets,lastTrayHadLarge,setsSinceLarge,setsSinceNine,endless}=old);return groups;},endlessGeneratorProbe:(n=80)=>{const old={grid,terrain,currentStage,generation,tray,sets,lastTrayHadLarge,setsSinceLarge,setsSinceNine,endless,score};grid=Array(64).fill(null);terrain=Array(64).fill(0);currentStage=1;generation=sets=score=0;lastTrayHadLarge=false;setsSinceLarge=setsSinceNine=0;endless=true;const groups=[];for(let i=0;i<n;i++){const generated=generateTray();groups.push({generated,complete:generated&&trayCompletable(tray),pieces:tray.map(s=>({id:s.id,size:s.size,cells:s.cells.length}))});}({grid,terrain,currentStage,generation,tray,sets,lastTrayHadLarge,setsSinceLarge,setsSinceNine,endless,score}=old);return groups;}};
const blockBlastGetState=window.__BLOCK_BLAST__.getState;
window.__BLOCK_BLAST__.getState=()=>({...blockBlastGetState(),endlessBest});
window.__BLOCK_BLAST__.getEndlessBest=()=>endlessBest;
applyLocale();syncSound();setScreen("main");setTimeout(()=>{mountEndlessEntry();document.documentElement.dataset.gameReady="true";},0);
})();
