(()=>{'use strict';
  const $=id=>document.getElementById(id),LOCALES=window.AnimalParkingPatrolLocales||{},SUPPORTED=['en','zh-Hant','zh-Hans','es','ja','ko','pt-BR','de'],SAVE_KEY='animalParkingPatrolSaveV1',LOCALE_KEY='animalParkingPatrolLocale',VEHICLES=['fox','otter','panda','lion','owl','turtle','rabbit','rhino'],DIRS=['up','right','down','left'],VECTORS={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]},ARROWS={up:'↑',right:'→',down:'↓',left:'←'},ROTS={up:'0deg',right:'90deg',down:'180deg',left:'-90deg'};
  const memory=new Map(),safeStorage={get(key){try{const value=localStorage.getItem(key);if(value!==null)memory.set(key,value);return value??memory.get(key)??null}catch{return memory.get(key)??null}},set(key,value){memory.set(key,String(value));try{localStorage.setItem(key,String(value));return true}catch{return false}}};
  const normalizeLocale=value=>{const raw=String(value||'').replace('_','-'),low=raw.toLowerCase();if(low.startsWith('zh')&&(low.includes('tw')||low.includes('hk')||low.includes('hant')))return'zh-Hant';if(low.startsWith('zh'))return'zh-Hans';if(low.startsWith('pt'))return'pt-BR';return SUPPORTED.find(item=>low===item.toLowerCase()||low.startsWith(item.toLowerCase().split('-')[0]))||'en'};
  const platformLocale=safeStorage.get('weightPlayLocale')||safeStorage.get('weightplayLocale')||navigator.language,trial=new URLSearchParams(location.search).get('trial')==='1';let lang=normalizeLocale(safeStorage.get(LOCALE_KEY)||platformLocale),save=readSave(),selectedStage=Math.max(0,Math.min(29,save.unlocked-1)),level=null,exited=new Set(),mistakes=0,hints=0,history=[],resolving=false,resultOpen=false,pauseOpen=false,tutorialStartsRoute=false,tutorialReturn=null,toastTimer=0,foregroundTimer=null;
  function freshSave(){return{unlocked:1,completed:Array(30).fill(false),stars:Array(30).fill(0),best:Array(30).fill(null),tutorialSeen:false}}
  function readSave(){try{const parsed=JSON.parse(safeStorage.get(SAVE_KEY)||'null'),base=freshSave();if(!parsed)return base;const unlocked=Math.max(1,Math.min(30,Math.trunc(Number(parsed.unlocked)||1)));return{...base,unlocked,completed:Array.from({length:30},(_,i)=>Boolean(parsed.completed?.[i])),stars:Array.from({length:30},(_,i)=>Math.max(0,Math.min(3,Math.trunc(Number(parsed.stars?.[i])||0)))),best:Array.from({length:30},(_,i)=>parsed.best?.[i]===null||parsed.best?.[i]===undefined?null:Math.max(0,Math.min(2,Math.trunc(Number(parsed.best[i])||0)))),tutorialSeen:Boolean(parsed.tutorialSeen)}}catch{return freshSave()}}
  function persist(){safeStorage.set(SAVE_KEY,JSON.stringify(save))}
  function t(key,vars={}){let value=LOCALES[lang]?.[key]??LOCALES.en?.[key]??key;if(typeof value!=='string')return value;return value.replace(/\{(\w+)\}/g,(_,name)=>vars[name]??'')}
  function chapterText(key,index){return(LOCALES[lang]?.[key]||LOCALES.en?.[key]||[])[index]||''}
  function rng(seed){let state=seed>>>0;return()=>((state=Math.imul(state^state>>>15,1|state),state^=state+Math.imul(state^state>>>7,61|state),(state^state>>>14)>>>0)/4294967296)}
  function shuffle(items,random){for(let i=items.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
  function dependencies(carts,size){const byCell=new Map(carts.map(cart=>[`${cart.x},${cart.y}`,cart.id])),map=new Map();for(const cart of carts){const [dx,dy]=VECTORS[cart.dir],deps=[];let x=cart.x+dx,y=cart.y+dy;while(x>=0&&y>=0&&x<size&&y<size){const id=byCell.get(`${x},${y}`);if(id)deps.push(id);x+=dx;y+=dy}map.set(cart.id,deps)}return map}
  function topo(carts,deps){const pending=new Map([...deps].map(([id,list])=>[id,new Set(list)])),order=[];while(order.length<carts.length){const ready=carts.map(cart=>cart.id).filter(id=>!order.includes(id)&&pending.get(id).size===0);if(!ready.length)return null;const id=ready[0];order.push(id);for(const set of pending.values())set.delete(id)}return order}
  function makeLevel(index){const chapter=Math.floor(index/5),size=index<5?4:index<20?5:6,count=Math.min(size*size-2,6+Math.floor(index*.34));for(let attempt=0;attempt<600;attempt++){const random=rng(0x51f15e+index*7919+attempt*104729),cells=shuffle(Array.from({length:size*size},(_,i)=>[i%size,Math.floor(i/size)]),random).slice(0,count),carts=cells.map(([x,y],i)=>({id:`c${i}`,x,y,dir:DIRS[Math.floor(random()*4)],vehicle:VEHICLES[(i+index)%VEHICLES.length],signal:false,gated:false,lead:null})),deps=dependencies(carts,size),order=topo(carts,deps);if(!order)continue;if(chapter>=2){const signalId=order[Math.min(1,order.length-1)],signal=carts.find(cart=>cart.id===signalId);signal.signal=true;order.slice(2).forEach((id,pos)=>{if((pos+index)%3===0)carts.find(cart=>cart.id===id).gated=true})}if(chapter>=3){order.slice(chapter>=5?2:4).forEach((id,pos)=>{if((pos+index)%4===1){const current=order.indexOf(id),lead=order[Math.max(0,current-1)];if(lead!==id)carts.find(cart=>cart.id===id).lead=lead}})}return{index,chapter,size,carts,solution:order,moveLimit:count}}throw new Error(`Unable to build level ${index+1}`)}
  const LEVELS=Array.from({length:30},(_,index)=>makeLevel(index));
  function setScreen(screen){cancelForeground();$('mainGroup').hidden=screen!=='main';$('stageScreen').hidden=screen!=='stage';$('battleScreen').hidden=screen!=='battle';document.body.classList.toggle('playing',screen!=='main');document.body.classList.toggle('wp-logical-stage-active',screen==='stage');document.body.classList.toggle('wp-logical-battle-active',screen==='battle');if(screen!=='battle'){closeResult(false);closeLeave(false);closePause(false)}}
  function updateSoundButton(){const sound=window.WonderSound,muted=sound?.isMuted?.()??false;$('soundBtn').textContent=t(muted?'soundOn':'soundOff');$('soundBtn').setAttribute('aria-pressed',String(!muted));$('soundBtn').disabled=!sound}
  function applyLocale(){document.documentElement.lang=lang;$('localeSelect').value=lang;document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));document.querySelectorAll('[data-i18n-aria]').forEach(node=>node.setAttribute('aria-label',t(node.dataset.i18nAria)));document.querySelectorAll('[data-i18n-alt]').forEach(node=>node.setAttribute('alt',t(node.dataset.i18nAlt)));document.title=`${t('title')} | WeightPlay`;updateSoundButton();window.dispatchEvent(new CustomEvent('wonder:locale-change',{detail:{locale:lang}}));renderMain();if(!$('stageScreen').hidden)renderStage();if(!$('battleScreen').hidden&&level)renderBattle()}
  function renderMain(){const done=save.completed.filter(Boolean).length,stars=save.stars.reduce((sum,value)=>sum+value,0);$('mainProgress').textContent=t('progress',{done,stars})}
  function showMain(focus=false){setScreen('main');renderMain();if(focus)requestAnimationFrame(()=>$('startBtn').focus({preventScroll:true}))}
  function renderStage(){const done=save.completed.filter(Boolean).length,stars=save.stars.reduce((sum,value)=>sum+value,0),item=LEVELS[selectedStage],rail=$('stageRail');$('stageSummary').textContent=t('summary',{done,stars});$('chapterKicker').textContent=t('chapter',{n:item.chapter+1});$('chapterTitle').textContent=chapterText('chapters',item.chapter);$('chapterRule').textContent=chapterText('rules',item.chapter);rail.innerHTML='';rail.dataset.wpStageRecommendation='explicit';LEVELS.forEach((route,index)=>{const locked=index>=save.unlocked,centered=index===selectedStage,card=document.createElement('button');card.type='button';card.className=`stage-card${locked?' locked':''}${centered?' selected is-centered':''}`;card.setAttribute('aria-disabled',String(locked));if(centered)card.setAttribute('aria-current','true');card.dataset.stage=String(index);card.dataset.stageIndex=String(index);if(centered&&!locked)card.dataset.wpStageRecommended='true';const starsText='★'.repeat(save.stars[index]||0)+'☆'.repeat(3-(save.stars[index]||0));card.innerHTML=`<small>${t('chapter',{n:route.chapter+1})}</small><strong>${t('stage',{n:index+1})}</strong><span>${locked?t('locked'):save.completed[index]?t('cleared'):t('goal',{n:route.carts.length})}</span><span>${t('mistakeGoal')}</span><b class="stars">${locked?'':starsText}</b>`;card.onclick=()=>{if(rail.dataset.dragging==='true'||locked)return;selectedStage=index;startLevel(index)};card.addEventListener('keydown',rejectRepeat);rail.append(card)});requestAnimationFrame(()=>{const target=rail.querySelector(`[data-stage="${selectedStage}"]`);target?.scrollIntoView({behavior:'auto',block:'nearest',inline:'center'})})}
  function showStage(focus=false){selectedStage=Math.max(0,Math.min(29,save.unlocked-1));setScreen('stage');renderStage();if(focus)requestAnimationFrame(()=>$('stageBackBtn').focus({preventScroll:true}))}
  function startLevel(index){cancelForeground();closePause(false);selectedStage=Math.max(0,Math.min(29,index));level=LEVELS[selectedStage];exited=new Set();mistakes=0;hints=0;history=[];resolving=false;resultOpen=false;setScreen('battle');$('stageLabel').textContent=t('stage',{n:selectedStage+1});$('stageGoal').textContent=t('goal',{n:level.carts.length});renderBattle();requestAnimationFrame(()=>$('battleBackBtn').focus({preventScroll:true}));track('game_start',{stage:selectedStage+1})}
  function activeCarts(){return level.carts.filter(cart=>!exited.has(cart.id))}
  function signalOpen(){const signal=level.carts.find(cart=>cart.signal);return !signal||exited.has(signal.id)}
  function pathBlocker(cart){const [dx,dy]=VECTORS[cart.dir];return activeCarts().find(other=>other.id!==cart.id&&((dx&&other.y===cart.y&&Math.sign(other.x-cart.x)===dx)||(dy&&other.x===cart.x&&Math.sign(other.y-cart.y)===dy)))||null}
  function availability(cart){if(cart.gated&&!signalOpen())return'signal';if(cart.lead&&!exited.has(cart.lead))return'convoy';if(pathBlocker(cart))return'path';return'ok'}
  function cartRule(cart){if(cart.signal)return t('signalRule');if(cart.gated&&!signalOpen())return t('gatedRule');if(cart.lead&&!exited.has(cart.lead))return t('convoyRule');return''}
  function renderBattle(){if(!level)return;const board=$('trafficBoard');board.style.setProperty('--size',level.size);board.innerHTML='';for(const cart of activeCarts()){const button=document.createElement('button'),animalIndex=VEHICLES.indexOf(cart.vehicle),state=availability(cart);button.type='button';button.className=`cart${state==='ok'?' available':''}${state==='signal'?' blocked-signal':''}`;button.dataset.cart=cart.id;button.style.setProperty('--x',cart.x);button.style.setProperty('--y',cart.y);button.style.setProperty('--rot',ROTS[cart.dir]);button.style.setProperty('--tx',`${VECTORS[cart.dir][0]*720}%`);button.style.setProperty('--ty',`${VECTORS[cart.dir][1]*720}%`);button.setAttribute('aria-label',t('cartLabel',{animal:(t('animals')||[])[animalIndex]||cart.vehicle,direction:t('directions')?.[cart.dir]||cart.dir,rule:cartRule(cart)}));const badge=cart.signal?'✦':cart.gated&&!signalOpen()?'●':cart.lead&&!exited.has(cart.lead)?'⛓':'';button.innerHTML=`<img src="../../assets/animal-parking-patrol-vehicle-${cart.vehicle}.webp" alt="" /><span class="direction" aria-hidden="true">${ARROWS[cart.dir]}</span>${badge?`<span class="rule-badge" aria-hidden="true">${badge}</span>`:''}`;button.onclick=()=>tapCart(cart.id);button.addEventListener('keydown',rejectRepeat);board.append(button)}$('leftValue').textContent=activeCarts().length;$('safetyValue').textContent=Math.max(0,3-mistakes);$('objectiveBar').textContent=t('objective',{safety:Math.max(0,3-mistakes)});$('undoBtn').disabled=!history.length||resolving}
  function snapshot(){return{exited:[...exited],mistakes,hints}}
  function restore(state){exited=new Set(state.exited);mistakes=state.mistakes;hints=state.hints;resolving=false;renderBattle()}
  function tapCart(id){if(resolving||resultOpen)return;const cart=level.carts.find(item=>item.id===id);if(!cart||exited.has(id))return;const state=availability(cart);history.push(snapshot());if(state!=='ok'){mistakes++;const node=$('trafficBoard').querySelector(`[data-cart="${id}"]`);node?.classList.add('bump');showToast(t(state==='signal'?'signalPending':state==='convoy'?'convoyPending':'pathBlocked'));renderStatsOnly();if(mistakes>=3){resolving=true;scheduleForeground(()=>finishFail(),340)}else setTimeout(()=>{node?.classList.remove('bump');$('undoBtn').disabled=false},300);return}resolving=true;const node=$('trafficBoard').querySelector(`[data-cart="${id}"]`);node?.classList.add('exiting');const opens=cart.signal&&!signalOpen();scheduleForeground(()=>{exited.add(id);resolving=false;if(opens)showToast(t('signalCleared'));else showToast(t('safeExit'));renderBattle();if(!activeCarts().length)scheduleForeground(()=>finishWin(),220)},430)}
  function renderStatsOnly(){$('safetyValue').textContent=Math.max(0,3-mistakes);$('objectiveBar').textContent=t('objective',{safety:Math.max(0,3-mistakes)});$('undoBtn').disabled=!history.length||resolving}
  function undo(){if(resolving||resultOpen)return;if(!history.length){showToast(t('nothingUndo'));return}restore(history.pop());showToast(t('restored'))}
  function restart(){if(resolving||resultOpen)return;exited=new Set();mistakes=0;hints=0;history=[];renderBattle();showToast(t('restarted'))}
  function hint(){if(resolving||resultOpen)return;const cart=activeCarts().find(item=>availability(item)==='ok');if(!cart){showToast(t('noHint'));return}hints++;const node=$('trafficBoard').querySelector(`[data-cart="${cart.id}"]`);node?.classList.add('hint');setTimeout(()=>node?.classList.remove('hint'),2300);showToast(t('hintReady'))}
  function finishWin(){resolving=false;const previous=save.best[selectedStage],stars=hints?Math.min(2,3-mistakes):3-mistakes;save.completed[selectedStage]=true;save.stars[selectedStage]=Math.max(save.stars[selectedStage],stars);save.best[selectedStage]=previous===null?mistakes:Math.min(previous,mistakes);save.unlocked=Math.max(save.unlocked,Math.min(30,selectedStage+2));persist();$('resultTitle').textContent=t('winTitle');$('resultStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('resultText').textContent=t('winText',{stage:selectedStage+1,mistakes});$('bestText').textContent=previous===null||mistakes<previous?t('newBest'):t('best',{n:save.best[selectedStage]});$('nextBtn').hidden=selectedStage===29;openResult();track('game_complete',{stage:selectedStage+1,mistakes,stars})}
  function finishFail(){resolving=false;$('resultTitle').textContent=t('failTitle');$('resultStars').textContent='';$('resultText').textContent=t('failText');$('bestText').textContent=save.best[selectedStage]===null?'':t('best',{n:save.best[selectedStage]});$('nextBtn').hidden=true;openResult();track('game_fail',{stage:selectedStage+1})}
  function coverBattle(owner,covered){const canvas=$('battleBackBtn').closest('.battle-canvas');canvas.querySelectorAll(':scope > *').forEach(node=>{if(node===owner||node.id==='resultPanel'&&owner.id==='leavePanel'||node.id==='leavePanel'&&owner.id==='resultPanel')return;node.inert=covered;if(covered)node.setAttribute('aria-hidden','true');else node.removeAttribute('aria-hidden')})}
  function openResult(){clearTimeout(toastTimer);$('toast').classList.remove('show');resultOpen=true;$('resultPanel').hidden=false;$('resultPanel').inert=false;coverBattle($('resultPanel'),true);requestAnimationFrame(()=>(!$('nextBtn').hidden?$('nextBtn'):$('retryBtn')).focus({preventScroll:true}))}
  function closeResult(restoreFocus=true){if(!$('resultPanel'))return;resultOpen=false;$('resultPanel').hidden=true;$('resultPanel').inert=true;coverBattle($('resultPanel'),false);if(restoreFocus)requestAnimationFrame(()=>$('battleBackBtn').focus({preventScroll:true}))}
  function requestLeave(){if(resolving||resultOpen)return;if(!exited.size&&!mistakes){showStage(true);return}$('leavePanel').hidden=false;$('leavePanel').inert=false;coverBattle($('leavePanel'),true);requestAnimationFrame(()=>$('leaveContinueBtn').focus({preventScroll:true}))}
  function closeLeave(restoreFocus=true){if(!$('leavePanel'))return;$('leavePanel').hidden=true;$('leavePanel').inert=true;coverBattle($('leavePanel'),false);if(restoreFocus)requestAnimationFrame(()=>$('battleBackBtn').focus({preventScroll:true}))}
  function openPause(){if(pauseOpen||resultOpen||!$('leavePanel').hidden)return;pauseOpen=true;pauseForeground();clearTimeout(toastTimer);$('toast').classList.remove('show');updateSoundButton();$('pausePanel').hidden=false;$('pausePanel').inert=false;coverBattle($('pausePanel'),true);requestAnimationFrame(()=>$('pauseResumeBtn').focus({preventScroll:true}))}
  function closePause(restoreFocus=true){if(!$('pausePanel'))return;$('pausePanel').hidden=true;$('pausePanel').inert=true;if(!pauseOpen)return;pauseOpen=false;coverBattle($('pausePanel'),false);resumeForeground();if(restoreFocus)$('pauseBtn').focus({preventScroll:true})}
  function openTutorial(startsRoute,returnTarget){tutorialStartsRoute=Boolean(startsRoute);tutorialReturn=returnTarget||null;$('tutorialStartBtn').textContent=t(tutorialStartsRoute?'tutorialStart':'close');$('tutorialPanel').hidden=false;$('tutorialPanel').inert=false;if(!$('stageScreen').hidden)$('stageScreen').inert=true;if(!$('battleScreen').hidden)$('battleScreen').inert=true;requestAnimationFrame(()=>$('tutorialStartBtn').focus({preventScroll:true}))}
  function focusTrap(panel,event){if(event.key==='Escape'){if(panel.id==='leavePanel'){event.preventDefault();closeLeave(true);return}if(panel.id==='pausePanel'){event.preventDefault();closePause(true);return}if(panel.id==='tutorialPanel'){event.preventDefault();closeTutorial(false);return}}if(event.key!=='Tab')return;const actions=[...panel.querySelectorAll('button:not([hidden]):not(:disabled)')].filter(node=>node.getClientRects().length);if(!actions.length)return;const index=actions.indexOf(document.activeElement),next=event.shiftKey?(index<=0?actions.length-1:index-1):(index>=actions.length-1?0:index+1);event.preventDefault();actions[next].focus({preventScroll:true})}
  function showToast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1450)}
  function rejectRepeat(event){if((event.key==='Enter'||event.key===' ')&&event.repeat){event.preventDefault();event.stopImmediatePropagation()}}
  function track(name,data={}){window.WeightPlayAnalytics?.track?.(name,{game:'animal-parking-patrol',internal:trial,...data})}
  function scheduleForeground(fn,delay){cancelForeground();foregroundTimer={fn,remaining:delay,started:performance.now(),id:0};resumeForeground()}
  function resumeForeground(){if(!foregroundTimer||document.hidden)return;foregroundTimer.started=performance.now();foregroundTimer.id=setTimeout(()=>{const fn=foregroundTimer?.fn;foregroundTimer=null;fn?.()},foregroundTimer.remaining)}
  function pauseForeground(){if(!foregroundTimer||!foregroundTimer.id)return;clearTimeout(foregroundTimer.id);foregroundTimer.remaining=Math.max(0,foregroundTimer.remaining-(performance.now()-foregroundTimer.started));foregroundTimer.id=0}
  function cancelForeground(){if(foregroundTimer?.id)clearTimeout(foregroundTimer.id);foregroundTimer=null}
  document.addEventListener('visibilitychange',()=>document.hidden?pauseForeground():resumeForeground());
  $('localeSelect').onchange=()=>{lang=normalizeLocale($('localeSelect').value);safeStorage.set(LOCALE_KEY,lang);safeStorage.set('weightPlayLocale',lang);applyLocale()};$('startBtn').onclick=()=>{showStage(true);track('stage_open');if(!save.tutorialSeen)openTutorial(true,$('stageBackBtn'))};$('stageBackBtn').onclick=()=>showMain(true);$('stageHelpBtn').onclick=()=>openTutorial(false,$('stageHelpBtn'));$('battleBackBtn').onclick=requestLeave;$('pauseBtn').onclick=openPause;$('pauseResumeBtn').onclick=()=>closePause(true);$('soundBtn').onclick=()=>{const sound=window.WonderSound;if(!sound)return;sound.setMuted(!sound.isMuted());updateSoundButton()};$('pauseHelpBtn').onclick=()=>openTutorial(false,$('pauseHelpBtn'));$('undoBtn').onclick=undo;$('restartBtn').onclick=restart;$('hintBtn').onclick=hint;$('retryBtn').onclick=()=>{closeResult(false);startLevel(selectedStage)};$('resultStagesBtn').onclick=()=>{closeResult(false);showStage(true)};$('nextBtn').onclick=()=>{closeResult(false);startLevel(Math.min(29,selectedStage+1))};$('leaveContinueBtn').onclick=()=>closeLeave(true);$('leaveStagesBtn').onclick=()=>{closeLeave(false);showStage(true)};
  function closeTutorial(start){$('tutorialPanel').hidden=true;$('tutorialPanel').inert=true;$('stageScreen').inert=false;$('battleScreen').inert=false;save.tutorialSeen=true;persist();const shouldStart=start&&tutorialStartsRoute,returnTarget=tutorialReturn;tutorialStartsRoute=false;tutorialReturn=null;if(shouldStart)startLevel(0);else returnTarget?.focus({preventScroll:true})}$('tutorialCloseBtn').onclick=()=>closeTutorial(false);$('tutorialStartBtn').onclick=()=>closeTutorial(tutorialStartsRoute);
  ['startBtn','stageBackBtn','stageHelpBtn','battleBackBtn','pauseBtn','pauseResumeBtn','soundBtn','pauseHelpBtn','undoBtn','restartBtn','hintBtn','retryBtn','resultStagesBtn','nextBtn','leaveContinueBtn','leaveStagesBtn','tutorialCloseBtn','tutorialStartBtn'].forEach(id=>$(id).addEventListener('keydown',rejectRepeat));$('leavePanel').addEventListener('keydown',event=>focusTrap($('leavePanel'),event));$('pausePanel').addEventListener('keydown',event=>focusTrap($('pausePanel'),event));$('resultPanel').addEventListener('keydown',event=>focusTrap($('resultPanel'),event));$('tutorialPanel').addEventListener('keydown',event=>focusTrap($('tutorialPanel'),event));$('stageRail').addEventListener('wonder:stage-snap',event=>{const index=Number(event.detail?.index);if(!Number.isInteger(index)||!LEVELS[index])return;selectedStage=index;$('stageRail').querySelectorAll('.stage-card').forEach(card=>{const active=Number(card.dataset.stage)===index;card.classList.toggle('selected',active);card.classList.toggle('is-centered',active);if(active)card.setAttribute('aria-current','true');else card.removeAttribute('aria-current');delete card.dataset.wpStageRecommended});const item=LEVELS[index];$('chapterKicker').textContent=t('chapter',{n:item.chapter+1});$('chapterTitle').textContent=chapterText('chapters',item.chapter);$('chapterRule').textContent=chapterText('rules',item.chapter)});
  window.__animalParkingPatrolTest={LEVELS,getState:()=>({lang,selectedStage,remaining:level?activeCarts().length:0,mistakes,hints,exited:[...exited],unlocked:save.unlocked,resultOpen}),startLevel,showStage,tapCart,availability:cart=>availability(typeof cart==='string'?level.carts.find(item=>item.id===cart):cart),makeLevel,readSave};
  applyLocale();const assets=['../../assets/animal-parking-patrol-cover.webp','../../assets/animal-parking-patrol-background.webp','../../assets/weightplay-character-moon-cap-owl-cutout.webp',...VEHICLES.map(name=>`../../assets/animal-parking-patrol-vehicle-${name}.webp`)];let loaded=0;Promise.allSettled(assets.map(src=>new Promise(resolve=>{const image=new Image(),done=()=>{loaded++;$('loadingBar').style.width=`${loaded/assets.length*100}%`;resolve()};image.onload=done;image.onerror=done;image.src=src}))).then(()=>setTimeout(()=>{$('loadingPanel').hidden=true;showMain();track('game_view',{release:'internal'})},140));
})();
