/* Game-specific concise copy, applied before runtime locale initialization. */
(() => {
  'use strict';
  const copy = {
    en: ['Recruit soldiers, merge matching units and defend all three lanes.', 'Select two soldiers of the same type and level to merge. Keep every lane defended and use general skills when enemies press forward.'],
    'zh-Hant': ['招募士兵、合成同類單位，守住三條路線。', '依序點選同兵種、同等級的兩名士兵即可合成。每條路線都要留兵防守，敵軍逼近時使用武將技能。'],
    'zh-Hans': ['招募士兵、合成同类单位，守住三条路线。', '依次点选同兵种、同等级的两名士兵即可合成。每条路线都要留兵防守，敌军逼近时使用武将技能。'],
    ja: ['兵士を募集・合成して、3本の進路を守ろう。', '同じ兵種・レベルの兵士を2体選ぶと合成できます。各進路に守備兵を残し、敵が迫ったら武将のスキルを使いましょう。'],
    ko: ['병사를 모집하고 합성해 세 경로를 지키세요.', '병종과 레벨이 같은 병사 둘을 차례로 선택해 합성하세요. 각 경로에 수비병을 남기고 적이 다가오면 장수 기술을 사용하세요.'],
    es: ['Recluta y fusiona soldados para defender las tres rutas.', 'Selecciona dos soldados del mismo tipo y nivel para fusionarlos. Mantén defensores en cada ruta y usa las habilidades de los generales cuando avance el enemigo.'],
    'pt-BR': ['Recrute e combine soldados para defender as três rotas.', 'Selecione dois soldados do mesmo tipo e nível para combiná-los. Mantenha defensores em cada rota e use as habilidades dos generais quando os inimigos avançarem.'],
    fr: ['Recrutez et fusionnez vos soldats pour défendre les trois voies.', 'Sélectionnez deux soldats de même type et de même niveau pour les fusionner. Gardez chaque voie défendue et utilisez les compétences des généraux face à la pression ennemie.'],
    de: ['Rekrutiere und vereine Soldaten, um alle drei Wege zu verteidigen.', 'Wähle zwei Soldaten gleichen Typs und gleicher Stufe zum Vereinen. Lass jeden Weg bewacht und nutze die Fähigkeiten der Generäle, wenn Gegner vorrücken.'],
    it: ['Recluta e unisci soldati per difendere tutte e tre le corsie.', 'Seleziona due soldati dello stesso tipo e livello per unirli. Lascia difensori in ogni corsia e usa le abilità dei generali quando i nemici avanzano.'],
    ru: ['Нанимайте и объединяйте солдат, защищая три линии.', 'Выберите двух солдат одного типа и уровня для объединения. Оставляйте защитников на каждой линии и используйте умения полководцев при наступлении врага.'],
    hi: ['सैनिक भर्ती और मिलान करके तीनों रास्तों की रक्षा करें।', 'एक ही प्रकार और स्तर के दो सैनिक चुनकर उन्हें मिलाएँ। हर रास्ते पर रक्षक रखें और दुश्मन पास आने पर सेनापतियों की क्षमताएँ इस्तेमाल करें।'],
    ar: ['جنّد الجنود وادمج الوحدات المتطابقة للدفاع عن المسارات الثلاثة.', 'اختر جنديين من النوع والمستوى نفسيهما لدمجهما. أبقِ مدافعين في كل مسار واستخدم مهارات القادة عندما يتقدم الأعداء.'],
  };
  const presentation = {
    en: ['Start Game', 'Block-style Zhao Yun and soldiers protecting A Dou'],
    'zh-Hant': ['開始遊戲', '方塊風格的趙雲與士兵保護阿斗'],
    'zh-Hans': ['开始游戏', '方块风格的赵云与士兵保护阿斗'],
    ja: ['ゲーム開始', '阿斗を守るブロック風の趙雲と兵士たち'],
    ko: ['게임 시작', '아두를 지키는 블록 스타일의 조운과 병사들'],
    es: ['Iniciar juego', 'Zhao Yun y sus soldados de estilo cúbico protegen a A Dou'],
    'pt-BR': ['Iniciar jogo', 'Zhao Yun e seus soldados em estilo de blocos protegem A Dou'],
    fr: ['Commencer le jeu', 'Zhao Yun et ses soldats en style cubique protègent A Dou'],
    de: ['Spiel starten', 'Zhao Yun und seine Soldaten im Blockstil beschützen A Dou'],
    it: ['Inizia il gioco', 'Zhao Yun e i suoi soldati in stile a blocchi proteggono A Dou'],
    ru: ['Начать игру', 'Чжао Юнь и солдаты в блочном стиле защищают А-Доу'],
    hi: ['खेल शुरू करें', 'ब्लॉक शैली में झाओ युन और सैनिक आ-दो की रक्षा करते हैं'],
    ar: ['ابدأ اللعبة', 'تشاو يون وجنوده بأسلوب المكعبات يحمون آ دو'],
  };
  for (const [locale, [summary, guideBody]] of Object.entries(copy)) {
    const [start, posterAlt] = presentation[locale];
    Object.assign(window.ZHAO_YUN_ADOU_LOCALES[locale], {summary, guideBody, start, posterAlt});
  }
})();

// v27 mechanics: every public locale owns its dynamic battle vocabulary.
(() => {
  const keys='best|chargeLane|commandHelp|waveReward|renderError|rule_coverage|rule_merge|rule_reach|rule_reserve|rule_shield|rule_charge|rule_flank|rule_mud|rule_rally|rule_medic|rule_fog|rule_summon|rule_finale|boss_bulwark|boss_charger|boss_weaver|boss_healer|boss_summoner|boss_warlord|enemy_soldier|enemy_shield|enemy_raider|enemy_flanker|enemy_medic|counter_blade|counter_spear|counter_horse|counter_bow'.split('|');
  const rows={
    en:'Best|Aim: {lane}|Choose a lane, then use Dragon Charge. Select troop cards before recruiting.|Wave clear: +4 buns|The 3D scene stopped. Retry to resume this battle.|Cover three lanes|Merge, then fill the gap|Archers reach distant enemies|Supplies recover slowly|Blades pierce shields|Stop the warned charge|Watch for a lane switch|Mud slows one lane|The marked lane gains +2 damage|Archers target medics first|Fog shortens attack range|Stop the summoner|Combine counters for the finale|Iron Gate|Vanguard|Lane Weaver|Jade Medic|War Drummer|Changban Warlord|Soldier|Shield guard|Raider|Flanker|Medic|Pierces shields; hits nearby enemies|Briefly stops the target|Heavy close-range damage|Long range; targets medics first',
    'zh-Hant':'最佳|瞄準：{lane} 路|選擇路線後施放龍騎突襲；先選兵種再徵召。|本波守住：饅頭 +4|3D 戰場暫停，重試即可繼續本局。|守住三條路線|合成後補上防線|弓兵迎擊遠方敵人|補給恢復較慢|刀兵穿透護盾|阻止預警後的衝鋒|留意敵人換線|泥地減慢一路敵人|標記路線傷害 +2|弓兵優先射擊醫兵|迷霧縮短射程|阻止召喚援兵|組合剋制迎接決戰|鐵門守將|破陣先鋒|換線奇將|青玉醫將|戰鼓召將|長坂督軍|步兵|盾衛|突騎|奇兵|醫兵|穿透護盾並波及鄰近敵人|短暫阻止目標前進|近距離重擊|遠距離攻擊，優先射擊醫兵',
    'zh-Hans':'最佳|瞄准：{lane} 路|选择路线后施放龙骑突袭；先选兵种再征召。|本波守住：馒头 +4|3D 战场暂停，重试即可继续本局。|守住三条路线|合成后补上防线|弓兵迎击远方敌人|补给恢复较慢|刀兵穿透护盾|阻止预警后的冲锋|留意敌人换线|泥地减慢一路敌人|标记路线伤害 +2|弓兵优先射击医兵|迷雾缩短射程|阻止召唤援兵|组合克制迎接决战|铁门守将|破阵先锋|换线奇将|青玉医将|战鼓召将|长坂督军|步兵|盾卫|突骑|奇兵|医兵|穿透护盾并波及邻近敌人|短暂阻止目标前进|近距离重击|远距离攻击，优先射击医兵',
    ja:'ベスト|狙い：{lane}|進路を選んで龍騎突襲。募集前に兵種を選ぼう。|波を撃退：饅頭 +4|3D表示が停止しました。再試行で戦闘を続けます。|3本の進路を守ろう|合成後に守備を補充|弓兵は遠くの敵を攻撃|補給の回復が遅い|刀兵は盾を貫く|予告された突撃を止めよう|敵の進路変更に注意|泥が1本の進路を減速|印の進路はダメージ +2|弓兵は衛生兵を優先|霧で射程が短くなる|援軍の召喚を止めよう|相性を組み合わせて決戦へ|鉄門の守将|突撃の先鋒|進路の策士|翡翠の医将|戦鼓の召将|長坂の督軍|歩兵|盾兵|騎兵|奇襲兵|衛生兵|盾を貫き周囲にも攻撃|標的を短時間停止|近距離の強打|長射程、衛生兵を優先',
    ko:'최고|조준: {lane}|경로를 고르고 용기 돌격을 쓰세요. 모집 전에 병종을 선택하세요.|공세 방어: 만두 +4|3D 장면이 멈췄습니다. 다시 시도하면 전투가 계속됩니다.|세 경로를 지키세요|합성 후 빈자리를 채우세요|궁수로 먼 적을 공격|보급 회복이 느립니다|검병은 방패를 관통|예고된 돌격을 막으세요|적의 경로 변경에 주의|진흙이 한 경로의 적을 감속|표시된 경로 피해 +2|궁수는 의무병을 우선 공격|안개가 사거리를 줄입니다|증원 소환을 막으세요|상성을 조합해 결전에 도전|철문 수장|돌격 선봉|경로 책사|비취 의장|전고 소환장|장판 감독관|보병|방패병|기습 기병|측면병|의무병|방패 관통 및 주변 공격|대상을 잠시 정지|근거리 강타|긴 사거리, 의무병 우선',
    es:'Mejor|Apuntar: {lane}|Elige una ruta y usa Carga del dragón. Elige tropa antes de reclutar.|Oleada superada: +4 bollos|La escena 3D se detuvo. Reintenta para continuar.|Defiende las tres rutas|Fusiona y cubre el hueco|Arqueros contra enemigos lejanos|Los suministros se recuperan lento|Las espadas atraviesan escudos|Frena la carga anunciada|Vigila los cambios de ruta|El barro frena una ruta|La ruta marcada da +2 de daño|Arqueros: médicos primero|La niebla reduce el alcance|Detén al invocador|Combina tácticas para la final|Guardián de hierro|Vanguardia|Tejedor de rutas|Médico de jade|Tambor de guerra|Señor de Changban|Soldado|Escudero|Asaltante|Flanqueador|Médico|Atraviesa escudos y golpea grupos|Detiene al objetivo brevemente|Gran daño a corta distancia|Largo alcance; prioriza médicos',
    'pt-BR':'Melhor|Mira: {lane}|Escolha a rota e use Investida do Dragão. Escolha a tropa antes de recrutar.|Onda vencida: +4 pães|A cena 3D parou. Tente novamente para continuar.|Defenda as três rotas|Combine e cubra a abertura|Arqueiros atingem inimigos distantes|Suprimentos voltam devagar|Lâminas atravessam escudos|Pare a investida anunciada|Observe mudanças de rota|Lama desacelera uma rota|Rota marcada causa +2 de dano|Arqueiros priorizam médicos|Névoa reduz o alcance|Pare o invocador|Combine táticas na final|Guardião de ferro|Vanguarda|Tecelão de rotas|Médico de jade|Tambor de guerra|Senhor de Changban|Soldado|Guarda de escudo|Invasor|Flanqueador|Médico|Perfura escudos e atinge grupos|Para o alvo por um instante|Dano forte a curta distância|Longo alcance; prioriza médicos',
    fr:'Record|Cible : {lane}|Choisissez une voie puis la Charge du dragon. Choisissez une troupe avant de recruter.|Vague repoussée : +4 pains|La scène 3D est arrêtée. Réessayez pour reprendre.|Défendez les trois voies|Fusionnez puis comblez le vide|Les archers touchent de loin|Le ravitaillement revient lentement|Les lames percent les boucliers|Arrêtez la charge annoncée|Attention aux changements de voie|La boue ralentit une voie|La voie marquée inflige +2 dégâts|Les archers visent les soigneurs|La brume réduit la portée|Arrêtez l’invocateur|Combinez les tactiques en finale|Gardien de fer|Avant-garde|Tisseur de voies|Soigneur de jade|Tambour de guerre|Seigneur de Changban|Soldat|Garde au bouclier|Pillard|Flanqueur|Soigneur|Perce les boucliers et frappe un groupe|Arrête brièvement la cible|Frappe puissante à courte portée|Longue portée ; vise les soigneurs',
    de:'Bestzeit|Ziel: {lane}|Wähle einen Weg, dann den Drachenangriff. Wähle vor dem Rekrutieren einen Trupp.|Welle geschafft: +4 Brötchen|Die 3D-Szene wurde angehalten. Erneut versuchen setzt den Kampf fort.|Verteidige drei Wege|Vereine und schließe die Lücke|Bogenschützen treffen aus der Ferne|Vorräte erholen sich langsam|Klingen durchdringen Schilde|Stoppe den angekündigten Ansturm|Achte auf Wegwechsel|Schlamm bremst einen Weg|Markierter Weg: +2 Schaden|Bogenschützen zielen auf Heiler|Nebel verkürzt die Reichweite|Stoppe den Beschwörer|Kombiniere Konter im Finale|Eisenwächter|Vorhut|Wegwechsler|Jadeheiler|Kriegstrommler|Feldherr von Changban|Soldat|Schildwache|Reiter|Flankierer|Heiler|Durchdringt Schilde, trifft Gruppen|Hält das Ziel kurz auf|Starker Nahkampfschaden|Hohe Reichweite; Heiler zuerst',
    it:'Record|Mira: {lane}|Scegli una corsia e usa Carica del drago. Scegli le truppe prima di reclutarle.|Ondata superata: +4 panini|La scena 3D si è fermata. Riprova per continuare.|Difendi tutte e tre le corsie|Unisci e copri il varco|Gli arcieri colpiscono da lontano|I rifornimenti tornano lentamente|Le lame perforano gli scudi|Ferma la carica annunciata|Attento ai cambi di corsia|Il fango rallenta una corsia|Corsia segnata: +2 danni|Gli arcieri mirano ai guaritori|La nebbia riduce la gittata|Ferma l’evocatore|Combina le tattiche nella finale|Guardiano di ferro|Avanguardia|Tessitore di corsie|Guaritore di giada|Tamburo di guerra|Signore di Changban|Soldato|Scudiero|Incursore|Aggiratore|Guaritore|Perfora gli scudi e colpisce gruppi|Ferma brevemente il bersaglio|Danno elevato da vicino|Lunga gittata; guaritori per primi',
    ru:'Рекорд|Цель: {lane}|Выберите линию и примените рывок дракона. Выбирайте тип войск перед наймом.|Волна отражена: +4 булочки|Сцена 3D остановлена. Повторите, чтобы продолжить бой.|Защитите три линии|Объедините и закройте брешь|Лучники бьют издалека|Припасы восстанавливаются медленно|Клинки пробивают щиты|Остановите объявленную атаку|Следите за сменой линии|Грязь замедляет одну линию|На отмеченной линии урон +2|Лучники сначала бьют лекарей|Туман сокращает дальность|Остановите призывателя|Сочетайте тактики в финале|Железный страж|Авангард|Ткач линий|Нефритовый лекарь|Боевой барабанщик|Владыка Чанбаня|Солдат|Щитоносец|Налётчик|Обходчик|Лекарь|Пробивает щиты и бьёт группу|Ненадолго останавливает цель|Сильный удар вблизи|Дальний бой; лекари в приоритете',
    hi:'सर्वश्रेष्ठ|निशाना: {lane}|रास्ता चुनकर ड्रैगन धावा चलाएँ। भर्ती से पहले सैनिक प्रकार चुनें।|लहर रोकी: +4 बन|3D दृश्य रुक गया। लड़ाई जारी रखने के लिए फिर कोशिश करें।|तीनों रास्तों की रक्षा करें|मिलाएँ फिर खाली जगह भरें|तीरंदाज़ दूर के शत्रु मारते हैं|रसद धीरे लौटती है|तलवारें ढाल भेदती हैं|चेतावनी वाले धावे को रोकें|शत्रु के रास्ता बदलने पर ध्यान दें|कीचड़ एक रास्ते को धीमा करता है|चिह्नित रास्ते पर +2 क्षति|तीरंदाज़ पहले चिकित्सक मारते हैं|कोहरा मारक दूरी घटाता है|सहायक बुलाने वाले को रोकें|अंतिम युद्ध में रणनीतियाँ मिलाएँ|लौह रक्षक|अग्रदूत|रास्ता बदलने वाला|जेड चिकित्सक|युद्ध ढोलकिया|चांगबान सेनापति|सैनिक|ढाल रक्षक|हमलावर|घेरने वाला|चिकित्सक|ढाल भेदता है और समूह पर वार करता है|लक्ष्य को थोड़ी देर रोकता है|पास से भारी क्षति|लंबी दूरी; चिकित्सक पहले',
    ar:'الأفضل|التصويب: {lane}|اختر مسارًا ثم استخدم اندفاع التنين. اختر نوع الجندي قبل التجنيد.|تم صد الموجة: +4 خبز|توقف المشهد ثلاثي الأبعاد. أعد المحاولة لمتابعة المعركة.|احمِ المسارات الثلاثة|ادمج ثم املأ الفراغ|الرماة يضربون من بعيد|الإمدادات تتعافى ببطء|السيوف تخترق الدروع|أوقف الاندفاع بعد التحذير|راقب تبديل المسارات|الوحل يبطئ مسارًا|المسار المحدد: ضرر +2|الرماة يستهدفون المعالجين أولًا|الضباب يقلل المدى|أوقف مستدعي التعزيزات|اجمع التكتيكات في الختام|الحارس الحديدي|الطليعة|ناسج المسارات|معالج اليشم|طبال الحرب|سيد تشانغبان|جندي|حامل درع|مغير|ملتَف|معالج|يخترق الدروع ويضرب المجموعة|يوقف الهدف لفترة قصيرة|ضرر قوي من قرب|مدى بعيد؛ المعالجون أولًا'
  };
  for(const [locale,row] of Object.entries(rows)){
    const values=row.split('|');if(values.length!==keys.length)throw Error('ZHAO_V27_LOCALE:'+locale);
    const d=window.ZHAO_YUN_ADOU_LOCALES[locale];keys.forEach((key,i)=>d[key]=values[i]);
    d.tutorialRecruit=d.commandHelp;d.tutorialDefend=d.rule_coverage;
    d.noTarget={en:'No enemy in range. Aim at an occupied lane.', 'zh-Hant':'目前沒有目標，請瞄準有敵人的路線。','zh-Hans':'当前没有目标，请瞄准有敌人的路线。',ja:'対象がいません。敵のいる進路を狙ってください。',ko:'대상이 없습니다. 적이 있는 경로를 조준하세요.',es:'No hay objetivo. Apunta a una ruta con enemigos.','pt-BR':'Sem alvo. Mire em uma rota com inimigos.',fr:'Aucune cible. Visez une voie occupée par des ennemis.',de:'Kein Ziel. Ziele auf einen Weg mit Gegnern.',it:'Nessun bersaglio. Mira a una corsia con nemici.',ru:'Нет цели. Выберите линию с врагами.',hi:'कोई लक्ष्य नहीं। शत्रु वाले रास्ते पर निशाना लगाएँ।',ar:'لا يوجد هدف. صوّب نحو مسار فيه أعداء.'}[locale];
    d.guideBody=['blade','spear','horse','bow'].map(type=>d.unitLabels[type]+': '+d['counter_'+type]).join(' · ');
    d.v27Progression=[d.rule_shield,d.rule_charge,d.rule_flank,d.rule_medic,d.rule_mud,d.rule_fog,d.rule_summon,d.rule_finale].join(' · ');
  }
})();
