/* Direct deployment copy; also evaluated by the owned route generator. */
(() => {
 const rows={
 en:['Tap a troop card to deploy. Soldiers advance and fight automatically.','Protect A Dou and destroy the enemy fortress.','Front guard','Anti-cavalry','Long range','Fast assault','Supplies recover automatically. Cards show cost and cooldown.','Zhao Yun damages and pushes back all enemies.','Choose supply, guard or charge talents in Stages. Reset freely.','Supply recovery +27%','Camp health +40','Troop health +25%','Survive once with 30 health','Charge damage +50%','Mud slows both armies in the middle.','Protect archers with guards; save the charge for danger.'],
 'zh-Hant':['點下兵種卡就出兵，部隊會自動前進交戰。','保護阿斗，推進並攻破敵軍城寨。','前排護衛','克制騎兵','遠程支援','快速突擊','饅頭自動恢復，卡片直接顯示費用與冷卻。','趙雲衝鋒，傷害並擊退所有敵人。','在關卡頁選擇補給、堅守或突擊天賦，可免費重置搭配。','補給恢復加快 27%','營地生命 +40','部隊生命 +25%','承受致命攻擊後保留 30 生命一次','突擊傷害 +50%','道路中央的泥地會減慢雙方速度。','用刀兵保護後方弓兵，危急時再讓趙雲突擊。'],
 'zh-Hans':['点下兵种卡就出兵，部队会自动前进交战。','保护阿斗，推进并攻破敌军城寨。','前排护卫','克制骑兵','远程支援','快速突击','馒头自动恢复，卡片直接显示费用与冷却。','赵云冲锋，伤害并击退所有敌人。','在关卡页选择补给、坚守或突击天赋，可免费重置搭配。','补给恢复加快 27%','营地生命 +40','部队生命 +25%','承受致命攻击后保留 30 生命一次','突击伤害 +50%','道路中央的泥地会减慢双方速度。','用刀兵保护后方弓兵，危急时再让赵云突击。'],
 ja:['兵種カードをタップして出撃。兵士は自動で進軍し戦います。','阿斗を守り、敵の砦を破壊しよう。','前衛','騎兵対策','遠距離','速攻','兵糧は自動回復。カードに費用と待ち時間を表示。','趙雲が全敵にダメージを与えて押し戻します。','任務画面で補給・守備・突撃の才能を選択。無料リセット可能。','兵糧回復 +27%','陣地の体力 +40','部隊の体力 +25%','一度だけ体力30で致命傷を耐える','突撃ダメージ +50%','中央の泥は両軍の移動を遅くします。','前衛で弓兵を守り、危険なときに趙雲を突撃させましょう。'],
 ko:['병종 카드를 눌러 출격하세요. 병사들은 자동으로 전진하며 싸웁니다.','아두를 지키며 적 요새를 파괴하세요.','전방 수비','기병 대응','원거리','빠른 돌격','군량은 자동 회복됩니다. 카드에 비용과 대기 시간이 표시됩니다.','조운이 모든 적에게 피해를 주고 밀어냅니다.','미션에서 보급, 수비, 돌격 특성을 선택하세요. 무료 초기화가 가능합니다.','보급 회복 +27%','진영 체력 +40','부대 체력 +25%','치명타를 한 번 체력 30으로 버팀','돌격 피해 +50%','중앙의 진흙은 양쪽 부대의 속도를 늦춥니다.','전방 수비로 궁병을 보호하고 위험할 때 조운을 돌격시키세요.'],
 es:['Toca una carta para desplegar tropas. Avanzan y luchan automáticamente.','Protege a A Dou y destruye la fortaleza enemiga.','Vanguardia','Anticaballería','Largo alcance','Asalto rápido','Los suministros se recuperan solos. Las cartas muestran coste y espera.','Zhao Yun daña y empuja a todos los enemigos.','Elige talentos de suministro, defensa o carga en Misiones. Reinicio gratuito.','Recuperación de suministros +27%','Salud del campamento +40','Salud de tropas +25%','Sobrevive una vez con 30 de salud','Daño de carga +50%','El barro central ralentiza a ambos bandos.','Protege a los arqueros con guardias y reserva la carga para el peligro.'],
 'pt-BR':['Toque numa carta para enviar tropas. Elas avançam e lutam automaticamente.','Proteja A Dou e destrua a fortaleza inimiga.','Linha de frente','Anticavalaria','Longo alcance','Ataque rápido','Suprimentos se recuperam sozinhos. As cartas mostram custo e espera.','Zhao Yun causa dano e empurra todos os inimigos.','Escolha talentos de suprimento, defesa ou investida em Missões. Redefina grátis.','Recuperação de suprimentos +27%','Vida do acampamento +40','Vida das tropas +25%','Sobreviva uma vez com 30 de vida','Dano da investida +50%','A lama central desacelera os dois lados.','Proteja arqueiros com guardas e guarde a investida para o perigo.'],
 fr:['Touchez une carte pour déployer des troupes. Elles avancent et combattent seules.','Protégez A Dou et détruisez la forteresse ennemie.','Avant-garde','Anti-cavalerie','Longue portée','Assaut rapide','Les vivres se régénèrent. Les cartes affichent coût et délai.','Zhao Yun blesse et repousse tous les ennemis.','Choisissez des talents de ravitaillement, défense ou charge dans les missions. Réinitialisation gratuite.','Régénération des vivres +27%','Vie du camp +40','Vie des troupes +25%','Survivez une fois avec 30 de vie','Dégâts de charge +50%','La boue centrale ralentit les deux camps.','Protégez les archers avec des gardes et gardez la charge pour le danger.'],
 de:['Tippe eine Truppenkarte an. Soldaten rücken vor und kämpfen automatisch.','Beschütze A Dou und zerstöre die feindliche Festung.','Vorhut','Gegen Reiter','Fernkampf','Schneller Angriff','Vorräte erholen sich automatisch. Karten zeigen Kosten und Wartezeit.','Zhao Yun verletzt alle Gegner und stößt sie zurück.','Wähle in Missionen Talente für Vorräte, Verteidigung oder Ansturm. Kostenlos zurücksetzen.','Vorratserholung +27%','Lagerleben +40','Truppenleben +25%','Einmal mit 30 Leben überleben','Ansturmschaden +50%','Schlamm in der Mitte verlangsamt beide Seiten.','Schütze Bogenschützen mit Wachen und spare den Ansturm für Gefahr.'],
 it:['Tocca una carta per schierare truppe. Avanzano e combattono da sole.','Proteggi A Dou e distruggi la fortezza nemica.','Prima linea','Anti-cavalleria','Lunga gittata','Assalto rapido','Le scorte si rigenerano. Le carte mostrano costo e attesa.','Zhao Yun danneggia e respinge tutti i nemici.','Scegli talenti di scorte, difesa o carica nelle missioni. Ripristino gratuito.','Recupero scorte +27%','Salute accampamento +40','Salute truppe +25%','Sopravvivi una volta con 30 salute','Danni della carica +50%','Il fango centrale rallenta entrambi gli schieramenti.','Proteggi gli arcieri con guardie e conserva la carica per il pericolo.'],
 ru:['Нажмите карту бойца. Войска сами идут вперёд и сражаются.','Защитите А-Доу и разрушьте вражескую крепость.','Передний ряд','Против конницы','Дальний бой','Быстрый штурм','Припасы восстанавливаются сами. Карты показывают цену и ожидание.','Чжао Юнь наносит урон всем врагам и отбрасывает их.','Выбирайте таланты снабжения, защиты или рывка в миссиях. Сброс бесплатный.','Восстановление припасов +27%','Здоровье лагеря +40','Здоровье войск +25%','Один раз выжить с 30 здоровья','Урон рывка +50%','Грязь в центре замедляет обе стороны.','Защищайте лучников стражей и берегите рывок на случай опасности.'],
 hi:['सैनिक कार्ड दबाकर भेजें। सैनिक अपने आप आगे बढ़कर लड़ते हैं।','आ-दो की रक्षा करें और शत्रु का किला तोड़ें।','अग्रिम रक्षा','घुड़सवार रोधी','दूर से वार','तेज़ हमला','रसद अपने आप लौटती है। कार्ड पर लागत और प्रतीक्षा दिखती है।','झाओ युन सभी शत्रुओं को क्षति देकर पीछे धकेलता है।','मिशन में रसद, रक्षा या धावे की प्रतिभाएँ चुनें। मुफ़्त रीसेट करें।','रसद वापसी +27%','शिविर जीवन +40','सैनिक जीवन +25%','एक बार 30 जीवन के साथ बचें','धावा क्षति +50%','बीच का कीचड़ दोनों पक्षों को धीमा करता है।','रक्षकों से धनुर्धरों को बचाएँ और संकट के लिए धावा रखें।'],
 ar:['اضغط بطاقة جندي لإرساله. تتقدم القوات وتقاتل تلقائيًا.','احمِ آ دو ودمّر قلعة العدو.','حارس أمامي','ضد الفرسان','مدى بعيد','هجوم سريع','تتعافى المؤن تلقائيًا. تعرض البطاقة التكلفة ووقت الانتظار.','يؤذي تشاو يون جميع الأعداء ويدفعهم للخلف.','اختر مواهب الإمداد أو الحراسة أو الاندفاع في المهمات. إعادة الضبط مجانية.','تعافي المؤن +27%','صحة المعسكر +40','صحة القوات +25%','النجاة مرة بصحة 30','ضرر الاندفاع +50%','يبطئ الوحل في الوسط كلا الجانبين.','احمِ الرماة بالحراس واحتفظ بالاندفاع للخطر.']
 };
 const keys=['pushIntro','pushGoal','role_blade','role_spear','role_bow','role_horse','pushSupply','chargeAuto','talentHelp','talent_supply2','talent_guard1','talent_guard2','talent_guard3','talent_charge2','pushMud','pushTip'];
 for(const [locale,row] of Object.entries(rows)){
  const d=window.ZHAO_YUN_ADOU_LOCALES[locale];keys.forEach((key,i)=>d[key]=row[i]);
  d.summary=d.pushIntro;d.commandHelp=d.pushIntro;d.guideBody=d.pushSupply+' '+d.chargeAuto;
  d.tutorialRecruit=d.pushIntro;d.tutorialMerge=d.pushSupply;d.tutorialDefend=d.chargeAuto;
  d.mergeHint=d.pushTip;d.battleGuideBody=d.pushIntro;d.battleField=d.pushGoal;
  d.recruitOdds=d.pushSupply;d.typeOdds='';d.resultReplayGoalLoss=d.pushTip;
  d.rule_coverage=d.pushGoal;d.rule_merge=d.pushTip;d.rule_shield=d.role_blade+' · '+d.pushTip;
  d.rule_reach=d.role_bow;d.rule_charge=d.role_spear;d.rule_flank=d.role_spear;
  d.rule_medic=d.role_bow;d.rule_mud=d.pushMud;d.rule_reserve=d.pushSupply;
  d.rule_rally=d.pushGoal;d.rule_fog=d.pushTip;d.rule_summon=d.role_horse;d.rule_finale=d.pushTip;
  d.loseBody=d.pushTip;d.winBody=d.pushGoal;d.tipText=d.pushTip;
  d.v27Progression=d.talentHelp;d.waveReward=d.pushSupply;
 }
 const official={"en":"Zhao Yun & A Dou","zh-Hant":"趙雲與阿斗：墨線守衛","zh-Hans":"赵云与阿斗：墨线守卫","ja":"趙雲と阿斗：墨線ディフェンス","ko":"조운과 아두: 먹선 방어전","es":"Zhao Yun y A Dou: Defensa de tinta","pt-BR":"Zhao Yun e A Dou: Defesa de Tinta","fr":"Zhao Yun et A Dou : Défense d'encre","de":"Zhao Yun und A Dou: Tuschewache","it":"Zhao Yun e A Dou: Difesa d'inchiostro","ru":"Чжао Юнь и А-Доу: Чернильная оборона","hi":"झाओ युन और आ-दो: स्याही रक्षा","ar":"تشاو يون وآ دو: دفاع الحبر"};
 for(const [locale,title] of Object.entries(official))window.ZHAO_YUN_ADOU_LOCALES[locale].title=title;
 for(const d of Object.values(window.ZHAO_YUN_ADOU_LOCALES)){d.shortTitle=d.title;d.guideTitle=d.title;}
 const supplies={en:"Supplies","zh-Hant":"補給","zh-Hans":"补给",ja:"補給",ko:"보급",es:"Suministros","pt-BR":"Suprimentos",fr:"Ravitaillement",de:"Vorräte",it:"Scorte",ru:"Снабжение",hi:"रसद",ar:"الإمداد"};
 for(const [locale,label] of Object.entries(supplies))window.ZHAO_YUN_ADOU_LOCALES[locale].branch_supply=label;
 const genres={en:'Lane strategy', 'zh-Hant':'橫向推線','zh-Hans':'横向推线',ja:'横スクロール戦略',ko:'횡스크롤 전략',es:'Estrategia de avance','pt-BR':'Estratégia de avanço',fr:'Stratégie de progression',de:'Vormarschstrategie',it:'Strategia di avanzata',ru:'Стратегия наступления',hi:'आगे बढ़ने की रणनीति',ar:'استراتيجية التقدم'};
 const full={en:'Army limit: 12/12. Deploy again when a space opens.','zh-Hant':'部隊已滿 12/12，有空位即可再出兵。','zh-Hans':'部队已满 12/12，有空位即可再出兵。',ja:'部隊上限12/12。空きができると再出撃できます。',ko:'부대 한도 12/12. 자리가 나면 다시 출격하세요.',es:'Límite: 12/12. Despliega cuando haya espacio.','pt-BR':'Limite: 12/12. Envie mais quando houver espaço.',fr:'Limite : 12/12. Déployez dès qu’une place se libère.',de:'Truppenlimit: 12/12. Warte auf einen freien Platz.',it:'Limite: 12/12. Attendi un posto libero.',ru:'Лимит: 12/12. Дождитесь свободного места.',hi:'सेना सीमा: 12/12। जगह खाली होने पर भेजें।',ar:'حد الجيش: 12/12. أرسل قوات عند توفر مكان.'};
 for(const locale of Object.keys(genres)){const d=window.ZHAO_YUN_ADOU_LOCALES[locale];d.pushGenre=genres[locale];d.pushFull=full[locale];}
})();
