(() => {
 const rows={
 en:['Talents','Supplies','Guard','Charge','Reset freely','Points {left}/{total} · +1 per 3 first clears (max 5).','Battle loadout locked. Rebuild in Stages.','Zhao Yun charge','Auto: most urgent lane','Start with +3 buns','Merge refunds 1 bun','Every 4th recruit is free','Camp health +4','Spear stun ×2','Survive one lethal hit with 3 HP','Charge cooldown: 7s','Charge strikes all lanes','Charge readies all troop attacks','Lv1 82% · Lv2 16% · General 2%. Every 8 recruits guarantees Lv2+.','Spear 35% · Blade 35% · Archer 20% · Rider 10%.','Random recruitment; merge and defend. Tap Zhao Yun to charge the most urgent lane.','Choose talents before battle. Generals cast their own skills automatically.'],
 'zh-Hant':['天賦','補給合成','守護控場','趙雲突襲','免費重配','可用 {left}/{total} 點 · 每首通 3 關 +1，上限 5 點。','本場天賦已鎖定，返回關卡可免費重配。','趙雲突襲','自動救援最危急戰線','開場多 3 個饅頭','每次合成返還 1 饅頭','每第 4 次徵召免費','阿斗營地生命 +4','槍兵暈眩時間加倍','致命傷時保住 3 生命，每場一次','突襲冷卻縮短為 7 秒','突襲同時攻擊全部戰線','突襲讓全部部隊立即準備再攻','普通 Lv1 82% · 精銳 Lv2 16% · 武將 2%；每 8 抽至少一次精銳以上。','槍兵 35% · 刀兵 35% · 弓兵 20% · 騎兵 10%。','隨機徵召、合成守線；點擊趙雲突襲，自動救援最危急戰線。','戰前選擇天賦流派；武將會自動施放自己的技能。'],
 'zh-Hans':['天赋','补给合成','守护控场','赵云突袭','免费重配','可用 {left}/{total} 点 · 每首通 3 关 +1，上限 5 点。','本场天赋已锁定，返回关卡可免费重配。','赵云突袭','自动救援最危急战线','开场多 3 个馒头','每次合成返还 1 馒头','每第 4 次征召免费','阿斗营地生命 +4','枪兵眩晕时间加倍','致命伤时保住 3 生命，每场一次','突袭冷却缩短为 7 秒','突袭同时攻击全部战线','突袭让全部部队立即准备再攻','普通 Lv1 82% · 精锐 Lv2 16% · 武将 2%；每 8 抽至少一次精锐以上。','枪兵 35% · 刀兵 35% · 弓兵 20% · 骑兵 10%。','随机征召、合成守线；点击赵云突袭，自动救援最危急战线。','战前选择天赋流派；武将会自动施放自己的技能。'],
 ja:['才能','補給','守護','突撃','無料リセット','残り {left}/{total} · 3面初クリアごとに+1（最大5）。','戦闘中は固定。任務画面で変更できます。','趙雲の突撃','最も危険な進路へ自動突撃','開始時の饅頭 +3','合成で饅頭1個を回収','4回目ごとの招集は無料','拠点体力 +4','槍兵の足止め時間 ×2','致命傷を体力3で一度耐える','突撃の待機時間7秒','全進路に突撃','突撃で全兵士が再攻撃可能','Lv1 82% · Lv2 16% · 武将2%。8回以内にLv2以上確定。','槍35% · 刀35% · 弓20% · 騎兵10%。','ランダム招集と合成で防衛。趙雲は最も危険な進路へ突撃。','戦闘前に才能を選択。武将の技能は自動発動。'],
 ko:['특성','보급','수호','돌격','무료 초기화','남은 점수 {left}/{total} · 첫 클리어 3개마다 +1 (최대 5).','전투 중 고정됩니다. 임무 화면에서 변경하세요.','조운 돌격','가장 위험한 길 자동 지원','시작 만두 +3','합성 시 만두 1개 반환','4번째 모집마다 무료','진영 체력 +4','창병 기절 시간 ×2','치명타를 체력 3으로 한 번 생존','돌격 재사용 7초','모든 길에 돌격','돌격 시 전 병력 공격 준비','Lv1 82% · Lv2 16% · 장수 2%. 8회마다 Lv2 이상 보장.','창35% · 검35% · 궁20% · 기병10%.','무작위 모집과 합성으로 방어하세요. 조운은 가장 위험한 길로 돌격합니다.','전투 전에 특성을 선택하세요. 장수 스킬은 자동 발동합니다.'],
 es:['Talentos','Suministros','Guardia','Carga','Reiniciar gratis','Puntos {left}/{total} · +1 por 3 primeras victorias (máx. 5).','Fijo en combate. Cambia en Misiones.','Carga de Zhao Yun','Ataca la ruta más urgente','+3 panes iniciales','Fusionar devuelve 1 pan','Cada 4.º recluta es gratis','Salud del campamento +4','Aturdimiento de lanzas ×2','Sobrevive una vez con 3 de salud','Recarga de carga: 7 s','Carga en todas las rutas','La carga prepara todos los ataques','Nv1 82% · Nv2 16% · General 2%. Nv2+ garantizado cada 8 reclutas.','Lanza35% · Hoja35% · Arco20% · Jinete10%.','Recluta al azar, fusiona y defiende. Zhao Yun carga hacia la ruta más urgente.','Elige talentos antes del combate. Los generales usan habilidades automáticamente.'],
 'pt-BR':['Talentos','Suprimentos','Guarda','Investida','Redefinir grátis','Pontos {left}/{total} · +1 a cada 3 primeiras vitórias (máx. 5).','Fixo na batalha. Altere nas Missões.','Investida de Zhao Yun','Ataca a rota mais urgente','+3 pães iniciais','Combinar devolve 1 pão','Cada 4.º recruta é grátis','Vida do acampamento +4','Atordoamento das lanças ×2','Sobrevive uma vez com 3 de vida','Recarga da investida: 7 s','Investida em todas as rotas','Investida prepara todos os ataques','Nv1 82% · Nv2 16% · General 2%. Nv2+ garantido a cada 8 recrutas.','Lança35% · Lâmina35% · Arco20% · Cavaleiro10%.','Recrute ao acaso, combine e defenda. Zhao Yun investe na rota mais urgente.','Escolha talentos antes da batalha. Generais usam habilidades automaticamente.'],
 fr:['Talents','Ravitaillement','Garde','Charge','Réinitialiser','Points {left}/{total} · +1 par 3 premières victoires (max. 5).','Fixé au combat. Modifiez dans Missions.','Charge de Zhao Yun','Vise la voie la plus menacée','+3 pains au départ','Fusion : récupère 1 pain','Chaque 4e recrue est gratuite','Vie du camp +4','Étourdissement des lances ×2','Survit une fois avec 3 PV','Recharge de la charge : 7 s','Charge sur toutes les voies','La charge prépare toutes les attaques','Niv1 82% · Niv2 16% · Général 2%. Niv2+ garanti tous les 8 recrutements.','Lance35% · Lame35% · Arc20% · Cavalier10%.','Recrutez au hasard, fusionnez et défendez. Zhao Yun charge la voie la plus menacée.','Choisissez vos talents avant le combat. Compétences des généraux automatiques.'],
 de:['Talente','Nachschub','Wache','Ansturm','Kostenlos zurücksetzen','Punkte {left}/{total} · +1 je 3 erstmalige Siege (max. 5).','Im Kampf gesperrt. Unter Missionen ändern.','Zhao Yuns Ansturm','Automatisch zum gefährlichsten Weg','Zu Beginn +3 Brötchen','Fusion erstattet 1 Brötchen','Jede 4. Rekrutierung kostenlos','Lagerleben +4','Speer-Betäubung ×2','Einmal mit 3 Leben überleben','Ansturm-Abklingzeit: 7 s','Ansturm auf allen Wegen','Ansturm bereitet alle Angriffe vor','Stufe1 82% · Stufe2 16% · General 2%. Stufe2+ spätestens alle 8 Rekrutierungen.','Speer35% · Klinge35% · Bogen20% · Reiter10%.','Zufällig rekrutieren, fusionieren und verteidigen. Zhao Yun stürmt den gefährlichsten Weg.','Vor dem Kampf Talente wählen. Generäle wirken Fähigkeiten automatisch.'],
 it:['Talenti','Rifornimenti','Guardia','Carica','Ripristina gratis','Punti {left}/{total} · +1 ogni 3 prime vittorie (max 5).','Fisso in battaglia. Modifica nelle Missioni.','Carica di Zhao Yun','Colpisce la corsia più in pericolo','+3 panini iniziali','La fusione restituisce 1 panino','Ogni 4ª recluta è gratuita','Salute del campo +4','Stordimento lance ×2','Sopravvivi una volta con 3 salute','Ricarica della carica: 7 s','Carica su tutte le corsie','La carica prepara tutti gli attacchi','Lv1 82% · Lv2 16% · Generale 2%. Lv2+ garantito ogni 8 reclute.','Lancia35% · Lama35% · Arco20% · Cavaliere10%.','Recluta a caso, unisci e difendi. Zhao Yun carica la corsia più minacciata.','Scegli i talenti prima della battaglia. Abilità dei generali automatiche.'],
 ru:['Таланты','Снабжение','Защита','Рывок','Сброс бесплатно','Очки {left}/{total} · +1 за 3 первых победы (макс. 5).','В бою выбор закреплён. Меняйте в миссиях.','Рывок Чжао Юня','Автоматически на опаснейшую линию','В начале +3 булочки','Слияние возвращает 1 булочку','Каждый 4-й наём бесплатный','Здоровье лагеря +4','Оглушение копий ×2','Один раз выжить с 3 здоровья','Перезарядка рывка: 7 с','Рывок по всем линиям','Рывок готовит все атаки','Ур1 82% · Ур2 16% · Генерал 2%. Ур2+ гарантирован за 8 наймов.','Копьё35% · Клинок35% · Лук20% · Всадник10%.','Случайный наём, слияние и оборона. Чжао Юнь атакует опаснейшую линию.','Выбирайте таланты перед боем. Умения генералов автоматические.'],
 hi:['प्रतिभाएँ','रसद','रक्षा','धावा','मुफ़्त रीसेट','अंक {left}/{total} · हर 3 पहली जीत पर +1 (अधिकतम 5)।','युद्ध में निश्चित। मिशन में बदलें।','झाओ युन का धावा','सबसे संकटपूर्ण रास्ते पर स्वतः','शुरुआत में +3 बन','मिलाने पर 1 बन वापस','हर चौथी भर्ती मुफ़्त','शिविर जीवन +4','भाले का स्तब्ध समय ×2','घातक वार पर एक बार 3 जीवन बचे','धावा फिर से: 7 सेकंड','सभी रास्तों पर धावा','धावा सभी हमले तैयार करता है','स्तर1 82% · स्तर2 16% · सेनापति 2%। हर 8 भर्ती में स्तर2+ निश्चित।','भाला35% · तलवार35% · धनुष20% · घुड़सवार10%।','यादृच्छिक भर्ती करें, मिलाएँ और रक्षा करें। झाओ युन सबसे संकटपूर्ण रास्ते पर धावा करता है।','युद्ध से पहले प्रतिभाएँ चुनें। सेनापति की क्षमताएँ स्वतः चलती हैं।'],
 ar:['المواهب','الإمداد','الحراسة','الاندفاع','إعادة مجانية','النقاط {left}/{total} · +1 لكل 3 انتصارات أولى (حد 5).','ثابت أثناء القتال. غيّره في المهمات.','اندفاع تشاو يون','ينقذ المسار الأكثر خطرًا تلقائيًا','ابدأ مع +3 خبز','الدمج يعيد خبزة واحدة','كل تجنيد رابع مجاني','صحة المعسكر +4','مدة صعق الرماح ×2','النجاة مرة بصحة 3 من ضربة قاتلة','تبريد الاندفاع: 7 ثوانٍ','اندفاع في جميع المسارات','الاندفاع يجهّز كل هجمات القوات','مستوى1 82% · مستوى2 16% · قائد 2%. مستوى2+ مضمون كل 8 تجنيدات.','رمح35% · سيف35% · قوس20% · فارس10%.','جنّد عشوائيًا وادمج ودافع. يندفع تشاو يون إلى المسار الأكثر خطرًا.','اختر المواهب قبل القتال. يستخدم القادة مهاراتهم تلقائيًا.']
 };
 const keys=['talents','branch_supply','branch_guard','branch_charge','resetTalents','talentPoints','talentLocked','chargeAction','chargeAuto','talent_supply1','talent_supply2','talent_supply3','talent_guard1','talent_guard2','talent_guard3','talent_charge1','talent_charge2','talent_charge3','recruitOdds','typeOdds','commandHelp','talentHelp'];
 const baseOdds={en:'Base odds: ', 'zh-Hant':'基礎機率：','zh-Hans':'基础概率：',ja:'基本確率：',ko:'기본 확률: ',es:'Probabilidad base: ','pt-BR':'Probabilidade base: ',fr:'Probabilités de base : ',de:'Grundchancen: ',it:'Probabilità base: ',ru:'Базовые шансы: ',hi:'मूल संभावना: ',ar:'الاحتمالات الأساسية: '};
 for(const [locale,row] of Object.entries(rows)){
  const d=window.ZHAO_YUN_ADOU_LOCALES[locale];keys.forEach((key,i)=>d[key]=row[i]);
  d.recruitOdds=baseOdds[locale]+d.recruitOdds;
  d.summary=d.commandHelp;d.tutorialRecruit=d.commandHelp;d.tutorialDefend=d.talentHelp;
  d.noTarget=d.readySkill;d.guideBody=d.recruitOdds+' '+d.typeOdds+' '+d.talentHelp;
 }
})();
(() => {
 const messages={en:'No enemies yet. Save the charge.', 'zh-Hant':'目前沒有敵人，先保留突襲。','zh-Hans':'目前没有敌人，先保留突袭。',ja:'敵がいません。突撃を温存しましょう。',ko:'아직 적이 없습니다. 돌격을 아끼세요.',es:'Aún no hay enemigos. Reserva la carga.','pt-BR':'Ainda não há inimigos. Guarde a investida.',fr:'Aucun ennemi. Gardez votre charge.',de:'Noch keine Gegner. Spare den Ansturm.',it:'Nessun nemico. Conserva la carica.',ru:'Врагов пока нет. Сохраните рывок.',hi:'अभी शत्रु नहीं हैं। धावा बचाकर रखें।',ar:'لا أعداء بعد. احتفظ بالاندفاع.'};
 for(const [locale,text] of Object.entries(messages))window.ZHAO_YUN_ADOU_LOCALES[locale].noTarget=text;
})();
