(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const localeKeys = window.ANIMAL_POSTCARD_CROP_LOCALE_KEYS || ["en"];
  const locales = window.ANIMAL_POSTCARD_CROP_LOCALES || {};
  const rounds = [
    { name:"Meadow card", target:["Pond","Oak"], decoy:"Fox", answer:{x:0,y:0}, cells:["Pond","Oak","Nest","Fox","Mushroom","Hill","Berry","Lantern","Bridge","Daisy","Rock","Cloud"] },
    { name:"Lantern card", target:["Lantern","Bridge"], decoy:"Mushroom", answer:{x:1,y:1}, cells:["Cloud","Daisy","Rock","Hill","Fox","Berry","Pond","Oak","Lantern","Bridge","Nest","Mushroom"] },
    { name:"Garden card", target:["Daisy","Rock"], decoy:"Fox", answer:{x:2,y:0}, cells:["Berry","Cloud","Pond","Oak","Nest","Daisy","Rock","Fox","Lantern","Bridge","Mushroom","Hill"] }
  ];
  const state = { view:"main", locale:"en", round:0, x:0, y:0, moves:0, sound:false };
  const t = (key, vars = {}) => { const copy = locales[state.locale] || locales.en || {}; let value = copy[key] ?? (locales.en || {})[key] ?? key; if (Array.isArray(value)) return value; return String(value).replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? `{${name}}`); };
  const sceneLabel = (name) => { const scenes = t("scenes"); const index = rounds[state.round].cells.indexOf(name); return scenes[index] || name; };
  const track = (name, detail = {}) => window.WonderAnalytics?.track?.(`postcard_crop_${name}`, detail);
  const readBest = () => { try { return Number(localStorage.getItem("weightplay-animal-postcard-crop-best")) || 0; } catch (_) { return 0; } };
  const saveBest = () => { const old = readBest(); if (!old || state.moves < old) { try { localStorage.setItem("weightplay-animal-postcard-crop-best", String(state.moves)); } catch (_) {} } };
  const show = (view) => { state.view = view; $("mainScreen").hidden = view !== "main"; $("battleScreen").hidden = view !== "battle"; $("resultScreen").hidden = view !== "result"; $("gameGuide").hidden = view !== "main"; document.body.classList.toggle("wp-shell-battle-active", view === "battle"); document.body.classList.toggle("wp-shell-result-active", view === "result"); window.scrollTo(0, 0); };
  const applyLocale = () => { const copy = locales[state.locale] || locales.en; document.documentElement.lang = state.locale === "zh-Hant" ? "zh-TW" : state.locale === "zh-Hans" ? "zh-CN" : state.locale; document.documentElement.dir = copy.direction || "ltr"; document.title = `${t("title")} | WeightPlay`; document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = t(node.dataset.i18n); }); $("locale-select").value = state.locale; document.querySelectorAll("[data-sound-toggle]").forEach((node) => { node.textContent = state.sound ? t("soundOn") : t("soundOff"); node.setAttribute("aria-pressed", String(state.sound)); }); if (state.view === "battle") renderBattle(); if (state.view === "result") renderResult(); };
  const populateLocales = () => { const select = $("locale-select"); select.replaceChildren(...localeKeys.map((key) => { const option = document.createElement("option"); option.value = key; option.textContent = (locales.en.languageNames || {})[key] || key; return option; })); select.addEventListener("change", () => { state.locale = select.value; try { localStorage.setItem("weightplay-animal-postcard-crop-locale", state.locale); } catch (_) {} applyLocale(); }); };
  const renderBattle = () => { const round = rounds[state.round]; $("roundTitle").textContent = round.name; $("roundCount").textContent = `${state.round + 1}/${rounds.length}`; $("clueText").textContent = `${t("targetLabel")}: ${round.target.map(sceneLabel).join(" + ")}`; $("decoyText").textContent = `${t("decoyLabel")}: ${sceneLabel(round.decoy)}`; const grid = $("sceneGrid"); grid.replaceChildren(...round.cells.map((name) => { const cell = document.createElement("div"); cell.className = `scene-cell scene-cell--${name.toLowerCase()}`; if (round.target.includes(name)) cell.classList.add("landmark"); if (round.decoy === name) cell.classList.add("decoy"); cell.setAttribute("role", "gridcell"); cell.textContent = sceneLabel(name); cell.title = cell.textContent; return cell; })); $("postcardFrame").style.transform = `translate(${state.x * 100}%, ${state.y * 100}%)`; $("battleStatus").textContent = t("moveHint"); };
  const renderResult = () => { $("resultText").textContent = t("resultText", { moves:state.moves }); $("resultMoves").textContent = String(state.moves); $("resultBest").textContent = String(readBest() || t("noBest")); $("resultStatus").textContent = t("correct"); };
  const start = () => { state.round = 0; state.x = 0; state.y = 0; state.moves = 0; show("battle"); renderBattle(); track("start"); };
  const move = (direction) => { const before = `${state.x},${state.y}`; if (direction === "left") state.x = Math.max(0, state.x - 1); if (direction === "right") state.x = Math.min(2, state.x + 1); if (direction === "up") state.y = Math.max(0, state.y - 1); if (direction === "down") state.y = Math.min(1, state.y + 1); if (before !== `${state.x},${state.y}`) state.moves += 1; renderBattle(); track("move", { direction, round:state.round + 1, x:state.x, y:state.y }); };
  const reset = () => { state.x = 0; state.y = 0; state.moves += 1; renderBattle(); track("reset", { round:state.round + 1 }); };
  const check = () => { const round = rounds[state.round]; if (state.x !== round.answer.x || state.y !== round.answer.y) { $("battleStatus").textContent = t("wrong"); $("battleStatus").dataset.kind = "wrong"; track("check", { round:state.round + 1, result:"wrong" }); return; } $("battleStatus").textContent = t("correct"); $("battleStatus").dataset.kind = "correct"; track("check", { round:state.round + 1, result:"correct" }); if (state.round < rounds.length - 1) { state.round += 1; state.x = 0; state.y = 0; renderBattle(); } else { saveBest(); renderResult(); show("result"); track("complete", { moves:state.moves }); } };
  const openSettings = () => { const dialog = $("settings-dialog"); dialog.classList.add("is-open"); };
  const closeSettings = () => { const dialog = $("settings-dialog"); dialog.classList.remove("is-open"); };
  const goHome = () => { closeSettings(); show("main"); applyLocale(); };
  state.locale = (() => { try { const saved = localStorage.getItem("weightplay-animal-postcard-crop-locale"); if (saved && locales[saved]) return saved; } catch (_) {} const query = new URLSearchParams(location.search).get("lang"); return locales[query] ? query : "en"; })();
  document.addEventListener("DOMContentLoaded", () => { populateLocales(); applyLocale(); $("startButton").addEventListener("click", start); $("guideButton").addEventListener("click", openSettings); $("main-settings").addEventListener("click", openSettings); $("battleSound").addEventListener("click", () => { state.sound = !state.sound; applyLocale(); }); $("result-settings").addEventListener("click", openSettings); $("close-settings").addEventListener("click", closeSettings); $("sound-toggle").addEventListener("click", () => { state.sound = !state.sound; applyLocale(); }); $("battleHome").addEventListener("click", goHome); $("resultHome").addEventListener("click", goHome); $("resetButton").addEventListener("click", reset); $("checkButton").addEventListener("click", check); $("replayButton").addEventListener("click", start); $("resultMenu").addEventListener("click", goHome); document.querySelectorAll("[data-move]").forEach((button) => button.addEventListener("click", () => move(button.dataset.move))); });
  window.ANIMAL_POSTCARD_CROP_TEST = { rounds, start, move, reset, check, getState:() => ({ ...state }) };
})();
