window.WONDER_LOBBY = {
  platform: {
    name: "WeightPlay",
    company: "WeightStudio",
    tagline: "Play small games made for every age.",
    subtitle: "",
    defaultLocale: "en",
  },
  featuredGameId: "wonder-crash",
  heroGameIds: ["wonder-crash", "color-lunchbox", "animal-quiz"],
  games: [
    {
      id: "wonder-crash",
      title: "Wonder Crash",
      status: "playable",
      statusText: "Playable",
      type: "Defense",
      categories: ["Featured", "Arcade"],
      ages: ["5", "13"],
      ageLabel: "5+",
      href: "games/wonder-crash/index.html",
      description: "Move the hero, throw school-supply weapons, and protect the wall.",
      meta: ["Hero Game", "30 Levels", "Gear Merge", "Mobile"],
      art: {
        kind: "image",
        background: "assets/battle-bg.png",
        hero: "assets/hero.png",
      },
    },
    {
      id: "color-lunchbox",
      title: "Color Lunchbox",
      status: "playable",
      statusText: "Playable",
      type: "Color Match",
      categories: ["Education", "Family"],
      ages: ["3", "family"],
      ageLabel: "3+",
      href: "games/color-lunchbox/index.html",
      description: "Drag each food into the matching color lunchbox.",
      meta: ["Drag Match", "No Pressure", "Family"],
      art: { kind: "pattern", className: "color-match" },
    },
    {
      id: "star-memory",
      title: "Star Memory",
      status: "planned",
      statusText: "Planned",
      type: "Memory Puzzle",
      categories: ["Puzzle", "Family"],
      ages: ["5", "family"],
      ageLabel: "5+",
      description: "Remember the cards and match the same symbols.",
      meta: ["Short Rounds", "Replayable", "Memory"],
      art: { kind: "pattern", className: "memory-flip" },
    },
    {
      id: "campus-dash",
      title: "Campus Dash",
      status: "planned",
      statusText: "Planned",
      type: "Reaction Runner",
      categories: ["Arcade"],
      ages: ["13"],
      ageLabel: "13+",
      description: "Swipe left and right, dodge obstacles, and chase a high score.",
      meta: ["Leaderboard", "Reaction", "1 Min"],
      art: { kind: "pattern", className: "reflex-run" },
    },
    {
      id: "snack-blocks",
      title: "Snack Blocks",
      status: "planned",
      statusText: "Backlog",
      type: "Casual Puzzle",
      categories: ["Puzzle"],
      ages: ["13", "family"],
      ageLabel: "13+",
      description: "Line up cute snacks and clear them for points.",
      meta: ["Casual", "Short Play", "Daily"],
      art: { kind: "pattern", className: "snack-blocks" },
    },
    {
      id: "animal-quiz",
      title: "Animal Quiz",
      status: "planned",
      statusText: "Backlog",
      type: "Family Quiz",
      categories: ["Animal Games", "Education", "Family"],
      ages: ["3", "5", "family"],
      ageLabel: "Family",
      description: "Listen, look, and guess the animal together.",
      meta: ["Animal Games", "Education", "Easy"],
      art: { kind: "pattern", className: "animal-quiz" },
    },
  ],
};
