window.WONDER_LOBBY = {
  featuredGameId: "wonder-crash",
  games: [
    {
      id: "wonder-crash",
      title: "Wonder Crash",
      status: "playable",
      statusText: "可遊玩",
      type: "防守養成",
      ages: ["6", "9"],
      ageLabel: "6+",
      href: "games/wonder-crash/index.html",
      description: "拖曳角色、投擲文具武器、守住城牆。",
      meta: ["30 關", "裝備合成", "手機可玩"],
      art: {
        kind: "image",
        background: "assets/battle-bg.png",
        hero: "assets/hero.png",
      },
    },
    {
      id: "color-lunchbox",
      title: "顏色便當盒",
      status: "playable",
      statusText: "可遊玩",
      type: "顏色配對",
      ages: ["3", "family"],
      ageLabel: "3+",
      href: "games/color-lunchbox/index.html",
      description: "把食物放到相同顏色的便當盒裡。",
      meta: ["拖曳配對", "無失敗壓力", "親子可玩"],
      art: { kind: "pattern", className: "color-match" },
    },
    {
      id: "star-memory",
      title: "星星翻翻牌",
      status: "planned",
      statusText: "企劃中",
      type: "記憶益智",
      ages: ["6", "9", "family"],
      ageLabel: "6+",
      description: "記住位置，翻出相同圖案。",
      meta: ["短局", "可重玩", "適合練記憶"],
      art: { kind: "pattern", className: "memory-flip" },
    },
    {
      id: "campus-dash",
      title: "校園閃電跑",
      status: "planned",
      statusText: "企劃中",
      type: "反應跑酷",
      ages: ["9", "12"],
      ageLabel: "9+",
      description: "左右滑動閃障礙，收集道具挑戰高分。",
      meta: ["排行榜候選", "反應挑戰", "一局 1 分鐘"],
      art: { kind: "pattern", className: "reflex-run" },
    },
    {
      id: "snack-blocks",
      title: "點心方塊",
      status: "planned",
      statusText: "候補",
      type: "休閒消除",
      ages: ["12", "family"],
      ageLabel: "12+",
      description: "把可愛點心排成一列，輕鬆消除拿分。",
      meta: ["成人休閒", "短時間遊玩", "可每日挑戰"],
      art: { kind: "pattern", className: "snack-blocks" },
    },
    {
      id: "animal-quiz",
      title: "動物小博士",
      status: "planned",
      statusText: "候補",
      type: "親子問答",
      ages: ["3", "6", "family"],
      ageLabel: "親子",
      description: "聽聲音、看圖片，一起猜是哪種動物。",
      meta: ["親子共玩", "教育", "低難度"],
      art: { kind: "pattern", className: "animal-quiz" },
    },
  ],
};
