(function(){
"use strict";
if(window.WeightPlayCastle?.builderVersion===4)return;
const STORE="weightplayCastleV1",BUILD="weightplayCastleBuilderV1",DAILY="weightplayDailyReward";
const REWARD=1,LEGACY=5,BOARD=6,MAXY=8,MAXBLOCKS=256;
const buildings=[{id:"gate",cost:12},{id:"bridge",cost:24},{id:"garden",cost:42},{id:"tower",cost:72},{id:"observatory",cost:120}];
const daily=[5,8,12,18,25,35];
const L={
en:{title:"Starlight Castle",intro:"Clear stages, collect blocks, and build your own castle.",blocks:"Blocks",daily:"Daily",claim:"Claim {n} diamonds",claimed:"Claimed today",next:"Next building",build:"Build",need:"Need {n} more",free:"Free Build",stone:"Stone",roof:"Roof",wood:"Wood",glass:"Glass",place:"Place",remove:"Remove",layer:"Layer",rotate:"Drag to rotate · wheel/pinch to zoom",clear:"Stage reward! +{n} block",visit:"Open castle",badges:"Game badges",full:"Block limit reached",occupied:"That space is occupied",support:"Build from the ground up",save:"Unable to save",done:"Built",level:"Castle Lv.{n}"},
"zh-Hant":{title:"星光城堡",intro:"闖關收集方塊，在方塊地板上打造自己的城堡。",blocks:"方塊",daily:"每日可領",claim:"領取 {n} 顆鑽石",claimed:"今日已領",next:"下一座建築",build:"建造",need:"還差 {n}",free:"自由建造",stone:"石材",roof:"屋瓦",wood:"木材",glass:"玻璃",place:"放置",remove:"回收",layer:"高度",rotate:"拖曳旋轉 · 滾輪／雙指縮放",clear:"關卡獎勵！獲得 {n} 個方塊",visit:"前往城堡",badges:"遊戲徽章",full:"方塊數量已達上限",occupied:"這個位置已被占用",support:"請由地面往上堆疊",save:"無法儲存",done:"已建造",level:"城堡 Lv.{n}"},
"zh-Hans":{title:"星光城堡",intro:"闯关收集方块，在方块地板上打造自己的城堡。",blocks:"方块",daily:"每日可领",claim:"领取 {n} 颗钻石",claimed:"今日已领",next:"下一座建筑",build:"建造",need:"还差 {n}",free:"自由建造",stone:"石材",roof:"屋瓦",wood:"木材",glass:"玻璃",place:"放置",remove:"回收",layer:"高度",rotate:"拖动旋转 · 滚轮／双指缩放",clear:"关卡奖励！获得 {n} 个方块",visit:"前往城堡",badges:"游戏徽章",full:"方块数量已达上限",occupied:"这个位置已被占用",support:"请从地面向上堆叠",save:"无法保存",done:"已建造",level:"城堡 Lv.{n}"},
ja:{title:"星明かりのお城",intro:"ステージでブロックを集め、自分だけのお城を作ろう。",blocks:"ブロック",daily:"毎日",claim:"ダイヤを{n}個受け取る",claimed:"今日は受取済み",next:"次の建物",build:"建てる",need:"あと{n}",free:"自由建築",stone:"石",roof:"屋根",wood:"木",glass:"ガラス",place:"置く",remove:"回収",layer:"高さ",rotate:"ドラッグで回転・ホイール/ピンチでズーム",clear:"ステージ報酬！ブロック +{n}",visit:"お城を見る",badges:"ゲームバッジ",full:"ブロック上限です",occupied:"その場所は使用中です",support:"地面から積んでください",save:"保存できません",done:"完成",level:"お城 Lv.{n}"},
ko:{title:"별빛 성",intro:"스테이지에서 블록을 모아 나만의 성을 지으세요.",blocks:"블록",daily:"매일",claim:"다이아 {n}개 받기",claimed:"오늘 받음",next:"다음 건물",build:"건설",need:"{n}개 더 필요",free:"자유 건설",stone:"석재",roof:"지붕",wood:"목재",glass:"유리",place:"놓기",remove:"회수",layer:"높이",rotate:"드래그 회전 · 휠/핀치 줌",clear:"스테이지 보상! 블록 +{n}",visit:"성 보기",badges:"게임 배지",full:"블록 한도입니다",occupied:"이미 사용 중인 칸입니다",support:"바닥부터 쌓아 주세요",save:"저장할 수 없습니다",done:"완성",level:"성 Lv.{n}"},
es:{title:"Castillo Estelar",intro:"Supera fases, consigue bloques y construye tu castillo.",blocks:"Bloques",daily:"Diario",claim:"Recibir {n} diamantes",claimed:"Recibido hoy",next:"Siguiente edificio",build:"Construir",need:"Faltan {n}",free:"Construcción libre",stone:"Piedra",roof:"Tejado",wood:"Madera",glass:"Vidrio",place:"Colocar",remove:"Reciclar",layer:"Altura",rotate:"Arrastra para girar · rueda/pellizco para zoom",clear:"¡Recompensa! +{n} bloque",visit:"Ver castillo",badges:"Insignias",full:"Límite de bloques",occupied:"Ese espacio está ocupado",support:"Construye desde el suelo",save:"No se pudo guardar",done:"Construido",level:"Castillo Nv.{n}"},
"pt-BR":{title:"Castelo Estelar",intro:"Vença fases, junte blocos e construa seu castelo.",blocks:"Blocos",daily:"Diário",claim:"Receber {n} diamantes",claimed:"Recebido hoje",next:"Próxima construção",build:"Construir",need:"Faltam {n}",free:"Construção livre",stone:"Pedra",roof:"Telhado",wood:"Madeira",glass:"Vidro",place:"Colocar",remove:"Reciclar",layer:"Altura",rotate:"Arraste para girar · roda/pinça para zoom",clear:"Recompensa! +{n} bloco",visit:"Ver castelo",badges:"Emblemas",full:"Limite de blocos",occupied:"Esse espaço está ocupado",support:"Construa a partir do chão",save:"Não foi possível salvar",done:"Construído",level:"Castelo Nv.{n}"},
fr:{title:"Château des Étoiles",intro:"Terminez des niveaux, gagnez des blocs et construisez votre château.",blocks:"Blocs",daily:"Quotidien",claim:"Recevoir {n} diamants",claimed:"Reçu aujourd’hui",next:"Prochain bâtiment",build:"Construire",need:"Encore {n}",free:"Construction libre",stone:"Pierre",roof:"Toit",wood:"Bois",glass:"Verre",place:"Placer",remove:"Recycler",layer:"Hauteur",rotate:"Glissez pour tourner · molette/pincement pour zoomer",clear:"Récompense ! +{n} bloc",visit:"Voir le château",badges:"Badges",full:"Limite de blocs",occupied:"Cet espace est occupé",support:"Construisez depuis le sol",save:"Enregistrement impossible",done:"Construit",level:"Château Niv.{n}"},
de:{title:"Sternenlichtschloss",intro:"Schließe Level ab, sammle Blöcke und baue dein Schloss.",blocks:"Blöcke",daily:"Täglich",claim:"{n} Diamanten abholen",claimed:"Heute abgeholt",next:"Nächstes Gebäude",build:"Bauen",need:"Noch {n}",free:"Freies Bauen",stone:"Stein",roof:"Dach",wood:"Holz",glass:"Glas",place:"Platzieren",remove:"Recyceln",layer:"Höhe",rotate:"Ziehen zum Drehen · Rad/Pinch zum Zoomen",clear:"Levelbelohnung! +{n} Block",visit:"Schloss ansehen",badges:"Abzeichen",full:"Blocklimit erreicht",occupied:"Dieser Platz ist belegt",support:"Vom Boden aus bauen",save:"Speichern nicht möglich",done:"Gebaut",level:"Schloss Lv.{n}"},
it:{title:"Castello Stellato",intro:"Completa i livelli, raccogli blocchi e costruisci il tuo castello.",blocks:"Blocchi",daily:"Giornaliero",claim:"Ricevi {n} diamanti",claimed:"Già ricevuto",next:"Prossimo edificio",build:"Costruisci",need:"Ne mancano {n}",free:"Costruzione libera",stone:"Pietra",roof:"Tetto",wood:"Legno",glass:"Vetro",place:"Posiziona",remove:"Ricicla",layer:"Altezza",rotate:"Trascina per ruotare · rotella/pizzico per zoom",clear:"Premio! +{n} blocco",visit:"Visita il castello",badges:"Distintivi",full:"Limite blocchi",occupied:"Spazio occupato",support:"Costruisci dal terreno",save:"Impossibile salvare",done:"Costruito",level:"Castello Lv.{n}"},
ru:{title:"Звёздный замок",intro:"Проходи уровни, собирай блоки и строй свой замок.",blocks:"Блоки",daily:"Ежедневно",claim:"Получить {n} алмазов",claimed:"Сегодня получено",next:"Следующая постройка",build:"Построить",need:"Нужно ещё {n}",free:"Свободная стройка",stone:"Камень",roof:"Крыша",wood:"Дерево",glass:"Стекло",place:"Поставить",remove:"Вернуть",layer:"Высота",rotate:"Тяните для вращения · колесо/щипок для масштаба",clear:"Награда! +{n} блок",visit:"Открыть замок",badges:"Значки",full:"Лимит блоков",occupied:"Место занято",support:"Стройте от земли",save:"Не удалось сохранить",done:"Построено",level:"Замок ур.{n}"},
hi:{title:"तारों का किला",intro:"स्तर पूरे करें, ब्लॉक जुटाएँ और अपना किला बनाएँ।",blocks:"ब्लॉक",daily:"रोज़",claim:"{n} हीरे लें",claimed:"आज ले लिए",next:"अगली इमारत",build:"बनाएँ",need:"{n} और चाहिए",free:"मुक्त निर्माण",stone:"पत्थर",roof:"छत",wood:"लकड़ी",glass:"काँच",place:"रखें",remove:"वापस लें",layer:"ऊँचाई",rotate:"खींचकर घुमाएँ · व्हील/पिंच से ज़ूम",clear:"इनाम! +{n} ब्लॉक",visit:"किला देखें",badges:"बैज",full:"ब्लॉक सीमा पूरी",occupied:"यह जगह भरी है",support:"ज़मीन से ऊपर बनाएँ",save:"सहेजा नहीं जा सका",done:"बन गया",level:"किला स्तर {n}"},
ar:{title:"قلعة النجوم",intro:"أكمل المراحل واجمع المكعبات وابنِ قلعتك الخاصة.",blocks:"مكعبات",daily:"يومي",claim:"استلم {n} ألماسة",claimed:"تم الاستلام اليوم",next:"المبنى التالي",build:"ابنِ",need:"ينقصك {n}",free:"بناء حر",stone:"حجر",roof:"سقف",wood:"خشب",glass:"زجاج",place:"ضع",remove:"استرجع",layer:"الارتفاع",rotate:"اسحب للتدوير · عجلة/ضم للتكبير",clear:"مكافأة! +{n} مكعب",visit:"افتح القلعة",badges:"الشارات",full:"بلغت حد المكعبات",occupied:"المكان مشغول",support:"ابنِ من الأرض",save:"تعذّر الحفظ",done:"مبني",level:"القلعة، المستوى {n}"}};
const editorCopy={
en:["Edit castle","Done","Welcome Gate","Starlight Bridge","Moon Garden","Sun Tower","Sky Observatory"],
"zh-Hant":["編輯城堡","完成編輯","迎賓城門","星光石橋","月光花園","日光塔","觀星台"],
"zh-Hans":["编辑城堡","完成编辑","迎宾城门","星光石桥","月光花园","日光塔","观星台"],
ja:["お城を編集","編集を終了","歓迎の門","星明かりの橋","月明かりの庭","陽光の塔","星見台"],
ko:["성 편집","편집 완료","환영의 문","별빛 다리","달빛 정원","햇빛 탑","별 관측대"],
es:["Editar castillo","Terminar","Puerta de Bienvenida","Puente Estelar","Jardín Lunar","Torre del Sol","Observatorio"],
"pt-BR":["Editar castelo","Concluir","Portão de Boas-vindas","Ponte Estelar","Jardim Lunar","Torre do Sol","Observatório"],
fr:["Modifier le château","Terminer","Porte d’accueil","Pont des étoiles","Jardin lunaire","Tour du Soleil","Observatoire"],
de:["Schloss bearbeiten","Fertig","Willkommenstor","Sternenbrücke","Mondgarten","Sonnenturm","Sternwarte"],
it:["Modifica castello","Fine","Porta di Benvenuto","Ponte stellato","Giardino Lunare","Torre del Sole","Osservatorio"],
ru:["Изменить замок","Готово","Приветственные ворота","Звёздный мост","Лунный сад","Солнечная башня","Обсерватория"],
hi:["किला संपादित करें","पूरा हुआ","स्वागत द्वार","तारों का पुल","चाँद का बगीचा","सूर्य मीनार","तारा वेधशाला"],
ar:["تعديل القلعة","إنهاء التعديل","بوابة الترحيب","جسر النجوم","حديقة القمر","برج الشمس","مرصد النجوم"]
};
for(const [language,values] of Object.entries(editorCopy)) ["edit","close","gate","bridge","garden","tower","observatory"].forEach((key,i)=>L[language][key]=values[i]);
const touchCopy={
en:["Tap a block face, then tap a material to build.","Tap a material to build on the highlighted face."],
"zh-Hant":["先點方塊表面，再點建材圖片來加蓋。","點建材圖片，就會蓋在亮起的那一面。"],
"zh-Hans":["先点方块表面，再点建材图片来加盖。","点建材图片，就会盖在亮起的那一面。"],
ja:["ブロックの面をタップし、素材をタップして建てよう。","素材をタップすると光った面に置けます。"],
ko:["블록 면을 누른 뒤 재료 그림을 눌러 지으세요.","재료를 누르면 빛나는 면에 블록을 놓습니다."],
es:["Toca una cara y luego un material para construir.","Toca un material para colocarlo en la cara iluminada."],
"pt-BR":["Toque numa face e depois num material para construir.","Toque num material para colocá-lo na face iluminada."],
fr:["Touchez une face, puis un matériau pour construire.","Touchez un matériau pour le poser sur la face éclairée."],
de:["Tippe auf eine Blockfläche und dann auf ein Material.","Tippe auf ein Material, um an der markierten Fläche zu bauen."],
it:["Tocca una faccia, poi un materiale per costruire.","Tocca un materiale per posarlo sulla faccia illuminata."],
ru:["Нажмите на грань блока, затем на материал.","Выберите материал для подсвеченной грани."],
hi:["ब्लॉक की सतह चुनें, फिर बनाने के लिए सामग्री चुनें।","चमकती सतह पर बनाने के लिए सामग्री चुनें।"],
ar:["المس وجه كتلة، ثم المس مادة للبناء.","المس مادة لوضعها على الوجه المضيء."]
};
for(const [language,values] of Object.entries(touchCopy)){L[language].pickFace=values[0];L[language].faceReady=values[1]}
const constructionCopy={"en":["Choose a face within the building area.","Blocks must stay connected to the ground or castle."],"zh-Hant":["請選擇建造範圍內的方塊表面。","方塊必須連接地面或城堡，回收後也不能懸空。"],"zh-Hans":["请选择建造范围内的方块表面。","方块必须连接地面或城堡，回收后也不能悬空。"],"ja":["建築範囲内の面を選んでください。","ブロックは地面やお城につなげてください。回収後も浮かせられません。"],"ko":["건설 영역 안의 면을 선택하세요.","블록은 바닥이나 성에 연결되어야 하며 회수 후에도 떠 있으면 안 됩니다."],"es":["Elige una cara dentro de la zona de construcción.","Los bloques deben seguir conectados al suelo o al castillo."],"pt-BR":["Escolha uma face dentro da área de construção.","Os blocos devem continuar ligados ao chão ou ao castelo."],"fr":["Choisissez une face dans la zone de construction.","Les blocs doivent rester reliés au sol ou au château."],"de":["Wähle eine Fläche innerhalb des Baubereichs.","Blöcke müssen mit dem Boden oder Schloss verbunden bleiben."],"it":["Scegli una faccia nella zona di costruzione.","I blocchi devono restare collegati al terreno o al castello."],"ru":["Выберите грань в пределах зоны строительства.","Блоки должны оставаться соединёнными с землёй или замком."],"hi":["निर्माण क्षेत्र के अंदर एक सतह चुनें।","ब्लॉक ज़मीन या किले से जुड़े रहने चाहिए।"],"ar":["اختر وجهاً داخل منطقة البناء.","يجب أن تبقى الكتل متصلة بالأرض أو القلعة."]};
for(const [language,values] of Object.entries(constructionCopy)){L[language].invalid=values[0];L[language].support=values[1]}
const alias={"zh-tw":"zh-Hant","zh-hant":"zh-Hant","zh-cn":"zh-Hans","zh-hans":"zh-Hans","pt-br":"pt-BR"};
const seg={en:"en","zh-Hant":"zh-tw","zh-Hans":"zh-cn",ja:"ja",ko:"ko",es:"es","pt-BR":"pt-br",fr:"fr",de:"de",it:"it",ru:"ru",hi:"hi",ar:"ar"};
function loc(){const x=window.WonderI18n?.actualLocale?.()||document.documentElement.lang||"en";return L[x]?x:(alias[String(x).toLowerCase()]||"en")}
function t(k,v={}){return (L[loc()][k]||L.en[k]||k).replace(/\{(\w+)\}/g,(_,n)=>String(v[n]??""))}
const clean=n=>Math.max(0,Math.floor(Number(n)||0));
function empty(){return{version:2,castleMaterials:0,completions:{},badges:[],buildings:["hall"]}}
function normBuildings(v,legacy=false){const a=Array.isArray(v)?v:[];if(legacy){const old=["tower","garden","library","observatory","gate"].filter(x=>a.includes(x)).length;return["hall",...buildings.slice(0,old).map(x=>x.id)]}const s=new Set(a.map(x=>x==="library"?"bridge":x));return["hall",...buildings.map(x=>x.id).filter(x=>s.has(x))]}
function read(){try{const s=JSON.parse(localStorage.getItem(STORE)||"null");if(!s||![1,2].includes(s.version))return empty();return{version:2,castleMaterials:s.castleMaterials==null?Math.floor(clean(s.starSand)/LEGACY):clean(s.castleMaterials),completions:s.completions&&typeof s.completions==="object"&&!Array.isArray(s.completions)?{...s.completions}:{},badges:Array.isArray(s.badges)?[...new Set(s.badges.filter(x=>typeof x==="string"))]:[],buildings:normBuildings(s.buildings,s.version===1)}}catch{return empty()}}
function save(s){try{localStorage.setItem(STORE,JSON.stringify(s));window.dispatchEvent(new Event("weightplay:castle-updated"));return true}catch{return false}}
function readBuild(){try{const x=JSON.parse(localStorage.getItem(BUILD)||"null");const arr=Array.isArray(x?.blocks)?x.blocks:[];const seen=new Set();return{version:1,blocks:arr.filter(b=>b&&["stone","roof","wood","glass"].includes(b.type)&&[b.x,b.y,b.z].every(Number.isInteger)&&Math.abs(b.x)<=BOARD&&Math.abs(b.z)<=BOARD&&b.y>=0&&b.y<MAXY&&!seen.has(`${b.x},${b.y},${b.z}`)&&seen.add(`${b.x},${b.y},${b.z}`)).slice(0,MAXBLOCKS)}}catch{return{version:1,blocks:[]}}}
function saveBuild(b){try{localStorage.setItem(BUILD,JSON.stringify(b));window.dispatchEvent(new Event("weightplay:castle-updated"));return true}catch{return false}}
function creditFirstClear(gameId,completionId="first-completion"){const g=String(gameId||"").trim(),c=String(completionId||"first-completion").trim();if(!/^[a-z0-9][a-z0-9-]{0,63}$/i.test(g)||!/^[a-z0-9][a-z0-9._-]{0,63}$/i.test(c))return{credited:false,reason:"invalid"};if(["stage-endless","stage-infinite","stage-survival","endless","infinite","survival"].includes(c.toLowerCase()))return{credited:false,reason:"non-stage-clear"};const s=read(),key=`${g}:${c}`;if(s.completions[key])return{credited:false,reason:"already-claimed",store:s};s.completions[key]=Date.now();if(!s.badges.includes(g))s.badges.push(g);s.castleMaterials+=REWARD;if(!save(s))return{credited:false,reason:"storage-unavailable"};window.WonderAnalytics?.track?.("castle_first_clear_reward",{game_id:g,completion_id:c,reward_amount:1,reward_type:"castle_block"});window.dispatchEvent(new CustomEvent("weightplay:castle-reward",{detail:{gameId:g,completionId:c,amount:1,currency:"castle-block"}}));return{credited:true,amount:1,currency:"castle-block",store:s}}
function build(id){const b=buildings.find(x=>x.id===id);if(!b)return{built:false,reason:"unknown-building"};const s=read();if(s.buildings.includes(id))return{built:false,reason:"already-built",store:s};if(s.castleMaterials<b.cost)return{built:false,reason:"not-enough",store:s,cost:b.cost};s.castleMaterials-=b.cost;s.buildings.push(id);return save(s)?{built:true,store:s}:{built:false,reason:"storage-unavailable"}}
function voxelBox(b){return{center:[b.x,b.y+.47,b.z],size:[.94,.94,.94]}}
function overlaps(a,b){return a.center.every((v,i)=>Math.abs(v-b.center[i])<(a.size[i]+b.size[i])/2-.08)}
function touches(a,b){return a.center.some((v,axis)=>{const gap=Math.abs(v-b.center[axis])-(a.size[axis]+b.size[axis])/2;return gap>=-.08&&gap<=.18&&a.center.every((q,i)=>i===axis||Math.abs(q-b.center[i])<(a.size[i]+b.size[i])/2-.2)})}
function structureBoxes(){const boxes=[];const collector={cube:(_a,x,y,z,w,h,d)=>{if(h>.25)boxes.push({center:[x,y,z],size:[w,h,d]})}};Scene.prototype.buildings.call(collector,[],read());return boxes}
function adjacent(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)+Math.abs(a.z-b.z)===1}
function supported(block,blocks,fixed){return block.y===0||blocks.some(q=>adjacent(q,block))||fixed.some(q=>touches(voxelBox(block),q))}
function allSupported(blocks,fixed){const reached=new Set(),queue=[];blocks.forEach((b,i)=>{if(b.y===0||fixed.some(q=>touches(voxelBox(b),q))){reached.add(i);queue.push(i)}});for(let n=0;n<queue.length;n++)blocks.forEach((b,i)=>{if(!reached.has(i)&&adjacent(blocks[queue[n]],b)){reached.add(i);queue.push(i)}});return reached.size===blocks.length}
function commitConstruction(b,s){let oldBuild,oldStore,ready=false;try{oldBuild=localStorage.getItem(BUILD);oldStore=localStorage.getItem(STORE);ready=true;localStorage.setItem(STORE,JSON.stringify(s));localStorage.setItem(BUILD,JSON.stringify(b))}catch{if(ready)for(const [key,value] of [[STORE,oldStore],[BUILD,oldBuild]])try{value==null?localStorage.removeItem(key):localStorage.setItem(key,value)}catch{}return false}window.dispatchEvent(new Event("weightplay:castle-updated"));return true}
function place(type,x,y,z){if(!["stone","roof","wood","glass"].includes(type)||![x,y,z].every(Number.isInteger)||Math.abs(x)>BOARD||Math.abs(z)>BOARD||y<0||y>=MAXY)return{placed:false,reason:"invalid"};const b=readBuild(),fixed=structureBoxes(),block={type,x,y,z};if(b.blocks.length>=MAXBLOCKS)return{placed:false,reason:"full"};if(b.blocks.some(q=>q.x===x&&q.y===y&&q.z===z)||fixed.some(q=>overlaps(voxelBox(block),q)))return{placed:false,reason:"occupied"};if(!supported(block,b.blocks,fixed))return{placed:false,reason:"support"};const s=read();if(s.castleMaterials<1)return{placed:false,reason:"not-enough"};b.blocks.push(block);s.castleMaterials--;return commitConstruction(b,s)?{placed:true,store:s,builder:b}:{placed:false,reason:"storage-unavailable"}}
function remove(x,y,z){const b=readBuild(),i=b.blocks.findIndex(q=>q.x===x&&q.y===y&&q.z===z);if(i<0)return{removed:false,reason:"invalid"};b.blocks.splice(i,1);if(!allSupported(b.blocks,structureBoxes()))return{removed:false,reason:"support"};const s=read();s.castleMaterials++;return commitConstruction(b,s)?{removed:true}:{removed:false,reason:"storage-unavailable"}}
function dailyDiamonds(s=read()){return daily[Math.max(0,Math.min(5,s.buildings.length-1))]}
function dailyDiamondBonus(s=read()){return dailyDiamonds(s)-daily[0]}
function dailyRewardState(){const d=new Date(),today=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;try{const old=localStorage.getItem(DAILY),s=JSON.parse(old||"{}")||{};return{today,old,s,claimedToday:s.lastClaimDate===today,available:true,amount:dailyDiamonds()}}catch{return{today,claimedToday:false,available:false,amount:dailyDiamonds()}}}
function claimNow(){const r=dailyRewardState();if(r.claimedToday)return{claimed:false,reason:"already-claimed"};if(!r.available||!window.WeightPlayWallet?.addDiamonds)return{claimed:false,reason:"storage-unavailable"};try{localStorage.setItem(DAILY,JSON.stringify({...r.s,lastClaimDate:r.today,totalClaims:clean(r.s.totalClaims)+1}));window.WeightPlayWallet.addDiamonds(r.amount)}catch{try{r.old==null?localStorage.removeItem(DAILY):localStorage.setItem(DAILY,r.old)}catch{}return{claimed:false,reason:"storage-unavailable"}}window.WeightPlayAudio?.play?.("feedback.success");render();return{claimed:true,amount:r.amount}}
async function claimDailyReward(){try{return navigator.locks?.request?await navigator.locks.request("weightplay-daily-reward",claimNow):claimNow()}catch{return{claimed:false,reason:"storage-unavailable"}}}
const api=Object.freeze({key:STORE,builderKey:BUILD,builderVersion:4,rewardPerClear:1,read,readBuilder:readBuild,creditFirstClear,build,placeBlock:place,removeBlock:remove,dailyDiamondBonus,dailyDiamonds,dailyRewardState,claimDailyReward,refresh:()=>render()});window.WeightPlayCastle=api;

const CUBE=(()=>{const c=document.createElement("canvas");c.width=64;c.height=72;const g=c.getContext("2d");if(!g)return "";for(const [fill,points] of [["#ffe39a",[[32,4],[60,19],[32,35],[4,19]]],["#e8b65a",[[4,19],[32,35],[32,68],[4,52]]],["#b67b36",[[32,35],[60,19],[60,52],[32,68]]]]){g.fillStyle=fill;g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fill()}return c.toDataURL("image/png")})();
const MATERIAL_IMAGES=Object.fromEntries(["stone","roof","wood","glass"].map(type=>{
const c=document.createElement("canvas");c.width=96;c.height=96;const g=c.getContext("2d");if(!g)return[type,CUBE];
const palettes={stone:["#d8cbb1","#b9aa91","#887c66"],roof:["#5bb6ad","#287b78","#18504f"],wood:["#d59c61","#a86e3c","#70452c"],glass:["#ccfbff","#6bcbdc","#2693ac"]};
const sides=[[[48,8],[87,29],[48,51],[9,29]],[[9,29],[48,51],[48,90],[9,68]],[[48,51],[87,29],[87,68],[48,90]]];
sides.forEach((points,i)=>{g.save();g.beginPath();points.forEach(([x,y],j)=>j?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fillStyle=palettes[type][i];g.fill();g.clip();g.strokeStyle=type==="glass"?"#e8ffff":"#0004";g.lineWidth=2;
if(type==="wood"){for(let x=15;x<96;x+=9){g.beginPath();g.moveTo(x,0);g.lineTo(x-12,96);g.stroke()}}
else if(type==="glass"){g.lineWidth=4;for(let x=-30;x<100;x+=35){g.beginPath();g.moveTo(x,5);g.lineTo(x+70,95);g.stroke()}}
else{for(let y=14;y<96;y+=type==="roof"?12:20){g.beginPath();g.moveTo(0,y);g.lineTo(96,y+15);g.stroke();for(let x=(y%40?5:20);x<96;x+=type==="roof"?14:26){g.beginPath();g.moveTo(x,y+x*.15);g.lineTo(x,y+19+x*.15);g.stroke()}}}
g.restore();g.strokeStyle="#09242b99";g.lineWidth=1.5;g.beginPath();points.forEach(([x,y],j)=>j?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.stroke()});return[type,c.toDataURL("image/png")]}));
const css=`
#weightplayCastle.wpb{order:16;margin:16px 0;padding:16px;border:2px solid #668f95;border-radius:10px;color:#f5f7ec;background:linear-gradient(145deg,#173f49,#0c2934);box-shadow:0 8px 0 #071d26}
.wpb *{box-sizing:border-box}.wpb-head,.wpb-row,.wpb-actions,.wpb-buildbar,.wpb-daily{display:flex;align-items:center;gap:10px}.wpb-head{justify-content:space-between}.wpb-title h2{margin:2px 0;font-size:clamp(26px,4vw,40px)}.wpb-title p{margin:4px 0;color:#b7d0d3}.wpb-balance{display:flex;align-items:center;gap:8px;padding:9px 13px;border:2px solid #ffe39a;border-radius:10px;color:#352710;background:linear-gradient(#ffe38a,#e8aa43);box-shadow:0 4px 0 #81541f}.wpb-balance img{width:34px}.wpb-balance strong{font-size:23px}
.wpb-daily{margin-top:12px;padding:10px 12px;border:1px solid #426c77;border-radius:8px;background:#10343e;flex-wrap:wrap}.wpb-gem{width:24px}.wpb-daily button{margin-inline-start:auto}
.wpb-main{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(250px,.55fr);gap:12px;margin-top:12px}.wpb-scene{position:relative;min-height:420px;border:2px solid #527b84;border-radius:10px;overflow:hidden;background:radial-gradient(circle at 50% 35%,#2b6169,#143944 65%,#0b2731)}.wpb-scene canvas{display:block;width:100%;height:100%;min-height:420px;touch-action:none}.wpb-note{pointer-events:none;position:absolute;top:10px;left:10px;padding:5px 8px;border-radius:6px;background:#071f29aa;color:#e7f4ef;font-size:12px}
.wpb-side{display:flex;flex-direction:column;gap:10px}.wpb-card{padding:13px;border:2px solid #456f79;border-radius:10px;background:linear-gradient(145deg,#214c56,#153640);box-shadow:0 4px 0 #071f29}.wpb-card h3{margin:0 0 8px;color:#ffd36c}.wpb-price{display:flex;align-items:center;gap:7px;font-weight:900;color:#ffe09a}.wpb-price img{width:25px}.wpb-progress{height:9px;border-radius:8px;background:#0b2730;overflow:hidden;margin:10px 0}.wpb-progress i{display:block;height:100%;background:linear-gradient(90deg,#f0b749,#ffe18b)}
.wpb-btn{min-height:42px;padding:8px 12px;border:2px solid #ffe4a0;border-radius:8px;color:#352510;background:linear-gradient(#ffdd7e,#e6a23d);box-shadow:0 3px 0 #80521c;font:inherit;font-weight:900;cursor:pointer}.wpb-btn:disabled{opacity:.45;cursor:not-allowed;box-shadow:none}.wpb-btn.alt{border-color:#72949b;color:#eaf4f1;background:#173c46;box-shadow:0 3px 0 #071f29}.wpb-btn.sel{outline:3px solid #ffd36c}
.wpb-builder{display:grid;gap:8px}.wpb-mats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.wpb-mats button{padding:7px 4px}.wpb-status{min-height:20px;color:#ffd988;font-weight:700}.wpb-badges{margin-top:12px;padding-top:10px;border-top:1px solid #456f79;color:#bad0d4}
.wpb-toast{position:fixed;z-index:10020;left:50%;bottom:max(80px,calc(env(safe-area-inset-bottom) + 80px));transform:translateX(-50%);display:flex;align-items:center;gap:10px;width:min(520px,calc(100% - 28px));padding:12px;border:2px solid #e2bd63;border-radius:10px;background:#fff2c9;color:#352b1b;box-shadow:0 10px 35px #0005;font-weight:900}.wpb-toast img{width:38px}.wpb-toast a{margin-inline-start:auto;color:#315b50}
@media(max-width:760px){#weightplayCastle.wpb{padding:11px}.wpb-main{grid-template-columns:1fr}.wpb-scene,.wpb-scene canvas{min-height:330px}.wpb-head{align-items:flex-start}.wpb-title h2{font-size:27px}.wpb-balance{padding:7px 9px}.wpb-mats{grid-template-columns:repeat(2,1fr)}}@media(max-width:390px){.wpb-scene,.wpb-scene canvas{min-height:280px}.wpb-btn{padding:7px 9px;font-size:13px}}
/* Compact preview; editing controls occupy only the explicitly opened dialog. */
#weightplayCastle.wpb{border-radius:4px}.wpb-btn{min-height:44px;border-radius:4px}.wpb-btn:focus-visible{outline:3px solid #a8f0fa;outline-offset:3px}
.wpb-main{grid-template-columns:minmax(0,1fr)}.wpb-side{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center}.wpb-upgrade{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:4px 12px;padding:10px 12px;border-radius:4px}.wpb-upgrade h3{font-size:12px;margin:0}.wpb-upgrade>strong{grid-column:1;font-size:18px}.wpb-upgrade .wpb-price{grid-column:2;grid-row:1 / span 2;font-size:14px}.wpb-upgrade .wpb-progress{grid-column:1;margin:3px 0;height:6px}.wpb-upgrade>small{grid-column:1;font-size:12px}.wpb-upgrade .wpb-actions{grid-column:2;grid-row:3 / span 2;justify-content:flex-end}.wpb-edit-entry{display:flex;align-items:center;justify-content:center;gap:10px;min-height:50px;max-width:100%}
.wpb-scene{min-height:340px;border-radius:4px}.wpb-scene canvas{height:340px;min-height:0}.wpb-gem{display:inline-block;width:22px;height:22px;flex:0 0 22px;clip-path:polygon(25% 0,75% 0,100% 35%,50% 100%,0 35%);background:conic-gradient(from 45deg at 50% 35%,#d5fcff,#168ab3,#68e5f2,#e8ffff,#299fc5)}
.wpb-editor{width:min(1100px,calc(100% - 24px));max-width:none;max-height:calc(100dvh - 24px);margin:auto;padding:16px;border:2px solid #638d93;border-radius:4px;background:#12343e;color:#f5f7ec;overflow:auto;overscroll-behavior:contain;box-shadow:0 16px 60px #0009}.wpb-editor::backdrop{background:#03151ee0}.wpb-editor-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.wpb-editor-head h2{margin:0;font-size:22px;color:#ffe09a}.wpb-editor .wpb-main{margin:0;grid-template-columns:minmax(0,1.4fr) minmax(260px,.6fr);align-items:start}.wpb-editor .wpb-side{display:flex}.wpb-editor .wpb-side>section{width:100%}.wpb-editor .wpb-scene canvas{height:420px}.wpb-editor .wpb-mats{grid-template-columns:repeat(4,minmax(0,1fr))}.wpb-editor .wpb-builder{order:-1;padding:10px}.wpb-touch-help{margin:0;font-size:13px;color:#bad0d4;line-height:1.5}.wpb-mats .wpb-material{padding:4px;min-width:0;display:grid;place-items:center}.wpb-material img{display:block;width:min(64px,100%);height:auto;aspect-ratio:1;object-fit:contain;pointer-events:none}.wpb-material.sel{background:#355b60}.wpb-editor .wpb-scene{position:sticky;top:0}.wpb-builder{border-radius:4px}.wpb-status:empty{display:none}.wpb-scene.is-growing{animation:wpb-grow .9s ease-out}@keyframes wpb-grow{0%{filter:brightness(.8);transform:translateY(4px)}40%{filter:brightness(1.25);transform:translateY(-2px)}100%{filter:brightness(1);transform:translateY(0)}}
@media(max-width:760px){.wpb-side{grid-template-columns:minmax(0,1fr)}.wpb-edit-entry{width:100%}.wpb-scene{min-height:0}.wpb-scene canvas{height:300px;min-height:0}.wpb-editor{padding:10px}.wpb-editor-head h2{font-size:19px}.wpb-editor .wpb-main{grid-template-columns:minmax(0,1fr);gap:10px}.wpb-editor .wpb-scene{position:relative;min-height:0}.wpb-editor .wpb-scene canvas{height:clamp(200px,38dvh,320px);min-height:0}.wpb-editor .wpb-note{max-width:calc(100% - 20px);font-size:11px}.wpb-editor .wpb-btn{min-height:44px}.wpb-title h2{font-size:26px}.wpb-title p{font-size:13px}.wpb-card{min-width:0}.wpb-editor-head .wpb-btn{max-width:55%;white-space:normal}}
@media(prefers-reduced-motion:reduce){.wpb-scene.is-growing{animation:none}}
`;const st=document.createElement("style");st.textContent=css;document.head.append(st);

function mat4(){return new Float32Array(16)}function ident(o){o.fill(0);o[0]=o[5]=o[10]=o[15]=1;return o}
function mul(o,a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let r0=0;r0<4;r0++)r[c*4+r0]=a[r0]*b[c*4]+a[4+r0]*b[c*4+1]+a[8+r0]*b[c*4+2]+a[12+r0]*b[c*4+3];o.set(r);return o}
function perspective(o,fovy,asp,n,f){const q=1/Math.tan(fovy/2);o.fill(0);o[0]=q/asp;o[5]=q;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o}
function look(o,e,c,u=[0,1,0]){let zx=e[0]-c[0],zy=e[1]-c[1],zz=e[2]-c[2],zl=Math.hypot(zx,zy,zz);zx/=zl;zy/=zl;zz/=zl;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx,xl=Math.hypot(xx,xy,xz);xx/=xl;xy/=xl;xz/=xl;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;ident(o);o[0]=xx;o[1]=yx;o[2]=zx;o[4]=xy;o[5]=yy;o[6]=zy;o[8]=xz;o[9]=yz;o[10]=zz;o[12]=-(xx*e[0]+xy*e[1]+xz*e[2]);o[13]=-(yx*e[0]+yy*e[1]+yz*e[2]);o[14]=-(zx*e[0]+zy*e[1]+zz*e[2]);return o}
const faces=[[[0,0,1],[0,0,1],[1,0,1],[1,1,1],[0,0,1],[1,1,1],[0,1,1]],[[0,0,-1],[1,0,0],[0,0,0],[0,1,0],[1,0,0],[0,1,0],[1,1,0]],[[1,0,0],[1,0,1],[1,0,0],[1,1,0],[1,0,1],[1,1,0],[1,1,1]],[[-1,0,0],[0,0,0],[0,0,1],[0,1,1],[0,0,0],[0,1,1],[0,1,0]],[[0,1,0],[0,1,1],[1,1,1],[1,1,0],[0,1,1],[1,1,0],[0,1,0]],[[0,-1,0],[0,0,0],[1,0,0],[1,0,1],[0,0,0],[1,0,1],[0,0,1]]];
function color(hex){return[((hex>>16)&255)/255,((hex>>8)&255)/255,(hex&255)/255]}
class Scene{
constructor(canvas){this.c=canvas;this.gl=canvas.getContext("webgl",{antialias:true,alpha:true});if(!this.gl)throw Error("WebGL");this.yaw=.72;this.pitch=.72;this.zoom=24;this.ptr=new Map();this.init();this.bind();this.draw();this.observer=new ResizeObserver(()=>this.draw());this.observer.observe(canvas)}
shader(t,s){const g=this.gl,x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(x));return x}
init(){const g=this.gl,v=this.shader(g.VERTEX_SHADER,'attribute vec3 p,n,c;uniform mat4 m;varying vec3 vc;void main(){float d=.48+.52*max(dot(normalize(n),normalize(vec3(.5,1.,.35))),0.);vc=c*d;gl_Position=m*vec4(p,1.);}'),f=this.shader(g.FRAGMENT_SHADER,'precision mediump float;varying vec3 vc;void main(){gl_FragColor=vec4(vc,1.);}');this.pr=g.createProgram();g.attachShader(this.pr,v);g.attachShader(this.pr,f);g.linkProgram(this.pr);g.deleteShader(v);g.deleteShader(f);this.buf=g.createBuffer();this.ap=g.getAttribLocation(this.pr,"p");this.an=g.getAttribLocation(this.pr,"n");this.ac=g.getAttribLocation(this.pr,"c");this.um=g.getUniformLocation(this.pr,"m");g.enable(g.DEPTH_TEST);g.enable(g.CULL_FACE);g.clearColor(0,0,0,0)}
cube(a,x,y,z,w,h,d,col,meta={kind:"structure"}){this.boxes?.push({center:[x,y,z],size:[w,h,d],...meta});for(const F of faces){const n=F[0],pts=F.slice(1);for(const P of pts){a.push(x+(P[0]-.5)*w,y+(P[1]-.5)*h,z+(P[2]-.5)*d,n[0],n[1],n[2],...col)}}}
geometry(){this.boxes=[];const a=[];const tileA=color(0x386b66),tileB=color(0x2d5a56);for(let x=-BOARD;x<=BOARD;x++)for(let z=-BOARD;z<=BOARD;z++)this.cube(a,x,-.23,z,.94,.22,.94,(x+z)&1?tileA:tileB,{kind:"ground",x,z});this.cube(a,0,-.55,0,14,.45,14,color(0x805d35),{kind:"base"});const s=read();this.buildings(a,s);for(const b of readBuild().blocks){const cols={stone:0xb9aa91,roof:0x247b78,wood:0x9a6136,glass:0x74d8e6};this.cube(a,b.x,b.y+.47,b.z,.94,.94,.94,color(cols[b.type]),{kind:"custom",...b})}if(UI?.edit&&UI.selection){const selected=UI.selection;const live=this.boxes.find(box=>box.kind===selected.kind&&box.center.every((v,i)=>Math.abs(v-selected.center[i])<.001));if(live)this.highlight(a,{...live,normal:selected.normal});else UI.selection=null;}return new Float32Array(a)}
buildings(a,s){
const palette={stone:0xc4baa5,shade:0xa99d87,roof:0x287c79,gold:0xe4b957,wood:0x885933,leaf:0x478b67,glass:0x74d7df};
const block=(x,y,z,key="stone")=>this.cube(a,x,y+.47,z,.94,.94,.94,color(palette[key]));
const roof=(x,z,width,depth,y)=>{for(let layer=0;layer<Math.ceil(Math.min(width,depth)/2);layer++){const w=width-layer*2,d=depth-layer*2;if(w<1||d<1)break;for(let i=0;i<w;i++)for(let k=0;k<d;k++)block(x+i-(w-1)/2,y+layer,z+k-(d-1)/2,"roof")}};
const tower=(x,z,height)=>{for(let y=0;y<height;y++)for(let i=-1;i<=1;i++)for(let k=-1;k<=1;k++)if(Math.abs(i)+Math.abs(k)>0)block(x+i,y,z+k,y===height-1?"gold":(y===2&&i===0&&k===1?"glass":"stone"));for(const [i,k] of [[-1,-1],[-1,1],[1,-1],[1,1]])block(x+i,height,z+k);roof(x,z,3,3,height+1)};
const level=s.buildings.length,h=level>=4?3:2;
// Every wall and roof is made of separately visible units, including the first level.
for(let y=0;y<h;y++)for(let x=-2;x<=2;x++)for(let z=-3;z<=0;z++)if((Math.abs(x)===2||z===-3||z===0)&&!(x===0&&z===0&&y<2))block(x,y,z,y===1&&z===0&&Math.abs(x)===1?"glass":((x+z+y)%3===0?"shade":"stone"));
roof(0,-1.5,5,4,h);block(0,h+2,-1.5,"gold");
for(let z=1;z<=4;z++)this.cube(a,0,.02,z,.94,.12,.94,color(0x9d967f));
if(s.buildings.includes("gate")){tower(-2,4,2);tower(2,4,2);for(let x=-1;x<=1;x++){block(x,2,4,"stone");if(x!==0)block(x,3,4,"gold")}}
if(s.buildings.includes("bridge")){for(let z=0;z<=4;z++){this.cube(a,-4.8,-.08,z,2,.08,.94,color(0x3b9bb4));for(const x of [-5.3,-4.3])block(x,0,z,"shade");if(z%2===0){block(-5.8,1,z,"stone");block(-3.8,1,z,"stone")}}}
if(s.buildings.includes("garden")){for(const [x,z] of [[4,2],[5,4],[3,5]]){block(x,0,z,"wood");block(x,1,z,"wood");for(let i=-1;i<=1;i++)for(let k=-1;k<=1;k++)block(x+i,2,z+k,"leaf");block(x,3,z,"leaf")}for(let x=3;x<=5;x++)this.cube(a,x,.02,0,.92,.16,.92,color(0x649868))}
if(s.buildings.includes("tower")){tower(4,-3,5);for(let y=0;y<3;y++)block(2,y,-3,"stone");block(4,7,-3,"glass")}
if(s.buildings.includes("observatory")){tower(-4,-3,4);for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)block(-4+x,6,-3+z,"glass");block(-4,7,-3,"gold");for(const x of [-2,2])for(let z=0;z<=2;z++){block(x,0,z,"shade");if(z===2)block(x,1,z,"gold")}}
}

resize(){const g=this.gl,d=Math.min(devicePixelRatio||1,1.7),w=Math.max(1,Math.floor(this.c.clientWidth*d)),h=Math.max(1,Math.floor(this.c.clientHeight*d));if(this.c.width!==w||this.c.height!==h){this.c.width=w;this.c.height=h}g.viewport(0,0,w,h)}
draw(){const g=this.gl;this.resize();const ar=this.c.width/this.c.height,cp=Math.cos(this.pitch),eye=[Math.sin(this.yaw)*cp*this.zoom,Math.sin(this.pitch)*this.zoom+5,Math.cos(this.yaw)*cp*this.zoom],P=mat4(),V=mat4(),M=mat4();perspective(P,.78,ar,.1,100);look(V,eye,[0,1.6,0]);mul(M,P,V);const data=this.geometry();g.bindBuffer(g.ARRAY_BUFFER,this.buf);g.bufferData(g.ARRAY_BUFFER,data,g.DYNAMIC_DRAW);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.pr);const S=36;for(const [loc,off] of [[this.ap,0],[this.an,3],[this.ac,6]]){g.enableVertexAttribArray(loc);g.vertexAttribPointer(loc,3,g.FLOAT,false,S,off*4)}g.uniformMatrix4fv(this.um,false,M);g.drawArrays(g.TRIANGLES,0,data.length/9)}
highlight(a,hit){const face=faces.find(f=>f[0].every((v,i)=>v===hit.normal[i]));if(!face)return;for(const p of face.slice(1)){const point=p.map((v,i)=>hit.center[i]+(v-.5)*hit.size[i]+hit.normal[i]*.012);a.push(...point,...hit.normal,1,.78,.16)}}
pick(clientX,clientY){const rect=this.c.getBoundingClientRect();if(!rect.width||!rect.height)return null;const norm=v=>{const d=Math.hypot(...v);return v.map(x=>x/d)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],cp=Math.cos(this.pitch),origin=[Math.sin(this.yaw)*cp*this.zoom,Math.sin(this.pitch)*this.zoom+5,Math.cos(this.yaw)*cp*this.zoom],forward=norm([0,1.6,0].map((v,i)=>v-origin[i])),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),x=((clientX-rect.left)/rect.width*2-1)*Math.tan(.39)*(this.c.width/this.c.height),y=(1-(clientY-rect.top)/rect.height*2)*Math.tan(.39),direction=norm(forward.map((v,i)=>v+x*right[i]+y*up[i]));let best=null,distance=Infinity;
for(const box of this.boxes||[]){if(box.kind==="base")continue;let near=-Infinity,far=Infinity,normal=[0,0,0],valid=true;for(let axis=0;axis<3;axis++){const low=box.center[axis]-box.size[axis]/2,high=box.center[axis]+box.size[axis]/2;if(Math.abs(direction[axis])<1e-8){if(origin[axis]<low||origin[axis]>high){valid=false;break}continue}const a=(low-origin[axis])/direction[axis],b=(high-origin[axis])/direction[axis],entry=Math.min(a,b);if(entry>near){near=entry;normal=[0,0,0];normal[axis]=direction[axis]>0?-1:1}far=Math.min(far,Math.max(a,b));if(far<Math.max(near,0)){valid=false;break}}if(valid&&near>=0&&near<distance){distance=near;best={...box,normal}}}return best}
bind(){const c=this.c;
c.addEventListener("pointerdown",e=>{if(e.button!==0)return;c.setPointerCapture(e.pointerId);this.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,tap:true});if(this.ptr.size>1){for(const p of this.ptr.values())p.tap=false;const p=[...this.ptr.values()];this.lastPinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});
c.addEventListener("pointermove",e=>{const old=this.ptr.get(e.pointerId);if(!old)return;const now={...old,x:e.clientX,y:e.clientY};if(Math.hypot(now.x-now.sx,now.y-now.sy)>7)now.tap=false;this.ptr.set(e.pointerId,now);if(this.ptr.size===1&&!now.tap){this.yaw-=(now.x-old.x)*.008;this.pitch=Math.max(.2,Math.min(1.15,this.pitch+(now.y-old.y)*.006))}else if(this.ptr.size===2){const p=[...this.ptr.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(d>1&&this.lastPinch>1)this.zoom=Math.max(12,Math.min(38,this.zoom*this.lastPinch/d));this.lastPinch=d}this.draw()});
const end=(e,cancel=false)=>{const p=this.ptr.get(e.pointerId),tap=!cancel&&p?.tap&&this.ptr.size===1&&Math.hypot(e.clientX-p.sx,e.clientY-p.sy)<=7;this.ptr.delete(e.pointerId);if(this.ptr.size<2)this.lastPinch=0;if(tap&&UI?.edit){UI.selection=this.pick(e.clientX,e.clientY);UI.status=UI.selection?t("faceReady"):t("pickFace");render()}};
c.addEventListener("pointerup",e=>end(e));c.addEventListener("pointercancel",e=>end(e,true));c.addEventListener("lostpointercapture",e=>{this.ptr.delete(e.pointerId);if(this.ptr.size<2)this.lastPinch=0});
c.addEventListener("wheel",e=>{e.preventDefault();this.zoom=Math.max(12,Math.min(38,this.zoom*Math.exp(Math.max(-120,Math.min(120,e.deltaY))*.0015)));this.draw()},{passive:false});
c.addEventListener("keydown",e=>{if(!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","+","-","=","Enter"].includes(e.key))return;e.preventDefault();if(e.key==="ArrowLeft")this.yaw-=.15;if(e.key==="ArrowRight")this.yaw+=.15;if(e.key==="ArrowUp")this.pitch=Math.min(1.15,this.pitch+.08);if(e.key==="ArrowDown")this.pitch=Math.max(.2,this.pitch-.08);if(["+","=","-"].includes(e.key))this.zoom=Math.max(12,Math.min(38,this.zoom+(e.key==="-"?2:-2)));this.draw();if(e.key==="Enter"&&UI?.edit){const r=c.getBoundingClientRect();UI.selection=this.pick(r.left+r.width/2,r.top+r.height/2);UI.status=UI.selection?t("faceReady"):t("pickFace");render();document.querySelector(".wpb-editor canvas")?.focus({preventScroll:true})}})
}

dispose(){this.observer?.disconnect();this.ptr.clear();try{this.gl.deleteBuffer(this.buf);this.gl.deleteProgram(this.pr);this.gl.getExtension("WEBGL_lose_context")?.loseContext()}catch{}}
}

let UI=null,scene=null,midnight,editorOverflow=null;
function editorScroll(open){if(open&&editorOverflow===null){editorOverflow={overflow:document.documentElement.style.overflow,y:window.scrollY};document.documentElement.style.overflow="hidden"}else if(!open&&editorOverflow!==null){document.documentElement.style.overflow=editorOverflow.overflow;window.scrollTo({top:editorOverflow.y,behavior:"instant"});editorOverflow=null}}
function closeEditor(){if(!UI)return;UI.edit=false;UI.status="";render();document.querySelector('[data-a="edit"]')?.focus({preventScroll:true})}
function icon(){return `<img src="${CUBE}" alt="">`}
function faceTarget(hit){if(!hit)return null;if(hit.kind==="ground")return hit.normal[1]===1?{x:hit.x,y:0,z:hit.z}:null;const coordinates=hit.center.map((v,i)=>Math.round(v-(i===1?.47:0)+hit.normal[i]*(hit.size[i]/2+.5)));return{x:coordinates[0],y:coordinates[1],z:coordinates[2]}}
function constructionError(reason){return t(["full","occupied","support","invalid"].includes(reason)?reason:reason==="not-enough"?"need":"save",{n:1})}
function render(){const camera=scene?{yaw:scene.yaw,pitch:scene.pitch,zoom:scene.zoom}:null;const active=document.activeElement?.dataset||{},scroll=document.querySelector(".wpb-editor")?.scrollTop||0;const m=document.querySelector("#weightplayCastle");if(!m)return;if(!UI){UI={type:"stone",selection:null,edit:false,status:""};m.className="wpb"}const s=read(),b=readBuild(),r=dailyRewardState(),w=window.WeightPlayWallet?.read?.()||{diamonds:0},next=buildings.find(x=>!s.buildings.includes(x.id));m.dir=loc()==="ar"?"rtl":"ltr";
m.innerHTML=`<div class="wpb-head"><div class="wpb-title"><small>WEIGHTPLAY</small><h2 id="wpCastleTitle">${t("title")}</h2><p>${t("intro")}</p></div><div class="wpb-balance">${icon()}<div><strong>${s.castleMaterials}</strong><div>${t("blocks")}</div></div></div></div>
<div class="wpb-daily"><span class="wpb-gem" aria-hidden="true"></span><span>${w.diamonds}</span><span>${t("daily")} +${r.amount}</span><button class="wpb-btn" data-a="claim" ${r.claimedToday||!r.available||!window.WeightPlayWallet?"disabled":""}>${r.claimedToday?t("claimed"):t("claim",{n:r.amount})}</button></div>
${UI.edit?`<dialog class="wpb-editor" aria-labelledby="wpbEditorTitle"><header class="wpb-editor-head"><h2 id="wpbEditorTitle">${t("edit")}</h2><button class="wpb-btn alt" data-a="close" autofocus>${t("close")} ×</button></header>`:""}<div class="wpb-main"><div class="wpb-scene ${UI.growing>Date.now()?"is-growing":""}"><canvas aria-label="${t("title")}" tabindex="0"></canvas><div class="wpb-note">${t("level",{n:s.buildings.length})} · ${t("rotate")}</div></div>
<div class="wpb-side"><section class="wpb-card wpb-upgrade"><h3>${t("next")}</h3>${next?`<strong>${t(next.id)}</strong><div class="wpb-price">${icon()}<span>${next.cost} ${t("blocks")}</span></div><div class="wpb-progress"><i style="width:${Math.min(100,s.castleMaterials/next.cost*100)}%"></i></div><small>${s.castleMaterials<next.cost?t("need",{n:next.cost-s.castleMaterials}):""}</small><div class="wpb-actions"><button class="wpb-btn" data-a="build" data-id="${next.id}" ${s.castleMaterials<next.cost?"disabled":""}>${t("build")}</button></div>`:`<strong>${t("done")}</strong>`}</section>
${UI.edit?`<section class="wpb-card wpb-builder"><p class="wpb-touch-help">${t("pickFace")}</p><div class="wpb-mats">${["stone","roof","wood","glass"].map(x=>`<button class="wpb-btn alt wpb-material ${UI.type===x?"sel":""}" data-a="mat" data-type="${x}" title="${t(x)}" aria-label="${t(x)}"><img src="${MATERIAL_IMAGES[x]}" alt="" width="96" height="96" draggable="false"></button>`).join("")}</div><div class="wpb-buildbar"><button class="wpb-btn alt" data-a="remove" ${UI.selection?.kind!=="custom"?"disabled":""}>${t("remove")}</button></div><div class="wpb-status" role="status" aria-live="polite">${UI.status||""}</div></section>`:`<button class="wpb-btn wpb-edit-entry" data-a="edit" aria-haspopup="dialog">${t("edit")} <span aria-hidden="true">▦</span></button>`}</div></div>${UI.edit?"</dialog>":""}<div class="wpb-badges">${t("badges")}: <strong>${s.badges.length}</strong> · ${b.blocks.length}/${MAXBLOCKS}</div>`;
editorScroll(UI.edit);
const dialog=m.querySelector(".wpb-editor");
if(dialog){dialog.showModal();dialog.scrollTop=scroll;dialog.addEventListener("cancel",e=>{e.preventDefault();closeEditor()});dialog.addEventListener("click",e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeEditor()});const target=[...dialog.querySelectorAll("[data-a]")].find(x=>x.dataset.a===active.a&&x.dataset.type===active.type);target?.focus({preventScroll:true})}
scene?.dispose();try{scene=new Scene(m.querySelector("canvas"));if(camera){Object.assign(scene,camera);scene.draw()}}catch{scene=null}
m.onclick=async e=>{const q=e.target.closest("[data-a]");if(!q)return;const a=q.dataset.a;if(a==="edit"){UI.edit=true;UI.status="";render();return}if(a==="close"){closeEditor();return}if(a==="claim"){const z=await claimDailyReward();UI.status=z.claimed?"✓":t("save");render();return}if(a==="build"){const z=build(q.dataset.id);if(z.built)UI.growing=Date.now()+900;UI.status=z.built?"✓":t(z.reason==="not-enough"?"need":"save",{n:z.cost-(z.store?.castleMaterials||0)});render();return}if(a==="mat"){UI.type=q.dataset.type;const selected=UI.selection,target=faceTarget(selected);if(!selected){UI.status=t("pickFace");render();return}if(!target){UI.status=t("invalid");render();return}const z=place(UI.type,target.x,target.y,target.z);if(z.placed)UI.selection={kind:"custom",type:UI.type,...target,...voxelBox(target),normal:selected.normal};UI.status=z.placed?"✓":constructionError(z.reason);render();return}if(a==="remove"&&UI.selection?.kind==="custom"){const selected=UI.selection,z=remove(selected.x,selected.y,selected.z);if(z.removed)UI.selection=null;UI.status=z.removed?"✓":constructionError(z.reason);render()}}

}
function schedule(){clearTimeout(midnight);if(!document.querySelector("#weightplayCastle"))return;const n=new Date(),d=new Date(n.getFullYear(),n.getMonth(),n.getDate()+1);midnight=setTimeout(()=>{render();schedule()},d-n+150)}
function mount(){const old=document.querySelector("#weightplayCastle"),dailyNode=document.querySelector("#dailyReward");if(!old&&!dailyNode)return;const m=old||document.createElement("section");if(!old){m.id="weightplayCastle";dailyNode.after(m)}document.querySelector("#lobbyAccountStrip")?.remove();dailyNode?.remove();render();schedule();if(location.hash==="#castle")m.scrollIntoView({block:"start"})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount,{once:true});else mount();
window.addEventListener("weightplay:castle-updated",()=>{if(document.querySelector("#weightplayCastle"))render()});
window.addEventListener("weightplay:game-completed",e=>{const d=e.detail||{},o=String(d.outcome||"").toLowerCase();if(d.cleared===false||d.success===false||d.won===false||["fail","failed","loss","lose","defeat"].includes(o))return;const g=d.gameId||location.pathname.match(/\/games\/([^/]+)/)?.[1];if(!g)return;const raw=d.stageId??d.stage_id??d.levelId??d.level_id??d.stage??d.level,txt=(typeof raw==="string"||typeof raw==="number")?String(raw).trim():"",id=d.completionId??(txt?(txt.toLowerCase().startsWith("stage-")?txt:`stage-${txt.toLowerCase().replace(/[^a-z0-9._-]+/g,"-").slice(0,54)}`):"first-completion");creditFirstClear(g,id)});
window.addEventListener("weightplay:castle-reward",e=>{if(document.querySelector("#weightplayCastle"))return;document.querySelectorAll(".wpb-toast").forEach(x=>x.remove());const n=document.createElement("div");n.className="wpb-toast";n.setAttribute("role","status");n.innerHTML=`${icon()}<span>${t("clear",{n:e.detail?.amount||1})}</span><a href="/${seg[loc()]}/#castle">${t("visit")}</a>`;document.body.append(n);setTimeout(()=>n.remove(),6500)});
window.addEventListener("wonder:locale-change",()=>render());window.addEventListener("storage",e=>{if([STORE,BUILD,DAILY,"weightplayWallet"].includes(e.key)||e.key==null)render()});window.addEventListener("pagehide",()=>{scene?.dispose();scene=null;editorScroll(false);clearTimeout(midnight)});window.addEventListener("pageshow",()=>{render();schedule()});
window.dispatchEvent(new Event("weightplay:castle-ready"));
})();
