(() => {
  "use strict";
  const locales = window.ANIMAL_LAYER_GROVE_LOCALES || {};
  const scenes = [
    { nameKey: "scene1", introKey: "scene1Intro", targetKey: "target1", wrongKey: "wrong1", target: ["fern", "pond", "moon"], initial: ["pond", "moon", "fern"], layers: ["fern", "pond", "moon"], glyphs: { fern: "🌿", pond: "◒", moon: "☾" } },
    { nameKey: "scene2", introKey: "scene2Intro", targetKey: "target2", wrongKey: "wrong2", target: ["reeds", "amber", "creek"], initial: ["amber", "reeds", "creek"], layers: ["reeds", "creek", "amber"], glyphs: { reeds: "🌾", creek: "≈", amber: "✦" } },
    { nameKey: "scene3", introKey: "scene3Intro", targetKey: "target3", wrongKey: "wrong3", target: ["owl", "frost", "pine"], initial: ["owl", "pine", "frost"], layers: ["owl", "frost", "pine"], glyphs: { owl: "🦉", frost: "❄", pine: "♠" } }
  ];
  const state = { locale: "en", scene: 0, completed: 0, order: [], moves: 0, sessionMoves: 0, screen: "main", sound: true };
  const $ = (id) => document.getElementById(id);
  const t = (key, vars = {}) => { const table = locales[state.locale] || locales.en || {}; let value = table[key] || locales.en?.[key] || key; Object.entries(vars).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); }); return value; };
  const track = (event, detail = {}) => { window.dispatchEvent(new CustomEvent("weightplay:analytics", { detail: { game: "animal-layer-grove", event, ...detail } })); };
  const tone = (frequency) => { if (!state.sound) return; try { const AudioContextClass = window.AudioContext || window.webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0.03, context.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.12); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.12); oscillator.addEventListener("ended", () => context.close(), { once: true }); } catch (_) {} };
  const show = (screen) => { state.screen = screen; document.querySelectorAll("section[data-screen]").forEach((node) => { node.hidden = node.dataset.screen !== screen; }); document.body.dataset.screen = screen; };
  const readBest = () => { try { const value = Number(localStorage.getItem("weightplay-animal-layer-grove-best-v3")); return Number.isFinite(value) && value > 0 ? value : null; } catch (_) { return null; } };
  const saveBest = () => { try { const old = readBest(); if (!old || state.sessionMoves < old) localStorage.setItem("weightplay-animal-layer-grove-best-v3", String(state.sessionMoves)); } catch (_) {} };
  const announce = (key, vars = {}, kind = "") => { const node = $("battleStatus"); node.textContent = t(key, vars); node.dataset.kind = kind; };
  const depthKey = (index) => index === 0 ? "front" : index === 1 ? "middle" : "backLayer";
  const depthLabel = (index) => t(depthKey(index));
  const currentScene = () => scenes[state.scene];
  const renderStages = () => { $("stageList").replaceChildren(...scenes.map((scene, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "stage-card"; button.setAttribute("role", "listitem"); button.innerHTML = `<strong>${t("round", { n: index + 1, total: scenes.length })}</strong><span>${t(scene.nameKey)}</span><small>${index < state.completed ? t("complete") : t("open")}</small>`; button.addEventListener("click", () => startScene(index)); return button; })); };
  const renderTarget = (scene) => { const wrap = $("targetWindow"); const emblems = document.createElement("div"); emblems.className = "target-emblems"; scene.target.forEach((id) => { const emblem = document.createElement("span"); emblem.className = `target-emblem layer-art layer-art-${id}`; emblem.textContent = scene.glyphs[id]; emblem.setAttribute("aria-label", t(id)); emblems.append(emblem); }); wrap.replaceChildren(emblems); $("targetCaption").textContent = t(scene.targetKey); };
  const renderLayers = () => { const scene = currentScene(); const list = $("layerList"); list.replaceChildren(...state.order.map((id, index) => { const row = document.createElement("div"); row.className = "layer-row"; row.dataset.depth = String(index); row.dataset.layerId = id; row.setAttribute("role", "listitem"); const info = document.createElement("div"); info.className = "layer-info"; const glyph = document.createElement("span"); glyph.className = `layer-glyph layer-art layer-art-${id}`; glyph.textContent = scene.glyphs[id]; glyph.setAttribute("aria-hidden", "true"); const copy = document.createElement("span"); copy.className = "layer-copy"; const name = document.createElement("strong"); name.textContent = t(id); const detail = document.createElement("small"); detail.textContent = t("layerLabel", { name: t(id), depth: depthLabel(index) }); copy.append(name, detail); info.append(glyph, copy); const up = document.createElement("button"); up.type = "button"; up.className = "order-btn"; up.textContent = "↑"; up.title = depthLabel(index - 1); up.setAttribute("aria-label", `${t("frontToBack")}: ${t("moveForward", { name: t(id) })}`); up.disabled = index === 0; up.addEventListener("click", () => moveLayer(index, -1)); const down = document.createElement("button"); down.type = "button"; down.className = "order-btn"; down.textContent = "↓"; down.title = depthLabel(index + 1); down.setAttribute("aria-label", `${t("frontToBack")}: ${t("moveBackward", { name: t(id) })}`); down.disabled = index === state.order.length - 1; down.addEventListener("click", () => moveLayer(index, 1)); row.append(info, up, down); list.append(row); return row; })); $("moveCount").textContent = t("moveCount", { n: state.sessionMoves }); };
  const renderBattle = () => { const scene = currentScene(); $("groveName").textContent = t(scene.nameKey); $("groveLabel").textContent = t("round", { n: state.scene + 1, total: scenes.length }); $("groveIntro").textContent = t(scene.introKey); renderTarget(scene); renderLayers(); $("checkBtn").disabled = !state.order.length; };
  const renderResult = () => { const complete = state.completed >= scenes.length; $("resultTitle").textContent = complete ? t("resultTitle") : t("resultPartial"); $("resultText").textContent = t("resultText", { count: state.completed, total: scenes.length, moves: state.sessionMoves }); $("resultPrimaryBtn").textContent = complete ? t("map") : t("next"); $("resultPrimaryBtn").onclick = complete ? () => { show("stage"); renderStages(); } : () => startScene(state.scene + 1); $("resultMapBtn").hidden = complete; };
  const startScene = (index) => { state.scene = Math.max(0, Math.min(scenes.length - 1, index)); state.order = [...scenes[state.scene].initial]; state.moves = 0; if (index === 0) state.sessionMoves = 0; show("battle"); renderBattle(); announce("waiting"); track("scene_start", { scene: state.scene + 1 }); };
  const moveLayer = (index, direction) => { const next = index + direction; if (next < 0 || next >= state.order.length) return; [state.order[index], state.order[next]] = [state.order[next], state.order[index]]; state.moves += 1; state.sessionMoves += 1; renderLayers(); announce("selected"); tone(520); track("layer_move", { scene: state.scene + 1, moves: state.sessionMoves }); };
  const resetLayers = () => { state.order = [...currentScene().initial]; state.moves += 1; state.sessionMoves += 1; renderLayers(); announce("waiting"); track("layer_reset", { scene: state.scene + 1 }); };
  const checkWindow = () => { const scene = currentScene(); if (!state.order.length) return; const matched = scene.target.every((id, index) => state.order[index] === id); if (!matched) { const mismatch = scene.target.findIndex((id, index) => state.order[index] !== id); const expected = mismatch >= 0 ? t(idFor(scene, mismatch)) : t(scene.wrongKey); announce("wrong", { hint: mismatch >= 0 ? t("placementHint", { name: expected, depth: depthLabel(mismatch) }) : t(scene.wrongKey) }, "wrong"); tone(220); track("window_check", { scene: state.scene + 1, result: "wrong" }); return; } state.completed = Math.max(state.completed, state.scene + 1); announce("correct", {}, "correct"); tone(760); track("window_check", { scene: state.scene + 1, result: "correct" }); if (state.completed >= scenes.length) saveBest(); show("result"); renderResult(); };
  const idFor = (scene, index) => scene.target[index];
  const applyLocale = () => { document.documentElement.lang = state.locale; document.documentElement.dir = state.locale === "ar" ? "rtl" : "ltr"; document.querySelectorAll("[data-copy]").forEach((node) => { node.textContent = t(node.dataset.copy); }); $("localeSelect").value = state.locale; $("localeSelect").setAttribute("aria-label", t("language")); $("soundState").textContent = state.sound ? t("on") : t("off"); $("soundBtn").setAttribute("aria-pressed", String(state.sound)); $("battleSoundBtn").setAttribute("aria-label", t("sound")); $("battleSoundBtn").setAttribute("aria-pressed", String(state.sound)); $("mainProgress").textContent = `${t("groves")}: ${state.completed} / ${scenes.length}`; $("bestValue").textContent = readBest() || t("noBest"); if (state.screen === "stage") renderStages(); if (state.screen === "battle") renderBattle(); if (state.screen === "result") renderResult(); };
  const installSoundBridge = () => { if (!window.WonderSound) window.WonderSound = { isMuted: () => !state.sound, setMuted: (muted) => { state.sound = !muted; applyLocale(); track("sound", { enabled: state.sound }); window.dispatchEvent(new CustomEvent("wonder:audio-volume-change")); } }; if (typeof window.WonderSound.isMuted === "function") state.sound = !window.WonderSound.isMuted(); window.addEventListener("wonder:audio-volume-change", () => { if (typeof window.WonderSound?.isMuted === "function") { state.sound = !window.WonderSound.isMuted(); applyLocale(); } }); };
  const settingsBtn = $("settingsBtn"); const soundBtn = $("soundBtn"); const battleSoundBtn = $("battleSoundBtn"); const openStage = () => { show("stage"); renderStages(); }; $("startBtn").addEventListener("click", openStage); $("mapBtn").addEventListener("click", openStage); $("stageBackBtn").addEventListener("click", () => show("main")); $("battleBackBtn").addEventListener("click", () => { show("stage"); renderStages(); }); $("resultMapBtn").addEventListener("click", openStage); $("resultHomeBtn").addEventListener("click", () => show("main")); $("checkBtn").addEventListener("click", checkWindow); $("resetBtn").addEventListener("click", resetLayers); settingsBtn?.addEventListener("click", () => { $("settingsPanel").hidden = !$("settingsPanel").hidden; }); soundBtn?.addEventListener("click", () => { state.sound = !state.sound; applyLocale(); }); battleSoundBtn?.addEventListener("click", () => { state.sound = !state.sound; applyLocale(); }); $("localeSelect").addEventListener("change", (event) => { state.locale = locales[event.target.value] ? event.target.value : "en"; try { localStorage.setItem("weightplayLocale", state.locale); } catch (_) {} applyLocale(); });
  const initialLocale = () => { const query = new URLSearchParams(window.location.search).get("lang"); if (query && locales[query]) return query; const routeLocale = document.documentElement.lang; if (routeLocale && locales[routeLocale]) return routeLocale; try { const saved = localStorage.getItem("weightplayLocale"); if (saved && locales[saved]) return saved; } catch (_) {} return "en"; }; state.locale = initialLocale(); installSoundBridge(); applyLocale(); show("main"); window.setTimeout(() => $("loadingScreen").classList.add("is-ready"), 0); window.__ANIMAL_LAYER_GROVE_TEST__ = { scenes, startScene, moveLayer, resetLayers, checkWindow, getState: () => ({ ...state, order: [...state.order] }) };
  const placeKeeperGuide = (attempt = 0) => { const image = document.querySelector(".keeper-guide"); const copy = document.querySelector(".wp-standard-main-copy"); if (image && copy && !copy.contains(image)) copy.prepend(image); if ((!image || !copy) && attempt < 40) window.setTimeout(() => placeKeeperGuide(attempt + 1), 50); };
  placeKeeperGuide();
})();
