(() => {
  "use strict";
  const keys = ["en", "zh-Hant", "zh-Hans", "ja", "ko", "es", "pt-BR", "fr", "de", "it", "ru", "hi", "ar"];
  const base = {
    title: "Layer Grove", kicker: "A calm habitat depth puzzle", intro: "Stack three transparent habitat layers until the animal scene matches the keeper’s window.",
    back: "Back", settings: "Settings", language: "Language", sound: "Sound", on: "On", off: "Off", loading: "Preparing the grove…", start: "Start the first grove", choose: "Choose a grove", best: "Best moves", noBest: "Not yet",
    guideTitle: "How to play", guideOne: "Study the target window and the three transparent layers.", guideTwo: "Move a layer toward the front or back to rebuild the depth.", guideThree: "Check the overlap; a mismatch stays visible for a calm retry.",
    groves: "Grove scenes", map: "Grove scenes", target: "Target window", layers: "Your layers", frontToBack: "Front → back", check: "Check the window", reset: "Reset layers", waiting: "Reorder the layers, then check the window.", selected: "Layer order changed. Check the overlap when ready.", wrong: "The overlap does not match yet. {hint}", correct: "The habitat window matches. This grove is restored.",
    round: "Grove {n} of {total}", open: "Open", complete: "Restored", resultTitle: "The grove is clear", resultPartial: "Grove restored", resultText: "You restored {count} of {total} grove scenes in {moves} moves.", next: "Next grove", home: "Back to menu", moveCount: "Moves: {n}", placementHint: "Place {name} at {depth}.", moveForward: "Move {name} toward the front", moveBackward: "Move {name} toward the back",
    guideSummary: "Compare a target habitat window, then move three transparent layers into the depth order that reveals the same animal scene.", gameplayFact: "Gameplay", gameplayValue: "Depth-order puzzle", genreFact: "Genre", genreValue: "Puzzle · Logic · Family · Animal", resultGuideTitle: "Results and saves", resultGuide: "Three grove scenes form one short session. Your best total moves is stored only in this browser when storage is available.", tipsTitle: "Practical tips", tips: "Read the target as a picture, not a timed task. Front layers cover the centre; back layers frame the scene.",
    scene1: "Fern Window", scene2: "Amber Creek", scene3: "Snowy Hollow", scene1Intro: "A fern window needs the soft pond glow to sit behind its fronds.", scene2Intro: "An amber creek reveals its reeds only when the warm light frames the water.", scene3Intro: "A snowy hollow opens when the owl looks through the frost and pine layers.",
    target1: "Fern, pond, and moonlight overlap", target2: "Reeds, creek, and amber light overlap", target3: "Owl, frost, and pine overlap", wrong1: "The front layer hides the fern window’s centre.", wrong2: "The water layer is not framed by the amber light.", wrong3: "The owl is not looking through the frost window.",
    fern: "Fern layer", pond: "Pond layer", moon: "Moonlight layer", reeds: "Reeds layer", creek: "Creek layer", amber: "Amber light layer", owl: "Owl layer", frost: "Frost layer", pine: "Pine layer", front: "Front", middle: "Middle", backLayer: "Back", layerLabel: "{name}, {depth}", mapOption: "{name} habitat scene"
  };
  const variants = {
    "zh-Hant": { title: "疊影林地", kicker: "平靜的棲地深度益智", intro: "疊放三層透明棲地圖層，直到動物場景符合守護員的視窗。", back: "返回", settings: "設定", language: "語言", sound: "音效", on: "開", off: "關", loading: "準備林地中⋯", start: "開始第一座林地", choose: "選擇林地", best: "最佳步數", noBest: "尚未完成", guideTitle: "玩法", guideOne: "觀察目標視窗與三層透明圖層。", guideTwo: "把圖層往前或往後移，重建深度。", guideThree: "檢查重疊；不符時會保留畫面，讓你平靜重試。", groves: "林地場景", map: "林地場景", target: "目標視窗", layers: "你的圖層", frontToBack: "前 → 後", check: "檢查視窗", reset: "重設圖層", waiting: "重新排列圖層，再檢查視窗。", selected: "圖層順序已改變，準備好就檢查重疊。", wrong: "重疊還不符合。{hint}", correct: "棲地視窗符合了，這座林地已修復。", round: "第 {n} 座／共 {total} 座", open: "開放", complete: "已修復", resultTitle: "林地清晰了", resultPartial: "林地已修復", resultText: "你用 {moves} 步修復了 {count}／{total} 座林地場景。", next: "下一座林地", home: "返回選單", moveCount: "步數：{n}", guideSummary: "比較目標棲地視窗，再把三層透明圖層排成能顯現相同動物場景的深度順序。", gameplayFact: "玩法", gameplayValue: "深度排序益智", genreFact: "類型", genreValue: "益智・邏輯・家庭・動物", resultGuideTitle: "結果與保存", resultGuide: "三座林地組成一段短流程。最佳總步數只會在可用時保存在本機瀏覽器。", tipsTitle: "小提示", tips: "把目標當成圖片觀察，不是計時任務。前景會遮住中央，後景會框住場景。", scene1: "蕨葉視窗", scene2: "琥珀溪流", scene3: "雪地谷地", scene1Intro: "蕨葉視窗需要柔和的池水光落在葉片後方。", scene2Intro: "暖光框住水面時，琥珀溪流才會露出蘆葦。", scene3Intro: "貓頭鷹穿過霜窗與松林圖層，雪地谷地才會開啟。", target1: "蕨葉、池水與月光重疊", target2: "蘆葦、溪流與琥珀光重疊", target3: "貓頭鷹、霜晶與松林重疊", wrong1: "前景圖層遮住了蕨葉視窗中央。", wrong2: "水面還沒有被琥珀光框住。", wrong3: "貓頭鷹還沒有穿過霜晶視窗。", fern: "蕨葉圖層", pond: "池水圖層", moon: "月光圖層", reeds: "蘆葦圖層", creek: "溪流圖層", amber: "琥珀光圖層", owl: "貓頭鷹圖層", frost: "霜晶圖層", pine: "松林圖層", front: "前景", middle: "中景", backLayer: "後景", layerLabel: "{name}，{depth}" },
    "zh-Hans": { title: "叠影林地", back: "返回", settings: "设置", language: "语言", sound: "音效", on: "开", off: "关", loading: "准备林地中⋯", start: "开始第一座林地", choose: "选择林地", best: "最佳步数", guideTitle: "玩法", guideOne: "观察目标窗口与三层透明图层。", guideTwo: "把图层向前或向后移动，重建深度。", guideThree: "检查重叠；不符时保留画面，平静重试。", groves: "林地场景", target: "目标窗口", layers: "你的图层", frontToBack: "前 → 后", check: "检查窗口", reset: "重置图层", waiting: "重新排列图层，再检查窗口。", wrong: "重叠还不符合。{hint}", correct: "栖地窗口符合了，这座林地已修复。", round: "第 {n} 座／共 {total} 座", open: "开放", complete: "已修复", resultTitle: "林地清晰了", resultPartial: "林地已修复", resultText: "你用 {moves} 步修复了 {count}／{total} 座林地场景。", next: "下一座林地", home: "返回菜单", moveCount: "步数：{n}", scene1: "蕨叶窗口", scene2: "琥珀溪流", scene3: "雪谷", front: "前景", middle: "中景", backLayer: "后景", fern: "蕨叶图层", pond: "池水图层", moon: "月光图层", reeds: "芦苇图层", creek: "溪流图层", amber: "琥珀光图层", owl: "猫头鹰图层", frost: "霜晶图层", pine: "松林图层" },
    ja: { title: "レイヤーの森", back: "戻る", settings: "設定", language: "言語", sound: "音", on: "オン", off: "オフ", loading: "森を準備中…", start: "最初の森へ", choose: "森を選ぶ", best: "最少手数", guideTitle: "遊び方", guideOne: "目標の窓と3枚の透明レイヤーを見る。", guideTwo: "レイヤーを前後へ動かして奥行きを作る。", guideThree: "重なりを確認し、違えば落ち着いて試し直す。", groves: "森の景色", target: "目標の窓", layers: "レイヤー", frontToBack: "前 → 後ろ", check: "窓を確認", reset: "レイヤーを戻す", waiting: "レイヤーを並べ替えて確認しましょう。", wrong: "重なりがまだ違います。{hint}", correct: "窓の重なりが合いました。森を修復しました。", round: "森 {n}／{total}", open: "開放", complete: "修復済み", resultTitle: "森が澄みました", resultPartial: "森を修復", resultText: "{moves}手で{count}／{total}の森を修復しました。", next: "次の森", home: "メニューへ", moveCount: "手数: {n}", scene1: "シダの窓", scene2: "琥珀の小川", scene3: "雪の谷", front: "前景", middle: "中景", backLayer: "背景" },
    ko: { title: "겹침 숲", back: "뒤로", settings: "설정", language: "언어", sound: "소리", on: "켜짐", off: "꺼짐", loading: "숲 준비 중…", start: "첫 숲 시작", choose: "숲 선택", best: "최고 이동", guideTitle: "플레이 방법", guideOne: "목표 창과 투명 레이어 세 장을 살펴봐요.", guideTwo: "레이어를 앞이나 뒤로 옮겨 깊이를 만들어요.", guideThree: "겹침을 확인하고 다르면 차분히 다시 시도해요.", groves: "숲 장면", target: "목표 창", layers: "내 레이어", frontToBack: "앞 → 뒤", check: "창 확인", reset: "레이어 초기화", waiting: "레이어 순서를 바꾼 뒤 확인하세요.", wrong: "겹침이 아직 달라요. {hint}", correct: "서식지 창이 맞았어요. 숲을 복원했어요.", round: "숲 {n} / {total}", open: "열림", complete: "복원됨", resultTitle: "숲이 맑아졌어요", resultPartial: "숲 복원", resultText: "{moves}번 이동으로 숲 {count}/{total}곳을 복원했어요.", next: "다음 숲", home: "메뉴로", moveCount: "이동: {n}", front: "앞", middle: "중간", backLayer: "뒤" },
    es: { title: "Bosque de Capas", back: "Volver", settings: "Ajustes", language: "Idioma", sound: "Sonido", on: "Sí", off: "No", loading: "Preparando el bosque…", start: "Empezar el primer bosque", choose: "Elegir un bosque", best: "Mejores movimientos", guideTitle: "Cómo jugar", guideOne: "Observa la ventana objetivo y las tres capas transparentes.", guideTwo: "Mueve una capa delante o detrás para reconstruir la profundidad.", guideThree: "Comprueba el solapamiento y reintenta con calma si no coincide.", groves: "Escenas del bosque", target: "Ventana objetivo", layers: "Tus capas", frontToBack: "Delante → detrás", check: "Comprobar ventana", reset: "Reiniciar capas", waiting: "Ordena las capas y comprueba la ventana.", wrong: "El solapamiento aún no coincide. {hint}", correct: "La ventana del hábitat coincide. Has restaurado este bosque.", round: "Bosque {n} de {total}", open: "Abierto", complete: "Restaurado", resultTitle: "El bosque está claro", resultPartial: "Bosque restaurado", resultText: "Restauraste {count} de {total} escenas en {moves} movimientos.", next: "Siguiente bosque", home: "Volver al menú", moveCount: "Movimientos: {n}", front: "Delante", middle: "Medio", backLayer: "Detrás" },
    "pt-BR": { title: "Bosque de Camadas", back: "Voltar", settings: "Configurações", language: "Idioma", sound: "Som", on: "Ligado", off: "Desligado", loading: "Preparando a floresta…", start: "Começar a primeira floresta", choose: "Escolher uma floresta", best: "Melhores movimentos", guideTitle: "Como jogar", guideOne: "Observe a janela-alvo e as três camadas transparentes.", guideTwo: "Mova uma camada para frente ou para trás para refazer a profundidade.", guideThree: "Confira a sobreposição e tente novamente com calma se não combinar.", groves: "Cenas da floresta", target: "Janela-alvo", layers: "Suas camadas", frontToBack: "Frente → trás", check: "Conferir janela", reset: "Redefinir camadas", waiting: "Reordene as camadas e confira a janela.", wrong: "A sobreposição ainda não combina. {hint}", correct: "A janela do habitat combina. Você restaurou esta floresta.", round: "Floresta {n} de {total}", open: "Aberta", complete: "Restaurada", resultTitle: "A floresta está clara", resultPartial: "Floresta restaurada", resultText: "Você restaurou {count} de {total} cenas em {moves} movimentos.", next: "Próxima floresta", home: "Voltar ao menu", moveCount: "Movimentos: {n}", front: "Frente", middle: "Meio", backLayer: "Trás" },
    fr: { title: "Bois en couches", back: "Retour", settings: "Réglages", language: "Langue", sound: "Son", on: "Activé", off: "Désactivé", loading: "Préparation du bois…", start: "Commencer le premier bois", choose: "Choisir un bois", best: "Meilleurs mouvements", guideTitle: "Comment jouer", guideOne: "Observe la fenêtre cible et les trois couches transparentes.", guideTwo: "Déplace une couche devant ou derrière pour recréer la profondeur.", guideThree: "Vérifie le chevauchement et réessaie calmement s’il diffère.", groves: "Scènes du bois", target: "Fenêtre cible", layers: "Tes couches", frontToBack: "Avant → arrière", check: "Vérifier la fenêtre", reset: "Réinitialiser les couches", waiting: "Réorganise les couches, puis vérifie la fenêtre.", wrong: "Le chevauchement ne correspond pas encore. {hint}", correct: "La fenêtre de l’habitat correspond. Ce bois est restauré.", round: "Bois {n} sur {total}", open: "Ouvert", complete: "Restauré", resultTitle: "Le bois est clair", resultPartial: "Bois restauré", resultText: "Tu as restauré {count} scènes sur {total} en {moves} mouvements.", next: "Bois suivant", home: "Retour au menu", moveCount: "Mouvements : {n}", front: "Avant", middle: "Milieu", backLayer: "Arrière" },
    de: { title: "Schichtenhain", back: "Zurück", settings: "Einstellungen", language: "Sprache", sound: "Ton", on: "An", off: "Aus", loading: "Hain wird vorbereitet…", start: "Ersten Hain starten", choose: "Hain wählen", best: "Beste Züge", guideTitle: "So wird gespielt", guideOne: "Betrachte das Zielfenster und die drei transparenten Schichten.", guideTwo: "Bewege eine Schicht nach vorn oder hinten, um die Tiefe aufzubauen.", guideThree: "Prüfe die Überlagerung und versuche es ruhig erneut, wenn sie nicht passt.", groves: "Hainszenen", target: "Zielfenster", layers: "Deine Schichten", frontToBack: "Vorn → hinten", check: "Fenster prüfen", reset: "Schichten zurücksetzen", waiting: "Ordne die Schichten und prüfe dann das Fenster.", wrong: "Die Überlagerung passt noch nicht. {hint}", correct: "Das Habitatfenster passt. Dieser Hain ist wiederhergestellt.", round: "Hain {n} von {total}", open: "Offen", complete: "Wiederhergestellt", resultTitle: "Der Hain ist klar", resultPartial: "Hain wiederhergestellt", resultText: "Du hast {count} von {total} Szenen mit {moves} Zügen wiederhergestellt.", next: "Nächster Hain", home: "Zum Menü", moveCount: "Züge: {n}", front: "Vorn", middle: "Mitte", backLayer: "Hinten" },
    it: { title: "Bosco a strati", back: "Indietro", settings: "Impostazioni", language: "Lingua", sound: "Suono", on: "Attivo", off: "Disattivo", loading: "Preparo il bosco…", start: "Inizia il primo bosco", choose: "Scegli un bosco", best: "Mosse migliori", guideTitle: "Come si gioca", guideOne: "Osserva la finestra-obiettivo e i tre strati trasparenti.", guideTwo: "Sposta uno strato davanti o dietro per ricreare la profondità.", guideThree: "Controlla la sovrapposizione e riprova con calma se non coincide.", groves: "Scene del bosco", target: "Finestra-obiettivo", layers: "I tuoi strati", frontToBack: "Davanti → dietro", check: "Controlla la finestra", reset: "Reimposta gli strati", waiting: "Riordina gli strati, poi controlla la finestra.", wrong: "La sovrapposizione non coincide ancora. {hint}", correct: "La finestra dell’habitat coincide. Hai restaurato questo bosco.", round: "Bosco {n} di {total}", open: "Aperto", complete: "Restaurato", resultTitle: "Il bosco è limpido", resultPartial: "Bosco restaurato", resultText: "Hai restaurato {count} scene su {total} in {moves} mosse.", next: "Bosco successivo", home: "Torna al menu", moveCount: "Mosse: {n}", front: "Davanti", middle: "Centro", backLayer: "Dietro" },
    ru: { title: "Роща слоёв", back: "Назад", settings: "Настройки", language: "Язык", sound: "Звук", on: "Вкл.", off: "Выкл.", loading: "Готовим рощу…", start: "Начать первую рощу", choose: "Выбрать рощу", best: "Лучшие ходы", guideTitle: "Как играть", guideOne: "Рассмотрите целевое окно и три прозрачных слоя.", guideTwo: "Переместите слой вперёд или назад, чтобы восстановить глубину.", guideThree: "Проверьте наложение и спокойно попробуйте снова, если оно не совпало.", groves: "Сцены рощи", target: "Целевое окно", layers: "Ваши слои", frontToBack: "Вперёд → назад", check: "Проверить окно", reset: "Сбросить слои", waiting: "Переставьте слои и проверьте окно.", wrong: "Наложение пока не совпадает. {hint}", correct: "Окно среды совпало. Роща восстановлена.", round: "Роща {n} из {total}", open: "Открыта", complete: "Восстановлена", resultTitle: "Роща прояснилась", resultPartial: "Роща восстановлена", resultText: "Восстановлено сцен: {count} из {total}, ходов: {moves}.", next: "Следующая роща", home: "В меню", moveCount: "Ходы: {n}", front: "Впереди", middle: "В середине", backLayer: "Сзади" },
    hi: { title: "परतों का वन", back: "वापस", settings: "सेटिंग्स", language: "भाषा", sound: "ध्वनि", on: "चालू", off: "बंद", loading: "वन तैयार हो रहा है…", start: "पहला वन शुरू करें", choose: "वन चुनें", best: "सर्वश्रेष्ठ चालें", guideTitle: "कैसे खेलें", guideOne: "लक्ष्य खिड़की और तीन पारदर्शी परतों को देखें।", guideTwo: "गहराई बनाने के लिए परत को आगे या पीछे ले जाएँ।", guideThree: "ओवरलैप जाँचें; न मिले तो शांति से फिर कोशिश करें।", groves: "वन दृश्य", target: "लक्ष्य खिड़की", layers: "आपकी परतें", frontToBack: "आगे → पीछे", check: "खिड़की जाँचें", reset: "परतें रीसेट करें", waiting: "परतों का क्रम बदलकर खिड़की जाँचें।", wrong: "ओवरलैप अभी नहीं मिला। {hint}", correct: "आवास की खिड़की मिल गई। वन बहाल है।", round: "वन {n} / {total}", open: "खुला", complete: "बहाल", resultTitle: "वन साफ़ है", resultPartial: "वन बहाल", resultText: "{moves} चालों में {total} में से {count} दृश्य बहाल किए।", next: "अगला वन", home: "मेनू पर", moveCount: "चालें: {n}", front: "आगे", middle: "बीच", backLayer: "पीछे" },
    ar: { title: "بستان الطبقات", back: "عودة", settings: "الإعدادات", language: "اللغة", sound: "الصوت", on: "تشغيل", off: "إيقاف", loading: "نحضّر البستان…", start: "ابدأ البستان الأول", choose: "اختر بستاناً", best: "أفضل الحركات", guideTitle: "طريقة اللعب", guideOne: "تأمل نافذة الهدف والطبقات الشفافة الثلاث.", guideTwo: "حرّك طبقة إلى الأمام أو الخلف لبناء العمق.", guideThree: "افحص التداخل؛ وإن لم يطابق، حاول بهدوء من جديد.", groves: "مشاهد البستان", target: "نافذة الهدف", layers: "طبقاتك", frontToBack: "الأمام ← الخلف", check: "تحقق من النافذة", reset: "إعادة الطبقات", waiting: "أعد ترتيب الطبقات ثم تحقق من النافذة.", wrong: "لم يطابق التداخل بعد. {hint}", correct: "تطابقت نافذة الموطن. أُصلح هذا البستان.", round: "البستان {n} من {total}", open: "مفتوح", complete: "تم الإصلاح", resultTitle: "صار البستان صافياً", resultPartial: "أُصلح البستان", resultText: "أصلحت {count} من {total} مشاهد في {moves} حركات.", next: "البستان التالي", home: "العودة للقائمة", moveCount: "الحركات: {n}", front: "الأمام", middle: "الوسط", backLayer: "الخلف", kicker: "لغز هادئ لعمق الموطن", intro: "رتّب ثلاث طبقات شفافة من الموطن حتى يطابق مشهد الحيوان نافذة الحارس.", noBest: "لم تُنجز بعد", map: "مشاهد البستان", selected: "تغيّر ترتيب الطبقات. افحص التداخل عندما تكون مستعداً.", placementHint: "ضع {name} في {depth}.", moveForward: "حرّك {name} نحو الأمام", moveBackward: "حرّك {name} نحو الخلف", guideSummary: "قارن نافذة الموطن المستهدفة، ثم حرّك ثلاث طبقات شفافة إلى ترتيب العمق الذي يُظهر المشهد الحيواني نفسه.", gameplayFact: "طريقة اللعب", gameplayValue: "لغز ترتيب العمق", genreFact: "النوع", genreValue: "ألغاز · منطق · عائلي · حيوانات", resultGuideTitle: "النتائج والحفظ", resultGuide: "تشكّل ثلاثة مشاهد من البستان جلسة قصيرة. تُحفظ أفضل نتيجة للحركات في هذا المتصفح فقط عند توفر التخزين.", tipsTitle: "نصائح عملية", tips: "اقرأ الهدف كصورة لا كمهمة مؤقتة. الطبقات الأمامية تغطي المركز؛ والطبقات الخلفية تؤطر المشهد.", scene1: "نافذة السرخس", scene2: "الجدول الكهرماني", scene3: "الوادي الثلجي", scene1Intro: "تحتاج نافذة السرخس إلى وهج البركة الناعم خلف أوراقها.", scene2Intro: "يكشف الجدول الكهرماني عن قصبه حين يؤطر الضوء الدافئ الماء.", scene3Intro: "ينفتح وادٍ ثلجي حين تنظر البومة عبر طبقتي الصقيع والصنوبر.", target1: "تداخل السرخس والبركة وضوء القمر", target2: "تداخل القصب والجدول والضوء الكهرماني", target3: "تداخل البومة والصقيع والصنوبر", wrong1: "تحجب الطبقة الأمامية مركز نافذة السرخس.", wrong2: "لم تُؤطّر طبقة الماء بالضوء الكهرماني.", wrong3: "لم تنظر البومة عبر نافذة الصقيع.", fern: "طبقة السرخس", pond: "طبقة البركة", moon: "طبقة ضوء القمر", reeds: "طبقة القصب", creek: "طبقة الجدول", amber: "طبقة الضوء الكهرماني", owl: "طبقة البومة", frost: "طبقة الصقيع", pine: "طبقة الصنوبر", layerLabel: "{name}، {depth}", mapOption: "مشهد موطن {name}" }
  };
  Object.assign(base, {
    intro: "Restore 30 habitat stages across six arcs. Stack layers to match the keeper’s window.",
    guideOne: "Study the target window and the layers for the current stage.",
    guideTwo: "Move a layer toward the front or back, then follow each arc’s special rule.",
    guideThree: "Check the overlap; wrong orders stay visible so you can learn and retry.",
    start: "Start the campaign", choose: "Choose a stage", next: "Next stage", groves: "Grove stages", map: "Grove stages", round: "Stage {n} of {total}", open: "Open", locked: "Locked", complete: "Restored",
    resultText: "You restored {count} of {total} grove stages in {moves} moves.",
    guideSummary: "Compare the target habitat window, then rebuild thirty authored scenes across six arcs with changing layer sets, decoys, wind reading, and echo layers.",
    resultGuide: "Thirty stages form six five-stage arcs. Progress unlocks the next stage, cleared stages remain replayable, and completed progress plus your best total moves are stored only in this browser when storage is available.",
    tips: "Read the target as a picture, not a timed task. Check the arc rule before moving, use Reset when a trial gets tangled, and replay any restored stage to refine your route.",
    farBack: "Far back", mechanicStack: "Rule: match the front-to-back order exactly.", mechanicDecoy: "Rule: keep the marked moth decoy behind every target layer.", mechanicWind: "Rule: this gust reads the target from back to front.", mechanicEcho: "Rule: place the echo layer in its shown position; every layer matters.",
    fern: "Fern layer", pond: "Pond layer", moon: "Moonlight layer", moss: "Moss layer", glow: "Grove glow layer", root: "Root layer", willow: "Willow layer", brook: "Brook layer", mist: "Mist layer", leaf: "Leaf layer", rain: "Rain layer", sun: "Sun layer", bloom: "Bloom layer", canopy: "Canopy layer", beacon: "Beacon layer", reeds: "Reeds layer", creek: "Creek layer", amber: "Amber light layer", reed: "Single reed layer", stone: "Stone layer", stream: "Stream layer", pebble: "Pebble layer", wind: "Wind layer", pine: "Pine layer", fog: "Fog layer", fox: "Fox layer", wing: "Wing layer", meadow: "Meadow layer", whistle: "Whistle layer", storm: "Storm layer", glass: "Glass layer", ridge: "Ridge layer", owl: "Owl layer", frost: "Frost layer", echo: "Echo layer", snow: "Snow layer", bell: "Bell layer", hollow: "Hollow layer", night: "Night layer", star: "Star layer", shell: "Shell layer", coral: "Coral layer", kelp: "Kelp layer", tide: "Tide layer", sand: "Sand layer", water: "Water layer", acorn: "Acorn layer", burrow: "Burrow layer", keeper: "Keeper layer", moth: "Moth decoy layer"
  });
  Object.assign(variants["zh-Hant"], {
    intro: "穿越六個篇章、三十個精心設計的關卡，修復有生命的棲地。疊放透明圖層，直到每個動物場景符合守護員的視窗。",
    guideOne: "觀察目標視窗與目前關卡的圖層。", guideTwo: "把圖層往前或往後移，再遵守每個篇章的特殊規則。", guideThree: "檢查重疊；錯誤順序會保留，讓你理解後重試。",
    start: "開始篇章", choose: "選擇關卡", next: "下一關", groves: "林地關卡", map: "林地關卡", round: "第 {n} 關／共 {total} 關", open: "開放", locked: "未解鎖", complete: "已修復", resultText: "你用 {moves} 步修復了 {count}／{total} 個林地關卡。",
    guideSummary: "比較目標棲地視窗，再跨越六個篇章重建三十個精心設計的場景；圖層組合會加入誘餌、風向讀法與回聲圖層。",
    resultGuide: "三十個關卡組成六個五關篇章。進度會解鎖下一關，已修復的關卡可以重玩；完成進度與最佳總步數只會在可用時保存在本機瀏覽器。",
    tips: "把目標當成圖片觀察，不是計時任務。移動前先看篇章規則；卡住時使用重設，也可以重玩已修復的關卡來改善路線。",
    farBack: "最深處", mechanicStack: "規則：完全符合由前到後的順序。", mechanicDecoy: "規則：把標記的飛蛾誘餌放在所有目標圖層後方。", mechanicWind: "規則：這股風要求你由後往前讀取目標。", mechanicEcho: "規則：把回聲圖層放在顯示的位置；每一層都重要。",
    fern: "蕨葉圖層", pond: "池水圖層", moon: "月光圖層", moss: "苔蘚圖層", glow: "林地光芒圖層", root: "樹根圖層", willow: "柳樹圖層", brook: "小溪圖層", mist: "薄霧圖層", leaf: "葉片圖層", rain: "雨水圖層", sun: "陽光圖層", bloom: "花朵圖層", canopy: "樹冠圖層", beacon: "燈塔圖層", reeds: "蘆葦圖層", creek: "溪流圖層", amber: "琥珀光圖層", reed: "單枝蘆葦圖層", stone: "石頭圖層", stream: "水流圖層", pebble: "卵石圖層", wind: "風圖層", pine: "松林圖層", fog: "霧氣圖層", fox: "狐狸圖層", wing: "翅膀圖層", meadow: "草地圖層", whistle: "口哨圖層", storm: "風暴圖層", glass: "玻璃圖層", ridge: "山脊圖層", owl: "貓頭鷹圖層", frost: "霜晶圖層", echo: "回聲圖層", snow: "雪地圖層", bell: "鈴鐺圖層", hollow: "空谷圖層", night: "夜色圖層", star: "星光圖層", shell: "貝殼圖層", coral: "珊瑚圖層", kelp: "海帶圖層", tide: "潮汐圖層", sand: "沙地圖層", water: "水面圖層", acorn: "橡實圖層", burrow: "洞穴圖層", keeper: "守護員圖層", moth: "飛蛾誘餌圖層"
  });
  Object.assign(variants["zh-Hant"], {
    placementHint: "請將{name}放在{depth}。",
    moveForward: "將{name}移向前景",
    moveBackward: "將{name}移向後景"
  });
  const stageCopy = [
    ["Fern Window", "A fern window needs the soft pond glow behind its fronds.", "Fern, pond, and moonlight overlap.", "The fern window is still hidden by the wrong depth."],
    ["Moss Lantern", "A moss lantern warms when its root holds the lowest edge.", "Moss, glow, and root overlap.", "The root is not holding the lowest edge yet."],
    ["Willow Pocket", "A willow pocket opens when the brook slips through the mist.", "Willow, brook, and mist overlap.", "The brook and mist are crossing in the wrong depth."],
    ["Rainfall Canopy", "Rain catches the sun below the leaf canopy.", "Leaf, rain, and sun overlap.", "The rain is not sitting below the leaf."],
    ["Sunlit Canopy", "A small bloom needs the canopy to frame its beacon.", "Bloom, canopy, and beacon overlap.", "The beacon is not framed by the canopy."],
    ["Amber Creek", "Amber light reveals reeds beside a quiet creek; leave the moth outside.", "Reeds, creek, and amber light overlap.", "The amber creek is tangled, or the moth is not behind it."],
    ["Reed Crossing", "A single reed crosses the stream while the stone anchors the view.", "Reed, stone, and stream overlap.", "The moth must stay behind the reed crossing."],
    ["Pebble Bend", "The pebble bend glints through the brook; ignore the moth’s false glimmer.", "Pebble, brook, and grove glow overlap.", "The moth is a decoy; keep it at the far back."],
    ["Misty Ford", "At the misty ford, the stone steadies the creek and the moth stays out of sight.", "Mist, stone, and creek overlap.", "The ford needs its three layers first and the moth last."],
    ["Heron Weir", "Reeds rise in sunlight beside a willow weir; the moth never belongs in the window.", "Reeds, sun, and willow overlap.", "The moth is still in the visible habitat stack."],
    ["Windcut Hollow", "A gust cuts the hollow between pine and fog.", "Wind, pine, and fog overlap.", "The gust asks you to read this target from back to front."],
    ["Foxglove Gale", "A fox watches through a leaf while the gale turns the reading order.", "Fox, leaf, and wind overlap.", "Follow the wind rule and read the target from back to front."],
    ["Kite Meadow", "A wing glides over the meadow and catches a low sun.", "Wing, meadow, and sun overlap.", "The kite meadow is still reversed by the gust."],
    ["Whistling Pine", "A whistle threads the pine and mist when the wind is read correctly.", "Whistle, pine, and mist overlap.", "The whistling pine follows the back-to-front wind reading."],
    ["Stormglass Ridge", "Storm light crosses glass before it reaches the ridge.", "Storm, glass, and ridge overlap.", "The ridge is not in the wind’s far-to-near reading yet."],
    ["Owl Echo", "The owl’s call returns through frost, pine, and one clear echo.", "Owl, frost, pine, and echo overlap.", "Every layer matters, including the echo in the middle."],
    ["Frost Echo", "Snow light rests on a moonlit frost echo above the pine.", "Snow, moon, echo, and pine overlap.", "The echo is not in its shown position."],
    ["Bellflower Echo", "A bellflower rings softly through moss and its returning echo.", "Bell, bloom, echo, and moss overlap.", "The bellflower’s echo must keep its place."],
    ["Hollow Echo", "A hollow stone sends one echo through the fog.", "Hollow, stone, echo, and fog overlap.", "The hollow needs the echo between stone and fog."],
    ["Night Echo", "An owl crosses the night sky, leaving one echo below the star.", "Night, star, echo, and owl overlap.", "The night scene needs its echo in the middle."],
    ["Tidepool Shell", "A shell settles over coral, kelp, and the turning tide.", "Shell, coral, kelp, and tide overlap.", "The tidepool layers are not in their keeper order."],
    ["Coral Shelf", "Coral shades the sand while the tide carries a moth-shaped false glint away.", "Coral, sand, and tide overlap.", "Keep the moth decoy behind the coral shelf."],
    ["Kelp Garden", "Kelp frames a shell and stream as the tide moves below.", "Kelp, shell, stream, and tide overlap.", "The kelp garden needs all four layers aligned."],
    ["Sandbar Moon", "Moonlight falls over a sandbar, tide, and a returning echo.", "Sand, moon, tide, and echo overlap.", "The sandbar echo is not in its shown position."],
    ["Starwater Pool", "Stars shimmer over water, tide, and a shell at the quiet edge.", "Star, water, tide, and shell overlap.", "The starwater layers still need a clean front-to-back order."],
    ["Rootbound Gate", "An acorn rests by the root while fog turns the final forest gate.", "Root, acorn, and fog overlap.", "The final arc begins with a back-to-front wind reading."],
    ["Blooming Burrow", "A bloom marks the burrow while a leaf carries its small echo.", "Bloom, burrow, leaf, and echo overlap.", "The burrow scene needs every layer, including the echo."],
    ["Fogbound Crossing", "Wind crosses the stone in a fogbound crossing; a moth is only a decoy.", "Fog, stone, and wind overlap.", "Place the moth far back and follow the crossing rule."],
    ["Beacon Hollow", "A beacon guides the night owl through pine and its echo.", "Beacon, night, pine, and echo overlap.", "The beacon hollow is not aligned around its echo."],
    ["Keeper’s Window", "The keeper’s window brings fern, moon, and echo together as the grove’s final seal.", "Keeper, fern, moon, and echo overlap.", "The final seal needs all four layers in the shown order."]
  ];
  const zhStageCopy = [
    ["蕨葉視窗", "蕨葉視窗需要柔和的池水光落在葉片後方。", "蕨葉、池水與月光重疊。", "蕨葉視窗仍被錯誤的深度遮住。"], ["苔蘚燈", "樹根守住最低邊緣時，苔蘚燈才會溫暖。", "苔蘚、光芒與樹根重疊。", "樹根還沒有守住最低邊緣。"], ["柳樹口袋", "小溪穿過薄霧時，柳樹口袋才會開啟。", "柳樹、小溪與薄霧重疊。", "小溪與薄霧的深度交錯了。"], ["雨幕樹冠", "雨水接住樹冠下方的陽光。", "葉片、雨水與陽光重疊。", "雨水還沒有放在葉片下方。"], ["日光樹冠", "小花需要樹冠替燈塔框出位置。", "花朵、樹冠與燈塔重疊。", "燈塔還沒有被樹冠框住。"], ["琥珀溪流", "琥珀光照亮溪旁蘆葦；把飛蛾留在外面。", "蘆葦、溪流與琥珀光重疊。", "琥珀溪流還沒整理好，或飛蛾尚未放到後方。"], ["蘆葦渡口", "單枝蘆葦越過水流，石頭固定住畫面。", "蘆葦、石頭與水流重疊。", "飛蛾必須留在蘆葦渡口後方。"], ["卵石彎", "卵石彎透過小溪閃耀；別被飛蛾的假光誤導。", "卵石、小溪與林地光芒重疊。", "飛蛾是誘餌，請把它放在最深處。"], ["薄霧渡口", "在薄霧渡口，石頭穩住溪流，飛蛾留在視線外。", "薄霧、石頭與溪流重疊。", "渡口需要先排好三層，再把飛蛾放到最後。"], ["蒼鷺堰", "陽光旁的蘆葦升起在柳樹堰邊；飛蛾不屬於視窗。", "蘆葦、陽光與柳樹重疊。", "飛蛾仍在看得見的棲地堆疊裡。"], ["風切空谷", "一陣風切過松林與霧氣之間的空谷。", "風、松林與霧氣重疊。", "這股風要求你由後往前讀取目標。"], ["狐狸狂風", "狐狸透過葉片觀察，狂風改變了讀取順序。", "狐狸、葉片與風重疊。", "遵守風的規則，由後往前讀取目標。"], ["風箏草地", "翅膀滑過草地，接住低低的陽光。", "翅膀、草地與陽光重疊。", "風箏草地仍被狂風反轉了。"], ["呼嘯松林", "口哨正確穿過松林與薄霧時，聲音才會抵達。", "口哨、松林與薄霧重疊。", "呼嘯松林要依風的由後往前讀法排列。"], ["風暴玻璃山脊", "風暴光線穿過玻璃，才抵達山脊。", "風暴、玻璃與山脊重疊。", "山脊還不在風的由遠到近讀法中。"], ["貓頭鷹回聲", "貓頭鷹的叫聲穿過霜晶、松林，留下清楚的回聲。", "貓頭鷹、霜晶、松林與回聲重疊。", "每一層都重要，包括中間的回聲。"], ["霜晶回聲", "雪光停在月光霜晶的回聲上方，松林守在最下方。", "雪地、月光、回聲與松林重疊。", "回聲還沒有放在顯示的位置。"], ["鈴花回聲", "鈴花穿過苔蘚，讓回聲輕輕返回。", "鈴鐺、花朵、回聲與苔蘚重疊。", "鈴花的回聲必須留在正確位置。"], ["空谷回聲", "空谷石頭讓一道回聲穿過霧氣。", "空谷、石頭、回聲與霧氣重疊。", "空谷需要把回聲放在石頭與霧氣之間。"], ["夜色回聲", "貓頭鷹穿越夜空，在星光下方留下回聲。", "夜色、星光、回聲與貓頭鷹重疊。", "夜色場景需要把回聲放在中間。"], ["潮池貝殼", "貝殼停在珊瑚、海帶與轉動潮汐之上。", "貝殼、珊瑚、海帶與潮汐重疊。", "潮池圖層還沒有排成守護員的順序。"], ["珊瑚沙棚", "珊瑚替沙地遮蔭，潮汐帶走飛蛾形狀的假光。", "珊瑚、沙地與潮汐重疊。", "把飛蛾誘餌留在珊瑚沙棚後方。"], ["海帶花園", "海帶框住貝殼與水流，潮汐在下方移動。", "海帶、貝殼、水流與潮汐重疊。", "海帶花園需要對齊全部四層。"], ["月光沙洲", "月光落在沙洲、潮汐與回聲上。", "沙地、月光、潮汐與回聲重疊。", "沙洲的回聲還沒有放在顯示的位置。"], ["星水池", "星光在水面、潮汐與安靜邊緣的貝殼上閃耀。", "星光、水面、潮汐與貝殼重疊。", "星水圖層仍需要乾淨的前後順序。"], ["樹根之門", "橡實靠著樹根，霧氣轉動最後的森林之門。", "樹根、橡實與霧氣重疊。", "最後篇章從由後往前的風之讀法開始。"], ["花開洞穴", "花朵標記洞穴，葉片帶著小小的回聲。", "花朵、洞穴、葉片與回聲重疊。", "洞穴場景需要每一層，包括回聲。"], ["霧中通道", "風穿過霧中的石頭；飛蛾只是誘餌。", "霧氣、石頭與風重疊。", "把飛蛾放到最深處，再遵守通道規則。"], ["燈塔空谷", "燈塔引導夜色中的貓頭鷹穿過松林與回聲。", "燈塔、夜色、松林與回聲重疊。", "燈塔空谷還沒有圍繞回聲對齊。"], ["守護員視窗", "守護員視窗把蕨葉、月光與回聲聚在一起，封住林地最後的印記。", "守護員、蕨葉、月光與回聲重疊。", "最後的印記需要四層都按顯示順序排列。"]
  ];
  const arStageCopy = [
    ["نافذة السرخس", "تحتاج نافذة السرخس إلى وهج البركة خلف أوراقها.", "تتداخل السرخس والبركة وضوء القمر.", "ما زال العمق الخاطئ يحجب نافذة السرخس."],
    ["فانوس الطحلب", "يدفئ فانوس الطحلب حين تمسك الجذور بالحافة السفلى.", "تتداخل الطحالب والوهج والجذور.", "لم تمسك الجذور الحافة السفلى بعد."],
    ["جيب الصفصاف", "ينفتح جيب الصفصاف حين يمر الجدول بين الضباب.", "يتداخل الصفصاف والجدول والضباب.", "يتقاطع الجدول والضباب في عمق خاطئ."],
    ["مظلة المطر", "يلتقط المطر الشمس تحت مظلة الأوراق.", "تتداخل الأوراق والمطر والشمس.", "لم يستقر المطر تحت الأوراق."],
    ["مظلة مضيئة", "تحتاج الزهرة الصغيرة إلى المظلة حول منارتها.", "تتداخل الزهرة والمظلة والمنارة.", "لم تؤطر المظلة المنارة بعد."],
    ["الجدول الكهرماني", "يكشف الضوء الكهرماني القصب قرب الجدول؛ اترك العثة خارجه.", "يتداخل القصب والجدول والضوء الكهرماني.", "الجدول غير مرتب أو العثة ليست في الخلف."],
    ["عبور القصب", "يعبر قصب واحد الماء بينما تثبت الصخرة المشهد.", "يتداخل القصب والصخرة والمجرى.", "يجب أن تبقى العثة خلف عبور القصب."],
    ["منعطف الحصى", "يلمع منعطف الحصى عبر الجدول؛ تجاهل بريق العثة الزائف.", "يتداخل الحصى والجدول ووهج البستان.", "العثة طُعم؛ ضعها في أقصى الخلف."],
    ["المعبر الضبابي", "تثبت الصخرة الجدول عند المعبر الضبابي وتبقى العثة بعيدة.", "يتداخل الضباب والصخرة والجدول.", "رتب الطبقات الثلاث ثم ضع العثة أخيراً."],
    ["حاجز مالك الحزين", "يرتفع القصب في الشمس قرب حاجز الصفصاف؛ لا تنتمي العثة للنافذة.", "يتداخل القصب والشمس والصفصاف.", "ما زالت العثة داخل مكدس الموطن المرئي."],
    ["جوف الريح", "تشق هبة جوفاً بين الصنوبر والضباب.", "تتداخل الريح والصنوبر والضباب.", "اقرأ الهدف من الخلف إلى الأمام وفق قاعدة الريح."],
    ["عاصفة قفاز الثعلب", "يراقب الثعلب عبر ورقة بينما تغيّر العاصفة ترتيب القراءة.", "يتداخل الثعلب والورقة والريح.", "اتبع قاعدة الريح واقرأ الهدف من الخلف إلى الأمام."],
    ["مرج الطائرة الورقية", "ينساب الجناح فوق المرج ويلتقط شمساً منخفضة.", "يتداخل الجناح والمرج والشمس.", "ما زالت العاصفة تعكس ترتيب المرج."],
    ["الصنوبر الصافر", "يمر الصفير بين الصنوبر والضباب حين تُقرأ الريح جيداً.", "يتداخل الصفير والصنوبر والضباب.", "رتب الصنوبر بقراءة الريح من الخلف إلى الأمام."],
    ["حافة زجاج العاصفة", "يعبر ضوء العاصفة الزجاج قبل أن يصل إلى الحافة.", "تتداخل العاصفة والزجاج والحافة.", "لم تصل الحافة إلى قراءة الريح الصحيحة."],
    ["صدى البومة", "يعود نداء البومة عبر الصقيع والصنوبر وصدى واضح.", "تتداخل البومة والصقيع والصنوبر والصدى.", "كل طبقة مهمة، ومنها الصدى في الوسط."],
    ["صدى الصقيع", "يستقر ضوء الثلج فوق صدى الصقيع والصنوبر تحته.", "يتداخل الثلج والقمر والصدى والصنوبر.", "لم يوضع الصدى في موضعه الظاهر."],
    ["صدى زهرة الجرس", "ترن زهرة الجرس بهدوء عبر الطحلب وصداها العائد.", "يتداخل الجرس والزهرة والصدى والطحلب.", "يجب أن يحافظ صدى الزهرة على موضعه."],
    ["صدى الجوف", "ترسل صخرة الجوف صدى واحداً عبر الضباب.", "يتداخل الجوف والصخرة والصدى والضباب.", "ضع الصدى بين الصخرة والضباب."],
    ["صدى الليل", "تعبر البومة سماء الليل وتترك صدى تحت النجمة.", "يتداخل الليل والنجمة والصدى والبومة.", "يحتاج مشهد الليل إلى الصدى في الوسط."],
    ["صدفة بركة المد", "تستقر الصدفة فوق المرجان وعشب البحر والمد المتحول.", "تتداخل الصدفة والمرجان وعشب البحر والمد.", "لم ترتب طبقات بركة المد بترتيب الحارس."],
    ["رف المرجان", "يظلل المرجان الرمل بينما يحمل المد بريقاً زائفاً بعيداً.", "يتداخل المرجان والرمل والمد.", "أبق طُعم العثة خلف رف المرجان."],
    ["حديقة عشب البحر", "يؤطر عشب البحر الصدفة والمجرى بينما يتحرك المد أسفلها.", "يتداخل عشب البحر والصدفة والمجرى والمد.", "تحتاج الحديقة إلى محاذاة الطبقات الأربع."],
    ["قمر الشريط الرملي", "يسقط ضوء القمر فوق الرمل والمد والصدى العائد.", "يتداخل الرمل والقمر والمد والصدى.", "صدى الشريط الرملي ليس في موضعه الظاهر."],
    ["بركة ماء النجوم", "تلمع النجوم فوق الماء والمد وصدفة عند الحافة الهادئة.", "يتداخل النجم والماء والمد والصدفة.", "تحتاج طبقات الماء النجمي إلى ترتيب أمامي نظيف."],
    ["بوابة الجذر", "تستقر ثمرة البلوط قرب الجذر بينما يقلب الضباب بوابة الغابة الأخيرة.", "يتداخل الجذر والبلوط والضباب.", "يبدأ الفصل الأخير بقراءة الريح من الخلف إلى الأمام."],
    ["جحر مزهر", "تعلّم زهرة الجحر بينما تحمل ورقة صداها الصغير.", "تتداخل الزهرة والجحر والورقة والصدى.", "يحتاج مشهد الجحر كل الطبقات، ومنها الصدى."],
    ["المعبر الضبابي العابر", "تعبر الريح الصخرة في ممر ضبابي؛ العثة مجرد طُعم.", "يتداخل الضباب والصخرة والريح.", "ضع العثة في أقصى الخلف واتبع قاعدة العبور."],
    ["جوف المنارة", "ترشد المنارة بومة الليل عبر الصنوبر وصداها.", "تتداخل المنارة والليل والصنوبر والصدى.", "لم يصطف جوف المنارة حول صداه."],
    ["نافذة الحارس", "تجمع نافذة الحارس السرخس والقمر والصدى لتختم البستان.", "يتداخل الحارس والسرخس والقمر والصدى.", "يحتاج الختم الأخير كل الطبقات بالترتيب الظاهر."]
  ];
  const addStageCopy = (table, copy) => copy.forEach(([name, intro, target, wrong], index) => Object.assign(table, { [`scene${index + 1}`]: name, [`scene${index + 1}Intro`]: intro, [`target${index + 1}`]: target, [`wrong${index + 1}`]: wrong }));
  addStageCopy(base, stageCopy); addStageCopy(variants["zh-Hant"], zhStageCopy); addStageCopy(variants.ar, arStageCopy);
  Object.assign(variants.ar, {
    locked: "مغلق", farBack: "أقصى الخلف", mechanicStack: "القاعدة: طابق الترتيب من الأمام إلى الخلف تماماً.", mechanicDecoy: "القاعدة: أبقِ عثة الطُعم المعلّمة خلف كل طبقات الهدف.", mechanicWind: "القاعدة: تقرأ هذه الهبة الهدف من الخلف إلى الأمام.", mechanicEcho: "القاعدة: ضع طبقة الصدى في موضعها الظاهر؛ كل طبقة مهمة.", genreValue: "ألغاز · منطق · تخطيط مكاني · عائلي · حيوانات",
    moss: "طبقة الطحلب", glow: "طبقة وهج البستان", root: "طبقة الجذر", willow: "طبقة الصفصاف", brook: "طبقة الجدول", mist: "طبقة الضباب", leaf: "طبقة الورقة", rain: "طبقة المطر", sun: "طبقة الشمس", bloom: "طبقة الزهرة", canopy: "طبقة المظلة", beacon: "طبقة المنارة", reeds: "طبقة القصب", creek: "طبقة المجرى", amber: "طبقة الضوء الكهرماني", reed: "طبقة القصب المفرد", stone: "طبقة الصخرة", stream: "طبقة الماء الجاري", pebble: "طبقة الحصى", wind: "طبقة الريح", pine: "طبقة الصنوبر", fog: "طبقة الضباب", fox: "طبقة الثعلب", wing: "طبقة الجناح", meadow: "طبقة المرج", whistle: "طبقة الصفير", storm: "طبقة العاصفة", glass: "طبقة الزجاج", ridge: "طبقة الحافة", owl: "طبقة البومة", frost: "طبقة الصقيع", echo: "طبقة الصدى", snow: "طبقة الثلج", bell: "طبقة الجرس", hollow: "طبقة الجوف", night: "طبقة الليل", star: "طبقة النجمة", shell: "طبقة الصدفة", coral: "طبقة المرجان", kelp: "طبقة عشب البحر", tide: "طبقة المد", sand: "طبقة الرمل", water: "طبقة الماء", acorn: "طبقة ثمرة البلوط", burrow: "طبقة الجحر", keeper: "طبقة الحارس", moth: "طبقة عثة الطُعم"
  });
  window.ANIMAL_LAYER_GROVE_LOCALES = Object.fromEntries(keys.map((key) => [key, { ...base, ...(variants[key] || {}) }]));
})();
