(function () {
  "use strict";
  const locales = window.BURROW_BUILDER_LOCALES;
  const localeKeys = locales.__localeKeys;
  const rounds = [
    { slots: ["stone", "leaf", "acorn"], options: ["stone", "leaf", "acorn", "flower"] },
    { slots: ["wood", "clay", "flower"], options: ["clay", "flower", "wood", "acorn"] },
    { slots: ["stone", "wood", "acorn"], options: ["acorn", "stone", "wood", "leaf"] }
  ];
  const moduleSymbols = { stone: "⬟", leaf: "❧", acorn: "●", flower: "✿", wood: "▰", clay: "◉" };
  const moduleNames = { en: { stone: "Stone floor", leaf: "Leaf canopy", acorn: "Acorn nest", flower: "Flower nest", wood: "Wood floor", clay: "Clay shelter" }, "zh-Hant": { stone: "石頭地板", leaf: "葉片遮棚", acorn: "橡果巢室", flower: "花朵巢室", wood: "木頭地板", clay: "黏土遮棚" }, "zh-Hans": { stone: "石头地板", leaf: "叶片遮棚", acorn: "橡果巢室", flower: "花朵巢室", wood: "木头地板", clay: "黏土遮棚" }, ja: { stone: "石の床", leaf: "葉の屋根", acorn: "どんぐりの巣", flower: "花の巣", wood: "木の床", clay: "粘土のシェルター" }, ko: { stone: "돌 바닥", leaf: "잎 지붕", acorn: "도토리 둥지", flower: "꽃 둥지", wood: "나무 바닥", clay: "점토 보금자리" }, es: { stone: "Suelo de piedra", leaf: "Techo de hojas", acorn: "Nido de bellota", flower: "Nido de flores", wood: "Suelo de madera", clay: "Refugio de arcilla" }, "pt-BR": { stone: "Piso de pedra", leaf: "Cobertura de folhas", acorn: "Ninho de bolota", flower: "Ninho de flores", wood: "Piso de madeira", clay: "Abrigo de argila" }, fr: { stone: "Sol de pierre", leaf: "Toit de feuilles", acorn: "Nid de gland", flower: "Nid de fleurs", wood: "Sol en bois", clay: "Abri d’argile" }, de: { stone: "Steinboden", leaf: "Blätterdach", acorn: "Eichelnest", flower: "Blumennest", wood: "Holzboden", clay: "Lehmhütte" }, it: { stone: "Pavimento in pietra", leaf: "Tetto di foglie", acorn: "Nido di ghiande", flower: "Nido di fiori", wood: "Pavimento in legno", clay: "Riparo d’argilla" }, ru: { stone: "Каменный пол", leaf: "Крыша из листьев", acorn: "Жёлудевое гнездо", flower: "Цветочное гнездо", wood: "Деревянный пол", clay: "Глиняное укрытие" }, hi: { stone: "पत्थर का फ़र्श", leaf: "पत्तों की छत", acorn: "बलूत घोंसला", flower: "फूलों का घोंसला", wood: "लकड़ी का फ़र्श", clay: "मिट्टी का आश्रय" }, ar: { stone: "أرضية حجرية", leaf: "سقف من الأوراق", acorn: "عش البلوط", flower: "عش الزهور", wood: "أرضية خشبية", clay: "مأوى من الطين" } };
  const staticGuideCopy = {
    en: { gameGuideLabel: "Burrow Builder game guide", aria: "Burrow Builder game information", kicker: "WeightPlay Original Game Guide", title: "Burrow Builder", intro: "Choose a habitat module, then place it into the matching burrow plan.", gameplayLabel: "Gameplay", gameplay: "Shelter Construction Puzzle", genreLabel: "Genre", genre: "Puzzle · Construction · Spatial Planning · Family · Animal", faqTitle: "FAQ", faqQuestion: "Is progress saved?", faqAnswer: "Yes, only in this browser." },
    "zh-Hant": { gameGuideLabel: "地穴建造隊遊戲指南", aria: "地穴建造隊遊戲資訊", kicker: "WeightPlay 原創遊戲指南", title: "地穴建造隊", intro: "選擇棲地模組，再放入相符的地穴藍圖。", gameplayLabel: "玩法", gameplay: "棲地建造益智", genreLabel: "類型", genre: "益智 · 建造 · 空間規劃 · 家庭 · 動物", faqTitle: "常見問題", faqQuestion: "進度會保存嗎？", faqAnswer: "是，只保存在這個瀏覽器中。" },
    "zh-Hans": { gameGuideLabel: "地穴建造队游戏指南", aria: "地穴建造队游戏信息", kicker: "WeightPlay 原创游戏指南", title: "地穴建造队", intro: "选择栖地模块，再放入相符的地穴蓝图。", gameplayLabel: "玩法", gameplay: "栖地建造益智", genreLabel: "类型", genre: "益智 · 建造 · 空间规划 · 家庭 · 动物", faqTitle: "常见问题", faqQuestion: "进度会保存吗？", faqAnswer: "是，只保存在此浏览器中。" },
    ja: { gameGuideLabel: "バロービルダー ゲームガイド", aria: "バロービルダー ゲーム情報", kicker: "WeightPlay オリジナルゲームガイド", title: "バロービルダー", intro: "すみかモジュールを選び、合う設計図に置きます。", gameplayLabel: "ゲーム内容", gameplay: "すみか建築パズル", genreLabel: "ジャンル", genre: "パズル · 建築 · 空間計画 · ファミリー · 動物", faqTitle: "よくある質問", faqQuestion: "進行状況は保存されますか？", faqAnswer: "はい、このブラウザにのみ保存されます。" },
    ko: { gameGuideLabel: "굴 보금자리 만들기 게임 가이드", aria: "굴 보금자리 만들기 게임 정보", kicker: "WeightPlay 오리지널 게임 가이드", title: "굴 보금자리 만들기", intro: "보금자리 모듈을 골라 알맞은 설계도에 놓으세요.", gameplayLabel: "게임플레이", gameplay: "보금자리 건설 퍼즐", genreLabel: "장르", genre: "퍼즐 · 건설 · 공간 계획 · 가족 · 동물", faqTitle: "FAQ", faqQuestion: "진행 상황이 저장되나요?", faqAnswer: "예, 이 브라우저에만 저장됩니다." },
    es: { gameGuideLabel: "Guía de Constructor de madrigueras", aria: "Información de Constructor de madrigueras", kicker: "Guía de juegos originales de WeightPlay", title: "Constructor de madrigueras", intro: "Elige un módulo y colócalo en el plano de madriguera correcto.", gameplayLabel: "Jugabilidad", gameplay: "Puzzle de construcción", genreLabel: "Género", genre: "Puzle · Construcción · Planificación espacial · Familia · Animal", faqTitle: "Preguntas frecuentes", faqQuestion: "¿Se guarda el progreso?", faqAnswer: "Sí, solo en este navegador." },
    "pt-BR": { gameGuideLabel: "Guia do Construtor de Tocas", aria: "Construtor de Tocas informações do jogo", kicker: "Guia de jogos originais WeightPlay", title: "Construtor de Tocas", intro: "Escolha um módulo e coloque-o no plano de toca certo.", gameplayLabel: "Gameplay", gameplay: "Puzzle de construção", genreLabel: "Gênero", genre: "Puzzle · Construção · Planejamento espacial · Família · Animal", faqTitle: "Perguntas frequentes", faqQuestion: "O progresso é salvo?", faqAnswer: "Sim, apenas neste navegador." },
    fr: { gameGuideLabel: "Guide du Bâtisseur de terriers", aria: "Informations sur Bâtisseur de terriers", kicker: "Guide des jeux originaux WeightPlay", title: "Bâtisseur de terriers", intro: "Choisis un module et place-le dans le bon plan de terrier.", gameplayLabel: "Jeu", gameplay: "Puzzle de construction", genreLabel: "Genre", genre: "Puzzle · Construction · Planification spatiale · Famille · Animal", faqTitle: "Questions fréquentes", faqQuestion: "La progression est-elle enregistrée ?", faqAnswer: "Oui, uniquement dans ce navigateur." },
    de: { gameGuideLabel: "Leitfaden für Bau der Tierhöhle", aria: "Informationen zu Bau der Tierhöhle", kicker: "WeightPlay-Leitfaden für Originalspiele", title: "Bau der Tierhöhle", intro: "Wähle ein Modul und setze es in den passenden Höhlenplan.", gameplayLabel: "Spielweise", gameplay: "Bau-Puzzle", genreLabel: "Genre", genre: "Puzzle · Bauen · Raumplanung · Familie · Tier", faqTitle: "Häufige Fragen", faqQuestion: "Wird der Fortschritt gespeichert?", faqAnswer: "Ja, nur in diesem Browser." },
    it: { gameGuideLabel: "Guida per Costruttore di tane", aria: "Costruttore di tane informazioni sul gioco", kicker: "Guida ai giochi originali WeightPlay", title: "Costruttore di tane", intro: "Scegli un modulo e posizionalo nel progetto di tana giusto.", gameplayLabel: "Gameplay", gameplay: "Puzzle di costruzione", genreLabel: "Genere", genre: "Puzzle · Costruzione · Pianificazione spaziale · Famiglia · Animale", faqTitle: "Domande frequenti", faqQuestion: "I progressi vengono salvati?", faqAnswer: "Sì, solo in questo browser." },
    ru: { gameGuideLabel: "Руководство по игре «Строитель нор»", aria: "Строитель нор: информация об игре", kicker: "Руководство по оригинальным играм WeightPlay", title: "Строитель нор", intro: "Выберите модуль и поставьте его в подходящий план норы.", gameplayLabel: "Игровой процесс", gameplay: "Пазл строительства", genreLabel: "Жанр", genre: "Головоломка · Строительство · Пространственное планирование · Семья · Животные", faqTitle: "Частые вопросы", faqQuestion: "Сохраняется ли прогресс?", faqAnswer: "Да, только в этом браузере." },
    hi: { gameGuideLabel: "बिल बनाने वाले खेल की गाइड", aria: "बिल बनाने वाला खेल की जानकारी", kicker: "WeightPlay मौलिक गेम गाइड", title: "बिल बनाने वाला", intro: "मॉड्यूल चुनकर सही बिल योजना में रखें।", gameplayLabel: "गेमप्ले", gameplay: "निर्माण पहेली", genreLabel: "शैली", genre: "पहेली · निर्माण · स्थानिक योजना · परिवार · पशु", faqTitle: "अक्सर पूछे जाने वाले प्रश्न", faqQuestion: "क्या प्रगति सहेजी जाती है?", faqAnswer: "हाँ, केवल इसी ब्राउज़र में।" },
    ar: { gameGuideLabel: "دليل لعبة بناء الجحور", aria: "معلومات لعبة بناء الجحور", kicker: "دليل ألعاب WeightPlay الأصلية", title: "بناء الجحور", intro: "اختر وحدة وضعها في مخطط الجحر المناسب.", gameplayLabel: "طريقة اللعب", gameplay: "لغز بناء المأوى", genreLabel: "النوع", genre: "لغز · بناء · تخطيط مكاني · عائلي · حيوانات", faqTitle: "الأسئلة الشائعة", faqQuestion: "هل يُحفظ التقدم؟", faqAnswer: "تبقى أفضل النتائج والتفضيلات في هذا المتصفح فقط." }
  };
  const routeLocaleMap = { en: "en", "zh-tw": "zh-Hant", "zh-hant": "zh-Hant", "zh-cn": "zh-Hans", "zh-hans": "zh-Hans", ja: "ja", ko: "ko", es: "es", "pt-br": "pt-BR", fr: "fr", de: "de", it: "it", ru: "ru", hi: "hi", ar: "ar" };
  const state = { locale: "en", sound: true, roundIndex: 0, placements: 0, completed: 0, selected: null, placed: [] };
  const $ = (id) => document.getElementById(id);
  const safeStorage = { get(key) { try { return window.localStorage.getItem(key); } catch (_) { return null; } }, set(key, value) { try { window.localStorage.setItem(key, value); } catch (_) {} } };
  function queryLocale() { const q = new URLSearchParams(window.location.search).get("lang"); if (q && locales[q]) return q; const seg = window.location.pathname.split("/").filter(Boolean)[0]?.toLowerCase(); return routeLocaleMap[seg] || safeStorage.get("weightplay-burrow-locale") || "en"; }
  function t(key, vars = {}) { const copy = locales[state.locale] || locales.en; const value = copy[key] || locales.en[key] || key; return value.replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? "")); }
  function name(token) { return (moduleNames[state.locale] || moduleNames.en)[token] || token; }
  function applyStaticGuideLocale() {
    const guide = document.querySelector("section.game-page-info-static");
    const copy = staticGuideCopy[state.locale] || staticGuideCopy.en;
    if ($("gameGuide")) $("gameGuide").setAttribute("aria-label", copy.gameGuideLabel);
    if (!guide) return;
    guide.setAttribute("aria-label", copy.aria);
    const kicker = guide.querySelector(".game-info-kicker");
    const title = guide.querySelector(".game-info-title h2");
    const intro = guide.querySelector(".game-info-title p");
    const facts = guide.querySelectorAll(".game-info-fact");
    const faq = guide.querySelector(".game-info-section");
    if (kicker) kicker.textContent = copy.kicker;
    if (title) title.textContent = copy.title;
    if (intro) intro.textContent = copy.intro;
    if (facts[0]) { facts[0].querySelector("span").textContent = copy.gameplayLabel; facts[0].querySelector("strong").textContent = copy.gameplay; }
    if (facts[1]) { facts[1].querySelector("span").textContent = copy.genreLabel; facts[1].querySelector("strong").textContent = copy.genre; }
    if (faq) { faq.querySelector("h3").textContent = copy.faqTitle; faq.querySelector("dt").textContent = copy.faqQuestion; faq.querySelector("dd").textContent = copy.faqAnswer; }
  }
  function applyLocale() {
    const copy = locales[state.locale] || locales.en;
    document.documentElement.lang = state.locale === "zh-Hant" ? "zh-TW" : state.locale; document.documentElement.dir = copy.direction || "ltr";
    document.querySelectorAll("[data-copy]").forEach((node) => { node.textContent = t(node.dataset.copy); });
    applyStaticGuideLocale();
    $("mainSettingsBtn").setAttribute("aria-label", t("settings")); $("mainSettingsPopover").setAttribute("aria-label", t("settings")); $("homeFromBattle").setAttribute("aria-label", t("home")); $("localeSelect").setAttribute("aria-label", t("language"));
    $("soundToggle").setAttribute("aria-pressed", String(state.sound)); $("soundToggle").setAttribute("aria-checked", String(state.sound)); $("battleSoundToggle").setAttribute("aria-pressed", String(state.sound)); $("battleSoundToggle").setAttribute("aria-label", t(state.sound ? "soundOn" : "soundOff")); $("battleSoundToggle").textContent = state.sound ? "♪" : "×";
    if (!$('battleView').hidden) renderRound();
  }
  function populateLocales() { const select = $("localeSelect"); localeKeys.forEach((key) => { const option = document.createElement("option"); option.value = key; option.textContent = locales.en.languageNames[key]; select.append(option); }); select.value = state.locale; select.addEventListener("change", () => { state.locale = select.value; safeStorage.set("weightplay-burrow-locale", state.locale); applyLocale(); }); }
  function tone(kind) { if (!state.sound || !(window.AudioContext || window.webkitAudioContext)) return; try { const C = window.AudioContext || window.webkitAudioContext; const a = new C(); const o = a.createOscillator(); const g = a.createGain(); o.frequency.value = kind === "success" ? 620 : 190; g.gain.setValueAtTime(.0001, a.currentTime); g.gain.exponentialRampToValueAtTime(.03, a.currentTime + .01); g.gain.exponentialRampToValueAtTime(.0001, a.currentTime + .11); o.connect(g).connect(a.destination); o.start(); o.stop(a.currentTime + .12); o.addEventListener("ended", () => a.close(), { once: true }); } catch (_) {} }
  function showView(id) { const main = id === "mainView"; const result = id === "resultView"; $("mainView").hidden = !main; $("gameGuide").hidden = !main; $("battleView").hidden = main; $("resultView").hidden = !result; $("leaveDialog").hidden = true; document.body.dataset.screen = main ? "main" : result ? "result" : "battle"; if (main) { $("mainSettingsPopover").hidden = true; $("mainSettingsBtn").setAttribute("aria-expanded", "false"); } window.scrollTo(0, 0); }
  function start() { state.roundIndex = 0; state.placements = 0; state.completed = 0; state.selected = null; state.placed = []; showView("battleView"); renderRound(); }
  function renderRound() {
    const round = rounds[state.roundIndex]; $("roundLabel").textContent = t("round", { current: state.roundIndex + 1, total: rounds.length }); $("placementCount").textContent = String(state.placements); $("instruction").textContent = t("instruction");
    const blueprint = $("blueprint"); blueprint.replaceChildren();
    ["floor", "shelter", "nest"].forEach((slot, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "blueprint-slot"; button.dataset.slot = slot; const token = state.placed[index]; if (token) { button.classList.add("is-filled"); button.innerHTML = `<span class="slot-symbol" aria-hidden="true">${moduleSymbols[token]}</span><span>${name(token)}</span><small>${t("placed")}</small>`; button.disabled = true; } else { button.innerHTML = `<span class="slot-label">${t(slot)}</span><small>${t("missing")}</small>`; button.setAttribute("aria-label", `${t(slot)} — ${t("missing")}`); button.addEventListener("click", () => place(slot, index, button)); } blueprint.append(button); });
    const moduleGrid = $("moduleGrid"); moduleGrid.replaceChildren(...round.options.map((token) => { const button = document.createElement("button"); button.type = "button"; button.className = "module-card"; button.dataset.module = token; button.disabled = state.placed.includes(token); button.setAttribute("aria-label", t("chooseModule", { module: name(token) })); button.innerHTML = `<span class="module-symbol module-${token}" aria-hidden="true"></span><span>${name(token)}</span>`; if (state.selected === token) button.classList.add("is-selected"); button.addEventListener("click", () => select(token)); return button; }));
    $("selectionHint").textContent = state.selected ? t("selected", { module: name(state.selected) }) : "";
  }
  function select(token) { state.selected = token; $("selectionHint").textContent = t("selected", { module: name(token) }); tone("select"); renderRound(); }
  function place(slot, index, button) { if (!state.selected) { $("feedback").textContent = t("instruction"); button.classList.add("needs-selection"); window.setTimeout(() => button.classList.remove("needs-selection"), 350); return; } state.placements += 1; $("placementCount").textContent = String(state.placements); const correctSlot = ["floor", "shelter", "nest"][rounds[state.roundIndex].slots.indexOf(state.selected)]; if (correctSlot !== slot) { $("feedback").textContent = t("wrong"); $("feedback").className = "feedback is-wrong"; tone("wrong"); button.classList.add("is-wrong"); window.setTimeout(() => button.classList.remove("is-wrong"), 420); return; } state.placed[index] = state.selected; state.completed += 1; state.selected = null; $("feedback").textContent = t("correct"); $("feedback").className = "feedback is-correct"; tone("success"); renderRound(); if (state.placed.filter(Boolean).length === 3) window.setTimeout(() => { if (state.roundIndex < rounds.length - 1) { state.roundIndex += 1; state.placed = []; $("feedback").textContent = ""; renderRound(); } else finish(); }, 420); }
  function finish() { const key = "weightplay-burrow-best-placements"; const prior = Number(safeStorage.get(key)); if (!prior || state.placements < prior) safeStorage.set(key, String(state.placements)); $("resultSummary").textContent = t("summary", { count: state.placements }); $("bestCount").textContent = safeStorage.get(key) || String(state.placements); showView("resultView"); }
  function goHome() { showView("mainView"); applyLocale(); }
  function toggleSound() { state.sound = !state.sound; applyLocale(); }
  function toggleSettings() { const panel = $("mainSettingsPopover"); const open = panel.hidden; panel.hidden = !open; $("mainSettingsBtn").setAttribute("aria-expanded", String(open)); }
  function openLeave() { $("leaveDialog").hidden = false; $("continueBtn").focus(); }
  function closeLeave() { $("leaveDialog").hidden = true; $("homeFromBattle").focus(); }
  state.locale = queryLocale();
  document.addEventListener("DOMContentLoaded", () => { populateLocales(); applyLocale(); $("startButton").addEventListener("click", start); $("replayButton").addEventListener("click", start); $("homeFromBattle").addEventListener("click", openLeave); $("leaveBtn").addEventListener("click", openLeave); $("continueBtn").addEventListener("click", closeLeave); $("confirmLeaveBtn").addEventListener("click", goHome); $("homeFromResult").addEventListener("click", goHome); $("mainSettingsBtn").addEventListener("click", toggleSettings); $("soundToggle").addEventListener("click", toggleSound); $("battleSoundToggle").addEventListener("click", toggleSound); });
  window.BURROW_BUILDER_TEST = { rounds, start, renderRound };
})();
