(function () {
  "use strict";
  window.BURROW_BUILDER_LOCALES = {
    __localeKeys: ["en", "zh-Hant"],
    en: {
      direction: "ltr", language: "Language", languageNames: { en: "English", "zh-Hant": "繁體中文" },
      title: "Burrow Builder", eyebrow: "A calm shelter-planning puzzle", subtitle: "Choose each habitat module, then place it in the matching burrow plan.", facts: "Three short plans · no timer · calm retry", start: "Start building", how: "How to play", howBody: "Tap a module, then tap the blueprint slot where it belongs. Correct pieces lock in. A wrong slot is harmless, so look again and try another place.",
      settings: "Settings", soundOn: "Sound on", soundOff: "Sound off", battleTitle: "Build the burrow", home: "Home", round: "Plan {current} of {total}", placements: "placements", instruction: "Choose a module, then place it in the matching slot.", floor: "Floor", shelter: "Shelter", nest: "Nest", modules: "Habitat modules", selected: "Selected: {module}", chooseModule: "Choose {module}", placed: "Placed", wrong: "That module belongs in another slot. Try again.", correct: "Nice fit! The burrow is sturdier.", leaveTitle: "Leave this plan?", leaveBody: "Your current placements will be lost, but your best build stays saved.", continue: "Continue", confirmLeave: "Return to Home", completeEyebrow: "Shelter complete", complete: "A cosy place to rest.", summary: "Three burrow plans completed with {count} placements.", best: "Best placements", replay: "Build again", footer: "Internal prototype · no public lobby or sitemap entry", missing: "Empty blueprint slot"
    },
    "zh-Hant": {
      direction: "ltr", language: "語言", languageNames: { en: "English", "zh-Hant": "繁體中文" },
      title: "地穴建造隊", eyebrow: "平靜的棲地規劃益智", subtitle: "選好每個棲地模組，再放進相符的地穴藍圖。", facts: "三張短藍圖・沒有計時・平靜重試", start: "開始建造", how: "玩法說明", howBody: "先點選模組，再點選它所屬的藍圖格。放對就會固定；放錯不會受罰，重新看看再試一次。",
      settings: "設定", soundOn: "音效開啟", soundOff: "音效關閉", battleTitle: "建造地穴", home: "首頁", round: "藍圖 {current}／{total}", placements: "次放置", instruction: "選擇模組，再放入相符的藍圖格。", floor: "地板", shelter: "遮棚", nest: "巢室", modules: "棲地模組", selected: "已選：{module}", chooseModule: "選擇{module}", placed: "已放置", wrong: "這個模組屬於另一個位置，再試試看。", correct: "放得真好！地穴更穩固了。", leaveTitle: "要離開這張藍圖嗎？", leaveBody: "目前放置會遺失，但最佳建造紀錄會保留。", continue: "繼續", confirmLeave: "回到首頁", completeEyebrow: "棲地完成", complete: "一個舒服的休息處。", summary: "完成三張地穴藍圖，共放置 {count} 次。", best: "最佳放置次數", replay: "再建一次", footer: "內部原型・尚未加入公開大廳或 Sitemap", missing: "空白藍圖格"
    }
  };
  const localeCopyKeys = ["language", "title", "eyebrow", "subtitle", "facts", "start", "how", "howBody", "settings", "soundOn", "soundOff", "battleTitle", "home", "round", "placements", "instruction", "floor", "shelter", "nest", "modules", "selected", "chooseModule", "placed", "wrong", "correct", "leaveTitle", "leaveBody", "continue", "confirmLeave", "completeEyebrow", "complete", "summary", "best", "replay", "footer", "missing"];
  const languageNames = { en: "English", "zh-Hant": "繁體中文", "zh-Hans": "简体中文", ja: "日本語", ko: "한국어", es: "Español", "pt-BR": "Português", fr: "Français", de: "Deutsch", it: "Italiano", ru: "Русский", hi: "हिन्दी", ar: "العربية" };
  const makeLocale = (values, direction = "ltr") => ({ direction, languageNames, ...Object.fromEntries(localeCopyKeys.map((key, index) => [key, values[index]])) });
  const extra = {
    "zh-Hans": makeLocale(["语言", "地穴建造队", "平静的栖地规划益智", "选择每个栖地模块并放入匹配地穴方案。", "三张短蓝图·无计时·平静重试", "开始建造", "玩法说明", "点击模块，再点击它所属的蓝图格。放对会固定。放错没有惩罚，再看一次继续。", "设置", "音效开启", "音效关闭", "建造地穴", "首页", "蓝图 {current}/{total}", "次放置", "选择模块，再放入匹配蓝图格。", "地板", "遮棚", "巢室", "栖地模块", "已选：{module}", "选择{module}", "已放置", "这个模块属于另一个位置，再试试。", "放得真好！地穴更稳固了。", "要离开这张蓝图吗？", "当前放置会丢失，但最佳建造记录会保留。", "继续", "返回首页", "栖地完成", "一个舒适的休息处。", "完成三张地穴蓝图，共放置 {count} 次。", "最佳放置次数", "再建一次", "内部原型·尚未加入公开大厅或 Sitemap", "空白蓝图格"]),
    ja: makeLocale(["言語", "バロービルダー", "穏やかなすみか計画パズル", "各すみかモジュールを選び、合う巣穴プランに置きます。", "短いプラン3つ・タイマーなし・穏やかに再挑戦", "建設を始める", "遊び方", "モジュールを選び、合う設計図の枠をタップします。正解は固定され、間違えても安全です。", "設定", "サウンドオン", "サウンドオフ", "巣穴を建てる", "ホーム", "プラン {current}/{total}", "配置", "モジュールを選び、合う設計図の枠に置きます。", "床", "屋根", "巣", "すみかモジュール", "選択中：{module}", "{module}を選ぶ", "配置済み", "そのモジュールは別の枠です。もう一度。", "ぴったり！巣穴が丈夫になりました。", "このプランを離れますか？", "現在の配置は失われますが、ベスト記録は残ります。", "続ける", "ホームに戻る", "すみか完成", "休める場所ができました。", "3つの巣穴プランを {count} 回の配置で完了。", "ベスト配置", "もう一度建てる", "内部プロトタイプ・公開ロビーやサイトマップには未掲載", "空の設計図枠"]),
    ko: makeLocale(["언어", "굴 보금자리 만들기", "차분한 보금자리 계획 퍼즐", "각 보금자리 모듈을 골라 알맞은 굴 계획에 놓으세요.", "짧은 계획 3개 · 타이머 없음 · 차분한 재시도", "건설 시작", "게임 방법", "모듈을 고른 뒤 맞는 설계도 칸을 누르세요. 틀려도 안전하니 다시 살펴보세요.", "설정", "소리 켜짐", "소리 꺼짐", "굴 만들기", "홈", "계획 {current}/{total}", "배치", "모듈을 고른 뒤 알맞은 칸에 놓으세요.", "바닥", "지붕", "둥지", "보금자리 모듈", "선택됨: {module}", "{module} 선택", "배치됨", "이 모듈은 다른 칸에 놓습니다. 다시 시도하세요.", "잘 맞았어요! 굴이 더 튼튼해졌습니다.", "이 계획을 나갈까요?", "현재 배치는 사라지지만 최고 기록은 저장됩니다.", "계속", "홈으로 돌아가기", "보금자리 완성", "편히 쉴 곳이 생겼어요.", "굴 계획 3개를 {count}번 배치로 완료했습니다.", "최고 배치", "다시 만들기", "내부 프로토타입 · 공개 로비와 사이트맵에 없음", "빈 설계도 칸"]),
    es: makeLocale(["Idioma", "Constructor de madrigueras", "Rompecabezas tranquilo de refugios", "Elige cada módulo y colócalo en el plano de madriguera correcto.", "Tres planos breves · sin temporizador · reintento tranquilo", "Empezar a construir", "Cómo jugar", "Toca un módulo y luego el espacio correcto del plano. Un error no penaliza; vuelve a mirar y prueba.", "Ajustes", "Sonido activado", "Sonido desactivado", "Construir la madriguera", "Inicio", "Plano {current}/{total}", "colocaciones", "Elige un módulo y colócalo en el espacio correspondiente.", "Suelo", "Refugio", "Nido", "Módulos de hábitat", "Seleccionado: {module}", "Elegir {module}", "Colocado", "Ese módulo va en otro espacio. Inténtalo de nuevo.", "¡Encaja muy bien! La madriguera es más firme.", "¿Salir de este plano?", "Se perderán las colocaciones actuales, pero se guardará tu mejor marca.", "Continuar", "Volver al inicio", "Refugio completo", "Un lugar acogedor para descansar.", "Completaste tres planos con {count} colocaciones.", "Mejor marca", "Construir otra vez", "Prototipo interno · sin lobby público ni sitemap", "Espacio vacío del plano"]),
    "pt-BR": makeLocale(["Idioma", "Construtor de Tocas", "Quebra-cabeça calmo de abrigos", "Escolha cada módulo e coloque-o no plano de toca correspondente.", "Três planos curtos · sem cronômetro · nova tentativa calma", "Começar a construir", "Como jogar", "Toque em um módulo e depois no espaço certo do plano. Errar não pune; observe e tente outra vez.", "Configurações", "Som ligado", "Som desligado", "Construir a toca", "Início", "Plano {current}/{total}", "colocações", "Escolha um módulo e coloque-o no espaço correspondente.", "Piso", "Abrigo", "Ninho", "Módulos de habitat", "Selecionado: {module}", "Escolher {module}", "Colocado", "Esse módulo pertence a outro espaço. Tente novamente.", "Ótimo encaixe! A toca ficou mais firme.", "Sair deste plano?", "As colocações atuais serão perdidas, mas o melhor resultado fica salvo.", "Continuar", "Voltar ao início", "Abrigo concluído", "Um lugar aconchegante para descansar.", "Três planos concluídos com {count} colocações.", "Melhor resultado", "Construir novamente", "Protótipo interno · sem lobby público ou sitemap", "Espaço vazio do plano"]),
    fr: makeLocale(["Langue", "Bâtisseur de terriers", "Puzzle calme de construction d’abris", "Choisissez chaque module et placez-le dans le bon plan de terrier.", "Trois plans courts · sans minuteur · reprise sereine", "Commencer la construction", "Comment jouer", "Touchez un module puis la case correspondante. Une erreur est sans danger : observez et réessayez.", "Paramètres", "Son activé", "Son désactivé", "Construire le terrier", "Accueil", "Plan {current}/{total}", "placements", "Choisissez un module puis placez-le dans la case correspondante.", "Sol", "Abri", "Nid", "Modules d’habitat", "Sélectionné : {module}", "Choisir {module}", "Placé", "Ce module va dans une autre case. Réessayez.", "Bien ajusté ! Le terrier est plus solide.", "Quitter ce plan ?", "Les placements actuels seront perdus, mais votre meilleur score restera enregistré.", "Continuer", "Retour à l’accueil", "Abri terminé", "Un endroit douillet pour se reposer.", "Trois plans terminés en {count} placements.", "Meilleur score", "Construire encore", "Prototype interne · sans lobby public ni sitemap", "Case de plan vide"]),
    de: makeLocale(["Sprache", "Bau der Tierhöhle", "Ruhiges Schutzbau-Puzzle", "Wähle jedes Habitat-Modul und setze es in den passenden Höhlenplan.", "Drei kurze Pläne · kein Timer · ruhiger Neustart", "Bau beginnen", "So wird gespielt", "Tippe ein Modul und danach auf das passende Planfeld. Fehler sind harmlos – schau noch einmal und probiere es.", "Einstellungen", "Ton an", "Ton aus", "Höhle bauen", "Start", "Plan {current}/{total}", "Platzierungen", "Wähle ein Modul und setze es in das passende Feld.", "Boden", "Schutz", "Nest", "Habitat-Module", "Ausgewählt: {module}", "{module} wählen", "Platziert", "Dieses Modul gehört in ein anderes Feld. Versuch es erneut.", "Passt gut! Die Höhle ist stabiler.", "Diesen Plan verlassen?", "Die aktuellen Platzierungen gehen verloren, dein bester Wert bleibt gespeichert.", "Weiter", "Zum Start", "Schutz fertig", "Ein gemütlicher Ruheplatz.", "Drei Höhlenpläne mit {count} Platzierungen abgeschlossen.", "Bester Wert", "Noch einmal bauen", "Interner Prototyp · kein öffentliches Lobby- oder Sitemap-Listing", "Leeres Planfeld"]),
    it: makeLocale(["Lingua", "Costruttore di tane", "Puzzle calmo per costruire rifugi", "Scegli ogni modulo e posizionalo nel progetto di tana corretto.", "Tre progetti brevi · senza timer · nuovo tentativo tranquillo", "Inizia a costruire", "Come si gioca", "Tocca un modulo e poi lo spazio giusto. Un errore non penalizza: guarda meglio e riprova.", "Impostazioni", "Audio attivo", "Audio disattivo", "Costruisci la tana", "Home", "Progetto {current}/{total}", "posizionamenti", "Scegli un modulo e posizionalo nello spazio corrispondente.", "Pavimento", "Riparo", "Nido", "Moduli dell’habitat", "Selezionato: {module}", "Scegli {module}", "Posizionato", "Questo modulo va in un altro spazio. Riprova.", "Ottimo incastro! La tana è più solida.", "Vuoi lasciare questo progetto?", "I posizionamenti attuali andranno persi, ma il record migliore resterà salvato.", "Continua", "Torna alla home", "Rifugio completato", "Un posto accogliente per riposare.", "Tre progetti completati con {count} posizionamenti.", "Miglior risultato", "Costruisci ancora", "Prototipo interno · nessuna lobby pubblica o sitemap", "Spazio vuoto del progetto"]),
    ru: makeLocale(["Язык", "Строитель нор", "Спокойная головоломка о жилищах", "Выберите каждый модуль и поставьте его в подходящий план норы.", "Три коротких плана · без таймера · спокойная попытка снова", "Начать строительство", "Как играть", "Выберите модуль, затем нажмите нужную ячейку плана. Ошибка безопасна — осмотритесь и попробуйте снова.", "Настройки", "Звук включён", "Звук выключен", "Строим нору", "Главная", "План {current}/{total}", "размещений", "Выберите модуль и поставьте его в подходящую ячейку.", "Пол", "Укрытие", "Гнездо", "Модули среды", "Выбрано: {module}", "Выбрать: {module}", "Размещено", "Этот модуль нужен в другой ячейке. Попробуйте ещё раз.", "Отлично подходит! Нора стала крепче.", "Покинуть этот план?", "Текущие размещения исчезнут, но лучший результат сохранится.", "Продолжить", "Вернуться на главную", "Жилище готово", "Уютное место для отдыха.", "Три плана норы завершены за {count} размещений.", "Лучший результат", "Строить снова", "Внутренний прототип · нет публичного лобби или sitemap", "Пустая ячейка плана"]),
    hi: makeLocale(["भाषा", "बिल बनाने वाला", "शांत आश्रय-योजना पहेली", "हर आवास मॉड्यूल चुनें और उसे सही बिल योजना में रखें।", "तीन छोटी योजनाएँ · टाइमर नहीं · शांत पुनः प्रयास", "निर्माण शुरू करें", "कैसे खेलें", "मॉड्यूल चुनें, फिर सही योजना-खाने पर टैप करें। गलत जगह रखने पर कोई दंड नहीं; फिर देखें और प्रयास करें।", "सेटिंग", "ध्वनि चालू", "ध्वनि बंद", "बिल बनाएँ", "होम", "योजना {current}/{total}", "रखने की संख्या", "मॉड्यूल चुनकर सही खाने में रखें।", "फ़र्श", "आश्रय", "घोंसला", "आवास मॉड्यूल", "चयनित: {module}", "{module} चुनें", "रखा गया", "यह मॉड्यूल किसी दूसरे खाने में जाएगा। फिर प्रयास करें।", "बहुत अच्छा! बिल और मज़बूत हुआ।", "क्या इस योजना से बाहर निकलें?", "वर्तमान जगहें मिट जाएँगी, लेकिन आपका सर्वश्रेष्ठ रिकॉर्ड सुरक्षित रहेगा।", "जारी रखें", "होम लौटें", "आश्रय पूरा", "आराम करने के लिए एक आरामदायक जगह।", "तीन बिल योजनाएँ {count} बार रखकर पूरी हुईं।", "सर्वश्रेष्ठ", "फिर बनाएँ", "आंतरिक प्रोटोटाइप · सार्वजनिक लॉबी या sitemap नहीं", "खाली योजना खाना"]),
    ar: makeLocale(["اللغة", "بناء الجحور", "لغز هادئ لتخطيط المأوى", "اختر كل وحدة موطن وضعها في مخطط الجحر المطابق.", "ثلاثة مخططات قصيرة · بلا مؤقت · إعادة هادئة", "ابدأ البناء", "طريقة اللعب", "اختر وحدة ثم اضغط خانة المخطط المناسبة. الخطأ بلا عقوبة؛ راجع الخطة وحاول مرة أخرى.", "الإعدادات", "الصوت مفعّل", "الصوت متوقف", "ابنِ الجحر", "الرئيسية", "المخطط {current}/{total}", "مرات الوضع", "اختر وحدة وضعها في الخانة المطابقة.", "الأرضية", "المأوى", "العش", "وحدات الموطن", "المحدد: {module}", "اختر {module}", "تم الوضع", "هذه الوحدة تنتمي إلى خانة أخرى. حاول مجدداً.", "اختيار موفق! أصبح الجحر أكثر متانة.", "هل تريد مغادرة هذا المخطط؟", "ستفقد المواضع الحالية، لكن أفضل نتيجة ستبقى محفوظة.", "متابعة", "العودة إلى الرئيسية", "اكتمل المأوى", "مكان دافئ للراحة.", "اكتملت ثلاثة مخططات للجحور عبر {count} عملية وضع.", "أفضل نتيجة", "ابنِ مرة أخرى", "نموذج أولي داخلي · بلا ردهة عامة أو sitemap", "خانة مخطط فارغة"], "rtl"),
  };
  Object.assign(window.BURROW_BUILDER_LOCALES, extra);
  window.BURROW_BUILDER_LOCALES.en.languageNames = languageNames;
  window.BURROW_BUILDER_LOCALES["zh-Hant"].languageNames = languageNames;
  window.BURROW_BUILDER_LOCALES.__localeKeys = ["en", "zh-Hant", "zh-Hans", "ja", "ko", "es", "pt-BR", "fr", "de", "it", "ru", "hi", "ar"];
})();
