(function(){
  "use strict";
  const en={
    loading:"Waking the clover meadow…",title:"Animal Honey Shield",language:"Language",backLobby:"Back to WeightPlay",
    posterAlt:"Pip sheltered by a glowing line as bees approach",eyebrow:"Cloverlight Meadow rescue puzzles",
    pitch:"Draw glowing nectar lines, repair weak spots during each wave, and keep Clover Pup Pip safe.",start:"Start Game",
    guideLabel:"Game guide",guideKicker:"WeightPlay Original Game Guide",guideTitle:"Protect Pip with the shortest strong line",
    guideIntro:"Pip has wandered beside Cloverlight Meadow's hives. Draw barriers while the startled bees fly, then reinforce openings before they reach the puppy.",
    howTitle:"How to play",how1:"Drag across the meadow to draw a glowing nectar barrier.",how2:"Release to begin the bee wave; keep drawing new segments while it runs.",how3:"Survive until the timer reaches zero without letting a bee touch Pip.",
    rulesTitle:"Rules and results",rulesText:"Each line spends nectar and weakens when bees collide with it. A touch on Pip fails the attempt. A safe countdown clears the stage; shorter lines and unused nectar earn more stars.",
    progressTitle:"Thirty meadow routes",progressText:"Six chapters add extra hives, split approaches, stone anchors, moving gusts, fragile gaps, and mixed mastery waves. Every clear unlocks the next route.",
    tipsTitle:"Practical tips",tipsText:"Anchor short curves between stones, leave room around Pip, and watch where the barrier glows red. A small repair is often stronger than drawing a second full circle.",
    saveTitle:"Save and privacy",saveText:"Unlocked stages and best stars stay only in this browser. No account, upload, or personal information is required.",
    faqTitle:"FAQ",faq1q:"Can I draw after the bees start?",faq1a:"Yes. Live repairs are the heart of the game, as long as nectar remains.",faq2q:"Do bees get hurt?",faq2a:"No. Nectar barriers gently bounce the startled bees back toward the flowers.",faq3q:"What should I play next?",faq3a:"Try One Line for careful tracing or Animal Guard Yard for a larger defense challenge.",
    backMain:"Back to Main",backStages:"Back to Stages",stageRailLabel:"Meadow stage selection",stages:"Stages",stage:"Stage {n}",locked:"Locked",cleared:"Protected",stars:"{n} stars",progress:"{done} / 30 protected · {stars} stars",
    chapter:"Chapter {n}",chapters:["First Flight","Twin Trails","Stone Anchors","Clover Gusts","Fragile Gaps","Honeyguard Mastery"],
    chapterRules:["Learn short barriers against one gentle wave.","Read two approaches and repair the weaker side.","Use meadow stones as strong line anchors.","React when warm gusts bend the bee route.","Spend nectar carefully across longer waves.","Combine every rule to keep Pip safe."],
    time:"Time",nectar:"Nectar",pause:"Pause",boardLabel:"Draw a nectar barrier to protect Pip",drawHint:"Draw anywhere to build Pip's shield",clear:"Clear lines",restart:"Restart",
    objective:"Keep Pip safe for {n} seconds",ready:"Draw the first barrier",waveStarted:"The bees are flying—repair weak spots!",lowNectar:"Nectar is low",lineStatus:"{used} drawn · {left} nectar",barrierHit:"That barrier is weakening!",protected:"Pip is safe!",touched:"A bee reached Pip. Try a different shield.",
    leaveTitle:"Leave this meadow?",leaveText:"Continue keeps this wave frozen. Returning to Stages ends only this attempt.",continue:"Continue",returnStages:"Return to Stages",
    pauseTitle:"Meadow paused",pauseText:"The bee wave is frozen while you take a break.",resume:"Resume",resultKicker:"Meadow report",winTitle:"Pip is protected!",failTitle:"The shield opened",winText:"Stage {stage} stayed safe with {nectar} nectar left.",failText:"Repair the first red gap before the bees reach Pip.",newBest:"New best shield!",best:"Best: {stars} stars",next:"Next Stage",retry:"Replay",
    tutorialTitle:"Draw, watch, and repair",tutorial1:"Drag one short barrier between Pip and the hive.",tutorial2:"Releasing starts the wave. Red flashes show a weakening line.",tutorial3:"Draw another short segment before a gap opens.",tutorialStart:"Protect Pip",close:"Close"
  };
  const zhHant={
    loading:"正在喚醒苜蓿草原…",title:"動物花蜜防線",language:"語言",backLobby:"返回 WeightPlay",
    posterAlt:"蜜蜂接近時，皮普躲在發光防線後方",eyebrow:"苜蓿光原救援解謎",pitch:"畫出發光花蜜線，在蜂群波次中修補弱點，保護苜蓿小犬皮普。",start:"開始遊戲",
    guideLabel:"遊戲指南",guideKicker:"WeightPlay 原創遊戲指南",guideTitle:"用最短又堅固的線保護皮普",guideIntro:"皮普走到苜蓿光原的蜂巢旁。蜂群飛行時畫出屏障，並在牠們碰到小犬前修補缺口。",
    howTitle:"遊玩方式",how1:"在草原上拖曳，畫出發光花蜜屏障。",how2:"放開後蜂群開始飛行；波次進行中仍可繼續補畫。",how3:"在倒數結束前，不讓任何蜜蜂碰到皮普。",
    rulesTitle:"規則與結果",rulesText:"畫線會消耗花蜜，蜜蜂撞擊也會讓線變弱。蜜蜂碰到皮普即失敗；安全撐過倒數即可過關，短線與剩餘花蜜會帶來更多星星。",
    progressTitle:"30 條草原路線",progressText:"六個章節加入更多蜂巢、分岔來向、石頭錨點、移動風勢、脆弱缺口與綜合波次。過關就能解鎖下一關。",
    tipsTitle:"實用提示",tipsText:"把短曲線固定在石頭之間，替皮普留下空間，並注意變紅的弱點。小幅補線通常比再畫一整圈更有效。",
    saveTitle:"儲存與隱私",saveText:"解鎖關卡與最佳星級只保存在這個瀏覽器，不需帳號、上傳或個人資料。",
    faqTitle:"常見問題",faq1q:"蜜蜂出發後還能畫線嗎？",faq1a:"可以。只要還有花蜜，即時修補就是遊戲核心。",faq2q:"蜜蜂會受傷嗎？",faq2a:"不會。花蜜屏障只會溫柔地把受驚蜂群彈回花朵方向。",faq3q:"接著適合玩什麼？",faq3a:"想練細緻描線可玩《動物一筆畫》，想挑戰大型防守可玩《動物守護庭院》。",
    backMain:"返回主畫面",backStages:"返回關卡",stageRailLabel:"草原關卡選擇",stages:"關卡",stage:"第 {n} 關",locked:"未解鎖",cleared:"已保護",stars:"{n} 星",progress:"已保護 {done} / 30 · {stars} 星",
    chapter:"第 {n} 章",chapters:["初次飛行","雙向花徑","石頭錨點","苜蓿暖風","脆弱缺口","花蜜守護試煉"],chapterRules:["用短屏障擋住第一波蜂群。","觀察兩個來向，優先修補較弱的一側。","利用草原石頭固定堅固防線。","暖風改變路線時立即應變。","在更長波次中謹慎分配花蜜。","綜合所有規則，完整保護皮普。"],
    time:"時間",nectar:"花蜜",pause:"暫停",boardLabel:"畫出花蜜屏障保護皮普",drawHint:"在任何位置畫線，建立皮普的防線",clear:"清除線條",restart:"重新開始",
    objective:"保護皮普 {n} 秒",ready:"先畫出第一道屏障",waveStarted:"蜂群出發了——快修補弱點！",lowNectar:"花蜜快用完了",lineStatus:"已畫 {used} · 剩餘 {left} 花蜜",barrierHit:"這段防線正在變弱！",protected:"皮普安全了！",touched:"蜜蜂碰到皮普了，換一種防線再試。",
    leaveTitle:"離開這片草原？",leaveText:"繼續會保留並凍結目前波次；返回關卡只會結束本次挑戰。",continue:"繼續遊戲",returnStages:"返回關卡",
    pauseTitle:"草原已暫停",pauseText:"休息期間蜂群波次會保持凍結。",resume:"繼續",resultKicker:"草原報告",winTitle:"皮普受到保護！",failTitle:"防線出現缺口",winText:"第 {stage} 關安全完成，剩餘 {nectar} 花蜜。",failText:"在蜜蜂抵達前，先修補第一個紅色缺口。",newBest:"新的最佳防線！",best:"最佳：{stars} 星",next:"下一關",retry:"再玩一次",
    tutorialTitle:"畫線、觀察、修補",tutorial1:"在皮普與蜂巢之間畫一道短屏障。",tutorial2:"放開後波次開始；紅色閃光代表防線正在變弱。",tutorial3:"在缺口形成前，再補上一小段線。",tutorialStart:"保護皮普",close:"關閉"
  };
  const zhHans={...zhHant,title:"动物花蜜防线",loading:"正在唤醒苜蓿草原…",language:"语言",backLobby:"返回 WeightPlay",posterAlt:"蜜蜂接近时，皮普躲在发光防线后方",eyebrow:"苜蓿光原救援解谜",pitch:"画出发光花蜜线，在蜂群波次中修补弱点，保护苜蓿小犬皮普。",start:"开始游戏",guideLabel:"游戏指南",guideKicker:"WeightPlay 原创游戏指南",guideTitle:"用最短又坚固的线保护皮普",howTitle:"玩法",rulesTitle:"规则与结果",progressTitle:"30 条草原路线",tipsTitle:"实用提示",saveTitle:"保存与隐私",faqTitle:"常见问题",backMain:"返回主界面",backStages:"返回关卡",stageRailLabel:"草原关卡选择",stages:"关卡",stage:"第 {n} 关",locked:"未解锁",cleared:"已保护",progress:"已保护 {done} / 30 · {stars} 星",chapter:"第 {n} 章",time:"时间",nectar:"花蜜",pause:"暂停",boardLabel:"画出花蜜屏障保护皮普",drawHint:"在任意位置画线，建立皮普的防线",clear:"清除线条",restart:"重新开始",ready:"先画出第一道屏障",waveStarted:"蜂群出发了——快修补弱点！",lowNectar:"花蜜快用完了",barrierHit:"这段防线正在变弱！",protected:"皮普安全了！",touched:"蜜蜂碰到皮普了，换一种防线再试。",leaveTitle:"离开这片草原？",continue:"继续游戏",returnStages:"返回关卡",pauseTitle:"草原已暂停",resume:"继续",resultKicker:"草原报告",winTitle:"皮普受到保护！",failTitle:"防线出现缺口",newBest:"新的最佳防线！",best:"最佳：{stars} 星",next:"下一关",retry:"再玩一次",tutorialTitle:"画线、观察、修补",tutorialStart:"保护皮普",close:"关闭"};
  const es={...en,loading:"Despertando el prado de tréboles…",title:"Escudo de Miel Animal",language:"Idioma",backLobby:"Volver a WeightPlay",posterAlt:"Pip protegido por una línea brillante mientras se acercan abejas",eyebrow:"Rescates del Prado Trébol Luz",pitch:"Dibuja líneas de néctar, repara puntos débiles durante cada oleada y protege a Pip.",start:"Empezar",guideLabel:"Guía del juego",guideKicker:"Guía del juego original de WeightPlay",guideTitle:"Protege a Pip con la línea fuerte más corta",howTitle:"Cómo jugar",rulesTitle:"Reglas y resultados",progressTitle:"Treinta rutas del prado",tipsTitle:"Consejos prácticos",saveTitle:"Guardado y privacidad",faqTitle:"Preguntas frecuentes",backMain:"Volver al inicio",backStages:"Volver a niveles",stageRailLabel:"Selección de rutas",stages:"Niveles",stage:"Nivel {n}",locked:"Bloqueado",cleared:"Protegido",stars:"{n} estrellas",progress:"{done} / 30 protegidos · {stars} estrellas",chapter:"Capítulo {n}",chapters:["Primer vuelo","Senderos dobles","Anclajes de piedra","Vientos de trébol","Huecos frágiles","Maestría guardamiel"],time:"Tiempo",nectar:"Néctar",pause:"Pausa",boardLabel:"Dibuja una barrera para proteger a Pip",drawHint:"Dibuja para crear el escudo de Pip",clear:"Borrar líneas",restart:"Reiniciar",objective:"Protege a Pip {n} segundos",ready:"Dibuja la primera barrera",waveStarted:"¡Las abejas vuelan! Repara los puntos débiles.",lowNectar:"Queda poco néctar",barrierHit:"¡La barrera se debilita!",protected:"¡Pip está a salvo!",touched:"Una abeja llegó a Pip. Prueba otro escudo.",leaveTitle:"¿Salir del prado?",continue:"Continuar",returnStages:"Volver a niveles",pauseTitle:"Prado en pausa",pauseText:"La oleada queda congelada durante el descanso.",resume:"Reanudar",resultKicker:"Informe del prado",winTitle:"¡Pip está protegido!",failTitle:"El escudo se abrió",newBest:"¡Nuevo mejor escudo!",best:"Mejor: {stars} estrellas",next:"Siguiente nivel",retry:"Repetir",tutorialTitle:"Dibuja, observa y repara",tutorialStart:"Proteger a Pip",close:"Cerrar"};
  const pt={...es,loading:"Acordando o Prado do Trevo…",title:"Escudo de Mel Animal",language:"Idioma",backLobby:"Voltar ao WeightPlay",posterAlt:"Pip protegido por uma linha brilhante enquanto abelhas se aproximam",eyebrow:"Resgates do Prado Luz do Trevo",pitch:"Desenhe linhas de néctar, conserte pontos fracos durante cada onda e proteja Pip.",start:"Começar",guideLabel:"Guia do jogo",guideKicker:"Guia de jogo original WeightPlay",guideTitle:"Proteja Pip com a linha forte mais curta",howTitle:"Como jogar",rulesTitle:"Regras e resultados",progressTitle:"Trinta rotas do prado",tipsTitle:"Dicas práticas",saveTitle:"Progresso e privacidade",faqTitle:"Perguntas frequentes",backMain:"Voltar ao início",backStages:"Voltar às fases",stageRailLabel:"Seleção de rotas",stages:"Fases",stage:"Fase {n}",locked:"Bloqueada",cleared:"Protegido",stars:"{n} estrelas",progress:"{done} / 30 protegidos · {stars} estrelas",chapter:"Capítulo {n}",time:"Tempo",nectar:"Néctar",pause:"Pausa",boardLabel:"Desenhe uma barreira para proteger Pip",drawHint:"Desenhe para criar o escudo de Pip",clear:"Apagar linhas",restart:"Reiniciar",ready:"Desenhe a primeira barreira",waveStarted:"As abelhas estão voando — conserte os pontos fracos!",lowNectar:"Pouco néctar",barrierHit:"A barreira está enfraquecendo!",protected:"Pip está seguro!",touched:"Uma abelha chegou a Pip. Tente outro escudo.",leaveTitle:"Sair do prado?",continue:"Continuar",returnStages:"Voltar às fases",pauseTitle:"Prado pausado",resume:"Retomar",resultKicker:"Relatório do prado",winTitle:"Pip está protegido!",failTitle:"O escudo abriu",newBest:"Novo melhor escudo!",best:"Melhor: {stars} estrelas",next:"Próxima fase",retry:"Repetir",tutorialTitle:"Desenhe, observe e conserte",tutorialStart:"Proteger Pip",close:"Fechar"};
  const fr={...en,loading:"Réveil de la prairie aux trèfles…",title:"Bouclier de Miel Animal",language:"Langue",backLobby:"Retour à WeightPlay",posterAlt:"Pip protégé par une ligne lumineuse à l'approche des abeilles",eyebrow:"Sauvetages de la Prairie Trèfle-Lumière",pitch:"Tracez des lignes de nectar, réparez leurs faiblesses pendant chaque vague et protégez Pip.",start:"Commencer",guideLabel:"Guide du jeu",guideKicker:"Guide du jeu original WeightPlay",guideTitle:"Protégez Pip avec la ligne solide la plus courte",howTitle:"Comment jouer",rulesTitle:"Règles et résultats",progressTitle:"Trente parcours",tipsTitle:"Conseils pratiques",saveTitle:"Sauvegarde et vie privée",faqTitle:"FAQ",backMain:"Retour à l'accueil",backStages:"Retour aux niveaux",stageRailLabel:"Sélection des parcours",stages:"Niveaux",stage:"Niveau {n}",locked:"Verrouillé",cleared:"Protégé",stars:"{n} étoiles",progress:"{done} / 30 protégés · {stars} étoiles",chapter:"Chapitre {n}",time:"Temps",nectar:"Nectar",pause:"Pause",boardLabel:"Tracez une barrière pour protéger Pip",drawHint:"Dessinez pour créer le bouclier de Pip",clear:"Effacer les lignes",restart:"Recommencer",objective:"Protégez Pip pendant {n} secondes",ready:"Tracez la première barrière",waveStarted:"Les abeilles volent — réparez les faiblesses !",lowNectar:"Nectar presque épuisé",barrierHit:"Cette barrière faiblit !",protected:"Pip est en sécurité !",touched:"Une abeille a atteint Pip. Essayez un autre bouclier.",leaveTitle:"Quitter la prairie ?",continue:"Continuer",returnStages:"Retour aux niveaux",pauseTitle:"Prairie en pause",resume:"Reprendre",resultKicker:"Rapport de prairie",winTitle:"Pip est protégé !",failTitle:"Le bouclier s'est ouvert",newBest:"Nouveau meilleur bouclier !",best:"Record : {stars} étoiles",next:"Niveau suivant",retry:"Rejouer",tutorialTitle:"Tracez, observez, réparez",tutorialStart:"Protéger Pip",close:"Fermer"};
  const de={...en,loading:"Die Kleewiese erwacht…",title:"Tierischer Honigschild",language:"Sprache",backLobby:"Zurück zu WeightPlay",posterAlt:"Pip hinter einer leuchtenden Linie, während Bienen näherkommen",eyebrow:"Rettungsrätsel auf der Kleelicht-Wiese",pitch:"Zeichne Nektarlinien, repariere Schwachstellen während jeder Welle und beschütze Pip.",start:"Spiel starten",guideLabel:"Spielanleitung",guideKicker:"Originale WeightPlay-Spielanleitung",guideTitle:"Beschütze Pip mit der kürzesten starken Linie",howTitle:"So wird gespielt",rulesTitle:"Regeln und Ergebnis",progressTitle:"Dreißig Wiesenrouten",tipsTitle:"Praktische Tipps",saveTitle:"Speichern und Datenschutz",faqTitle:"FAQ",backMain:"Zurück zum Hauptmenü",backStages:"Zurück zu Stufen",stageRailLabel:"Wiesenstufen wählen",stages:"Stufen",stage:"Stufe {n}",locked:"Gesperrt",cleared:"Geschützt",stars:"{n} Sterne",progress:"{done} / 30 geschützt · {stars} Sterne",chapter:"Kapitel {n}",time:"Zeit",nectar:"Nektar",pause:"Pause",boardLabel:"Zeichne eine Barriere zum Schutz von Pip",drawHint:"Zeichne Pips Schutzschild",clear:"Linien löschen",restart:"Neustart",objective:"Beschütze Pip {n} Sekunden",ready:"Zeichne die erste Barriere",waveStarted:"Die Bienen fliegen — repariere Schwachstellen!",lowNectar:"Wenig Nektar",barrierHit:"Diese Barriere wird schwach!",protected:"Pip ist sicher!",touched:"Eine Biene erreichte Pip. Probiere einen anderen Schild.",leaveTitle:"Diese Wiese verlassen?",continue:"Weiterspielen",returnStages:"Zu den Stufen",pauseTitle:"Wiese pausiert",resume:"Fortsetzen",resultKicker:"Wiesenbericht",winTitle:"Pip ist geschützt!",failTitle:"Der Schild ist offen",newBest:"Neuer bester Schild!",best:"Bestwert: {stars} Sterne",next:"Nächste Stufe",retry:"Wiederholen",tutorialTitle:"Zeichnen, beobachten, reparieren",tutorialStart:"Pip beschützen",close:"Schließen"};
  const it={...en,loading:"Risveglio del prato di trifogli…",title:"Scudo di Miele Animale",language:"Lingua",backLobby:"Torna a WeightPlay",posterAlt:"Pip protetto da una linea luminosa mentre arrivano le api",eyebrow:"Salvataggi del Prato Trifoglio Luce",pitch:"Disegna linee di nettare, ripara i punti deboli durante ogni ondata e proteggi Pip.",start:"Inizia",guideLabel:"Guida al gioco",guideKicker:"Guida al gioco originale WeightPlay",guideTitle:"Proteggi Pip con la linea forte più corta",howTitle:"Come giocare",rulesTitle:"Regole e risultati",progressTitle:"Trenta percorsi",tipsTitle:"Consigli pratici",saveTitle:"Salvataggio e privacy",faqTitle:"Domande frequenti",backMain:"Torna al menu",backStages:"Torna ai livelli",stageRailLabel:"Selezione percorsi",stages:"Livelli",stage:"Livello {n}",locked:"Bloccato",cleared:"Protetto",stars:"{n} stelle",progress:"{done} / 30 protetti · {stars} stelle",chapter:"Capitolo {n}",time:"Tempo",nectar:"Nettare",pause:"Pausa",boardLabel:"Disegna una barriera per proteggere Pip",drawHint:"Disegna per creare lo scudo di Pip",clear:"Cancella linee",restart:"Ricomincia",objective:"Proteggi Pip per {n} secondi",ready:"Disegna la prima barriera",waveStarted:"Le api stanno volando: ripara i punti deboli!",lowNectar:"Poco nettare",barrierHit:"La barriera si sta indebolendo!",protected:"Pip è al sicuro!",touched:"Un'ape ha raggiunto Pip. Prova un altro scudo.",leaveTitle:"Lasciare il prato?",continue:"Continua",returnStages:"Torna ai livelli",pauseTitle:"Prato in pausa",resume:"Riprendi",resultKicker:"Rapporto del prato",winTitle:"Pip è protetto!",failTitle:"Lo scudo si è aperto",newBest:"Nuovo scudo migliore!",best:"Migliore: {stars} stelle",next:"Livello successivo",retry:"Rigioca",tutorialTitle:"Disegna, osserva e ripara",tutorialStart:"Proteggi Pip",close:"Chiudi"};
  const ja={...en,loading:"クローバー草原を起こしています…",title:"どうぶつハニーシールド",language:"言語",backLobby:"WeightPlayへ戻る",posterAlt:"ハチが近づく中、光る線に守られるピップ",eyebrow:"クローバーライト草原の救助パズル",pitch:"蜜の線を描き、群れの途中で弱い所を直して子犬のピップを守ろう。",start:"ゲーム開始",guideLabel:"ゲームガイド",guideKicker:"WeightPlay オリジナルゲームガイド",guideTitle:"短く強い線でピップを守ろう",howTitle:"遊び方",rulesTitle:"ルールと結果",progressTitle:"草原の30ルート",tipsTitle:"実用ヒント",saveTitle:"保存とプライバシー",faqTitle:"よくある質問",backMain:"メインへ戻る",backStages:"ステージへ戻る",stageRailLabel:"草原ステージ選択",stages:"ステージ",stage:"ステージ {n}",locked:"ロック中",cleared:"保護完了",stars:"星 {n}",progress:"保護 {done} / 30・星 {stars}",chapter:"チャプター {n}",chapters:["はじめての飛行","二つの花道","石のアンカー","クローバーの風","こわれやすい隙間","ハニーガード試練"],time:"時間",nectar:"蜜",pause:"一時停止",boardLabel:"蜜の線を描いてピップを守る",drawHint:"好きな場所に描いてシールドを作ろう",clear:"線を消す",restart:"やり直す",objective:"{n} 秒間ピップを守る",ready:"最初のバリアを描こう",waveStarted:"ハチが飛んだ！弱い所を直そう",lowNectar:"蜜が残り少ない",barrierHit:"バリアが弱くなっている！",protected:"ピップは安全！",touched:"ハチがピップに届きました。別の形を試そう。",leaveTitle:"草原を離れますか？",continue:"続ける",returnStages:"ステージへ戻る",pauseTitle:"草原を一時停止",resume:"再開",resultKicker:"草原レポート",winTitle:"ピップを守った！",failTitle:"シールドに隙間ができた",newBest:"新しいベストシールド！",best:"ベスト：星 {stars}",next:"次のステージ",retry:"もう一度",tutorialTitle:"描いて、見て、直そう",tutorialStart:"ピップを守る",close:"閉じる"};
  const ko={...en,loading:"클로버 초원을 깨우는 중…",title:"애니멀 허니 실드",language:"언어",backLobby:"WeightPlay로 돌아가기",posterAlt:"벌이 다가올 때 빛나는 선 뒤에 숨은 핍",eyebrow:"클로버라이트 초원 구조 퍼즐",pitch:"꿀빛 선을 그리고 벌 떼가 오는 동안 약한 곳을 고쳐 강아지 핍을 지키세요.",start:"게임 시작",guideLabel:"게임 안내",guideKicker:"WeightPlay 오리지널 게임 안내",guideTitle:"가장 짧고 튼튼한 선으로 핍을 지키세요",howTitle:"플레이 방법",rulesTitle:"규칙과 결과",progressTitle:"초원 경로 30개",tipsTitle:"실전 팁",saveTitle:"저장 및 개인정보",faqTitle:"자주 묻는 질문",backMain:"메인으로",backStages:"스테이지로",stageRailLabel:"초원 스테이지 선택",stages:"스테이지",stage:"스테이지 {n}",locked:"잠김",cleared:"보호 완료",stars:"별 {n}개",progress:"보호 {done} / 30 · 별 {stars}개",chapter:"챕터 {n}",time:"시간",nectar:"꽃꿀",pause:"일시정지",boardLabel:"꽃꿀 방어선을 그려 핍을 보호하세요",drawHint:"원하는 곳에 그려 핍의 방패를 만드세요",clear:"선 지우기",restart:"다시 시작",objective:"{n}초 동안 핍 보호",ready:"첫 방어선을 그리세요",waveStarted:"벌이 날아옵니다. 약한 곳을 고치세요!",lowNectar:"꽃꿀이 부족합니다",barrierHit:"방어선이 약해지고 있어요!",protected:"핍이 안전해요!",touched:"벌이 핍에게 닿았습니다. 다른 방패를 시도하세요.",leaveTitle:"초원을 떠날까요?",continue:"계속하기",returnStages:"스테이지로",pauseTitle:"초원 일시정지",resume:"계속",resultKicker:"초원 보고서",winTitle:"핍을 지켰어요!",failTitle:"방패가 열렸어요",newBest:"새로운 최고 방패!",best:"최고: 별 {stars}개",next:"다음 스테이지",retry:"다시 하기",tutorialTitle:"그리고, 보고, 고치기",tutorialStart:"핍 보호하기",close:"닫기"};
  const ru={...en,loading:"Пробуждаем клеверный луг…",title:"Звериный медовый щит",language:"Язык",backLobby:"Назад в WeightPlay",posterAlt:"Пип под защитой светящейся линии, пока приближаются пчёлы",eyebrow:"Спасательные головоломки Клеверного луга",pitch:"Рисуйте нектарные линии, чините слабые места во время волн и защищайте щенка Пипа.",start:"Начать игру",guideLabel:"Руководство",guideKicker:"Руководство к оригинальной игре WeightPlay",guideTitle:"Защитите Пипа самой короткой прочной линией",howTitle:"Как играть",rulesTitle:"Правила и результат",progressTitle:"Тридцать маршрутов",tipsTitle:"Полезные советы",saveTitle:"Сохранение и конфиденциальность",faqTitle:"Вопросы",backMain:"В главное меню",backStages:"К этапам",stageRailLabel:"Выбор этапа",stages:"Этапы",stage:"Этап {n}",locked:"Закрыто",cleared:"Защищён",stars:"Звёзд: {n}",progress:"Защищено {done} / 30 · звёзд {stars}",chapter:"Глава {n}",time:"Время",nectar:"Нектар",pause:"Пауза",boardLabel:"Нарисуйте преграду для защиты Пипа",drawHint:"Рисуйте, чтобы создать щит Пипа",clear:"Стереть линии",restart:"Заново",objective:"Защищайте Пипа {n} секунд",ready:"Нарисуйте первую преграду",waveStarted:"Пчёлы летят — чините слабые места!",lowNectar:"Мало нектара",barrierHit:"Преграда слабеет!",protected:"Пип в безопасности!",touched:"Пчела достигла Пипа. Попробуйте другой щит.",leaveTitle:"Покинуть луг?",continue:"Продолжить",returnStages:"К этапам",pauseTitle:"Луг на паузе",resume:"Продолжить",resultKicker:"Отчёт луга",winTitle:"Пип защищён!",failTitle:"Щит раскрылся",newBest:"Новый лучший щит!",best:"Лучшее: {stars} звёзд",next:"Следующий этап",retry:"Снова",tutorialTitle:"Рисуйте, следите и чините",tutorialStart:"Защитить Пипа",close:"Закрыть"};
  const hi={...en,loading:"क्लोवर मैदान जाग रहा है…",title:"एनिमल हनी शील्ड",language:"भाषा",backLobby:"WeightPlay पर वापस जाएँ",posterAlt:"मधुमक्खियों के पास आने पर चमकती रेखा से सुरक्षित पिप",eyebrow:"क्लोवरलाइट मैदान बचाव पहेलियाँ",pitch:"नेक्टर रेखाएँ बनाएँ, हर लहर में कमजोर जगह सुधारें और पिल्ले पिप को सुरक्षित रखें।",start:"खेल शुरू करें",guideLabel:"खेल मार्गदर्शिका",guideKicker:"WeightPlay मूल खेल मार्गदर्शिका",guideTitle:"सबसे छोटी मजबूत रेखा से पिप को बचाएँ",howTitle:"कैसे खेलें",rulesTitle:"नियम और परिणाम",progressTitle:"मैदान के 30 रास्ते",tipsTitle:"उपयोगी सुझाव",saveTitle:"सेव और गोपनीयता",faqTitle:"सामान्य प्रश्न",backMain:"मुख्य स्क्रीन पर",backStages:"चरणों पर",stageRailLabel:"मैदान चरण चयन",stages:"चरण",stage:"चरण {n}",locked:"बंद",cleared:"सुरक्षित",stars:"{n} सितारे",progress:"{done} / 30 सुरक्षित · {stars} सितारे",chapter:"अध्याय {n}",time:"समय",nectar:"नेक्टर",pause:"रोकें",boardLabel:"पिप को बचाने के लिए नेक्टर दीवार बनाएँ",drawHint:"पिप की ढाल बनाने के लिए रेखा खींचें",clear:"रेखाएँ मिटाएँ",restart:"फिर शुरू",objective:"पिप को {n} सेकंड बचाएँ",ready:"पहली दीवार बनाएँ",waveStarted:"मधुमक्खियाँ उड़ रही हैं—कमजोर जगह सुधारें!",lowNectar:"नेक्टर कम है",barrierHit:"दीवार कमजोर हो रही है!",protected:"पिप सुरक्षित है!",touched:"मधुमक्खी पिप तक पहुँच गई। दूसरी ढाल आजमाएँ।",leaveTitle:"मैदान छोड़ें?",continue:"जारी रखें",returnStages:"चरणों पर लौटें",pauseTitle:"मैदान रुका है",resume:"फिर शुरू",resultKicker:"मैदान रिपोर्ट",winTitle:"पिप सुरक्षित है!",failTitle:"ढाल खुल गई",newBest:"नई सर्वश्रेष्ठ ढाल!",best:"सर्वश्रेष्ठ: {stars} सितारे",next:"अगला चरण",retry:"फिर खेलें",tutorialTitle:"बनाएँ, देखें और सुधारें",tutorialStart:"पिप को बचाएँ",close:"बंद करें"};
  const ar={...en,loading:"جارٍ إيقاظ مرج البرسيم…",title:"درع العسل الحيواني",language:"اللغة",backLobby:"العودة إلى WeightPlay",posterAlt:"بيب محمي بخط مضيء مع اقتراب النحل",eyebrow:"ألغاز إنقاذ مرج ضوء البرسيم",pitch:"ارسم خطوط الرحيق وأصلح نقاط الضعف أثناء كل موجة واحمِ الجرو بيب.",start:"ابدأ اللعبة",guideLabel:"دليل اللعبة",guideKicker:"دليل لعبة WeightPlay الأصلية",guideTitle:"احمِ بيب بأقصر خط قوي",howTitle:"طريقة اللعب",rulesTitle:"القواعد والنتائج",progressTitle:"ثلاثون مسارًا في المرج",tipsTitle:"نصائح عملية",saveTitle:"الحفظ والخصوصية",faqTitle:"الأسئلة الشائعة",backMain:"العودة للرئيسية",backStages:"العودة للمراحل",stageRailLabel:"اختيار مراحل المرج",stages:"المراحل",stage:"المرحلة {n}",locked:"مغلقة",cleared:"محمي",stars:"{n} نجوم",progress:"تمت حماية {done} / 30 · {stars} نجوم",chapter:"الفصل {n}",time:"الوقت",nectar:"الرحيق",pause:"إيقاف",boardLabel:"ارسم حاجز رحيق لحماية بيب",drawHint:"ارسم في أي مكان لبناء درع بيب",clear:"امسح الخطوط",restart:"إعادة",objective:"احمِ بيب لمدة {n} ثوانٍ",ready:"ارسم الحاجز الأول",waveStarted:"النحل يطير—أصلح نقاط الضعف!",lowNectar:"الرحيق منخفض",barrierHit:"الحاجز يضعف!",protected:"بيب بأمان!",touched:"وصلت نحلة إلى بيب. جرّب درعًا آخر.",leaveTitle:"مغادرة المرج؟",continue:"متابعة",returnStages:"العودة للمراحل",pauseTitle:"المرج متوقف",resume:"استئناف",resultKicker:"تقرير المرج",winTitle:"بيب محمي!",failTitle:"انفتح الدرع",newBest:"أفضل درع جديد!",best:"الأفضل: {stars} نجوم",next:"المرحلة التالية",retry:"إعادة اللعب",tutorialTitle:"ارسم وراقب وأصلح",tutorialStart:"احمِ بيب",close:"إغلاق"};
  Object.assign(zhHans,{
    guideIntro:"皮普走到苜蓿光原的蜂巢旁。蜂群飞行时画出屏障，并在它们碰到小犬前修补缺口。",
    how1:"在草原上拖动，画出发光花蜜屏障。",how2:"松开后蜂群开始飞行；波次进行中仍可继续补画。",how3:"在倒计时结束前，不让任何蜜蜂碰到皮普。",
    rulesText:"画线会消耗花蜜，蜜蜂撞击也会让线变弱。蜜蜂碰到皮普即失败；安全撑过倒计时即可过关，短线与剩余花蜜会带来更多星星。",
    progressText:"六个章节加入更多蜂巢、分岔来向、石头锚点、移动风势、脆弱缺口与综合波次。过关就能解锁下一关。",
    tipsText:"把短曲线固定在石头之间，给皮普留下空间，并注意变红的弱点。小幅补线通常比再画一整圈更有效。",
    saveText:"解锁关卡与最佳星级只保存在这个浏览器，不需账号、上传或个人信息。",
    faq1q:"蜜蜂出发后还能画线吗？",faq1a:"可以。只要还有花蜜，实时修补就是游戏核心。",faq2q:"蜜蜂会受伤吗？",faq2a:"不会。花蜜屏障只会轻轻地把受惊蜂群弹回花朵方向。",faq3q:"接着适合玩什么？",faq3a:"想练细致描线可玩《动物一笔画》，想挑战大型防守可玩《动物守护庭院》。",
    chapters:["初次飞行","双向花径","石头锚点","苜蓿暖风","脆弱缺口","花蜜守护试炼"],chapterRules:["用短屏障挡住第一波蜂群。","观察两个来向，优先修补较弱的一侧。","利用草原石头固定坚固防线。","暖风改变路线时立即应对。","在更长波次中谨慎分配花蜜。","综合所有规则，完整保护皮普。"],
    lineStatus:"已画 {used} · 剩余 {left} 花蜜",leaveText:"继续会保留并冻结当前波次；返回关卡只会结束本次挑战。",pauseText:"休息期间蜂群波次会保持冻结。",
    winText:"第 {stage} 关安全完成，剩余 {nectar} 花蜜。",failText:"在蜜蜂到达前，先修补第一个红色缺口。",
    tutorial1:"在皮普与蜂巢之间画一道短屏障。",tutorial2:"松开后波次开始；红色闪光代表防线正在变弱。",tutorial3:"在缺口形成前，再补上一小段线。"
  });
  Object.assign(ja,{
    guideIntro:"ピップはクローバーライト草原の巣のそばに迷い込みました。ハチが飛んでいる間に壁を描き、子犬に届く前に隙間を補強します。",
    how1:"草原をドラッグして光る蜜のバリアを描きます。",how2:"指を離すとハチの波が始まります。波の途中でも線を追加できます。",how3:"ハチをピップに触れさせず、タイマーがゼロになるまで守ります。",
    rulesText:"線は蜜を消費し、ハチが当たると弱くなります。ピップに触れられると失敗です。短い線と残った蜜ほど多くの星を獲得します。",
    progressText:"6章30ステージで、巣の追加、二方向、石のアンカー、風、弱い隙間、複合ウェーブが登場します。",
    tipsText:"石の間に短い曲線を固定し、ピップの周りに余裕を残しましょう。赤く光る場所だけを小さく直すのが効果的です。",
    saveText:"解放ステージと最高の星はこのブラウザーだけに保存されます。アカウントや個人情報は不要です。",
    faq1q:"ハチが飛び始めた後も描けますか？",faq1a:"はい。蜜が残っている間の修理がゲームの中心です。",faq2q:"ハチは傷つきますか？",faq2a:"いいえ。蜜のバリアは驚いたハチを花の方向へ優しく跳ね返します。",faq3q:"次におすすめのゲームは？",faq3a:"丁寧ななぞりなら『どうぶつ一筆書き』、大きな防衛なら『アニマル・ガード・ヤード』がおすすめです。",
    chapterRules:["1回の優しい波を短い壁で防ぎます。","二方向を読み、弱い側を先に修理します。","草原の石を強いアンカーに使います。","暖かい風で進路が曲がったら反応します。","長い波で蜜を慎重に使います。","すべてのルールを組み合わせてピップを守ります。"],
    lineStatus:"描画 {used}・蜜 {left}",leaveText:"続けると波をそのまま凍結します。ステージへ戻ると今回の挑戦だけが終了します。",pauseText:"休憩中はハチの波が完全に止まります。",
    winText:"ステージ {stage} を守りました。蜜は {nectar} 残りました。",failText:"ハチが届く前に最初の赤い隙間を直しましょう。",
    tutorial1:"ピップと巣の間に短い壁を描きます。",tutorial2:"指を離すと波が開始。赤い点滅は線が弱い合図です。",tutorial3:"隙間が開く前に短い線を追加します。"
  });
  Object.assign(ko,{
    guideIntro:"핍이 클로버라이트 초원의 벌집 가까이 왔습니다. 벌이 나는 동안 방어선을 그리고 강아지에게 닿기 전에 틈을 보강하세요.",
    how1:"초원을 드래그해 빛나는 꽃꿀 방어선을 그리세요.",how2:"손을 떼면 벌 떼가 출발하며, 진행 중에도 선을 더 그릴 수 있습니다.",how3:"벌이 핍에게 닿지 않게 타이머가 0이 될 때까지 버티세요.",
    rulesText:"선을 그리면 꽃꿀이 들고 벌이 부딪히면 약해집니다. 핍이 닿으면 실패합니다. 짧은 선과 남은 꽃꿀이 많을수록 별을 더 받습니다.",
    progressText:"여섯 챕터에 추가 벌집, 양쪽 접근, 돌 고정점, 바람, 약한 틈, 종합 파도가 등장합니다. 클리어할 때마다 다음 길이 열립니다.",
    tipsText:"돌 사이에 짧은 곡선을 고정하고 핍 주변에 공간을 남기세요. 빨갛게 빛나는 부분만 짧게 고치는 편이 좋습니다.",
    saveText:"열린 스테이지와 최고 별은 이 브라우저에만 저장됩니다. 계정이나 개인정보가 필요하지 않습니다.",
    faq1q:"벌이 출발한 뒤에도 그릴 수 있나요?",faq1a:"네. 꽃꿀이 남아 있는 동안 실시간 수리가 핵심입니다.",faq2q:"벌이 다치나요?",faq2a:"아니요. 꽃꿀 방어선은 놀란 벌을 꽃 쪽으로 부드럽게 튕겨 냅니다.",faq3q:"다음에는 무엇을 플레이하나요?",faq3a:"정교한 선 긋기는 애니멀 원 라인, 더 큰 방어는 애니멀 가드 야드를 추천합니다.",
    chapters:["첫 비행","두 갈래 꽃길","돌 고정점","클로버 바람","약한 틈","허니가드 숙련"],chapterRules:["짧은 방어선으로 첫 파도를 막으세요.","두 방향을 읽고 약한 쪽을 먼저 고치세요.","초원의 돌을 튼튼한 고정점으로 쓰세요.","따뜻한 바람이 벌의 길을 바꾸면 대응하세요.","긴 파도에서 꽃꿀을 신중히 나누세요.","모든 규칙을 합쳐 핍을 안전하게 지키세요."],
    lineStatus:"그린 양 {used} · 꽃꿀 {left}",leaveText:"계속하기는 현재 파도를 그대로 멈춰 둡니다. 스테이지로 돌아가면 이번 도전만 끝납니다.",pauseText:"쉬는 동안 벌 떼는 완전히 멈춥니다.",
    winText:"스테이지 {stage}를 지켰습니다. 꽃꿀 {nectar}가 남았습니다.",failText:"벌이 핍에게 닿기 전에 첫 번째 빨간 틈을 고치세요.",
    tutorial1:"핍과 벌집 사이에 짧은 방어선을 그리세요.",tutorial2:"손을 떼면 파도가 시작됩니다. 빨간 빛은 선이 약해졌다는 뜻입니다.",tutorial3:"틈이 열리기 전에 짧은 선을 하나 더 그리세요."
  });
  Object.assign(es,{
    guideIntro:"Pip se acercó a las colmenas del Prado Trébol Luz. Dibuja barreras mientras vuelan las abejas y refuerza las aberturas antes de que alcancen al cachorro.",
    how1:"Arrastra por el prado para dibujar una barrera luminosa de néctar.",how2:"Suelta para iniciar la oleada; puedes seguir dibujando segmentos mientras avanza.",how3:"Resiste hasta que el tiempo llegue a cero sin que una abeja toque a Pip.",
    rulesText:"Cada línea consume néctar y se debilita con los impactos. Si una abeja toca a Pip, fallas. Las líneas cortas y el néctar restante dan más estrellas.",
    progressText:"Seis capítulos añaden más colmenas, ataques divididos, anclajes de piedra, ráfagas, huecos frágiles y oleadas combinadas.",
    tipsText:"Ancla curvas cortas entre piedras, deja espacio junto a Pip y vigila las zonas rojas. Una reparación pequeña suele superar a otro círculo completo.",
    saveText:"Los niveles y mejores estrellas se guardan solo en este navegador. No se necesita cuenta ni información personal.",
    faq1q:"¿Puedo dibujar cuando las abejas ya vuelan?",faq1a:"Sí. Las reparaciones en vivo son el centro del juego mientras quede néctar.",faq2q:"¿Las abejas se lastiman?",faq2a:"No. Las barreras las hacen rebotar suavemente hacia las flores.",faq3q:"¿Qué puedo jugar después?",faq3a:"Prueba One Line para trazos precisos o Animal Guard Yard para una defensa mayor.",
    chapterRules:["Aprende barreras cortas contra una oleada suave.","Lee dos direcciones y repara primero el lado débil.","Usa las piedras como anclajes firmes.","Reacciona cuando el viento cambia la ruta.","Administra el néctar en oleadas más largas.","Combina todas las reglas para proteger a Pip."],
    lineStatus:"{used} dibujado · {left} de néctar",leaveText:"Continuar conserva esta oleada congelada. Volver a niveles termina solo este intento.",winText:"El nivel {stage} quedó seguro con {nectar} de néctar.",failText:"Repara el primer hueco rojo antes de que lleguen las abejas.",
    tutorial1:"Dibuja una barrera corta entre Pip y la colmena.",tutorial2:"Al soltar comienza la oleada. Los destellos rojos señalan una línea débil.",tutorial3:"Añade otro segmento corto antes de que se abra un hueco."
  });
  Object.assign(pt,{
    guideIntro:"Pip chegou perto das colmeias do Prado Luz do Trevo. Desenhe barreiras enquanto as abelhas voam e reforce as aberturas antes que alcancem o filhote.",
    how1:"Arraste pelo prado para desenhar uma barreira luminosa de néctar.",how2:"Solte para iniciar a onda; continue desenhando segmentos enquanto ela acontece.",how3:"Resista até o tempo zerar sem deixar uma abelha tocar Pip.",
    rulesText:"Cada linha gasta néctar e enfraquece com impactos. Se uma abelha tocar Pip, a tentativa falha. Linhas curtas e néctar restante dão mais estrelas.",
    progressText:"Seis capítulos adicionam colmeias, ataques divididos, âncoras de pedra, rajadas, brechas frágeis e ondas combinadas.",
    tipsText:"Prenda curvas curtas entre pedras, deixe espaço perto de Pip e observe as partes vermelhas. Um pequeno conserto costuma ser melhor que outro círculo inteiro.",
    saveText:"Fases e melhores estrelas ficam apenas neste navegador. Nenhuma conta ou informação pessoal é necessária.",
    faq1q:"Posso desenhar depois que as abelhas saem?",faq1a:"Sim. O conserto ao vivo é o centro do jogo enquanto houver néctar.",faq2q:"As abelhas se machucam?",faq2a:"Não. As barreiras as fazem voltar suavemente para as flores.",faq3q:"O que jogar depois?",faq3a:"Tente One Line para traços cuidadosos ou Animal Guard Yard para uma defesa maior.",
    chapterRules:["Aprenda barreiras curtas contra uma onda leve.","Leia duas direções e conserte primeiro o lado fraco.","Use pedras como âncoras firmes.","Reaja quando o vento mudar a rota.","Gerencie o néctar em ondas longas.","Combine todas as regras para proteger Pip."],
    lineStatus:"{used} desenhado · {left} de néctar",leaveText:"Continuar mantém esta onda congelada. Voltar às fases encerra só esta tentativa.",winText:"A fase {stage} ficou segura com {nectar} de néctar.",failText:"Conserte a primeira brecha vermelha antes que as abelhas cheguem.",
    tutorial1:"Desenhe uma barreira curta entre Pip e a colmeia.",tutorial2:"Ao soltar, a onda começa. Brilhos vermelhos mostram uma linha fraca.",tutorial3:"Adicione outro segmento curto antes que a brecha abra."
  });
  Object.assign(fr,{
    guideIntro:"Pip s'est approché des ruches de la Prairie Trèfle-Lumière. Tracez des barrières pendant le vol des abeilles et renforcez les ouvertures avant qu'elles atteignent le chiot.",
    how1:"Faites glisser le doigt sur la prairie pour tracer une barrière de nectar.",how2:"Relâchez pour lancer la vague ; vous pouvez encore tracer des segments pendant celle-ci.",how3:"Tenez jusqu'à zéro sans qu'une abeille touche Pip.",
    rulesText:"Chaque ligne dépense du nectar et faiblit sous les chocs. Si une abeille touche Pip, la tentative échoue. Les lignes courtes et le nectar restant donnent plus d'étoiles.",
    progressText:"Six chapitres ajoutent des ruches, des approches divisées, des ancrages de pierre, des rafales, des brèches fragiles et des vagues mixtes.",
    tipsText:"Ancrez de petites courbes entre les pierres, laissez de l'espace autour de Pip et surveillez les zones rouges. Une petite réparation vaut souvent mieux qu'un cercle entier.",
    saveText:"Les niveaux et records restent dans ce navigateur. Aucun compte ni renseignement personnel n'est nécessaire.",
    faq1q:"Puis-je dessiner après le départ des abeilles ?",faq1a:"Oui. Les réparations en direct sont essentielles tant qu'il reste du nectar.",faq2q:"Les abeilles sont-elles blessées ?",faq2a:"Non. Les barrières les repoussent doucement vers les fleurs.",faq3q:"À quoi jouer ensuite ?",faq3a:"Essayez One Line pour le tracé précis ou Animal Guard Yard pour une défense plus vaste.",
    chapters:["Premier vol","Sentiers doubles","Ancrages de pierre","Rafales de trèfle","Brèches fragiles","Maîtrise Gardemiel"],chapterRules:["Apprenez une barrière courte contre une vague douce.","Lisez deux approches et réparez d'abord le côté faible.","Utilisez les pierres comme ancrages solides.","Réagissez quand le vent dévie les abeilles.","Gérez le nectar pendant les longues vagues.","Combinez toutes les règles pour protéger Pip."],
    lineStatus:"{used} tracé · {left} nectar",leaveText:"Continuer conserve la vague gelée. Revenir aux niveaux termine seulement cet essai.",pauseText:"La vague reste entièrement immobile pendant votre pause.",
    winText:"Le niveau {stage} est sûr avec {nectar} de nectar restant.",failText:"Réparez la première brèche rouge avant l'arrivée des abeilles.",
    tutorial1:"Tracez une petite barrière entre Pip et la ruche.",tutorial2:"Relâcher lance la vague. Un éclat rouge signale une ligne faible.",tutorial3:"Ajoutez un petit segment avant l'ouverture d'une brèche."
  });
  Object.assign(de,{
    guideIntro:"Pip ist den Bienenstöcken der Kleelicht-Wiese zu nahe gekommen. Zeichne Barrieren, während die Bienen fliegen, und schließe Lücken rechtzeitig.",
    how1:"Ziehe über die Wiese, um eine leuchtende Nektarbarriere zu zeichnen.",how2:"Loslassen startet die Welle; währenddessen kannst du weitere Abschnitte zeichnen.",how3:"Halte bis zum Ablauf der Zeit durch, ohne dass eine Biene Pip berührt.",
    rulesText:"Jede Linie kostet Nektar und wird durch Treffer schwächer. Berührt eine Biene Pip, ist der Versuch verloren. Kurze Linien und übriger Nektar bringen mehr Sterne.",
    progressText:"Sechs Kapitel ergänzen weitere Stöcke, geteilte Anflüge, Steinanker, Böen, brüchige Lücken und gemischte Wellen.",
    tipsText:"Verankere kurze Kurven zwischen Steinen, lasse Platz um Pip und beobachte rote Stellen. Eine kleine Reparatur ist oft besser als ein zweiter Kreis.",
    saveText:"Stufen und Beststerne bleiben nur in diesem Browser. Konto und persönliche Daten sind nicht nötig.",
    faq1q:"Kann ich nach dem Start der Bienen zeichnen?",faq1a:"Ja. Live-Reparaturen sind der Kern des Spiels, solange Nektar bleibt.",faq2q:"Werden die Bienen verletzt?",faq2a:"Nein. Die Barrieren lenken sie sanft zurück zu den Blumen.",faq3q:"Was kann ich danach spielen?",faq3a:"Probiere One Line für genaues Zeichnen oder Animal Guard Yard für größere Verteidigung.",
    chapters:["Erster Flug","Doppelte Pfade","Steinanker","Kleeböen","Brüchige Lücken","Honigwacht-Meisterschaft"],chapterRules:["Lerne kurze Barrieren gegen eine sanfte Welle.","Lies zwei Anflüge und repariere zuerst die schwache Seite.","Nutze Wiesensteine als feste Anker.","Reagiere, wenn Böen den Flugweg ändern.","Teile den Nektar in langen Wellen ein.","Verbinde alle Regeln und beschütze Pip."],
    lineStatus:"{used} gezeichnet · {left} Nektar",leaveText:"Fortsetzen hält diese Welle eingefroren. Die Rückkehr zu Stufen beendet nur diesen Versuch.",pauseText:"Die Bienenwelle bleibt während der Pause vollständig stehen.",
    winText:"Stufe {stage} blieb sicher; {nectar} Nektar ist übrig.",failText:"Repariere die erste rote Lücke, bevor die Bienen Pip erreichen.",
    tutorial1:"Zeichne eine kurze Barriere zwischen Pip und dem Stock.",tutorial2:"Loslassen startet die Welle. Rotes Blinken zeigt eine schwache Linie.",tutorial3:"Zeichne einen kurzen Abschnitt, bevor eine Lücke entsteht."
  });
  Object.assign(it,{
    guideIntro:"Pip si è avvicinato agli alveari del Prato Trifoglio Luce. Disegna barriere mentre le api volano e rinforza le aperture prima che raggiungano il cucciolo.",
    how1:"Trascina sul prato per disegnare una barriera luminosa di nettare.",how2:"Rilascia per iniziare l'ondata; puoi continuare a disegnare segmenti mentre procede.",how3:"Resisti fino allo zero senza lasciare che un'ape tocchi Pip.",
    rulesText:"Ogni linea consuma nettare e si indebolisce con gli urti. Se un'ape tocca Pip, il tentativo fallisce. Linee brevi e nettare rimasto danno più stelle.",
    progressText:"Sei capitoli aggiungono alveari, approcci divisi, ancoraggi di pietra, raffiche, varchi fragili e ondate miste.",
    tipsText:"Ancora curve brevi tra le pietre, lascia spazio attorno a Pip e osserva le zone rosse. Una piccola riparazione è spesso migliore di un altro cerchio.",
    saveText:"Livelli e stelle migliori restano solo in questo browser. Non servono account o dati personali.",
    faq1q:"Posso disegnare dopo la partenza delle api?",faq1a:"Sì. Le riparazioni in tempo reale sono centrali finché resta nettare.",faq2q:"Le api si fanno male?",faq2a:"No. Le barriere le fanno rimbalzare dolcemente verso i fiori.",faq3q:"A cosa posso giocare dopo?",faq3a:"Prova One Line per tracciare con precisione o Animal Guard Yard per una difesa più ampia.",
    chapters:["Primo volo","Sentieri doppi","Ancoraggi di pietra","Raffiche di trifoglio","Varchi fragili","Maestria Guardamiele"],chapterRules:["Impara barriere brevi contro un'ondata leggera.","Leggi due direzioni e ripara prima il lato debole.","Usa le pietre come ancoraggi solidi.","Reagisci quando il vento cambia la rotta.","Gestisci il nettare nelle ondate lunghe.","Combina tutte le regole per proteggere Pip."],
    lineStatus:"{used} disegnato · {left} nettare",leaveText:"Continua conserva l'ondata congelata. Tornare ai livelli termina solo questo tentativo.",pauseText:"L'ondata resta completamente ferma durante la pausa.",
    winText:"Il livello {stage} è salvo con {nectar} di nettare rimasto.",failText:"Ripara il primo varco rosso prima dell'arrivo delle api.",
    tutorial1:"Disegna una barriera breve tra Pip e l'alveare.",tutorial2:"Rilasciare avvia l'ondata. I lampi rossi indicano una linea debole.",tutorial3:"Aggiungi un breve segmento prima che si apra un varco."
  });
  Object.assign(ru,{
    guideIntro:"Пип подошёл к ульям Клеверного луга. Рисуйте преграды во время полёта пчёл и укрепляйте проходы, пока они не достигли щенка.",
    how1:"Проведите по лугу, чтобы нарисовать светящуюся нектарную преграду.",how2:"Отпустите, чтобы начать волну; новые отрезки можно рисовать и во время неё.",how3:"Дождитесь нуля на таймере, не позволив пчеле коснуться Пипа.",
    rulesText:"Каждая линия тратит нектар и слабеет от ударов. Касание Пипа завершает попытку. Короткие линии и остаток нектара дают больше звёзд.",
    progressText:"Шесть глав добавляют ульи, разные направления, каменные опоры, порывы ветра, хрупкие проходы и смешанные волны.",
    tipsText:"Крепите короткие дуги к камням, оставляйте место вокруг Пипа и следите за красными участками. Небольшой ремонт лучше нового круга.",
    saveText:"Открытые этапы и лучшие звёзды хранятся только в браузере. Учётная запись и личные данные не нужны.",
    faq1q:"Можно рисовать после вылета пчёл?",faq1a:"Да. Ремонт во время волны — основа игры, пока остаётся нектар.",faq2q:"Пчёлы получают вред?",faq2a:"Нет. Преграды мягко направляют их обратно к цветам.",faq3q:"Во что сыграть дальше?",faq3a:"Попробуйте One Line для точного ведения линии или Animal Guard Yard для большой обороны.",
    chapters:["Первый полёт","Двойные тропы","Каменные опоры","Клеверный ветер","Хрупкие проходы","Мастер медовой стражи"],chapterRules:["Освойте короткую преграду против лёгкой волны.","Читайте два направления и сначала чините слабую сторону.","Используйте камни как прочные опоры.","Реагируйте, когда ветер меняет маршрут.","Экономьте нектар в длинных волнах.","Объедините все правила и защитите Пипа."],
    lineStatus:"Нарисовано {used} · нектар {left}",leaveText:"Продолжение сохраняет волну замороженной. Возврат к этапам завершит только эту попытку.",pauseText:"Во время перерыва волна полностью остановлена.",
    winText:"Этап {stage} защищён, осталось {nectar} нектара.",failText:"Почините первый красный проход до приближения пчёл.",
    tutorial1:"Нарисуйте короткую преграду между Пипом и ульем.",tutorial2:"После отпускания начинается волна. Красная вспышка означает слабую линию.",tutorial3:"Добавьте короткий отрезок до появления прохода."
  });
  Object.assign(hi,{
    guideIntro:"पिप क्लोवरलाइट मैदान के छत्तों के पास पहुँच गया है। मधुमक्खियों के उड़ते समय दीवार बनाएँ और पिल्ले तक पहुँचने से पहले खाली जगह सुधारें।",
    how1:"चमकती नेक्टर दीवार बनाने के लिए मैदान पर खींचें।",how2:"लहर शुरू करने के लिए छोड़ें; लहर के दौरान भी नए हिस्से बना सकते हैं।",how3:"किसी मधुमक्खी को पिप तक पहुँचने दिए बिना समय शून्य होने तक बचाएँ।",
    rulesText:"हर रेखा नेक्टर खर्च करती है और टकराव से कमजोर होती है। पिप को छूने पर प्रयास विफल होता है। छोटी रेखाएँ और बचा नेक्टर अधिक सितारे देते हैं।",
    progressText:"छह अध्यायों में अतिरिक्त छत्ते, दो दिशाएँ, पत्थर के सहारे, हवा, कमजोर खाली जगह और मिश्रित लहरें आती हैं।",
    tipsText:"पत्थरों के बीच छोटी वक्र रेखाएँ लगाएँ, पिप के आसपास जगह छोड़ें और लाल हिस्सों पर ध्यान दें। छोटा सुधार पूरे नए घेरे से बेहतर है।",
    saveText:"खुले चरण और सर्वश्रेष्ठ सितारे केवल इस ब्राउज़र में रहते हैं। खाते या निजी जानकारी की जरूरत नहीं है।",
    faq1q:"क्या मधुमक्खियों के उड़ने के बाद भी रेखा बना सकता हूँ?",faq1a:"हाँ। नेक्टर रहते हुए लाइव सुधार ही खेल का मुख्य भाग है।",faq2q:"क्या मधुमक्खियों को चोट लगती है?",faq2a:"नहीं। नेक्टर दीवार उन्हें धीरे से फूलों की ओर लौटा देती है।",faq3q:"इसके बाद क्या खेलूँ?",faq3a:"सटीक रेखा के लिए One Line या बड़ी रक्षा के लिए Animal Guard Yard खेलें।",
    chapters:["पहली उड़ान","दो रास्ते","पत्थर के सहारे","क्लोवर हवा","कमजोर खाली जगह","हनीगार्ड महारत"],chapterRules:["हल्की लहर के विरुद्ध छोटी दीवार सीखें।","दो दिशाएँ पढ़ें और कमजोर तरफ पहले सुधारें।","पत्थरों को मजबूत सहारा बनाएँ।","हवा रास्ता बदले तो तुरंत प्रतिक्रिया दें।","लंबी लहरों में नेक्टर बचाकर खर्च करें।","सभी नियम मिलाकर पिप को सुरक्षित रखें।"],
    lineStatus:"{used} बनाया · {left} नेक्टर",leaveText:"जारी रखने पर लहर यहीं रुकी रहेगी। चरणों पर लौटने से केवल यह प्रयास खत्म होगा।",pauseText:"आराम के दौरान मधुमक्खी लहर पूरी तरह रुकी रहती है।",
    winText:"चरण {stage} सुरक्षित रहा और {nectar} नेक्टर बचा।",failText:"मधुमक्खियों के पहुँचने से पहले पहली लाल जगह सुधारें।",
    tutorial1:"पिप और छत्ते के बीच छोटी दीवार बनाएँ।",tutorial2:"छोड़ने पर लहर शुरू होती है। लाल चमक कमजोर रेखा दिखाती है।",tutorial3:"खाली जगह खुलने से पहले एक छोटा हिस्सा और बनाएँ।"
  });
  Object.assign(ar,{
    guideIntro:"اقترب بيب من خلايا مرج ضوء البرسيم. ارسم الحواجز أثناء طيران النحل وعزّز الفتحات قبل وصوله إلى الجرو.",
    how1:"اسحب عبر المرج لرسم حاجز رحيق مضيء.",how2:"ارفع إصبعك لبدء الموجة؛ ويمكنك رسم أجزاء جديدة أثناءها.",how3:"اصمد حتى يصل المؤقت إلى الصفر من دون أن تلمس نحلة بيب.",
    rulesText:"يستهلك كل خط الرحيق ويضعف عند الاصطدام. تفشل المحاولة إذا لمست نحلة بيب. تمنح الخطوط القصيرة والرحيق المتبقي نجوماً أكثر.",
    progressText:"تضيف ستة فصول خلايا واتجاهات مزدوجة ومراسي حجرية ورياحاً وفجوات هشة وموجات مختلطة.",
    tipsText:"ثبّت منحنيات قصيرة بين الحجارة واترك مساحة حول بيب وراقب الأجزاء الحمراء. إصلاح صغير أفضل غالباً من دائرة كاملة أخرى.",
    saveText:"تبقى المراحل المفتوحة وأفضل النجوم في هذا المتصفح فقط. لا يلزم حساب أو معلومات شخصية.",
    faq1q:"هل يمكنني الرسم بعد انطلاق النحل؟",faq1a:"نعم. الإصلاح المباشر هو جوهر اللعبة ما دام الرحيق متاحاً.",faq2q:"هل يتأذى النحل؟",faq2a:"لا. تعيده حواجز الرحيق برفق نحو الأزهار.",faq3q:"ماذا ألعب بعد ذلك؟",faq3a:"جرّب One Line للرسم الدقيق أو Animal Guard Yard لدفاع أكبر.",
    chapters:["الرحلة الأولى","مساران","مراسي الحجر","رياح البرسيم","فجوات هشة","إتقان حارس العسل"],chapterRules:["تعلّم حاجزاً قصيراً أمام موجة لطيفة.","راقب اتجاهين وأصلح الجانب الأضعف أولاً.","استخدم حجارة المرج كمراسي قوية.","استجب عندما تغيّر الرياح مسار النحل.","وزّع الرحيق بحذر في الموجات الطويلة.","اجمع كل القواعد لتحافظ على سلامة بيب."],
    lineStatus:"رُسم {used} · الرحيق {left}",leaveText:"المتابعة تحفظ هذه الموجة مجمّدة. العودة إلى المراحل تنهي هذه المحاولة فقط.",pauseText:"تبقى موجة النحل متوقفة تماماً أثناء الاستراحة.",
    winText:"بقيت المرحلة {stage} آمنة مع {nectar} من الرحيق.",failText:"أصلح أول فجوة حمراء قبل وصول النحل.",
    tutorial1:"ارسم حاجزاً قصيراً بين بيب والخلية.",tutorial2:"يبدأ الهجوم عند رفع الإصبع. الوميض الأحمر يعني ضعف الخط.",tutorial3:"أضف جزءاً قصيراً قبل أن تنفتح فجوة."
  });
  Object.assign(en,{how2:"The bees launch after a brief ready beat—or as soon as you finish your first line. Keep drawing during the wave.",tutorial2:"The wave starts automatically after a short ready beat. Bees move quickly and steer around solid obstacles.",tutorial3:"Free walls can be pushed. Touch a stone, flower gate, or platform to pin a wall in place."});
  Object.assign(zhHant,{how2:"短暫準備後蜂群會自動出發；先畫完第一條線也會立即開戰。波次中仍可繼續畫線。",tutorial2:"短暫準備後波次會自動開始。蜜蜂速度很快，也會繞過實體障礙。",tutorial3:"未固定的防線會被推動。讓線碰到石塊、花門或平台即可固定。"});
  Object.assign(zhHans,{how2:"短暂准备后蜂群会自动出发；先画完第一条线也会立即开战。波次中仍可继续画线。",tutorial2:"短暂准备后波次会自动开始。蜜蜂速度很快，也会绕过实体障碍。",tutorial3:"未固定的防线会被推动。让线碰到石块、花门或平台即可固定。"});
  Object.assign(ja,{how2:"短い準備時間の後、または最初の線を描き終えるとハチが出発します。ウェーブ中も描けます。",tutorial2:"短い準備時間の後に自動で開始します。ハチは速く、固い障害物を回り込みます。",tutorial3:"固定されていない壁は押されます。石・花の門・足場に線を触れさせて固定しましょう。"});
  Object.assign(ko,{how2:"짧은 준비 시간이 지나거나 첫 선을 완성하면 벌 떼가 출발합니다. 진행 중에도 계속 그릴 수 있습니다.",tutorial2:"짧은 준비 후 자동으로 시작합니다. 벌은 빠르게 움직이며 단단한 장애물을 돌아갑니다.",tutorial3:"고정되지 않은 벽은 밀립니다. 선을 돌, 꽃문 또는 발판에 닿게 해 고정하세요."});
  Object.assign(es,{how2:"Las abejas salen tras una breve preparación o al terminar la primera línea. Puedes seguir dibujando durante la oleada.",tutorial2:"La oleada empieza automáticamente tras una breve pausa. Las abejas son rápidas y rodean obstáculos sólidos.",tutorial3:"Los muros libres pueden moverse. Toca una piedra, puerta floral o plataforma para fijarlos."});
  Object.assign(pt,{how2:"As abelhas partem após um breve preparo ou ao terminar a primeira linha. Continue desenhando durante a onda.",tutorial2:"A onda começa automaticamente após um breve preparo. As abelhas são rápidas e contornam obstáculos sólidos.",tutorial3:"Paredes soltas podem ser empurradas. Encoste a linha em uma pedra, portal de flores ou plataforma para fixá-la."});
  Object.assign(fr,{how2:"Les abeilles partent après une brève préparation ou dès la première ligne terminée. Continuez à dessiner pendant la vague.",tutorial2:"La vague démarre automatiquement après un court délai. Les abeilles sont rapides et contournent les obstacles solides.",tutorial3:"Les murs libres peuvent être poussés. Touchez une pierre, une porte fleurie ou une plateforme pour les fixer."});
  Object.assign(de,{how2:"Die Bienen starten nach einer kurzen Vorbereitung oder sobald die erste Linie fertig ist. Zeichne während der Welle weiter.",tutorial2:"Die Welle startet nach kurzer Vorbereitung automatisch. Bienen sind schnell und umfliegen feste Hindernisse.",tutorial3:"Freie Wände können verschoben werden. Berühre Stein, Blumentor oder Plattform, um sie zu verankern."});
  Object.assign(it,{how2:"Le api partono dopo una breve preparazione o appena completi la prima linea. Continua a disegnare durante l'ondata.",tutorial2:"L'ondata parte automaticamente dopo una breve attesa. Le api sono veloci e aggirano gli ostacoli solidi.",tutorial3:"I muri liberi possono essere spinti. Tocca una pietra, un portale floreale o una piattaforma per fissarli."});
  Object.assign(ru,{how2:"Пчёлы вылетают после короткой подготовки или сразу после первой линии. Во время волны можно продолжать рисовать.",tutorial2:"Волна начинается автоматически после короткой паузы. Пчёлы быстрые и обходят твёрдые препятствия.",tutorial3:"Свободные стены можно сдвинуть. Коснитесь линией камня, цветочных ворот или платформы, чтобы закрепить её."});
  Object.assign(hi,{how2:"थोड़ी तैयारी के बाद या पहली रेखा पूरी होते ही मधुमक्खियाँ उड़ेंगी। लहर के दौरान भी रेखाएँ बनाते रहें।",tutorial2:"थोड़ी तैयारी के बाद लहर अपने आप शुरू होती है। मधुमक्खियाँ तेज़ हैं और ठोस बाधाओं के चारों ओर जाती हैं।",tutorial3:"खुली दीवारें धकेली जा सकती हैं। उन्हें रोकने के लिए रेखा को पत्थर, फूल-द्वार या मंच से जोड़ें।"});
  Object.assign(ar,{how2:"ينطلق النحل بعد مهلة قصيرة أو فور إكمال الخط الأول. يمكنك متابعة الرسم أثناء الموجة.",tutorial2:"تبدأ الموجة تلقائيًا بعد استعداد قصير. النحل سريع ويلتف حول العوائق الصلبة.",tutorial3:"يمكن دفع الجدران الحرة. صِل الخط بحجر أو بوابة زهور أو منصة لتثبيته."});
  window.ANIMAL_HONEY_SHIELD_LOCALES={en,"zh-Hant":zhHant,"zh-Hans":zhHans,ja,ko,es,"pt-BR":pt,fr,de,it,ru,hi,ar};
})();
