(()=>{"use strict";
const L=window.ANIMAL_BLOCK_GROVE_LOCALES||{},SAVE_KEY="weightplay_animal_block_grove_v1",INFINITE=30,TILE_NAMES=["leaf","paw","flower","star","ripple","acorn"],SHAPES=[
 {id:"single",c:[[0,0]]},{id:"dominoH",c:[[0,0],[1,0]]},{id:"dominoV",c:[[0,0],[0,1]]},{id:"line3H",c:[[0,0],[1,0],[2,0]]},{id:"line3V",c:[[0,0],[0,1],[0,2]]},{id:"line4H",c:[[0,0],[1,0],[2,0],[3,0]]},{id:"line4V",c:[[0,0],[0,1],[0,2],[0,3]]},{id:"square",c:[[0,0],[1,0],[0,1],[1,1]]},{id:"l3a",c:[[0,0],[0,1],[1,1]]},{id:"l3b",c:[[0,0],[1,0],[0,1]]},{id:"l3c",c:[[0,0],[1,0],[1,1]]},{id:"l3d",c:[[1,0],[0,1],[1,1]]},{id:"t4",c:[[0,0],[1,0],[2,0],[1,1]]},{id:"z4",c:[[0,0],[1,0],[1,1],[2,1]]},{id:"s4",c:[[1,0],[2,0],[0,1],[1,1]]},{id:"corner5",c:[[0,0],[0,1],[0,2],[1,2],[2,2]]}
];
const $=s=>document.querySelector(s),dom={loading:$("#loadingPanel"),loadingFill:$("#loadingFill"),main:$("#mainScreen"),stage:$("#stageScreen"),battle:$("#battleScreen"),locale:$("#localeSelect"),start:$("#startBtn"),mainProgress:$("#mainProgress"),stageBack:$("#stageBackBtn"),summary:$("#stageSummary"),campaign:$("#campaignTab"),challenge:$("#challengeTab"),chapterKicker:$("#chapterKicker"),chapterTitle:$("#chapterTitle"),chapterRule:$("#chapterRule"),rail:$("#stageRail"),battleBack:$("#battleBackBtn"),stageLabel:$("#stageLabel"),goal:$("#goalValue"),moves:$("#movesValue"),score:$("#scoreValue"),objectives:$("#objectiveRow"),board:$("#gameBoard"),tray:$("#pieceTray"),toast:$("#comboToast"),undo:$("#undoBtn"),hint:$("#hintBtn"),result:$("#resultPanel"),resultTitle:$("#resultTitle"),resultStars:$("#resultStars"),resultText:$("#resultText"),best:$("#bestText"),retry:$("#retryBtn"),resultStages:$("#resultStagesBtn"),next:$("#nextBtn"),leave:$("#leavePanel"),leaveContinue:$("#leaveContinueBtn"),leaveStages:$("#leaveStagesBtn"),tutorial:$("#tutorialPanel"),tutorialClose:$("#tutorialCloseBtn"),tutorialStart:$("#tutorialStartBtn"),ghost:$("#dragGhost")};
let locale=localStorage.getItem("weightPlayLocale")||localStorage.getItem("weightplayLocale")||"zh-Hant";if(!L[locale])locale="zh-Hant";
let save=loadSave(),mode="campaign",stageIndex=0,mission=null,board=Array(64).fill(0),tray=[],selected=-1,moves=0,score=0,lines=0,crosses=0,marks=new Set(),acorns=new Set(),initialMarks=0,initialAcorns=0,initialStones=0,undoState=null,rngState=1,resultState="",drag=null,hintCells=[],toastTimer=0,resultTimer=0,clearTimer=0,interactionLocked=false;
function loadSave(){try{return Object.assign({unlocked:1,cleared:{},stars:{},best:{},infiniteBest:0,tutorial:false},JSON.parse(localStorage.getItem(SAVE_KEY)||"{}"));}catch{return{unlocked:1,cleared:{},stars:{},best:{},infiniteBest:0,tutorial:false};}}
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save));}
function tr(key,vars={}){let v=(L[locale]&&L[locale][key])??L.en?.[key]??key;if(typeof v!=="string")return v;return v.replace(/\{(\w+)\}/g,(_,k)=>vars[k]??"");}
function applyLocale(){document.documentElement.lang=locale;dom.locale.value=locale;document.title=`${tr("fullTitle")} | WeightPlay`;document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=tr(el.dataset.i18n);});document.querySelectorAll("[data-i18n-aria]").forEach(el=>el.setAttribute("aria-label",tr(el.dataset.i18nAria)));document.querySelectorAll("[data-i18n-alt]").forEach(el=>el.alt=tr(el.dataset.i18nAlt));renderMainProgress();if(!dom.stage.hidden)renderStage();if(!dom.battle.hidden)renderBattle();}
function positionMainSoundToggle(){const toggle=$(".sound-toggle");if(!toggle||document.body.dataset.screen!=="main")return;toggle.style.setProperty("left","auto","important");toggle.style.setProperty("top","84px","important");toggle.style.setProperty("right","12px","important");toggle.style.setProperty("bottom","auto","important");}
function setScreen(name){document.body.dataset.screen=name;dom.stage.hidden=name!=="stage";dom.battle.hidden=name!=="battle";window.dispatchEvent(new Event("resize"));requestAnimationFrame(()=>{window.dispatchEvent(new Event("resize"));positionMainSoundToggle();});if(name==="main")setTimeout(positionMainSoundToggle,950);}
function rng(){rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;return rngState/4294967296;}
function missionFor(i){const chapter=Math.floor(i/5),slot=i%5+1;const m={index:i,chapter,seed:9473+i*7919,limit:14+chapter*3+slot+(chapter===5?12:0),goals:{lines:Math.min(2+Math.floor(chapter/2)+Math.floor(slot/3),5),score:0,marks:0,acorns:0,stones:0,cross:0}};if(chapter===0)m.goals.score=300+slot*120;if(chapter===1)m.goals.marks=1+Math.ceil(slot/2);if(chapter===2)m.goals.acorns=1+Math.ceil(slot/2);if(chapter===3)m.goals.stones=2+slot;if(chapter===4)m.goals.cross=1;if(chapter===5){m.goals.score=900+slot*220;m.goals.marks=1+Math.floor(slot/2);m.goals.acorns=1+Math.floor(slot/2);m.goals.stones=2+slot;m.goals.cross=slot>=4?1:0;}return m;}
const MISSIONS=Array.from({length:30},(_,i)=>missionFor(i));
function starterFor(m){const b=Array(64).fill(0),holes=[];rngState=m.seed;const firstRow=(m.index*3+1)%8,crossCol=(m.index*5+2)%8,rowCount=Math.min(6,Math.max(1,m.goals.lines-(m.goals.cross?1:0)));for(let r=0;r<rowCount;r++){const row=(firstRow+r)%8,hole=r===0?crossCol:(crossCol+r)%8;for(let x=0;x<8;x++)if(x!==hole)b[row*8+x]=1+Math.floor(rng()*6);holes.push(row*8+hole);}if(m.goals.cross){for(let y=0;y<8;y++){const idx=y*8+crossCol;if(y!==firstRow&&!b[idx])b[idx]=1+Math.floor(rng()*6);}}return{b,holes};}
function setupObjects(m,holes){marks=new Set();acorns=new Set();const free=Array.from({length:64},(_,i)=>i).filter(i=>!board[i]);for(let i=0;i<m.goals.marks;i++)marks.add(holes[i%holes.length]??free[i]);for(let i=0;i<m.goals.acorns;i++)acorns.add(free[(i*7+3)%free.length]);const occupied=Array.from({length:64},(_,i)=>i).filter(i=>board[i]&&board[i]!==7);let placed=0,scan=(m.index*11+9)%Math.max(1,occupied.length),checked=0;while(placed<m.goals.stones&&occupied.length&&checked<occupied.length){const idx=occupied[scan%occupied.length];if(board[idx]!==7&&!marks.has(idx)&&!acorns.has(idx)){board[idx]=7;placed++;}scan++;checked++;}initialMarks=marks.size;initialAcorns=acorns.size;initialStones=board.filter(v=>v===7).length;}
function shapeById(id){return SHAPES.find(s=>s.id===id)||SHAPES[0];}
function drawTray(first=false){const easy=first||mission&&mission.chapter<2;tray=Array.from({length:3},(_,i)=>{let pool=easy?SHAPES.slice(0,12):SHAPES;let shape=pool[Math.floor(rng()*pool.length)];if(i===0||first&&i<Math.min(3,mission?.goals.lines||1))shape=SHAPES[0];return{id:`${moves}-${i}-${rngState}`,shape:shape.id,tile:1+Math.floor(rng()*6),used:false};});selected=-1;}
function startStage(index){clearTimeout(resultTimer);resultTimer=0;stageIndex=Math.max(0,Math.min(INFINITE,index));mission=index===INFINITE?{type:"infinite",index:INFINITE,chapter:5,seed:(Date.now()^performance.now())>>>0,limit:Infinity,goals:{lines:0,score:0,marks:0,acorns:0,stones:0,cross:0}}:MISSIONS[stageIndex];rngState=mission.seed||1;moves=score=lines=crosses=0;resultState="";undoState=null;hintCells=[];const starter=stageIndex===INFINITE?{b:Array(64).fill(0),holes:[]}:starterFor(mission);board=starter.b;setupObjects(mission,starter.holes);drawTray(true);dom.result.hidden=true;dom.leave.hidden=true;setScreen("battle");renderBattle();requestAnimationFrame(()=>dom.board.focus({preventScroll:true}));window.WonderAnalytics?.track?.("game_start",{gameId:"animal-block-grove",stage:index===INFINITE?"infinite":index+1,mode:index===INFINITE?"endless":"mission"});}
function renderMainProgress(){const cleared=Object.values(save.cleared||{}).filter(Boolean).length,stars=Object.values(save.stars||{}).reduce((a,b)=>a+Number(b||0),0);dom.mainProgress.textContent=tr("progress",{cleared,stars});}
function renderStage(){const cleared=Object.values(save.cleared||{}).filter(Boolean).length,stars=Object.values(save.stars||{}).reduce((a,b)=>a+Number(b||0),0);dom.summary.textContent=tr("summary",{cleared,stars});dom.campaign.setAttribute("aria-pressed",String(mode==="campaign"));dom.challenge.setAttribute("aria-pressed",String(mode==="challenge"));dom.stage.dataset.mode=mode;const chapter=Math.min(5,Math.floor(Math.max(0,Math.min(stageIndex,29))/5));dom.chapterKicker.textContent=mode==="campaign"?tr("chapter",{chapter:chapter+1}):tr("infinite");dom.chapterTitle.textContent=mode==="campaign"?tr("chapterTitles")[chapter]:tr("infinite");dom.chapterRule.textContent=mode==="campaign"?tr("chapterRules")[chapter]:tr("infiniteRule");dom.rail.innerHTML="";if(mode==="challenge"){const card=stageCard(INFINITE,true);card.classList.add("challenge-card","selected");dom.rail.append(card);}else MISSIONS.forEach((_,i)=>dom.rail.append(stageCard(i,i===stageIndex)));requestAnimationFrame(()=>{const target=dom.rail.querySelector(".selected")||dom.rail.querySelector(".stage-card");target?.scrollIntoView({behavior:"auto",inline:"center",block:"nearest"});syncCenteredStageCard();window.dispatchEvent(new Event("resize"));requestAnimationFrame(syncCenteredStageCard);setTimeout(syncCenteredStageCard,380);});}
function stageCard(i,isSelected){const locked=i!==INFINITE&&i>=Number(save.unlocked||1),card=document.createElement("button");card.type="button";card.className=`stage-card${locked?" locked":""}${isSelected?" selected":""}`;card.dataset.stage=String(i);card.dataset.index=String(i);const best=i===INFINITE?Number(save.infiniteBest||0):Number(save.best?.[i]||0),stars=i===INFINITE?"∞":"★".repeat(save.stars?.[i]||0)+"☆".repeat(3-(save.stars?.[i]||0));card.innerHTML=`<span>${i===INFINITE?tr("infinite"):tr("mission",{stage:i+1})}</span><strong>${locked?tr("locked"):i===INFINITE?tr("infiniteRule"):tr("chapterTitles")[Math.floor(i/5)]}</strong><small><span>${tr("best",{score:best})}</span><span>${stars}</span></small>`;card.disabled=locked;card.addEventListener("click",()=>{stageIndex=i;renderStage();setTimeout(()=>startStage(i),90);});return card;}
function syncCenteredStageCard(){if(dom.stage.hidden)return;const cards=[...dom.rail.querySelectorAll(".stage-card")];if(!cards.length)return;const railRect=dom.rail.getBoundingClientRect(),center=railRect.left+railRect.width/2,nearest=cards.reduce((best,card)=>{const rect=card.getBoundingClientRect(),distance=Math.abs(rect.left+rect.width/2-center);return!best||distance<best.distance?{card,distance}:best;},null)?.card;if(!nearest)return;stageIndex=Number(nearest.dataset.index);cards.forEach(card=>{const active=card===nearest;card.classList.toggle("selected",active);card.classList.toggle("is-centered",active);if(active)card.setAttribute("aria-current","true");else card.removeAttribute("aria-current");});}
let stageDrag=null,suppressStageClick=false;
function settleStageRail(){const cards=[...dom.rail.querySelectorAll(".stage-card")];if(!cards.length)return;const railRect=dom.rail.getBoundingClientRect(),center=railRect.left+railRect.width/2,nearest=cards.reduce((best,card)=>{const rect=card.getBoundingClientRect(),distance=Math.abs(rect.left+rect.width/2-center);return!best||distance<best.distance?{card,distance}:best;},null)?.card;nearest?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",inline:"center",block:"nearest"});requestAnimationFrame(syncCenteredStageCard);setTimeout(syncCenteredStageCard,360);}
function tileUrl(value){return`../../assets/animal-block-grove-tile-${TILE_NAMES[(Math.max(1,value)-1)%TILE_NAMES.length]}.webp`;}
function objectUrl(type){return`../../assets/animal-block-grove-icon-${type==="score"?"cross":type}.webp`;}
function renderBattle(){const infinite=stageIndex===INFINITE;dom.stageLabel.textContent=infinite?tr("infinite"):tr("mission",{stage:stageIndex+1});dom.goal.textContent=infinite?tr("infiniteBest",{score:save.infiniteBest||0}):tr("placements",{used:moves,limit:mission.limit});dom.moves.textContent=infinite?moves:`${moves}/${mission.limit}`;dom.score.textContent=score;renderObjectives();renderBoard();renderTray();dom.undo.disabled=!undoState||!!resultState;dom.hint.disabled=!!resultState;}
function renderObjectives(){const g=mission.goals,chips=[];if(stageIndex===INFINITE)chips.push(["score",tr("goalScore",{now:score,goal:"∞"}),false]);else{if(g.lines)chips.push(["cross",tr("goalLines",{now:lines,goal:g.lines}),lines>=g.lines]);if(g.score)chips.push(["cross",tr("goalScore",{now:score,goal:g.score}),score>=g.score]);if(g.marks)chips.push(["mark",tr("goalMarks",{now:initialMarks-marks.size,goal:g.marks}),marks.size===0]);if(g.acorns)chips.push(["acorn",tr("goalAcorns",{now:initialAcorns-acorns.size,goal:g.acorns}),acorns.size===0]);if(g.stones)chips.push(["stone",tr("goalStones",{now:initialStones-board.filter(v=>v===7).length,goal:g.stones}),board.filter(v=>v===7).length===0]);if(g.cross)chips.push(["cross",tr("goalCross",{now:crosses,goal:g.cross}),crosses>=g.cross]);}dom.objectives.innerHTML=chips.map(([icon,text,done])=>`<span class="objective-chip${done?" done":""}"><img src="${objectUrl(icon)}" alt=""><span>${text}</span></span>`).join("");}
function renderBoard(){if(!dom.board.children.length){for(let i=0;i<64;i++){const c=document.createElement("div");c.className="board-cell";c.dataset.index=i;dom.board.append(c);}}[...dom.board.children].forEach((cell,i)=>{cell.className="board-cell";cell.innerHTML="";if(board[i])cell.innerHTML+=`<img class="tile-image" src="${board[i]===7?objectUrl("stone"):tileUrl(board[i])}" alt="">`;if(marks.has(i))cell.innerHTML+=`<img class="object-image" src="${objectUrl("mark")}" alt="">`;if(acorns.has(i))cell.innerHTML+=`<img class="object-image" src="${objectUrl("acorn")}" alt="">`;if(hintCells.includes(i))cell.classList.add("hint");});}
function pieceBounds(shape){const xs=shape.c.map(v=>v[0]),ys=shape.c.map(v=>v[1]);return{w:Math.max(...xs)+1,h:Math.max(...ys)+1};}
function pieceMarkup(piece,large=false){const s=shapeById(piece.shape),b=pieceBounds(s),bits=new Set(s.c.map(([x,y])=>`${x},${y}`));let html="";for(let y=0;y<b.h;y++)for(let x=0;x<b.w;x++)html+=bits.has(`${x},${y}`)?`<i class="piece-bit" style="background-image:url('${tileUrl(piece.tile)}')"></i>`:`<i></i>`;return`<span class="piece-grid" style="grid-template-columns:repeat(${b.w},${large?34:20}px);grid-template-rows:repeat(${b.h},${large?34:20}px)">${html}</span>`;}
function renderTray(){dom.tray.innerHTML="";tray.forEach((p,i)=>{const btn=document.createElement("button");btn.type="button";btn.className=`piece-card${p.used?" used":""}${selected===i?" selected":""}`;btn.dataset.piece=i;btn.setAttribute("aria-label",`${tr("trayLabel")} ${i+1}`);btn.innerHTML=pieceMarkup(p);btn.addEventListener("pointerdown",e=>beginDrag(e,i));btn.addEventListener("click",()=>{if(!p.used){selected=i;hintCells=[];renderBattle();}});dom.tray.append(btn);});}
function canPlace(piece,anchor){const shape=shapeById(piece.shape),ax=anchor%8,ay=Math.floor(anchor/8);return shape.c.every(([dx,dy])=>{const x=ax+dx,y=ay+dy;return x>=0&&x<8&&y>=0&&y<8&&!board[y*8+x];});}
function cellsFor(piece,anchor){const ax=anchor%8,ay=Math.floor(anchor/8);return shapeById(piece.shape).c.map(([dx,dy])=>(ay+dy)*8+ax+dx);}
function allPlacements(piece){const out=[];for(let i=0;i<64;i++)if(canPlace(piece,i))out.push(i);return out;}
function remainingFits(){return tray.some(p=>!p.used&&allPlacements(p).length);}
function snapshot(){return{board:[...board],tray:tray.map(p=>({...p})),selected,moves,score,lines,crosses,marks:[...marks],acorns:[...acorns],rngState};}
function restore(s){board=[...s.board];tray=s.tray.map(p=>({...p}));selected=s.selected;moves=s.moves;score=s.score;lines=s.lines;crosses=s.crosses;marks=new Set(s.marks);acorns=new Set(s.acorns);rngState=s.rngState;hintCells=[];resultState="";dom.result.hidden=true;renderBattle();}
function evaluate(piece,anchor){if(!canPlace(piece,anchor))return-Infinity;const copy=[...board];cellsFor(piece,anchor).forEach(i=>copy[i]=piece.tile);const fullRows=[],fullCols=[],clear=new Set();for(let y=0;y<8;y++)if(copy.slice(y*8,y*8+8).every(Boolean))fullRows.push(y);for(let x=0;x<8;x++)if(Array.from({length:8},(_,y)=>copy[y*8+x]).every(Boolean))fullCols.push(x);fullRows.forEach(y=>{for(let x=0;x<8;x++)clear.add(y*8+x);});fullCols.forEach(x=>{for(let y=0;y<8;y++)clear.add(y*8+x);});const rows=fullRows.length,cols=fullCols.length,center=3.5-Math.abs(anchor%8-3.5)+3.5-Math.abs(Math.floor(anchor/8)-3.5),markGain=[...clear].filter(i=>marks.has(i)).length,stoneGain=[...clear].filter(i=>board[i]===7).length,crossNeeded=Boolean(mission.goals.cross&&crosses<mission.goals.cross),targets=[...new Set([...marks,...board.map((value,i)=>value===7?i:-1).filter(i=>i>=0)])],targetProgress=targets.reduce((sum,i)=>{const row=Math.floor(i/8),col=i%8,rowFill=copy.slice(row*8,row*8+8).filter(Boolean).length,colFill=Array.from({length:8},(_,y)=>copy[y*8+col]).filter(Boolean).length;return sum+Math.max(rowFill,colFill)**2*8;},0);return(rows+cols)*1000+(rows&&cols?(crossNeeded?12000:1500):0)+markGain*1400+stoneGain*950+targetProgress+cellsFor(piece,anchor).filter(i=>acorns.has(i)).length*800+center-copy.filter(Boolean).length*.2;}
function place(pieceIndex,anchor,quiet=false){const p=tray[pieceIndex];if(!p||p.used||!canPlace(p,anchor)){if(!quiet)showToast(tr("invalid"));return false;}undoState=snapshot();hintCells=[];const cells=cellsFor(p,anchor);cells.forEach(i=>{board[i]=p.tile;acorns.delete(i);});p.used=true;selected=-1;moves++;score+=cells.length*10;const fullRows=[],fullCols=[];for(let y=0;y<8;y++)if(board.slice(y*8,y*8+8).every(Boolean))fullRows.push(y);for(let x=0;x<8;x++)if(Array.from({length:8},(_,y)=>board[y*8+x]).every(Boolean))fullCols.push(x);const clear=new Set();fullRows.forEach(y=>{for(let x=0;x<8;x++)clear.add(y*8+x);});fullCols.forEach(x=>{for(let y=0;y<8;y++)clear.add(y*8+x);});if(clear.size){const count=fullRows.length+fullCols.length,bonus=count*120+Math.max(0,count-1)*100;score+=bonus;lines+=count;if(fullRows.length&&fullCols.length)crosses++;clear.forEach(i=>{board[i]=0;marks.delete(i);});if(!quiet)showToast(tr("combo",{count,score:bonus}));}if(tray.every(x=>x.used))drawTray();if(!quiet)renderBattle();if(checkWin()){finish(true);return true;}if(stageIndex!==INFINITE&&moves>=mission.limit){finish(false,"moves");return true;}if(!remainingFits())finish(false,"board");return true;}
function checkWin(){if(stageIndex===INFINITE)return false;const g=mission.goals;return(!g.lines||lines>=g.lines)&&(!g.score||score>=g.score)&&(!g.marks||marks.size===0)&&(!g.acorns||acorns.size===0)&&(!g.stones||board.filter(v=>v===7).length===0)&&(!g.cross||crosses>=g.cross);}
function finish(win,reason=""){if(resultState)return;resultState=stageIndex===INFINITE?"infinite":win?"win":"lose";const old=stageIndex===INFINITE?Number(save.infiniteBest||0):Number(save.best?.[stageIndex]||0);if(stageIndex===INFINITE){save.infiniteBest=Math.max(old,score);dom.resultTitle.textContent=tr("infiniteTitle");dom.resultStars.textContent="∞";dom.resultText.textContent=tr("infiniteText",{moves,score});dom.best.textContent=score>old?tr("newBest"):tr("best",{score:save.infiniteBest});dom.next.hidden=true;}else if(win){const remain=mission.limit-moves,stars=remain>=Math.ceil(mission.limit*.35)?3:remain>=1?2:1;save.cleared[stageIndex]=true;save.stars[stageIndex]=Math.max(save.stars?.[stageIndex]||0,stars);save.best[stageIndex]=Math.max(old,score);save.unlocked=Math.max(Number(save.unlocked||1),Math.min(30,stageIndex+2));dom.resultTitle.textContent=tr("winTitle");dom.resultStars.textContent="★".repeat(stars)+"☆".repeat(3-stars);dom.resultText.textContent=tr("winText",{stage:stageIndex+1,moves,score});dom.best.textContent=score>old?tr("newBest"):tr("best",{score:save.best[stageIndex]});dom.next.hidden=stageIndex===29;}else{dom.resultTitle.textContent=tr("loseTitle");dom.resultStars.textContent="";dom.resultText.textContent=tr(reason==="moves"?"loseMoves":"loseBoard");dom.best.textContent=tr("best",{score:old});dom.next.hidden=true;}persist();resultTimer=setTimeout(()=>{resultTimer=0;dom.result.hidden=false;dom.retry.focus({preventScroll:true});},260);window.WonderAnalytics?.track?.(win?"game_complete":"game_fail",{gameId:"animal-block-grove",stage:stageIndex===INFINITE?"infinite":stageIndex+1,score,moves,reason});}
function showToast(text){clearTimeout(toastTimer);dom.toast.textContent=text;toastTimer=setTimeout(()=>dom.toast.textContent="",1200);}
function modalButtons(panel){return[...panel.querySelectorAll("button:not([disabled])")].filter(button=>!button.hidden);}
function focusModal(panel,button){panel.hidden=false;requestAnimationFrame(()=>button?.focus({preventScroll:true}));}
function bestHint(){let best=null;tray.forEach((p,i)=>{if(p.used)return;allPlacements(p).forEach(a=>{const value=evaluate(p,a);if(!best||value>best.value)best={i,a,value};});});return best;}
function showHint(){const best=bestHint();if(!best){showToast(tr("noFit"));return;}selected=best.i;hintCells=cellsFor(tray[best.i],best.a);showToast(tr("hintReady"));renderBattle();}
function boardAnchorFromPoint(x,y){const r=dom.board.getBoundingClientRect();if(x<r.left||x>r.right||y<r.top||y>r.bottom)return-1;const col=Math.min(7,Math.max(0,Math.floor((x-r.left)/r.width*8))),row=Math.min(7,Math.max(0,Math.floor((y-r.top)/r.height*8)));return row*8+col;}
function preview(anchor,pieceIndex){[...dom.board.children].forEach(c=>c.classList.remove("preview","invalid"));if(anchor<0)return;const p=tray[pieceIndex];if(!p)return;const valid=canPlace(p,anchor),cells=cellsFor(p,anchor).filter(i=>i>=0&&i<64);cells.forEach(i=>dom.board.children[i]?.classList.add("preview",...(valid?[]:["invalid"])));}
function beginDrag(e,i){if(tray[i]?.used||resultState)return;selected=i;drag={i,moved:false,startX:e.clientX,startY:e.clientY};dom.ghost.innerHTML=pieceMarkup(tray[i],true);dom.ghost.hidden=false;moveGhost(e);try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}renderTray();}
function moveGhost(e){if(!drag)return;dom.ghost.style.left=`${e.clientX}px`;dom.ghost.style.top=`${e.clientY}px`;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>8)drag.moved=true;preview(boardAnchorFromPoint(e.clientX,e.clientY),drag.i);}
function endDrag(e){if(!drag)return;const d=drag;drag=null;dom.ghost.hidden=true;preview(-1,d.i);const anchor=boardAnchorFromPoint(e.clientX,e.clientY);if(d.moved&&anchor>=0)place(d.i,anchor);}
document.addEventListener("pointermove",moveGhost,{passive:true});document.addEventListener("pointerup",endDrag);document.addEventListener("pointercancel",endDrag);
dom.board.addEventListener("click",e=>{if(drag||resultState)return;const cell=e.target.closest(".board-cell");if(!cell)return;if(selected<0){showToast(tr("selectPiece"));return;}place(selected,Number(cell.dataset.index));});
dom.board.addEventListener("keydown",e=>{if(resultState)return;let cursor=Number(dom.board.dataset.cursor||0);if(e.key==="ArrowLeft")cursor=Math.max(0,cursor-1);else if(e.key==="ArrowRight")cursor=Math.min(63,cursor+1);else if(e.key==="ArrowUp")cursor=Math.max(0,cursor-8);else if(e.key==="ArrowDown")cursor=Math.min(63,cursor+8);else if((e.key==="Enter"||e.key===" ")&&selected>=0){place(selected,cursor);e.preventDefault();return;}else return;e.preventDefault();dom.board.dataset.cursor=cursor;hintCells=[cursor];renderBoard();});
dom.start.addEventListener("click",()=>{mode="campaign";setScreen("stage");renderStage();if(!save.tutorial)focusModal(dom.tutorial,dom.tutorialStart);});dom.stageBack.addEventListener("click",()=>{setScreen("main");renderMainProgress();});dom.campaign.addEventListener("click",()=>{mode="campaign";stageIndex=Math.min(29,Math.max(0,Number(save.unlocked||1)-1));renderStage();});dom.challenge.addEventListener("click",()=>{mode="challenge";stageIndex=INFINITE;renderStage();});dom.rail.addEventListener("wonder:stage-snap",event=>{const index=Number(event.detail?.index);if(!Number.isInteger(index))return;stageIndex=index;dom.rail.querySelectorAll(".stage-card").forEach(card=>card.classList.toggle("selected",Number(card.dataset.index)===index));});dom.battleBack.addEventListener("click",()=>{if(resultState){mode=stageIndex===INFINITE?"challenge":"campaign";setScreen("stage");renderStage();}else focusModal(dom.leave,dom.leaveContinue);});dom.leaveContinue.addEventListener("click",()=>{dom.leave.hidden=true;dom.battleBack.focus({preventScroll:true});});dom.leaveStages.addEventListener("click",()=>{dom.leave.hidden=true;mode=stageIndex===INFINITE?"challenge":"campaign";setScreen("stage");renderStage();});dom.undo.addEventListener("click",()=>{if(undoState){const s=undoState;undoState=null;restore(s);}});dom.hint.addEventListener("click",showHint);dom.retry.addEventListener("click",()=>startStage(stageIndex));dom.resultStages.addEventListener("click",()=>{mode=stageIndex===INFINITE?"challenge":"campaign";setScreen("stage");renderStage();});dom.next.addEventListener("click",()=>startStage(Math.min(29,stageIndex+1)));dom.tutorialClose.addEventListener("click",()=>{save.tutorial=true;persist();dom.tutorial.hidden=true;dom.stageBack.focus({preventScroll:true});});dom.tutorialStart.addEventListener("click",()=>{save.tutorial=true;persist();dom.tutorial.hidden=true;startStage(0);});dom.locale.addEventListener("change",()=>{locale=dom.locale.value;localStorage.setItem("weightPlayLocale",locale);applyLocale();});
document.addEventListener("keydown",event=>{const panel=!dom.leave.hidden?dom.leave:!dom.tutorial.hidden?dom.tutorial:!dom.result.hidden?dom.result:null;if(!panel)return;if(event.key==="Escape"){event.preventDefault();if(panel===dom.leave)dom.leaveContinue.click();else if(panel===dom.tutorial)dom.tutorialClose.click();else dom.resultStages.click();return;}if(event.key!=="Tab")return;const buttons=modalButtons(panel);if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
window.__animalBlockGroveSmoke={MISSIONS,startStage,getState:()=>({stageIndex,board:[...board],tray:tray.map(p=>({...p})),moves,score,lines,crosses,marks:[...marks],acorns:[...acorns],resultState}),setState:next=>{if(next.board)board=[...next.board];if(next.tray)tray=next.tray.map(p=>({...p}));if(Number.isFinite(next.moves))moves=next.moves;if(Number.isFinite(next.score))score=next.score;if(Number.isFinite(next.lines))lines=next.lines;if(Number.isFinite(next.crosses))crosses=next.crosses;if(next.marks)marks=new Set(next.marks);if(next.acorns)acorns=new Set(next.acorns);if(typeof next.resultState==="string")resultState=next.resultState;undoState=null;renderBattle();},placements:(i)=>allPlacements(tray[i]),bestHint,place,checkEnd:()=>{if(!remainingFits())finish(false,"board");return resultState;},finish,showStage:()=>{setScreen("stage");renderStage();}};
function runCampaignSmoke(){const clears=[];for(let i=0;i<MISSIONS.length;i++){startStage(i);for(let turn=0;turn<48&&!resultState;turn++){const best=bestHint();if(!best)break;place(best.i,best.a,true);}clears.push({stage:i+1,result:resultState,moves,score,lines,crosses,marks:marks.size,acorns:acorns.size,stones:board.filter(v=>v===7).length});}document.documentElement.dataset.wpBlockGroveSmoke=JSON.stringify({ok:clears.every(item=>item.result==="win"),clears});}
document.addEventListener("wp:block-grove-smoke-run",runCampaignSmoke);if(/[?&](?:trial|qa|smoke)=/.test(location.search)){const qa=document.createElement("button");qa.type="button";qa.id="blockGroveQaRun";qa.setAttribute("aria-label","Run 30 mission verification");qa.style.cssText="position:fixed;left:0;bottom:0;width:2px;height:2px;opacity:.001;z-index:9999;padding:0;border:0";qa.addEventListener("click",runCampaignSmoke);document.body.append(qa);}
dom.rail.addEventListener("scroll",()=>requestAnimationFrame(syncCenteredStageCard),{passive:true});window.addEventListener("resize",()=>requestAnimationFrame(syncCenteredStageCard),{passive:true});applyLocale();const assets=["../../assets/animal-block-grove-cover.webp","../../assets/animal-block-grove-background.webp","../../assets/weightplay-character-moss-shell-turtle-cutout.webp","../../assets/weightplay-character-rainbow-hop-mimi-clean-cutout.webp",...TILE_NAMES.map(n=>`../../assets/animal-block-grove-tile-${n}.webp`),"mark","acorn","stone","cross","hint","undo"].map(n=>n.includes("/")?n:objectUrl(n));let loaded=0;Promise.allSettled(assets.map(src=>new Promise(resolve=>{const img=new Image(),done=()=>{loaded++;dom.loadingFill.style.width=`${loaded/assets.length*100}%`;resolve();};img.onload=done;img.onerror=done;img.src=src;}))).then(()=>setTimeout(()=>{dom.loading.hidden=true;setScreen("main");renderMainProgress();window.WonderAnalytics?.track?.("game_view",{gameId:"animal-block-grove",release:"internal"});},160));
function settleAnimatedPlacement(clear,quiet=false){clear.forEach(i=>{board[i]=0;marks.delete(i);});if(tray.every(x=>x.used))drawTray();interactionLocked=false;dom.battle.dataset.animating="false";if(!quiet)renderBattle();if(checkWin()){finish(true);return true;}if(stageIndex!==INFINITE&&moves>=mission.limit){finish(false,"moves");return true;}if(!remainingFits())finish(false,"board");return true;}
function place(pieceIndex,anchor,quiet=false){if(interactionLocked)return false;const p=tray[pieceIndex];if(!p||p.used||!canPlace(p,anchor)){if(!quiet)showToast(tr("invalid"));return false;}undoState=snapshot();hintCells=[];const cells=cellsFor(p,anchor);cells.forEach(i=>{board[i]=p.tile;acorns.delete(i);});p.used=true;selected=-1;moves++;score+=cells.length*10;const fullRows=[],fullCols=[];for(let y=0;y<8;y++)if(board.slice(y*8,y*8+8).every(Boolean))fullRows.push(y);for(let x=0;x<8;x++)if(Array.from({length:8},(_,y)=>board[y*8+x]).every(Boolean))fullCols.push(x);const clear=new Set();fullRows.forEach(y=>{for(let x=0;x<8;x++)clear.add(y*8+x);});fullCols.forEach(x=>{for(let y=0;y<8;y++)clear.add(y*8+x);});if(clear.size){const count=fullRows.length+fullCols.length,bonus=count*120+Math.max(0,count-1)*100;score+=bonus;lines+=count;if(fullRows.length&&fullCols.length)crosses++;if(!quiet){interactionLocked=true;dom.battle.dataset.animating="true";renderBattle();showToast(tr("combo",{count,score:bonus}));requestAnimationFrame(()=>clear.forEach(i=>dom.board.children[i]?.classList.add("clearing")));const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;clearTimer=setTimeout(()=>{clearTimer=0;settleAnimatedPlacement(clear);},reduced?20:430);return true;}}return settleAnimatedPlacement(clear,quiet);}
const smokeStartStage=window.__animalBlockGroveSmoke.startStage,smokeSetState=window.__animalBlockGroveSmoke.setState;window.__animalBlockGroveSmoke.startStage=index=>{clearTimeout(clearTimer);clearTimer=0;interactionLocked=false;dom.battle.dataset.animating="false";smokeStartStage(index);};window.__animalBlockGroveSmoke.setState=next=>{clearTimeout(clearTimer);clearTimer=0;interactionLocked=false;dom.battle.dataset.animating="false";smokeSetState(next);};
dom.battle.addEventListener("click",event=>{if(interactionLocked){event.preventDefault();event.stopImmediatePropagation();}},{capture:true});dom.battle.addEventListener("keydown",event=>{if(interactionLocked){event.preventDefault();event.stopImmediatePropagation();}},{capture:true});
dom.rail.addEventListener("pointerdown",event=>{if(event.pointerType==="mouse"&&event.button!==0)return;stageDrag={pointerId:event.pointerId,startX:event.clientX,startScroll:dom.rail.scrollLeft,direction:event.pointerType==="mouse"?1:-1,moved:false};dom.rail.setPointerCapture?.(event.pointerId);});dom.rail.addEventListener("pointermove",event=>{if(!stageDrag||event.pointerId!==stageDrag.pointerId)return;const delta=event.clientX-stageDrag.startX;if(Math.abs(delta)>5)stageDrag.moved=true;if(stageDrag.moved){dom.rail.scrollLeft=stageDrag.startScroll+stageDrag.direction*delta;event.preventDefault();}});const finishStageDrag=event=>{if(!stageDrag||event.pointerId!==stageDrag.pointerId)return;const moved=stageDrag.moved;stageDrag=null;if(moved){suppressStageClick=true;settleStageRail();setTimeout(()=>{suppressStageClick=false;},0);}};dom.rail.addEventListener("pointerup",finishStageDrag);dom.rail.addEventListener("pointercancel",finishStageDrag);dom.rail.addEventListener("click",event=>{if(suppressStageClick){event.preventDefault();event.stopPropagation();}},{capture:true});dom.rail.addEventListener("scrollend",syncCenteredStageCard,{passive:true});
})();
