(()=>{"use strict";
const L=window.ANIMAL_BLOCK_GROVE_LOCALES||{},SAVE_KEY="weightplay_animal_block_grove_v1",INFINITE=30,TILE_NAMES=["leaf","paw","flower","star","ripple","acorn"],SHAPES=[
 {id:"single",c:[[0,0]]},{id:"dominoH",c:[[0,0],[1,0]]},{id:"dominoV",c:[[0,0],[0,1]]},{id:"line3H",c:[[0,0],[1,0],[2,0]]},{id:"line3V",c:[[0,0],[0,1],[0,2]]},{id:"line4H",c:[[0,0],[1,0],[2,0],[3,0]]},{id:"line4V",c:[[0,0],[0,1],[0,2],[0,3]]},{id:"square",c:[[0,0],[1,0],[0,1],[1,1]]},{id:"l3a",c:[[0,0],[0,1],[1,1]]},{id:"l3b",c:[[0,0],[1,0],[0,1]]},{id:"l3c",c:[[0,0],[1,0],[1,1]]},{id:"l3d",c:[[1,0],[0,1],[1,1]]},{id:"t4",c:[[0,0],[1,0],[2,0],[1,1]]},{id:"z4",c:[[0,0],[1,0],[1,1],[2,1]]},{id:"s4",c:[[1,0],[2,0],[0,1],[1,1]]},{id:"corner5",c:[[0,0],[0,1],[0,2],[1,2],[2,2]]}
];
const $=s=>document.querySelector(s),dom={loading:$("#loadingPanel"),loadingFill:$("#loadingFill"),main:$("#mainScreen"),stage:$("#stageScreen"),battle:$("#battleScreen"),locale:$("#localeSelect"),start:$("#startBtn"),mainProgress:$("#mainProgress"),stageBack:$("#stageBackBtn"),summary:$("#stageSummary"),campaign:$("#campaignTab"),challenge:$("#challengeTab"),chapterKicker:$("#chapterKicker"),chapterTitle:$("#chapterTitle"),chapterRule:$("#chapterRule"),rail:$("#stageRail"),battleBack:$("#battleBackBtn"),stageLabel:$("#stageLabel"),goal:$("#goalValue"),moves:$("#movesValue"),score:$("#scoreValue"),objectives:$("#objectiveRow"),board:$("#gameBoard"),tray:$("#pieceTray"),toast:$("#comboToast"),undo:$("#undoBtn"),hint:$("#hintBtn"),result:$("#resultPanel"),resultTitle:$("#resultTitle"),resultStars:$("#resultStars"),resultText:$("#resultText"),best:$("#bestText"),retry:$("#retryBtn"),resultStages:$("#resultStagesBtn"),next:$("#nextBtn"),leave:$("#leavePanel"),leaveContinue:$("#leaveContinueBtn"),leaveStages:$("#leaveStagesBtn"),tutorial:$("#tutorialPanel"),tutorialClose:$("#tutorialCloseBtn"),tutorialStart:$("#tutorialStartBtn"),ghost:$("#dragGhost")};
let locale=localStorage.getItem("weightPlayLocale")||localStorage.getItem("weightplayLocale")||"zh-Hant";if(!L[locale])locale="zh-Hant";
let save=loadSave(),mode="campaign",stageIndex=0,mission=null,board=Array(64).fill(0),tray=[],selected=-1,moves=0,score=0,lines=0,crosses=0,marks=new Set(),acorns=new Set(),initialMarks=0,initialAcorns=0,initialStones=0,undoState=null,rngState=1,resultState="",drag=null,hintCells=[],toastTimer=0,resultTimer=0;
function loadSave(){try{return Object.assign({unlocked:1,cleared:{},stars:{},best:{},infiniteBest:0,tutorial:false},JSON.parse(localStorage.getItem(SAVE_KEY)||"{}"));}catch{return{unlocked:1,cleared:{},stars:{},best:{},infiniteBest:0,tutorial:false};}}
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save));}
function tr(key,vars={}){let v=(L[locale]&&L[locale][key])??L.en?.[key]??key;if(typeof v!=="string")return v;return v.replace(/\{(\w+)\}/g,(_,k)=>vars[k]??"");}
function applyLocale(){document.documentElement.lang=locale;dom.locale.value=locale;document.title=`${tr("fullTitle")} | WeightPlay`;document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=tr(el.dataset.i18n);});document.querySelectorAll("[data-i18n-aria]").forEach(el=>el.setAttribute("aria-label",tr(el.dataset.i18nAria)));document.querySelectorAll("[data-i18n-alt]").forEach(el=>el.alt=tr(el.dataset.i18nAlt));renderMainProgress();if(!dom.stage.hidden)renderStage();if(!dom.battle.hidden)renderBattle();}
function setScreen(name){document.body.dataset.screen=name;dom.stage.hidden=name!=="stage";dom.battle.hidden=name!=="battle";window.dispatchEvent(new Event("resize"));requestAnimationFrame(()=>window.dispatchEvent(new Event("resize")));}
function rng(){rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;return rngState/4294967296;}
function missionFor(i){const chapter=Math.floor(i/5),slot=i%5+1;const m={index:i,chapter,seed:9473+i*7919,limit:10+chapter*2+slot,goals:{lines:Math.min(2+chapter+Math.floor(slot/2),8),score:0,marks:0,acorns:0,stones:0,cross:0}};if(chapter===0)m.goals.score=300+slot*120;if(chapter===1)m.goals.marks=1+Math.ceil(slot/2);if(chapter===2)m.goals.acorns=1+Math.ceil(slot/2);if(chapter===3)m.goals.stones=2+slot;if(chapter===4)m.goals.cross=1+Math.floor(slot/3);if(chapter===5){m.goals.score=900+slot*220;m.goals.marks=1+Math.floor(slot/2);m.goals.acorns=1+Math.floor(slot/2);m.goals.stones=2+slot;m.goals.cross=slot>=4?1:0;}return m;}
const MISSIONS=Array.from({length:30},(_,i)=>missionFor(i));
function starterFor(m){const b=Array(64).fill(0),holes=[];rngState=m.seed;const row=(m.index*3+1)%8,col=(m.index*5+2)%8;for(let x=0;x<8;x++){if(x!==col)b[row*8+x]=1+Math.floor(rng()*6);}holes.push(row*8+col);if(m.goals.cross){for(let y=0;y<8;y++){const idx=y*8+col;if(y!==row&&!b[idx])b[idx]=1+Math.floor(rng()*6);}holes.length=0;holes.push(row*8+col);}else if(m.goals.lines>=4){const row2=(row+3)%8,hole2=(col+2)%8;for(let x=0;x<8;x++)if(x!==hole2)b[row2*8+x]=1+Math.floor(rng()*6);holes.push(row2*8+hole2);}return{b,holes};}
function setupObjects(m,holes){marks=new Set();acorns=new Set();const free=Array.from({length:64},(_,i)=>i).filter(i=>!board[i]);for(let i=0;i<m.goals.marks;i++)marks.add(holes[i%holes.length]??free[i]);for(let i=0;i<m.goals.acorns;i++)acorns.add(free[(i*7+3)%free.length]);let placed=0,scan=(m.index*11+9)%64;while(placed<m.goals.stones){if(!board[scan]&&!marks.has(scan)&&!acorns.has(scan)){board[scan]=7;placed++;}scan=(scan+13)%64;}initialMarks=marks.size;initialAcorns=acorns.size;initialStones=board.filter(v=>v===7).length;}
function shapeById(id){return SHAPES.find(s=>s.id===id)||SHAPES[0];}
function drawTray(first=false){const easy=first||mission&&mission.chapter<2;tray=Array.from({length:3},(_,i)=>{let pool=easy?SHAPES.slice(0,12):SHAPES;let shape=pool[Math.floor(rng()*pool.length)];if(i===0&&(first||mission?.goals.cross))shape=SHAPES[0];return{id:`${moves}-${i}-${rngState}`,shape:shape.id,tile:1+Math.floor(rng()*6),used:false};});selected=-1;}
function startStage(index){clearTimeout(resultTimer);resultTimer=0;stageIndex=Math.max(0,Math.min(INFINITE,index));mission=index===INFINITE?{type:"infinite",index:INFINITE,chapter:5,seed:(Date.now()^performance.now())>>>0,limit:Infinity,goals:{lines:0,score:0,marks:0,acorns:0,stones:0,cross:0}}:MISSIONS[stageIndex];rngState=mission.seed||1;moves=score=lines=crosses=0;resultState="";undoState=null;hintCells=[];const starter=stageIndex===INFINITE?{b:Array(64).fill(0),holes:[]}:starterFor(mission);board=starter.b;setupObjects(mission,starter.holes);drawTray(true);dom.result.hidden=true;dom.leave.hidden=true;setScreen("battle");renderBattle();requestAnimationFrame(()=>dom.board.focus({preventScroll:true}));window.WonderAnalytics?.track?.("game_start",{gameId:"animal-block-grove",stage:index===INFINITE?"infinite":index+1,mode:index===INFINITE?"endless":"mission"});}
function renderMainProgress(){const cleared=Object.values(save.cleared||{}).filter(Boolean).length,stars=Object.values(save.stars||{}).reduce((a,b)=>a+Number(b||0),0);dom.mainProgress.textContent=tr("progress",{cleared,stars});}
function renderStage(){const cleared=Object.values(save.cleared||{}).filter(Boolean).length,stars=Object.values(save.stars||{}).reduce((a,b)=>a+Number(b||0),0);dom.summary.textContent=tr("summary",{cleared,stars});dom.campaign.setAttribute("aria-pressed",String(mode==="campaign"));dom.challenge.setAttribute("aria-pressed",String(mode==="challenge"));dom.stage.dataset.mode=mode;const chapter=Math.min(5,Math.floor(Math.max(0,Math.min(stageIndex,29))/5));dom.chapterKicker.textContent=mode==="campaign"?tr("chapter",{chapter:chapter+1}):tr("infinite");dom.chapterTitle.textContent=mode==="campaign"?tr("chapterTitles")[chapter]:tr("infinite");dom.chapterRule.textContent=mode==="campaign"?tr("chapterRules")[chapter]:tr("infiniteRule");dom.rail.innerHTML="";if(mode==="challenge"){const card=stageCard(INFINITE,true);card.classList.add("challenge-card","selected");dom.rail.append(card);}else MISSIONS.forEach((_,i)=>dom.rail.append(stageCard(i,i===stageIndex)));requestAnimationFrame(()=>{const target=dom.rail.querySelector(".selected")||dom.rail.querySelector(".stage-card");target?.scrollIntoView({behavior:"auto",inline:"center",block:"nearest"});window.dispatchEvent(new Event("resize"));});}
function stageCard(i,isSelected){const locked=i!==INFINITE&&i>=Number(save.unlocked||1),card=document.createElement("button");card.type="button";card.className=`stage-card${locked?" locked":""}${isSelected?" selected":""}`;card.dataset.stage=String(i);const best=i===INFINITE?Number(save.infiniteBest||0):Number(save.best?.[i]||0),stars=i===INFINITE?"∞":"★".repeat(save.stars?.[i]||0)+"☆".repeat(3-(save.stars?.[i]||0));card.innerHTML=`<span>${i===INFINITE?tr("infinite"):tr("mission",{stage:i+1})}</span><strong>${locked?tr("locked"):i===INFINITE?tr("infiniteRule"):tr("chapterTitles")[Math.floor(i/5)]}</strong><small><span>${tr("best",{score:best})}</span><span>${stars}</span></small>`;card.disabled=locked;card.addEventListener("click",()=>{stageIndex=i;renderStage();setTimeout(()=>startStage(i),90);});return card;}
function tileUrl(value){return`../../assets/animal-block-grove-tile-${TILE_NAMES[(Math.max(1,value)-1)%TILE_NAMES.length]}.webp`;}
function objectUrl(type){return`../../assets/animal-block-grove-icon-${type}.webp`;}
function renderBattle(){const infinite=stageIndex===INFINITE;dom.stageLabel.textContent=infinite?tr("infinite"):tr("mission",{stage:stageIndex+1});dom.goal.textContent=infinite?tr("infiniteBest",{score:save.infiniteBest||0}):tr("placements",{used:moves,limit:mission.limit});dom.moves.textContent=infinite?moves:`${moves}/${mission.limit}`;dom.score.textContent=score;renderObjectives();renderBoard();renderTray();dom.undo.disabled=!undoState||!!resultState;dom.hint.disabled=!!resultState;}
function renderObjectives(){const g=mission.goals,chips=[];if(stageIndex===INFINITE)chips.push(["score",tr("goalScore",{now:score,goal:"∞"}),false]);else{if(g.lines)chips.push(["cross",tr("goalLines",{now:lines,goal:g.lines}),lines>=g.lines]);if(g.score)chips.push(["cross",tr("goalScore",{now:score,goal:g.score}),score>=g.score]);if(g.marks)chips.push(["mark",tr("goalMarks",{now:initialMarks-marks.size,goal:g.marks}),marks.size===0]);if(g.acorns)chips.push(["acorn",tr("goalAcorns",{now:initialAcorns-acorns.size,goal:g.acorns}),acorns.size===0]);if(g.stones)chips.push(["stone",tr("goalStones",{now:initialStones-board.filter(v=>v===7).length,goal:g.stones}),board.filter(v=>v===7).length===0]);if(g.cross)chips.push(["cross",tr("goalCross",{now:crosses,goal:g.cross}),crosses>=g.cross]);}dom.objectives.innerHTML=chips.map(([icon,text,done])=>`<span class="objective-chip${done?" done":""}"><img src="${objectUrl(icon)}" alt=""><span>${text}</span></span>`).join("");}
function renderBoard(){if(!dom.board.children.length){for(let i=0;i<64;i++){const c=document.createElement("div");c.className="board-cell";c.dataset.index=i;dom.board.append(c);}}[...dom.board.children].forEach((cell,i)=>{cell.className="board-cell";cell.innerHTML="";if(board[i])cell.innerHTML+=`<img class="tile-image" src="${board[i]===7?objectUrl("stone"):tileUrl(board[i])}" alt="">`;if(marks.has(i))cell.innerHTML+=`<img class="object-image" src="${objectUrl("mark")}" alt="">`;if(acorns.has(i))cell.innerHTML+=`<img class="object-image" src="${objectUrl("acorn")}" alt="">`;if(hintCells.includes(i))cell.classList.add("hint");});}
function pieceBounds(shape){const xs=shape.c.map(v=>v[0]),ys=shape.c.map(v=>v[1]);return{w:Math.max(...xs)+1,h:Math.max(...ys)+1};}
function pieceMarkup(piece,large=false){const s=shapeById(piece.shape),b=pieceBounds(s),bits=new Set(s.c.map(([x,y])=>`${x},${y}`));let html="";for(let y=0;y<b.h;y++)for(let x=0;x<b.w;x++)html+=bits.has(`${x},${y}`)?`<i class="piece-bit" style="background-image:url('${tileUrl(piece.tile)}')"></i>`:`<i></i>`;return`<span class="piece-grid" style="grid-template-columns:repeat(${b.w},${large?34:20}px);grid-template-rows:repeat(${b.h},${large?34:20}px)">${html}</span>`;}
function renderTray(){dom.tray.innerHTML="";tray.forEach((p,i)=>{const btn=document.createElement("button");btn.type="button";btn.className=`piece-card${p.used?" used":""}${selected===i?" selected":""}`;btn.dataset.piece=i;btn.setAttribute("aria-label",`${tr("trayLabel")} ${i+1}`);btn.innerHTML=pieceMarkup(p);btn.addEventListener("pointerdown",e=>beginDrag(e,i));btn.addEventListener("click",()=>{if(!p.used){selected=i;hintCells=[];renderBattle();}});dom.tray.append(btn);});}
function canPlace(piece,anchor){const shape=shapeById(piece.shape),ax=anchor%8,ay=Math.floor(anchor/8);return shape.c.every(([dx,dy])=>{const x=ax+dx,y=ay+dy;return x>=0&&x<8&&y>=0&&y<8&&!board[y*8+x];});}
function cellsFor(piece,anchor){const ax=anchor%8,ay=Math.floor(anchor/8);return shapeById(piece.shape).c.map(([dx,dy])=>(ay+dy)*8+ax+dx);}
function allPlacements(piece){const out=[];for(let i=0;i<64;i++)if(canPlace(piece,i))out.push(i);return out;}
function remainingFits(){return tray.some(p=>!p.used&&allPlacements(p).length);}
function snapshot(){return{board:[...board],tray:tray.map(p=>({...p})),selected,moves,score,lines,crosses,marks:[...marks],acorns:[...acorns],rngState};}
function restore(s){board=[...s.board];tray=s.tray.map(p=>({...p}));selected=s.selected;moves=s.moves;score=s.score;lines=s.lines;crosses=s.crosses;marks=new Set(s.marks);acorns=new Set(s.acorns);rngState=s.rngState;hintCells=[];resultState="";dom.result.hidden=true;renderBattle();}
function evaluate(piece,anchor){if(!canPlace(piece,anchor))return-Infinity;const copy=[...board];cellsFor(piece,anchor).forEach(i=>copy[i]=piece.tile);let rows=0,cols=0;for(let y=0;y<8;y++)if(copy.slice(y*8,y*8+8).every(Boolean))rows++;for(let x=0;x<8;x++)if(Array.from({length:8},(_,y)=>copy[y*8+x]).every(Boolean))cols++;const center=3.5-Math.abs(anchor%8-3.5)+3.5-Math.abs(Math.floor(anchor/8)-3.5);return(rows+cols)*1000+(rows&&cols?1500:0)+cellsFor(piece,anchor).filter(i=>acorns.has(i)).length*800+center-copy.filter(Boolean).length*.2;}
function place(pieceIndex,anchor){const p=tray[pieceIndex];if(!p||p.used||!canPlace(p,anchor)){showToast(tr("invalid"));return false;}undoState=snapshot();hintCells=[];const cells=cellsFor(p,anchor);cells.forEach(i=>{board[i]=p.tile;acorns.delete(i);});p.used=true;selected=-1;moves++;score+=cells.length*10;const fullRows=[],fullCols=[];for(let y=0;y<8;y++)if(board.slice(y*8,y*8+8).every(Boolean))fullRows.push(y);for(let x=0;x<8;x++)if(Array.from({length:8},(_,y)=>board[y*8+x]).every(Boolean))fullCols.push(x);const clear=new Set();fullRows.forEach(y=>{for(let x=0;x<8;x++)clear.add(y*8+x);});fullCols.forEach(x=>{for(let y=0;y<8;y++)clear.add(y*8+x);});if(clear.size){const count=fullRows.length+fullCols.length,bonus=count*120+Math.max(0,count-1)*100;score+=bonus;lines+=count;if(fullRows.length&&fullCols.length)crosses++;clear.forEach(i=>{board[i]=0;marks.delete(i);});showToast(tr("combo",{count,score:bonus}));}if(tray.every(x=>x.used))drawTray();renderBattle();if(checkWin()){finish(true);return true;}if(stageIndex!==INFINITE&&moves>=mission.limit){finish(false,"moves");return true;}if(!remainingFits())finish(false,"board");return true;}
function checkWin(){if(stageIndex===INFINITE)return false;const g=mission.goals;return(!g.lines||lines>=g.lines)&&(!g.score||score>=g.score)&&(!g.marks||marks.size===0)&&(!g.acorns||acorns.size===0)&&(!g.stones||board.filter(v=>v===7).length===0)&&(!g.cross||crosses>=g.cross);}
function finish(win,reason=""){if(resultState)return;resultState=stageIndex===INFINITE?"infinite":win?"win":"lose";const old=stageIndex===INFINITE?Number(save.infiniteBest||0):Number(save.best?.[stageIndex]||0);if(stageIndex===INFINITE){save.infiniteBest=Math.max(old,score);dom.resultTitle.textContent=tr("infiniteTitle");dom.resultStars.textContent="∞";dom.resultText.textContent=tr("infiniteText",{moves,score});dom.best.textContent=score>old?tr("newBest"):tr("best",{score:save.infiniteBest});dom.next.hidden=true;}else if(win){const remain=mission.limit-moves,stars=remain>=Math.ceil(mission.limit*.35)?3:remain>=1?2:1;save.cleared[stageIndex]=true;save.stars[stageIndex]=Math.max(save.stars?.[stageIndex]||0,stars);save.best[stageIndex]=Math.max(old,score);save.unlocked=Math.max(Number(save.unlocked||1),Math.min(30,stageIndex+2));dom.resultTitle.textContent=tr("winTitle");dom.resultStars.textContent="★".repeat(stars)+"☆".repeat(3-stars);dom.resultText.textContent=tr("winText",{stage:stageIndex+1,moves,score});dom.best.textContent=score>old?tr("newBest"):tr("best",{score:save.best[stageIndex]});dom.next.hidden=stageIndex===29;}else{dom.resultTitle.textContent=tr("loseTitle");dom.resultStars.textContent="";dom.resultText.textContent=tr(reason==="moves"?"loseMoves":"loseBoard");dom.best.textContent=tr("best",{score:old});dom.next.hidden=true;}persist();resultTimer=setTimeout(()=>{resultTimer=0;dom.result.hidden=false;dom.retry.focus({preventScroll:true});},260);window.WonderAnalytics?.track?.(win?"game_complete":"game_fail",{gameId:"animal-block-grove",stage:stageIndex===INFINITE?"infinite":stageIndex+1,score,moves,reason});}
function showToast(text){clearTimeout(toastTimer);dom.toast.textContent=text;toastTimer=setTimeout(()=>dom.toast.textContent="",1200);}
function showHint(){let best=null;tray.forEach((p,i)=>{if(p.used)return;allPlacements(p).forEach(a=>{const value=evaluate(p,a);if(!best||value>best.value)best={i,a,value};});});if(!best){showToast(tr("noFit"));return;}selected=best.i;hintCells=cellsFor(tray[best.i],best.a);showToast(tr("hintReady"));renderBattle();}
function boardAnchorFromPoint(x,y){const r=dom.board.getBoundingClientRect();if(x<r.left||x>r.right||y<r.top||y>r.bottom)return-1;const col=Math.min(7,Math.max(0,Math.floor((x-r.left)/r.width*8))),row=Math.min(7,Math.max(0,Math.floor((y-r.top)/r.height*8)));return row*8+col;}
function preview(anchor,pieceIndex){[...dom.board.children].forEach(c=>c.classList.remove("preview","invalid"));if(anchor<0)return;const p=tray[pieceIndex];if(!p)return;const valid=canPlace(p,anchor),cells=cellsFor(p,anchor).filter(i=>i>=0&&i<64);cells.forEach(i=>dom.board.children[i]?.classList.add("preview",...(valid?[]:["invalid"])));}
function beginDrag(e,i){if(tray[i]?.used||resultState)return;selected=i;drag={i,moved:false,startX:e.clientX,startY:e.clientY};dom.ghost.innerHTML=pieceMarkup(tray[i],true);dom.ghost.hidden=false;moveGhost(e);try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}renderTray();}
function moveGhost(e){if(!drag)return;dom.ghost.style.left=`${e.clientX}px`;dom.ghost.style.top=`${e.clientY}px`;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>8)drag.moved=true;preview(boardAnchorFromPoint(e.clientX,e.clientY),drag.i);}
function endDrag(e){if(!drag)return;const d=drag;drag=null;dom.ghost.hidden=true;preview(-1,d.i);const anchor=boardAnchorFromPoint(e.clientX,e.clientY);if(d.moved&&anchor>=0)place(d.i,anchor);}
document.addEventListener("pointermove",moveGhost,{passive:true});document.addEventListener("pointerup",endDrag);document.addEventListener("pointercancel",endDrag);
dom.board.addEventListener("click",e=>{if(drag||resultState)return;const cell=e.target.closest(".board-cell");if(!cell)return;if(selected<0){showToast(tr("selectPiece"));return;}place(selected,Number(cell.dataset.index));});
dom.board.addEventListener("keydown",e=>{if(resultState)return;let cursor=Number(dom.board.dataset.cursor||0);if(e.key==="ArrowLeft")cursor=Math.max(0,cursor-1);else if(e.key==="ArrowRight")cursor=Math.min(63,cursor+1);else if(e.key==="ArrowUp")cursor=Math.max(0,cursor-8);else if(e.key==="ArrowDown")cursor=Math.min(63,cursor+8);else if((e.key==="Enter"||e.key===" ")&&selected>=0){place(selected,cursor);e.preventDefault();return;}else return;e.preventDefault();dom.board.dataset.cursor=cursor;hintCells=[cursor];renderBoard();});
dom.start.addEventListener("click",()=>{mode="campaign";setScreen("stage");renderStage();if(!save.tutorial)dom.tutorial.hidden=false;});dom.stageBack.addEventListener("click",()=>{setScreen("main");renderMainProgress();});dom.campaign.addEventListener("click",()=>{mode="campaign";stageIndex=Math.min(29,Math.max(0,Number(save.unlocked||1)-1));renderStage();});dom.challenge.addEventListener("click",()=>{mode="challenge";stageIndex=INFINITE;renderStage();});dom.battleBack.addEventListener("click",()=>{if(resultState){mode=stageIndex===INFINITE?"challenge":"campaign";setScreen("stage");renderStage();}else dom.leave.hidden=false;});dom.leaveContinue.addEventListener("click",()=>{dom.leave.hidden=true;dom.board.focus({preventScroll:true});});dom.leaveStages.addEventListener("click",()=>{dom.leave.hidden=true;mode=stageIndex===INFINITE?"challenge":"campaign";setScreen("stage");renderStage();});dom.undo.addEventListener("click",()=>{if(undoState){const s=undoState;undoState=null;restore(s);}});dom.hint.addEventListener("click",showHint);dom.retry.addEventListener("click",()=>startStage(stageIndex));dom.resultStages.addEventListener("click",()=>{mode=stageIndex===INFINITE?"challenge":"campaign";setScreen("stage");renderStage();});dom.next.addEventListener("click",()=>startStage(Math.min(29,stageIndex+1)));dom.tutorialClose.addEventListener("click",()=>{save.tutorial=true;persist();dom.tutorial.hidden=true;});dom.tutorialStart.addEventListener("click",()=>{save.tutorial=true;persist();dom.tutorial.hidden=true;startStage(0);});dom.locale.addEventListener("change",()=>{locale=dom.locale.value;localStorage.setItem("weightPlayLocale",locale);applyLocale();});
window.__animalBlockGroveSmoke={MISSIONS,startStage,getState:()=>({stageIndex,board:[...board],tray:tray.map(p=>({...p})),moves,score,lines,crosses,marks:[...marks],acorns:[...acorns],resultState}),placements:(i)=>allPlacements(tray[i]),place,finish,showStage:()=>{setScreen("stage");renderStage();}};
applyLocale();const assets=["../../assets/animal-block-grove-cover.webp","../../assets/animal-block-grove-background.webp","../../assets/weightplay-character-moss-shell-turtle-cutout.webp","../../assets/weightplay-character-rainbow-hop-mimi-clean-cutout.webp",...TILE_NAMES.map(n=>`../../assets/animal-block-grove-tile-${n}.webp`),"mark","acorn","stone","cross","hint","undo"].map(n=>n.includes("/")?n:objectUrl(n));let loaded=0;Promise.allSettled(assets.map(src=>new Promise(resolve=>{const img=new Image(),done=()=>{loaded++;dom.loadingFill.style.width=`${loaded/assets.length*100}%`;resolve();};img.onload=done;img.onerror=done;img.src=src;}))).then(()=>setTimeout(()=>{dom.loading.hidden=true;setScreen("main");renderMainProgress();window.WonderAnalytics?.track?.("game_view",{gameId:"animal-block-grove",release:"internal"});},160));
})();
