(function () {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const locales = window.ACORN_AUCTION_LOCALES || {};
  const rounds = [
    { id: 1, name: "round1", hint: "hint1", request: "request1", animal: "animal1", count: 3, budget: 5, answer: 1, lots: [[2, 4], [3, 5], [4, 6]] },
    { id: 2, name: "round2", hint: "hint2", request: "request2", animal: "animal2", count: 4, budget: 6, answer: 1, lots: [[3, 4], [4, 6], [5, 8]] },
    { id: 3, name: "round3", hint: "hint3", request: "request3", animal: "animal3", count: 2, budget: 7, answer: 0, lots: [[2, 7], [3, 5], [4, 8]] }
  ];
  let locale = localStorage.getItem("weightplay-acorn-auction-locale") || "en";
  if (!locales[locale]) locale = "en";
  let sound = localStorage.getItem("weightplay-acorn-auction-sound") !== "off";
  let roundIndex = 0; let phase = "main"; let picks = 0; let sessionPicks = 0; let solved = new Set(); let feedback = ""; let timer = null;
  const copy = (key, vars = {}) => Object.entries(vars).reduce((out, [name, value]) => out.replaceAll(`{${name}}`, String(value)), (locales[locale] || locales.en)[key] || locales.en[key] || key);
  const bestValue = () => Number(localStorage.getItem("weightplay-acorn-auction-best-v1") || 0) || "—";
  const announce = (name, data = {}) => { window.dataLayer = window.dataLayer || []; window.dataLayer.push({ event: `acorn_auction_${name}`, round: roundIndex + 1, picks, ...data }); };
  function show(screen) { phase = screen; document.querySelectorAll("[data-screen]").forEach((node) => { node.hidden = node.dataset.screen !== screen; }); $("settingsPanel").hidden = true; $("backBtn").hidden = screen === "main"; }
  function renderStatic() { document.documentElement.lang = locale === "zh-Hant" ? "zh-Hant" : "en"; document.documentElement.dir = "ltr"; document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = copy(node.dataset.i18n); }); $("backBtn").setAttribute("aria-label", copy("close")); $("settingsBtn").setAttribute("aria-label", copy("settings")); $("closeSettings").setAttribute("aria-label", copy("close")); $("localeSelect").setAttribute("aria-label", copy("language")); $("soundBtn").textContent = sound ? copy("on") : copy("off"); $("soundBtn").setAttribute("aria-pressed", String(sound)); $("best").textContent = copy("best", { best: bestValue() }); renderStages(); renderBattle(); renderResult(); }
  function renderStages() { const root = $("stageList"); if (!root) return; root.replaceChildren(); rounds.forEach((round, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "stage-card"; button.dataset.roundIndex = String(index); button.innerHTML = `<span><strong>${copy(round.name)}</strong><small>${copy(round.hint)}</small></span><span class="arrow">${solved.has(index) ? "✓" : "→"}</span>`; button.addEventListener("click", () => startRound(index, true)); root.appendChild(button); }); }
  function clearTimer() { if (timer) { clearTimeout(timer); timer = null; } }
  function startRound(index, fromStage = false) { clearTimer(); roundIndex = index; picks = 0; feedback = ""; if (index === 0 || fromStage) sessionPicks = 0; show("battle"); phase = "choose"; renderBattle(); announce("start"); }
  function replayRound() { phase = "choose"; feedback = ""; renderBattle(); }
  function renderBattle() { if (!$("lotCards") || phase === "main" || phase === "stage" || phase === "result") return; const round = rounds[roundIndex]; $("roundTitle").textContent = copy(round.name); $("progressPill").textContent = `${roundIndex + 1} / ${rounds.length}`; $("requestTitle").textContent = `${copy("request")} · ${copy(round.animal)}`; $("requestText").textContent = copy(round.request); $("prompt").textContent = feedback === "wrong" ? copy("wrong") : feedback === "correct" ? copy("correct") : copy("prompt"); const root = $("lotCards"); root.replaceChildren(); round.lots.forEach(([count, cost], index) => { const button = document.createElement("button"); button.type = "button"; button.className = `lot-card ${feedback === "correct" && index === round.answer ? "is-correct" : ""}`; button.disabled = phase !== "choose"; button.setAttribute("aria-label", copy("lotLabel", { count: index + 1 }) + ": " + copy("lot", { count, cost })); button.innerHTML = `<span class="lot-icon" aria-hidden="true">◆</span><strong>${copy("lotLabel", { count: index + 1 })}</strong><span>${copy("lot", { count, cost })}</span>`; button.addEventListener("click", () => chooseLot(index)); root.appendChild(button); }); $("resetBtn").disabled = phase === "complete"; $("status").textContent = copy("selected", { count: picks }); $("status").className = feedback === "correct" ? "status good" : feedback === "wrong" ? "status try" : "status"; }
  function chooseLot(index) { if (phase !== "choose") return; const round = rounds[roundIndex]; picks += 1; sessionPicks += 1; if (index !== round.answer) { feedback = "wrong"; phase = "retry"; announce("wrong", { lot: index + 1 }); renderBattle(); timer = setTimeout(replayRound, 760); return; } solved.add(roundIndex); feedback = "correct"; phase = "complete"; announce("complete", { lot: index + 1 }); renderBattle(); timer = setTimeout(() => { show("result"); renderResult(); }, 420); }
  function renderResult() { if (!$("resultText")) return; const complete = solved.size === rounds.length; $("resultTitle").textContent = complete ? copy("resultTitle") : copy("resultRound"); $("resultText").textContent = complete ? copy("resultAll", { best: bestValue() }) : copy("resultText", { count: solved.size, picks }); $("nextBtn").hidden = complete; $("resultMapBtn").hidden = !complete; if (complete) { const old = Number(localStorage.getItem("weightplay-acorn-auction-best-v1") || 0); if (!old || sessionPicks < old) localStorage.setItem("weightplay-acorn-auction-best-v1", String(sessionPicks)); $("resultText").textContent = copy("resultAll", { best: Math.min(old || sessionPicks, sessionPicks) }); } }
  function nextRound() { const next = roundIndex + 1; if (next < rounds.length) startRound(next); else { show("stage"); renderStages(); } }
  function goBack() { clearTimer(); if (["battle", "choose", "retry", "complete"].includes(phase)) { show("stage"); renderStages(); } else if (phase === "stage" || phase === "result") show("main"); }
  function bind() { $("startBtn").addEventListener("click", () => startRound(0)); $("mapBtn").addEventListener("click", () => { show("stage"); renderStages(); }); $("resultMapBtn").addEventListener("click", () => { show("stage"); renderStages(); }); $("nextBtn").addEventListener("click", nextRound); $("resetBtn").addEventListener("click", () => startRound(roundIndex)); $("backMarketBtn").addEventListener("click", () => { show("stage"); renderStages(); }); $("backBtn").addEventListener("click", goBack); $("settingsBtn").addEventListener("click", () => { $("settingsPanel").hidden = false; }); $("closeSettings").addEventListener("click", () => { $("settingsPanel").hidden = true; }); $("soundBtn").addEventListener("click", () => { sound = !sound; localStorage.setItem("weightplay-acorn-auction-sound", sound ? "on" : "off"); renderStatic(); }); $("localeSelect").addEventListener("change", (event) => { locale = event.target.value; localStorage.setItem("weightplay-acorn-auction-locale", locale); renderStatic(); }); }
  function boot() { bind(); $("localeSelect").value = locale; $("loading").hidden = true; $("app").hidden = false; show("main"); renderStatic(); announce("loaded"); }
  window.__ACORN_AUCTION_TEST__ = { rounds, startRound, chooseLot, getState: () => ({ roundIndex, phase, solved: [...solved], picks, screen: phase }) };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot, { once: true }); else boot();
}());
