(function () {
  "use strict";
  window.ACORN_AUCTION_LOCALES = {
    en: {
      loading: "Opening the acorn market…", title: "Acorn Auction", kicker: "A gentle choice puzzle", world: "Moonlit woodland market", intro: "Read each animal's request, then choose the one acorn lot that fits the count and budget.", start: "Open the market", choose: "Choose a round", best: "Best careful picks: {best}", rounds: "Market rounds", marketRound: "Market round", request: "Request", prompt: "Choose the lot that matches both clues.", lot: "{count} acorns · {cost} tokens", lotLabel: "Acorn lot {count}", reset: "Start this round over", finished: "Market complete", resultTitle: "Every request is ready!", resultRound: "A fair exchange!", next: "Next request", settings: "Settings", sound: "Sound", language: "Language", on: "On", off: "Off", close: "Close", wrong: "That lot misses one clue. Read the request again and try once more.", correct: "A careful choice! The request is ready.", selected: "Picks this round: {count}", resultText: "{count} of 3 requests are ready. This round took {picks} picks.", resultAll: "All three requests are ready. Fewest careful picks: {best}.", round1: "Squirrel's basket", round2: "Rabbit's lantern", round3: "Otter's picnic", request1: "Squirrel needs exactly 3 acorns and can spend at most 5 tokens.", request2: "Rabbit needs exactly 4 acorns and can spend at most 6 tokens.", request3: "Otter needs exactly 2 acorns and can spend at most 7 tokens.", animal1: "Squirrel", animal2: "Rabbit", animal3: "Otter", hint1: "Count before you bid", hint2: "The lantern needs a fuller basket", hint3: "Small lot, generous budget"
    },
    "zh-Hant": {
      loading: "正在開啟橡果市集⋯", title: "橡果競標", kicker: "溫柔的選擇益智", world: "月光林地市集", intro: "讀懂每隻動物的需求，再挑出同時符合數量與預算的一份橡果批次。", start: "開啟市集", choose: "選擇回合", best: "最佳精準選擇：{best}", rounds: "市集回合", marketRound: "市集回合", request: "需求", prompt: "挑出同時符合兩個線索的批次。", lot: "{count} 枚橡果・{cost} 枚代幣", lotLabel: "橡果批次 {count}", reset: "重新開始本回合", finished: "市集完成", resultTitle: "每份需求都準備好了！", resultRound: "公平的交換！", next: "下一份需求", settings: "設定", sound: "聲音", language: "語言", on: "開", off: "關", close: "關閉", wrong: "這份批次漏掉了一個線索。再讀一次需求，重新試試看。", correct: "精準的選擇！需求準備好了。", selected: "本回合選擇：{count}", resultText: "已準備 {count} / 3 份需求。本回合用了 {picks} 次選擇。", resultAll: "三份需求都準備好了。最少精準選擇：{best}。", round1: "松鼠的籃子", round2: "兔子的燈籠", round3: "水獺的野餐", request1: "松鼠需要剛好 3 枚橡果，最多能花 5 枚代幣。", request2: "兔子需要剛好 4 枚橡果，最多能花 6 枚代幣。", request3: "水獺需要剛好 2 枚橡果，最多能花 7 枚代幣。", animal1: "松鼠", animal2: "兔子", animal3: "水獺", hint1: "先數數再競標", hint2: "燈籠需要更滿的籃子", hint3: "小批次，大預算"
    },
    "zh-Hans": {
      loading: "正在打开橡果市集⋯", title: "橡果竞标", kicker: "温和的选择益智游戏", world: "月光林地市集", intro: "读懂每只动物的需求，再挑出同时符合数量和预算的一份橡果批次。", start: "打开市集", choose: "选择回合", best: "最佳精准选择：{best}", rounds: "市集回合", marketRound: "市集回合", request: "需求", prompt: "挑出同时符合两个线索的批次。", lot: "{count} 枚橡果 · {cost} 枚代币", lotLabel: "橡果批次 {count}", reset: "重新开始本回合", finished: "市集完成", resultTitle: "每份需求都准备好了！", resultRound: "公平的交换！", next: "下一份需求", settings: "设置", sound: "声音", language: "语言", on: "开", off: "关", close: "关闭", wrong: "这份批次漏掉了一个线索。再读一次需求，重新试试。", correct: "精准的选择！需求准备好了。", selected: "本回合选择：{count}", resultText: "已准备 {count} / 3 份需求。本回合用了 {picks} 次选择。", resultAll: "三份需求都准备好了。最少精准选择：{best}。", round1: "松鼠的篮子", round2: "兔子的灯笼", round3: "水獭的野餐", request1: "松鼠需要正好 3 枚橡果，最多能花 5 枚代币。", request2: "兔子需要正好 4 枚橡果，最多能花 6 枚代币。", request3: "水獭需要正好 2 枚橡果，最多能花 7 枚代币。", animal1: "松鼠", animal2: "兔子", animal3: "水獭", hint1: "先数数再竞标", hint2: "灯笼需要更满的篮子", hint3: "小批次，大预算"
    },
    ja: {
      loading: "どんぐり市場を開いています…", title: "どんぐりオークション", kicker: "やさしい選択パズル", world: "月明かりの森の市場", intro: "動物の注文を読み、数と予算の両方に合うどんぐりの束を選びましょう。", start: "市場を開く", choose: "ラウンドを選ぶ", best: "最少の慎重な選択：{best}", rounds: "市場ラウンド", marketRound: "市場ラウンド", request: "注文", prompt: "2つの条件に合う束を選びましょう。", lot: "どんぐり {count}個・トークン {cost}", lotLabel: "どんぐりの束 {count}", reset: "このラウンドをやり直す", finished: "市場クリア", resultTitle: "すべての注文がそろいました！", resultRound: "公平な交換！", next: "次の注文", settings: "設定", sound: "サウンド", language: "言語", on: "オン", off: "オフ", close: "閉じる", wrong: "この束は条件を1つ満たしません。注文を読み直してもう一度。", correct: "ていねいな選択です！注文に合いました。", selected: "このラウンドの選択：{count}", resultText: "注文 {count} / 3 件を準備。このラウンドの選択回数：{picks}。", resultAll: "3件の注文をすべて準備。市場の最少選択回数：{best}。", round1: "リスのかご", round2: "ウサギのランタン", round3: "カワウソのピクニック", request1: "リスはどんぐりをちょうど3個、トークンを5まで使えます。", request2: "ウサギはどんぐりをちょうど4個、トークンを6まで使えます。", request3: "カワウソはどんぐりをちょうど2個、トークンを7まで使えます。", animal1: "リス", animal2: "ウサギ", animal3: "カワウソ", hint1: "数えてから入札", hint2: "ランタンには多めのかご", hint3: "小さな束、ゆとりの予算"
    },
    ko: {
      loading: "도토리 시장을 여는 중…", title: "도토리 경매", kicker: "차분한 선택 퍼즐", world: "달빛 숲 시장", intro: "동물의 요청을 읽고 수량과 예산에 모두 맞는 도토리 묶음을 골라 보세요.", start: "시장 열기", choose: "라운드 선택", best: "가장 신중한 선택: {best}", rounds: "시장 라운드", marketRound: "시장 라운드", request: "요청", prompt: "두 단서에 모두 맞는 묶음을 고르세요.", lot: "도토리 {count}개 · 토큰 {cost}", lotLabel: "도토리 묶음 {count}", reset: "이 라운드 다시 시작", finished: "시장 완료", resultTitle: "모든 요청을 준비했어요!", resultRound: "공정한 교환이에요!", next: "다음 요청", settings: "설정", sound: "소리", language: "언어", on: "켜짐", off: "꺼짐", close: "닫기", wrong: "이 묶음은 단서 하나가 맞지 않아요. 요청을 다시 읽고 시도해 보세요.", correct: "신중한 선택이에요! 요청에 맞아요.", selected: "이번 라운드 선택: {count}", resultText: "요청 {count} / 3개를 준비했어요. 이번 라운드 선택: {picks}번.", resultAll: "세 요청을 모두 준비했어요. 시장 최소 선택: {best}번.", round1: "다람쥐의 바구니", round2: "토끼의 등불", round3: "수달의 소풍", request1: "다람쥐는 도토리 3개가 정확히 필요하고 토큰은 최대 5개까지 쓸 수 있어요.", request2: "토끼는 도토리 4개가 정확히 필요하고 토큰은 최대 6개까지 쓸 수 있어요.", request3: "수달은 도토리 2개가 정확히 필요하고 토큰은 최대 7개까지 쓸 수 있어요.", animal1: "다람쥐", animal2: "토끼", animal3: "수달", hint1: "입찰 전에 세어 보세요", hint2: "등불에는 더 가득한 바구니", hint3: "작은 묶음, 넉넉한 예산"
    },
    es: {
      loading: "Abriendo el mercado de bellotas…", title: "Subasta de Bellotas", kicker: "Un rompecabezas de elecciones tranquilas", world: "Mercado del bosque lunar", intro: "Lee el pedido de cada animal y elige el lote de bellotas que encaje con la cantidad y el presupuesto.", start: "Abrir el mercado", choose: "Elegir ronda", best: "Menos elecciones cuidadosas: {best}", rounds: "Rondas del mercado", marketRound: "Ronda del mercado", request: "Pedido", prompt: "Elige el lote que cumpla las dos pistas.", lot: "{count} bellotas · {cost} fichas", lotLabel: "Lote de bellotas {count}", reset: "Repetir esta ronda", finished: "Mercado completo", resultTitle: "¡Todos los pedidos están listos!", resultRound: "¡Un intercambio justo!", next: "Siguiente pedido", settings: "Ajustes", sound: "Sonido", language: "Idioma", on: "Activado", off: "Desactivado", close: "Cerrar", wrong: "A este lote le falta una pista. Lee el pedido otra vez e inténtalo.", correct: "¡Una elección cuidadosa! El pedido está listo.", selected: "Elecciones de esta ronda: {count}", resultText: "Pedidos listos: {count} de 3. Esta ronda necesitó {picks} elecciones.", resultAll: "Los tres pedidos están listos. Menos elecciones del mercado: {best}.", round1: "La cesta de la ardilla", round2: "El farol del conejo", round3: "El picnic de la nutria", request1: "La ardilla necesita exactamente 3 bellotas y puede gastar como máximo 5 fichas.", request2: "El conejo necesita exactamente 4 bellotas y puede gastar como máximo 6 fichas.", request3: "La nutria necesita exactamente 2 bellotas y puede gastar como máximo 7 fichas.", animal1: "Ardilla", animal2: "Conejo", animal3: "Nutria", hint1: "Cuenta antes de pujar", hint2: "El farol necesita una cesta más llena", hint3: "Lote pequeño, presupuesto amplio"
    },
    "pt-BR": {
      loading: "Abrindo o mercado de bolotas…", title: "Leilão de Bolotas", kicker: "Um quebra-cabeça de escolhas tranquilas", world: "Mercado da floresta ao luar", intro: "Leia o pedido de cada animal e escolha o lote de bolotas que combina com a quantidade e o orçamento.", start: "Abrir o mercado", choose: "Escolher rodada", best: "Menos escolhas cuidadosas: {best}", rounds: "Rodadas do mercado", marketRound: "Rodada do mercado", request: "Pedido", prompt: "Escolha o lote que combina com as duas pistas.", lot: "{count} bolotas · {cost} fichas", lotLabel: "Lote de bolotas {count}", reset: "Recomeçar esta rodada", finished: "Mercado completo", resultTitle: "Todos os pedidos estão prontos!", resultRound: "Uma troca justa!", next: "Próximo pedido", settings: "Configurações", sound: "Som", language: "Idioma", on: "Ligado", off: "Desligado", close: "Fechar", wrong: "Este lote não combina com uma pista. Leia o pedido de novo e tente outra vez.", correct: "Uma escolha cuidadosa! O pedido está pronto.", selected: "Escolhas nesta rodada: {count}", resultText: "Pedidos prontos: {count} de 3. Esta rodada levou {picks} escolhas.", resultAll: "Os três pedidos estão prontos. Menos escolhas no mercado: {best}.", round1: "A cesta do esquilo", round2: "A lanterna do coelho", round3: "O piquenique da lontra", request1: "O esquilo precisa de exatamente 3 bolotas e pode gastar no máximo 5 fichas.", request2: "O coelho precisa de exatamente 4 bolotas e pode gastar no máximo 6 fichas.", request3: "A lontra precisa de exatamente 2 bolotas e pode gastar no máximo 7 fichas.", animal1: "Esquilo", animal2: "Coelho", animal3: "Lontra", hint1: "Conte antes de dar o lance", hint2: "A lanterna precisa de uma cesta mais cheia", hint3: "Lote pequeno, orçamento generoso"
    },
    fr: {
      loading: "Ouverture du marché aux glands…", title: "Enchères de glands", kicker: "Un doux puzzle de choix", world: "Marché de la forêt au clair de lune", intro: "Lis la demande de chaque animal, puis choisis le lot de glands qui respecte la quantité et le budget.", start: "Ouvrir le marché", choose: "Choisir une manche", best: "Minimum de choix attentifs : {best}", rounds: "Manches du marché", marketRound: "Manche du marché", request: "Demande", prompt: "Choisis le lot qui respecte les deux indices.", lot: "{count} glands · {cost} jetons", lotLabel: "Lot de glands {count}", reset: "Recommencer cette manche", finished: "Marché terminé", resultTitle: "Toutes les demandes sont prêtes !", resultRound: "Un échange équitable !", next: "Demande suivante", settings: "Réglages", sound: "Son", language: "Langue", on: "Activé", off: "Désactivé", close: "Fermer", wrong: "Ce lot ne respecte pas un indice. Relis la demande et réessaie.", correct: "Un choix attentif ! La demande est prête.", selected: "Choix dans cette manche : {count}", resultText: "Demandes prêtes : {count} sur 3. Cette manche a demandé {picks} choix.", resultAll: "Les trois demandes sont prêtes. Minimum de choix au marché : {best}.", round1: "Le panier de l'écureuil", round2: "La lanterne du lapin", round3: "Le pique-nique de la loutre", request1: "L'écureuil veut exactement 3 glands et peut dépenser au plus 5 jetons.", request2: "Le lapin veut exactement 4 glands et peut dépenser au plus 6 jetons.", request3: "La loutre veut exactement 2 glands et peut dépenser au plus 7 jetons.", animal1: "Écureuil", animal2: "Lapin", animal3: "Loutre", hint1: "Compte avant d'enchérir", hint2: "La lanterne demande un panier plus rempli", hint3: "Petit lot, budget généreux"
    },
    de: {
      loading: "Der Eichelmarkt wird geöffnet…", title: "Eichel-Auktion", kicker: "Ein ruhiges Auswahlrätsel", world: "Mondheller Waldmarkt", intro: "Lies den Wunsch jedes Tieres und wähle das Eichellot, das zu Menge und Budget passt.", start: "Markt öffnen", choose: "Runde wählen", best: "Wenigste sorgfältige Auswahlen: {best}", rounds: "Marktrunden", marketRound: "Marktrunde", request: "Wunsch", prompt: "Wähle das Lot, das beide Hinweise erfüllt.", lot: "{count} Eicheln · {cost} Marken", lotLabel: "Eichellot {count}", reset: "Diese Runde neu starten", finished: "Markt geschafft", resultTitle: "Alle Wünsche sind bereit!", resultRound: "Ein fairer Tausch!", next: "Nächster Wunsch", settings: "Einstellungen", sound: "Ton", language: "Sprache", on: "An", off: "Aus", close: "Schließen", wrong: "Dieses Lot erfüllt einen Hinweis nicht. Lies den Wunsch noch einmal und versuche es erneut.", correct: "Eine sorgfältige Wahl! Der Wunsch ist bereit.", selected: "Auswahlen in dieser Runde: {count}", resultText: "Wünsche bereit: {count} von 3. Diese Runde brauchte {picks} Auswahlen.", resultAll: "Alle drei Wünsche sind bereit. Wenigste Marktauswahlen: {best}.", round1: "Das Körbchen des Eichhörnchens", round2: "Die Laterne des Kaninchens", round3: "Das Picknick des Otters", request1: "Das Eichhörnchen braucht genau 3 Eicheln und kann höchstens 5 Marken ausgeben.", request2: "Das Kaninchen braucht genau 4 Eicheln und kann höchstens 6 Marken ausgeben.", request3: "Der Otter braucht genau 2 Eicheln und kann höchstens 7 Marken ausgeben.", animal1: "Eichhörnchen", animal2: "Kaninchen", animal3: "Otter", hint1: "Vor dem Gebot zählen", hint2: "Die Laterne braucht ein volleres Körbchen", hint3: "Kleines Lot, großzügiges Budget"
    },
    it: {
      loading: "Apertura del mercato delle ghiande…", title: "Asta delle Ghiande", kicker: "Un tranquillo rompicapo di scelte", world: "Mercato del bosco al chiaro di luna", intro: "Leggi la richiesta di ogni animale e scegli il lotto di ghiande adatto per quantità e budget.", start: "Apri il mercato", choose: "Scegli il turno", best: "Meno scelte attente: {best}", rounds: "Turni del mercato", marketRound: "Turno del mercato", request: "Richiesta", prompt: "Scegli il lotto che rispetta entrambi gli indizi.", lot: "{count} ghiande · {cost} gettoni", lotLabel: "Lotto di ghiande {count}", reset: "Ricomincia questo turno", finished: "Mercato completato", resultTitle: "Tutte le richieste sono pronte!", resultRound: "Uno scambio equo!", next: "Richiesta successiva", settings: "Impostazioni", sound: "Suono", language: "Lingua", on: "Attivo", off: "Disattivo", close: "Chiudi", wrong: "Questo lotto non rispetta un indizio. Rileggi la richiesta e riprova.", correct: "Una scelta attenta! La richiesta è pronta.", selected: "Scelte in questo turno: {count}", resultText: "Richieste pronte: {count} su 3. Questo turno ha richiesto {picks} scelte.", resultAll: "Tutte e tre le richieste sono pronte. Meno scelte al mercato: {best}.", round1: "Il cestino dello scoiattolo", round2: "La lanterna del coniglio", round3: "Il picnic della lontra", request1: "Lo scoiattolo vuole esattamente 3 ghiande e può spendere al massimo 5 gettoni.", request2: "Il coniglio vuole esattamente 4 ghiande e può spendere al massimo 6 gettoni.", request3: "La lontra vuole esattamente 2 ghiande e può spendere al massimo 7 gettoni.", animal1: "Scoiattolo", animal2: "Coniglio", animal3: "Lontra", hint1: "Conta prima di fare un'offerta", hint2: "La lanterna vuole un cestino più pieno", hint3: "Lotto piccolo, budget generoso"
    },
    ru: {
      loading: "Открываем рынок желудей…", title: "Аукцион желудей", kicker: "Спокойная головоломка выбора", world: "Лесной рынок при луне", intro: "Прочитайте просьбу каждого животного и выберите лот желудей, подходящий по количеству и бюджету.", start: "Открыть рынок", choose: "Выбрать раунд", best: "Меньше всего обдуманных выборов: {best}", rounds: "Раунды рынка", marketRound: "Раунд рынка", request: "Просьба", prompt: "Выберите лот, который подходит по обоим признакам.", lot: "Желудей: {count} · жетонов: {cost}", lotLabel: "Лот желудей {count}", reset: "Начать этот раунд заново", finished: "Рынок завершён", resultTitle: "Все просьбы готовы!", resultRound: "Честный обмен!", next: "Следующая просьба", settings: "Настройки", sound: "Звук", language: "Язык", on: "Вкл.", off: "Выкл.", close: "Закрыть", wrong: "Этот лот не подходит по одному признаку. Перечитайте просьбу и попробуйте снова.", correct: "Внимательный выбор! Просьба выполнена.", selected: "Выборов в этом раунде: {count}", resultText: "Готово просьб: {count} из 3. В этом раунде выборов: {picks}.", resultAll: "Все три просьбы готовы. Меньше всего выборов на рынке: {best}.", round1: "Корзинка белки", round2: "Фонарь кролика", round3: "Пикник выдры", request1: "Белке нужно ровно 3 желудя, потратить можно не больше 5 жетонов.", request2: "Кролику нужно ровно 4 желудя, потратить можно не больше 6 жетонов.", request3: "Выдре нужно ровно 2 желудя, потратить можно не больше 7 жетонов.", animal1: "Белка", animal2: "Кролик", animal3: "Выдра", hint1: "Сосчитайте до ставки", hint2: "Фонарю нужна корзинка полнее", hint3: "Маленький лот, щедрый бюджет"
    },
    hi: {
      loading: "बलूत बाज़ार खुल रहा है…", title: "बलूत नीलामी", kicker: "शांत चुनाव वाली पहेली", world: "चाँदनी वन बाज़ार", intro: "हर जानवर की माँग पढ़ें और मात्रा व बजट दोनों से मेल खाने वाला बलूत चुनें।", start: "बाज़ार खोलें", choose: "राउंड चुनें", best: "सबसे कम सावधान चुनाव: {best}", rounds: "बाज़ार राउंड", marketRound: "बाज़ार राउंड", request: "माँग", prompt: "दोनों संकेतों से मेल खाने वाला लॉट चुनें।", lot: "{count} बलूत · {cost} टोकन", lotLabel: "बलूत लॉट {count}", reset: "यह राउंड फिर शुरू करें", finished: "बाज़ार पूरा", resultTitle: "हर माँग तैयार है!", resultRound: "न्यायपूर्ण अदला-बदली!", next: "अगली माँग", settings: "सेटिंग्स", sound: "ध्वनि", language: "भाषा", on: "चालू", off: "बंद", close: "बंद करें", wrong: "इस लॉट में एक संकेत नहीं मिलता। माँग फिर पढ़ें और दोबारा कोशिश करें।", correct: "सावधान चुनाव! माँग पूरी हुई।", selected: "इस राउंड के चुनाव: {count}", resultText: "तैयार माँग: 3 में से {count}। इस राउंड में {picks} चुनाव लगे।", resultAll: "तीनों माँग तैयार हैं। बाज़ार में सबसे कम चुनाव: {best}।", round1: "गिलहरी की टोकरी", round2: "खरगोश की लालटेन", round3: "ऊदबिलाव की पिकनिक", request1: "गिलहरी को ठीक 3 बलूत चाहिए और वह अधिकतम 5 टोकन खर्च कर सकती है।", request2: "खरगोश को ठीक 4 बलूत चाहिए और वह अधिकतम 6 टोकन खर्च कर सकता है।", request3: "ऊदबिलाव को ठीक 2 बलूत चाहिए और वह अधिकतम 7 टोकन खर्च कर सकता है।", animal1: "गिलहरी", animal2: "खरगोश", animal3: "ऊदबिलाव", hint1: "बोली से पहले गिनें", hint2: "लालटेन के लिए भरी टोकरी चाहिए", hint3: "छोटा लॉट, खुला बजट"
    },
    ar: {
      loading: "نفتح سوق البلوط…", title: "مزاد البلوط", kicker: "لغز اختيار هادئ", world: "سوق الغابة تحت ضوء القمر", intro: "اقرأ طلب كل حيوان، ثم اختر كمية البلوط التي تناسب العدد والميزانية معاً.", start: "افتح السوق", choose: "اختر جولة", best: "أقل اختيارات دقيقة: {best}", rounds: "جولات السوق", marketRound: "جولة السوق", request: "الطلب", prompt: "اختر الكمية التي تطابق الدليلين.", lot: "{count} من البلوط · {cost} من الرموز", lotLabel: "كمية البلوط {count}", reset: "ابدأ هذه الجولة من جديد", finished: "اكتمل السوق", resultTitle: "كل الطلبات جاهزة!", resultRound: "مبادلة عادلة!", next: "الطلب التالي", settings: "الإعدادات", sound: "الصوت", language: "اللغة", on: "تشغيل", off: "إيقاف", close: "إغلاق", wrong: "هذه الكمية لا تطابق دليلاً واحداً. اقرأ الطلب مرة أخرى وحاول من جديد.", correct: "اختيار دقيق! أصبح الطلب جاهزاً.", selected: "الاختيارات في هذه الجولة: {count}", resultText: "الطلبات الجاهزة: {count} من 3. احتاجت هذه الجولة إلى {picks} اختيارات.", resultAll: "أصبحت الطلبات الثلاثة جاهزة. أقل عدد من اختيارات السوق: {best}.", round1: "سلة السنجاب", round2: "فانوس الأرنب", round3: "نزهة ثعلب الماء", request1: "يحتاج السنجاب إلى 3 حبات بلوط بالضبط، ويمكنه إنفاق 5 رموز كحد أقصى.", request2: "يحتاج الأرنب إلى 4 حبات بلوط بالضبط، ويمكنه إنفاق 6 رموز كحد أقصى.", request3: "يحتاج ثعلب الماء إلى حبتَي بلوط بالضبط، ويمكنه إنفاق 7 رموز كحد أقصى.", animal1: "السنجاب", animal2: "الأرنب", animal3: "ثعلب الماء", hint1: "عدّ قبل المزايدة", hint2: "الفانوس يحتاج إلى سلة أكثر امتلاءً", hint3: "كمية صغيرة، ميزانية واسعة"
    }
  };
}());
