(function(){
"use strict";
const en={
  localeName:"English",loading:"Lighting the Starbell Carnival…",title:"Animal Carnival Claw",backLobby:"Back to WeightPlay",language:"Language",posterAlt:"Nori and Rux operating a teal carnival claw machine",eyebrow:"Starbell skill arcade",pitch:"Choose a charm, time the swaying claw, then steady the lift before three drops run out.",start:"Start Game",
  guideLabel:"Game guide",guideKicker:"WeightPlay Original Game Guide",guideTitle:"Turn every drop into a deliberate rescue",guideIntro:"Rux built thirty fair skill machines for Starbell Carnival. Nori needs your timing to retrieve the requested memory charms.",howTitle:"How to play",how1:"Drag the aiming reticle over a visible target charm.",how2:"Release or press Drop when the swaying claw lines up.",how3:"Drag against the load swing while it rises to protect the grip.",rulesTitle:"Rules and results",rulesText:"Each mission gives three free drops and shows every target, weight and grip need. Retrieve the complete target set to clear. No payment, random rarity or real prize is involved.",progressTitle:"Thirty carnival missions",progressText:"Six machines add bumpers, shelves, magnetic drift, fragile stacks and mixed championship layouts. Every clear unlocks the next authored mission.",tipsTitle:"Practical tips",tipsText:"Start with exposed light charms, watch the sway cone, and make small opposite corrections during the lift. A centered heavy charm needs more steadying than a light one.",saveTitle:"Save and privacy",saveText:"Unlocked missions, medals and cabinet charms stay only in this browser. No account, upload or personal information is required.",faqTitle:"FAQ",faq1q:"Is a grab random?",faq1a:"No. Position, timing, visible weight and your stabilization determine the result.",faq2q:"Can I lose collected charms?",faq2a:"No. Cabinet progress is permanent on this device.",faq3q:"What should I play next?",faq3a:"Try Animal Reef Fisher for another timing challenge or Animal Parking Patrol for careful planning.",
  backMain:"Back to Main",stageRailLabel:"Carnival mission selection",enter:"Enter Machine",cabinet:"Cabinet",workshop:"Workshop",workshopIntro:"Spend earned starbolts on permanent, transparent machine tuning.",stages:"Missions",stageTabs:"Stage tabs",backStages:"Back to Missions",drops:"Drops",grip:"Grip",targets:"Targets",boardLabel:"Aim and operate the carnival claw",stability:"Stability",drop:"Drop Claw",restart:"Restart",pause:"Pause",tutorialTitle:"Aim, drop, stabilize",tutorial1:"Drag the reticle over one requested charm.",tutorial2:"Drop when the swaying claw overlaps the target.",tutorial3:"During the lift, drag opposite the swing to keep grip above the line.",tutorialStart:"Start the machine",leaveTitle:"Leave this machine?",leaveText:"Continue keeps this exact drop frozen. Returning to Missions ends only this attempt.",continue:"Continue",returnStages:"Return to Missions",pauseTitle:"Machine paused",pauseText:"The rail, claw and prize bin are frozen.",resume:"Resume",resultKicker:"Carnival report",next:"Next Mission",retry:"Replay",
  progress:"{cleared} / 30 missions · {charms} / 8 charms",stageSummary:"{cleared} cleared · {bolts} starbolts",mission:"Mission {n}",locked:"Locked",ready:"Ready",cleared:"Cleared · {medal}",objective:"Collect {count} target charms",phaseAim:"Aim at a target, then release or press Drop.",phaseDrop:"Claw descending…",phaseLift:"Drag opposite the swing to stabilize the lift.",phaseReturn:"Returning to the rail…",caught:"Charm delivered!",miss:"The grip slipped. Choose a new angle.",wrong:"That charm was not requested, but it joined your cabinet.",winTitle:"Machine cleared!",failTitle:"Targets still in the bin",winText:"All requested charms reached the chute with {drops} drops left.",failText:"Study the visible weights and try a steadier lift.",newBest:"New best medal!",best:"Best: {medal}",none:"None yet",collected:"Collected",unknown:"Undiscovered",starbolts:"{n} starbolts",upgrade:"Upgrade",max:"MAX",needBolts:"Need more starbolts.",upgradeDone:"Machine tuning upgraded.",tuningGrip:"Grip lining",tuningGripText:"Widens the fair centered-grab window.",tuningStability:"Sway damper",tuningStabilityText:"Makes counter-steering more responsive.",tuningRail:"Rail guide",tuningRailText:"Slows aim drift before release.",
  chapter1:"Lantern Lane",chapter2:"Bubble Bumpers",chapter3:"Clockwork Shelves",chapter4:"Moon Magnet",chapter5:"Glass Garden",chapter6:"Star Crown",rule1:"Open bins teach position, sway timing and lift control.",rule2:"Rounded bumpers reward a clean approach angle.",rule3:"Moving shelves open short timing windows.",rule4:"Gentle magnetic drift demands counter-steering.",rule5:"Fragile stacks punish careless side contact.",rule6:"Championship layouts combine every fair machine rule.",
  prize1:"Leo charm",prize2:"Nori charm",prize3:"Fia charm",prize4:"Taro charm",prize5:"Orla charm",prize6:"Panko charm",prize7:"Rux charm",prize8:"Mimi charm"
};
Object.assign(en,{
  how3:"After a catch, press and hold Stabilize until the claw reaches the top.",
  tutorial3:"After a catch, press and hold Stabilize until the claw reaches the top.",
  phaseLift:"Caught! Hold Stabilize until the claw reaches the top.",
  holdGrip:"HOLD TO STABILIZE",
  holdAction:"CAUGHT! HOLD THE STABILIZE BUTTON BELOW",
  holdingAction:"STABILIZING — KEEP HOLDING",
  holdNeeded:"Press and hold Stabilize now. Releasing drains the grip.",
  holdingGood:"Good! Keep holding until the claw reaches the top.",
  dragLeftAction:"YOUR MOVE: HOLD + DRAG LEFT ←",
  dragRightAction:"YOUR MOVE: HOLD + DRAG RIGHT →",
  guideDeepTitle:"Read the machine before committing a drop",
  guideDeep1:"Every mission is a small spatial puzzle rather than a lottery. The target strip names the charms that matter, while the bin shows their exact locations and relative weights. Move the reticle slowly enough to compare the claw center with the target center. Nearby bumpers, shelves, and stacks are not decoration: they define the safe approach corridor. If the direct route is narrow, begin from the open side and let the visible sway carry the claw into alignment. Releasing at the same rail position can produce different contact when the sway direction differs, so watch both position and motion.",
  guideDeep2:"The lift is a second decision, not an automatic reward. Once a charm is held, its load swings beneath the claw. Drag against that movement with short corrections. Holding one direction too long creates a new swing and spends stability; alternating small inputs keeps the meter above the marked grip requirement. Light charms forgive wider motion, while heavy charms demand a centered grab and calmer lift. Workshop tuning changes the size or responsiveness of known windows, but never a hidden probability. A clear is always explainable from the same visible rules.",
  guideDeep3:"Three drops create a planning budget. A non-target charm can still enter the permanent cabinet, but it does not advance the current objective, so decide whether discovery is worth one attempt. Early missions isolate one lesson at a time. Later chapters combine moving shelves, magnetic drift, fragile neighbors, and mixed weights. When a layout feels crowded, identify the most constrained target first. Removing an exposed charm can also open a safer path to one below it. Failure leaves the authored layout understandable and replayable, making practice more useful than guessing.",
  guideDeep4:"Keyboard players can focus the machine, use the arrow keys to move the reticle, press Space or Enter to drop, and use left or right during the lift. Pointer and touch players use the same underlying controls by dragging and releasing. Pause freezes the complete attempt, and the protected back action asks before ending it. Result buttons always return to Missions first, then offer the next unlocked mission, then Replay. Progress, medals, cabinet discoveries, starbolts, and transparent tuning remain on this device only. Clearing browser storage resets them without affecting an account because no account is used.",
  counterLeft:"The charm swings right. Follow the player action shown above.",
  counterRight:"The charm swings left. Follow the player action shown above.",
  steadyGood:"Correct move! Keep holding until the claw reaches the top.",
  steadyWrong:"Wrong way — follow the player action shown above."
});
const zht={...en,localeName:"繁體中文",loading:"正在點亮星鈴嘉年華……",title:"動物嘉年華抓寶機",backLobby:"返回 WeightPlay",language:"語言",posterAlt:"諾里與魯克斯操作藍綠色嘉年華抓寶機",eyebrow:"星鈴技巧遊樂場",pitch:"選定收藏物、抓準擺動時機，再在三次機會用完前穩住上升中的爪子。",start:"開始遊戲",guideLabel:"遊戲指南",guideKicker:"WeightPlay 原創遊戲指南",guideTitle:"讓每一次抓取都有明確判斷",guideIntro:"魯克斯為星鈴嘉年華打造了三十台公平的技巧機台。諾里需要你的時機感取回指定回憶收藏物。",howTitle:"遊玩方式",how1:"拖曳瞄準標記到看得見的目標收藏物上。",how2:"擺動爪子對準時放開，或按下「放下爪子」。",how3:"上升時往載物擺動的反方向拖曳，維持抓力。",rulesTitle:"規則與結果",rulesText:"每關有三次免費抓取，所有目標、重量與抓力需求都會顯示。取回完整目標組即可過關，沒有付費、隨機稀有度或真實獎品。",progressTitle:"三十個嘉年華任務",progressText:"六台機器逐步加入彈墊、移動層架、磁力漂移、易碎堆疊與混合冠軍布局。每次過關都會解鎖下一個原創任務。",tipsTitle:"實用技巧",tipsText:"先抓外露的輕型收藏物，觀察擺動範圍，上升時做小幅反向修正。置中的重型收藏物需要更多穩定操作。",saveTitle:"儲存與隱私",saveText:"解鎖任務、獎章與收藏櫃只保存在這個瀏覽器，不需要帳號、上傳或個人資料。",faqTitle:"常見問題",faq1q:"抓取結果是隨機的嗎？",faq1a:"不是。位置、時機、可見重量與你的穩定操作共同決定結果。",faq2q:"已收藏的物品會消失嗎？",faq2a:"不會。這台裝置上的收藏櫃進度會永久保留。",faq3q:"接下來可以玩什麼？",faq3a:"想挑戰時機可玩《動物珊瑚礁釣手》，想仔細規劃可玩《森林停車疏導隊》。",backMain:"返回主畫面",stageRailLabel:"嘉年華任務選擇",enter:"進入機台",cabinet:"收藏櫃",workshop:"工坊",workshopIntro:"使用獲得的星栓，進行公開透明的永久機台調校。",stages:"任務",stageTabs:"關卡分頁",backStages:"返回任務",drops:"次數",grip:"抓力",targets:"目標",boardLabel:"瞄準並操作嘉年華爪子",stability:"穩定度",drop:"放下爪子",restart:"重新開始",pause:"暫停",tutorialTitle:"瞄準、放下、穩定",tutorial1:"把瞄準標記拖到一個指定收藏物上。",tutorial2:"擺動爪子與目標重疊時放下。",tutorial3:"上升時往擺動反方向拖曳，讓抓力維持在線上。",tutorialStart:"啟動機台",leaveTitle:"離開這台機器？",leaveText:"繼續會保留目前抓取狀態；返回任務只會結束這次挑戰。",continue:"繼續",returnStages:"返回任務",pauseTitle:"機台已暫停",pauseText:"軌道、爪子與獎品槽都已凍結。",resume:"繼續遊戲",resultKicker:"嘉年華報告",next:"下一任務",retry:"再玩一次",progress:"{cleared} / 30 任務 · {charms} / 8 收藏",stageSummary:"已完成 {cleared} · {bolts} 星栓",mission:"任務 {n}",locked:"未解鎖",ready:"可挑戰",cleared:"已完成 · {medal}",objective:"收集 {count} 個目標收藏",phaseAim:"瞄準目標，然後放開或按下「放下爪子」。",phaseDrop:"爪子下降中……",phaseLift:"往擺動反方向拖曳以穩定上升。",phaseReturn:"正在返回軌道……",caught:"收藏物已送達！",miss:"抓力滑落了，換個角度再試。",wrong:"這不是指定目標，但已加入收藏櫃。",winTitle:"機台完成！",failTitle:"目標仍留在槽中",winText:"所有指定收藏物都已送達，剩餘 {drops} 次抓取。",failText:"觀察可見重量，再嘗試更穩定的上升。",newBest:"新的最佳獎章！",best:"最佳：{medal}",none:"尚無",collected:"已收藏",unknown:"尚未發現",starbolts:"{n} 星栓",upgrade:"升級",max:"最高",needBolts:"星栓不足。",upgradeDone:"機台調校已升級。",tuningGrip:"爪墊",tuningGripText:"擴大公平的置中抓取範圍。",tuningStability:"擺動阻尼",tuningStabilityText:"讓反向穩定操作更靈敏。",tuningRail:"軌道導引",tuningRailText:"放下前減緩瞄準漂移。",chapter1:"燈籠街",chapter2:"泡泡彈墊",chapter3:"發條層架",chapter4:"月光磁環",chapter5:"玻璃花園",chapter6:"星冠機台",rule1:"開放槽教你位置、擺動時機與上升控制。",rule2:"圓形彈墊鼓勵乾淨的接近角度。",rule3:"移動層架會開啟短暫時機。",rule4:"溫和磁力漂移需要反向控制。",rule5:"易碎堆疊會懲罰粗心的側面碰撞。",rule6:"冠軍布局組合所有公平機台規則。",prize1:"里歐收藏",prize2:"諾里收藏",prize3:"菲亞收藏",prize4:"塔羅收藏",prize5:"奧拉收藏",prize6:"潘可收藏",prize7:"魯克斯收藏",prize8:"咪咪收藏"};
Object.assign(zht,{
  how3:"抓到後，按住「穩住」直到爪子升到頂端。",
  tutorial3:"抓到後，按住「穩住」直到爪子升到頂端。",
  phaseLift:"抓到了！按住「穩住」直到爪子升到頂端。",
  holdGrip:"按住穩住",
  holdAction:"抓到了！按住下方「穩住」",
  holdingAction:"穩定中——繼續按住",
  holdNeeded:"現在按住「穩住」；放開會失去抓力。",
  holdingGood:"做對了！繼續按住直到爪子升頂。",
  dragLeftAction:"你的操作：按住往左拖 ←",
  dragRightAction:"你的操作：按住往右拖 →",
  tutorial3:"抓到後再按住畫面，照箭頭向左或向右拖，讓抓力維持到爪子升頂。",
  phaseLift:"照箭頭往擺動反方向拖，保持到爪子升頂。",
  counterLeft:"吊飾往右擺；請照上方「你的操作」反向拖。",
  counterRight:"吊飾往左擺；請照上方「你的操作」反向拖。",
  steadyGood:"操作正確！繼續按住到爪子升到頂端。",
  steadyWrong:"拖反了；請改照上方「你的操作」方向。"
});
const zhs={...zht,localeName:"简体中文",loading:"正在点亮星铃嘉年华……",title:"动物嘉年华抓宝机",backLobby:"返回 WeightPlay",language:"语言",pitch:"选定收藏物、抓准摆动时机，再在三次机会用完前稳住上升中的爪子。",start:"开始游戏",guideLabel:"游戏指南",guideTitle:"让每一次抓取都有明确判断",howTitle:"游玩方式",rulesTitle:"规则与结果",progressTitle:"三十个嘉年华任务",tipsTitle:"实用技巧",saveTitle:"保存与隐私",faqTitle:"常见问题",backMain:"返回主画面",stageRailLabel:"嘉年华任务选择",enter:"进入机器",cabinet:"收藏柜",workshop:"工坊",stages:"任务",stageTabs:"关卡分页",backStages:"返回任务",drops:"次数",grip:"抓力",targets:"目标",stability:"稳定度",drop:"放下爪子",restart:"重新开始",pause:"暂停",tutorialTitle:"瞄准、放下、稳定",tutorialStart:"启动机器",leaveTitle:"离开这台机器？",continue:"继续",returnStages:"返回任务",pauseTitle:"机器已暂停",resume:"继续游戏",resultKicker:"嘉年华报告",next:"下一任务",retry:"再玩一次",mission:"任务 {n}",locked:"未解锁",ready:"可挑战",objective:"收集 {count} 个目标收藏",phaseAim:"瞄准目标，然后放开或按下“放下爪子”。",phaseDrop:"爪子下降中……",phaseLift:"往摆动反方向拖动以稳定上升。",phaseReturn:"正在返回轨道……",caught:"收藏物已送达！",miss:"抓力滑落了，换个角度再试。",winTitle:"机器完成！",failTitle:"目标仍留在槽中",newBest:"新的最佳奖章！",none:"尚无",collected:"已收藏",unknown:"尚未发现",upgrade:"升级",max:"最高",needBolts:"星栓不足。",upgradeDone:"机器调校已升级。",tuningGrip:"爪垫",tuningGripText:"扩大公平的置中抓取范围。",tuningStability:"摆动阻尼",tuningStabilityText:"让反向稳定操作更灵敏。",tuningRail:"轨道导引",tuningRailText:"放下前减缓瞄准漂移。",chapter1:"灯笼街",chapter2:"泡泡弹垫",chapter3:"发条层架",chapter4:"月光磁环",chapter5:"玻璃花园",chapter6:"星冠机器"};
const compact={
  ja:{localeName:"日本語",title:"アニマル・カーニバルクロー",loading:"スターべル・カーニバルを点灯中…",backLobby:"WeightPlayへ戻る",language:"言語",pitch:"チャームを選び、揺れるクローのタイミングを合わせ、3回以内に持ち上げを安定させよう。",start:"ゲーム開始",howTitle:"遊び方",rulesTitle:"ルールと結果",progressTitle:"30のカーニバルミッション",tipsTitle:"実用ヒント",saveTitle:"保存とプライバシー",faqTitle:"よくある質問",backMain:"メインへ戻る",enter:"マシンに入る",cabinet:"キャビネット",workshop:"工房",stages:"ミッション",backStages:"ミッションへ戻る",drops:"回数",grip:"グリップ",targets:"目標",stability:"安定度",drop:"クローを下ろす",restart:"リスタート",pause:"一時停止",tutorialTitle:"狙う・下ろす・安定",tutorialStart:"マシン開始",leaveTitle:"このマシンを離れますか？",continue:"続ける",returnStages:"ミッションへ",pauseTitle:"一時停止中",resume:"再開",resultKicker:"カーニバル報告",next:"次のミッション",retry:"リプレイ",mission:"ミッション {n}",locked:"ロック中",ready:"準備完了",objective:"目標チャームを {count} 個集める",phaseAim:"目標を狙い、離すかドロップを押します。",phaseDrop:"クロー下降中…",phaseLift:"揺れと反対へ動かして安定させよう。",phaseReturn:"レールへ戻っています…",caught:"チャーム獲得！",miss:"グリップが外れました。別の角度で試そう。",winTitle:"マシンクリア！",failTitle:"目標が残っています",newBest:"ベストメダル更新！",collected:"収集済み",unknown:"未発見",upgrade:"強化",max:"MAX",needBolts:"スターボルトが足りません。",upgradeDone:"マシンを強化しました。",chapter1:"ランタンレーン",chapter2:"バブルバンパー",chapter3:"クロックワーク棚",chapter4:"ムーンマグネット",chapter5:"ガラスガーデン",chapter6:"スタークラウン"},
  ko:{localeName:"한국어",title:"애니멀 카니발 클로",loading:"스타벨 카니발에 불을 켜는 중…",backLobby:"WeightPlay로 돌아가기",language:"언어",pitch:"장식을 고르고 흔들리는 집게의 때를 맞춘 뒤 세 번 안에 들어 올림을 안정시키세요.",start:"게임 시작",howTitle:"플레이 방법",rulesTitle:"규칙과 결과",progressTitle:"카니발 미션 30개",tipsTitle:"실전 팁",saveTitle:"저장과 개인정보",faqTitle:"자주 묻는 질문",backMain:"메인으로",enter:"기계 입장",cabinet:"진열장",workshop:"작업장",stages:"미션",backStages:"미션으로",drops:"횟수",grip:"그립",targets:"목표",stability:"안정도",drop:"집게 내리기",restart:"다시 시작",pause:"일시 정지",tutorialTitle:"조준, 내리기, 안정",tutorialStart:"기계 시작",leaveTitle:"이 기계를 나갈까요?",continue:"계속",returnStages:"미션으로",pauseTitle:"기계 일시 정지",resume:"계속하기",resultKicker:"카니발 보고서",next:"다음 미션",retry:"다시 플레이",mission:"미션 {n}",locked:"잠김",ready:"준비",objective:"목표 장식 {count}개 수집",phaseAim:"목표를 조준한 뒤 놓거나 내리기를 누르세요.",phaseDrop:"집게가 내려갑니다…",phaseLift:"흔들림 반대쪽으로 움직여 안정시키세요.",phaseReturn:"레일로 돌아가는 중…",caught:"장식 도착!",miss:"그립이 미끄러졌습니다. 다른 각도를 선택하세요.",winTitle:"기계 완료!",failTitle:"목표가 통에 남았습니다",newBest:"새 최고 메달!",collected:"수집함",unknown:"미발견",upgrade:"업그레이드",max:"최대",needBolts:"스타볼트가 부족합니다.",upgradeDone:"기계 조정을 강화했습니다.",chapter1:"랜턴 레인",chapter2:"버블 범퍼",chapter3:"태엽 선반",chapter4:"문 마그넷",chapter5:"유리 정원",chapter6:"스타 크라운"},
  es:{localeName:"Español",title:"Garra de Carnaval Animal",loading:"Encendiendo el Carnaval Estrella…",backLobby:"Volver a WeightPlay",language:"Idioma",pitch:"Elige un amuleto, calcula el balanceo y estabiliza la subida antes de gastar tres intentos.",start:"Comenzar",howTitle:"Cómo jugar",rulesTitle:"Reglas y resultados",progressTitle:"Treinta misiones de carnaval",tipsTitle:"Consejos prácticos",saveTitle:"Guardado y privacidad",faqTitle:"Preguntas frecuentes",backMain:"Volver al inicio",enter:"Entrar en la máquina",cabinet:"Vitrina",workshop:"Taller",stages:"Misiones",backStages:"Volver a Misiones",drops:"Intentos",grip:"Agarre",targets:"Objetivos",stability:"Estabilidad",drop:"Bajar garra",restart:"Reiniciar",pause:"Pausa",tutorialTitle:"Apunta, baja y estabiliza",tutorialStart:"Iniciar máquina",leaveTitle:"¿Salir de esta máquina?",continue:"Continuar",returnStages:"Volver a Misiones",pauseTitle:"Máquina en pausa",resume:"Reanudar",resultKicker:"Informe del carnaval",next:"Siguiente misión",retry:"Repetir",mission:"Misión {n}",locked:"Bloqueada",ready:"Lista",objective:"Recoge {count} amuletos objetivo",phaseAim:"Apunta a un objetivo y suelta o pulsa Bajar.",phaseDrop:"La garra está bajando…",phaseLift:"Arrastra contra el balanceo para estabilizar.",phaseReturn:"Volviendo al riel…",caught:"¡Amuleto entregado!",miss:"El agarre resbaló. Elige otro ángulo.",winTitle:"¡Máquina superada!",failTitle:"Quedan objetivos en la caja",newBest:"¡Nueva mejor medalla!",collected:"Conseguido",unknown:"Sin descubrir",upgrade:"Mejorar",max:"MÁX.",needBolts:"Faltan pernos estrella.",upgradeDone:"Ajuste de máquina mejorado.",chapter1:"Calle de Faroles",chapter2:"Topes Burbuja",chapter3:"Estantes Mecánicos",chapter4:"Imán Lunar",chapter5:"Jardín de Cristal",chapter6:"Corona Estelar"},
  "pt-BR":{localeName:"Português (Brasil)",title:"Garra do Carnaval Animal",loading:"Acendendo o Carnaval Estelar…",backLobby:"Voltar ao WeightPlay",language:"Idioma",pitch:"Escolha um amuleto, acerte o balanço e estabilize a subida antes de gastar três tentativas.",start:"Começar",howTitle:"Como jogar",rulesTitle:"Regras e resultados",progressTitle:"Trinta missões de carnaval",tipsTitle:"Dicas práticas",saveTitle:"Salvamento e privacidade",faqTitle:"Perguntas frequentes",backMain:"Voltar ao início",enter:"Entrar na máquina",cabinet:"Coleção",workshop:"Oficina",stages:"Missões",backStages:"Voltar às Missões",drops:"Tentativas",grip:"Pegada",targets:"Alvos",stability:"Estabilidade",drop:"Baixar garra",restart:"Reiniciar",pause:"Pausa",tutorialTitle:"Mire, baixe e estabilize",tutorialStart:"Ligar a máquina",leaveTitle:"Sair desta máquina?",continue:"Continuar",returnStages:"Voltar às Missões",pauseTitle:"Máquina pausada",resume:"Retomar",resultKicker:"Relatório do carnaval",next:"Próxima missão",retry:"Repetir",mission:"Missão {n}",locked:"Bloqueada",ready:"Pronta",objective:"Colete {count} amuletos-alvo",phaseAim:"Mire em um alvo e solte ou toque em Baixar.",phaseDrop:"A garra está descendo…",phaseLift:"Arraste contra o balanço para estabilizar.",phaseReturn:"Voltando ao trilho…",caught:"Amuleto entregue!",miss:"A pegada escapou. Tente outro ângulo.",winTitle:"Máquina concluída!",failTitle:"Ainda há alvos na caixa",newBest:"Nova melhor medalha!",collected:"Coletado",unknown:"Não descoberto",upgrade:"Melhorar",max:"MÁX.",needBolts:"Faltam parafusos estelares.",upgradeDone:"Ajuste melhorado.",chapter1:"Rua das Lanternas",chapter2:"Para-choques Bolha",chapter3:"Prateleiras Mecânicas",chapter4:"Ímã Lunar",chapter5:"Jardim de Vidro",chapter6:"Coroa Estelar"},
  fr:{localeName:"Français",title:"Griffe du Carnaval Animal",loading:"Illumination du Carnaval Étoilé…",backLobby:"Retour à WeightPlay",language:"Langue",pitch:"Choisissez un charme, visez pendant le balancement puis stabilisez la montée en trois essais.",start:"Commencer",howTitle:"Comment jouer",rulesTitle:"Règles et résultats",progressTitle:"Trente missions de carnaval",tipsTitle:"Conseils pratiques",saveTitle:"Sauvegarde et confidentialité",faqTitle:"FAQ",backMain:"Retour à l'accueil",enter:"Entrer dans la machine",cabinet:"Vitrine",workshop:"Atelier",stages:"Missions",backStages:"Retour aux missions",drops:"Essais",grip:"Prise",targets:"Cibles",stability:"Stabilité",drop:"Descendre la griffe",restart:"Recommencer",pause:"Pause",tutorialTitle:"Viser, descendre, stabiliser",tutorialStart:"Démarrer la machine",leaveTitle:"Quitter cette machine ?",continue:"Continuer",returnStages:"Retour aux missions",pauseTitle:"Machine en pause",resume:"Reprendre",resultKicker:"Rapport du carnaval",next:"Mission suivante",retry:"Rejouer",mission:"Mission {n}",locked:"Verrouillée",ready:"Prête",objective:"Récupérez {count} charmes cibles",phaseAim:"Visez une cible puis relâchez ou appuyez sur Descendre.",phaseDrop:"La griffe descend…",phaseLift:"Glissez à l'opposé du balancement pour stabiliser.",phaseReturn:"Retour vers le rail…",caught:"Charme livré !",miss:"La prise a glissé. Essayez un autre angle.",winTitle:"Machine terminée !",failTitle:"Des cibles restent dans le bac",newBest:"Nouvelle meilleure médaille !",collected:"Collecté",unknown:"Inconnu",upgrade:"Améliorer",max:"MAX",needBolts:"Pas assez de boulons-étoiles.",upgradeDone:"Réglage amélioré.",chapter1:"Allée des Lanternes",chapter2:"Pare-chocs Bulle",chapter3:"Étagères Mécaniques",chapter4:"Aimant Lunaire",chapter5:"Jardin de Verre",chapter6:"Couronne Stellaire"},
  de:{localeName:"Deutsch",title:"Tierische Jahrmarkt-Kralle",loading:"Der Sternenglocken-Jahrmarkt leuchtet auf…",backLobby:"Zurück zu WeightPlay",language:"Sprache",pitch:"Wähle einen Anhänger, nutze den Schwung und stabilisiere das Heben innerhalb von drei Versuchen.",start:"Spiel starten",howTitle:"Spielweise",rulesTitle:"Regeln und Ergebnis",progressTitle:"Dreißig Jahrmarkt-Missionen",tipsTitle:"Praktische Tipps",saveTitle:"Speichern und Datenschutz",faqTitle:"FAQ",backMain:"Zurück zum Hauptmenü",enter:"Maschine betreten",cabinet:"Vitrine",workshop:"Werkstatt",stages:"Missionen",backStages:"Zurück zu Missionen",drops:"Versuche",grip:"Griff",targets:"Ziele",stability:"Stabilität",drop:"Kralle senken",restart:"Neustart",pause:"Pause",tutorialTitle:"Zielen, senken, stabilisieren",tutorialStart:"Maschine starten",leaveTitle:"Diese Maschine verlassen?",continue:"Weiter",returnStages:"Zu den Missionen",pauseTitle:"Maschine pausiert",resume:"Fortsetzen",resultKicker:"Jahrmarktbericht",next:"Nächste Mission",retry:"Nochmal",mission:"Mission {n}",locked:"Gesperrt",ready:"Bereit",objective:"Sammle {count} Zielanhänger",phaseAim:"Ziele und lass los oder drücke Senken.",phaseDrop:"Die Kralle sinkt…",phaseLift:"Ziehe gegen den Schwung, um zu stabilisieren.",phaseReturn:"Rückkehr zur Schiene…",caught:"Anhänger geliefert!",miss:"Der Griff rutschte ab. Wähle einen anderen Winkel.",winTitle:"Maschine geschafft!",failTitle:"Ziele liegen noch im Behälter",newBest:"Neue Bestmedaille!",collected:"Gesammelt",unknown:"Unentdeckt",upgrade:"Verbessern",max:"MAX",needBolts:"Mehr Sternbolzen nötig.",upgradeDone:"Maschine verbessert.",chapter1:"Laternenweg",chapter2:"Blasenpuffer",chapter3:"Uhrwerkregale",chapter4:"Mondmagnet",chapter5:"Glasgarten",chapter6:"Sternenkrone"},
  it:{localeName:"Italiano",title:"Artiglio del Carnevale Animale",loading:"Accensione del Carnevale Stellato…",backLobby:"Torna a WeightPlay",language:"Lingua",pitch:"Scegli un ciondolo, calcola l'oscillazione e stabilizza la salita entro tre tentativi.",start:"Inizia",howTitle:"Come giocare",rulesTitle:"Regole e risultati",progressTitle:"Trenta missioni di carnevale",tipsTitle:"Consigli pratici",saveTitle:"Salvataggio e privacy",faqTitle:"FAQ",backMain:"Torna alla schermata principale",enter:"Entra nella macchina",cabinet:"Vetrina",workshop:"Officina",stages:"Missioni",backStages:"Torna alle missioni",drops:"Tentativi",grip:"Presa",targets:"Obiettivi",stability:"Stabilità",drop:"Abbassa artiglio",restart:"Ricomincia",pause:"Pausa",tutorialTitle:"Mira, abbassa, stabilizza",tutorialStart:"Avvia macchina",leaveTitle:"Uscire da questa macchina?",continue:"Continua",returnStages:"Torna alle missioni",pauseTitle:"Macchina in pausa",resume:"Riprendi",resultKicker:"Rapporto del carnevale",next:"Missione successiva",retry:"Rigioca",mission:"Missione {n}",locked:"Bloccata",ready:"Pronta",objective:"Raccogli {count} ciondoli obiettivo",phaseAim:"Mira a un obiettivo e rilascia o premi Abbassa.",phaseDrop:"L'artiglio scende…",phaseLift:"Trascina contro l'oscillazione per stabilizzare.",phaseReturn:"Ritorno al binario…",caught:"Ciondolo consegnato!",miss:"La presa è scivolata. Prova un'altra angolazione.",winTitle:"Macchina completata!",failTitle:"Restano obiettivi nel contenitore",newBest:"Nuova medaglia migliore!",collected:"Raccolto",unknown:"Da scoprire",upgrade:"Migliora",max:"MAX",needBolts:"Servono più bulloni stellari.",upgradeDone:"Regolazione migliorata.",chapter1:"Viale delle Lanterne",chapter2:"Paraurti Bolla",chapter3:"Scaffali Meccanici",chapter4:"Magnete Lunare",chapter5:"Giardino di Vetro",chapter6:"Corona Stellare"},
  ru:{localeName:"Русский",title:"Карнавальный зверо-кран",loading:"Зажигаем карнавал Звёздного Колокола…",backLobby:"Вернуться в WeightPlay",language:"Язык",pitch:"Выберите подвеску, поймайте момент качания и стабилизируйте подъём за три попытки.",start:"Начать игру",howTitle:"Как играть",rulesTitle:"Правила и результаты",progressTitle:"Тридцать карнавальных миссий",tipsTitle:"Полезные советы",saveTitle:"Сохранение и конфиденциальность",faqTitle:"Вопросы",backMain:"На главный экран",enter:"Войти в автомат",cabinet:"Витрина",workshop:"Мастерская",stages:"Миссии",backStages:"К миссиям",drops:"Попытки",grip:"Захват",targets:"Цели",stability:"Стабильность",drop:"Опустить кран",restart:"Заново",pause:"Пауза",tutorialTitle:"Цельтесь, опускайте, стабилизируйте",tutorialStart:"Запустить автомат",leaveTitle:"Покинуть автомат?",continue:"Продолжить",returnStages:"К миссиям",pauseTitle:"Автомат на паузе",resume:"Продолжить",resultKicker:"Отчёт карнавала",next:"Следующая миссия",retry:"Повторить",mission:"Миссия {n}",locked:"Закрыто",ready:"Готово",objective:"Соберите целей: {count}",phaseAim:"Наведитесь на цель и отпустите или нажмите «Опустить».",phaseDrop:"Кран опускается…",phaseLift:"Двигайте против качания для устойчивости.",phaseReturn:"Возвращаемся к рельсу…",caught:"Подвеска доставлена!",miss:"Захват сорвался. Выберите другой угол.",winTitle:"Автомат пройден!",failTitle:"Цели остались в контейнере",newBest:"Новая лучшая медаль!",collected:"Собрано",unknown:"Не найдено",upgrade:"Улучшить",max:"МАКС.",needBolts:"Нужно больше звёздных болтов.",upgradeDone:"Настройка улучшена.",chapter1:"Аллея фонарей",chapter2:"Пузырьковые бамперы",chapter3:"Часовые полки",chapter4:"Лунный магнит",chapter5:"Стеклянный сад",chapter6:"Звёздная корона"},
  hi:{localeName:"हिन्दी",title:"एनिमल कार्निवल क्लॉ",loading:"स्टारबेल कार्निवल रोशन हो रहा है…",backLobby:"WeightPlay पर वापस जाएँ",language:"भाषा",pitch:"चार्म चुनें, झूलते पंजे का समय साधें और तीन मौकों में उठान स्थिर रखें।",start:"खेल शुरू करें",howTitle:"कैसे खेलें",rulesTitle:"नियम और परिणाम",progressTitle:"तीस कार्निवल मिशन",tipsTitle:"काम के सुझाव",saveTitle:"सेव और गोपनीयता",faqTitle:"सामान्य प्रश्न",backMain:"मुख्य स्क्रीन पर",enter:"मशीन में जाएँ",cabinet:"संग्रह",workshop:"कार्यशाला",stages:"मिशन",backStages:"मिशन पर वापस",drops:"मौके",grip:"पकड़",targets:"लक्ष्य",stability:"स्थिरता",drop:"पंजा नीचे करें",restart:"फिर शुरू करें",pause:"रोकें",tutorialTitle:"निशाना, नीचे, स्थिर",tutorialStart:"मशीन शुरू करें",leaveTitle:"यह मशीन छोड़ें?",continue:"जारी रखें",returnStages:"मिशन पर वापस",pauseTitle:"मशीन रुकी है",resume:"फिर शुरू करें",resultKicker:"कार्निवल रिपोर्ट",next:"अगला मिशन",retry:"फिर खेलें",mission:"मिशन {n}",locked:"बंद",ready:"तैयार",objective:"{count} लक्ष्य चार्म जुटाएँ",phaseAim:"लक्ष्य पर निशाना लगाकर छोड़ें या नीचे दबाएँ।",phaseDrop:"पंजा नीचे जा रहा है…",phaseLift:"झूले की उलटी दिशा में खींचकर स्थिर करें।",phaseReturn:"रेल पर लौट रहा है…",caught:"चार्म पहुँच गया!",miss:"पकड़ फिसल गई। नया कोण चुनें।",winTitle:"मशीन पूरी!",failTitle:"लक्ष्य अभी डिब्बे में हैं",newBest:"नया सर्वश्रेष्ठ पदक!",collected:"मिल गया",unknown:"नहीं मिला",upgrade:"अपग्रेड",max:"अधिकतम",needBolts:"और स्टारबोल्ट चाहिए।",upgradeDone:"मशीन ट्यूनिंग बढ़ी।",chapter1:"लालटेन लेन",chapter2:"बबल बंपर",chapter3:"क्लॉकवर्क शेल्फ",chapter4:"मून मैग्नेट",chapter5:"ग्लास गार्डन",chapter6:"स्टार क्राउन"},
  ar:{localeName:"العربية",title:"مخلب كرنفال الحيوانات",loading:"جارٍ إضاءة كرنفال جرس النجوم…",backLobby:"العودة إلى WeightPlay",language:"اللغة",pitch:"اختر تعويذة واضبط توقيت المخلب المتأرجح ثم ثبّت الرفع خلال ثلاث محاولات.",start:"ابدأ اللعب",howTitle:"طريقة اللعب",rulesTitle:"القواعد والنتائج",progressTitle:"ثلاثون مهمة كرنفال",tipsTitle:"نصائح عملية",saveTitle:"الحفظ والخصوصية",faqTitle:"الأسئلة الشائعة",backMain:"العودة للرئيسية",enter:"ادخل الآلة",cabinet:"الخزانة",workshop:"الورشة",stages:"المهمات",backStages:"العودة للمهمات",drops:"المحاولات",grip:"القبضة",targets:"الأهداف",stability:"الثبات",drop:"أنزل المخلب",restart:"إعادة البدء",pause:"إيقاف مؤقت",tutorialTitle:"صوّب وأنزل وثبّت",tutorialStart:"شغّل الآلة",leaveTitle:"مغادرة هذه الآلة؟",continue:"متابعة",returnStages:"العودة للمهمات",pauseTitle:"الآلة متوقفة",resume:"استئناف",resultKicker:"تقرير الكرنفال",next:"المهمة التالية",retry:"إعادة",mission:"المهمة {n}",locked:"مغلق",ready:"جاهز",objective:"اجمع {count} تعويذات مطلوبة",phaseAim:"صوّب إلى هدف ثم أفلت أو اضغط إنزال.",phaseDrop:"المخلب يهبط…",phaseLift:"اسحب عكس التأرجح لتثبيت الرفع.",phaseReturn:"العودة إلى السكة…",caught:"وصلت التعويذة!",miss:"انزلقت القبضة. اختر زاوية أخرى.",winTitle:"اكتملت الآلة!",failTitle:"ما زالت أهداف في الحاوية",newBest:"أفضل ميدالية جديدة!",collected:"مجموع",unknown:"غير مكتشف",upgrade:"ترقية",max:"الأقصى",needBolts:"تحتاج إلى مسامير نجمية.",upgradeDone:"تم تحسين ضبط الآلة.",chapter1:"ممر الفوانيس",chapter2:"مصدات الفقاعات",chapter3:"رفوف الساعة",chapter4:"مغناطيس القمر",chapter5:"حديقة الزجاج",chapter6:"تاج النجوم"}
};
for(const [locale,values] of Object.entries(compact))compact[locale]={...en,...values};
const steerLabels={
  ja:{dragLeftAction:"操作：押したまま左へドラッグ ←",dragRightAction:"操作：押したまま右へドラッグ →"},
  ko:{dragLeftAction:"조작: 누른 채 왼쪽으로 드래그 ←",dragRightAction:"조작: 누른 채 오른쪽으로 드래그 →"},
  es:{dragLeftAction:"TU ACCIÓN: MANTÉN Y ARRASTRA A LA IZQUIERDA ←",dragRightAction:"TU ACCIÓN: MANTÉN Y ARRASTRA A LA DERECHA →"},
  "pt-BR":{dragLeftAction:"SUA AÇÃO: SEGURE E ARRASTE PARA A ESQUERDA ←",dragRightAction:"SUA AÇÃO: SEGURE E ARRASTE PARA A DIREITA →"},
  fr:{dragLeftAction:"À TOI : MAINTIENS ET GLISSE À GAUCHE ←",dragRightAction:"À TOI : MAINTIENS ET GLISSE À DROITE →"},
  de:{dragLeftAction:"DEINE AKTION: HALTEN UND NACH LINKS ZIEHEN ←",dragRightAction:"DEINE AKTION: HALTEN UND NACH RECHTS ZIEHEN →"},
  it:{dragLeftAction:"TOCCA A TE: TIENI E TRASCINA A SINISTRA ←",dragRightAction:"TOCCA A TE: TIENI E TRASCINA A DESTRA →"},
  ru:{dragLeftAction:"ТВОЁ ДЕЙСТВИЕ: УДЕРЖИВАЙ И ТЯНИ ВЛЕВО ←",dragRightAction:"ТВОЁ ДЕЙСТВИЕ: УДЕРЖИВАЙ И ТЯНИ ВПРАВО →"},
  hi:{dragLeftAction:"आपकी चाल: दबाकर बाएँ खींचें ←",dragRightAction:"आपकी चाल: दबाकर दाएँ खींचें →"},
  ar:{dragLeftAction:"حركتك: اضغط واسحب لليسار ←",dragRightAction:"حركتك: اضغط واسحب لليمين →"}
};
for(const [locale,values] of Object.entries(steerLabels))Object.assign(compact[locale],values);
const holdLabels={
  ja:{holdGrip:"押して安定",holdAction:"つかんだ！下の「安定」を押し続ける",holdingAction:"安定中—そのまま押し続ける",holdNeeded:"今すぐ「安定」を押し続けてください。離すとグリップが下がります。",holdingGood:"その調子！上まで押し続けてください。",phaseLift:"つかんだ！上まで「安定」を押し続けてください。"},
  ko:{holdGrip:"길게 눌러 안정",holdAction:"잡았다! 아래 안정 버튼을 길게 누르세요",holdingAction:"안정 중—계속 누르세요",holdNeeded:"지금 안정 버튼을 길게 누르세요. 놓으면 집게 힘이 줄어듭니다.",holdingGood:"좋아요! 꼭대기까지 계속 누르세요.",phaseLift:"잡았다! 꼭대기까지 안정 버튼을 길게 누르세요."},
  es:{holdGrip:"MANTÉN PARA ESTABILIZAR",holdAction:"¡ATRAPADO! MANTÉN EL BOTÓN ESTABILIZAR",holdingAction:"ESTABILIZANDO—SIGUE PULSANDO",holdNeeded:"Mantén pulsado Estabilizar ahora. Soltar reduce el agarre.",holdingGood:"¡Bien! Sigue pulsando hasta llegar arriba.",phaseLift:"¡Atrapado! Mantén Estabilizar hasta llegar arriba."},
  "pt-BR":{holdGrip:"SEGURE PARA ESTABILIZAR",holdAction:"PEGOU! SEGURE O BOTÃO ESTABILIZAR",holdingAction:"ESTABILIZANDO—CONTINUE SEGURANDO",holdNeeded:"Segure Estabilizar agora. Soltar reduz a firmeza.",holdingGood:"Boa! Continue segurando até chegar ao topo.",phaseLift:"Pegou! Segure Estabilizar até chegar ao topo."},
  fr:{holdGrip:"MAINTENIR POUR STABILISER",holdAction:"ATTRAPÉ ! MAINTIENS STABILISER",holdingAction:"STABILISATION—GARDE APPUYÉ",holdNeeded:"Maintiens Stabiliser maintenant. Relâcher réduit la prise.",holdingGood:"Bien ! Garde appuyé jusqu'en haut.",phaseLift:"Attrapé ! Maintiens Stabiliser jusqu'en haut."},
  de:{holdGrip:"HALTEN ZUM STABILISIEREN",holdAction:"GEFANGEN! STABILISIEREN GEDRÜCKT HALTEN",holdingAction:"STABILISIERT—WEITER HALTEN",holdNeeded:"Halte Stabilisieren jetzt gedrückt. Loslassen schwächt den Griff.",holdingGood:"Gut! Bis ganz oben weiter halten.",phaseLift:"Gefangen! Stabilisieren bis ganz oben gedrückt halten."},
  it:{holdGrip:"TIENI PER STABILIZZARE",holdAction:"PRESO! TIENI PREMUTO STABILIZZA",holdingAction:"STABILIZZAZIONE—CONTINUA A TENERE",holdNeeded:"Tieni premuto Stabilizza ora. Lasciare riduce la presa.",holdingGood:"Bene! Continua a tenere fino in cima.",phaseLift:"Preso! Tieni premuto Stabilizza fino in cima."},
  ru:{holdGrip:"УДЕРЖИВАЙ ДЛЯ СТАБИЛИЗАЦИИ",holdAction:"СХВАЧЕНО! УДЕРЖИВАЙ «СТАБИЛИЗИРОВАТЬ»",holdingAction:"СТАБИЛИЗАЦИЯ—НЕ ОТПУСКАЙ",holdNeeded:"Удерживай «Стабилизировать». Если отпустить, захват ослабнет.",holdingGood:"Хорошо! Не отпускай до самого верха.",phaseLift:"Схвачено! Удерживай «Стабилизировать» до самого верха."},
  hi:{holdGrip:"स्थिर करने के लिए दबाए रखें",holdAction:"पकड़ लिया! नीचे स्थिर बटन दबाए रखें",holdingAction:"स्थिर हो रहा है—दबाए रखें",holdNeeded:"अभी स्थिर बटन दबाए रखें। छोड़ने पर पकड़ घटेगी।",holdingGood:"अच्छा! ऊपर पहुँचने तक दबाए रखें।",phaseLift:"पकड़ लिया! ऊपर तक स्थिर बटन दबाए रखें।"},
  ar:{holdGrip:"اضغط مطولاً للتثبيت",holdAction:"تم الالتقاط! اضغط زر التثبيت بالأسفل",holdingAction:"جارٍ التثبيت—استمر بالضغط",holdNeeded:"اضغط زر التثبيت الآن. الإفلات يضعف القبضة.",holdingGood:"جيد! استمر بالضغط حتى الأعلى.",phaseLift:"تم الالتقاط! اضغط زر التثبيت حتى الأعلى."}
};
for(const [locale,values] of Object.entries(holdLabels))Object.assign(compact[locale],values);
Object.assign(zhs,{holdGrip:"按住稳住",holdAction:"抓到了！按住下方“稳住”",holdingAction:"稳定中——继续按住",holdNeeded:"现在按住“稳住”；松开会失去抓力。",holdingGood:"做对了！继续按住直到爪子升顶。",phaseLift:"抓到了！按住“稳住”直到爪子升到顶端。"});
window.CARNIVAL_CLAW_LOCALES={en,"zh-Hant":zht,"zh-Hans":zhs,...compact};
})();
