/* Internal prototype only. Grid art is temporary until the art gate. */
(() => {
  const $ = (id) => document.getElementById(id);
  const loadingPanel = $("loadingPanel");
  if (loadingPanel) {
    const hideLoading = () => { loadingPanel.hidden = true; loadingPanel.classList.add("hidden"); };
    if (document.readyState === "complete") hideLoading();
    else window.addEventListener("load", hideLoading, { once: true });
  }
  const canvas = $("arena");
  const ctx = canvas.getContext("2d");
  const cols = 12, rows = 7, cell = 72;
  const heroArt = new Image(); heroArt.src = "assets/animal-frost-maze-original-assets-v1.png";
  const drifterArt = heroArt;
  const berryArt = heroArt;
  const propArt = new Image(); propArt.src = "assets/animal-frost-maze-props.png";
  const state = { screen: "main", chapter: 1, room: 1, best: Number(localStorage.getItem("wp-frost-best") || 0), player: null, enemy: null, walls: new Set(), fruits: new Set(), facing: { x: 1, y: 0 }, moves: 0, ticks: 0, raf: 0 };
  const notifyAnalytics = (name, details = {}) => window.__wpFrostAnalytics?.record?.(name, details);
  const key = (x,y) => `${x},${y}`;
  const text = (value) => window.wpFiveText ? window.wpFiveText(value) : value;
  function show(name){state.screen=name;document.body.dataset.screen=name==="result"?"battle":name;cancelAnimationFrame(state.raf);const result=document.querySelector("#result-screen");document.querySelectorAll(".screen").forEach((el)=>{const isResult=el===result&&name==="result";const keepBattle=name==="result"&&el.id==="battle-screen";const on=isResult||keepBattle||el.dataset.screen===name;el.hidden=!on;el.classList.toggle("active",on)});if(name==="battle")result?.setAttribute("hidden","");if(name==="battle")state.raf=requestAnimationFrame(frame);}
  function stageCards(){$("stage-list").innerHTML=[1,2,3,4].map((n)=>`<button data-chapter="${n}">Chapter ${n}<br><small>${n===1?"first thaw":n===2?"split routes":n===3?"drifter pressure":"final melt"}</small></button>`).join("");$("stage-list").querySelectorAll("button").forEach((b)=>b.addEventListener("click",()=>startRoom(Number(b.dataset.chapter),1)));}
  function layoutFor(chapter, room) { const variant=(chapter-1)*4+room-1; const walls=new Set([key(3,1),key(3,2),key(3,3),key(5,3),key(6,3),key(8,2),key(8,3),key(8,4),key(4,5),key(5,5),key(7,5)]); const variants=[[2,2],[4,1],[6,4],[9,5],[2,5],[7,1],[9,2],[5,1]]; const extra=variants[variant%variants.length]; walls.add(key(extra[0],extra[1])); if(chapter>=2)walls.add(key(6,1)); if(chapter>=3)walls.add(key(9,4)); if(chapter===4)walls.add(key(1,2)); const candidates=[[2,1],[5,1],[7,2],[10,4],[2,4],[6,6],[9,6],[10,1],[1,1]]; const fruits=new Set(); candidates.forEach(([x,y],i)=>{if(!walls.has(key(x,y))&&i<5+(variant%3))fruits.add(key(x,y))}); return {walls,fruits,enemy:{x:10-(variant%3),y:1+(variant%2)}}; }
  function buildRoom(){const layout=layoutFor(state.chapter,state.room);state.player={x:1,y:5};state.enemy=layout.enemy;state.facing={x:1,y:0};state.moves=0;state.ticks=0;state.walls=layout.walls;state.fruits=layout.fruits;$(`room-label`).textContent=`Chapter ${state.chapter} · Room ${state.room} / 4`;$(`battle-status`).textContent="Arrows move. SPACE breaks ice; F builds a short wall.";updateLabels();}
  function startRoom(chapter=1,room=1){state.chapter=chapter;state.room=room;buildRoom();show("battle");}
  function updateLabels(){$("fruit-label").textContent=`Berries ${state.fruits.size}`;}
  function canMove(x,y){return x>=0&&x<cols&&y>=0&&y<rows&&!state.walls.has(key(x,y));}
  function move(dx,dy){if(state.screen!=="battle")return;state.facing={x:dx,y:dy};const nx=state.player.x+dx,ny=state.player.y+dy;if(canMove(nx,ny)){state.player.x=nx;state.player.y=ny;notifyAnalytics("first_move",{action:`move_${dx}_${dy}`});const collected=state.fruits.delete(key(nx,ny));if(collected)notifyAnalytics("berry_collected",{remaining_berries:state.fruits.size,collected_count:5-state.fruits.size});updateLabels();if(state.fruits.size===0){finish(true);return;}state.moves+=1;if(state.moves%8===0)enemyStep();}else $("battle-status").textContent="Ice wall ahead. Break it, then move through.";}
  function breakIce(){const p=state.player,nx=p.x+state.facing.x,ny=p.y+state.facing.y;if(state.walls.delete(key(nx,ny))){$("battle-status").textContent="Ice cracked open — route changed.";notifyAnalytics("first_edit",{action:"break"});}else $("battle-status").textContent="Nothing breakable in that direction.";}
  function buildIce(){const p=state.player,nx=p.x+state.facing.x,ny=p.y+state.facing.y;if(nx>0&&nx<cols-1&&ny>0&&ny<rows-1&&!state.walls.has(key(nx,ny))&&!state.fruits.has(key(nx,ny))&&!(state.enemy.x===nx&&state.enemy.y===ny)){$("battle-status").textContent="A new ice wall changed the drifter's route.";state.walls.add(key(nx,ny));notifyAnalytics("first_edit",{action:"build"});}else $("battle-status").textContent="That space cannot hold a new ice wall.";}
  function enemyStep(){const e=state.enemy,p=state.player;const options=[];if(Math.abs(p.x-e.x)>=Math.abs(p.y-e.y))options.push([Math.sign(p.x-e.x),0],[0,Math.sign(p.y-e.y)]);else options.push([0,Math.sign(p.y-e.y)],[Math.sign(p.x-e.x),0]);for(const [dx,dy] of options){if(canMove(e.x+dx,e.y+dy)){e.x+=dx;e.y+=dy;break;}}if(e.x===p.x&&e.y===p.y)finish(false);}
  function finish(win){if(win){state.best=Math.max(state.best,state.room+(state.chapter-1)*4);localStorage.setItem("wp-frost-best",String(state.best));}$("result-title").textContent=win?"Room clear":"Route blocked";$("result-copy").textContent=win?`All berries recovered in chapter ${state.chapter}, room ${state.room}.`:`The ice route needs another attempt.`;$("next").textContent=state.room>=4?"Replay Chapter":"Next Room";show("result");}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#061b2c";ctx.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){ctx.strokeStyle="#174c68";ctx.strokeRect(x*cell,y*cell,cell,cell);if(state.walls.has(key(x,y))){ctx.fillStyle="#6dd4e8";ctx.fillRect(x*cell+6,y*cell+6,cell-12,cell-12);ctx.fillStyle="#c8f7ff";ctx.fillRect(x*cell+18,y*cell+18,cell-36,5);if(propArt.complete&&propArt.naturalWidth)ctx.drawImage(propArt,0,0,500,650,x*cell+7,y*cell+5,cell-14,cell-10);}}state.fruits.forEach((v)=>{const [x,y]=v.split(",").map(Number);if(propArt.complete&&propArt.naturalWidth)ctx.drawImage(propArt,480,0,350,600,x*cell+12,y*cell+12,48,48);else if(berryArt.complete&&berryArt.naturalWidth)ctx.drawImage(berryArt,625,5,310,340,x*cell+12,y*cell+12,48,48);else{ctx.fillStyle="#ff8198";ctx.beginPath();ctx.arc(x*cell+36,y*cell+36,15,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ffd36b";ctx.fillRect(x*cell+30,y*cell+17,12,7);}});actor(state.enemy,drifterArt,"#d8f2ff","#176079",[25,760,570,500]);actor(state.player,heroArt,"#ffd36b","#24465b",[10,5,600,780]);ctx.fillStyle="#c5e0ea";ctx.font="bold 17px system-ui";ctx.fillText(text("BREAK THE ICE"),18,28);}
  function actor(o,art,body,ink,crop){ctx.save();ctx.translate(o.x*cell+36,o.y*cell+36);if(art.complete&&art.naturalWidth)ctx.drawImage(art,crop[0],crop[1],crop[2],crop[3],-28,-28,56,56);else{ctx.fillStyle=body;ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.fill();ctx.fillStyle=ink;ctx.fillRect(-13,-5,26,8);ctx.fillRect(-9,10,18,7);}ctx.restore();}
  function frame(){if(state.screen!=="battle")return;state.ticks++;draw();state.raf=requestAnimationFrame(frame);}
  const actions={up:()=>move(0,-1),down:()=>move(0,1),left:()=>move(-1,0),right:()=>move(1,0),break:breakIce,build:buildIce};
  window.addEventListener("keydown",(e)=>{const k=e.code;if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","KeyW","KeyA","KeyS","KeyD","Space","KeyF"].includes(k)){e.preventDefault();if(k==="Space")breakIce();else if(k==="KeyF")buildIce();else if(k==="ArrowUp"||k==="KeyW")move(0,-1);else if(k==="ArrowDown"||k==="KeyS")move(0,1);else if(k==="ArrowLeft"||k==="KeyA")move(-1,0);else move(1,0)}});document.querySelectorAll("[data-action]").forEach((b)=>b.addEventListener("pointerdown",()=>actions[b.dataset.action]()));
  $("start-game").addEventListener("click",()=>{show("stage");stageCards()});document.querySelectorAll("[data-back]").forEach((b)=>b.addEventListener("click",()=>show(b.dataset.back)));$("retry").addEventListener("click",()=>startRoom(state.chapter,state.room));$("next").addEventListener("click",()=>startRoom(state.chapter,state.room>=4?1:state.room+1));$("to-stages").addEventListener("click",()=>{show("stage");stageCards()});$("main-progress").textContent=`Best rooms: ${state.best}`;stageCards();buildRoom();draw();
})();
